### ISSUE TITLE
训练过程的阶段性验证加速

### ISSUE THREAD

**Issue by liuyijian** [PaddlePaddle/PaddleFormers#1032]
![image](https://tva1.sinaimg.cn/large/0081Kckwly1gkuxunvtnsj31jg08wwi4.jpg)

使用GPU训练时速度较快，但验证较慢，验证过程是跑在CPU上还是GPU上的，有没有办法提速

**Comment by haoyuying** [comment]
训练是多卡，验证是单卡，目前还没有支持多卡验证和预测的功能。
