### ISSUE TITLE
PaddleHub部署预训练模型, 内存泄漏

### ISSUE THREAD

**Issue by ViewWholeWorld** [PaddlePaddle/PaddleFormers#1039]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本： PaddleHub 2.0 beta, PaddlePaddle 2.0
2）系统环境：MacOS, Linux, Python3.7
- 复现信息
hub serving start -m deeplabv3p_xception65_humanseg --port 12315 --use_multiprocess --workers=8
以 serving 模式启动时, HTTP 请求结束后没有释放内存, 32G 内存很快被占满, 1.8版本也有此问题,
不以 serving 模式启动, 也有此问题

**Comment by T-baby** [comment]
https://github.com/PaddlePaddle/PaddleHub/issues/1030

你这个问题跟我遇到的很像。我估计也是因为自动调整了 batch_size。然后就再也不下降了。你试着控制最大的 batch_size，可以临时解决。

**Comment by ViewWholeWorld** [comment]
> #1030
> 
> 你这个问题跟我遇到的很像。我估计也是因为自动调整了 batch_size。然后就再也不下降了。你试着控制最大的 batch_size，可以临时解决。

启动命令里没看到有调整 batch size 的选项, 我用 http 请求预测, 每次只传入一张图片

**Comment by T-baby** [comment]
不知道是不是同一个问题，如果是的话。。等官方回复看看吧。

**Comment by haoyuying** [comment]
这个模型本身很大，如果不是非必要用serving,可以使用本地预测，batchsize调小。因为预测部分不支持多卡预测，所以大模型会出现这个问题。

**Comment by ViewWholeWorld** [comment]
> 这个模型本身很大，如果不是非必要用serving,可以使用本地预测，batchsize调小。因为预测部分不支持多卡预测，所以大模型会出现这个问题。

我是用 CPU 预测然后多进程启动的

**Comment by haoyuying** [comment]
建议更换小模型https://www.paddlepaddle.org.cn/hubdetail?name=humanseg_lite&en_category=ImageSegmentation和https://www.paddlepaddle.org.cn/hubdetail?name=humanseg_mobile&en_category=ImageSegmentation，精度也不错，之前我们跑deeplabv3p_xception65_humanseg是在gpu上跑的，在cpu上很慢。

**Comment by haoyuying** [comment]
建议更换小模型
https://www.paddlepaddle.org.cn/hubdetail?name=humanseg_lite&en_category=ImageSegmentation
和
https://www.paddlepaddle.org.cn/hubdetail?name=humanseg_mobile&en_category=ImageSegmentation
 精度也不错，之前我们跑deeplabv3p_xception65_humanseg是在gpu上跑的，在cpu上很慢。

**Comment by haoyuying** [comment]
serving在执行时，会占用一部分内存，等到程序完全结束后再释放，该内存在serving服务启动过程中可以重复使用。目前不支持在serving服务中就释放该内存。
