### ISSUE TITLE
关于PaddleHub Module参数中的processor兼容问题

### ISSUE THREAD

**Issue by FisherOuch** [PaddlePaddle/PaddleFormers#104]
您好，我在近期尝试使用 paddlehub.Module("lac") 进行词性分析时发现有processor参数，在windows下开启4进程时速度提升明显，但在centos下开启时似乎并没有什么效果。想要请问一下processor参数在centos环境下是否支持开启多进程，是否有其他方式可以较为显著地提升词性分析的速度？
我目前采用的是在保证句子不被切断的前提下将文章尽可能切割成500字符一下的分段，在分词结束后再重新拼接。如果开启多进程的话，更多分段和较少分段应该如何取舍呢？

**Comment by Steffy-zxf** [comment]
感谢反馈！这个processor不是多线程的含义，是指对module运行前后的数据处理。无论是windows还是linux，LAC目前暂时不支持多线程。可以尝试调用lac，利用gpu，加大batch_size，提升词性分析的速度。如下：
```python
results = lac.lexical_analysis(data=inputs, use_gpu=True, batch_size=10)
```

**Comment by FisherOuch** [comment]
感谢您的指点！因为没有找到 lexical_analysis 的代码部分所以一直不知道这部分该怎么处理。使用batch_size确实可以直接解决目前的问题！
