### ISSUE TITLE
tiny error in readme of sequence-labeling demo

### ISSUE THREAD

**Issue by nlp4whp** [PaddlePaddle/PaddleFormers#106]
feed_list in readme.md is:
```
feed_list = [
    inputs["input_ids"].name, inputs["position_ids"].name,
    inputs["segment_ids"].name, inputs["input_mask"].name, label.name
]
```

but in sequence_label.py:
```
feed_list = [
        inputs["input_ids"].name,
        inputs["position_ids"].name,
        inputs["segment_ids"].name,
        inputs["input_mask"].name,
    ]
```

maybe `label.name` in readme is a tiny mistake ? 
because I see  `self.dataset.get_labels()` will be run in `BaseReader`

**Comment by Steffy-zxf** [comment]
Thanks for your feedback! Yes, it's a mistake of the readme. We have modified it.

**Comment by nlp4whp** [comment]
> Thanks for your feedback! Yes, it's a mistake of the readme. We have modified it.

thank YOU, paddlepaddle helps me a lot.
