### ISSUE TITLE
HubServing能否部署在树莓派4b上？

### ISSUE THREAD

**Issue by mcflysj** [PaddlePaddle/PaddleFormers#1067]
**问题：**
打算将HubServing运行在树莓派4b上，但在安装paddlehub时就出现异常，似乎是在安装sentencepiece环节，请问是硬件层面不支持，还是软件配置不兼容？如果只是我配置异常，应如何调整？

**环境：**
硬件为树莓派4b，2GB内存；
操作系统为Raspberry Pi OS with desktop
安装了Python3.7.3
操作系统内核信息Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

**目标：**
将HubServing运行在树莓派4b里

**操作：**
1. 安装paddlehub，在命令行执行下述命令：
> pip3 install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple

2.运行过程中在Running setup.py bdist_wheel for sentencepiece卡了十多分钟后出现异常；

3.尝试手动安装sentencepiece，在https://pypi.org/project/sentencepiece/#files 查找相应的版本，没找到能支持armv7的；

4.到sentencepiece源码库https://github.com/google/sentencepiece 下载，用pip，c++编译，vcpkg三种方式均没安装成功。

**异常信息：**

操作2出现的异常信息，截取部分内容如下：

Package sentencepiece was not found in the pkg-config search path.
  Perhaps you should add the directory containing `sentencepiece.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'sentencepiece' found
  Failed to find sentencepiece pkg-config

  Failed building wheel for sentencepiece
  Running setup.py clean for sentencepiece
Failed to build sentencepiece
Installing collected packages: sentencepiece, paddlehub
  Running setup.py install for sentencepiece ... error
------------ 中间省略的其它信息 ---------------------
collect2: error: ld returned 1 exit status
    make[2]: *** [src/CMakeFiles/spm_normalize.dir/build.make:88: src/spm_normalize] Error 1
    make[1]: *** [CMakeFiles/Makefile2:215: src/CMakeFiles/spm_normalize.dir/all] Error 2
    make: *** [Makefile:152: all] Error 2
    [ 65%] Built target sentencepiece-static
    [ 67%] Linking CXX executable spm_export_vocab
    /usr/bin/ld: libsentencepiece.a(arena.cc.o): in function `google::protobuf::internal::ArenaImpl::Init()':
    arena.cc:(.text+0x8c8): undefined reference to `__atomic_fetch_add_8'
    collect2: error: ld returned 1 exit status
    make[2]: *** [src/CMakeFiles/spm_export_vocab.dir/build.make:86: src/spm_export_vocab] Error 1
    make[1]: *** [CMakeFiles/Makefile2:103: src/CMakeFiles/spm_export_vocab.dir/all] Error 2
    make: *** [Makefile:152: all] Error 2
    Package sentencepiece was not found in the pkg-config search path.
    Perhaps you should add the directory containing `sentencepiece.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'sentencepiece' found
    Failed to find sentencepiece pkg-config
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-zbobydfa/sentencepiece/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1kl0_k70/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-zbobydfa/sentencepiece/

**Comment by ZeyuChen** [comment]
能否了解下你具体要使用哪个模型部署到树莓派上？

**Comment by mcflysj** [comment]
> 能否了解下你具体要使用哪个模型部署到树莓派上？

打算使用识别模型，但在第一步的“准备环境”就出现异常了，还没开始第二步的“下载推理模型”。

**Comment by mcflysj** [comment]
![image](https://user-images.githubusercontent.com/3817470/101583899-6fd7bb00-3a17-11eb-99e1-e97bcf24a57c.png)
看来暂时是不支持了～
感谢飞桨团队提供这么好的平台
