### ISSUE TITLE
多标签文本分类问题

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleFormers#1078]
官网上关于使用自定义数据集进行多标签文本分类  描述不是很清楚   我使用 ernie_tiny模型 自定义数据集一直报错  找不到为什么   请问能否提供一个 paddlehub  多标签文本分类 使用自定义数据集 的例子

**Comment by KPatr1ck** [comment]
想问下你用的paddlepaddle和paddlehub的版本分别是多少，如果可以的话把脚本和报错也发出来看一下。
如果是1.8，可以参考`PaddleHub/docs/tutorial/how_to_finetune.md`这个[文档](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/how_to_finetune.md#%E5%8A%A0%E8%BD%BD%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86)，加载自定义的文本分类数据集。

**Comment by wa3926** [comment]
用的是1.8  网上搜索 加载reader的写法 后来发现1.8 已经不需要了  
"Input is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers."
ValueError: Input is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.

之前一直这个错  get_train_examples() 这个写可以打印出数据      get_train_records() 这样写一直报错   后来无意间发现有一条数据 是空的   已经好了

**Comment by wa3926** [comment]
已经解决了
