### ISSUE TITLE
not authorized `hub' @ error/constitute.c/WriteImage/1028. after install paddle and paddlehub

### ISSUE THREAD

**Issue by github2016-yuan** [PaddlePaddle/PaddleFormers#1088]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
I have installed paddle successfully with cmds like this:
 
**python -m pip install paddlepaddle-gpu==2.0.0rc0 -i https://mirror.baidu.com/pypi/simple**
 
**and then I test it with:**
import paddle.fluid as fluid 
fluid.install_check.run_check()
 
**Soon I get messages below**:
Running Verify Fluid Program ... 
W1204 11:07:18.746273 11193 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 11.0, Runtime API Version: 10.1
W1204 11:07:18.827904 11193 device_context.cc:346] device: 0, cuDNN Version: 7.6.
Your Paddle Fluid works well on SINGLE GPU or CPU.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
 
**Then** I continue to install paddlehub with :
 
**pip install paddlehub==2.0.0b**
 
After a few time I get info **below**:
 
Installing collected packages: paddlehub
Successfully installed paddlehub-2.0.0b0
 
 
Next I input with:
import paddlehub
 
but I got error like this:
import: not authorized `paddlehub' @ error/constitute.c/WriteImage/1028.
 
environment is :
 
Ubuntu16.04 64bit
1080Ti
Driver Version: 450.57
cuda10.1
cudnn7.6
python3.7
 
 
I have reinstalled  many times and still cannot solve it.
Any advice will be appreciated.

**Comment by haoyuying** [comment]
first , uninstall paddle and paddle hub:
pip uninstall paddlepaddle-gpu 
pip uninstall paddle hub

then, install paddle and paddlehub like this:

pip install paddlepaddle-gpu==2.0.0rc
pip install paddlehub==2.0.0b1

good luck

**Comment by github2016-yuan** [comment]
Solve it. Need to get into python environmet before using "import paddlehub"
