### ISSUE TITLE
paddle模型库中是否有已经训练好的VGG模型可以直接拿来做预测

### ISSUE THREAD

**Issue by Overtown** [PaddlePaddle/PaddleFormers#111]
如题，请问paddle模型仓库中是否有已经训练好的VGG，可以用来直接做预测或者用于特征提取？如有，请告知下地址，个人没有找到。

**Comment by Steffy-zxf** [comment]
可以看我们的官网 https://www.paddlepaddle.org.cn/hub
其中 图像分类 和 特征提取 类目里面都有vgg module
https://www.paddlepaddle.org.cn/hubdetail?name=vgg19_imagenet&en_category=ImageClassification

https://www.paddlepaddle.org.cn/hubdetail?name=vgg19_imagenet&en_category=FeatureExtraction

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddleHub的支持!
