### ISSUE TITLE
W1212 20:26:32.475172  4256 analysis_predictor.cc:1042] Deprecated. Please use CreatePredictor instead.

### ISSUE THREAD

**Issue by Jeremy-ttt** [PaddlePaddle/PaddleFormers#1115]
这要怎么解决啊

**Comment by haoyuying** [comment]
请给出具体的模型和环境，方便我们复现问题。

**Comment by yuyuko233** [comment]
animegan_v2_hayao_99也出现了这个问题

**Comment by haoyuying** [comment]
这个是warning吧，如果是报错请给出完整的报错信息和运行环境。

**Comment by yuyuko233** [comment]
> 
> 
> 这个是warning吧，如果是报错请给出完整的报错信息和运行环境。

![图片](https://user-images.githubusercontent.com/20128226/102304155-bb4e1400-3f97-11eb-9cf4-154b4b941399.png)

报出这个之后直接退出程序

**Comment by haoyuying** [comment]
您好，这个不是个报错信息，由于animegan_v2_hayao_99的模型之前是用1.8版本的hub和1.8版本的paddle写的，现在适配到2.0的hub和2.0的paddle会有一些老的op的提示信息，但是不影响输出结果，用以下脚本运行，在output文件夹下可以看到输出结果。具体使用方法可以参见https://www.paddlepaddle.org.cn/hubdetail?name=animegan_v2_hayao_99&en_category=GANs

import cv2
import paddlehub as hub

model = hub.Module(name='animegan_v2_hayao_99', use_gpu=False)

result = model.style_transfer(images=[cv2.imread('/PATH/TO/IMAGE')], visualization=True)
