### ISSUE TITLE
无法安装module

### ISSUE THREAD

**Issue by tychobraheastro** [PaddlePaddle/PaddleFormers#112]
![20190808181715](https://user-images.githubusercontent.com/48246743/62695532-1c132700-ba09-11e9-98d8-fb1e77ae3fa4.jpg)
![20190808181657](https://user-images.githubusercontent.com/48246743/62695545-1f0e1780-ba09-11e9-8b9f-f6ca6c4379cb.jpg)

无法安装module，搜到也装不了。外网能连，paddle-gpu和hub都是最新的。

**Comment by Steffy-zxf** [comment]
这个bug, 我们正在修复，可以先尝试指定version，如：
```python
module=hub.Module(name="ernie", version="1.0.2")
```

**Comment by tychobraheastro** [comment]
感谢，问题解决了
