### ISSUE TITLE
Fine-tune模型转换为PaddleHub Module后使用PaddleHub Serving调用，本地系统重启后PaddleHub提示找不到模型

### ISSUE THREAD

**Issue by lastrei** [PaddlePaddle/PaddleFormers#1124]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：
paddlehub                1.8.3
paddlepaddle             2.0.0rc0
2）系统环境：请您描述系统类型:
windows
python版本3.73
- 复现信息：
- 使用erine预训练模型进行文本分类任务的fine-tuning后的模型，按照范例转换为paddleHub 模型
然后使用hub install的方式进行安装，然后使用hub serving start的方式启动服务，这里都没有问题，
在一次windows更新升级造成重启后，我再次使用hub serving start的方式启动服务，这时候提示我
找不到已经安装的模型，请问这个是否是因为模型默认安装的位置是cache目录下的原因？如果是请问
如何更改模型的安装位置及启动服务时如果指定模型位置，如不是，请问如何解决这种状况？谢谢！

**Comment by KPatr1ck** [comment]
你好，你可以在python控制台里，通过打印`paddlehub.common.dir.MODULE_HOME`来查看当前的模型安装目录。
```python
from paddlehub.common.dir import MODULE_HOME
print(MODULE_HOME)
```

此外，如果需要更改模型安装的位置的话，需要配置系统的环境变量'HUB_HOME'为你指定的目录，具体的目录读取逻辑可以看[此处](https://github.com/PaddlePaddle/PaddleHub/blob/f8910d0c9de61d63cc300074f0e3d9f6c01bbe0a/paddlehub/common/dir.py#L24)。

**Comment by lastrei** [comment]
感谢，打印之后显示model_home
C:\Users\usr\.paddlehub\modules 这个应该不存在会重启之后丢失的问题，我先更改一下hub_home的地址好了，谢谢
