### ISSUE TITLE
使用ERNIE_TINY 进行新闻标题分类训练，然后用hub封装模型后使用提示 The length of input_text is out of handling, which must be 1 or 2!

### ISSUE THREAD

**Issue by Simba9980** [PaddlePaddle/PaddleFormers#1159]
`
版本
   python 3.7
   PaddlePaddle 2.0.0rc
   paddlehub-1.8.3
`
`
错误截图
   ![image](https://user-images.githubusercontent.com/26837690/103405748-20f2f080-4b93-11eb-8091-4f8ed1d2fec2.png)
`
`
模型的module.py
![image](https://user-images.githubusercontent.com/26837690/103405834-89da6880-4b93-11eb-9f9e-6852f4d48e30.png)
![image](https://user-images.githubusercontent.com/26837690/103405849-965ec100-4b93-11eb-842a-a3fd98306a77.png)
运行测试用的test.py
![image](https://user-images.githubusercontent.com/26837690/103405860-ab3b5480-4b93-11eb-99e9-a8aab88c6a3a.png)
   `

**Comment by xct-xct** [comment]
> `版本 python 3.7 PaddlePaddle 2.0.0rc paddlehub-1.8.3`
> `错误截图 ![image](https://user-images.githubusercontent.com/26837690/103405748-20f2f080-4b93-11eb-8091-4f8ed1d2fec2.png)`
> `模型的module.py ![image](https://user-images.githubusercontent.com/26837690/103405834-89da6880-4b93-11eb-9f9e-6852f4d48e30.png) ![image](https://user-images.githubusercontent.com/26837690/103405849-965ec100-4b93-11eb-842a-a3fd98306a77.png) 运行测试用的test.py ![image](https://user-images.githubusercontent.com/26837690/103405860-ab3b5480-4b93-11eb-99e9-a8aab88c6a3a.png)`

data数据换用这种格式试一下：
`{
	"data":[["国籍保障公民基本权利票"]]
}`

**Comment by Simba9980** [comment]
data = [["小米11镇压全场，友商黯然失色！堪称雷军扬眉吐气的封神之作"]]
data = {"data":[["小米11镇压全场，友商黯然失色！堪称雷军扬眉吐气的封神之作"]]}
data = ["小米11镇压全场，友商黯然失色！堪称雷军扬眉吐气的封神之作"]
这三种都试了，还是不行，提示一样的错误

**Comment by KPatr1ck** [comment]
module的组网和预测接口可以参考paddlehub1.8的文本分类finetune的demo
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/demo/text_classification/finetuned_model_to_module/module.py

多类别的文本分类可以参考的另一个demo
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.8/demo/multi_label_classification

在paddlehub 2.0.0rc会整合成一个文本分类，建议升级到paddlehub2.0的动态图版本使用~

**Comment by Simba9980** [comment]
好的，我现在先测试一下

**Comment by Simba9980** [comment]
目前我在自定义训练集的时候发现还是有问题，训练报错了，提示
InvalidArgumentError: The sample number of reader's input data and the input number of feed list are not equal.
Possible reasons are:
  The generator is decorated by `paddle.batch` and configured by `set_batch_generator`, but here need to used `set_sample_list_generator`.

我的环境配置是：python 3.7 PaddlePaddle 2.0.0rc paddlehub-2.0.0rc
我的训练脚本是：
![image](https://user-images.githubusercontent.com/26837690/103536198-07bcad80-4ecd-11eb-8eab-72153b4379dc.png)
![image](https://user-images.githubusercontent.com/26837690/103536224-13a86f80-4ecd-11eb-81b1-b35c3b7d1924.png)
![image](https://user-images.githubusercontent.com/26837690/103536234-1905ba00-4ecd-11eb-830c-ed55a5668299.png)

我的训练集样式：
![image](https://user-images.githubusercontent.com/26837690/103536277-2d49b700-4ecd-11eb-88a5-2defe20528aa.png)

执行训练后提示：
![image](https://user-images.githubusercontent.com/26837690/103536324-46526800-4ecd-11eb-9d54-d4b22be873bc.png)

**Comment by KPatr1ck** [comment]
你好，paddlehub 2.0.0rc版本已经发布，文本分类任务建议更新到最新版本使用
以下是相关的教程：
- [添加自定义文本分类数据集](https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.0.0-rc/docs/docs_ch/tutorial/how_to_load_data.md#%E5%9B%9B%E6%96%87%E6%9C%AC%E5%88%86%E7%B1%BB%E6%95%B0%E6%8D%AE%E9%9B%86)
-  [paddlehub2.0版本文本分类demo](https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0.0-rc/demo/text_classification)

**Comment by Simba9980** [comment]
十分感谢,目前已经成功训练完成模型,不过这个模型怎么打包成为hub serving呢?
