### ISSUE TITLE
predict.py代码疑问

### ISSUE THREAD

**Issue by YUTianGong** [PaddlePaddle/PaddleFormers#116]
在predict.py的第47行有dataset = hub.dataset.ChnSentiCorp()，那在其他的任务中，请问加载的是自己的数据还是这个ChnSentiCorp数据，如果是自己的那加载的是训练数据还是测试数据呢？谢谢大佬解答一下！

**Comment by Steffy-zxf** [comment]
感谢反馈！您上面提到的“其他任务”是什么任务呢？PaddleHub 文本分类demo中predict.py 用于预测的数据集是 所选数据集的dev部分的前3个数据。
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.1.0/demo/text-classification/predict.py#L153

**Comment by YUTianGong** [comment]
就是用示例代码做其他数据的文本分类任务，在predict.py的第47行有“dataset = hub.dataset.ChnSentiCorp()”，这个“dataset”在自己的分类数据中是指什么数据呢？还是继续用“dataset = hub.dataset.ChnSentiCorp()”？

**Comment by Steffy-zxf** [comment]
hub.dataset.ChnSentiCorp() 有三个部分：train，dev，test部分。文本分类demo中 predict.py中预测数据就是 这个数据集的dev部分前三个数据。如果您想替换为自定义数据，可以将自定义数据加载进来，直接用于预测，参考以下写法：
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.0.0/demo/text-classification/predict.py

如果想利用PaddleHub finetune自定义数据集做文本分类，可以参考
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E9%80%82%E9%85%8D%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E5%AE%8C%E6%88%90FineTune

**Comment by YUTianGong** [comment]
@Steffy-zxf 好的，谢谢你，我试试自定义的方法。
