### ISSUE TITLE
PaddleHub 关键点检测不能用gpu预测

### ISSUE THREAD

**Issue by CHENBIN99** [PaddlePaddle/PaddleFormers#1174]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub 1.8.3 PaddlePaddle 1.8.5
2）win10  Python 3.7.9

调用paddlehub中关键点检测模型human_pose_estimation_resnet50_mpii，使用keypoint_detection进行预测的时候，不能使用**use_gpu**预测，报错提示**AttributeError: 'HumanPoseEstimation' object has no attribute 'gpu_predictor'**

根据官网上的说明，API的参数中是有use_gpu这个选项
`
def keypoint_detection(self,
                       images=None,
                       paths=None,
                       batch_size=1,
                       use_gpu=False,
                       output_dir='output_pose',
                       visualization=False)
`

所以想问一下这个函数怎样才能使用gpu进行预测

**Comment by yeyupiaoling** [comment]
@ANDNEWHERE 我刚才试了一下，环境跟你一样，是正确的。我的CUDA版本是10.0，我的PaddlePaddle版本是1.8.5.post107
安装模型
```
hub install human_pose_estimation_resnet50_mpii==1.1.1
```

执行预测：
```
hub run human_pose_estimation_resnet50_mpii --input_path test.jpg
```

**Comment by yeyupiaoling** [comment]
@ANDNEWHERE 上面回答不算数，我忘了开GPU了。

**Comment by yeyupiaoling** [comment]
@ANDNEWHERE 要用GPU的话，命令应该这：
```
CUDA_VISIBLE_DEVICES=0 hub run human_pose_estimation_resnet50_mpii --input_path test.jpg --use_gpu=True
```

**Comment by CHENBIN99** [comment]
> @ANDNEWHERE要用GPU的话，命令应该这：
> 
> ```
> CUDA_VISIBLE_DEVICES=0 hub run human_pose_estimation_resnet50_mpii --input_path test.jpg --use_gpu=True
> ```

用python代码可以调用gpu吗

**Comment by yeyupiaoling** [comment]
@ANDNEWHERE 

```python
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '0'
import paddlehub as hub

detector = hub.Module(name="human_pose_estimation_resnet50_mpii")

result = detector.keypoint_detection(paths=['test.jpg'], use_gpu=True)
print(result)

```

**Comment by CHENBIN99** [comment]
> > @ANDNEWHERE要用GPU的话，命令应该这：
> > ```
> > CUDA_VISIBLE_DEVICES=0 hub run human_pose_estimation_resnet50_mpii --input_path test.jpg --use_gpu=True
> > ```
> 
> 用python代码可以调用gpu吗

> @ANDNEWHERE
> 
> ```python
> import os
> 
> os.environ['CUDA_VISIBLE_DEVICES'] = '0'
> import paddlehub as hub
> 
> detector = hub.Module(name="human_pose_estimation_resnet50_mpii")
> 
> result = detector.keypoint_detection(paths=['test.jpg'], use_gpu=True)
> print(result)
> ```

十分感谢，我可以调用gpu了！

**Comment by iwanglei1** [comment]
Could not locate zlibwapi.dll. Please make sure it is in your library path!
