### ISSUE TITLE
建议修改 import paddlehub  访问网络的特性

### ISSUE THREAD

**Issue by chaosfish** [PaddlePaddle/PaddleFormers#118]
因部署关系 ，希望能在运行时可以不依赖于网络是否通畅。

希望能解决以下两个场景使用问题：
1.有时候跑单元测试也会因为网络不好，造成测试用例失败。
2.在下载过相关的PaddleHub中的预训练模型和预置数据集，可以不依赖于网络运行。

**Comment by Steffy-zxf** [comment]
感谢反馈！PaddleHub 最新版本1.1.1现已支持离线运行。可以先卸载之前的PaddleHub，安装最新版1.1.1 PaddleHub。

**Comment by chaosfish** [comment]
感谢！ 已验证1.1.1版本可离线运行。
