### ISSUE TITLE
paddlehub无法使用多gpu训练

### ISSUE THREAD

**Issue by jane96** [PaddlePaddle/PaddleFormers#1181]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.8.5，PaddlePaddle1.8.1
2）系统环境：请您描述系统类型：Linux centos7.7，python3.7
- 复现信息：使用paddlehub进行ernie训练，想使用多个gpu，因为我服务器上有八块gpu。
- 1. 指定 os.environ['CUDA_VISIBLE_DEVICES']="0,,1,2,3,4,5,6,7"
- 2.在RunConfig中设置： use_cuda=True,use_data_parallel=True
- 发现始终只会使用第一块显卡，其他的都未使用。
![1](https://user-images.githubusercontent.com/16450829/104318862-f736b380-551a-11eb-97f0-ffc9169a30a6.jpg)

**Comment by jane96** [comment]
已解决

**Comment by lixiaosa2** [comment]
遇到同样的问题，想请问下当时您是怎么解决的？

**Comment by hjj-lmx** [comment]
> 已解决

怎么解决的
