### ISSUE TITLE
服务端部署完毕以后，能否返回base64编码格式的识别图片？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleFormers#1186]
https://www.paddlepaddle.org.cn/hub/scene/ocr
官网这里上传图片进行OCR以后，会返回识别以后用红框标注的base64编码的图片。我在本地部署以后，返回的只有识别结果，没有base64编码的图片

**Comment by ShenYuhan** [comment]
这里需要改动源码，我们下次升级的时候会考虑增加返回编码后的图片

**Comment by ghost** [comment]
好的，谢谢！
