### ISSUE TITLE
paddlehub 口罩检测pyramidbox_lite_mobile_face_detection如何使用gpu，以及如何将hub改成识别一个视频流而不是单张图片

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleFormers#1189]
paddlehub 口罩检测pyramidbox_lite_mobile_face_detection如何使用gpu，以及如何将hub改成识别一个视频流而不是单张图片

**Comment by haoyuying** [comment]
执行 CUDA_VISIBLE_DEVICES=0 python predict.py， 其中predict.py为：

```
import paddlehub as hub
import cv2

face_detector = hub.Module(name="pyramidbox_lite_mobile")
result = face_detector.face_detection(images=[cv2.imread('/PATH/TO/IMAGE')], use_gpu=True)
```
视频流预测需要用户自己搭建外部的代码，将视频拆成单帧，并且将得到的结果串成视频，可以参考https://www.paddlepaddle.org.cn/hubdetail?name=humanseg_server&en_category=ImageSegmentation
处理视频的方式。

**Comment by Sunyingbin** [comment]
> 执行 CUDA_VISIBLE_DEVICES=0 python predict.py， 其中predict.py为：
> 
> ```
> import paddlehub as hub
> import cv2
> 
> face_detector = hub.Module(name="pyramidbox_lite_mobile")
> result = face_detector.face_detection(images=[cv2.imread('/PATH/TO/IMAGE')], use_gpu=True)
> ```
> 
> 视频流预测需要用户自己搭建外部的代码，将视频拆成单帧，并且将得到的结果串成视频，可以参考https://www.paddlepaddle.org.cn/hubdetail?name=humanseg_server&en_category=ImageSegmentation
> 处理视频的方式。
我尝试了增加参数use_gpu=True好像不好用，results不返回任何值

**Comment by haoyuying** [comment]
请给出测试图片，方便我们复现。请问是很多图片结果都出现了这个问题还是有几张出现了这个问题。模型会出现漏检的问题，如果是少部分图片，这是比较正常的。

**Comment by Sunyingbin** [comment]
我尝试识别一个视频流，卡住了，识别一张图片也是这样的效果，result没有返回任何值，把use_gpu=True去掉就好用了

**Comment by haoyuying** [comment]
我试了用gpu的方式，没有复现您的问题，是否是您的一张单独的图片出现了漏检的问题导致的呢，若不是，请提供照片方便复现问题。
![image](https://user-images.githubusercontent.com/35907364/104569736-05f0a800-568c-11eb-93af-10a225fd9b2f.png)

**Comment by Sunyingbin** [comment]
> 我试了用gpu的方式，没有复现您的问题，是否是您的一张单独的图片出现了漏检的问题导致的呢，若不是，请提供照片方便复现问题。
> ![image](https://user-images.githubusercontent.com/35907364/104569736-05f0a800-568c-11eb-93af-10a225fd9b2f.png)

跟照片没有关系，我是视频流rtsp，我用paddleDetection的python部署方式用gpu是好用的，不会是版本问题吧。。。。

**Comment by haoyuying** [comment]
目前该模型不提供视频流处理的方式，如果不满足您对模型的需求，需要修改模型源码增加该功能，如果您将视频流功能接入成功，我们非常欢迎您将代码贡献给我们。

**Comment by Sunyingbin** [comment]
> 目前该模型不提供视频流处理的方式，如果不满足您对模型的需求，需要修改模型源码增加该功能，如果您将视频流功能接入成功，我们非常欢迎您将代码贡献给我们。

我意思就是result = face_detector.face_detection(images=[cv2.imread('/PATH/TO/IMAGE')], use_gpu=True)这么写不行就得写成result = face_detector.face_detection(images=[cv2.imread('/PATH/TO/IMAGE')])这样，use_gpu不好用啊。
我就把这个预测外面自己写一个视频流的循环播放预测不就行吗，不需要修改源码增加该功能啊，我现在问题就是为啥这个use_gpu不好用呢，是就我不好用吗，你是好用的是吗

**Comment by haoyuying** [comment]
我是好用的，我贴的图用了gpu

**Comment by haoyuying** [comment]
```
import paddlehub as hub
import cv2

face_detector = hub.Module(name="pyramidbox_lite_mobile")
result = face_detector.face_detection(images=[cv2.imread('old.jpg')], use_gpu=True)
print(result)
```
![image](https://user-images.githubusercontent.com/35907364/104572683-f2930c00-568e-11eb-91b2-27003d159606.png)
脚本和图片给你。

**Comment by Sunyingbin** [comment]
> 我是好用的，我贴的图用了gpu

哦哦，你的paddlehub和paddlepaddle版本是多少呢

**Comment by haoyuying** [comment]
paddlepaddle-gpu 2.0.0rc0
paddlehub 2.0.0b2

**Comment by haoyuying** [comment]
pyramidbox_lite_mobile 1.2.0
paddlepaddle-gpu 2.0.0rc0
paddlehub 2.0.0b2

**Comment by Sunyingbin** [comment]
> pyramidbox_lite_mobile 1.2.0
> paddlepaddle-gpu 2.0.0rc0
> paddlehub 2.0.0b2

pyramidbox_lite_mobile 1.2.0
paddlepaddle-gpu 1.8.5
paddlehub 1.8.3

**Comment by Sunyingbin** [comment]
请问我该如何升级呢

**Comment by haoyuying** [comment]
pip install paddlepaddle-gpu==2.0.0rc0
pip install paddlehub=2.0.0b2

**Comment by haoyuying** [comment]
pip install paddlepaddle-gpu==2.0.0rc0
pip install paddlehub==2.0.0b2

**Comment by Sunyingbin** [comment]
> > pyramidbox_lite_mobile 1.2.0
> > paddlepaddle-gpu 2.0.0rc0
> > paddlehub 2.0.0b2

你好，我改成跟你一样的版本了，报了这个问题
D:\anaconda3\envs\deploy\lib\site-packages\pip\_vendor\packaging\version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
[2021-01-15 10:06:22,604] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object

**Comment by haoyuying** [comment]
这个不影像结果，是个warning。

**Comment by haoyuying** [comment]
这个不影响结果，是个warning。

**Comment by Sunyingbin** [comment]
> 这个不影响结果，是个warning。

但是程序不运行了啊，连结果都不返回了。
