### ISSUE TITLE
paddlehub label是如何添加上的

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleFormers#1190]
你好，我看了一下，paddlehub的那个代码，返回的results里有label属性，但是在processor里面没有看到属性赋值

**Comment by haoyuying** [comment]
请问是什么模型呢？

**Comment by Sunyingbin** [comment]
pyramidbox_lite_mobile_mask

> 请问是什么模型呢？

**Comment by haoyuying** [comment]
通过网络得到有无mask置信度结果，选择置信度高的作为label，具体可以参见https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0.0-rc/modules/image/face_detection/pyramidbox_lite_mobile_mask
在processor.py里有具体的添加label的流程。

**Comment by Sunyingbin** [comment]
> 通过网络得到有无mask置信度结果，选择置信度高的作为label，具体可以参见https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0.0-rc/modules/image/face_detection/pyramidbox_lite_mobile_mask
> 在processor.py里有具体的添加label的流程。

好的，非常感谢
