### ISSUE TITLE
请问有没有动态图预发布模型转hub模型的示例,我这边想把模型转成hub模型后使用hub serving

### ISSUE THREAD

**Issue by Simba9980** [PaddlePaddle/PaddleFormers#1195]
当前已经训练完成了动态图的预发布模型，但是现在一直没有找到关于动态图预发布模型转hub模型的样例，用老的版本教程是提示报错的

**Comment by haoyuying** [comment]
是想把paddle的动态图模型转换成hub的模型是吗，可以参考教程https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.0.0-rc/docs/docs_ch/tutorial/contri_pretrained_model.md
按照参照代码进行仿写https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0.0-rc/modules/image/keypoint_detection/openpose_body_estimation

**Comment by Simba9980** [comment]
请问有没有关于文本处理方面的示例呢?这个图片的看起来```有难度,还没研究过

**Comment by haoyuying** [comment]
参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.0.0-rc/docs/docs_ch/contribution/contri_pretrained_model.md
