### ISSUE TITLE
word2vec模型如何使用

### ISSUE THREAD

**Issue by stopit** [PaddlePaddle/PaddleFormers#120]
想直接利用hub.Module(name="word2vec_skipgram")拿到word2vec的模型直接使用，但是没找到demo。能否补充一下这块。

现在的测试代码是这样的，但是运行会报错：

import paddlehub as hub

module = hub.Module(name="word2vec_skipgram")
inputs, outputs, program = module.context(trainable=False)

word_ids = inputs["word_ids"]
embedding = outputs["word_embs"]
print(embedding[1123])

**Comment by Steffy-zxf** [comment]
感谢反馈！根据您以上的测试代码，embedding = outputs["word_embs"]，embedding是paddle的Variable，无法直接print相应的值。需要通过fluid.Executor.run方法，指定fetch_list取出相应的值。
可以尝试如下代码：

```python
import paddle.fluid as fluid 
import paddlehub as hub
import numpy as np

module = hub.Module(name="word2vec_skipgram")
inputs, outputs, program = module.context(trainable=False)
word_ids = inputs["word_ids"]
embedding = outputs["word_embs"]

place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
feeder = fluid.DataFeeder(feed_list=[word_ids], place=place)
w2v, = exe.run(program, feed=feeder.feed([[[1123]]]), fetch_list=[embedding.name], return_numpy=False)

print(np.array(w2v))
```

关于word2vec的demo，我们更新后第一时间通知您。同时，想了解下您想利用word2vec具体做什么任务呢？

**Comment by stopit** [comment]
感谢回复~  主要是需要拿到词向量后做后续的nlp任务，想看看paddle训练出来的vec效果怎么样。由于训练集太少，也可能会用bert之类的模型做迁移。目前在看paddle的相关信息，看看paddle是否符合我们的项目，但是现在发现demo和社区环境可能都不是非常地成熟。。

**Comment by Steffy-zxf** [comment]
方便告知下具体是什么nlp任务吗？我们可以考虑参考您的任务用word2vec做一个demo。

**Comment by stopit** [comment]
主要任务时文章的相似度检测，大概的算法思路是这样的：
（1）jieba或lac分词   
（2）构造tf-idf提取关键字（jieba可以直接提取关键字，lac中还没找到相关的方法）  
（3）由于样本数量较少，选用预训练的word2vec模型做关键字向量化  
（4）计算每篇文章各个关键字的词向量加权和   
（5）根据每个文章关键词向量加权和之间的距离判断相似度

**Comment by Steffy-zxf** [comment]
好的，了解了。您可以参考我的第一条回复取到对应的word embedding。

**Comment by stopit** [comment]
目前paddle是否有相关群组供大家进行交流哈~~

**Comment by Steffy-zxf** [comment]
飞桨PaddlePaddle 交流群：432676488（QQ群）
飞桨 ERNIE交流群：760439550（QQ群）

**Comment by Steffy-zxf** [comment]
@stopit 根据您上次的回复，我们做了一版简易版本的文本相似度计算（利用word2vec） ，您可以参考以下链接
https://github.com/PaddlePaddle/PaddleHub/blob/develop/demo/sentence_similarity/sensim.py

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。

**Comment by yokings** [comment]
新版本的word2vec是不是api改了，demo运行不出来了
