### ISSUE TITLE
No module named 'paddle'

### ISSUE THREAD

**Issue by liweigu** [PaddlePaddle/PaddleFormers#1207]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
PaddlePaddle-gpu 2.0.0rc 或 2.0.0rc0 或 2.0.0rc1
PaddleHub 2.0.0rc0
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

先安装paddlepaddle-gpu，
`python -m pip install paddlepaddle-gpu==2.0.0rc -f https://paddlepaddle.org.cn/whl/stable.html -i https://mirror.baidu.com/pypi/simple`
（或 ==2.0.0rc0，或 ==2.0.0rc1，或 ==2.0.0rc1.post100，或 ==2.0.0rc1.post110）
再安装hub
`pip3 install paddlehub==2.0.0rc0 -i https://mirror.baidu.com/pypi/simple`
之后执行 hub install chinese_ocr_db_crnn_server==1.1.1 时报错：

Traceback (most recent call last):
  File "/usr/local/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/usr/local/lib/python3.8/dist-packages/paddlehub/__init__.py", line 24, in <module>
    from paddlehub import datasets
  File "/usr/local/lib/python3.8/dist-packages/paddlehub/datasets/__init__.py", line 15, in <module>
    from paddlehub.datasets.canvas import Canvas
  File "/usr/local/lib/python3.8/dist-packages/paddlehub/datasets/canvas.py", line 19, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'

另外如果执行 python3 ，然后
>>> import paddle
>>> paddle.utils.run_check()
都是正常的，返回信息有“PaddlePaddle is installed successfully!”。

hub install 的报错该怎么解决呢？

**Comment by haoyuying** [comment]
您可以单独试下
```
import paddle
import paddlehub
```
如果报错，建议卸载后重装paddle及paddlehub，我怀疑您3.8的python和paddle的版本不对应，安装位置混乱导致的。

**Comment by liweigu** [comment]
测试结果：
>>> import paddle
>>> import paddlehub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'paddlehub'

我的python是3.7.6，需要改成3.8.x版本吗？

另外我是自建docker的，因此每次测试都是新安装的。

**Comment by liweigu** [comment]
使用python 3.8就能用了。
