### ISSUE TITLE
安装后使用会出现KeyError: 'version'的报错

### ISSUE THREAD

**Issue by ScottishFold007** [PaddlePaddle/PaddleFormers#121]
![image](https://user-images.githubusercontent.com/36957508/63205709-f3f78800-c0da-11e9-958e-ddd540bfb925.png)

**Comment by Steffy-zxf** [comment]
感谢反馈！初步怀疑是lac module没有安装正确导致，可以尝试先卸载lac，重新安装lac，如：
```shell

$ hub uninstall lac
$ hub install lac

# 正常结果可以看到 lac module 的 ModuleName，Version等信息
$ hub show lac
 
```

**Comment by ScottishFold007** [comment]
谢谢！但是按您的指导，还是出现了这个问题：
![image](https://user-images.githubusercontent.com/36957508/63223995-863d8000-c1f0-11e9-96bf-d211f89d382e.png)

**Comment by Steffy-zxf** [comment]
截图看看
C:\Users\gaochangkuan\\.paddlehub\modules\lac\下有哪些文件

截图完之后，试试把C:\Users\gaochangkuan\\.paddlehub\modules\lac\删除，重新安装lac，
看看这样是否会有问题

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
