### ISSUE TITLE
hub install 从本地文件安装模型

### ISSUE THREAD

**Issue by liweigu** [PaddlePaddle/PaddleFormers#1216]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
以 hub install chinese_ocr_db_crnn_server 为例，安装模型时需要联网，如果预先下载了模型文件，能不能支持从本地模型文件安装？

- 什么样的场景下需要该特性？
离线场景下需要。

- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
目前没有找到替代方法。
如果是用CPU，应该可以预先制作docker镜像，在镜像里预先安装模型。但使用GPU时，无论是 docker build 还是 nvidia-docker build 编译镜像，在 hub install 或 hub download 时都会提示错误信息：
/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py:293: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default. 
（我还没找到在 docker build 时使用GPU的方法）

- 增加该特性，PaddleHub可能需要变化的部分。
需要支持命令类似于 hub install xxxx.tar 或 hub install [模型名] --from xxxx.tar

- 如果可以的话，简要描述下您的解决方案
方案一：支持指定本地模型文件路径进行安装；
方案二：说明在线安装时的模型文件下载路径，如果在该路径下已存在模型文件，则不再下载。

**Comment by KPatr1ck** [comment]
你好，hub install目前是可以支持本地目录或者压缩文件安装的，hub install + 本地路径/本地压缩文件即可。
另外在制作docker镜像时提示的是warning，不影响功能，但是hub install的返回值1被shell当成执行失败了，之后发包更新后会修复该问题。可以先忽略hub命令的返回值，这样制作镜像的时候就不会因此被中断。例如：
```shell
hub install ernie_tiny; exit 0
```

**Comment by liweigu** [comment]
这两种方法都可行。谢谢~
