### ISSUE TITLE
about face recognition 

### ISSUE THREAD

**Issue by zgsxwsdxg** [PaddlePaddle/PaddleFormers#1217]
感谢paddle的技术工作者辛苦的技术开发，我想问下paddlehub中是否会加入一些关于人脸识别的model，期待您的答复，谢谢！

**Comment by haoyuying** [comment]
您好，请问您的人脸识别的需求是什么呢，我们的模型库中有人脸检测相关的模型供您选择，比如https://www.paddlepaddle.org.cn/hubdetail?name=ultra_light_fast_generic_face_detector_1mb_640&en_category=FaceDetection

**Comment by zgsxwsdxg** [comment]
> 您好，请问您的人脸识别的需求是什么呢，我们的模型库中有人脸检测相关的模型供您选择，比如https://www.paddlepaddle.org.cn/hubdetail?name=ultra_light_fast_generic_face_detector_1mb_640&en_category=FaceDetection

就是说检测完人脸了，有没有用来做人脸特征提取的model可以用来做人脸识别，聚类等

**Comment by zgsxwsdxg** [comment]
> 您好，请问您的人脸识别的需求是什么呢，我们的模型库中有人脸检测相关的模型供您选择，比如https://www.paddlepaddle.org.cn/hubdetail?name=ultra_light_fast_generic_face_detector_1mb_640&en_category=FaceDetection

比如cosface 、arcface等

**Comment by haoyuying** [comment]
您好，目前还没有这个排期，如果您能为开源社区贡献模型，我们将非常感谢，欢迎给我们提pr。
