### ISSUE TITLE
paddlehub2.0rc0 无法使用 ddparser

### ISSUE THREAD

**Issue by paopjian** [PaddlePaddle/PaddleFormers#1219]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddlePaddle 2.0.0rc, paddlehub2.0.0rc0
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：
- 使用https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0.0-rc/modules/text/syntactic_analysis/DDParser 代码,无法下载ddparse module,有版本限制
问题如下:
paddlehub.module.manager.EnvironmentMismatchError: ddparser cannot be installed because some conditions are not met:
+---------------+----------+-----------------------------------+-----------------------------------+
|     Name      | Version  |   PaddlePaddle Version Required   |    PaddleHub Version Required     |
+---------------+----------+-----------------------------------+-----------------------------------+
|   ddparser    |  1.0.0   |    >=1.8.0, <=1.9.9(Mismatch)     |              >=1.7.0              |
+---------------+----------+-----------------------------------+-----------------------------------+

**Comment by haoyuying** [comment]
您好，目前该模型还不支持paddlehub2.0版本，请安装paddlehub 1.8版本进行体验。
ip install paddlehub==1.8.3

**Comment by haoyuying** [comment]
您好，目前该模型还不支持paddlehub2.0版本，请安装paddlehub 1.8版本进行体验。
pip install paddlehub==1.8.3

**Comment by paopjian** [comment]
那为什么出现在了2.0.0的module里?

**Comment by haoyuying** [comment]
是这样的，2.0的分支下面包含了hub之前所有的模型，该模型中存在一部分静态图api无法迁移到动态图版本，因此这个模型目前还只能使用1.x的paddlehub。
