### ISSUE TITLE
目前PaddlePaddle所有系列版本+PaddleHub 均无法使用ERNIE-GEN

### ISSUE THREAD

**Issue by uuleaf** [PaddlePaddle/PaddleFormers#1221]
PaddlePaddle 1.8.0~2.0.0  + PaddleHub 1.7~2.0.0rc0 ，经过**穷举安装**，均无法安装成功ERNIE-GEN

**系统环境**
- python3.8 ubuntu 18.04 
- aistudio 以及 paddle:2.0.0-gpu-cuda10.2-cudnn7、paddle:2.0.0-gpu-cuda10.2-cudnn7、paddle:1.8.5-gpu-cuda10.0-cudnn7 三个docker均试过
- paddle-ernie 所有dev版本均试过
- ernie_gen 所有版本均试过

**安装步骤**

> !pip install --upgrade paddlehub
!pip install paddle-ernie
!hub install ernie_gen==1.0.2

> ubuntu@ubuntu:~$ pip3 list | grep paddle
paddle-ernie                 0.1.0.dev1          
paddlehub                    2.0.0rc0            
paddlenlp                    2.0.0b2             
paddlepaddle                 2.0.0               
paddlepaddle-gpu             2.0.0 

**报错信息**

> [2021-01-28 15:46:50,362] [    INFO] - Installing ernie_gen module
---------------------------------------------------------------------------RuntimeError                              Traceback (most recent call last)~/.paddlehub/modules/ernie_gen/module.py in <module>
     24 try:
---> 25     from ernie.modeling_ernie import ErnieModelForGeneration
     26     from ernie.tokenizing_ernie import ErnieTokenizer
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ernie/__init__.py in <module>
     22     raise RuntimeError('propeller 0.2 requires paddle 2.0+, got %s' %
---> 23                        paddle.__version__)
     24 
RuntimeError: propeller 0.2 requires paddle 2.0+, got 1.8.4
During handling of the above exception, another exception occurred:
ImportError                               Traceback (most recent call last)<ipython-input-6-7a5911e08702> in <module>
      2 
      3 # 加载ernie_gen模型
----> 4 module = hub.Module(name="ernie_gen")
      5 
      6 train_data_file = os.path.join(new_dataset_dir, "lcsts_train_500k.txt")
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in __new__(cls, name, directory, module_dir, version, **kwargs)
    100             if name:
    101                 module = cls.init_with_name(
--> 102                     name=name, version=version, **kwargs)
    103             elif directory:
    104                 module = cls.init_with_directory(directory=directory, **kwargs)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in init_with_name(cls, name, version, **kwargs)
    169         extra = {"command": "install"}
    170         result, tips, module_dir = default_module_manager.install_module(
--> 171             module_name=name, module_version=version, extra=extra)
    172         if not result:
    173             logger.error(tips)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in install_module(self, module_name, module_dir, module_package, module_version, upgrade, extra)
    125         with tmp_dir() as _dir:
    126             if module_name:
--> 127                 self.all_modules(update=True)
    128                 module_info = self.modules_dict.get(module_name, None)
    129                 if module_info:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in all_modules(self, update)
    103                     shutil.move(sub_dir_path, new_sub_dir_path)
    104                     sub_dir_path = new_sub_dir_path
--> 105                 valid, info = self.check_module_valid(sub_dir_path)
    106                 if valid:
    107                     module_name = info['name']
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in check_module_valid(self, module_path)
     70                     sys.path.insert(0, dirname)
     71                     _module = importlib.import_module(
---> 72                         "{}.module".format(basename))
     73                     for _item, _cls in inspect.getmembers(
     74                             _module, inspect.isclass):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _load_unlocked(spec)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap_external.py in exec_module(self, module)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)
~/.paddlehub/modules/ernie_gen/module.py in <module>
     28 except:
     29     raise ImportError(
---> 30         "The module requires additional dependencies: ernie. You can install ernie via 'pip install paddle-ernie'"
     31     )
     32 import paddlehub as hub
ImportError: The module requires additional dependencies: ernie. You can install ernie via 'pip install paddle-ernie'

**偶尔在docker里面一次安装成功了，但ERNIE-GEN无法引入**

![image](https://user-images.githubusercontent.com/6434727/106361321-4886d580-6358-11eb-8f8e-117bf563b2bc.png)

然后代码：

> import  paddlehub as hub
> 加载ernie_gen模型的时候报错
> module = hub.Module(name="ernie_gen")

![image](https://user-images.githubusercontent.com/6434727/106361339-5f2d2c80-6358-11eb-8b4c-c3c532628f6d.png)

版本更新，不兼容没关系，连历史的版本都不兼容了。
历史的版本都不兼容没关系，在baidu的AIStudio上运行也不兼容。

**Comment by KPatr1ck** [comment]
你好，可以尝试安装paddle-ernie 0.04版本后，再执行脚本
```
pip install paddle-ernie==0.0.4.dev1
```

**Comment by uuleaf** [comment]
> 你好，可以尝试安装paddle-ernie 0.04版本后，再执行脚本
> 
> ```
> pip install paddle-ernie==0.0.4.dev1
> ```

paddle-ernie 所有 版本都试过了，依旧报错

**Comment by uuleaf** [comment]
**paddlepaddle1.8.4 + paddlehub1.8.3 + paddle-ernie0.0.4.dev1**

ubuntu@ubuntu:~$ hub install ernie_gen==1.0.0
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddlehub/commands/install.py", line 62, in execute
    result, tips, module_dir = default_module_manager.install_module(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddlehub/module/manager.py", line 127, in install_module
    self.all_modules(update=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddlehub/module/manager.py", line 105, in all_modules
    valid, info = self.check_module_valid(sub_dir_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddlehub/module/manager.py", line 71, in check_module_valid
    _module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ernie.module'

**Comment by KPatr1ck** [comment]
> > 你好，可以尝试安装paddle-ernie 0.04版本后，再执行脚本
> > ```
> > pip install paddle-ernie==0.0.4.dev1
> > ```
> 
> paddle-ernie 所有 版本都试过了，依旧报错

paddlehub           1.8.0
paddlepaddle      1.8.5
paddle-ernie        0.0.4.dev1

以上环境经测试可用，建议先同步到对应的环境使用。
paddlepaddle和各个组件都逐渐升级至动态图版本，ernie-gen在之后也会同步升级至2.0~

**Comment by uuleaf** [comment]
> > > 你好，可以尝试安装paddle-ernie 0.04版本后，再执行脚本
> > > ```
> > > pip install paddle-ernie==0.0.4.dev1
> > > ```
> > 
> > 
> > paddle-ernie 所有 版本都试过了，依旧报错
> 
> paddlehub 1.8.0
> paddlepaddle 1.8.5
> paddle-ernie 0.0.4.dev1
> 
> 以上环境经测试可用，建议先同步到对应的环境使用。
> paddlepaddle和各个组件都逐渐升级至动态图版本，ernie-gen在之后也会同步升级至2.0~

感谢反馈，刚才用docker 在这个版本安装成功
