### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by wangzhiwei-ai** [PaddlePaddle/PaddleFormers#123]
调用期间出现异常 ：Floating point exception (core dumped)，请问如何处理？

**Comment by Steffy-zxf** [comment]
感谢反馈！是什么场景下调用哪个API出现以上错误？错误出现的调用堆栈信息可以截图看看吗？

**Comment by FisherOuch** [comment]
@wangzhiwei-ai 您好， 本人在测试PaddleHub LAC工具的时候发现，当进行分词的字符串长度为0或全部为空白字符时可能出现Floating point exception错误，您可以试着从这个方向回溯看看。

**Comment by Steffy-zxf** [comment]
感谢反馈@FisherOuch！这个问题我们后续会修复。您可以先运行分词之前，加入判断字符串是否为0或全部为空白字符，避免这种情况的产生。同时想了解下，为什么您需要分词的字符串会是字符串长度为0或全部为空白字符？

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
