### ISSUE TITLE
MiDaS_Large 报错

### ISSUE THREAD

**Issue by Cy6er7um** [PaddlePaddle/PaddleFormers#1231]
1）PaddleHub和PaddlePaddle版本：PaddleHub 2.0.0b ; PaddlePaddle 2.0.0-Cpu .
2）系统环境：Windows Server 2019 Datacenter ; Python 3.7.9 .
3）项目源码：
```
import paddlehub as hub

model = hub.Module(name='MiDaS_Large', use_gpu=False)
```
4）报错如图：![image](https://user-images.githubusercontent.com/70457081/106857501-2516ae80-66fb-11eb-94c0-059300d3c2c6.png)

**Comment by Cy6er7um** [comment]
总之就是很懵，用Paddle第一次遇到这种情况...

**Comment by jm12138** [comment]
这个就是加载模型初始化的正常提示而已，不是报错，不会影响后面的使用的

**Comment by Cy6er7um** [comment]
> 这个就是加载模型初始化的正常提示而已，不是报错，不会影响后面的使用的

它跑到这里就直接退出了....算了嘤嘤嘤
