### ISSUE TITLE
Paddlehub这里有语法错误？？？

### ISSUE THREAD

**Issue by Cy6er7um** [PaddlePaddle/PaddleFormers#1234]
Paddlehub报错语法错误了....你们f""后面没加format的String
![image](https://user-images.githubusercontent.com/70457081/106864114-69f31300-6704-11eb-973b-48708cab813d.png)

**Comment by Cy6er7um** [comment]
我是rc0的hub
标准2.0.0的paddle
oracle linux7

**Comment by KPatr1ck** [comment]
python 3.5是不支持f string的，可以尝试在python3.6+环境下运行。

**Comment by UnknownMistyRain** [comment]
> python 3.5是不支持f string的，可以尝试在python3.6+环境下运行。

草我忘了 抱歉
