### ISSUE TITLE
调用api出现HTTPConnectionPool

### ISSUE THREAD

**Issue by txssg** [PaddlePaddle/PaddleFormers#1245]
开始可以正常使用 电脑无响应自动重新启动后无法使用
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8866): Max retries exceeded with url: /predict/animegan_v1_hayao_60 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002617BD3C708>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by haoyuying** [comment]
请问使用serving的脚本是什么呢

**Comment by txssg** [comment]
import requests
import json
import cv2
import base64


def cv2_to_base64(image):
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')


# 发送HTTP请求
data = {'images':[cv2_to_base64(cv2.imread("abc.png"))]}
headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:8866/predict/animegan_v1_hayao_60"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(r.json()["results"])
官方示例的

**Comment by txssg** [comment]
> 请问使用serving的脚本是什么呢
import requests
import json
import cv2
import base64


def cv2_to_base64(image):
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')


# 发送HTTP请求
data = {'images':[cv2_to_base64(cv2.imread("abc.png"))]}
headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:8866/predict/animegan_v1_hayao_60"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(r.json()["results"])
官方示例的

**Comment by ShenYuhan** [comment]
是否是本机请求本机？如果是windows机器，尝试关闭防火墙，或者换一个端口，确保你可以访问到使用的端口。

**Comment by txssg** [comment]
> 是否是本机请求本机？如果是Windows机器，尝试关闭防火墙，或者换一个端口，确保您可以访问到使用的端口。

y已解决
