### ISSUE TITLE
支持用户自己训练的模型吗？

### ISSUE THREAD

**Issue by aofch** [PaddlePaddle/PaddleFormers#125]
如题

**Comment by Steffy-zxf** [comment]
感谢反馈！您指的是把自己预训练的模型加载进PaddleHub，之后通过 hub.Module()接口调用吗？

**Comment by aofch** [comment]
https://github.com/PaddlePaddle/models.git
在这里面训练的模型，能放到 PaddleHub 里面加载吗？

**Comment by Steffy-zxf** [comment]
您想用PaddleModels下的哪个预训练模型呢？您想用的这个预训练模型有相应的服务器托管吗？
PaddleHub暂不支持加载自定义预训练模型，因为PaddleHub还对预训练模型参数做了一些工作进行封装。PaddleHub支持加载自定义预训练模型的功能在规划中，敬请期待。

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
