### ISSUE TITLE
安装了paddle-ernie，使用的时候说没安装

### ISSUE THREAD

**Issue by 1084667371** [PaddlePaddle/PaddleFormers#1250]
![1](https://user-images.githubusercontent.com/50902619/108810593-6d343d00-75e6-11eb-8f5f-e37f254da8bf.png)
![2](https://user-images.githubusercontent.com/50902619/108810594-6e656a00-75e6-11eb-9e51-3df1ef08f4e7.png)
![3](https://user-images.githubusercontent.com/50902619/108810596-6f969700-75e6-11eb-9f14-b7da2e6be303.png)

**Comment by KPatr1ck** [comment]
你好，可以参考一下这个回复解决该问题。
https://github.com/PaddlePaddle/PaddleHub/issues/1221#issuecomment-771394903
