### ISSUE TITLE
有动态图的实现版本嘛？

### ISSUE THREAD

**Issue by zhangqianjin** [PaddlePaddle/PaddleFormers#126]
最近使用pytorch训练网络，感觉特别舒服，看到paddle也有动态图的编程方式，可是查了所有资料也就“动态图机制-DyGraph”这一个文档，请问还有其他基于动态图的资料嘛？比如模型fine tuning,词向量等

**Comment by Steffy-zxf** [comment]
PaddleHub目前暂不支持动态图，这个已纳入未来规划中。

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
