### ISSUE TITLE
paddlehub2.0 fine-tune保存的模型转成paddlehub module之后使用自定义module name预测报错 

### ISSUE THREAD

**Issue by no7wan7** [PaddlePaddle/PaddleFormers#1261]
版本：
paddlehub              2.0.0                          
paddlenlp              2.0.0rc2                       
paddlepaddle-gpu       2.0.0.post101
python3.7.4
环境是AIstudio上的高级版
Linux jupyter-635754-1568929 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

复现了仓库下的 [图片分类demo](https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0/demo/image_classification)，使用的是自定义数据集，能够正常的训练
可以使用 hub.Module(name='resnet50_vd_imagenet_ssld', label_list=["roses", "tulips", "daisy", "sunflowers", "dandelion"], load_checkpoint='/PATH/TO/CHECKPOINT') 的方式预测
但是将finetune转成paddle hub module之后，hub list中有对应的模型（idcard_bill_classify）
再通过 hub.Module(name='idcard_bill_classify'）去预测就会报错
错误： AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

**Comment by haoyuying** [comment]
您好，您使用的resnet50_vd_imagenet_ssld是动态图模型，如果您想写自己的module，可以参考以下材料：
模型部分：https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0/modules/image/classification/resnet50_vd_imagenet_ssld
数据集部分：https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.0/paddlehub/datasets/flowers.py
训练及测试代码定义部分：https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.0/paddlehub/module/cv_module.py#L46
demo： https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0/demo/image_classification

目前您出现的问题可能是动态图和静态图模式切换问题，您可以现在https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.0/demo/image_classification/predict.py#L5 这句之前加上paddle.disable_static()试下是否有效，如果没用，请利用我提供的代码模版修改您的代码。

**Comment by no7wan7** [comment]
paddle.disable_static() 没有效果，报错信息还是一样的。直接用fine-tune训练的model.pdparams是没有问题的，可能我的fine-tune to paddlehub module代码写的有问题。但是我在git仓库的docs下没有找到finetuned_model_to_module.md文件，1.8版本及以往版本是有的，这个官方后续会补充吗

**Comment by haoyuying** [comment]
您好，如果是您自定义的分类模型，对于finetune部分的代码书写可以参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.0/paddlehub/module/cv_module.py#L46

可以排查下在什么地方程序执行出现问题，请问您的model定义是否按照动态图版本定义的呢，是否按照以下格式https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.0/modules/image/classification/resnet50_vd_imagenet_ssld
