### ISSUE TITLE
AttributeError: partially initialized module 'paddlehub' has no attribute 'Module' (most likely due to a circular import)

### ISSUE THREAD

**Issue by mr-abccc** [PaddlePaddle/PaddleFormers#1271]
环境：
windows 10 
paddlepaddle 2.0  paddlehub 2.0.1

运行代码：
import paddlehub as hub
import cv2

ocr = hub.Module(name="chinese_ocr_db_crnn_mobile")
result = ocr.recognize_text(images=[cv2.imread('./image/20210112190124.bmp')])

print(result)

代码参考的：
代码示例
https://www.paddlepaddle.org.cn/hubdetail?name=chinese_ocr_db_crnn_mobile&en_category=TextRecognition

错误信息：
    ocr = hub.Module(name="chinese_ocr_db_crnn_mobile")
AttributeError: partially initialized module 'paddlehub' has no attribute 'Module' (most likely due to a circular import)

其他：
https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.0/modules/image/text_recognition/README.md
高精度文字识别链接指向的是一个超轻量级中文OCR模型

以上。
 谢谢！

**Comment by mr-abccc** [comment]
问题解决，把.py文件名取成了paddlehub...

**Comment by haoyuying** [comment]
您好，如果问题已经解决，请及时关闭issue，谢谢您的配合。
