### ISSUE TITLE
文本分类Demo没有使用GPU

### ISSUE THREAD

**Issue by vForce825** [PaddlePaddle/PaddleFormers#1272]
- 使用版本
PaddlePaddle 2.0.0
Paddlehub 2.0
Paddlenlp 2.0.0rc2

- 复现代码
https://aistudio.baidu.com/aistudio/projectdetail/1598752

- 现象描述
观察发现GPU利用率一直为0，且Module载入后显存占用不再变化。开始训练后也没有进一步显存增加

**Comment by KPatr1ck** [comment]
```python
import paddle
optimizer = paddle.optimizer.Adam(learning_rate=5e-5, parameters=model.parameters())
trainer = hub.Trainer(model, optimizer, checkpoint_dir='test_ernie_text_cls')

trainer.train(train_dataset, epochs=3, batch_size=32, eval_dataset=dev_dataset)

# 在测试集上评估当前训练模型
trainer.evaluate(test_dataset, batch_size=32)
```

你好，`hub.Trainer`中的参数`use_gpu`默认是`False`，使用gpu的时候需要传递这个参数。
详情可查看： 
 https://github.com/PaddlePaddle/PaddleHub/blob/f4d9b46bf09ef35dd3fc65e609bd11a43ab66ec4/paddlehub/finetune/trainer.py#L56
