### ISSUE TITLE
python2.7：import paddlehub报错：from nltk.probability import FreqDist：SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Irvingao** [PaddlePaddle/PaddleFormers#1282]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：
PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：
ubuntu 18.04 ，python 2.7.17
- 复现信息：
import paddlehub as hub
![image](https://user-images.githubusercontent.com/58903762/110071227-a030ba80-7db6-11eb-9175-ea9ab388c4f5.png)

尝试注释解决，但是该模块中会有其他除print部分依然报错。

**Comment by haoyuying** [comment]
您好，建议您按章paddlehub2.0版本和paddlepaddle2.0版本，python版本使用3.6及以上。目前您使用的版本过老，中间存在的很多问题我们均已经修复。
