### ISSUE TITLE
DDParser 0.1.2 与 paddlehub 1.8.3中的word2vec_skipgram模型不能同时使用吗？

### ISSUE THREAD

**Issue by Macxy2018** [PaddlePaddle/PaddleFormers#1285]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.8.3，PaddlePaddle1.8.5
2）系统环境：请您描述系统类型，例如Windows，python版本3.6
- 复现信息：如为报错，请给出复现环境、复现步骤

import numpy as np
import scipy
from scipy.spatial import distance

from paddlehub.reader.tokenization import load_vocab
import paddle.fluid as fluid
import paddlehub as hub
from ddparser import DDParser

def convert_tokens_to_ids(vocab, text):
    wids = []
    tokens = text.split(" ")
    for token in tokens:
        wid = vocab.get(token, None)
        if not wid:
            wid = vocab["unknown"]
        wids.append(wid)
    return wids

if __name__ == "__main__":
    module = hub.Module(name="word2vec_skipgram", version='1.0.0')
    inputs, outputs, program = module.context(trainable=False)
    vocab = load_vocab(module.get_vocab_path())

    word_ids = inputs["word_ids"]
    embedding = outputs["word_embs"]

    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    feeder = fluid.DataFeeder(feed_list=[word_ids], place=place)

    ddp = DDParser(
        prob=True,
        use_pos=True
    )

    data = [
        [
            "驾驶违章一次扣12分用两个驾驶证处理可以吗",
            " 一次性扣12分的违章, 能用不满十二分的驾驶证扣分吗"
        ],
        ["水果放冰箱里储存好吗", "中国银行纪念币网上怎么预约"],
        ["电脑反应很慢怎么办", "反应速度慢, 电脑总是卡是怎么回事"],
    ]

    for item in data:
        item[0] = ' '.join(ddp.parse(item[0])[0]['word'])
        item[1] = ' '.join(ddp.parse(item[1])[0]['word'])
        text_a = convert_tokens_to_ids(vocab, item[0])
        text_b = convert_tokens_to_ids(vocab, item[1])

        vecs_a, = exe.run(
            program,
            feed=feeder.feed([[text_a]]),
            fetch_list=[embedding.name],
            return_numpy=False)
        vecs_a = np.array(vecs_a)
        vecs_b, = exe.run(
            program,
            feed=feeder.feed([[text_b]]),
            fetch_list=[embedding.name],
            return_numpy=False)
        vecs_b = np.array(vecs_b)

        sent_emb_a = np.sum(vecs_a, axis=0)
        sent_emb_b = np.sum(vecs_b, axis=0)
        cos_sim = 1 - distance.cosine(sent_emb_a, sent_emb_b)

        print("text_a: %s; text_b: %s; cosine_similarity: %.5f" %
              (item[0], item[1], cos_sim))

报错信息

[2021-03-05 19:56:35,608] [    INFO] - Installing word2vec_skipgram module-1.0.0
[2021-03-05 19:56:35,610] [    INFO] - Module word2vec_skipgram-1.0.0 already installed in C:\Users\Mao Xueyu\.paddlehub\modules\word2vec_skipgram
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/tmp/tmp2.py", line 158, in <module>
    sswv = SenSimWV()
  File "E:/tmp/tmp2.py", line 47, in __init__
    module = hub.Module(name="word2vec_skipgram", version='1.0.0')
  File "D:\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "D:\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 178, in init_with_name
    return cls.init_with_directory(directory=module_dir[0], **kwargs)
  File "D:\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 186, in init_with_directory
    return ModuleV1(directory=directory, **kwargs)
  File "D:\Anaconda3\lib\site-packages\paddlehub\module\module.py", line 321, in __init__
    self.helper.model_path(), executor=exe)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 1397, in load_inference_model
    program = Program.parse_from_string(program_desc_str)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 4361, in parse_from_string
    p._sync_with_cpp()
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 4561, in _sync_with_cpp
    block._sync_with_cpp()
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2730, in _sync_with_cpp
    op = Operator(self, op_desc)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 1832, in __init__
    "`type` to initialized an Operator can not be None.")
ValueError: `type` to initialized an Operator can not be None.

**Comment by KPatr1ck** [comment]
你好，请问当前使用的paddlepaddle和paddlehub版本号是多少？
在你当前环境下，两个模型分别使用的话可以正常执行吗？

**Comment by Macxy2018** [comment]
> 你好，请问当前使用的paddlepaddle和paddlehub版本号是多少？
> 在你当前环境下，两个模型分别使用的话可以正常执行吗？

paddlepaddle为1.8.5
paddlehub为1.8.3
词向量单独运行没有问题，句法解析单独运行也没有问题

**Comment by KPatr1ck** [comment]
> > 你好，请问当前使用的paddlepaddle和paddlehub版本号是多少？
> > 在你当前环境下，两个模型分别使用的话可以正常执行吗？
> 
> paddlepaddle为1.8.5
> paddlehub为1.8.3
> 词向量单独运行没有问题，句法解析单独运行也没有问题

尝试类似下面的方式，在循环体里加入`fluid.enable_dygraph()`和`fluid.disable_dygraph()`的语句，再测试一下是否能正常执行。

```python
for item in data:
    fluid.enable_dygraph()    # 动态图模式
    item[0] = ' '.join(ddp.parse(item[0])[0]['word'])
    item[1] = ' '.join(ddp.parse(item[1])[0]['word'])
    text_a = convert_tokens_to_ids(vocab, item[0])
    text_b = convert_tokens_to_ids(vocab, item[1])

    fluid.disable_dygraph()   # 静态图模式
    vecs_a, = exe.run(
        program,
        feed=feeder.feed([[text_a]]),
        fetch_list=[embedding.name],
        return_numpy=False)
    vecs_a = np.array(vecs_a)
    vecs_b, = exe.run(
        program,
        feed=feeder.feed([[text_b]]),
        fetch_list=[embedding.name],
        return_numpy=False)
    vecs_b = np.array(vecs_b)

    sent_emb_a = np.sum(vecs_a, axis=0)
    sent_emb_b = np.sum(vecs_b, axis=0)
    cos_sim = 1 - distance.cosine(sent_emb_a, sent_emb_b)

    print("text_a: %s; text_b: %s; cosine_similarity: %.5f" %
          (item[0], item[1], cos_sim))

```

**Comment by Macxy2018** [comment]
> > > 你好，请问当前使用的paddlepaddle和paddlehub版本号是多少？
> > > 在你当前环境下，两个模型分别使用的话可以正常执行吗？
> > 
> > 
> > paddlepaddle为1.8.5
> > paddlehub为1.8.3
> > 词向量单独运行没有问题，句法解析单独运行也没有问题
> 
> 尝试类似下面的方式，在循环体里加入`fluid.enable_dygraph()`和`fluid.disable_dygraph()`的语句，再测试一下是否能正常执行。
> 
> ```python
> for item in data:
>     fluid.enable_dygraph()    # 动态图模式
>     item[0] = ' '.join(ddp.parse(item[0])[0]['word'])
>     item[1] = ' '.join(ddp.parse(item[1])[0]['word'])
>     text_a = convert_tokens_to_ids(vocab, item[0])
>     text_b = convert_tokens_to_ids(vocab, item[1])
> 
>     fluid.disable_dygraph()   # 静态图模式
>     vecs_a, = exe.run(
>         program,
>         feed=feeder.feed([[text_a]]),
>         fetch_list=[embedding.name],
>         return_numpy=False)
>     vecs_a = np.array(vecs_a)
>     vecs_b, = exe.run(
>         program,
>         feed=feeder.feed([[text_b]]),
>         fetch_list=[embedding.name],
>         return_numpy=False)
>     vecs_b = np.array(vecs_b)
> 
>     sent_emb_a = np.sum(vecs_a, axis=0)
>     sent_emb_b = np.sum(vecs_b, axis=0)
>     cos_sim = 1 - distance.cosine(sent_emb_a, sent_emb_b)
> 
>     print("text_a: %s; text_b: %s; cosine_similarity: %.5f" %
>           (item[0], item[1], cos_sim))
> ```

添加动静态转换就可以运行了
