### ISSUE TITLE
Jetson nano 安装好paddlehub后，import paddlehub崩溃

### ISSUE THREAD

**Issue by Irvingao** [PaddlePaddle/PaddleFormers#1287]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：
PaddleHub2.0.4，PaddlePaddle-gpu 2.0
2）系统环境：
Jetson  nano JetPack 4.4.1
Ubuntu 18.04
python 3.6.9
- 复现信息：
`>>> import paddlehub        
Illegal instruction (core dumped)`

**Comment by haoyuying** [comment]
您好，请提供更多的报错栈信息，您可以先尝试是否在import paddle时候就报错呢？

**Comment by Irvingao** [comment]
是的，按该博客进行安装操作就正常了。https://blog.csdn.net/qq_45779334/article/details/114436858
