### ISSUE TITLE
关于文本分类训练结果文件夹

### ISSUE THREAD

**Issue by myechona** [PaddlePaddle/PaddleFormers#129]
训练文本分类后，训练结果会保留在ckpt_*文件夹下，有三个文件夹best_model， step_14436 ， vdllog，还有一个文件 ckpt.meta，而best_model， step_14436文件夹下又有多个文件，请问当进行预测的时候，ckpt_*这个文件夹下所有文件都是有用的吗？能去除冗余文件吗？像pytorch训练后就调用一个bin文件。

**Comment by kinghuin** [comment]
Hi 如果不进行增量训练，且预测的时候predict函数不改变默认参数load_best_model=True，则可以删除 ckpt.meta以及step_14436文件夹
如果预测的时候不采用load_best_model=True，仅使用最后的训练结果用于预测，则可以删除best_model
否则请保留best_model, ckpt.meta和step_14436，分别记录了在dev数据集表现最佳的模型参数，模型训练结束时的状态信息以及最后的参数信息

**Comment by kinghuin** [comment]
Hi  在≤1.1版本中，如果不进行增量训练，且预测的时候predict函数不改变默认参数load_best_model=True，则可以删除 ckpt.meta以及step_14436文件夹
在未来的版本中，如果预测的时候不采用load_best_model=True，仅使用最后的训练结果用于预测，则可以删除best_model
否则请保留best_model, ckpt.meta和step_14436，分别记录了在dev数据集表现最佳的模型参数，模型训练结束时的状态信息以及最后的参数信息

**Comment by myechona** [comment]
默认的predic函数中 load_best_model=True，但是删去ckpt.meta，会提示PaddleHub model checkpoint not found, start training from scratch

**Comment by myechona** [comment]
感谢这么快回复，尝试了你说的，可行，虽然会提示PaddleHub model checkpoint not found, start training from scratch...那么best_model文件夹下所有文件都需要保留吗？

**Comment by kinghuin** [comment]
在≤1.1版本中，模型先进行了初始化再加载最优模型，这句提示是在初始化的时候产生的，不会影响到最优模型的使用，故您可以忽略这句提示。 在未来的版本中，我们已经更新了接口不会再出现这个提示了。 是的，best_model文件夹下所有文件都需要保留，它们保存了每个参数的值

**Comment by myechona** [comment]
偷偷修改了layer0的一个文件名，似乎也能预测

**Comment by myechona** [comment]
偷偷修改了layer0的一个文件名，似乎也能预测

**Comment by kinghuin** [comment]
不建议这么修改噢 这么修改的话会导致改动的那个变量的值是初始化的值而不是最优模型的值

**Comment by myechona** [comment]
哦，好的，希望以后要是有个说明文件就好了，再次感谢！

**Comment by kinghuin** [comment]
感谢您的建议 后续我们会完善的！
