### ISSUE TITLE
PaddleHub导入出现错误

### ISSUE THREAD

**Issue by ElieenAndBella** [PaddlePaddle/PaddleFormers#1292]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub 2.0.0
2）系统环境：Windows，python 3.7
- 复现信息：如为报错，请给出复现环境、复现步骤
![image](https://user-images.githubusercontent.com/54427695/110341063-ea3ec800-8064-11eb-97b8-5219acd8d89b.png)

**Comment by haoyuying** [comment]
您好，从报错信息上来看，应该是git 安装问题，请参考https://github.com/PaddlePaddle/PaddleHub/issues/1100

**Comment by ElieenAndBella** [comment]
解决了，但是不是用这个，是更新C++版本解决的，这几天有点忙，没回
