### ISSUE TITLE
yolov3_darknet53_coco2017 模型传入多张图片,标签正确,但结果图片使用的是第一张图作为org_img

### ISSUE THREAD

**Issue by paopjian** [PaddlePaddle/PaddleFormers#1296]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：2.0.0
2）系统环境：windows10, cuda10.2
- 复现信息：如为报错，请给出复现环境、复现步骤
1.mp4下载链接:https://paddlehub.bj.bcebos.com/model/video/video_classifcation/1.mp4
复现代码:

import cv2
import paddlehub as hub
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '0'
object_detector = hub.Module(name="yolov3_darknet53_coco2017")
temp = []
cap = cv2.VideoCapture('1.mp4')
while(cap.isOpened()):
    ret, frame = cap.read()
    if frame is None:
        break
    temp.append(frame)
cap.release()

result = object_detector.object_detection(images=temp,use_gpu=True,batch_size=2)

**Comment by haoyuying** [comment]
您好同学，我试了下，输入的frame也只有一帧，你可以打印下temp里面的长度。目前初步判断是您的mp4文件读取有问题。
```
import cv2
import paddlehub as hub
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '0'
object_detector = hub.Module(name="yolov3_darknet53_coco2017")
temp = []
cap = cv2.VideoCapture('1.mp4')
while(cap.isOpened()):
    ret, frame = cap.read()
    if frame is None:
        break
    temp.append(frame)
    cap.release()
print(len(temp))
result = object_detector.object_detection(images=temp,use_gpu=True,batch_size=2)
print(len(result))
```
如果您对视频流读取有疑问，可以参考如下代码进行修改：https://www.paddlepaddle.org.cn/hubdetail?name=humanseg_mobile&en_category=ImageSegmentation

**Comment by paopjian** [comment]
我传入的是temp,是把所有frame append到temp里的,但是结果是label用的temp[i]的,图片用的temp[0]的

**Comment by paopjian** [comment]
`import cv2
import paddlehub as hub
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '0'
object_detector = hub.Module(name="yolov3_darknet53_coco2017")
temp = []
cap = cv2.VideoCapture('1.mp4')
while(cap.isOpened()):
    ret, frame = cap.read()
    if frame is None:
        break
    temp.append(frame)
cap.release()
print(len(temp))
result = object_detector.object_detection(images=temp,use_gpu=True,batch_size=2)
print(len(result))`
代码应该是这样,cap.release()位置错了

**Comment by paopjian** [comment]
应该是
```
import cv2
import paddlehub as hub
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '0'
object_detector = hub.Module(name="yolov3_darknet53_coco2017")
temp = []
cap = cv2.VideoCapture('https://paddlehub.bj.bcebos.com/model/video/video_classifcation/1.mp4')
while(cap.isOpened()):
    ret, frame = cap.read()
    if frame is None:
        break
    temp.append(frame)
cap.release()
print(len(temp))
result = object_detector.object_detection(images=temp,use_gpu=True,batch_size=2)
print(len(result))
```
cap.release()位置错了,请重试
