### ISSUE TITLE
yolov3_darknet53_coco2017模型,processor.py文件,postprocess方法有误

### ISSUE THREAD

**Issue by paopjian** [PaddlePaddle/PaddleFormers#1310]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：2.0.0
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
windows10, cuda10.2,python=3.8,  yolov3_darknet53_coco2017=1.1.1

使用方法:
result = object_detector.object_detection(images=images, use_gpu=True, batch_size=1, visualization=True)

源代码中163行处只检查了paths,但函数应该可以处理paths和images两种数据,未针对images进行handle调整
![image](https://user-images.githubusercontent.com/20377352/110883703-cfc25400-82db-11eb-90a2-9c123c1e2422.png)
导致在149行处,index永远为0,unhandled_paths_num也为0,每次都取images[0]作为org_img.
![image](https://user-images.githubusercontent.com/20377352/110884231-b40b7d80-82dc-11eb-8ee5-7f984a213133.png)
此issue是 https://github.com/PaddlePaddle/PaddleHub/issues/1296  的溯源

**Comment by haoyuying** [comment]
我们将近期排查及升级该问题，感谢您的反馈及对开源社区的贡献。

**Comment by haoyuying** [comment]
同学您好，这边 yolov3_darknet53_coco2017 1.1.1版本已经修复了该问题，您可以重新体验下。但是您给的视频很大，会把显存用尽，建议截一个20帧的视频试下。

**Comment by paopjian** [comment]
确实修复问题,但是应该不会用尽显存啊,batch_size设为1了,一次只处理1张图
