### ISSUE TITLE
自定义任务中如何定义指标

### ISSUE THREAD

**Issue by foreversolar** [PaddlePaddle/PaddleFormers#132]
在这个[教程](https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub:-%E8%87%AA%E5%AE%9A%E4%B9%89Task)中, 提到可以自定义 `_add_metrics` ,如果想自己定义一个Macro-F1的指标应该怎么修改呢，因为fluid.layers 只提供了acc和auc两个指标，fluid.metric这个接口接不起来。
谢谢！

**Comment by Steffy-zxf** [comment]
感谢反馈！自定义评价指标，需要重载_add_metrics方法，参数run_states是存放训练过程中训练结果(run_states.run_results,  run program的时候fetch_list取出来的结果)。指标Macro-F1，fluid.metric没有相应的实现，可以利用numpy实现。具体可以参考PaddleHub的Task里面的写法。

**Comment by foreversolar** [comment]
请问大概是哪段代码呢？task里面的metric都是使用了fluid.layers.auc/acc 是要模仿这两个类写吗？

**Comment by Steffy-zxf** [comment]
您想要实现什么任务？是序列标注任务？如果是的话，可以参考实现，https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.1.0/paddlehub/finetune/task.py#L897
其中np_infers是模型预测label，np_labels是数据真实label，np_lens是句子的长度，这些是存放在run_states.run_results里，这是run program时指定fetch_list取出来的结果。

**Comment by foreversolar** [comment]
看到啦，谢谢！！
