### ISSUE TITLE
predict的BUG，i fix it already（那是不可能的）。

### ISSUE THREAD

**Issue by yangtianyu92** [PaddlePaddle/PaddleFormers#134]
作为管理学院唯一指定代码工具人，你们第一次一度让我感觉自己像个HACKER。

代码地址在这
https://github.com/PaddlePaddle/PaddleHub/blob/675e80c364f6b41540f4f508c47ad019f97673f9/paddlehub/reader/nlp_reader.py

PaddleHub 0.5版本 
  nlp_reader.py  
    LACClassifyReader

        '''
        if self.label_map:
            if example.label not in self.label_map:
                raise KeyError(
                    "example.label = {%s} not in label" % example.label)
            label_id = self.label_map[example.label]
        else:
            label_id = example.label
        '''

log打出label_map = {'risk4': 4, 'risk2': 2, 'risk3': 3, 'risk0': 0, 'risk1': 1}
而我输入文本    “阿拉伯7国发布通报修订冷冻龙虾的相关规定”， 类别应属于risk4
但是这时候example.label输出都为0，按照这段代码的逻辑就会raise an error。

修复方法就是把这段注释掉，直接label_id = example.label

**Comment by Steffy-zxf** [comment]
感谢反馈！Paddlehub已经在后续版本修复该问题。请更新PaddleHub至最新的版本1.1.1.
PaddleHub每次升级都会新增一些新特性，建议及时更新。

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
