### ISSUE TITLE
Bug on finetune.py for senta related modules

### ISSUE THREAD

**Issue by sfu2** [PaddlePaddle/PaddleFormers#1344]
### 1. 版本信息
下述两种环境中均可复现相同BUG
paddlepaddle == 1.7.2 && paddlehub == 1.7.0
paddlepaddle == 1.8 && paddlehub == 1.8

### 2. 系统环境
Ubuntu 16.04.6 LTS

### 3. 复现信息
运行 repo 中 demo/senta/senta_finetune.py 时报错
```
Traceback (most recent call last):
  File "senta_finetune.py", line 30, in <module>
    feed_list = [inputs["words"].name]
KeyError: 'words'
```

**Comment by KPatr1ck** [comment]
你好，paddlehub 1.8中用senta finetune的demo请参考该脚本[demo/senta/senta_finetune.py](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/demo/senta/senta_finetune.py)。 
 在以下环境测试中是正常执行的：
```
paddlehub              1.8.0                                          
paddlepaddle-gpu       1.8.4.post97                 
```

经检查，下面这一行仅出现在paddlehub 1.7版本的[demo/senta/senta_finetune.py](https://github.com/PaddlePaddle/PaddleHub/blob/9894fbb1dc8575ae1fa74f32a23cc1363467461b/demo/senta/senta_finetune.py#L31)。
```
feed_list = [inputs["words"].name]
```

建议确保当前环境下是paddlehub 1.8，然后运行的脚本是对应的1.8分支的repo中的[demo/senta/senta_finetune.py](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/demo/senta/senta_finetune.py)。

**Comment by sfu2** [comment]
感谢。在 paddlehub 1.8 中的 senta_finetune.py 代码可以成功运行。  
经检查，1.8 版本中 [demo/senta/senta_finetune.py](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/demo/senta/senta_finetune.py) 和 [demo/senta/README.md](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/demo/senta/README.md) 中的描述存在出入。  

另，我注意到在 v2.0 中 demo/senta 相关代码已被移除，请问后续版本还会对 senta 以及其 finetune 提供支持吗？如果有，请问可以提供 v2.0 下 senta 的相关 demo 吗？

**Comment by KPatr1ck** [comment]
> 感谢。在 paddlehub 1.8 中的 senta_finetune.py 代码可以成功运行。
> 经检查，1.8 版本中 [demo/senta/senta_finetune.py](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/demo/senta/senta_finetune.py) 和 [demo/senta/README.md](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/demo/senta/README.md) 中的描述存在出入。
> 
> 另，我注意到在 v2.0 中 demo/senta 相关代码已被移除，请问后续版本还会对 senta 以及其 finetune 提供支持吗？如果有，请问可以提供 v2.0 下 senta 的相关 demo 吗？

senta目前还没有升级成2.0的动态图版本，但是paddlehub这边对于module是向下兼容的，所以之前1.8的代码和module能用的话，在2.0下也是能用的。
