### ISSUE TITLE
cls_task.finetune_and_eval() 报错

### ISSUE THREAD

**Issue by cchan19** [PaddlePaddle/PaddleFormers#136]
在百度AI STUDIO运行文本分类任务示例：https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.1.0/demo/text-classification

cls_task.finetune_and_eval() 报错：
---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-14-37278a27b4b6> in <module>
----> 1 cls_task.finetune_and_eval()
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/finetune/task.py in finetune_and_eval(self)
    504 
    505     def finetune_and_eval(self):
--> 506         return self.finetune(do_eval=True)
    507 
    508     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/finetune/task.py in finetune(self, do_eval)
    509         # Start to finetune
    510         with self.phase_guard(phase="train"):
--> 511             self.init_if_necessary()
    512             self._finetune_start_event()
    513             run_states = []
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/finetune/task.py in init_if_necessary(self)
    166         if not self.is_checkpoint_loaded:
    167             self.is_checkpoint_loaded = True
--> 168             if not self.load_checkpoint():
    169                 self.exe.run(self._base_startup_program)
    170 
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/finetune/task.py in load_checkpoint(self)
    487             self.config.checkpoint_dir,
    488             self.exe,
--> 489             main_program=self.main_program)
    490 
    491         return is_load_successful
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/finetune/task.py in main_program(self)
    331     def main_program(self):
    332         if not self.env.is_inititalized:
--> 333             self._build_env()
    334         return self.env.main_program
    335 
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/finetune/task.py in _build_env(self)
    244                 with fluid.unique_name.guard(self.env.UNG):
    245                     self.config.strategy.execute(
--> 246                         self.loss, self._base_data_reader, self.config)
    247 
    248         if self.is_train_phase:
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/finetune/strategy.py in execute(self, loss, data_reader, config)
    132         scheduled_lr = adam_weight_decay_optimization(
    133             loss, warmup_steps, max_train_steps, self.learning_rate,
--> 134             main_program, self.weight_decay, self.lr_scheduler)
    135 
    136         return scheduled_lr
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/finetune/optimization.py in adam_weight_decay_optimization(loss, warmup_steps, num_train_steps, learning_rate, main_program, weight_decay, scheduler)
     77         param_list[param.name].stop_gradient = True
     78 
---> 79     _, param_grads = optimizer.minimize(loss)
     80 
     81     if weight_decay > 0:
</opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/decorator.py:decorator-gen-144> in minimize(self, loss, startup_program, parameter_list, no_grad_set, grad_clip)
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/dygraph/base.py in __impl__(*args, **kwargs)
     86     def __impl__(*args, **kwargs):
     87         with _switch_tracer_mode_guard_(is_train=False):
---> 88             return func(*args, **kwargs)
     89 
     90     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/optimizer.py in minimize(self, loss, startup_program, parameter_list, no_grad_set, grad_clip)
    591             startup_program=startup_program,
    592             parameter_list=parameter_list,
--> 593             no_grad_set=no_grad_set)
    594 
    595         if grad_clip is not None and framework.in_dygraph_mode():
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/optimizer.py in backward(self, loss, startup_program, parameter_list, no_grad_set, callbacks)
    491             with program_guard(program, startup_program):
    492                 params_grads = append_backward(loss, parameter_list,
--> 493                                                no_grad_set, callbacks)
    494                 # Note: since we can't use all_reduce_op now,
    495                 #  dgc_op should be the last op of one grad.
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/backward.py in append_backward(loss, parameter_list, no_grad_set, callbacks)
    568         grad_to_var,
    569         callbacks,
--> 570         input_grad_names_set=input_grad_names_set)
    571 
    572     # Because calc_gradient may be called multiple times,
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/backward.py in _append_backward_ops_(block, ops, target_block, no_grad_dict, grad_to_var, callbacks, input_grad_names_set)
    308         # Getting op's corresponding grad_op
    309         grad_op_desc, op_grad_to_var = core.get_grad_op_desc(
--> 310             op.desc, cpt.to_text(no_grad_dict[block.idx]), grad_sub_block_list)
    311 
    312         # If input_grad_names_set is not None, extend grad_op_descs only when
EnforceNotMet: Input ShapeTensor cannot be found in Op reshape2 at [/paddle/paddle/fluid/framework/op_desc.cc:306]
PaddlePaddle Call Stacks: 
0       0x7f991b9132e0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f991b913659p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f991ba8423fp paddle::framework::OpDesc::Input(std::string const&) const + 207
3       0x7f991bf537fcp paddle::framework::details::OpInfoFiller<paddle::operators::Reshape2GradMaker, (paddle::framework::details::OpInfoFillType)2>::operator()(char const*, paddle::framework::OpInfo*) const::{lambda(paddle::framework::OpDesc const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >*, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> > const&)#1}::operator()(paddle::framework::OpDesc const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >*, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> > const&) const + 540
4       0x7f991bf53d74p std::_Function_handler<std::vector<std::unique_ptr<paddle::framework::OpDesc, std::default_delete<paddle::framework::OpDesc> >, std::allocator<std::unique_ptr<paddle::framework::OpDesc, std::default_delete<paddle::framework::OpDesc> > > > (paddle::framework::OpDesc const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >*, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> > const&), paddle::framework::details::OpInfoFiller<paddle::operators::Reshape2GradMaker, (paddle::framework::details::OpInfoFillType)2>::operator()(char const*, paddle::framework::OpInfo*) const::{lambda(paddle::framework::OpDesc const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >*, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> > const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::OpDesc const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >*, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> > const&) + 20
5       0x7f991b90c24ap
6       0x7f991b945ca6p
7       0x7f999ff31199p PyCFunction_Call + 233
8       0x7f999ffcbdbep PyEval_EvalFrameEx + 31950
9       0x7f999ffce4b6p
10      0x7f999ffcb5b5p PyEval_EvalFrameEx + 29893
11      0x7f999ffce4b6p
12      0x7f999ffcb5b5p PyEval_EvalFrameEx + 29893
13      0x7f999ffce4b6p
14      0x7f999ffcb5b5p PyEval_EvalFrameEx + 29893
15      0x7f999ffce4b6p
16      0x7f999ffce5a8p PyEval_EvalCodeEx + 72
17      0x7f999ff0dc33p
18      0x7f999fedc33ap PyObject_Call + 106
19      0x7f999ffc66eep PyEval_EvalFrameEx + 9726
20      0x7f999ffce4b6p
21      0x7f999ffce5a8p PyEval_EvalCodeEx + 72
22      0x7f999ff0dc33p
23      0x7f999fedc33ap PyObject_Call + 106
24      0x7f999ffc66eep PyEval_EvalFrameEx + 9726
25      0x7f999ffce4b6p
26      0x7f999ffcb5b5p PyEval_EvalFrameEx + 29893
27      0x7f999ffce4b6p
28      0x7f999ffcb5b5p PyEval_EvalFrameEx + 29893
29      0x7f999ffce4b6p
30      0x7f999ffcb5b5p PyEval_EvalFrameEx + 29893
31      0x7f999ffcc1d0p PyEval_EvalFrameEx + 32992
32      0x7f999ffce4b6p
33      0x7f999ffcb5b5p PyEval_EvalFrameEx + 29893
34      0x7f999ffce4b6p
35      0x7f999ffce5a8p PyEval_EvalCodeEx + 72
36      0x7f999ff0db56p
37      0x7f999fedc33ap PyObject_Call + 106
38      0x7f999fefa172p
39      0x7f999ff3451cp _PyObject_GenericGetAttrWithDict + 124
40      0x7f999ffc8d2ap PyEval_EvalFrameEx + 19514
41      0x7f999ffcc1d0p PyEval_EvalFrameEx + 32992
42      0x7f999ffcc1d0p PyEval_EvalFrameEx + 32992
43      0x7f999ffce4b6p
44      0x7f999ffcb5b5p PyEval_EvalFrameEx + 29893
45      0x7f999ffcc1d0p PyEval_EvalFrameEx + 32992
46      0x7f999ffce4b6p
47      0x7f999ffce5a8p PyEval_EvalCodeEx + 72
48      0x7f999ffce5ebp PyEval_EvalCode + 59
49      0x7f999ffc1c5dp
50      0x7f999ff31179p PyCFunction_Call + 201
51      0x7f999ffcbdbep PyEval_EvalFrameEx + 31950
52      0x7f999ff05410p _PyGen_Send + 128
53      0x7f999ffca953p PyEval_EvalFrameEx + 26723
54      0x7f999ff05410p _PyGen_Send + 128
55      0x7f999ffca953p PyEval_EvalFrameEx + 26723
56      0x7f999ff05410p _PyGen_Send + 128
57      0x7f999ffcbd60p PyEval_EvalFrameEx + 31856
58      0x7f999ffcc1d0p PyEval_EvalFrameEx + 32992
59      0x7f999ffcc1d0p PyEval_EvalFrameEx + 32992
60      0x7f999ffce4b6p
61      0x7f999ffce5a8p PyEval_EvalCodeEx + 72
62      0x7f999ff0dc33p
63      0x7f999fedc33ap PyObject_Call + 106
64      0x7f999ffc66eep PyEval_EvalFrameEx + 9726
65      0x7f999ffce4b6p
66      0x7f999ffcb5b5p PyEval_EvalFrameEx + 29893
67      0x7f999ff046bap
68      0x7f999ffbfaf6p
69      0x7f999ff31179p PyCFunction_Call + 201
70      0x7f999ffcbdbep PyEval_EvalFrameEx + 31950
71      0x7f999ffce4b6p
72      0x7f999ffcb5b5p PyEval_EvalFrameEx + 29893
73      0x7f999ff046bap
74      0x7f999ffbfaf6p
75      0x7f999ff31179p PyCFunction_Call + 201
76      0x7f999ffcbdbep PyEval_EvalFrameEx + 31950
77      0x7f999ffce4b6p
78      0x7f999ffcb5b5p PyEval_EvalFrameEx + 29893
79      0x7f999ff046bap
80      0x7f999ffbfaf6p
81      0x7f999ff31179p PyCFunction_Call + 201
82      0x7f999ffcbdbep PyEval_EvalFrameEx + 31950
83      0x7f999ffce4b6p
84      0x7f999ffce5a8p PyEval_EvalCodeEx + 72
85      0x7f999ff0db56p
86      0x7f999fedc33ap PyObject_Call + 106
87      0x7f999ffc66eep PyEval_EvalFrameEx + 9726
88      0x7f999ff05410p _PyGen_Send + 128
89      0x7f999ffcbd60p PyEval_EvalFrameEx + 31856
90      0x7f999ffcc1d0p PyEval_EvalFrameEx + 32992
91      0x7f999ffce4b6p
92      0x7f999ffce5a8p PyEval_EvalCodeEx + 72
93      0x7f999ff0dc33p
94      0x7f999fedc33ap PyObject_Call + 106
95      0x7f999ffc66eep PyEval_EvalFrameEx + 9726
96      0x7f999ffce4b6p
97      0x7f999ffce5a8p PyEval_EvalCodeEx + 72
98      0x7f999ff0db56p
99      0x7f999fedc33ap PyObject_Call + 106
[ ]

**Comment by Steffy-zxf** [comment]
感谢反馈！注意到 以上报错信息：EnforceNotMet: Input ShapeTensor cannot be found in Op reshape2 at ，可以参考下面问题的解决方法。https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub-FAQ#%E9%97%AE%E9%A2%98%E4%B8%89

**Comment by cchan19** [comment]
@Steffy-zxf 谢谢，该问题已解决。
然后我又遇到另一个问题。
在AI STUDIO平台上运行示例，第一次可以完整运行，
但重启notebook后，运行到
`module = hub.Module(name="ernie")`
就报错了。报错信息如下：

[2019-09-03 15:33:37,626] [    INFO] - Installing ernie module
[2019-09-03 15:33:37,708] [    INFO] - Module ernie already installed in /home/aistudio/.paddlehub/modules/ernie
Traceback (most recent call last):
  File "./work/fine_tune.py", line 13, in <module>
    module = hub.Module(name="ernie")
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/module/module.py", line 122, in __init__
    self._init_with_name(name=name, version=version)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/module/module.py", line 152, in _init_with_name
    self._init_with_module_file(module_dir[0])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/module/module.py", line 212, in _init_with_module_file
    self.helper.model_path(), executor=exe)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/io.py", line 1199, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/io.py", line 747, in load_persistables
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/io.py", line 611, in load_vars
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/io.py", line 648, in load_vars
    executor.run(load_prog)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/executor.py", line 749, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator load error.
Python Callstacks: 
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/io.py", line 633, in load_vars
    'file_path': os.path.join(load_dirname, new_var.name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/io.py", line 611, in load_vars
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/io.py", line 747, in load_persistables
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/io.py", line 1199, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/module/module.py", line 212, in _init_with_module_file
    self.helper.model_path(), executor=exe)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/module/module.py", line 152, in _init_with_name
    self._init_with_module_file(module_dir[0])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/module/module.py", line 122, in __init__
    self._init_with_name(name=name, version=version)
  File "./work/fine_tune.py", line 13, in <module>
    module = hub.Module(name="ernie")
C++ Callstacks: 
cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: CUDA driver version is insufficient for CUDA runtime version at [/paddle/paddle/fluid/platform/gpu_info.cc:97]
PaddlePaddle Call Stacks: 
0       0x7fec5b2a4870p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fec5b2a4be9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fec5d3f50acp paddle::platform::GetCUDADeviceCount() + 1036
3       0x7fec5d3c2f1fp paddle::memory::allocation::AllocatorFacadePrivate::InitLegacyAllocator() + 175
4       0x7fec5d3bff38p paddle::memory::allocation::AllocatorFacade::AllocatorFacade() + 888
5       0x7fec5d3c013cp paddle::memory::allocation::AllocatorFacade::Instance() + 76
6       0x7fec5cfb85cbp paddle::memory::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 27
7       0x7fec5d391664p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, paddle::framework::proto::VarType_Type, unsigned long) + 148
8       0x7fec5d39b108p void paddle::framework::VisitDataType<paddle::framework::DeserializedDataFunctor>(paddle::framework::proto::VarType_Type, paddle::framework::DeserializedDataFunctor) + 408
9       0x7fec5d399f4cp paddle::framework::TensorFromStream(std::istream&, paddle::framework::Tensor*, paddle::platform::DeviceContext const&) + 924
10      0x7fec5cf6eff0p paddle::framework::DeserializeFromStream(std::istream&, paddle::framework::LoDTensor*, paddle::platform::DeviceContext const&) + 576
11      0x7fec5bda5074p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::LoadLodTensor(std::istream&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::Variable*, paddle::framework::ExecutionContext const&) const + 100
12      0x7fec5bda54d0p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 432
13      0x7fec5bda5893p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
14      0x7fec5d332ec7p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
15      0x7fec5d3332a1p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
16      0x7fec5d33089cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
17      0x7fec5b42f74ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 606
18      0x7fec5b43270fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
19      0x7fec5b295efdp
20      0x7fec5b2d7186p
21      0x7fecc1a42199p PyCFunction_Call + 233
22      0x7fecc1add3f9p PyEval_EvalFrameEx + 33545
23      0x7fecc1adf4b6p
24      0x7fecc1adc5b5p PyEval_EvalFrameEx + 29893
25      0x7fecc1adf4b6p
26      0x7fecc1adc5b5p PyEval_EvalFrameEx + 29893
27      0x7fecc1adf4b6p
28      0x7fecc1adc5b5p PyEval_EvalFrameEx + 29893
29      0x7fecc1adf4b6p
30      0x7fecc1adc5b5p PyEval_EvalFrameEx + 29893
31      0x7fecc1adf4b6p
32      0x7fecc1adc5b5p PyEval_EvalFrameEx + 29893
33      0x7fecc1adf4b6p
34      0x7fecc1adc5b5p PyEval_EvalFrameEx + 29893
35      0x7fecc1add1d0p PyEval_EvalFrameEx + 32992
36      0x7fecc1adf4b6p
37      0x7fecc1adc5b5p PyEval_EvalFrameEx + 29893
38      0x7fecc1adf4b6p
39      0x7fecc1adf5a8p PyEval_EvalCodeEx + 72
40      0x7fecc1a1ec33p
41      0x7fecc19ed33ap PyObject_Call + 106
42      0x7fecc1a05d7dp
43      0x7fecc19ed33ap PyObject_Call + 106
44      0x7fecc1a5e289p
45      0x7fecc1a58fd6p
46      0x7fecc19ed33ap PyObject_Call + 106
47      0x7fecc1ad94c5p PyEval_EvalFrameEx + 17365
48      0x7fecc1adf4b6p
49      0x7fecc1adf5a8p PyEval_EvalCodeEx + 72
50      0x7fecc1adf5ebp PyEval_EvalCode + 59
51      0x7fecc1b0fa02p PyRun_FileExFlags + 178
52      0x7fecc1b0fb67p PyRun_SimpleFileExFlags + 231
53      0x7fecc1b2cd2cp Py_Main + 3676
54            0x400b54p main + 356
55      0x7fecc0aa0830p __libc_start_main + 240
56            0x400c01p

**Comment by Steffy-zxf** [comment]
参照以上错误提示，cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: CUDA driver version is insufficient for CUDA runtime version at [/paddle/paddle/fluid/platform/gpu_info.cc:97]，是环境问题，确认下cuda版本和paddle 版本是否匹配

**Comment by foreversolar** [comment]
在Aistudio中运行项目，paddlepaddle 1.5.0 hub 1.1.1 ernie 1.0.2 
仍然出现：EnforceNotMet: Input ShapeTensor cannot be found in Op reshape2 at [/paddle/paddle/fluid/framework/op_desc.cc:306]
请问怎么解决呢？

**Comment by Steffy-zxf** [comment]
参考以下解决方法
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub-FAQ#%E9%97%AE%E9%A2%98%E4%B8%80

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
