### ISSUE TITLE
Jetson AGX上安装paddlepaddle-gpu以后hub运行并没有使用GPU

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/PaddleFormers#1362]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub 2.0.0 paddlepaddle_gpu-2.0.2-cp36-cp36m-linux_aarch64.whl
2）系统环境：jetson AGX，Py36， 
安装paddlepaddle_gpu-2.0.2-cp36-cp36m-linux_aarch64.whl后，安装最新版的paddlehub。在使用ocr过程中，使用jetson-stats监控jetson agx发现paddle发现GPU的占用率最高也不到30%，但CPU却一直是满的或接近满的状态。将agx 的性能模式从30W ALL 调整至30W 4Cores后，CPU跑满，GPU不变（还是没有被调用），预测速率降低了好几倍，不知道这是什么问题

**Comment by PhilCuriosity** [comment]
未配置CUDA设备

**Comment by kractics** [comment]
请问怎么配置cuda设备啊
我已经安装了cuda和cudnn
