### ISSUE TITLE
打包成exe会产生新的进程

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleFormers#1363]
paddlehub                 2.0.4
paddlepaddle              2.0.0
pyinstaller               5.0.dev0
PyQt5                     5.15.4

打包好的exe在 语句“import paddlehub as hub” 执行时，会产生新的进程，有办法避免吗？

**Comment by nepeplwu** [comment]
@iceriver97 打包的代码是否方便发下？

**Comment by iceriver97** [comment]
你可以自行试验一下，“import paddlehub as hub”  就会导致这个问题；
```
import paddlehub as hub
human_seg = hub.Module(name="deeplabv3p_xception65_humanseg")
```

**Comment by iceriver97** [comment]
我尝试过在不同的位置执行“import paddlehub as hub ”，得到的结果有所差异，如果我在界面初始化之前执行，会连续复制几十个进程，但仅当关闭当前窗口界面后，下一个窗口界面才显示出来；若在点击按钮之后再执行，执行到‘import paddlehub as hub ’时会复制一个新的进程，这时候若继续点击按钮执行导入语句，会再产生新的进程；但如果关闭第二个窗口后，第一个窗口就会正常了，即使再点击第一个窗口的按钮，也不会再产生新的进程；
