### ISSUE TITLE
C++ Traceback (most recent call last):

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleFormers#1375]
ubuntu 16 

paddlehub               2.0.4
paddlepaddle-gpu        2.0.2

-------------
....

face_detector = hub.Module(name="pyramidbox_lite_mobile")
cap = cv2.VideoCapture(0)
ret, frame = cap.read()
result = face_detector.face_detection(images=[frame],use_gpu=True)
.....
-----------

 python aaaaa.py

/home/mm/anaconda3/envs/paddlehub/lib/python3.6/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
/home/mm/anaconda3/envs/paddlehub/lib/python3.6/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
[2021-04-20 23:38:11,997] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
W0420 23:38:11.997763 10775 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1618933094 (unix time) try "date -d @1618933094" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 10775 (TID 0x7f3d01f1b740) from PID 0 ***]

段错误 (核心已转储)

**Comment by haoyuying** [comment]
错误初步认定为cudnn和cuda及paddle的版本不匹配导致的。可以尝试cudnn使用7.6.5，cuda使用10.2，并按照https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html
安装匹配版本的paddle。
