### ISSUE TITLE
运行报错Error: Cannot open .\model_dir/steps1_116.ckpt to write at (D:\1.6.3\paddle\paddle/fluid/operators/save_combine_op.h:51)   [operator < save_combine > error]

### ISSUE THREAD

**Issue by HUI587** [PaddlePaddle/PaddleFormers#1380]
![RJRVXW1VUG_XJZ`CS7WIV6K](https://user-images.githubusercontent.com/83018645/115727075-ddc4c380-a3b5-11eb-8596-1bf7bc3e86fd.png)
![$5TWPBPO_@AN3$QN YV8J{F](https://user-images.githubusercontent.com/83018645/115727083-def5f080-a3b5-11eb-8545-3eb09b3de6b3.png)
![7804A2CLAP$@_KVPUYZH1GK](https://user-images.githubusercontent.com/83018645/115727085-def5f080-a3b5-11eb-98c9-fc839dfab5f1.png)

**Comment by haoyuying** [comment]
请问是用的paddlehub的什么模型，什么环境呢

**Comment by HUI587** [comment]
paddlepaddle 1.6.3
parl 1.3.1
实现的是四轴飞行器的悬停控制，代码用pycharm运行了就是这个样子了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleHub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 上午9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleHub] 运行报错Error: Cannot open .\model_dir/steps1_116.ckpt to write at (D:\1.6.3\paddle\paddle/fluid/operators/save_combine_op.h:51)   [operator < save_combine &gt; error] (#1380)





 
请问是用的paddlehub的什么模型，什么环境呢

**Comment by HUI587** [comment]
paddlepaddle 1.6.3
parl 1.3.1
实现的是四轴飞行器悬停控制，使用pycharm运行就这样了

**Comment by haoyuying** [comment]
您好，若您使用的是paddlehub的模型，请给出具体的模型名字，如果是paddle出现问题，请您移步到paddle的repo下提问，从而得到更专业的回复，感谢您的配合。
