### ISSUE TITLE
paddlehub2.0.4版本nlp_module.py缺少task:'text-matching'.需要发新版

### ISSUE THREAD

**Issue by paopjian** [PaddlePaddle/PaddleFormers#1381]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：
paddlehub:2.0.4
2）系统环境：win10, python3.7

pypi中paddlehub最新版本为2.0.4,使用https://github.com/PaddlePaddle/PaddleHub/blob/8c1a18eba094be319247d50d84042a1e108e3246/demo/text_matching/README.md的示例无法运行,发现在nlp_module.py的404行处_tasks_supported未添加text-matching
![image](https://user-images.githubusercontent.com/20377352/115826305-40ad6d80-a43d-11eb-9c1e-da5b37af747a.png)
![image](https://user-images.githubusercontent.com/20377352/115826322-4905a880-a43d-11eb-8c25-2f0b371db5b2.png)

**Comment by KPatr1ck** [comment]
你好，paddlehub 2.1会在这周发布，将支持文本匹配任务。

**Comment by paopjian** [comment]
那现在使用setup.py安装?

**Comment by KPatr1ck** [comment]
> 那现在使用setup.py安装?

可以，用release/v2.1分支。
