### ISSUE TITLE
使用paddlehub1.6版本加载预训练模型失败

### ISSUE THREAD

**Issue by Gray-web** [PaddlePaddle/PaddleFormers#1385]
运行具体报错如下：.
---------------------------------------------------------------------------ImportError                               Traceback (most recent call last)<ipython-input-36-ac0ee84d94bb> in <module>
      1 # 加载模型
      2 import paddlehub as hub
----> 3 module = hub.Module(name="ernie")
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in __new__(cls, name, directory, version, source, update, branch, **kwargs)
    170             module_name=name, module_version=version, extra=extra)
    171         if not result:
--> 172             logger.error(tips)
    173             raise RuntimeError(tips)
    174 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in init_with_name(cls, name, version, source, update, branch, **kwargs)
    257         return os.path.join(self.directory, MODULE_DESC_PBNAME)
    258 
--> 259     def model_path(self):
    260         return os.path.join(self.directory, MODEL_DIRNAME)
    261 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in <module>
     28 
     29 import paddlehub as hub
---> 30 from paddlehub.common import utils
     31 from paddlehub.common.downloader import default_downloader
     32 from paddlehub.common.dir import MODULE_HOME
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/common/__init__.py in <module>
     15 
     16 from . import utils
---> 17 from .utils import get_running_device_info
     18 from .dir import tmp_dir, tmp_file
ImportError: cannot import name 'get_running_device_info' from 'paddlehub.utils.utils' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/utils/utils.py)

**Comment by KPatr1ck** [comment]
你好，麻烦问下使用的paddlepaddle的版本是多少？
然后安装的ernie模型的版本号是多少？（用hub list可以查看）

如果你想用ernie模型的话，建议你升级到最新的paddlepaddle和paddlehub版本，都升级至2.0以上。

**Comment by Gray-web** [comment]
升级到最新版就可以了，感谢。
