### ISSUE TITLE
hub run 模型测试失败

### ISSUE THREAD

**Issue by zouxiaodong** [PaddlePaddle/PaddleFormers#1386]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1） paddle.__version__  '2.0.2'     paddlehub.__version__：'2.0.4'
2）ubuntu 20.04

 使用hub run 测试一个模型提示如下错误：
**hub run resnet50_vd_imagenet_ssld --input_path=test.jpg --top-k 5**

/home/robert/anaconda3/envs/xzitv/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
/home/robert/anaconda3/envs/xzitv/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
Traceback (most recent call last):
  File "/home/robert/anaconda3/envs/xzitv/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/home/robert/anaconda3/envs/xzitv/lib/python3.7/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/home/robert/anaconda3/envs/xzitv/lib/python3.7/site-packages/paddlehub/commands/run.py", line 56, in execute
    result = module._run_func(argv[1:])
**TypeError: 'property' object is not callable**

**Comment by shaunhurryup** [comment]
请问 `TypeError: 'property' object is not callable`  这个错误是如何解决的？
