### ISSUE TITLE
有关PaddleHub问题

### ISSUE THREAD

**Issue by Gray-web** [PaddlePaddle/PaddleFormers#1402]
1. 将PaddleHub预训练模型下载至本地进行迁移学习，然后使用hub serving进行部署使用的模型，部署的模型会是训练后得到的吗？
2. 使用PaddleHub迁移学习得到的best_model能否直接用于hub serving部署，如果可以该怎么做？
3. 如果best_model不能直接用于部署，需要经过什么步骤才能进行部署？
我使用的是paddlehub2.0版本

**Comment by ShenYuhan** [comment]
1 是的；
2 可以，只要其拥有一个@serving修饰的预测接口；
3 如果没有@serving预测接口，需要自行定义，保证api的入参和返回值是可以被json化的数据即可。

**Comment by Gray-web** [comment]
那请问得到best_model文件要怎么样才能部署，有没有具体步骤，我使用的paddlepaddle和paddlehub都是2.0版本的

**Comment by Gray-web** [comment]
> 1 是的；
> 2 可以，只要其拥有一个@Serving修饰的预测接口；
> 3 如果没有@Serving预测接口，需要自行定义，保证api的入参和返回值是可以被json化的数据即可。

那请问如何将得到的best_model文件夹用于部署，具体步骤是什么，有没有教程可以发一下，我使用的paddlepaddle和padlehub都是2.0版本的

**Comment by ShenYuhan** [comment]
可以参考一下这个教程 https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/docs/docs_ch/tutorial/serving.md
