### ISSUE TITLE
hub serving请求返回数据

### ISSUE THREAD

**Issue by Gray-web** [PaddlePaddle/PaddleFormers#1409]
在Windows启动hub serving，请求返回的数据该如何使用或处理，paddlehub和paddle均为2.0版本
====================请求代码如下：
```python
import requests
import json

# 指定用于获取embedding的文本[[text_1], [text_2], ... ]}
text = [["今天是个好日子"], ["天气预报说今天要下雨"]]
# 以key的方式指定text传入预测方法的时的参数，此例中为"data"
# 对应本地部署，则为module.get_embedding(data=text)
data = {"data": text}
# 发送post请求，content-type类型应指定json方式，url中的ip地址需改为对应机器的ip
url = "http://127.0.0.1:8866/predict/ernie_tiny"
# 指定post请求的headers为application/json方式
headers = {"Content-Type": "application/json"}

r = requests.post(url=url, headers=headers, data=json.dumps(data))
print(r.json())
```

=================返回数据如下：
{'msg': '', 'results': [[[0.8196346759796143, -0.2564534842967987, 0.2717680335044861, -0.8285651803016663, -0.9940673112869263, -0.6035592555999756, -0.4847404360771179, 0.999825119972229, -0.8109226822853088, 0.22210416197776794, 0.4089120030403137, 0.416570782661438, -0.9890956282615662, -0.9631263017654419, 0.10344718396663666, 0.9999669194221497, 0.8100689649581909, 0.04554236680269241, -0.44693776965141296, 0.9999998807907104, -0.13602641224861145, -0.25569528341293335, 0.32235556840896606, -0.2280748337507248, 
...
1.1045171022415161, 1.6778051853179932, -0.31823307275772095, 0.455386]]], 'status': '000'}

得到的results数据该如何使用

**Comment by KPatr1ck** [comment]
你好，示例的代码执行后，hub serving会返回预测文本的embedding，包括句子每个token的embedding和整句的embedding。

关于results的数据，详情为：
1. results里的返回是两个元素，分别对应两个输入文本`"今天是个好日子"`和`"天气预报说今天要下雨"`的embedding。
2. results[0]是一个列表，包含两个元素`[句子的embedding, 每个token的embedding]`

**Comment by Gray-web** [comment]
> 你好，示例的代码执行后，hub serving会返回预测文本的embedding，包括句子每个token的embedding和整句的embedding。
> 
> 关于results的数据，详情为：
> 
> 1. results里的返回是两个元素，分别对应两个输入文本`"今天是个好日子"`和`"天气预报说今天要下雨"`的embedding。
> 2. results[0]是一个列表，包含两个元素`[句子的embedding, 每个token的embedding]`

我现在训练了ernie_tiny这个模型做文本分类，启动hub serving服务，返回的这些数据要怎么处理才能得到我想要的结果，假设我设定它能够分类“开心”和“难过”，那results的数据该如何处理？

**Comment by KPatr1ck** [comment]
关于hub serving的服务使用，详情可以参考：[PaddleHub Serving模型一键服务部署](https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/docs/docs_ch/tutorial/serving.md#demo%E9%83%A8%E7%BD%B2%E4%B8%80%E4%B8%AA%E5%9C%A8%E7%BA%BFlac%E5%88%86%E8%AF%8D%E6%9C%8D%E5%8A%A1)

> 我现在训练了ernie_tiny这个模型做文本分类，启动hub serving服务，返回的这些数据要怎么处理才能得到我想要的结果，假设我设定它能够分类“开心”和“难过”，那results的数据该如何处理？

你需要使用hub serving，并使用相关的配置去指定你的模型和预测相关的参数，一个可用的配置如下：
```json
{
  "modules_info": {
    "ernie_tiny": {
      "init_args": {
        "task": "seq-cls",
        "version": "2.0.2",
        "load_checkpoint": "./best_model/model.pdparams",
        "label_map": {"0": "negative", "1": "positive"},
        "num_classes": 2
      },
      "predict_args": {
        "batch_size": 1,
        "use_gpu": false
      }
    }
  },
  "port": 8866
}
```

注意需要指定`load_checkpoint`参数，选择可用的checkpoint，保存配置后使用下面命令启动服务
```shell
hub serving start -c serving_config.json
```

发送预测请求后返回的结果类似：
```
{'msg': '', 'results': ['positive', 'positive'], 'status': '000'}
```

**Comment by Gray-web** [comment]
> 关于hub serving的服务使用，详情可以参考：[PaddleHub Serving模型一键服务部署](https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/docs/docs_ch/tutorial/serving.md#demo%E9%83%A8%E7%BD%B2%E4%B8%80%E4%B8%AA%E5%9C%A8%E7%BA%BFlac%E5%88%86%E8%AF%8D%E6%9C%8D%E5%8A%A1)
> 
> > 我现在训练了ernie_tiny这个模型做文本分类，启动hub serving服务，返回的这些数据要怎么处理才能得到我想要的结果，假设我设定它能够分类“开心”和“难过”，那results的数据该如何处理？
> 
> 你需要使用hub serving，并使用相关的配置去指定你的模型和预测相关的参数，一个可用的配置如下：
> 
> ```json
> {
>   "modules_info": {
>     "ernie_tiny": {
>       "init_args": {
>         "task": "seq-cls",
>         "version": "2.0.2",
>         "load_checkpoint": "./best_model/model.pdparams",
>         "label_map": {"0": "negative", "1": "positive"},
>         "num_classes": 2
>       },
>       "predict_args": {
>         "batch_size": 1,
>         "use_gpu": false
>       }
>     }
>   },
>   "port": 8866
> }
> ```
> 
> 注意需要指定`load_checkpoint`参数，选择可用的checkpoint，保存配置后使用下面命令启动服务
> 
> ```shell
> hub serving start --config config.json
> ```
> 
> 发送预测请求后返回的结果类似：
> 
> ```
> {'msg': '', 'results': ['positive', 'positive'], 'status': '000'}
> ```

那这个json文件需要存放在哪个目录下，还是说任意存放，执行命令时指定路径就可以

**Comment by KPatr1ck** [comment]
> 那这个json文件需要存放在哪个目录下，还是说任意存放，执行命令时指定路径就可以

任意路径，执行时指定。

**Comment by Gray-web** [comment]
> > 那这个json文件需要存放在哪个目录下，还是说任意存放，执行命令时指定路径就可以
> 
> 任意路径，执行时指定。

好的，非常感谢！
