### ISSUE TITLE
使用示例之外的模型fine tune出错

### ISSUE THREAD

**Issue by jxy-1017** [PaddlePaddle/PaddleFormers#1429]
示例中使用的模型为resnet50_vd_imagenet_ssld，能够正常训练。（paddlepaddle=2.0.2,paddlehub=2.1.0）
训练代码：
model = hub.Module(name='efficientnetb7_imagenet',
                   label_list=["roses", "tulips", "daisy", "sunflowers", "dandelion"],
                   load_checkpoint=None)

optimizer = paddle.optimizer.Adam(learning_rate=0.001, parameters=model.parameters())
trainer = Trainer(model, optimizer, checkpoint_dir='./img_classification_ckpt', use_gpu=True)
trainer.train(flowers, epochs=1, batch_size=8, eval_dataset=flowers_validate, save_interval=1)

但我使用其他模型如efficientnetb7_imagenet（即实例中所说的无缝修改模型）进行同样操作，报错如下：
TypeError: _initialize() got an unexpected keyword argument 'label_list'

如果将上述代码中的label_list=["roses", "tulips", "daisy", "sunflowers", "dandelion"],去掉
报的错误是：
AttributeError: 'EfficientNetB7ImageNet' object has no attribute 'parameters'

在1.6.2版本的paddlehub下用其他方式能完成finetune。
谢谢解答！

**Comment by haoyuying** [comment]
您好，目前efficientnetb7_imagenet暂时不支持动态图版本，陆续paddlehub会支持，敬请期待。

**Comment by jxy-1017** [comment]
谢谢您的回答！
我尝试的hub图像分类中的其他的模型也不能使用，比如“alexnet_imagenet、vgg19_imagenet”等等。
是不是现在仅支持示例中的“resnet50_vd_imagenet_ssld”模型，或者您可以提供哪些模型支持这种用法吗？

**Comment by haoyuying** [comment]
目前动态图版本仅支持resnet50_vd_imagenet_ssld

**Comment by jxy-1017** [comment]
好的，谢谢！
