### ISSUE TITLE
paddlehub情感分析模型senta_bilstm离线下载后，hub run报错：无法连接hub service

### ISSUE THREAD

**Issue by jxufeRebecca** [PaddlePaddle/PaddleFormers#1433]
下载了paddlepaddle、paddlehub最新的版本，
系统环境：linux，python 3.6
由于无法访问外网，想离线调用情感分析模型，先用一台可以连上外网的电脑装了senta_bilstm的包，传到服务器的paddlehub/modules路径下，可以成功hub install,但是hub run就会报错说无法连接到Hub service
请问该怎么解决呀？

**Comment by KPatr1ck** [comment]
你好，senta_bilstm里还用到了lac，可能是这个逻辑触发了下载。
你可以尝试将lac也离线下载，放进去后再运行。
https://github.com/PaddlePaddle/PaddleHub/blob/b100dc5d8f740c1d2402dc6e3a2d515ebcc0b3a6/modules/text/sentiment_analysis/senta_bilstm/module.py#L47

**Comment by jxufeRebecca** [comment]
> 你好，senta_bilstm里还用到了lac，可能是这个逻辑触发了下载。
> 你可以尝试将lac也离线下载，放进去后再运行。
> https://github.com/PaddlePaddle/PaddleHub/blob/b100dc5d8f740c1d2402dc6e3a2d515ebcc0b3a6/modules/text/sentiment_analysis/senta_bilstm/module.py#L47

谢谢！就是这个问题，已经解决了 非常感谢
