### ISSUE TITLE
hub serving start -m sena_bilstm 启动正常，访问后提示"status":"111"

### ISSUE THREAD

**Issue by 249805118** [PaddlePaddle/PaddleFormers#1436]
项目启动后，访问接口返回下面提示。这是什么原因呢
{"msg":"Module sena_bilstm is not available.","results":"","status":"111"}

**Comment by KPatr1ck** [comment]
你好，方便的话麻烦提供一下接口调用的脚本。
PaddleHub里目前没有`sena_bilstm`这个模型，可能是你名字输入错了，建议改成`senta_bilstm`试一下。

**Comment by 249805118** [comment]
是我写错了，尴尬，谢谢啦
