### ISSUE TITLE
官方提供的文档有问题

### ISSUE THREAD

**Issue by allenxln** [PaddlePaddle/PaddleFormers#1455]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1） hub 2.1.0
2）python3.8。 系统 阿里云的标准 centos。
- 复现步骤：按照官方文档的搭建服务流程，没问题，但是python写程序访问服务流程的时候，一直访问不了，提示 少了一个 predict_args 字段。

https://www.paddlepaddle.org.cn/hubdetail?name=lac&en_category=LexicalAnalysis
报错信息如下：

![image](https://user-images.githubusercontent.com/19772008/120991226-019c6700-c7b4-11eb-9a62-c83e8b193854.png)

同时，import request 一直提示有问题，后来发现少了个s，应该是 import requests……

**Comment by KPatr1ck** [comment]
你好，非常感谢你的反馈。
经检查，链接中提供的配置文件和预测脚本确实存在问题。对于你目前遇到的问题的解决办法如下：

1. 在配置中加入predict_args键值对，更改后的配置文件参考：
   ```json
   {
     "modules_info": {
       "lac": {
         "init_args": {
           "version": "2.2.0"
         },
         "predict_args": {}
       }
     },
     "port": 8866,
     "use_singleprocess": false,
     "workers": 2
   }
   ```
2. `import request` -> `import requests`
