### ISSUE TITLE
希望有一个问题语义相似度得DEMO

### ISSUE THREAD

**Issue by xinaiwunai** [PaddlePaddle/PaddleFormers#147]
我看了几乎所有得Paddle Hub在GitHub上提供得所有NLP demo。都没有找到我想要得。因为我正计划做一个检索式问答系统(和官方提供得“检索式问答”并不是同一种，是的，我原本满心欢喜，结果却发现事实和我想象的不一样)。
我指得的检索式问答，是指可以将用户的提问与已知的问答库中的”问题“进行相似度排序，找到最相似的问题，并以该问题的答案进行回答。
我并没有看到有这样的demo。
非常希望官方能提供一个该功能的Demo。

**Comment by Steffy-zxf** [comment]
感谢反馈！参看simnet_bow module是否符合您的需求
https://www.paddlepaddle.org.cn/hubdetail?name=simnet_bow&en_category=SemanticModel

**Comment by xinaiwunai** [comment]
> 感谢反馈！参看simnet_bow module是否符合您的需求
> https://www.paddlepaddle.org.cn/hubdetail?name=simnet_bow&en_category=SemanticModel

非常棒，这就是我要的。太感谢了。另外也希望能把这个案例做到GitHub的Demo中！

**Comment by Steffy-zxf** [comment]
您写好这个demo后，欢迎给PaddleHub提PR.

**Comment by xinaiwunai** [comment]
PS E:\paddlehub\models\PaddleNLP\similarity_net> python run_classifier.py    --task_name 'wyh_simmilarity_net_fine_tune_
test'    --use_cuda false     --do_train True      --do_valid True      --do_test True       --do_infer True     --batch
_size 128     --train_data_dir ./data/qqsim     --valid_data_dir ./data/test_pointwise_data     --test_data_dir ./data/t
est_pointwise_data       --infer_data_dir ./data/infer_data     --output_dir ./model_files               --config_path .
/config/bow_pointwise.json            --vocab_path ./data/term2id.dict              --epoch 10        --save_steps 1000
     --validation_steps 100     --task_mode 'pointwise'    --compute_accuracy False       --lamda 0.958
-----------  Configuration Arguments -----------
batch_size: 128
compute_accuracy: False
config_path: ./config/bow_pointwise.json
do_infer: True
do_test: True
do_train: True
do_valid: True
enable_ce: False
epoch: 10
infer_data_dir: ./data/infer_data
infer_result_path: infer_result
init_checkpoint: None
lamda: 0.958
output_dir: ./model_files
save_steps: 1000
skip_steps: 10
task_mode: pointwise
task_name: wyh_simmilarity_net_fine_tune_test
test_data_dir: ./data/test_pointwise_data
test_result_path: test_result
train_data_dir: ./data/qqsim
use_cuda: False
valid_data_dir: ./data/test_pointwise_data
validation_steps: 100
verbose_result: True
vocab_path: ./data/term2id.dict
------------------------------------------------

**Comment by xinaiwunai** [comment]
训练之后，为什么没有模型文件输出呢？在output_dir: ./model_files看不到任何文件？

**Comment by Steffy-zxf** [comment]
PaddleHub simnet_bow module用于计算两个文本的语义相似度，只适合用于预测。如果您想在simnet_bow基础上接着finetune，则PaddleHub simnet_bow module无法满足您的需求。另外关于models的问题，建议您在https://github.com/PaddlePaddle/models下提issue。

**Comment by xinaiwunai** [comment]
谢谢
