### ISSUE TITLE
pycharm配置paddle环境出错

### ISSUE THREAD

**Issue by TLTLHILL** [PaddlePaddle/PaddleFormers#1479]
![%0XQ{)0GQLD`KQ53%$OX(_N](https://user-images.githubusercontent.com/85716726/121616627-ce98f280-ca95-11eb-9586-6cb54d8f386a.png)
该下载的东西下载了，环境变量也设置了还是这样

**Comment by haoyuying** [comment]
您好，您可以到paddle官方repo下提问该问题，以便得到更好的专业的解决方案。https://github.com/PaddlePaddle/Paddle
