### ISSUE TITLE
nlp序列标注时候报错:The length of tokens must be same with labels

### ISSUE THREAD

**Issue by suntao2015005848** [PaddlePaddle/PaddleFormers#1487]
paddlepaddle-gpu==1.8.5.post97
paddlehub==1.8.2
ernie==1.2.0
报错：
`Traceback (most recent call last):   File "module.py", line 136, in <module>     law_ernie = ERNIELAWFinetuned(ckpt_dir="/home/aistudio/es_005/mod/es005_mod", use_gpu=True)   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 122, in __new__     directory=directory, **kwargs)   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 200, in init_with_directory     user_module = _item(directory=directory, **kwargs)   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 146, in __init__     self._initialize(**kwargs)   File "/home/aistudio/es_005/mod/module.py", line 90, in _initialize     self.seq_label_task.finetune_and_eval()   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 945, in finetune_and_eval     return self.finetune(do_eval=True)   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 960, in finetune     self.init_if_necessary()   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 384, in init_if_necessary     if not self.load_checkpoint():   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 911, in load_checkpoint     main_program=self.main_program)   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 545, in main_program     self._build_env()   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 458, in _build_env     self.dataset.get_train_records())   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/dataset/base_nlp_dataset.py", line 192, in get_train_records     return self.get_records("train", shuffle=shuffle)   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/dataset/base_nlp_dataset.py", line 208, in get_records     records = self.train_records   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/dataset/base_nlp_dataset.py", line 73, in train_records     examples, phase="train")   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/dataset/base_nlp_dataset.py", line 489, in _convert_examples_to_records     labels=example.label.split(self.split_char))   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/dataset/base_nlp_dataset.py", line 521, in _reseg_token_label     "The length of tokens must be same with labels") ValueError: The length of tokens must be same with labels`

**Comment by KPatr1ck** [comment]
你好，请问下用的是什么模型和数据集？
方便的话麻烦把可复现的代码贴在issue里，可以快速协助你定位问题。

此外，PaddleHub 2.0+已经支持序列标注任务，环境可以升级的话建议更新到最新的2.1版本。
2.0+的序列标注任务，可以参考：[PaddleHub Transformer模型fine-tune序列标注（动态图）](https://github.com/PaddlePaddle/PaddleHub/tree/release/v2.1/demo/sequence_labeling)
如需在自定义数据集finetune，可以参考：[PaddleHub2.0——使用动态图版预训练模型ERNIE实现快递单信息抽取
](https://aistudio.baidu.com/aistudio/projectdetail/1467763)

**Comment by suntao2015005848** [comment]
目前的需求是基于paddlehub 1.8的不能升到2.0， 用的模型师ernie==1.2.0 。数据集是自定义且自己人工标注的数据集：
执行到此过程时候：
[2021-06-21 14:07:20,846] [    INFO] - Processing the train set...
  4%|██▊                                                                           | 115/3160 [00:00<00:04, 754.70it/s]
Traceback (most recent call last):
ValueError: The length of tokens must be same with labels
报标签和文本长度不一致错误，但是经过排查并未发现115条数据处出现标签和数据长度不一致。

**Comment by KPatr1ck** [comment]
> 目前的需求是基于paddlehub 1.8的不能升到2.0， 用的模型师ernie==1.2.0 。数据集是自定义且自己人工标注的数据集：
> 执行到此过程时候：
> [2021-06-21 14:07:20,846] [ INFO] - Processing the train set...
> 4%|██▊ | 115/3160 [00:00<00:04, 754.70it/s]
> Traceback (most recent call last):
> ValueError: The length of tokens must be same with labels
> 报标签和文本长度不一致错误，但是经过排查并未发现115条数据处出现标签和数据长度不一致。

关于自定义数据集在paddlehub 1.8中的添加方式，请参考以下项目：
[PaddleHub实战——使用语义预训练模型ERNIE优化快递单信息抽取](https://aistudio.baidu.com/aistudio/projectdetail/184200)

已在paddlehub 1.8.0和ernie 1.2.0的环境下测试可正常执行。
