### ISSUE TITLE
序列标注任务在预测时无法对空格进行标注

### ISSUE THREAD

**Issue by BossRobin** [PaddlePaddle/PaddleFormers#1489]
我训练完示例的模型后，运行https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/demo/sequence_labeling/predict.py
中的代码进行推理。

```
输入文本：
华裔作家韩素音女士曾三次到大足，称“大足石窟是一座未被开发的金矿”。
输出为：
B-LOC, O, O, O, B-PER, I-PER, I-PER, O, O, O, O, O, O, O, I-LOC, O, O, O, B-LOC, I-LOC, I-LOC, I-LOC, O, O, O, O, O, O, O, O, O, O, O, O

输入文本：
华裔作家 韩素音 女士曾三次到大足，称“大足石窟是一座未被开发的金矿”。
输出为：
B-LOC, O, O, O, B-PER, I-PER, I-PER, O, O, O, O, O, O, O, I-LOC, O, O, O, B-LOC, I-LOC, I-LOC, I-LOC, O, O, O, O, O, O, O, O, O, O, O, O, O, O

输入文本：
华裔作家                韩素音 女士曾三次到大足，称“大足石窟是一座未被开发的金矿”。
输出为：
B-LOC, O, O, O, B-PER, I-PER, I-PER, O, O, O, O, O, O, O, I-LOC, O, O, O, B-LOC, I-LOC, I-LOC, I-LOC, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O
```

我的问题是针对输入文本中的空格，为什么输出会出现现在这样的结果呢？

配置
paddlehub           2.1.0
paddlenlp           2.0.2
paddlepaddle-gpu    2.1.0.post101
Linux python3.6.9

**Comment by KPatr1ck** [comment]
```python
输入文本：
华裔作家                韩素音 女士曾三次到大足，称“大足石窟是一座未被开发的金矿”。
输出为：
B-LOC, O, O, O, B-PER, I-PER, I-PER, O, O, O, O, O, O, O, I-LOC, O, O, O, B-LOC, I-LOC, I-LOC, I-LOC, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O
```

你好，输入的空格会在文本预处理的时候被sentencepiece过滤，可参考此处代码：
https://github.com/PaddlePaddle/PaddleHub/blob/0b963719db0422a0507959ed709606e389d845c1/paddlehub/module/nlp_module.py#L419
https://github.com/PaddlePaddle/PaddleHub/blob/0b963719db0422a0507959ed709606e389d845c1/paddlehub/utils/utils.py#L333

**Comment by BossRobin** [comment]
> ```python
> 输入文本：
> 华裔作家                韩素音 女士曾三次到大足，称“大足石窟是一座未被开发的金矿”。
> 输出为：
> B-LOC, O, O, O, B-PER, I-PER, I-PER, O, O, O, O, O, O, O, I-LOC, O, O, O, B-LOC, I-LOC, I-LOC, I-LOC, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O
> ```
> 
> 你好，输入的空格会在文本预处理的时候被sentencepiece过滤，可参考此处代码：
> https://github.com/PaddlePaddle/PaddleHub/blob/0b963719db0422a0507959ed709606e389d845c1/paddlehub/module/nlp_module.py#L419
> 
> 
> https://github.com/PaddlePaddle/PaddleHub/blob/0b963719db0422a0507959ed709606e389d845c1/paddlehub/utils/utils.py#L333

好的，明白了~
请问这么做的原因是什么呢？我的训练数据中存在这种有空格的句子，训练的时候没有什么问题。请问训练的过程中也会将空格过滤掉吗？还是只有在推理的时候会这么做呢

**Comment by BossRobin** [comment]
> ```python
> 输入文本：
> 华裔作家                韩素音 女士曾三次到大足，称“大足石窟是一座未被开发的金矿”。
> 输出为：
> B-LOC, O, O, O, B-PER, I-PER, I-PER, O, O, O, O, O, O, O, I-LOC, O, O, O, B-LOC, I-LOC, I-LOC, I-LOC, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O
> ```
> 
> 你好，输入的空格会在文本预处理的时候被sentencepiece过滤，可参考此处代码：
> https://github.com/PaddlePaddle/PaddleHub/blob/0b963719db0422a0507959ed709606e389d845c1/paddlehub/module/nlp_module.py#L419
> 
> 
> https://github.com/PaddlePaddle/PaddleHub/blob/0b963719db0422a0507959ed709606e389d845c1/paddlehub/utils/utils.py#L333

明白了，感谢~
