### ISSUE TITLE
使用paddlehub微调分类任务，多分类任务，怎么增加一个“其他”类别让模型没见过的数据都分到其他类别上去呢

### ISSUE THREAD

**Issue by ForFishes** [PaddlePaddle/PaddleFormers#1506]
麻烦相关同学，帮忙看看这个Paddle下的issue
https://github.com/PaddlePaddle/Paddle/issues/33773

**Comment by KPatr1ck** [comment]
https://github.com/PaddlePaddle/PaddleHub/issues/1515
