### ISSUE TITLE
paddlehub.finetue.Trainer中checkpoint保存逻辑调整

### ISSUE THREAD

**Issue by XiaoqingWang** [PaddlePaddle/PaddleFormers#1509]
paddlehub.finetue.Trainer中checkpoint保存逻辑调整
1）PaddleHub 2.0及以上
2）所有环境Linux/Windows/MacOS/，python 3
checkpoint保存判断现有逻辑有一些问题，比较难达到预期的指定步数保存，需要调整逻辑（代码第238行）

**Comment by XiaoqingWang** [comment]
关联的调整的pull request  
https://github.com/PaddlePaddle/PaddleHub/pull/1510

**Comment by KPatr1ck** [comment]
https://github.com/PaddlePaddle/PaddleHub/pull/1510#pullrequestreview-694534468
你好，pr内容已经添加reivew意见，方便的话讲述一下修改的目的和修改前后代码逻辑的不同。
感谢你对PaddleHub Repo的贡献～
