### ISSUE TITLE
ace2p为啥没脖子 :(

### ISSUE THREAD

**Issue by h3clikejava** [PaddlePaddle/PaddleFormers#1516]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：

一整串语意都有了，咋把脖子给丢了。。。
有谁可以推荐一个比较好的皮肤分割模型吗?

**Comment by haoyuying** [comment]
您好，paddlehub暂时没有这类模型，您使用的场景是什么，具体有什么需求呢，我们可以根据您的需求之后扩充paddlehub的模型库，当然若您有好的模型，也可以提供给我们，感谢您对开源社区的建议和贡献。

**Comment by ajiansoft** [comment]
使用最新的代码还是没有脖子，好不容易找到个这么好用的模型，咋就没脖子呢，，，
