### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'Tensor'

### ISSUE THREAD

**Issue by woshixioahu** [PaddlePaddle/PaddleFormers#1517]
AnimeGAN动漫化模型一键应用实例教程中
!pip install -U paddlehub==2.0.0b1 
输出照片时出现
---------------------------------------------------------------------------AttributeError                            Traceback (most recent call last)<ipython-input-11-9a85f7c12975> in <module>
      2 
      3 import cv2
----> 4 import paddlehub as hub
      5 
      6 # 模型加载
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/__init__.py in <module>
     22 from paddlehub import env
     23 from paddlehub.config import config
---> 24 from paddlehub import datasets
     25 from paddlehub.finetune import Trainer
     26 from paddlehub.utils import log, parser, utils
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/datasets/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from paddlehub.datasets.canvas import Canvas
     16 from paddlehub.datasets.flowers import Flowers
     17 from paddlehub.datasets.minicoco import MiniCOCO
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/datasets/canvas.py in <module>
     21 
     22 import paddlehub.env as hubenv
---> 23 from paddlehub.vision.utils import get_img_file
     24 from paddlehub.utils.download import download_data
     25 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/vision/utils.py in <module>
    157 
    158 
--> 159 def subtract_imagenet_mean_batch(batch: paddle.Tensor) -> paddle.Tensor:
    160     """Subtract ImageNet mean pixel-wise from a BGR image."""
    161     mean = np.zeros(shape=batch.shape, dtype='float32')
AttributeError: module 'paddle' has no attribute 'Tensor'

**Comment by haoyuying** [comment]
您好，建议您使用最新版的paddle和paddlehub，目前定位的问题是您的paddle版本过低导致该问题。

**Comment by woshixioahu** [comment]
谢谢，确实是没有安装最新的paddle,解决了
