### ISSUE TITLE
关于hub serving部署应用后的跨域访问问题

### ISSUE THREAD

**Issue by huangcao008** [PaddlePaddle/PaddleFormers#1523]
有这样的需求,同域名下的不同端口服务需要访问hub serving部署的接口，但是存在跨域问题，请问在hub serving有什么办法处理？

**Comment by KPatr1ck** [comment]
你好，想问下你当前使用的paddlehub版本是多少？
如果方便请尽可能详细地描述一下 hub serving的部署和调用方式的。

**Comment by huangcao008** [comment]
> 你好，想问下你当前使用的paddlehub版本是多少？
> 如果方便请尽可能详细地描述一下 hub serving的部署和调用方式的。

hub 2.1.0,我是使用docker部署
hub serving start --modules Prediction_Module --port 8866 启动服务
另外一台服务器的前端直接调用的启动后的服务

**Comment by SPDB-foss** [comment]
It works for cross-domain [https://github.com/PaddlePaddle/PaddleHub/pull/1567](url)

**Comment by ghost** [comment]
It works for cross-domain #1567

**Comment by shwanliu** [comment]
> It works for cross-domain #1567

cool！thks！
