### ISSUE TITLE
hub启动模型失败

### ISSUE THREAD

**Issue by suntao2015005848** [PaddlePaddle/PaddleFormers#1526]
paddlepaddle-gpu ==2.1.0
paddlehub == 2.0.4
paddlenlp == 2.0.1
添加--use_gpu参数报:
启动命令：hub serving start -m lac --port 6692 --use_gpu
`/usr/local/python3/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/local/python3/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/usr/local/python3/lib/python3.7/site-packages/scipy/linalg/__init__.py:217: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/usr/local/python3/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
/usr/local/python3/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:130: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
[2021-07-09 15:17:27 +0800] [44634] [INFO] Starting gunicorn 20.1.0
[2021-07-09 15:17:27 +0800] [44634] [INFO] Listening at: http://0.0.0.0:6692 (44634)
[2021-07-09 15:17:27 +0800] [44634] [INFO] Using worker: sync
[2021-07-09 15:17:27 +0800] [44639] [INFO] Booting worker with pid: 44639
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/serving/worker.py", line 24
    def run_worker(modules_info: dict, gpu_index: int, addr: str):
                               ^
SyntaxError: invalid syntax`

**Comment by suntao2015005848** [comment]
python版本是3.7.5

**Comment by suntao2015005848** [comment]
CUDA Version 10.2.89

**Comment by KPatr1ck** [comment]
```shell
启动命令：hub serving start -m lac --port 6692 --use_gpu
```
你好，在以下环境测试可以正常执行上面命令。
```shell
Python                 3.6.12
paddlehub              2.1.0
paddlenlp              2.0.3
paddlepaddle-gpu       2.1.0
```

```python
[2021-07-09 15:17:27 +0800] [44639] [INFO] Booting worker with pid: 44639 File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/serving/worker.py", line 24 def run_worker(modules_info: dict, gpu_index: int, addr: str): ^ SyntaxError: invalid syntax
```
关于你运行时的报错，像是`/usr/local/python3/lib/python3.7/site-packages/paddlehub/serving/worker.py`这个文件有语法错误，建议检查一下有没被修改了，或者可以尝试重新安装paddlehub。

**Comment by suntao2015005848** [comment]
这个问题已经解决，是python环境的问题，paddlehub的work.py必须依赖的是 python -V 是3.7的，如果默认环境的python是2.7.5，就会报错，希望官网说明。我的机器是有两个版本的python，默认python是2.7.5.
