### ISSUE TITLE
serving http_server 返回的结果在msg中而不是result中

### ISSUE THREAD

**Issue by no7wan7** [PaddlePaddle/PaddleFormers#1539]
在使用hub serving时，返回的预测结果在msg字段中，之前都是在result中。
错误出现在以下代码段：
https://github.com/PaddlePaddle/PaddleHub/blob/f743bf9a3aecaf169bf60d63049b33ff50355495/paddlehub/serving/http_server.py#L133
在这段方法中，package_result方法传参位置错误，导致预测结果到了msg中。
错误的具体位置：
https://github.com/PaddlePaddle/PaddleHub/blob/f743bf9a3aecaf169bf60d63049b33ff50355495/paddlehub/serving/http_server.py#L146
https://github.com/PaddlePaddle/PaddleHub/blob/f743bf9a3aecaf169bf60d63049b33ff50355495/paddlehub/serving/http_server.py#L151
https://github.com/PaddlePaddle/PaddleHub/blob/f743bf9a3aecaf169bf60d63049b33ff50355495/paddlehub/serving/http_server.py#L159

**Comment by KPatr1ck** [comment]
非常感谢您的反馈～
predict_serving目前两版接口中，返回结果的键值对存在不对应的问题，这个问题将会统一修复。
如果需求紧急可先从对应的key中取处预测结果。
