### ISSUE TITLE
cls_task.predict 可以获得各标签的概率吗？

### ISSUE THREAD

**Issue by foreversolar** [PaddlePaddle/PaddleFormers#155]
cls_task.predict 可以获得各标签的概率吗？

**Comment by Steffy-zxf** [comment]
感谢反馈！cls_task.predict() 接口可以获得各标签的概率，参考以下代码：
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.1.0/demo/text-classification/predict.py#L157
results就是所有预测样本对应各标签的概率值

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
