### ISSUE TITLE
conv2d(): argument 'Filter' (position 1) must be Tensor, but got Parameter

### ISSUE THREAD

**Issue by FrankWhh** [PaddlePaddle/PaddleFormers#1554]
利用paddlehub部署DeepSpeech2模型，报**ValueError: (InvalidArgument) conv2d(): argument 'Filter' (position 1) must be Tensor, but got Parameter (at /paddle/paddle/fluid/pybind/op_function.h:56)**。
paddlehub版本2.1.0/2.0.0，DeepSpeech2模型本身调用运行预测没问题，在paddlehub里就会报错，即使是跑warm_up_test。
File "/opt/anaconda3/lib/python3.7/site-packages/paddlehub/serving/app_compat.py", line 87, in predict_v2
    output = serving_method(**predict_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/paddlehub/module/module.py", line 63, in _wrapper
    return func(*args, **kwargs)
  File "/home/ailab/.paddlehub/modules/voice_recognition_deepspeech2/module.py", line 134, in serving_method
    num_test_cases=3)
  File "DeepSpeech2/deepspeech/utils/socket_server.py", line 52, in warm_up_test
    transcript = audio_process_handler(sample['audio_filepath'])
  File "/opt/anaconda3/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/home/ailab/.paddlehub/modules/voice_recognition_deepspeech2/module.py", line 106, in file_to_transcript
    num_processes=self.config.decoding.num_proc_bsearch)
  File "</opt/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-233>", line 2, in decode
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 315, in _decorate_function
    return func(*args, **kwargs)
  File "DeepSpeech2/deepspeech/models/deepspeech2.py", line 208, in decode
    eouts, eouts_len = self.encoder(audio, audio_len)
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "DeepSpeech2/deepspeech/models/deepspeech2.py", line 94, in forward
    **x, x_lens = self.conv(x, x_lens)**
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "DeepSpeech2/deepspeech/modules/conv.py", line 144, in forward
    **x, x_len = self.conv_in(x, x_len)**
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "DeepSpeech2/deepspeech/modules/conv.py", line 85, in forward
    x = self.conv(x)
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 660, in forward
    use_cudnn=self._use_cudnn)
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 119, in _conv_nd
    pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)
ValueError: (InvalidArgument) conv2d(): argument 'Filter' (position 1) must be Tensor, but got Parameter (at /paddle/paddle/fluid/pybind/op_function.h:56)

打印x,x_lens，未发现问题
Tensor(shape=[1, 1, 161, 135], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[[[-2.25398755, -2.11723757, -2.10718966, ..., -1.49337590, -1.63317239, -2.11299682],
          [-2.71892667, -2.64595103, -2.67157292, ..., -1.91262162, -2.25656271, -2.62241554],
          [-2.95244622, -2.86706758, -2.82853651, ..., -2.21879625, -2.50305438, -2.95195198],
          ...,
          [-1.53820324, -0.70819622, -1.07595241, ..., -0.62452424, -1.55061817, -1.44218242],
          [-1.48655856, -0.58279842, -1.39044034, ..., -0.19443606, -1.33336318, -1.26881135],
          [-1.12830818, -0.42334875, -1.07599461, ..., -0.21980844, -0.95654881, -0.84670091]]]])
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [135])

**Comment by KPatr1ck** [comment]
你好，请问你通过何种方式部署DeepSpeech2模型的呢？
能否提供当前使用的DeepSpeech2的预测脚本、预训练模型和paddlehub的部署步骤和脚本？

**Comment by FrankWhh** [comment]
DeepSpeech2模型近10G，实在需要的话我传到百度网盘
这边我看之前有人遇到同样的error：https://github.com/PaddlePaddle/Paddle/issues/31842，不知道这个后续有没有解决

**Comment by KPatr1ck** [comment]
> DeepSpeech2模型近10G，实在需要的话我传到百度网盘
> 这边我看之前有人遇到同样的error：[https://github.com/PaddlePaddle/Paddle/issues/31842，不知道这个后续有没有解决](https://github.com/PaddlePaddle/Paddle/issues/31842%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E8%BF%99%E4%B8%AA%E5%90%8E%E7%BB%AD%E6%9C%89%E6%B2%A1%E6%9C%89%E8%A7%A3%E5%86%B3)

你是如何将模型放在paddlehub上部署的呢？
另外这个问题可能需要确认一下DeepSpeech模型正常使用时的paddle环境，最好保证部署时用到的paddle版本是一致的。

**Comment by FrankWhh** [comment]
修改好module.py文件后，放入DeepSpeech中，hub install DeepSpeech这个文件夹。paddle环境跟正常使用是一样的

**Comment by KPatr1ck** [comment]
> 修改好module.py文件后，放入DeepSpeech中，hub install DeepSpeech这个文件夹。paddle环境跟正常使用是一样的

module.py文件的脚本是否方便粘贴一下？
我可以不下载checkpoint，用你的module.py先测试一下能否跑通。

**Comment by FrankWhh** [comment]
链接：https://pan.baidu.com/s/10KnCejWl8jwLdf_dxhYR1w 
提取码：kaqm

**Comment by KPatr1ck** [comment]
```python
@moduleinfo(
    name="voice_recognition_deepspeech2",
    version="1.0.0",
    summary="chinese speech recognition",
    author="haihua.wu",
    author_email="123456",
    type="speech/recognition")
class ChineseDeepSpeech2(hub.Module):
    def _initialize(self):
        """
        initialize with the necessary elements
        """
        self.config = self.merge_configs()
```

PaddleHub 2.0+的module封装方式不需要继承hub.Module，请参考[如何创建自己的Module](https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/docs/docs_ch/tutorial/custom_module.rst#%E6%AD%A5%E9%AA%A4-3_3-%E6%89%A7%E8%A1%8C%E5%BF%85%E8%A6%81%E7%9A%84%E5%88%9D%E5%A7%8B%E5%8C%96)修改至最新的样式后，重新安装再测试运行。

**Comment by FrankWhh** [comment]
OCR模型继承可以跑的呀，继承这个会导致这个error吗？

**Comment by KPatr1ck** [comment]
> OCR模型继承可以跑的呀，继承这个会导致这个error吗？

DeepSpeech2的repo上介绍是依赖paddlepaddle>=2.1.0，所以可以按照新的方式封装，可避免一些潜在的兼容性问题。

**Comment by FrankWhh** [comment]
我训练的DeepSpeech2是基于paddle2.0的，另我按照Paddlehub2.0+修改module至最新样式，会报hub参数错误：
usage: hub [-h] [--config FILE] [--dump-config FILE] [--output OUTPUT_DIR]
           [--checkpoint_path CHECKPOINT_PATH] [--export_path EXPORT_PATH]
           [--device {cpu,gpu}] [--nprocs NPROCS] [--opts OPTS [OPTS ...]]
           [--host_ip HOST_IP] [--host_port HOST_PORT]
           [--speech_save_dir SPEECH_SAVE_DIR]
           [--warmup_manifest WARMUP_MANIFEST]
hub: error: unrecognized arguments: serving start -c config.json
-------------------------------------------------
class ChineseDeepSpeech2():
    def __init__(self):
        """
        initialize with the necessary elements
        """
        self.args = default_argument_parser()
        self.config = get_cfg_defaults()
        
        if self.args.config:
            self.config.merge_from_file(self.args.config)
        if self.args.opts:
            self.config.merge_from_list(self.args.opts)

**Comment by KPatr1ck** [comment]
> ## 我训练的DeepSpeech2是基于paddle2.0的，另我按照Paddlehub2.0+修改module至最新样式，会报hub参数错误：
> usage: hub [-h] [--config FILE] [--dump-config FILE] [--output OUTPUT_DIR]
> [--checkpoint_path CHECKPOINT_PATH] [--export_path EXPORT_PATH]
> [--device {cpu,gpu}] [--nprocs NPROCS] [--opts OPTS [OPTS ...]]
> [--host_ip HOST_IP] [--host_port HOST_PORT]
> [--speech_save_dir SPEECH_SAVE_DIR]
> [--warmup_manifest WARMUP_MANIFEST]
> hub: error: unrecognized arguments: serving start -c config.json
> class ChineseDeepSpeech2():
> def **init**(self):
> """
> initialize with the necessary elements
> """
> self.args = default_argument_parser()
> self.config = get_cfg_defaults()
> 
> ```
>     if self.args.config:
>         self.config.merge_from_file(self.args.config)
>     if self.args.opts:
>         self.config.merge_from_list(self.args.opts)   
> ```

你先按照以下方式测试是否能跑通，后续再测试serving的形式部署：
1. 完成module.py
2. hub install安装
3. 在python控制台或脚本中，执行：
   ```python
   import paddlehub as hub
   model = hub.Module(name='xxx')
   model.predict(xxx)
   ```
如果上面的脚本正常执行，则说明流程是ok的。

**Comment by FrankWhh** [comment]
一样的错误： ValueError: (InvalidArgument) conv2d(): argument 'Filter' (position 1) must be Tensor, but got Parameter (at /paddle/paddle/fluid/pybind/op_function.h:56)

**Comment by KPatr1ck** [comment]
> paddlehub版本2.1.0/2.0.0，DeepSpeech2模型本身调用运行预测没问题

能否提供可以正常运行调用DeepSpeech模型的最小化的脚本，还有运行时paddlepaddle的具体版本。
感觉这个问题不像paddlehub会引起的。

**Comment by FrankWhh** [comment]
所有文件我放在网盘了：链接：https://pan.baidu.com/s/1rLhZBM4msXP-HdxZi7QpMw  提取码：5ore
运行环境配置就是参考开源说明
paddle版本 paddlepaddle-gpu 2.0.1

**Comment by KPatr1ck** [comment]
> 所有文件我放在网盘了：链接：https://pan.baidu.com/s/1rLhZBM4msXP-HdxZi7QpMw 提取码：5ore
> 运行环境配置就是参考开源说明
> paddle版本 paddlepaddle-gpu 2.0.1

代码就可以了，预训练模型checkpoint下载太慢。

**Comment by FrankWhh** [comment]
那直接看GitHub DeepSpeech realease2.0的代码即可

**Comment by KPatr1ck** [comment]
经测试，将DeepSpeech2模型封装进Hub是可以正常执行预测的。

测试环境：
```
paddlehub                         2.1.0
paddlepaddle-gpu                  2.1.1
```
DeepSpeech 2.0分支

---

相关脚本：
`module.py`
```python
from deepspeech.models.deepspeech2 import DeepSpeech2InferModel
import numpy as np
import paddle
import paddle.nn as nn
from paddlehub.module.module import moduleinfo
                                                                                     
                                                                                     
@moduleinfo(
    name="deep_speech",
    version="1.0.0",
    summary="",
    author="",
    author_email="",
    type="audio/asr")
class DeepSpeech(nn.Layer):
                                                                                                                                                                    
    def __init__(self, **kwargs):
        super(DeepSpeech, self).__init__()
        self.model = DeepSpeech2InferModel(161, 29, 2, 3, 2048, False, True)
                                                                                                                                                     
    def forward(self, audio, audio_len):
        return self.model(audio, audio_len)
                                                                                     
```

hub install安装后，预测脚本如下
```python
import numpy as np
import paddle
import paddlehub as hub

batch_size, feature_size, max_length = 8, 161, 200
audio_np = np.random.randn(batch_size, feature_size, max_length).astype(np.float32)
audio_len_np = np.asarray([max_length] * batch_size).astype(np.int64)
                                                                                                                                                                        
audio, audio_len = map(paddle.to_tensor, [audio_np, audio_len_np])
print(audio.shape, audio.dtype)
print(audio_len.shape, audio_len.dtype)
                                                                                                                                                                        
model = hub.Module(name='deep_speech')
res = model(audio, audio_len)
print(res.shape)
```

执行结果如图：
![image](https://user-images.githubusercontent.com/22954146/127599266-7c59fc93-c0d2-459c-9db7-eeeaf9fd1bc3.png)

**Comment by FrankWhh** [comment]
解决了 谢谢
