### ISSUE TITLE
Ubuntu16.04运行报错

### ISSUE THREAD

**Issue by JefferyBoy** [PaddlePaddle/PaddleFormers#1557]
根据官方教程安装后，运行hub命令直接报错了

![image](https://user-images.githubusercontent.com/9283254/127641228-b4fe6b8d-b696-4dd1-a078-ed6acba93e90.png)

**Comment by haoyuying** [comment]
您好，请问您的paddle， paddlehub，paddlex及gitpython的版本是什么呢
请尝试
```
pip install gitpython==3.1.6
```

**Comment by huangcao008** [comment]
同样碰到这个问题

**Comment by haoyuying** [comment]
gitpython本身的问题，我们将在下次升级中去掉该依赖，大家可以使用3.1.6版本的gitpython规避这个问题
