### ISSUE TITLE
运行AnimeGAN动漫化模型一键应用（含动漫化小程序体验）时报错，

### ISSUE THREAD

**Issue by yizhunhai** [PaddlePaddle/PaddleFormers#1558]
aistudio，PaddleHub 2.0.0
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
![图片](https://user-images.githubusercontent.com/88195471/127656096-b914d4e1-5396-4a72-9c33-30226ed19426.png)
![图片](https://user-images.githubusercontent.com/88195471/127656260-81f5c477-25a2-46e1-bc2a-707170503203.png)

**Comment by haoyuying** [comment]
您好，看这个错误是由于您的paddle版本不是2.0以上的导致的，建议重新安装2.0以上版本的paddle

**Comment by yizhunhai** [comment]
> 
> 
> 您好，看这个错误是由于您的paddle版本不是2.0以上的导致的，建议重新安装2.0以上版本的paddle
并不是，我已安装2.0.0
![图片](https://user-images.githubusercontent.com/88195471/127799150-5494f3d0-244e-48a9-b72a-5f8531a02015.png)

**Comment by haoyuying** [comment]
因为您的报错是paddle.Tensor没有，这是一个显然的没有使用动态图的错误，您可以安装完新的paddle之后测试下paddle.Tensor是否报错
![image](https://user-images.githubusercontent.com/35907364/127802400-120ef488-d863-4934-8ae9-543b1453f631.png)

**Comment by yizhunhai** [comment]
> 
> 
> 因为您的报错是paddle.Tensor没有，这是一个显然的没有使用动态图的错误，您可以安装完新的paddle之后测试下paddle.Tensor是否报错
> ![image](https://user-images.githubusercontent.com/35907364/127802400-120ef488-d863-4934-8ae9-543b1453f631.png)

升级后又出现了新的错误
![图片](https://user-images.githubusercontent.com/88195471/127813834-bf27d675-6019-4c3e-99d9-24a3a5116604.png)

**Comment by haoyuying** [comment]
要写hub.Module(name='animegan_v1_hayao_60', use_gpu=True)

**Comment by yizhunhai** [comment]
> 
> 
> 要写hub.Module(name='animegan_v1_hayao_60', use_gpu=True)

谢谢解答
