### ISSUE TITLE
 两个问题 好像服务器不行了？Can't connect to Hub Server: http://paddlepaddle.org.cn/paddlehub  

### ISSUE THREAD

**Issue by yslion** [PaddlePaddle/PaddleFormers#1562]
**1 
D:\venv36\paddle>python -m pip install paddlepaddle-gpu==2.1.1.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html**

Looking in links: https://paddlepaddle.org.cn/whl/mkl/stable.html
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000016A2D35FBE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))': /whl/mkl/stable.html

**2 hub install ernie_gen**

paddlehub.server.server_source.ServerConnectionError: Can't connect to Hub Server: http://paddlepaddle.org.cn/paddlehub

**Comment by javadoge** [comment]
@yslion 请教 这个问题怎么解决的？
