### ISSUE TITLE
Jetson Agx 在调用paddlehub模型时  没有使用gpu应该怎么解决

### ISSUE THREAD

**Issue by kractics** [PaddlePaddle/PaddleFormers#1578]
![@Q5GKX029}LH9IEUUJ_%@%1](https://user-images.githubusercontent.com/73003661/129658770-06b8371f-fe91-4884-b2ef-14dc161c6bfd.png)
会提示如上的warning 但是在环境变量中我已经配置了cuda的位置
![CX 1E78Z0CA)O~{JV7 (HGE](https://user-images.githubusercontent.com/73003661/129658981-45079b28-a8aa-4bf5-b14e-38f861c7ae4e.png)

**Comment by haoyuying** [comment]
请问是什么模型，看下cuda环境是否生效呢，nvcc -V

**Comment by kractics** [comment]
@haoyuying 
![V2GW(O@2$A9%)IPA)5G8K{L](https://user-images.githubusercontent.com/73003661/129839167-28ff9f51-a858-431e-9967-dedce877367d.png)
![@K_H E RLHLYEI0H)$OD7AX](https://user-images.githubusercontent.com/73003661/129839173-38969287-e73b-46cb-87f4-31180f797ac1.png)

**Comment by kractics** [comment]
![V2GW(O@2$A9%)IPA)5G8K{L](https://user-images.githubusercontent.com/73003661/129839208-7e7afd45-140a-4a8f-a14c-42993e3e18be.png)
![@K_H E RLHLYEI0H)$OD7AX](https://user-images.githubusercontent.com/73003661/129839214-fc3a74b5-a069-47ee-b3a4-cec585ccee54.png)

**Comment by haoyuying** [comment]
可以提供一下完整的报错信息吗

**Comment by kractics** [comment]
@haoyuying   并没有出现报错 程序是在运行的  只是从后台看仅仅使用 了cpu  没有使用gpu  导致模型识别速度很慢

**Comment by haoyuying** [comment]
试下在脚本最开始使用import os， 用os.environ设置CUDA_VISIBLE_DEVICES，同时在用object_detection函数的时候将use_gpu=True打开

**Comment by kractics** [comment]
@haoyuying 感谢多次回复  但是设置之后  一运行程序他依旧会提示找不到cuda
![2AK3APA064U~G F%5LJ0)EG](https://user-images.githubusercontent.com/73003661/129891394-b3f68eee-7e71-4150-aea7-ef899c3ffff2.png)
![DMSI$Z24EST0@TT}SAOM 6N](https://user-images.githubusercontent.com/73003661/129891410-abebeeac-a886-4f5c-bc1c-669e1ba666b7.png)

**Comment by kractics** [comment]
解决了 在开头
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

然后object里面加上use——gpu就完成了  谢谢@haoyuying
