### ISSUE TITLE
加载模型报错，好像无法下载

### ISSUE THREAD

**Issue by alwaysbetter1314** [PaddlePaddle/PaddleFormers#160]
[2019-09-18 21:19:47,006] [    INFO] - Installing bert module
[2019-09-18 21:19:47,093] [   ERROR] - Can't find module bert
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<ipython-input-12-7415ad322c2e> in <module>
      1 # 加载 erine
----> 2 module = hub.Module(name="bert")
      3 
      4 inputs, outputs, program = module.context(trainable="True", max_seq_len=128)
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/module/module.py in __init__(self, name, module_dir, signatures, module_info, assets, processor, extra_info, version)
    120         # TODO(wuzewu): print more module loading info log
    121         if name:
--> 122             self._init_with_name(name=name, version=version)
    123         elif module_dir:
    124             self._init_with_module_file(module_dir=module_dir[0])
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddlehub/module/module.py in _init_with_name(self, name, version)
    148         if not result:
    149             logger.error(tips)
--> 150             exit(1)
    151         logger.info(tips)
    152         self._init_with_module_file(module_dir[0])
NameError: name 'exit' is not defined

**Comment by Steffy-zxf** [comment]
感谢反馈！根据上面的日志显示，bert的module名字不对, bert的系列module有：bert_uncased_L-24_H-1024_A-16， bert_uncased_L-12_H-768_A-12， bert_multi_cased_L-12_H-768_A-12，bert_chinese_L-12_H-768_A-12， bert_cased_L-24_H-1024_A-16， bert_cased_L-12_H-768_A-12。可以通过hub search查看paddlehub支持的所有module，paddlehub官网（https://www.paddlepaddle.org.cn/hub）
上也有paddlehub支持的所有module相关介绍。

**Comment by alwaysbetter1314** [comment]
谢谢，换名字就可以加载模型了

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
