### ISSUE TITLE
hub install 后通过 hub list 找不到对应的 module

### ISSUE THREAD

**Issue by omegod** [PaddlePaddle/PaddleFormers#1619]
飞桨团队您好，首先感谢开源提供了 hub 平台，非常好用，但由于对 hub 的不了解，在文档中没有找到相关的说明，这边通过 PaddleClas 套件 install 后的组件只能在当前目录下通过 hub list 找到，在其他目录下通过 hub list 均无法找到，这个是为什么呢，希望有知道的同学解答一下，感谢感谢。
![image](https://user-images.githubusercontent.com/22209885/134474976-e2db4c88-e16a-4569-8b77-e415a7c086ce.png)
![image](https://user-images.githubusercontent.com/22209885/134474923-6f1f66c4-e356-4e7a-aae0-4588dbd4822b.png)

**Comment by haoyuying** [comment]
hub list找到的模型必须在.paddlehub\modules里面，并且主要针对的是符合paddlehub规范的模型，两者缺一不可。当该模型不符合paddlehub的模型规范时候，模型会报error，建议不要混用。

**Comment by omegod** [comment]
奥，大概明白了，是由于 img_clas 这个 module 只在 deploy 目录下是正常的（因为引用了 deploy 中的 python 方法，但没有打包入 module），所以只有在 deploy 这个目录下通过 hub list 可以看到，是这样对吗？ @haoyuying

**Comment by 89080322** [comment]
同样的问题  在哪个目录安装的模块 只能在当时安模块的目录LIST看到.  模块当然安装成功了..只是hub自带模块可以全局命令启动..  自己做的模块  只能在执行安装模块时的目录list到

**Comment by 89080322** [comment]
刚看到说 list只会把加载成功的模块显示出来.
也就是说 我们自己做的模块  有些BUG

**Comment by omegod** [comment]
> 刚看到说 list只会把加载成功的模块显示出来. 也就是说 我们自己做的模块 有些BUG

明白了，感谢各位的解答
