### ISSUE TITLE
文本分类时最后只有平均准确率，如何得到每个类别单独的准确率和召回率？

### ISSUE THREAD

**Issue by topxxuki** [PaddlePaddle/PaddleFormers#164]

**Comment by Steffy-zxf** [comment]
感谢反馈！您可以根据预测label 和真实label计算每个类别准确率和召回率。Task接口详情参考
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub-API:-BasicTask
PaddleHub目前不支持计算每个类别的准确率和召回率，正在开发中。PaddleHub支持该功能时，第一时间告知您。

**Comment by kinghuin** [comment]
@topxxuki 您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
