### ISSUE TITLE
{'msg': "'Predictor' object has no attribute 'batch_predict'", 'results': '', 'status': '101'}

### ISSUE THREAD

**Issue by careylipu** [PaddlePaddle/PaddleFormers#1650]
版本、环境信息
1）PaddleHub和PaddlePaddle版本：

Name: paddlepaddle Version: 2.1.2
Name: paddlex Version: 2.0.0
Name: paddlehub Version: 2.1.1

2）系统环境：Linux 
python版本:Python 3.7.4

报错信息：
{'msg': "'Predictor' object has no attribute 'batch_predict'", 'results': '', 'status': '101'}

详细描述：对开源的项目进行学习和测试，该项目采用1.8.0版本的PaddlePaddle，通过PaddleHub部署成API，客户端调用正常。
后来自己克隆了该项目并且升级到PaddlePaddle最新版2.1.2，然后重新训练了模型。最后通过PaddleHub部署成API，客户端调用是API返回错误信息：{'msg': "'Predictor' object has no attribute 'batch_predict'", 'results': '', 'status': '101'}
原始项目地址（1.8.0版本的PaddlePaddle）：https://aistudio.baidu.com/aistudio/projectdetail/742090?channelType=0&channel=0

**Comment by KPatr1ck** [comment]
你好，你是想将该项目整体迁移到2.x的版本吗？一般来说demo中需要不同工具的配合，所以建议尽量保持跟随demo中使用的版本。
方便的话麻烦提供一下生成的module、部署和客户端调用的脚本，看一下这个迁移是否存在可行性问题。

**Comment by careylipu** [comment]
算不上迁移了，训练的代码时重新按照2.0的格式写的，重新训练的，只是数据集还是之前的。和原来项目完全不一样了。

**Comment by careylipu** [comment]
以上所述时训练模型部分，完全按照全新代码写的，以下部分还是参考的原始版本的

生成module
!hub convert --model_dir predict/yolov3_darknet53/inference_model \
              --module_name xxxx\
              --module_version 1.0 
部署
!hub install xxxx_1634116005.8467143/xxxx.tar.gz


`import requests
import json
import cv2
import base64


def cv2_to_base64(image):
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')

调用
# 发送HTTP请求
data = {'images':[cv2_to_base64(cv2.imread("/home/jovyan/work/predict/InputImages/xxxx-6-17-00130.jpeg"))]}
headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:8866/predict/xxxx"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(r.json())`

**Comment by KPatr1ck** [comment]
> 生成module
!hub convert --model_dir predict/yolov3_darknet53/inference_model
--module_name xxxx
--module_version 1.0
部署
!hub install xxxx_1634116005.8467143/xxxx.tar.gz

生成后的文件方便看看吗？

**Comment by careylipu** [comment]
`from __future__ import absolute_import
from __future__ import division

import os
import cv2
import argparse
import base64
import paddlex as pdx

import numpy as np
import paddlehub as hub
from paddlehub.module.module import moduleinfo, runnable, serving


def base64_to_cv2(b64str):
    data = base64.b64decode(b64str.encode('utf8'))
    data = np.frombuffer(data, np.uint8)
    data = cv2.imdecode(data, cv2.IMREAD_COLOR)
    return data


def base64_to_np(b64tuple):
    data, shape = b64tuple
    data = base64.b64decode(data.encode('utf8'))
    data = np.frombuffer(data, np.float32).reshape(shape)
    return data


def cv2_to_base64(image):
    # return base64.b64encode(image)
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')


def np_to_base64(array):
    shape = array.shape
    data = base64.b64encode(array).decode('utf8')
    return data, shape


def read_images(paths):
    images = []
    for path in paths:
        images.append(cv2.imread(path))
    return images


@moduleinfo(
    name='xxxx',
    type='CV',
    author='Baidu',
    author_email='',
    summary='',
    version='1.0')
class MODULE(hub.Module):
    def _initialize(self, **kwargs):
        self.default_pretrained_model_path = os.path.join(
            self.directory, 'assets')
        self.model = pdx.deploy.Predictor(self.default_pretrained_model_path,
                                          **kwargs)

    def predict(self,
                images=None,
                paths=None,
                data=None,
                batch_size=1,
                use_gpu=False,
                **kwargs):

        all_data = images if images is not None else read_images(paths)
        total_num = len(all_data)
        loop_num = int(np.ceil(total_num / batch_size))

        res = []
        for iter_id in range(loop_num):
            batch_data = list()
            handle_id = iter_id * batch_size
            for image_id in range(batch_size):
                try:
                    batch_data.append(all_data[handle_id + image_id])
                except IndexError:
                    break
            out = self.model.batch_predict(batch_data, **kwargs)
            res.extend(out)
        return res

    @serving
    def serving_method(self, images, **kwargs):
        """
        Run as a service.
        """
        images_decode = [base64_to_cv2(image) for image in images]
        results = self.predict(images_decode, **kwargs)
        res = []
        for result in results:
            if isinstance(result, dict):
                # result_new = dict()
                for key, value in result.items():
                    if key == 'score_map':
                        result[key] = np_to_base64(value)
                    elif isinstance(value, np.ndarray):
                        result[key] = cv2_to_base64(value)
                    elif isinstance(value, np.generic):
                        result[key] = np.asscalar(value)

            elif isinstance(result, list):
                for index in range(len(result)):
                    for key, value in result[index].items():
                        if key == 'score_map':
                            result[index][key] = np_to_base64(value)
                        elif isinstance(value, np.ndarray):
                            result[index][key] = cv2_to_base64(value)
                        elif isinstance(value, np.generic):
                            result[index][key] = np.asscalar(value)
            else:
                raise RuntimeError('The result cannot be used in serving.')
            res.append(result)
        return res

    @runnable
    def run_cmd(self, argvs):
        """
        Run as a command.
        """
        self.parser = argparse.ArgumentParser(
            description="Run the {} module.".format(self.name),
            prog='hub run {}'.format(self.name),
            usage='%(prog)s',
            add_help=True)
        self.arg_input_group = self.parser.add_argument_group(
            title="Input options", description="Input data. Required")
        self.arg_config_group = self.parser.add_argument_group(
            title="Config options",
            description=
            "Run configuration for controlling module behavior, not required.")
        self.add_module_config_arg()
        self.add_module_input_arg()
        args = self.parser.parse_args(argvs)
        results = self.predict(
            paths=[args.input_path],
            use_gpu=args.use_gpu)
        return results

    def add_module_config_arg(self):
        """
        Add the command config options.
        """
        self.arg_config_group.add_argument(
            '--use_gpu',
            type=bool,
            default=False,
            help="whether use GPU or not")

    def add_module_input_arg(self):
        """
        Add the command input options.
        """
        self.arg_input_group.add_argument(
            '--input_path', type=str, help="path to image.")

if __name__ == '__main__':
    module = MODULE(directory='./new_model')
    images = [cv2.imread('./cat.jpg'), cv2.imread('./cat.jpg'), cv2.imread('./cat.jpg')]
    res = module.predict(images=images)
`

**Comment by KPatr1ck** [comment]
> self.model = pdx.deploy.Predictor(self.default_pretrained_model_path,
**kwargs)

> out = self.model.batch_predict(batch_data, **kwargs)

> 报错信息：
{'msg': "'Predictor' object has no attribute 'batch_predict'", 'results': '', 'status': '101'}

应该是调用paddlex的api出现的问题，建议确认下正常运行时的paddlex版本和module.py的使用的api。

**Comment by careylipu** [comment]
您好，老的环境版本和 module.py代码如下，请查看

Python 3.7.4
Name: paddlepaddle
Version: 1.8.0 
Name: paddlex
Version: 1.3.11
Name: paddlehub
Version: 2.1.0



代码 module.py

`from __future__ import absolute_import
from __future__ import division

import os
import cv2
import argparse
import base64
import paddlex as pdx

import numpy as np
import paddlehub as hub
from paddlehub.module.module import moduleinfo, runnable, serving


def base64_to_cv2(b64str):
    data = base64.b64decode(b64str.encode('utf8'))
    data = np.frombuffer(data, np.uint8)
    data = cv2.imdecode(data, cv2.IMREAD_COLOR)
    return data


def base64_to_np(b64tuple):
    data, shape = b64tuple
    data = base64.b64decode(data.encode('utf8'))
    data = np.frombuffer(data, np.float32).reshape(shape)
    return data


def cv2_to_base64(image):
    # return base64.b64encode(image)
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')


def np_to_base64(array):
    shape = array.shape
    data = base64.b64encode(array).decode('utf8')
    return data, shape


def read_images(paths):
    images = []
    for path in paths:
        images.append(cv2.imread(path))
    return images


@moduleinfo(
    name='hatdet',
    type='CV',
    author='Baidu',
    author_email='',
    summary='',
    version='1.0')
class MODULE(hub.Module):
    def _initialize(self, **kwargs):
        self.default_pretrained_model_path = os.path.join(
            self.directory, 'assets')
        self.model = pdx.deploy.Predictor(self.default_pretrained_model_path,
                                          **kwargs)

    def predict(self,
                images=None,
                paths=None,
                data=None,
                batch_size=1,
                use_gpu=False,
                **kwargs):

        all_data = images if images is not None else read_images(paths)
        total_num = len(all_data)
        loop_num = int(np.ceil(total_num / batch_size))

        res = []
        for iter_id in range(loop_num):
            batch_data = list()
            handle_id = iter_id * batch_size
            for image_id in range(batch_size):
                try:
                    batch_data.append(all_data[handle_id + image_id])
                except IndexError:
                    break
            out = self.model.batch_predict(batch_data, **kwargs)
            res.extend(out)
        return res

    @serving
    def serving_method(self, images, **kwargs):
        """
        Run as a service.
        """
        images_decode = [base64_to_cv2(image) for image in images]
        results = self.predict(images_decode, **kwargs)
        res = []
        for result in results:
            if isinstance(result, dict):
                # result_new = dict()
                for key, value in result.items():
                    if key == 'score_map':
                        result[key] = np_to_base64(value)
                    elif isinstance(value, np.ndarray):
                        result[key] = cv2_to_base64(value)
                    elif isinstance(value, np.generic):
                        result[key] = np.asscalar(value)

            elif isinstance(result, list):
                for index in range(len(result)):
                    for key, value in result[index].items():
                        if key == 'score_map':
                            result[index][key] = np_to_base64(value)
                        elif isinstance(value, np.ndarray):
                            result[index][key] = cv2_to_base64(value)
                        elif isinstance(value, np.generic):
                            result[index][key] = np.asscalar(value)
            else:
                raise RuntimeError('The result cannot be used in serving.')
            res.append(result)
        return res

    @runnable
    def run_cmd(self, argvs):
        """
        Run as a command.
        """
        self.parser = argparse.ArgumentParser(
            description="Run the {} module.".format(self.name),
            prog='hub run {}'.format(self.name),
            usage='%(prog)s',
            add_help=True)
        self.arg_input_group = self.parser.add_argument_group(
            title="Input options", description="Input data. Required")
        self.arg_config_group = self.parser.add_argument_group(
            title="Config options",
            description=
            "Run configuration for controlling module behavior, not required.")
        self.add_module_config_arg()
        self.add_module_input_arg()
        args = self.parser.parse_args(argvs)
        results = self.predict(
            paths=[args.input_path],
            use_gpu=args.use_gpu)
        return results

    def add_module_config_arg(self):
        """
        Add the command config options.
        """
        self.arg_config_group.add_argument(
            '--use_gpu',
            type=bool,
            default=False,
            help="whether use GPU or not")

    def add_module_input_arg(self):
        """
        Add the command input options.
        """
        self.arg_input_group.add_argument(
            '--input_path', type=str, help="path to image.")

if __name__ == '__main__':
    module = MODULE(directory='./new_model')
    images = [cv2.imread('./cat.jpg'), cv2.imread('./cat.jpg'), cv2.imread('./cat.jpg')]
    res = module.predict(images=images)
`

**Comment by careylipu** [comment]
之前的paddlehub好像不记得版本了

**Comment by careylipu** [comment]
paddlehub当时安装的时候没有指定版本获取的最新的，现在不好复现了。
现在我 手动修改 out = self.model.batch_predict(batch_data, **kwargs)  为 out = self.model.predict(batch_data, **kwargs)
已经可以运行，现在总结下来我认为是最新版的 pandlehub在hub convert自动生成代码里的小bug，希望官网下个版本能够修正。望采纳验证！

**Comment by KPatr1ck** [comment]
> paddlehub当时安装的时候没有指定版本获取的最新的，现在不好复现了。 现在我 手动修改 out = self.model.batch_predict(batch_data, **kwargs) 为 out = self.model.predict(batch_data, **kwargs) 已经可以运行，现在总结下来我认为是最新版的 pandlehub在hub convert自动生成代码里的小bug，希望官网下个版本能够修正。望采纳验证！

好的。感谢反馈～

**Comment by careylipu** [comment]
感谢
