### ISSUE TITLE
PaddleHub 2.1版本如何使用自定义图像数据集

### ISSUE THREAD

**Issue by oruchimaru420** [PaddlePaddle/PaddleFormers#1663]
我需要使用PaddleHub 2.1版本来实现图像分类任务的迁移学习
但之前版本中的base_cv_dataset模块被移除了，请问现在如何自定义数据集？
请给出相关链接或API
非常感谢！

**Comment by haoyuying** [comment]
可参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/docs/docs_ch/finetune/customized_dataset.md

**Comment by oruchimaru420** [comment]
> 可参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/docs/docs_ch/finetune/customized_dataset.md
您好，我看了您给的链接。但还是不能解决我提出的问题。

前面关于图像分类任务，给出的示例代码，是直接下载内置的Flowers数据集。

而后面给出的自定义数据集示例代码，其基类是base_nlp_dataset下的TextClassificationDataset，其无法应用到图像应用中。

我现在已经有一个格式与图像分类数据集完全一样的已标注数据集，问题是如何加载到paddlehub中，烦请给出示例。
