### ISSUE TITLE
请问能在未标记样本上微调吗？

### ISSUE THREAD

**Issue by Reveyer** [PaddlePaddle/PaddleFormers#167]
比如在分类任务里，有更多的未分类的数据话，怎么把这些数据也用来进行微调？

**Comment by Steffy-zxf** [comment]
感谢反馈！分类任务的话，没有真实的label，就无法参与训练，也就是说没办法在没有label的数据上进行微调。因为PaddleHub中分类Task的loss计算需要样本的真实label。

**Comment by Reveyer** [comment]
> 感谢反馈！�分类任务的话，没有真实的label，就无法参与训练，也就是说没办法在没有label的数据上进行微调。因为PaddleHub中分类Task的loss计算需要样本的真实label。

就是可以在更多目标领域未标记的数据上对Language Model进行tuning，然后再对有label的样本上进行分类器的训练。

这一功能，以后能实现么？

**Comment by Steffy-zxf** [comment]
你是指完全重头训练模型吗？比如重新用更多目标领域未标记的数据训练Ernie，保存这个预训练Ernie，之后把这个预训练Ernie用于文本分类任务吗？
PaddleHub目前还不支持这样的完全重头训练模型。后续我们会考虑支持该功能，开放后第一时间通知您。

**Comment by Reveyer** [comment]
额，抱歉，之前表达意思不清晰。我想要的是像UMLFiT的那种迁移学习策略

**Comment by Steffy-zxf** [comment]
近期PaddleHub会发布最新版，该版本支持UMLFiT的优化策略。发布后，第一时间告知您，欢迎使用。

**Comment by Steffy-zxf** [comment]
@Reveyer PaddleHub 已经发布最新版本1.2.0 支持UMLFiT优化策略，相应的接口信息参考https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub-API:-Strategy#class-hubfinetunestrategyulmfitstrategy

**Comment by Reveyer** [comment]
> @Reveyer PaddleHub 已经发布最新版本1.2.0 支持UMLFiT优化策略，相应的接口信息参考https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub-API:-Strategy#class-hubfinetunestrategyulmfitstrategy

感谢
