### ISSUE TITLE
2.0版本后的Fine-tune应用在senta各类模型下不可用

### ISSUE THREAD

**Issue by yangchanglin324** [PaddlePaddle/PaddleFormers#1696]
paddle 2.2
paddlehub 2.1
windows 10

datasets下各加载数据类都需要tokenizer参数输入，但senta类别（senta_gre, sent_lstm等）模型目前都没有get_tokenizer相关方法。

请问下这些模型在hub2.0后还没有支持，还是说使用的有问题？

**Comment by linjieccc** [comment]
您好，paddlehub 2.1版本的senta各类模型目前只支持预测

如果想用senta做finetune，可以参考paddlehub 1.8版本的教程：[Senta 情感分析](https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.8/demo/senta)

**Comment by yangchanglin324** [comment]
你好，谢谢，2.1之前是知道的，未来版本会支持情感分析的Fine-tune不

**Comment by linjieccc** [comment]
会的
