### ISSUE TITLE
windows本地paddlehub模型的存储位置

### ISSUE THREAD

**Issue by Ja1Zhou** [PaddlePaddle/PaddleFormers#1703]
您好 我在使用paddlehub下载预先提供的模型时网速较慢 想配合neat download manager等工具先把模型的压缩包下载到本地。因此想请问一下上述的操作是否可行？如果可行的话，应该把下载好的压缩包放在本地的什么位置？

**Comment by haoyuying** [comment]
下载模型之后解压，比如下载了falsr_a这个模型，解压之后在包含该目录的位置直接hub install falsr_a就可以实现模型的安装。

**Comment by Ja1Zhou** [comment]
> 下载模型之后解压，比如下载了falsr_a这个模型，解压之后在包含该目录的位置直接hub install falsr_a就可以实现模型的安装。

已解决 谢谢!
