### ISSUE TITLE
hub 指令不存在

### ISSUE THREAD

**Issue by renoyuan** [PaddlePaddle/PaddleFormers#1720]
![image](https://user-images.githubusercontent.com/50486789/145139719-42c1fb19-8cad-4d39-b414-161e20d34503.png)

安装paddlehub 后hub  指令不存在

**Comment by KPatr1ck** [comment]
你好，看一下环境变量里有没有anaconda/envs/你的环境名/bin的目录，如过没有，需要你手动配置一下。

**Comment by renoyuan** [comment]
在base 环境中使用hub  指令不存在，创建新的环境 安装paddlepaddle 和 paddlehub 就可以了
