### ISSUE TITLE
无法本地安装senta_bilstm

### ISSUE THREAD

**Issue by qianshuifanzhou** [PaddlePaddle/PaddleFormers#175]
centos 系统中 hub install senta_bilstm  返回结果  Can't find module senta_bilstm ,
进入python3之后执行 
>>> import paddlehub as hub
>>> hub.Module(name="senta_bilstm")
返回：
[2019-09-25 19:59:21,050] [    INFO] - Installing senta_bilstm module
[2019-09-25 19:59:21,285] [   ERROR] - Can't find module senta_bilstm

**Comment by Steffy-zxf** [comment]
感谢反馈！根据以下方法：确认是否可以访问外网https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub-FAQ#%E9%97%AE%E9%A2%98%E5%9B%9B

**Comment by kinghuin** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天关闭。关闭后您可重新开启此issue继续跟进问题。
