### ISSUE TITLE
关于Anconda里安装问题

### ISSUE THREAD

**Issue by ghm** [PaddlePaddle/PaddleFormers#177]
Anconda安装PaddleHub时，我在自己创建的虚拟环境里用pip安装的，但没有安装到虚拟环境所在文件夹下，却装到C盘了。信息如下：
  WARNING: The script hub.exe is installed in 'C:\Users\May\AppData\Roaming\Pyth
on\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warn
ing, use --no-warn-script-location.
Successfully installed paddlehub-1.2.0 pandas-0.25.1

导致conda list 时看不到安装包，无法使用。。。

**Comment by Steffy-zxf** [comment]
感谢反馈！您确认自己创建的虚拟环境成功启动了吗？同时用命令where pip确认下，pip是否在自己创建的虚拟环境中？

**Comment by ghm** [comment]
where pip看了，是在自己创建的虚拟环境中，原因是pip时加了--user，不加安装时报pandas文件夹拒绝访问，把pandas删掉重新安装就可以了。
这里有另外一个问题：pip install pyahocorasick 时，报错如下：
Collecting pyahocorasick
  Using cached https://files.pythonhosted.org/packages/f4/9f/f0d8e8850e12829eea2e778f1c90e3c53a9a799b7f412082a5d21cd19ae1/pyahocorasick-1.4.0.tar.gz
Building wheels for collected packages: pyahocorasick
  Building wheel for pyahocorasick (setup.py): started
  Building wheel for pyahocorasick (setup.py): finished with status 'error'
  Running setup.py clean for pyahocorasick
Failed to build pyahocorasick
Installing collected packages: pyahocorasick
  Running setup.py install for pyahocorasick: started
    Running setup.py install for pyahocorasick: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'd:\anaconda3\envs\py37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\May\\AppData\\Local\\Temp\\pip-install-3ydtxupy\\pyahocorasick\\setup.py'"'"'; __file__='"'"'C:\\Users\\May\\AppData\\Local\\Temp\\pip-install-3ydtxupy\\pyahocorasick\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\May\AppData\Local\Temp\pip-wheel-3xxtzljs' --python-tag cp37
       cwd: C:\Users\May\AppData\Local\Temp\pip-install-3ydtxupy\pyahocorasick\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ahocorasick' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pyahocorasick
    ERROR: Command errored out with exit status 1:
     command: 'd:\anaconda3\envs\py37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\May\\AppData\\Local\\Temp\\pip-install-3ydtxupy\\pyahocorasick\\setup.py'"'"'; __file__='"'"'C:\\Users\\May\\AppData\\Local\\Temp\\pip-install-3ydtxupy\\pyahocorasick\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\May\AppData\Local\Temp\pip-record-3honrz21\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\May\AppData\Local\Temp\pip-install-3ydtxupy\pyahocorasick\
    Complete output (5 lines):
    running install
    running build
    running build_ext
    building 'ahocorasick' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\anaconda3\envs\py37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\May\\AppData\\Local\\Temp\\pip-install-3ydtxupy\\pyahocorasick\\setup.py'"'"'; __file__='"'"'C:\\Users\\May\\AppData\\Local\\Temp\\pip-install-3ydtxupy\\pyahocorasick\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\May\AppData\Local\Temp\pip-record-3honrz21\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

请问该怎么解决？

**Comment by Steffy-zxf** [comment]
参考以下链接，尝试下：
https://blog.csdn.net/weixin_42057852/article/details/80857948

**Comment by ghm** [comment]
感谢您的及时回复，问题解决了，谢谢！
