### ISSUE TITLE
使用一段时间报错IndexError: string index out of range

### ISSUE THREAD

**Issue by ningshixian** [PaddlePaddle/PaddleFormers#178]
```
Traceback (most recent call last):
  .....
  File "/data/ningshixian/work/extract/info_extract.py", line 65, in run_lac
    results = self.lac.lexical_analysis(data=data)  # 词法分析
  File "/data/ningshixian/software/anaconda3/lib/python3.7/site-packages/paddlehub/module/module.py", line 497, in __call__
    sub_data, **kwargs)
  File "/home/ningshixian/.paddlehub/modules/lac/python/a62c5d015111daae0dbd8719b0293c1b.py", line 304, in postprocess
    cur_word = words[word_index]
**IndexError: string index out of range**
```

code is following:

main.py
```
# load Baidu LAC service
import paddlehub as hub
lac = hub.Module(name='lac')
slot_extractor = info_extractor(lac)
for i in range(len(xx)):
    slot_extractor.run_lac('text')
...
```

info_extract.py
```
class info_extractor:
    def __init__(self, lac, logger):
        self.lac = lac
    def run_lac(self, text):    #  text是一句话
        data = {'text':[text]}
        results = self.lac.lexical_analysis(data=data)  # IndexError: string index out of range
...
```

main.py 会调用多次info_extract.py，每隔一段时间就会报错**IndexError: string index out of range**，请各路大神帮忙看看，谢谢

**Comment by kinghuin** [comment]
@ningshixian ，感谢反馈，请问您使用的paddlehub是什么版本呢？可以打印一下出错前的data吗？

**Comment by ningshixian** [comment]
paddlepaddle  1.5.2         
paddlehub 1.2.0

出错前的data？
每次就是输入一段短文本句子。每当报错的时候，把报错的句子再重新拿去词法分析是没问题的，应该不是句子本身的问题吧

data的示例：
电脑端如何关联发票？
发票无法关联怎么办？
手机端如何关联发票？
手机端如何修改发票？
电脑端如何修改发票？
什么时候可以修改发票？
....

每个一小段时间就会报IndexError: string index out of range，跟输入的data无关

**Comment by kinghuin** [comment]
@ningshixian 
我这边复现了您的代码但是没有出现相应的错误
```python
import paddlehub as hub

class info_extractor:
    def __init__(self, lac):
        self.lac = lac
    def run_lac(self, text):    #  text是一句话
        data = {'text':[text]}
        results = self.lac.lexical_analysis(data=data)  # IndexError: string index out of range
        for result in results:
            print(result['word'])
            print(result['tag'])

lac = hub.Module(name='lac')
slot_extractor = info_extractor(lac)
for i in range(100000):
    print(i)
    slot_extractor.run_lac("什么时候可以修改发票？")
```

您的代码还有更多的细节可以补充吗？数据集中是否存在空行或者特殊字符呢？

如果可以的话，尝试以下方案获取错误信息：
1. 备份module文件：
```bash
cp /home/ningshixian/.paddlehub/modules/lac/python/a62c5d015111daae0dbd8719b0293c1b.py /home/ningshixian/.paddlehub/modules/lac/python/a62c5d015111daae0dbd8719b0293c1b.py.bak
```
2. 获取异常信息
```bash
vi /home/ningshixian/.paddlehub/modules/lac/python/a62c5d015111daae0dbd8719b0293c1b.py
```
将304行cur_word = words[word_index]修改为：
```python
try:
    cur_word = words[word_index]
except Exception as exc:
    raise Exception("Exception: %s, words: %s, word_index: %s, lod_info:%s, crf_decode:%s"%(exc,words,word_index,lod_info,crf_decode))
```

**Comment by ningshixian** [comment]
好的，非常感谢细致的解答，已修改a62c5d015111daae0dbd8719b0293c1b.py文件

我再等待几天，观望下是否还会报错

**Comment by kinghuin** [comment]
@ningshixian 您好，请问现在还会报错吗？

**Comment by ningshixian** [comment]
> @ningshixian 您好，请问现在还会报错吗？

已经可以正常使用了

**Comment by kinghuin** [comment]
好的 谢谢反馈 如有新的问题可以重新打开本issue :)

**Comment by ningshixian** [comment]
tyr...catch...之后，程序捕捉到的异常（较多）

[2019-10-18 08:07:29,333-WARNING - get error msg:Exception: string index out of range, words: 是挂的急诊, word_index: 5, lod_info:[0, 9], crf_decode:   lod: {{0, 9}}
        dim: 9, 1
        layout: NCHW
        dtype: int64_t
        data: [0 14 15 14 15 10 44 14 15]

[2019-10-18 08:07:29,340-WARNING - error traceback:Traceback (most recent call last):
  File "/home/ningshixian/.paddlehub/modules/lac/python/a62c5d015111daae0dbd8719b0293c1b.py", line 305, in postprocess
    cur_word = words[word_index]
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask_slot.py", line 164, in slot_extract
    res = get_entity(json_data)
  File "flask_slot.py", line 144, in get_entity
    slot_dic = slot_extractor.all_extract(sen)[:]
  File "/data/ningshixian/work/extract/info_extract.py", line 111, in all_extract
    names = self.name_extract(text)
  File "/data/ningshixian/work/extract/info_extract.py", line 695, in name_extract
    self.run_lac(text)
  File "/data/ningshixian/work/extract/info_extract.py", line 676, in run_lac
    results = lac.lexical_analysis(data=inputs)  # IndexError: string index out of range 未解决
  File "/data/ningshixian/software/anaconda3/lib/python3.7/site-packages/paddlehub/module/module.py", line 490, in __call__
    sub_data, **kwargs)
  File "/home/ningshixian/.paddlehub/modules/lac/python/a62c5d015111daae0dbd8719b0293c1b.py", line 307, in postprocess
    raise Exception("Exception: %s, words: %s, word_index: %s, lod_info:%s, crf_decode:%s"%(exc,words,word_index,lod_info,crf_decode))
Exception: Exception: string index out of range, words: 是挂的急诊, word_index: 5, lod_info:[0, 9], crf_decode: lod: {{0, 9}}
        dim: 9, 1
        layout: NCHW
        dtype: int64_t
        data: [0 14 15 14 15 10 44 14 15]

]

**Comment by kinghuin** [comment]
@ningshixian 谢谢反馈，出错句子“是挂的急诊”的前面一个句子是有9个词吗？ 您的flask是采用多线程吗？

**Comment by ningshixian** [comment]
出错句子“是挂的急诊”的前面一个句确实子是有**9个词**，我是用flask写的一个接口（调用paddlehub的LAC服务，不是多线程），但是利用其他程序调用该接口是多线程的

**Comment by ShenYuhan** [comment]
> 出错句子“是挂的急诊”的前面一个句确实子是有**9个词**，我是用flask写的一个接口（调用paddlehub的LAC服务，不是多线程），但是利用其他程序调用该接口是多线程的


如果使用flask做多线程或多进程服务的话，建议+gunicorn等框架，您的具体需求是什么，我这里实现了用flask做服务的paddlehub版本，具体内容已经给您发了邮件，可以交流一下。

**Comment by kinghuin** [comment]
@ningshixian Hi，如果您的程序中涉及到并发执行LAC服务就可能出现这种情况，您是否尝试过 @ShenYuhan 提供的多线程或多进程paddlehub版本呢，它是否解决了您的问题呢？

**Comment by ningshixian** [comment]
> @ningshixian Hi，如果您的程序中涉及到并发执行LAC服务就可能出现这种情况，您是否尝试过 @ShenYuhan 提供的多线程或多进程paddlehub版本呢，它是否解决了您的问题呢？

暂时还没，由于是团队项目，安全稳定性比较重要。正式版大概1~2周后会发布，我想等正式版发布后再尝试

**Comment by kinghuin** [comment]
@ningshixian 由于本issue在7天内没有更新，我们将暂时将它关闭，如您还有新的问题，欢迎重新打开
