### ISSUE TITLE
关于使用文档中的代码示例报错的问题

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/PaddleFormers#1789]
地址：https://www.paddlepaddle.org.cn/hubdetail?name=ultra_light_fast_generic_face_detector_1mb_320&en_category=FaceDetection
or 
https://www.paddlepaddle.org.cn/hubdetail?name=ace2p&en_category=ImageSegmentation

![image](https://user-images.githubusercontent.com/61859193/153584595-40e2a678-50ab-4dc1-ab04-597ab70a6c6b.png)  

此处多了`（` 根据初步测试发现此处使用的两个文档都有一样的情况

不知道是特意这样子出现的还是什么原因，希望官方看一下。

**Comment by KPatr1ck** [comment]
感谢反馈，文档确实存在问题，使用时可以先去掉，将更新修复。
