### ISSUE TITLE
demo运行错误

### ISSUE THREAD

**Issue by huohaodong** [PaddlePaddle/PaddleFormers#179]
环境：Windows10、pycharm 、Cuda版本10.1.0
问题：当我试着跑senta的demo时，部分报错如下：
`C++ Call stacks: 
Cannot open file C:\Users\霍浩东\.paddlehub\modules\senta_bilstm\model\@HUB_senta_bilstm@fc_0.b_0 for load op at [D:\zty\paddle\paddle/fluid/operators/load_op.h:37]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.`
当我试着跑其他demo时亦是如此。

然而当我在ubuntu19.04的类似配置环境下拿来跑时没有出现问题。

请问是我哪里出了问题，或者说这个问题该如何解决？

**Comment by nepeplwu** [comment]
@inf1nityhhd ，感谢反馈，从报错堆栈来看，是因为你的windows 用户路径带有中文名导致，可以试试通过HUB_HOME设置为其他路径，例如
```
set HUB_HOME=D:\
```
详细资料可以查看[命令行工具](https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7)

**Comment by huohaodong** [comment]
@nepeplwu 非常感谢，刚尝试了一下，成功解决了问题。

**Comment by kinghuin** [comment]
感谢反馈，如您仍有疑问，可以重新打开本issue
