### ISSUE TITLE
图像文字识别时,读取带有中文路径图片失败

### ISSUE THREAD

**Issue by YouJianYue** [PaddlePaddle/PaddleFormers#1791]
1）PaddlePaddle版本：PaddlePaddle1.6.2
2）系统环境：Windows  python3.8.12
![image](https://user-images.githubusercontent.com/29574966/154229355-bc077aef-22d8-4fa1-9df3-3e3f073d568e.png)
![image](https://user-images.githubusercontent.com/29574966/154229572-0f270bbc-4934-4c4d-9eb4-cf26e07cddd4.png)
文档中并未提及,希望及时补充文档

**Comment by KPatr1ck** [comment]
你好，感谢反馈。
看了你提供的脚本，可能是`cv2.imread`这个api不支持中文的图片路径。

**Comment by YouJianYue** [comment]
模型：chinese_ocr_db_crnn_mobile
是的,cv2.imread这个api不支持中文的图片路径,需要用numpy先转一下,希望可以在文档提及一下
![image](https://user-images.githubusercontent.com/29574966/155047370-6e3386fa-3faf-4376-8727-f401482e2b3b.png)

**Comment by YouJianYue** [comment]
解决了问题
