### ISSUE TITLE
Huggingface Hub

### ISSUE THREAD

**Issue by AK391** [PaddlePaddle/PaddleFormers#1793]
Hi, I opened a issue in paddlepaddle regarding this https://github.com/PaddlePaddle/Paddle/issues/39489 but here might be a better place

some team members already joined the paddepaddle org on Huggingface: https://huggingface.co/PaddlePaddle

is there any interest to add demos(spaces) for the models on paddlehub to huggingface, we can help with the technical implementation. 

See a example demo for wav2lip here: https://huggingface.co/spaces/PaddlePaddle/wav2lip

Thanks

**Comment by KPatr1ck** [comment]
Hi @AK391 , we have lots of intrest to add demos(CV/NLP/Speech/Video) on Huggingface Hub using PaddleHub models.
I think Huggingface Hub is convenient for visualing the usage of deep learning models.
I had sent request to join https://huggingface.co/PaddlePaddle and hope to create some intresting demos.

**Comment by AK391** [comment]
@KPatr1ck thanks, approved the request, let me know if you have any questions

**Comment by AK391** [comment]
@KPatr1ck there are 8 spaces now in the paddlepaddle org https://huggingface.co/PaddlePaddle, I also opened a PR to add a badge to the readme for the org https://github.com/PaddlePaddle/PaddleHub/pull/1795
