### ISSUE TITLE
paddlehub使用hub convert  把inference 模型转换程paddleHub的预训练模型,那有官方的把paddleHub的预训练模型转换回infernce 模型的命令吗？ 

### ISSUE THREAD

**Issue by smallhaozigithub** [PaddlePaddle/PaddleFormers#1822]
使用命令hub convert可一键转换Inference Model转换成PaddleHub的预训练模型，那能反过来把PaddleHub的预训练模型转换成Inference Model么？

**Comment by KPatr1ck** [comment]
可以参考paddle官方的动转静教程：
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/04_dygraph_to_static/basic_usage_cn.html
