### ISSUE TITLE
paddlehub安装问题

### ISSUE THREAD

**Issue by javadoge** [PaddlePaddle/PaddleFormers#1831]
paddlehub 安装报错，安装执行命令：pip install paddlehub -i http://mirror.baidu.com/pypi/simple --trusted-host mirror.baidu.com

报错信息：

![1649226155(1)](https://user-images.githubusercontent.com/5305836/161908831-5687bff6-2ef4-4767-8e14-d497169bdbb2.png)

**Comment by javadoge** [comment]
WARNING: Discarding http://mirror.baidu.com/pypi/packages/c4/47/f85f522f1f2532ca650474088e4024a9f52d524379bff058eaadf53cb663/seqeval-1.2.1.tar.gz#sha256=30906241b12e654c8545d1f707c00339d7ccfee1e53b9da0cdc0dea72156721e (from http://mirror.baidu.com/pypi/simple/seqeval/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by KPatr1ck** [comment]
尝试下这里的方法：
https://stackoverflow.com/a/57753808

**Comment by javadoge** [comment]
> 尝试下这里的方法： https://stackoverflow.com/a/57753808

谢谢，这个问题已经解决了，我看报错这个是 seqeval安装不上，我先安装setuptools_scm后 再执行 pip install paddlehub -i http://mirror.baidu.com/pypi/simple --trusted-host mirror.baidu.com  就可以了
