### ISSUE TITLE
chinese_ocr_db_crnn_server增加特殊字体的识别，怎么训练？

### ISSUE THREAD

**Issue by webtang** [PaddlePaddle/PaddleFormers#1838]
chinese_ocr_db_crnn_server对银行卡的突出字体识别不好，我想训练下，有没有时间操作的较详细的教程？

**Comment by haoyuying** [comment]
您好，paddlehub提供的ocr模型仅支持预测，如需训练，可移步paddleocr仓库：https://github.com/PaddlePaddle/PaddleOCR

**Comment by webtang** [comment]
ok,谢谢
