### ISSUE TITLE
TTS - fastspeech2_baker - 读车牌号会漏掉字母

### ISSUE THREAD

**Issue by imzjy** [PaddlePaddle/PaddleFormers#1845]
# Example script:

```python
import paddlehub as hub

# 需要合成语音的文本
sentences = ['苏A 8877Q已经到站，车次 A23456R，请有序排队检票！']

model = hub.Module(
    name='fastspeech2_baker',
    version='1.0.0')
wav_files =  model.generate(sentences)

# 打印合成的音频文件的路径
print(wav_files)
```

# Output:
车牌号和车次上的字母完全没有读出来。

[1.zip](https://github.com/PaddlePaddle/PaddleHub/files/8526962/1.zip)

# 问题

1. 是Bug还是预期的行为，是不是因为是中文TTS模型所以不支持英文字母？
2. 如果想要Paddle支持类似车牌号的TTS，需要怎么做？

谢谢~

**Comment by KPatr1ck** [comment]
你好，当前的TTS模型暂不支持中英混合输入的情况，数字的话可以通过文本正则的方式处理，详情可以参考：
https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/paddlespeech/t2s/frontend/zh_normalization

**Comment by imzjy** [comment]
@KPatr1ck 感谢你的回复。

如果什么时候可以了能ping下这个thread就太棒了，中英文混合输入的场景使用还是较为普遍的。

**Comment by imzjy** [comment]
发现了一个好玩的，官方的语音合成小样也跳过了英文语音输出，这下我死心了，确实不支持 :)

https://www.bilibili.com/video/BV1cL411V71o

**Comment by KPatr1ck** [comment]
> @KPatr1ck 感谢你的回复。
> 
> 如果什么时候可以了能ping下这个thread就太棒了，中英文混合输入的场景使用还是较为普遍的。

OK的。你也可以关注一下PaddleSpeech，这个中英混合的场景之后会解决的。

**Comment by shihzenq** [comment]
fastspeech2_baker 能否支持调整男声，女声，童声。
