### ISSUE TITLE
PaddleHub 在 开发机上不好用

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/PaddleFormers#185]
问题如下，可以引入 Hub，也能找到 LAC module，但无法使用。

![Screen Shot 2019-10-08 at 3 07 05 PM](https://user-images.githubusercontent.com/5635322/66436959-54b98780-e9dd-11e9-87dd-902add810b45.png)

**Comment by Steffy-zxf** [comment]
感谢反馈！先用命令hub clear清空paddlehub的缓存，现在paddlehub的最新版本为1.2.0，PaddleHub每升级一版会增加一些新功能，也会修复一些bug。建议升级paddlehub至最新版本。之后再尝试下是否可以搜索到lac
```shell
$ hub clear
$ pip install --upgrade paddlehub
$ hub search lac
$ hub install lac
```

**Comment by Steffy-zxf** [comment]
经和用户沟通，问题已解决！
