### ISSUE TITLE
paddlehub LAC模块的lexical_analysis(）方法

### ISSUE THREAD

**Issue by luzm3** [PaddlePaddle/PaddleFormers#186]
hi，我想学习一下这个API的实现，但是怎么都找不到，能麻烦帮我看看嘛，下面是对应的例子哈
![image](https://user-images.githubusercontent.com/45001329/66481130-cde6d680-ead2-11e9-9199-d6df2250d7ce.png)

**Comment by kinghuin** [comment]
@luzm3  Hi 感谢反馈，可以在 ~/.paddlehub/modules/lac/python 文件夹中找到这个API的源码

**Comment by Steffy-zxf** [comment]
@luzm3 lexical_analysis接口调用流程是，先找到 paddlehub/module/module.py中__call__()接口，lexical_analysis是lac的一个signature，之后这个call接口会调用 lac module 下的一个python文件，预处理 输入文件成 相应的格式，之后输出分词结果。同时了解下，您为什么想要了解这个接口实现呢？

**Comment by luzm3** [comment]
> @luzm3 lexical_analysis接口调用流程是，先找到 paddlehub/module/module.py中__call__()接口，lexical_analysis是lac的一个signature，之后这个call接口会调用 lac module 下的一个python文件，预处理 输入文件成 相应的格式，之后输出分词结果。同时了解下，您为什么想要了解这个接口实现呢？

我也想封装一个类似的哈,因为你们这个必须有网才可以lac的，我想搞一个自己线下也可以用的

**Comment by Steffy-zxf** [comment]
PaddleHub 1.2.0版本支持离线运行module，可以升级paddlehub，但是 下载数据集、module还是需要外网访问权限。

**Comment by luzm3** [comment]
> @luzm3 Hi 感谢反馈，可以在 ~/.paddlehub/modules/lac/python 文件夹中找到这个API的源码

hi，可以加你个好友详细问一下嘛

**Comment by kinghuin** [comment]
@luzm3 Hi, 有任何问题可以在issues中提出，您也可以加入QQ群：
- 飞桨PaddlePaddle 交流群：432676488
- 飞桨 ERNIE交流群：760439550

**Comment by luzm3** [comment]
> @luzm3 Hi, 有任何问题可以在issues中提出，您也可以加入QQ群：
> 
> * 飞桨PaddlePaddle 交流群：432676488
> * 飞桨 ERNIE交流群：760439550

好的  thx！
