### ISSUE TITLE
运行trainer.train()出现label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,        [2])

### ISSUE THREAD

**Issue by fatepary** [PaddlePaddle/PaddleFormers#1869]
- 版本、环境信息
1）例如PaddleHub2.1.1，PaddlePaddle2.2.2.post101使用erine_tiny
2）系统环境：aistudio平台
- 复现信息：ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,[2]
- 
代码：https://aistudio.baidu.com/aistudio/datasetdetail/146374/0

**Comment by KPatr1ck** [comment]
> ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,[2]

这个报错可能是代码中 label 的传参有问题，可以把具体的代码贴出来看下。

**Comment by fatepary** [comment]
解决了，是没设置好分类数量
