### ISSUE TITLE
如何二次加载经过一次finetune的ERNIE模型，进行二次finetune

### ISSUE THREAD

**Issue by sz547073165** [PaddlePaddle/PaddleFormers#188]
用“数据集1”对预训练模型ERNIE，进行第一次finetune后，并保存“模型1”。

如何加载“模型1”，使用“数据集2”，进行第二次finetune，得到“模型2”。

需要自己对Class hub.module.Module进行重新实现，导自己的“模型1”吗？

**Comment by Steffy-zxf** [comment]
感谢反馈！ 加载模型2，可以利用Task类的load_parameters接口，参考以下示例：
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.2/demo/autofinetune/img_cls.py#L107

其中 model_path 是 模型1的参数文件路径。

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
