### ISSUE TITLE
human_pose_estimation_resnet50_mpii 使用GPU推理单图速度慢，跟pphuman完全没法比

### ISSUE THREAD

**Issue by yueyue0574** [PaddlePaddle/PaddleFormers#1895]
有业务需要快速进行单图姿态检测，用paddlehub的human_pose_estimation_resnet50_mpii速度巨慢，开GPU一张图耗时1秒多，图也不大，800*800的图，代码为以下代码
paddlepaddle-gpu          2.3.0
paddlehub                 1.8.0
显卡GTX1066Ti

import os,time
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
import paddlehub as hub
detector = hub.Module(name="human_pose_estimation_resnet50_mpii")
time_start = time.time()
result = detector.keypoint_detection(paths=['human.jpg'],use_gpu=True)
print(time.time() - time_start)

paddlehub跑其他骨骼关键点模型也是慢

pphuman那里的骨骼关键点检测速度比它快的完全不是一个级别的，这是什么原因

**Comment by haoyuying** [comment]
模型本身不同，参数量不同导致的
