### ISSUE TITLE
paddlehub http接口性能问题

### ISSUE THREAD

**Issue by hkzero** [PaddlePaddle/PaddleFormers#1917]
我本地部署了paddlehub，用模型：chinese_ocr_db_crnn_server，识别图片文字，直接调用方法ocr.recognize_text(images=[img])大概1s就识别出来了，然后我本地启动hub服务，然后调用http接口，居然要20s才能返回结果，这是什么问题呢？

**Comment by hkzero** [comment]
![image](https://user-images.githubusercontent.com/4122641/179148660-cc77cb7c-cfa5-4e2c-b576-ae435af3e1f9.png)

**Comment by hkzero** [comment]
![image](https://user-images.githubusercontent.com/4122641/179148862-cccbf2a9-b9f5-442c-84ba-6d42fd1d7518.png)

**Comment by hkzero** [comment]
set FLASK_ENV=server
nohup hub serving start -c /apps/config.json &

**Comment by buchongyu2** [comment]
图片转化成 base64编码后，大小会变成原来的1.3倍。
可以看看是不是上传的图片太大，用个小图片测试下。
然后可以每个阶段都把时间打印出来，分析下哪个过程耗时来解决即可。

**Comment by hkzero** [comment]
> 

我解决了，我看了paddlehub的源码，感觉他那个http接口内部又使用了socket，在进程间通信，不太明白他那样做的原因，我自己用flask写了一个http接口直接调用模型识别，1s就能返回

**Comment by hkzero** [comment]
![image](https://user-images.githubusercontent.com/4122641/179181470-b8341ff0-2055-4ddd-9080-cfc1e7d48c36.png)
