### ISSUE TITLE
save_inference_model 出错

### ISSUE THREAD

**Issue by tangtang666** [PaddlePaddle/PaddleFormers#1929]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub2.2.0，PaddlePaddle2.3.1
2）系统环境：Linux，python版本3.7
- 复现信息：AttributeError: module 'paddle' has no attribute 'Executor
```python
# coding: utf8
import paddlehub as hub
module = hub.Module(name="pyramidbox_lite_mobile_mask")
# 将模型保存在test_program文件夹之中
module.processor.save_inference_model(dirname="test_program") 
#module.save_inference_model(dirname="test_program") 

```

**Comment by tangtang666** [comment]
module = hub.Module(name="pyramidbox_lite_mobile_mask",version="1.2.0")

版本1.2.0的模型可以导出

**Comment by tangtang666** [comment]
module = hub.Module(name="pyramidbox_lite_mobile_mask",version="1.2.0")

版本1.2.0的模型可以导出

**Comment by StrongandSurvive** [comment]
请问1.2.0和最新版效果差距大吗？

**Comment by jm12138** [comment]
> 请问1.2.0和最新版效果差距大吗？

模型效果没有区别
