### ISSUE TITLE
预测多卡问题

### ISSUE THREAD

**Issue by ZhongliGao** [PaddlePaddle/PaddleFormers#1930]
hub预测现在支持多卡吗？
如果不支持的话，以后会考虑支持多卡预测吗？

**Comment by jm12138** [comment]
目前不支持多卡，目前暂时还没有考虑支持多卡预测

**Comment by ZhongliGao** [comment]
> 目前不支持多卡，目前暂时还没有考虑支持多卡预测

好的谢谢您的回答。
