### ISSUE TITLE
data换成自己的跑出的结果不好

### ISSUE THREAD

**Issue by ghm** [PaddlePaddle/PaddleFormers#194]
我在原程序中，将data换成其他文本，如下：
    data = [
        [
            "效果不好的原因是什么呢？句子太短了吗",
            " 今天为什么下雨了呢？昨天天气太闷了吧"
        ],
        ["今天有什么新闻", "冬天来了，春天还会远吗"],
        ["我有两个苹果", "桌上有两个苹果"],
    ]
执行结果如下：
![image](https://user-images.githubusercontent.com/8744664/67255376-5fcbe780-f4b4-11e9-823c-a340d543a7fe.png)
请问是什么原因？

**Comment by ghm** [comment]
另【simnet_bow】问题如下：
https://www.paddlepaddle.org.cn/hubdetail?name=simnet_bow&en_category=SemanticModel
这个例子中的相似度，句子换成不相干的也能相似0.6多，为什么？不相干的不是应该很低的么？
![image](https://user-images.githubusercontent.com/8744664/67256007-7fb0da80-f4b7-11e9-8c56-1904f06bfef1.png)

**Comment by kinghuin** [comment]
@ghm Hi，感谢您的反馈，您程序结果异常的原因是您的输入文本没有分词，正确用法可参考此教程：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.2/tutorial/sentence_sim.md 

您可以尝试用以下代码代替您的data：
```python
    data = [
            ["效果不好的原因是什么呢？句子太短了吗"," 今天为什么下雨了呢？昨天天气太闷了吧"],
            ["今天有什么新闻", "冬天来了，春天还会远吗"],
            ["我有两个苹果", "桌上有两个苹果"],
        ]

    lac = hub.Module(name="lac")
    text = []
    for words in data:
        text.append(words[0])
        text.append(words[1])
    inputs = {"text": text}
    results = lac.lexical_analysis(data=inputs, use_gpu=False, batch_size=10)
    data= []
    for i in range(0,len(text),2):
        data.append([" ".join(results[i]['word']), " ".join(results[i + 1]['word'])])
```

**Comment by ghm** [comment]
@kinghuin 这个问题解决了
另：请问上面第二个问题中simnet_bow的不相关的句子，为什么相似度会是0.6多呢？

**Comment by kinghuin** [comment]
@ghm 这个问题同样是没有分词导致的，分词以后得到的相似度第一个是负数，第三个是0.03，都是很低的

**Comment by ghm** [comment]
@kinghuin 我分词后试了下，还是一样的结果 。
下面例子中也没有分词：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.2/tutorial/sentence_sim.md

我分词后的代码及结果如下：
![image](https://user-images.githubusercontent.com/8744664/67258564-e5a35f00-f4c3-11e9-9729-d89e55c36208.png)

**Comment by kinghuin** [comment]
@ghm 没有注意到是simnet_bow的问题。simnet_bow在输入前可以不分词；它输出的similarity的阈值需要根据具体任务进行判断，不一定>0.5就判作“相似”；因此simnet_bow一般用于判断哪个文本"最"相似，例如：

```python
import paddlehub as hub

simnet_bow = hub.Module(name="simnet_bow")
test_text_1 = ["这道题太难了", "这道题太难了", "这道题太难了"]
test_text_2 = ["这道题是上一年的考题", "这道题不简单", "这道题很有意思"]

inputs = {"text_1": test_text_1, "text_2": test_text_2}
results = simnet_bow.similarity(data=inputs)

max_score = -1
result_text = ""
for result in results:
    if result['similarity'] > max_score:
        max_score = result['similarity']
        result_text = result['text_2']

print("The most matching with the %s is %s" % (test_text_1[0], result_text))
```

**Comment by ghm** [comment]
@kinghuin 原来是这样，多谢解答！
