### ISSUE TITLE
module 'paddlehub' has no attribute 'create_img_cls_task'

### ISSUE THREAD

**Issue by shangfr** [PaddlePaddle/PaddleFormers#199]
PaddleHub十行代码完成迁移学习

task = hub.create_img_cls_task(feature=feature_map, num_classes=dataset.num_labels)

**Comment by Steffy-zxf** [comment]
感谢反馈！查看下PaddleHub的版本，PaddleHub 1.0.0版本之后，对Task进行了升级，create_img_cls_task是 PaddleHub 0.5版本的接口。PaddleHub 每次升级，会增加新功能，修复一些问题。建议升级PaddleHub至目前最新版本1.2.1。相关demo，可以参考：
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.2/demo

**Comment by shangfr** [comment]
谢谢，找到原因了，官网的公开项目教程太旧了，https://aistudio.baidu.com/aistudio/projectdetail/70155
找到了最新的教程：
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E5%9B%BE%E5%83%8F%E5%88%86%E7%B1%BB%E8%BF%81%E7%A7%BB%E6%95%99%E7%A8%8B
