### ISSUE TITLE
pyramidbox_lite_mobile_mask模型导出时遇到问题

### ISSUE THREAD

**Issue by StrongandSurvive** [PaddlePaddle/PaddleFormers#1993]
- 版本、环境信息
1）版本：paddlehub  2.2.0，paddlepaddle-gpu 2.2.2
2）系统环境：Windows10，python 3.7.13

1.直接尝试导出最新模型：
`import paddle`
`import paddlehub as hub`

`module = hub.Module(name="pyramidbox_lite_mobile_mask")`
`module.processor.save_inference_model(dirname="test_program")`

报错：
`AttributeError: module 'paddle' has no attribute 'Executor'`

2.尝试按照#1929所述，将模型版本降至1.2.0：
`import paddlehub as hub`

`module = hub.Module(name="pyramidbox_lite_mobile_mask", version="1.2.0")`
`module.processor.save_inference_model(dirname="test_program")`

报错：
`
"In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and '%s()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode." % func.__name__
AssertionError: In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and 'save_inference_model()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode.
`

3.按照报错修改，增加
`import paddle`
`import paddlehub as hub`

`module = hub.Module(name="pyramidbox_lite_mobile_mask", version="1.2.0")`
`paddle.enable_static()`
`module.processor.save_inference_model(dirname="test_program")`
报错：
`AttributeError: module 'paddle' has no attribute 'Executor'`

请帮助查找一下问题所在，谢谢！

**Comment by jm12138** [comment]
> * 版本、环境信息
>   1）版本：paddlehub  2.2.0，paddlepaddle-gpu 2.2.2
>   2）系统环境：Windows10，python 3.7.13
> 
> 1.直接尝试导出最新模型： `import paddle` `import paddlehub as hub`
> 
> `module = hub.Module(name="pyramidbox_lite_mobile_mask")` `module.processor.save_inference_model(dirname="test_program")`
> 
> 报错： `AttributeError: module 'paddle' has no attribute 'Executor'`
> 
> 2.尝试按照#1929所述，将模型版本降至1.2.0： `import paddlehub as hub`
> 
> `module = hub.Module(name="pyramidbox_lite_mobile_mask", version="1.2.0")` `module.processor.save_inference_model(dirname="test_program")`
> 
> 报错： `"In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and '%s()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode." % func.__name__ AssertionError: In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and 'save_inference_model()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode.`
> 
> 3.按照报错修改，增加 `import paddle` `import paddlehub as hub`
> 
> `module = hub.Module(name="pyramidbox_lite_mobile_mask", version="1.2.0")` `paddle.enable_static()` `module.processor.save_inference_model(dirname="test_program")` 报错： `AttributeError: module 'paddle' has no attribute 'Executor'`
> 
> 请帮助查找一下问题所在，谢谢！

* 目前由于兼容性问题，推理模型导出存在一些bug，可以通过指定特定版本的方式暂时解决：
* 安装特定版本模型：

  ```bash
  hub install pyramidbox_lite_mobile_mask==1.3.0
  hub install pyramidbox_lite_mobile==1.2.0
  ```
* 使用如下脚本导出模型：

  ```python
  import paddlehub as hub
  
  module = hub.Module(name="pyramidbox_lite_mobile_mask")
  module.processor.save_inference_model(dirname="test_program")
  ```
* 刚才测试过了，应该是能够正常导出的。

**Comment by StrongandSurvive** [comment]
> > * 版本、环境信息
> >   1）版本：paddlehub  2.2.0，paddlepaddle-gpu 2.2.2
> >   2）系统环境：Windows10，python 3.7.13
> > 
> > 1.直接尝试导出最新模型： `import paddle` `import paddlehub as hub`
> > `module = hub.Module(name="pyramidbox_lite_mobile_mask")` `module.processor.save_inference_model(dirname="test_program")`
> > 报错： `AttributeError: module 'paddle' has no attribute 'Executor'`
> > 2.尝试按照#1929所述，将模型版本降至1.2.0： `import paddlehub as hub`
> > `module = hub.Module(name="pyramidbox_lite_mobile_mask", version="1.2.0")` `module.processor.save_inference_model(dirname="test_program")`
> > 报错： `"In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and '%s()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode." % func.__name__ AssertionError: In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and 'save_inference_model()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode.`
> > 3.按照报错修改，增加 `import paddle` `import paddlehub as hub`
> > `module = hub.Module(name="pyramidbox_lite_mobile_mask", version="1.2.0")` `paddle.enable_static()` `module.processor.save_inference_model(dirname="test_program")` 报错： `AttributeError: module 'paddle' has no attribute 'Executor'`
> > 请帮助查找一下问题所在，谢谢！
> 
> * 目前由于兼容性问题，推理模型导出存在一些bug，可以通过指定特定版本的方式暂时解决：
> * 安装特定版本模型：
>   ```shell
>   hub install pyramidbox_lite_mobile_mask==1.3.0
>   hub install pyramidbox_lite_mobile==1.2.0
>   ```
> * 使用如下脚本导出模型：
>   ```python
>   import paddlehub as hub
>   
>   module = hub.Module(name="pyramidbox_lite_mobile_mask")
>   module.processor.save_inference_model(dirname="test_program")
>   ```
> * 刚才测试过了，应该是能够正常导出的。

感谢，已经尝试过了，顺利导出模型，开始进一步的研究探索~

**Comment by David9591** [comment]
你好，通过参考上述讨论，顺利导出了模型，在paddle框架中也可以顺利加载执行；
但是当我想通过Paddle2ONNX将模型由paddle转为onnx协议时，遇到了问题，在经过查询调研发现Paddle2ONNX对Paddle2.0版本之后导出的模型支持较为完善，pyramidbox_lite_mobile_mask好像是1.x版本导出的模型，导出时会存在问题，请问有解决方案吗？
