### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by K0shachiyamyatA** [PaddlePaddle/PaddleFormers#2004]
Esterday everything worked normal and today while using ernie-vilg i'm getting this error, i'm using last version library and cpu generation
Expecting value: line 1 column 1 (char 0)

**Comment by rainyfly** [comment]
Hi, I think this error may happens accidentally, try again.

**Comment by K0shachiyamyatA** [comment]
> Hi, I think this error may happens accidentally, try again.

Yes, i already figured that out and made replies for my discord bot. But thanks for answer anyway.
