### ISSUE TITLE
Can someeone explain what this is

### ISSUE THREAD

**Issue by inikishev** [PaddlePaddle/PaddleFormers#2011]
lets say i do this 
```
!pip install --upgrade paddlepaddle
!pip install --upgrade paddlehub
```
will this download all 400 models to my computer? Or does it run on a server? Or does it download on demand?

**Comment by jm12138** [comment]
> lets say i do this
> 
> ```
> !pip install --upgrade paddlepaddle
> !pip install --upgrade paddlehub
> ```
> 
> will this download all 400 models to my computer? Or does it run on a server? Or does it download on demand?

The model will be downloaded on demand at runtime, or manually installed using commands.
