### ISSUE TITLE
文档报错：零基础Linux安装并实现图像风格迁移

### ISSUE THREAD

**Issue by wendao365** [PaddlePaddle/PaddleFormers#2019]
[连接](https://github.com/PaddlePaddle/PaddleHub/blob/develop/docs/docs_ch/get_start/linux_quickstart.md#%E7%AC%AC1%E6%AD%A5%E5%AE%89%E8%A3%85anaconda)

这篇文档讲的是在linux下安装运行的quickstart，结论处写成了Windows
```第6步：飞桨预训练模型探索之旅
恭喜你，到这里PaddleHub在windows环境下的安装和入门案例就全部完成了，快快开启你更多的深度学习模型探索之旅吧。[【更多模型探索，跳转飞桨官网】](https://www.paddlepaddle.org.cn/hublist)```

**Comment by jm12138** [comment]
> [连接](https://github.com/PaddlePaddle/PaddleHub/blob/develop/docs/docs_ch/get_start/linux_quickstart.md#%E7%AC%AC1%E6%AD%A5%E5%AE%89%E8%A3%85anaconda)
> 
> 这篇文档讲的是在linux下安装运行的quickstart，结论处写成了Windows
> 
> ```
> 恭喜你，到这里PaddleHub在windows环境下的安装和入门案例就全部完成了，快快开启你更多的深度学习模型探索之旅吧。[【更多模型探索，跳转飞桨官网】](https://www.paddlepaddle.org.cn/hublist)```
> ```

感谢您的反馈，已记录，后续会更新修正的。
