### ISSUE TITLE
文图生成

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleFormers#2057]
您好，文图生成我看提供了api接口来调用，请问提供了离线模型吗？

**Comment by jm12138** [comment]
> 您好，文图生成我看提供了api接口来调用，请问提供了离线模型吗？

暂时没有提供离线模型的计划，更多开源相关的消息，可以关注文心的官网 https://wenxin.baidu.com/  和官方开源项目 https://github.com/PaddlePaddle/ERNIE
