### ISSUE TITLE
openpose 身体骨骼关键点是25个关键点，怎么获取呢？

### ISSUE THREAD

**Issue by z411500976** [PaddlePaddle/PaddleFormers#2060]
我用https://github.com/CMU-Perceptual-Computing-Lab/openpose 这个身体关键点模型转换过来，但是是25个点，paddlehue 模型是17个点，导致获取关键点不正确，需要怎么获取呢？

**Comment by jm12138** [comment]
* openpose 模型训练时使用了不同的数据集，所以关键点的格式和数量略有差异，目前 paddlehub 实现的模型只有 18 个点的这种格式
* 可以根据下图来转换这两种格式的关键点：

  ![c6d25bdc7e9915a1dec117e6754f0e6f9fea6f12 png@942w_1641h_progressive](https://user-images.githubusercontent.com/15712990/194683155-fc41fe59-73e7-427d-816f-3958df2219e5.png)
  <img width="300" alt="ad7120de317f463198343b58edb257fdf7ff64a01ba44d78888f1867bf07d1fb" src="https://user-images.githubusercontent.com/15712990/194683156-d1d93c7e-5a7a-4a1b-b399-34ec2e51da54.png">

**Comment by z411500976** [comment]
才接触深度学习这方便，相当于小白，有没有教程呢？谢谢
