### ISSUE TITLE
使用paddlehub的UGATIT_100w模型生成的结果图尺寸比原图小

### ISSUE THREAD

**Issue by thgpddl** [PaddlePaddle/PaddleFormers#2063]
我使用paddlehub的UGATIT_100w模型，通过给定一张图片，期望生成动漫风格的效果图。虽然能够成功生成动漫风格的效果图，但是效果图尺寸比原图小得多，这是我设置有问题还是模型本身的输出图就是缩小的图？

**Comment by jm12138** [comment]
> 我使用paddlehub的UGATIT_100w模型，通过给定一张图片，期望生成动漫风格的效果图。虽然能够成功生成动漫风格的效果图，但是效果图尺寸比原图小得多，这是我设置有问题还是模型本身的输出图就是缩小的图？

* 该模型的输入输出为 256x256 的图像，如果输入图像尺寸过大或过小都会缩放至 256x256。所以导致输出的图像偏小。

**Comment by thgpddl** [comment]
明白了谢谢

发自我的移动设备
