### ISSUE TITLE
PaddleHub 数据集该怎么定义

### ISSUE THREAD

**Issue by playgit2001** [PaddlePaddle/PaddleFormers#2064]
操作系统：win10
python：3.7
目前使用paddlehub 的ch_pp_ocrv3，想对预训练模型进行训练，请问该怎么定义数据集。OCR，是只需要一个trains.txt，里面包括图片路径和标签吗？标签等于识别结果吗？

**Comment by jm12138** [comment]
paddlehub 这些ocr模型暂不支持微调训练，如需训练可参考 [paddleocr](https://github.com/PaddlePaddle/PaddleOCR) 项目文档

**Comment by playgit2001** [comment]
意思是说paddlehub 的ocr预训练模型不能进行微调训练，只能使用paddleOcr的通用模型，然后对paddleOcr的通用模型进行训练，最后给paddleOcr使用对吗？

**Comment by playgit2001** [comment]
意思是说paddlehub 的ocr预训练模型不能进行微调训练，只能使用paddleOcr的通用模型，然后对paddleOcr的通用模型进行训练，最后放进paddlehub的module文件夹下，然后进行在线服务是吗？

**Comment by jm12138** [comment]
> 意思是说paddlehub 的ocr预训练模型不能进行微调训练，只能使用paddleOcr的通用模型，然后对paddleOcr的通用模型进行训练，最后放进paddlehub的module文件夹下，然后进行在线服务是吗？

可以这么操作，不过，如果你需要微调模型的话，推荐使用 paddleocr 项目中的部署方式进行部署。

**Comment by playgit2001** [comment]
你说的部署是用 PaddleOCR/deploy/hubserving  ，这个集成在paddleOcr下的部署吗？

**Comment by playgit2001** [comment]
比如说下面的这篇文章中的部署方式，http://t.csdn.cn/GEDtm

**Comment by playgit2001** [comment]
还有就是为什么推荐使用paddleOcr项目中的部署方式有什么好处吗？

**Comment by jm12138** [comment]
> 还有就是为什么推荐使用paddleOcr项目中的部署方式有什么好处吗？

paddleocr 部署的文档相对详细，自定义程度高，对微调过的模型支持比较好。
