### ISSUE TITLE
paddlehub使用disco diffusion ernievil base 报错

### ISSUE THREAD

**Issue by ionescofung** [PaddlePaddle/PaddleFormers#2067]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

环境：
windows11
python 3.8.13
paddlepaddle 2.3.2
paddlehub2.3.0
代码：
import paddlehub as hub

module = hub.Module(name="disco_diffusion_ernievil_base")
text_prompts = ["孤舟蓑笠翁，独钓寒江雪。"]
da = module.generate_image(text_prompts=text_prompts, artist='齐白石', output_dir='./disco_diffusion_ernievil_base_out/')  
da[0].save_uri_to_file('disco_diffusion_ernievil_base_out-result.png')
da[0].chunks.plot_image_sprites(skip_empty=True, show_index=True, keep_aspect_ratio=True)
da[0].chunks.save_gif('disco_diffusion_ernievil_base_out-result.gif')
运行提示错误：
C:\Users\62845\.conda\envs\paddle2\lib\site-packages\paddlenlp\transformers\image_utils.py:213: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  resample=Image.BILINEAR,
C:\Users\62845\.conda\envs\paddle2\lib\site-packages\paddlenlp\transformers\image_utils.py:379: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  resample=Image.NEAREST,
C:\Users\62845\.conda\envs\paddle2\lib\site-packages\paddlenlp\transformers\ernie_vil\feature_extraction.py:65: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  resample=Image.BICUBIC,
C:\Users\62845\.conda\envs\paddle2\lib\site-packages\paddlenlp\transformers\clip\feature_extraction.py:64: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  resample=Image.BICUBIC,
W1011 11:49:58.713550  3056 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.6
W1011 11:49:58.718113  3056 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Traceback (most recent call last):
  File "D:/python/envs/paddle2/paddlehub/hub_disco.py", line 7, in <module>
    da = module.generate_image(text_prompts=text_prompts,
  File "C:\Users\62845\.conda\envs\paddle2\lib\site-packages\paddlehub\compat\paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "C:\Users\62845\.paddlehub\modules\disco_diffusion_ernievil_base\module.py", line 139, in generate_image
    return create(text_prompts=text_prompts,
  File "C:\Users\62845\.paddlehub\modules\disco_diffusion_ernievil_base\reverse_diffusion\__init__.py", line 127, in create
    from .config import load_config
  File "C:\Users\62845\.paddlehub\modules\disco_diffusion_ernievil_base\reverse_diffusion\config.py", line 16, in <module>
    default_args = yaml.load(ymlfile, Loader=Loader)
  File "C:\Users\62845\.conda\envs\paddle2\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\62845\.conda\envs\paddle2\lib\site-packages\yaml\loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\62845\.conda\envs\paddle2\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\62845\.conda\envs\paddle2\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\62845\.conda\envs\paddle2\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 70: illegal multibyte sequence

**Comment by jm12138** [comment]
> 欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！ 在留下您的问题时，辛苦您同步提供如下信息：
> 
> * 版本、环境信息
>   1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
>   2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
> * 复现信息：如为报错，请给出复现环境、复现步骤
> 
> 环境： windows11 python 3.8.13 paddlepaddle 2.3.2 paddlehub2.3.0 代码： import paddlehub as hub
> 
> module = hub.Module(name="disco_diffusion_ernievil_base") text_prompts = ["孤舟蓑笠翁，独钓寒江雪。"] da = module.generate_image(text_prompts=text_prompts, artist='齐白石', output_dir='./disco_diffusion_ernievil_base_out/') da[0].save_uri_to_file('disco_diffusion_ernievil_base_out-result.png') da[0].chunks.plot_image_sprites(skip_empty=True, show_index=True, keep_aspect_ratio=True) da[0].chunks.save_gif('disco_diffusion_ernievil_base_out-result.gif') 运行提示错误： C:\Users\62845.conda\envs\paddle2\lib\site-packages\paddlenlp\transformers\image_utils.py:213: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. resample=Image.BILINEAR, C:\Users\62845.conda\envs\paddle2\lib\site-packages\paddlenlp\transformers\image_utils.py:379: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. resample=Image.NEAREST, C:\Users\62845.conda\envs\paddle2\lib\site-packages\paddlenlp\transformers\ernie_vil\feature_extraction.py:65: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. resample=Image.BICUBIC, C:\Users\62845.conda\envs\paddle2\lib\site-packages\paddlenlp\transformers\clip\feature_extraction.py:64: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. resample=Image.BICUBIC, W1011 11:49:58.713550 3056 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.6 W1011 11:49:58.718113 3056 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4. Traceback (most recent call last): File "D:/python/envs/paddle2/paddlehub/hub_disco.py", line 7, in da = module.generate_image(text_prompts=text_prompts, File "C:\Users\62845.conda\envs\paddle2\lib\site-packages\paddlehub\compat\paddle_utils.py", line 221, in runner return func(*args, **kwargs) File "C:\Users\62845.paddlehub\modules\disco_diffusion_ernievil_base\module.py", line 139, in generate_image return create(text_prompts=text_prompts, File "C:\Users\62845.paddlehub\modules\disco_diffusion_ernievil_base\reverse_diffusion__init__.py", line 127, in create from .config import load_config File "C:\Users\62845.paddlehub\modules\disco_diffusion_ernievil_base\reverse_diffusion\config.py", line 16, in default_args = yaml.load(ymlfile, Loader=Loader) File "C:\Users\62845.conda\envs\paddle2\lib\site-packages\yaml__init__.py", line 79, in load loader = Loader(stream) File "C:\Users\62845.conda\envs\paddle2\lib\site-packages\yaml\loader.py", line 44, in **init** Reader.**init**(self, stream) File "C:\Users\62845.conda\envs\paddle2\lib\site-packages\yaml\reader.py", line 85, in **init** self.determine_encoding() File "C:\Users\62845.conda\envs\paddle2\lib\site-packages\yaml\reader.py", line 124, in determine_encoding self.update_raw() File "C:\Users\62845.conda\envs\paddle2\lib\site-packages\yaml\reader.py", line 178, in update_raw data = self.stream.read(size) UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 70: illegal multibyte sequence

* 请尝试在代码的开头添加：
```python
import os
os.environ['PYTHONUTF8'] = '1'
```
* 或者使用 python -X utf8 xxx.py 执行python脚本
* 或者在系统中添加环境变量 `PYTHONUTF8=1`

**Comment by ionescofung** [comment]
使用 python -X utf8 xxx.py 执行python脚本成功
谢谢
