### ISSUE TITLE
安装模型报错

### ISSUE THREAD

**Issue by hbo-lambda** [PaddlePaddle/PaddleFormers#2072]
![image](https://user-images.githubusercontent.com/7626261/195753419-c7031f28-3e5f-44e4-a5f5-f1254e18482b.png)
想试用模型，可是却报错了

paddlepaddle 2.3.0
paddle hub 2.3.0

**Comment by jm12138** [comment]
> ![image](https://user-images.githubusercontent.com/7626261/195753419-c7031f28-3e5f-44e4-a5f5-f1254e18482b.png) 想试用模型，可是却报错了
> 
> paddlepaddle 2.3.0 paddle hub 2.3.0

* 看报错好像是网络问题

**Comment by hbo-lambda** [comment]
> 

网络是通的，pip、apt等等安装第三方包没问题的

**Comment by hbo-lambda** [comment]
> > 
> 
> 网络是通的，pip、apt等等安装第三方包没问题的

没事了，在另外的环境里装了一遍paddlehub，查了下hub config的server。在原来的环境里设置了下hub server地址：
hub config server==http://paddlepaddle.org.cn/paddlehub。这个地址也不知道官网上在哪儿说明的，反正我是没找到
