### ISSUE TITLE
倾斜图片矫正

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleFormers#2078]
请问下，如何将一张图片识别倾斜的角度，并将图片转正过来。可以给几行代码？

**Comment by jm12138** [comment]
> 请问下，如何将一张图片识别倾斜的角度，并将图片转正过来。可以给几行代码？

目前 paddlehub 没有能够实现相关操作的模型

**Comment by tianchiguaixia** [comment]
那paddlehub里面的ocr模型如何识别倾斜图片内容的。不矫正怎么识别

**Comment by jm12138** [comment]
> 那paddlehub里面的ocr模型如何识别倾斜图片内容的。不矫正怎么识别

ocr 检测模型会输出文本框的四个坐标的，是一个不规则的四边形，然后通过图像变换得到一个规则的矩形，这样图像就矫正好了， 具体操作可以参考一下：[如何进行图像矫正？OpenCV图像矫正算法实战！](https://www.w3cschool.cn/article/20774695.html)

**Comment by tianchiguaixia** [comment]
目前我的图片有的切斜90度，有的180，有的270。目前我想的是，有没有什么方法或者模型。如果我输入一张图片就能判断角度是（0,90,180,270）

**Comment by jm12138** [comment]
> 目前我的图片有的切斜90度，有的180，有的270。目前我想的是，有没有什么方法或者模型。如果我输入一张图片就能判断角度是（0,90,180,270）

ppocr 里面有个角度分类模型，不过只能识别 0，180 度
