### ISSUE TITLE
使用出现RuntimeError

### ISSUE THREAD

**Issue by liaoxuewei** [PaddlePaddle/PaddleFormers#2084]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：paddlehub==1.8.3，paddlepaddle==2.3.2
2）系统环境：Windows 7
- 复现信息：如为报错，请给出复现环境、复现步骤
```
import paddlehub as hub


def genImage():
    module = hub.Module(name="ernie_vilg")
    results = module.generate_image(text_prompts=["王者之心"])


def textAna():
    lac = hub.Module(name="lac")
    test_text = ["今天是个好天气。"]

    results = lac.cut(
        text=test_text, use_gpu=False, batch_size=1, return_tag=True)
    print(results)
    #{'word': ['今天', '是', '个', '好天气', '。'], 'tag': ['TIME', 'v', 'q', 'n', 'w']}


genImage()
#textAna()
```

无论调用genImage()还是textAna()函数，都会出现RuntimeError

```
[2022-10-24 09:40:04,237] [    INFO] - Installing ernie_vilg module
Traceback (most recent call last):
  File "e:/MyProjects/py-demo/aiApp/ai02.py", line 26, in <module>
    genImage()
  File "e:/MyProjects/py-demo/aiApp/ai02.py", line 12, in genImage
    module = hub.Module(name="ernie_vilg")
  File "E:\Python37\lib\site-packages\paddlehub\module\module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "E:\Python37\lib\site-packages\paddlehub\module\module.py", line 171, in init_with_name
    module_name=name, module_version=version, extra=extra)
  File "E:\Python37\lib\site-packages\paddlehub\module\manager.py", line 127, in install_module
    self.all_modules(update=True)
  File "E:\Python37\lib\site-packages\paddlehub\module\manager.py", line 105, in all_modules
    valid, info = self.check_module_valid(sub_dir_path)
  File "E:\Python37\lib\site-packages\paddlehub\module\manager.py", line 72, in check_module_valid
    "{}.module".format(basename))
  File "E:\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\liaoxuewei\.paddlehub\modules\ernie_vilg\module.py", line 29, in <module>
    author_email="paddle-dev@baidu.com")
  File "E:\Python37\lib\site-packages\paddlehub\module\module.py", line 80, in _wrapper
    raise RuntimeError
RuntimeError
```

**Comment by jm12138** [comment]
> * 版本、环境信息
>   1）PaddleHub和PaddlePaddle版本：paddlehub==1.8.3，paddlepaddle==2.3.2
>   2）系统环境：Windows 7
> * 复现信息：如为报错，请给出复现环境、复现步骤
> 
> ```
> import paddlehub as hub
> 
> 
> def genImage():
>     module = hub.Module(name="ernie_vilg")
>     results = module.generate_image(text_prompts=["王者之心"])
> 
> 
> def textAna():
>     lac = hub.Module(name="lac")
>     test_text = ["今天是个好天气。"]
> 
>     results = lac.cut(
>         text=test_text, use_gpu=False, batch_size=1, return_tag=True)
>     print(results)
>     #{'word': ['今天', '是', '个', '好天气', '。'], 'tag': ['TIME', 'v', 'q', 'n', 'w']}
> 
> 
> genImage()
> #textAna()
> ```
> 
> 无论调用genImage()还是textAna()函数，都会出现RuntimeError
> 
> ```
> [2022-10-24 09:40:04,237] [    INFO] - Installing ernie_vilg module
> Traceback (most recent call last):
>   File "e:/MyProjects/py-demo/aiApp/ai02.py", line 26, in <module>
>     genImage()
>   File "e:/MyProjects/py-demo/aiApp/ai02.py", line 12, in genImage
>     module = hub.Module(name="ernie_vilg")
>   File "E:\Python37\lib\site-packages\paddlehub\module\module.py", line 102, in __new__
>     name=name, version=version, **kwargs)
>   File "E:\Python37\lib\site-packages\paddlehub\module\module.py", line 171, in init_with_name
>     module_name=name, module_version=version, extra=extra)
>   File "E:\Python37\lib\site-packages\paddlehub\module\manager.py", line 127, in install_module
>     self.all_modules(update=True)
>   File "E:\Python37\lib\site-packages\paddlehub\module\manager.py", line 105, in all_modules
>     valid, info = self.check_module_valid(sub_dir_path)
>   File "E:\Python37\lib\site-packages\paddlehub\module\manager.py", line 72, in check_module_valid
>     "{}.module".format(basename))
>   File "E:\Python37\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "C:\Users\liaoxuewei\.paddlehub\modules\ernie_vilg\module.py", line 29, in <module>
>     author_email="paddle-dev@baidu.com")
>   File "E:\Python37\lib\site-packages\paddlehub\module\module.py", line 80, in _wrapper
>     raise RuntimeError
> RuntimeError
> ```

可能是 PaddleHub 版本过低导致的，paddlepaddle >= 2.0.0 请搭配 paddlehub >= 2.0.0 使用

建议使用如下命令升级 PaddleHub 后重试：

```bash
$ pip install paddlehub==2.3.0
```

**Comment by liaoxuewei** [comment]
可以了，为什么不指定版本默认安装的是1.8.3呢？

**Comment by jm12138** [comment]
> 可以了，为什么不指定版本默认安装的是1.8.3呢？

一般不加版本号默认安装也是最新正式版本（现在是 2.3.0），可能是因为其他的模块安装或者版本的原因导致装成了 1.8.3 的版本。

**Comment by liaoxuewei** [comment]
Ok，感谢！
