### ISSUE TITLE
版本环境

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleFormers#2096]
https://aistudio.baidu.com/aistudio/projectdetail/147006?channelType=0&channel=0
环境一直跑不通：dataset = hub.datasets.ChnSentiCorp()
报错：
![image](https://user-images.githubusercontent.com/29837553/198917284-54d1c995-5f6f-4d3d-89c9-918895983352.png)
请问下，paddlehub文本分类，有跑的通的环境？

**Comment by jm12138** [comment]
> https://aistudio.baidu.com/aistudio/projectdetail/147006?channelType=0&channel=0

这个项目有点旧了，可以试试 https://aistudio.baidu.com/aistudio/projectdetail/1467767

**Comment by tianchiguaixia** [comment]
ok，谢谢

**Comment by tianchiguaixia** [comment]
不好意思，可以再推荐一个图像分类的最新的项目链接？类似上面你发的那个

**Comment by jm12138** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/1749014

**Comment by tianchiguaixia** [comment]
谢谢
