### ISSUE TITLE
安装paddlehub报错

### ISSUE THREAD

**Issue by vitoman** [PaddlePaddle/PaddleFormers#210]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/23158451/67825524-84ebd600-fb04-11e9-8d96-877bc5819f2c.png">

这个该如何解决呢，感谢~~

**Comment by Steffy-zxf** [comment]
感谢反馈！尝试手动卸载imageio, 再重新安装paddlehub，如：
```shell
pip uninstall imageio
pip install paddlehub
```

**Comment by vitoman** [comment]
<img width="1126" alt="屏幕快照 2019-10-30 上午11 16 59" src="https://user-images.githubusercontent.com/23158451/67826429-689d6880-fb07-11e9-9b06-fb3edce93adf.png">
手工卸载也报相同的错误

**Comment by Steffy-zxf** [comment]
参考下面链接的做法：
https://stackoverflow.com/questions/50421287/pip-cannot-uninstall-ipython-it-is-a-distutils-installed-project-and-thus-w
```shell
sudo -H pip install --ignore-installed -U imageio
```

**Comment by vitoman** [comment]
已解决，感谢
