### ISSUE TITLE
ERNIE-VILG总访问量超限

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/PaddleFormers#2110]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by yytdfc** [comment]
same error on HuggingFace

**Comment by jm12138** [comment]
* 已收到反馈。该问题目前正在修复。

**Comment by wanpower** [comment]
这个版本不是离线的，训练会去服务器验证，验证不通过，就不能继续了

**Comment by qiceng** [comment]
ERNIE-VILG服务已修复，可以使用了，感谢对ERNIE-VILG支持
