### ISSUE TITLE
 PaddleHub模型下载后在PaddleDetection中部署的问题

### ISSUE THREAD

**Issue by bittergourd1224** [PaddlePaddle/PaddleFormers#2131]
我想在PaddleDetection中使用C++运行 PaddleHub模型的模型。我下载了https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_mobile_mask&en_category=FaceDetection 中的模型，保存到本地后只有 __model__和__params__两个文件。但是PaddleDetection还需要infer_cfg.yml才可以运行，请问有什么方法能够得到模型对应的这个文件吗？

PaddleHub版本2.5
PaddleDetection版本2.5

**Comment by jm12138** [comment]
> 我想在PaddleDetection中使用C++运行 PaddleHub模型的模型。我下载了https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_mobile_mask&en_category=FaceDetection 中的模型，保存到本地后只有 __model__和__params__两个文件。但是PaddleDetection还需要infer_cfg.yml才可以运行，请问有什么方法能够得到模型对应的这个文件吗？
> 
> PaddleHub版本2.5 PaddleDetection版本2.5

pyramidbox_lite_mobile_mask 这个模型包含两个部分，人脸检测和口罩佩戴分类模型。所以没法直接套到 paddledetection 的代码进行推理的。如果需要c++部署，可以尝试使用 paddledetection 自带的人脸检测模型导出后部署，口罩佩戴分类模型比较麻烦，目前没有现成的 c++ 推理代码，可能需要自行编写 c++ 推理代码，或使用 paddleclas 的推理代码进行修改。

**Comment by bittergourd1224** [comment]
> > 我想在PaddleDetection中使用C++运行 PaddleHub模型的模型。我下载了https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_mobile_mask&en_category=FaceDetection 中的模型，保存到本地后只有 __model__和__params__两个文件。但是PaddleDetection还需要infer_cfg.yml才可以运行，请问有什么方法能够得到模型对应的这个文件吗？
> > PaddleHub版本2.5 PaddleDetection版本2.5
> 
> pyramidbox_lite_mobile_mask 这个模型包含两个部分，人脸检测和口罩佩戴分类模型。所以没法直接套到 paddledetection 的代码进行推理的。如果需要c++部署，可以尝试使用 paddledetection 自带的人脸检测模型导出后部署，口罩佩戴分类模型比较麻烦，目前没有现成的 c++ 推理代码，可能需要自行编写 c++ 推理代码，或使用 paddleclas 的推理代码进行修改。

感谢回复。paddledetection的人脸检测模型我试用过，不过担心在佩戴口罩后的准确率如何。另外口罩佩戴分类模型，指其实这是一个分类模型而不是目标检测模型吗？如果只是代码逻辑上需要自行编写，其实工作量还好，比如检测到人脸后，将人脸切割出来送入口罩佩戴模型。不过现在由于缺少infer_cfg.yml这个文件，导致现在各个模型单独加载都会失败，这个有没有什么办法呢？

**Comment by jm12138** [comment]
> > > 我想在PaddleDetection中使用C++运行 PaddleHub模型的模型。我下载了https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_mobile_mask&en_category=FaceDetection 中的模型，保存到本地后只有 __model__和__params__两个文件。但是PaddleDetection还需要infer_cfg.yml才可以运行，请问有什么方法能够得到模型对应的这个文件吗？
> > > PaddleHub版本2.5 PaddleDetection版本2.5
> > 
> > 
> > pyramidbox_lite_mobile_mask 这个模型包含两个部分，人脸检测和口罩佩戴分类模型。所以没法直接套到 paddledetection 的代码进行推理的。如果需要c++部署，可以尝试使用 paddledetection 自带的人脸检测模型导出后部署，口罩佩戴分类模型比较麻烦，目前没有现成的 c++ 推理代码，可能需要自行编写 c++ 推理代码，或使用 paddleclas 的推理代码进行修改。
> 
> 感谢回复。paddledetection的人脸检测模型我试用过，不过担心在佩戴口罩后的准确率如何。另外口罩佩戴分类模型，指其实这是一个分类模型而不是目标检测模型吗？如果只是代码逻辑上需要自行编写，其实工作量还好，比如检测到人脸后，将人脸切割出来送入口罩佩戴模型。不过现在由于缺少infer_cfg.yml这个文件，导致现在各个模型单独加载都会失败，这个有没有什么办法呢？

* 人脸检测模型其实都一样，pyramidbox_lite_mobile_mask 这里面的检测模型也没有针对带口罩的场景进行微调
* 口罩佩戴是一个分类模型
* pyramidbox_lite_mobile_mask 就是检测人脸后分类
* infer_cfg.yml 这个可以自己参考其他模型的文件改改看，因为这个格式是 ppdet 专用的，paddlehub这边没有这个文件

**Comment by bittergourd1224** [comment]
> > > > 我想在PaddleDetection中使用C++运行 PaddleHub模型的模型。我下载了https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_mobile_mask&en_category=FaceDetection 中的模型，保存到本地后只有 __model__和__params__两个文件。但是PaddleDetection还需要infer_cfg.yml才可以运行，请问有什么方法能够得到模型对应的这个文件吗？
> > > > PaddleHub版本2.5 PaddleDetection版本2.5
> > > 
> > > 
> > > pyramidbox_lite_mobile_mask 这个模型包含两个部分，人脸检测和口罩佩戴分类模型。所以没法直接套到 paddledetection 的代码进行推理的。如果需要c++部署，可以尝试使用 paddledetection 自带的人脸检测模型导出后部署，口罩佩戴分类模型比较麻烦，目前没有现成的 c++ 推理代码，可能需要自行编写 c++ 推理代码，或使用 paddleclas 的推理代码进行修改。
> > 
> > 
> > 感谢回复。paddledetection的人脸检测模型我试用过，不过担心在佩戴口罩后的准确率如何。另外口罩佩戴分类模型，指其实这是一个分类模型而不是目标检测模型吗？如果只是代码逻辑上需要自行编写，其实工作量还好，比如检测到人脸后，将人脸切割出来送入口罩佩戴模型。不过现在由于缺少infer_cfg.yml这个文件，导致现在各个模型单独加载都会失败，这个有没有什么办法呢？
> 
> * 人脸检测模型其实都一样，pyramidbox_lite_mobile_mask 这里面的检测模型也没有针对带口罩的场景进行微调
> * 口罩佩戴是一个分类模型
> * pyramidbox_lite_mobile_mask 就是检测人脸后分类
> * infer_cfg.yml 这个可以自己参考其他模型的文件改改看，因为这个格式是 ppdet 专用的，paddlehub这边没有这个文件

感谢解答~口罩佩戴是分类模型的话，那可能是没法实现在ppdet中调用。那我再去了解下是否能直接用paddle inference进行推理。或者有用paddle inference推理paddlehub模型的demo吗？

**Comment by jm12138** [comment]
> 感谢解答~口罩佩戴是分类模型的话，那可能是没法实现在ppdet中调用。那我再去了解下是否能直接用paddle inference进行推理。或者有用paddle inference推理paddlehub模型的demo吗？

* python 版本的推理代码可以参考 [modules/image/face_detection/pyramidbox_lite_mobile_mask](https://github.com/PaddlePaddle/PaddleHub/tree/develop/modules/image/face_detection/pyramidbox_lite_mobile_mask)
* paddlehub 不提供 c++ 相关的推理代码，可以自行根据 python 代码进行编写。

**Comment by bittergourd1224** [comment]
> > 感谢解答~口罩佩戴是分类模型的话，那可能是没法实现在ppdet中调用。那我再去了解下是否能直接用paddle inference进行推理。或者有用paddle inference推理paddlehub模型的demo吗？
> 
> * python 版本的推理代码可以参考 [modules/image/face_detection/pyramidbox_lite_mobile_mask](https://github.com/PaddlePaddle/PaddleHub/tree/develop/modules/image/face_detection/pyramidbox_lite_mobile_mask)
> * paddlehub 不提供 c++ 相关的推理代码，可以自行根据 python 代码进行编写。

好的了解。使用下来paddlehub、paddlex、paddledetection都有各自的部署API，学习和兼容不同API的时间成本较高，后面可以考虑打通一下。
