### ISSUE TITLE
mismatch PaddleHub2.0.0  and PaddlePaddle2.0.0

### ISSUE THREAD

**Issue by MaxokDavid** [PaddlePaddle/PaddleFormers#2156]
1）PaddleHub2.0.0和PaddlePaddle2.0.0版本
2）系统环境：Windows
when run 二、加载预训练模型
the error
PaddleHub2.0.0和PaddlePaddle2.0.0 is mismatch ，but  this version  following the guidance                    
  https://aistudio.baidu.com/aistudio/projectdetail/507159?channelType=0&channel=0

**Comment by jm12138** [comment]
建议升级至 paddlepaddle==2.3.2 paddlehub==2.3.1 使用

**Comment by MaxokDavid** [comment]
It's useful , thanks a lot.
















在 2022-12-02 15:30:39，"jm12138" ***@***.***> 写道：

建议升级至 paddlepaddle==2.3.2 paddlehub==2.3.1 使用
