### ISSUE TITLE
yolov3_darknet53_pedestrian行人检测模型预测出错

### ISSUE THREAD

**Issue by tianmaxingkong168** [PaddlePaddle/PaddleFormers#2191]
操作系统： Ubuntu20.04
CPU or GPU： CPU
版本信息如下：
paddlehub： 2.3.1
paddlepaddle： 2.4.1
报错信息如下：
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlehub as hub
/home/app/py4pphub/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
>>> import cv2
>>>
>>> pedestrian_detector = hub.Module(name="yolov3_darknet53_pedestrian")
>>> result = pedestrian_detector.object_detection(images=[cv2.imread('baideng.jpeg')])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/app/py4pphub/lib/python3.8/site-packages/paddlehub/compat/paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "/home/app/.paddlehub/modules/yolov3_darknet53_pedestrian/module.py", line 105, in object_detection
    feed_data = np.array(feed_data)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.
>>> result = pedestrian_detector.object_detection(images=[cv2.imread('000000014439.jpg')])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/app/py4pphub/lib/python3.8/site-packages/paddlehub/compat/paddle_utils.py", line 221, in runner
    return func(*args, **kwargs)
  File "/home/app/.paddlehub/modules/yolov3_darknet53_pedestrian/module.py", line 105, in object_detection
    feed_data = np.array(feed_data)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.
部署为服务通过http接口请求报错如下：
{'msg': 'setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.', 'results': '', 'status': '101'}

**Comment by rainyfly** [comment]
你好，是每张图片都会报这个错误么，我这边跑了一张图可以跑通

**Comment by tianmaxingkong168** [comment]
> 你好，是每张图片都会报这个错误么，我这边跑了一张图可以跑通

测试了两张图片，一张是000000014439.jpg，一张是网上下载的。稍晚一些我再试一下。

**Comment by tianmaxingkong168** [comment]
> 你好，是每张图片都会报这个错误么，我这边跑了一张图可以跑通
![错误信息](https://user-images.githubusercontent.com/68491689/210688950-97c19213-85e9-4fdf-86c8-b5c902ed3574.png)
又尝试了命令行和API两种方式预测，还是一样的错误，不知道是不是版本的原因。

**Comment by rainyfly** [comment]
很奇怪诶，我这边和你环境版本是一样的没有报错。会不会是模块版本的问题，你试试hub uninstall 这个模块，然后重新安装一下试试看。

**Comment by wanghchen** [comment]
我目前也遇到了这样的问题，难道是yolov3相关的object detection模型都会出现这个问题吗？

**Comment by tianmaxingkong168** [comment]
原来是版本不匹配导致的，降低版本就正常了。如果能给出版本要求就好了。
(py4pp) app@ubuntu18:~$ pip list|grep paddle
paddle2onnx         1.0.5
paddlefsl           1.1.0
paddlehub           2.1.0
paddlenlp           2.2.0
paddlepaddle        2.2.0
(py4pp) app@ubuntu18:~$ hub run yolov3_darknet53_pedestrian --input_path "000000014439.jpg"
[2023-01-17 03:40:22,585] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
W0117 03:40:22.586536  6436 analysis_predictor.cc:1353] Deprecated. Please use CreatePredictor instead.
[{'data': [{'label': 'pedestrian', 'confidence': 0.8740391731262207, 'left': 502.9425048828125, 'top': 112.24583435058594, 'right': 600.0916748046875, 'bottom': 276.62353515625}, {'label': 'pedestrian', 'confidence': 0.8344127535820007, 'left': 401.73773193359375, 'top': 90.59823608398438, 'right': 505.46734619140625, 'bottom': 284.4360656738281}, {'label': 'pedestrian', 'confidence': 0.64225834608078, 'left': 579.5266723632812, 'top': 112.4227066040039, 'right': 611.8283081054688, 'bottom': 201.43072509765625}, {'label': 'pedestrian', 'confidence': 0.6136857271194458, 'left': 162.73565673828125, 'top': 81.39930725097656, 'right': 196.91366577148438, 'bottom': 167.2406005859375}, {'label': 'pedestrian', 'confidence': 0.473660409450531, 'left': 269.3009338378906, 'top': 84.3621826171875, 'right': 295.2157287597656, 'bottom': 166.55848693847656}]}]

**Comment by kenJPG** [comment]
能列出你使用的版本吗? thx

**Comment by rainyfly** [comment]
paddlehub 2.3.1 paddle2.4.2 直接hub install 这个模型，可以跑吗

**Comment by tianmaxingkong168** [comment]
> paddlehub 2.3.1 paddle2.4.2 直接hub install 这个模型，可以跑吗

最近没试过。

**Comment by tianmaxingkong168** [comment]
> 能列出你使用的版本吗? thx

版本已经列出了。 见这条命令输出结果：pip list|grep paddle

**Comment by kenJPG** [comment]
问题是 numpy 1.24。必须使用 numpy 1.22.4
