### ISSUE TITLE
调用openpose_body_estimation返回数据使用问题

### ISSUE THREAD

**Issue by Gray-web** [PaddlePaddle/PaddleFormers#2198]
输入预测图片进入openpose_body_estimation模型返回结果包含以下数据：
res (dict): 识别结果的列表，列表元素为 dict, 有以下两个字段：
data : 可视化图片内容(numpy.ndarray，BGR格式);
candidate: 图片中所有肢体关键点坐标;
subset: 不同的人不同关键点对应的关键点坐标的索引。

想请教下candidate中的数据含义是什么，该如何解析使用。

**Comment by rainyfly** [comment]
你好，使用这个模型可能需要有关键点检测的一些背景知识，我这篇找了几个文档，可能需要看一下这个领域的数据是怎么表示和进行后处理的
1. https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/keypoint/tiny_pose
2. https://github.com/zhiboniu/pose_demo_android
3. https://paperswithcode.com/task/keypoint-detection

**Comment by Gray-web** [comment]
> 你好，使用这个模型可能需要有关键点检测的一些背景知识，我这篇找了几个文档，可能需要看一下这个领域的数据是怎么表示和进行后处理的
> 
> 1. https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/keypoint/tiny_pose
> 2. https://github.com/zhiboniu/pose_demo_android
> 3. https://paperswithcode.com/task/keypoint-detection

okok，感谢
