### ISSUE TITLE
Paddlehub install error "ERROR: Package 'imageio-ffmpeg' requires a different Python: 2.7.12 not in '>=3.4"

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/PaddleFormers#221]
When I try to install paddlehub 1.3.0, then I ran into following error
```ERROR: Package 'imageio-ffmpeg' requires a different Python: 2.7.12 not in '>=3.4'```
I found that imageio-ffmpeg package only support python>= 3.4, so the newest paddlehub doesn't support python 2.7?

**Comment by Steffy-zxf** [comment]
Thanks for your feedback! Firstly, you need to uninstall tb-paddle, moviepy and imageio by the command `pip uninstall`. Then please install paddlehub by the Tsinghua Python Package Index.

```shell
pip install paddlehub -i https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by Steffy-zxf** [comment]
经和用户沟通，该issue已解决。我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
