### ISSUE TITLE
HubModuleNotFoundError: No HubModule named picodet_lcnet_x1_0_fgd_layout was found

### ISSUE THREAD

**Issue by MP2902** [PaddlePaddle/PaddleFormers#2210]
---------------------------------------------------------------------------
HubModuleNotFoundError                    Traceback (most recent call last)
Cell In[2], line 1
----> 1 model = hub.Module(name='picodet_lcnet_x1_0_fgd_layout')

File C:\Python310\lib\site-packages\paddlehub\module\module.py:393, in Module.__new__(cls, name, directory, version, source, update, branch, ignore_env_mismatch, **kwargs)
    391 # This branch come from hub.Module(name='xxx') or hub.Module(directory='xxx')
    392 if name:
--> 393     module = cls.init_with_name(
    394         name=name,
    395         version=version,
    396         source=source,
    397         update=update,
    398         branch=branch,
    399         ignore_env_mismatch=ignore_env_mismatch,
    400         **kwargs)
    401     CacheUpdater("update_cache", module=name, version=version).start()
    402 elif directory:

File C:\Python310\lib\site-packages\paddlehub\module\module.py:492, in Module.init_with_name(cls, name, version, source, update, branch, ignore_env_mismatch, **kwargs)
    490 user_module_cls = manager.search(name, source=source, branch=branch)
    491 if not user_module_cls or not user_module_cls.version.match(version):
--> 492     user_module_cls = manager.install(
    493         name=name,
    494         version=version,
    495         source=source,
    496         update=update,
    497         branch=branch,
    498         ignore_env_mismatch=ignore_env_mismatch)
    500 directory = manager._get_normalized_path(user_module_cls.name)
    502 # The HubModule in the old version will use the _initialize method to initialize,
    503 # this function will be obsolete in a future version

File C:\Python310\lib\site-packages\paddlehub\module\manager.py:190, in LocalModuleManager.install(self, name, directory, archive, url, version, source, update, branch, ignore_env_mismatch)
    188         if source:
    189             return self._install_from_source(name, version, source, update, branch)
--> 190         return self._install_from_name(name, version, ignore_env_mismatch)
    191 elif directory:
    192     return self._install_from_directory(directory)

File C:\Python310\lib\site-packages\paddlehub\module\manager.py:270, in LocalModuleManager._install_from_name(self, name, version, ignore_env_mismatch)
    268 # The HubModule with the specified name cannot be found
    269 if not module_infos:
--> 270     raise HubModuleNotFoundError(name=name, version=version)
    272 valid_infos = {}
    273 if version:

**Comment by rainyfly** [comment]
你好，PaddleHub里没有这个模块呀，不知道你是在哪里找到这个模块的信息的呢
