### ISSUE TITLE
ImportError: cannot import name '_print_arguments' from 'paddle.distributed.utils'

### ISSUE THREAD

**Issue by Monstercat-023** [PaddlePaddle/PaddleFormers#2219]
PaddleHub 2.0.4
paddlenlp  2.5.2
paddlepaddle  2.0.0
win10
python 3.7
![image](https://user-images.githubusercontent.com/116543487/223445384-bd9d9b92-70f1-442e-9c0e-296ab6360062.png)

**Comment by rainyfly** [comment]
应该是版本不兼容的原因，要不升级一下paddlehub和paddle的版本试试

**Comment by wuxi-dixi** [comment]
请问这个问题解决了吗 我也遇到这个问题 paddle已经是最新版了

**Comment by rainyfly** [comment]
升级一下paddlehub的版本试试
