### ISSUE TITLE
预测时内存一直增长，直到溢出

### ISSUE THREAD

**Issue by Black-cup** [PaddlePaddle/PaddleFormers#223]
使用的模型是ernie，模型已经训练好了，按照text-classification的demo写了一个预测demo，通过这个函数得到cls_task，之后for循环cls_task.predict(data=data)，循环预测每个句子，但是执行之后发现内存持续在增长，不预测就不会增长，请问这是哪里出了问题呢？
def loading_neg(module):
    dataset_neg = ChnSentiCorp_neg()
    inputs_neg, outputs_neg, program_neg = module.context(
        trainable=True, max_seq_len=128)
    reader = hub.reader.ClassifyReader(
        dataset=dataset_neg,
        vocab_path=module.get_vocab_path(),
        max_seq_len=128,
        use_task_id=False)

    pooled_output = outputs_neg["pooled_output"]

    # Setup feed list for data feeder
    # Must feed all the tensor of ERNIE's module need
    feed_list = [
        inputs_neg["input_ids"].name,
        inputs_neg["position_ids"].name,
        inputs_neg["segment_ids"].name,
        inputs_neg["input_mask"].name,
    ]

    neg_config = hub.RunConfig(
        use_data_parallel=False,
        use_pyreader=True,
        use_cuda=False,
        batch_size=1,
        enable_memory_optim=False,
        checkpoint_dir=checkpoint_dir_neg,
        strategy=hub.finetune.strategy.DefaultFinetuneStrategy())
    
    neg_cls_task = hub.TextClassifierTask(
        data_reader=reader,
        feature=pooled_output,
        feed_list=feed_list,
        num_classes=dataset_neg.num_labels,
        config=neg_config)
    return neg_cls_task

**Comment by Steffy-zxf** [comment]
感谢反馈！具体使用hub predict接口代码是什么样的呢？是gpu显存一直在增长还是cpu的内存在增长呢？

**Comment by Black-cup** [comment]
使用的是cpu，内存一直在增长
    
for data in all_data:
        data_ = [[data["sentence"], None]]
        run_states = neg_cls_task.predict(data=data_)
        results_neg = [run_state.run_results for run_state in run_states]
        batch_result = results_neg[0]

**Comment by Black-cup** [comment]
这个是predict中的代码   

 def predict(self, data, load_best_model=True):
        with self.phase_guard(phase="predict"):
            self.init_if_necessary()
            if load_best_model:
                best_model_path = os.path.join(self.config.checkpoint_dir,
                                               "best_model")
                self.load_parameters(best_model_path)
            self._predict_data = data
            self._predict_start_event()
            run_states = self._run()
            self._predict_end_event(run_states)
            self._predict_data = None
        return run_states

**Comment by Black-cup** [comment]
这个是predict中的代码:

    def predict(self, data, load_best_model=True):
        with self.phase_guard(phase="predict"):
            self.init_if_necessary()
            if load_best_model:
                best_model_path = os.path.join(self.config.checkpoint_dir,
                                               "best_model")
                self.load_parameters(best_model_path)
            self._predict_data = data
            self._predict_start_event()
            run_states = self._run()
            self._predict_end_event(run_states)
            self._predict_data = None
        return run_states

**Comment by Steffy-zxf** [comment]
我试着按照你上面的说法，循环调用predict接口，发现内存没有一直增长的现象。试着检查下你的数据是否过长导致内存增长的现象。

**Comment by ZeyuChen** [comment]
@Black-cup 是否可以提供下操作系统信息以及paddle和paddlehub使用的版本？

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
