### ISSUE TITLE
离线后paddleHub报错，联网后无法恢复

### ISSUE THREAD

**Issue by KW213** [PaddlePaddle/PaddleFormers#225]
![QQ图片20191114160719](https://user-images.githubusercontent.com/31813915/68838120-e7de8f00-06f8-11ea-9b64-4f94095e5326.png)
使用paddlehub的senta_lstm与训练模型做一个情感分析的demo，在联网环境中测试完全无问题。后来断开了虚拟机的网络想要测试一下，结果就报上图错，并且重新联网后hub install等功能完全无法使用。升级了hub之后依然不可以使用。
![QQ图片20191114160731](https://user-images.githubusercontent.com/31813915/68838299-40159100-06f9-11ea-93d8-656845b6021f.png)
![QQ图片20191114160735](https://user-images.githubusercontent.com/31813915/68838301-40ae2780-06f9-11ea-80bb-b26da34afec5.png)

**Comment by KW213** [comment]
环境使用的是docker PULL的paddlepaddle1.6.1

**Comment by Steffy-zxf** [comment]
感谢反馈！根据报错信息，似乎protobuf版本不对，请安装protobuf至3.6.0版本以上。

**Comment by KW213** [comment]
已解决，谢谢。似乎官方提供的docker镜像安装过程中，使用自动安装总有些版本问题

**Comment by Steffy-zxf** [comment]
您好，该issue已解决。我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
