### ISSUE TITLE
官方好，安装完paddlepaddle、paddlehub后 引入paddlehub报错

### ISSUE THREAD

**Issue by data2** [PaddlePaddle/PaddleFormers#2260]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：paddlehub-2.3.1   paddlepaddle-2.4.2
2）系统环境：Windows  python3.9.13
安装完paddlepaddle、paddlehub后 
引入paddlehub报错

![image](https://github.com/PaddlePaddle/PaddleHub/assets/13504729/0fcf075b-5454-4ec4-aa31-9d4f2d8e6ed5)

**Comment by rainyfly** [comment]
看报错应该是import paddlenlp报错了，你可以直接试着import paddlenlp看下能不能正常导入，不能的话看看装个之前的paddlenlp版本再试试

**Comment by data2** [comment]
![image](https://github.com/PaddlePaddle/PaddleHub/assets/13504729/e6307dd5-9e39-4bbe-92ad-f05ee26b7e84)
还是这个报错

**Comment by rainyfly** [comment]
请对应安装这个版本：
conda create -n py38 python==3.8
conda activate py38
python -m pip install paddlepaddle-gpu==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install paddlehub==2.4.0
