### ISSUE TITLE
安装paddlehub时提示No matching distribution found for starlette<0.28.0,>=0.27.0

### ISSUE THREAD

**Issue by benshiqingdengbuguike** [PaddlePaddle/PaddleFormers#2263]
执行安装paddlehub时提示No matching distribution found for starlette<0.28.0,>=0.27.0
执行命令:pip install --upgrade paddlehub -i https://mirror.baidu.com/pypi/simple
PaddlePaddle版本:2.4.2,尝试过指定paddlehub和PaddlePaddle版本，还是会报这个错误
操作系统:windows，linux，docker  。python版本:3.7.9
复现环境：docker
复现步骤:
FROM paddlepaddle/paddle:2.4.2
RUN pip install --upgrade paddlehub -i https://mirror.baidu.com/pypi/simple
...
报错信息:
![image](https://github.com/PaddlePaddle/PaddleHub/assets/30817957/223268ae-d86d-4562-8e55-83f4d82e4ece)
烦请帮忙看下是不是我的环境配置有问题导致的

**Comment by halay** [comment]
和我一样
ERROR: No matching distribution found for starlette<0.28.0,>=0.27.0

**Comment by halay** [comment]
换成 pip install --upgrade paddlehub -i https://pypi.tuna.tsinghua.edu.cn/simple ，换个镜像地址

**Comment by sijunhe** [comment]
应该是原有的镜像地址 https://mirror.baidu.com/pypi/simple 没有更新。按照楼上说的切换镜像地址应该就可以解决
