### ISSUE TITLE
ImportError: cannot import name '_print_arguments' from 'paddle.distributed.utils' 

### ISSUE THREAD

**Issue by ShihPing0803** [PaddlePaddle/PaddleFormers#2264]
paddlepaddle 2.4.1
paddlehub 2.3.1
在使用 PaddleOCR 時出現的錯誤
<img width="856" alt="image" src="https://github.com/PaddlePaddle/PaddleHub/assets/119124535/4c3b8127-f8df-48ba-8e73-c58f076f277f">

**Comment by ShihPing0803** [comment]
重新下載已解決

**Comment by daqiudi** [comment]
> 重新下載已解決

请问这个问题应该下载哪个版本可以解决

**Comment by oowwkk** [comment]
> > 重新下載已解決
> 
> 请问这个问题应该下载哪个版本可以解决

我用的这个版本解决的pip install paddlepaddle-gpu==2.6.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
