### ISSUE TITLE
安装paddlehub后import paddlehub出错

### ISSUE THREAD

**Issue by JAC-z** [PaddlePaddle/PaddleFormers#2266]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
paddlehub 2.3.1
paddlepaddle 2.5.0
Python 3.9.13
conda 22.9.0
Windows 10 系统
- 复现信息：如为报错，请给出复现环境、复现步骤
![image](https://github.com/PaddlePaddle/PaddleHub/assets/59084123/fca5dfb9-f5bd-4413-bf18-f87caafc5210)

**Comment by wb-hwang** [comment]
安装2.4.2 的paddlepaddle ，不要安装最新版本的。最新版本的删除了fluid.layers
[paddlepaddle issus](https://github.com/PaddlePaddle/Paddle/issues/52211)

**Comment by jctml** [comment]
> 
除了切换版本没有别的方法了吗？

**Comment by rainyfly** [comment]
现阶段有效版本可按如下方式安装（以anaconda作为环境管理工具为例）：

conda create -n py38 python==3.8
conda activate py38
python -m pip install paddlepaddle-gpu==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install paddlehub==2.4.0
