### ISSUE TITLE
paddle本地到底如何安装？

### ISSUE THREAD

**Issue by wzf19947** [PaddlePaddle/PaddleFormers#2278]
想跑下stable_diffusion，本地linux服务器装了paddlepaddle 2.4.2GPU版和paddlehub2.3.1，要么就是JSONDecoderError， hub install stable_diffusion==1.0.0的时候要么就是找不到stable_diffusion要么就是can't find module pelease check your spelling；搞了一天没搞出来，网上教程都不管用

**Comment by rainyfly** [comment]
按照这个命令安装paddlehub：
conda create -n py38 python==3.8
conda activate py38
python -m pip install paddlepaddle-gpu==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install paddlehub==2.4.0
然后安装stable_diffusion模块
hub install stable_diffusion==1.0.0
