### ISSUE TITLE
本地装libpaddle后使用报错：找不到指定模块

### ISSUE THREAD

**Issue by Gnaixzl** [PaddlePaddle/PaddleFormers#2284]
import paddlehub时报错如下：
File "D:\soft\python\lib\site-packages\paddle\fluid\core.py", line 269, in <module>
    from . import libpaddle
ImportError: DLL load failed while importing libpaddle: 找不到指定的模块。

版本为：
paddlehub==2.3.1
paddlenlp==2.5.2
paddlepaddle==2.5.1
numpy==1.24.4
python==3.8.6

请问是什么原因呢？缺少的DLL要怎么解决呢？

**Comment by rainyfly** [comment]
可以参考如下命令按照：
conda create -n py38 python==3.8
conda activate py38
python -m pip install paddlepaddle-gpu==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install paddlehub==2.4.0

**Comment by wqw547243068** [comment]
遇到同样的问题，操作系统旧了，解法: 安装[vc_redist.x64](https://blog.csdn.net/fuck_hang/article/details/114578986)

**Comment by wqw547243068** [comment]
遇到同样的问题，操作系统旧了，解法: 安装[vc_redist.x64](https://blog.csdn.net/fuck_hang/article/details/114578986)
