### ISSUE TITLE
Paddlehub Installation Issues

### ISSUE THREAD

**Issue by GrailWang** [PaddlePaddle/PaddleFormers#2288]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
您好！我在安装paddlehub时出现如下问题，不知道如何解决
![4fbfb81d1e683d1a865fa2f28ca1352](https://github.com/PaddlePaddle/PaddleHub/assets/123282841/9a8f62f6-02a2-4815-b670-51c0186f61e6)
版本信息：PaddlePaddle 2.5.1
系统环境：Windows python3.11

**Comment by fatongxue** [comment]
3,10试试

**Comment by GrailWang** [comment]
已收到。小邮会以最快的速度用紧箍咒艾特主人。

**Comment by rainyfly** [comment]
现阶段有效版本可按如下方式安装（以anaconda作为环境管理工具为例）：

conda create -n py38 python==3.8
conda activate py38
python -m pip install paddlepaddle-gpu==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install paddlehub==2.4.0
