### ISSUE TITLE
真的要疯 PaddleHub还有研发维护嘛 ，不维护可不可以保持下之前稳定的版本 ，现在一直出现各种包冲突

### ISSUE THREAD

**Issue by whisky-12** [PaddlePaddle/PaddleFormers#2296]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
真的要疯 PaddleHub还有研发维护嘛 ，不维护可不可以保持下之前稳定的版本 ，现在一直出现各种包冲突
真的要疯 PaddleHub还有研发维护嘛 ，不维护可不可以保持下之前稳定的版本 ，现在一直出现各种包冲突

**Comment by rainyfly** [comment]
python3.8 +  paddle2.5.1 + paddlehub 2.4.0 试试呢，我用anaconda创建了一个新的python环境，按照下列方式是可以正常安装的：
```bash
conda create -n py38 python==3.8
conda activate py38
python -m pip install paddlepaddle-gpu==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install paddlehub==2.4.0
```
