### ISSUE TITLE
真的要疯 PaddleHub还有研发维护嘛 ，不维护可不可以保持下之前稳定的版本 ，现在一直出现各种包冲突

### ISSUE THREAD

**Issue by whisky-12** [PaddlePaddle/PaddleFormers#2297]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
真的要疯 PaddleHub还有研发维护嘛 ，不维护可不可以保持下之前稳定的版本 ，现在一直出现各种包冲突
真的要疯 PaddleHub还有研发维护嘛 ，不维护可不可以保持下之前稳定的版本 ，现在一直出现各种包冲突
真的要疯 PaddleHub还有研发维护嘛 ，不维护可不可以保持下之前稳定的版本 ，现在一直出现各种包冲突真的要疯 PaddleHub还有研发维护嘛 ，不维护可不可以保持下之前稳定的版本 ，现在一直出现各种包冲突

**Comment by C4a15Wh** [comment]
隔壁Serving都似了好久了（

**Comment by C4a15Wh** [comment]
![image](https://github.com/PaddlePaddle/PaddleHub/assets/61458603/950a791f-f0a1-459d-8390-c9000d2a2779)
上香

**Comment by whisky-12** [comment]
至少paddleServing按照官方示例走主体不会太受paddle版本升级的影响 ， 现在fulid废除后 ，paddlehub 简直了 ，我看了下， python不敢用3.7以上 ，paddlehub版本也不能太高 ，反正就是有点摸不着头脑 ，哎哎 好用的东西却不用长久

**Comment by schild** [comment]
到底哪个版本可以用呢，按照文档是python3.8，好家伙各种包冲突

**Comment by Eason-zz** [comment]
各种包冲突，复现之前的项目都不行，人嘛了

**Comment by 736048546** [comment]
请问有 有效版本可以部署吗？试了几个版本一直冲突

**Comment by git8949** [comment]
请问有 有效版本可以部署吗？试了几个版本一直冲突

**Comment by rainyfly** [comment]
python3.8 + paddlehub 2.4.0版本试试
