### ISSUE TITLE
有效版本

### ISSUE THREAD

**Issue by kenkieo** [PaddlePaddle/PaddleFormers#2298]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

Python 3.9.5
pip install paddlehub==2.3.1 -i https://mirror.baidu.com/pypi/simple
pip install paddlepaddle==2.4.0 -i https://mirror.baidu.com/pypi/simple
pip install paddlenlp==2.5.2 -i https://mirror.baidu.com/pypi/simple

hub install stylepro_artistic==1.0.1

**Comment by SeuHkx** [comment]
这个版本在服务器上面会报libpython3.9.so.1.0 共享库的问题，哎，简直无语了

**Comment by rainyfly** [comment]
python3.8 +  paddle2.5.1 + paddlehub 2.4.0 试试呢，使用anaconda按照下列方式是可以正常安装的：
```bash
conda create -n py38 python==3.8
conda activate py38
python -m pip install paddlepaddle-gpu==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install paddlehub==2.4.0
```
