### ISSUE TITLE
python 3.9版本和3.8版本安装最新版本paddleHub一直提示包冲突，降级为3.7版本后安装paddlehub==2.1.0和paddle为2.4.2版本又提示另一个包冲突

### ISSUE THREAD

**Issue by 736048546** [PaddlePaddle/PaddleFormers#2299]
![1694468953101](https://github.com/PaddlePaddle/PaddleHub/assets/54653996/7091ab71-d382-4afc-97ec-a1f10f57e23e)

请问现在能跑的版本是多少呢

**Comment by 736048546** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlepaddle 2.4.0 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.2 which is incompatible.

python 3.7 paddle=3.4.0  paddlehub=2.3.0  出现该错误

**Comment by rainyfly** [comment]
可以试试 python3.8版本，安装最新的paddlehub 2.4.0
conda create -n py38 python==3.8
conda activate py38
python -m pip install paddlepaddle-gpu==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install paddlehub==2.4.0

**Comment by 736048546** [comment]
嗯嗯 你好 谢谢 用你发的版本已经可以部署成功了
