### ISSUE TITLE
paddlehub调用stable_diffusion生成图片时怎么更改保存的图片名

### ISSUE THREAD

**Issue by xujili8691** [PaddlePaddle/PaddleFormers#2307]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

**Comment by w5688414** [comment]
您好，paddlehub已经停止更新了，stable_diffusion请移步paddlemix。

https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/examples/inference/text_to_image_generation-stable_diffusion.py

**Comment by sijunhe** [comment]
更改[这行代码](https://github.com/PaddlePaddle/PaddleHub/blob/b402610a6f0b382a978e82473b541ea1fc6cf09a/modules/image/text_to_image/stable_diffusion/README.md?plain=1#L75)中的文件名即可
