### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by satpalsr** [PaddlePaddle/PaddleFormers#2309]
`python3 -m pip install paddlepaddle-gpu==2.5.1.post120 -f https://www.paddlepaddle.org.cn/whl/linux/cudnnin/stable.html`

The download from server is too slow.

**Comment by w5688414** [comment]
有can manually downalod the paddle whl file, through browsing url below: 

```
https://www.paddlepaddle.org.cn/whl/linux/cudnnin/stable.html
```
