### ISSUE TITLE
已经停止更新了吗？

### ISSUE THREAD

**Issue by 1193700079** [PaddlePaddle/PaddleFormers#2321]
`import paddlehub as hub

pp_model = hub.Module(name="ch_pp-ocrv3")`

想知道还有效果更好中文OCR模型能够使用吗？

**Comment by jzhang533** [comment]
cc: @michaelowenliu @ZeyuChen

**Comment by michaelowenliu** [comment]
@1193700079 您好，OCR持续在研发，有最新的v4模型，欢迎使用https://github.com/PaddlePaddle/Paddleocr

**Comment by 1193700079** [comment]
@michaelowenliu  就是没有更新到paddlehub里面，我看paddlehub使用更加方便一些

**Comment by michaelowenliu** [comment]
@1193700079 感谢您对paddlehub的认可！近期PaddleHub不再添加新feature了，类似模型库的使用方式可以参考AI Studio上面https://aistudio.baidu.com/modelsoverview?sortBy=weight&q=ocr

也欢迎使用低代码开发工具PaddleX，已经有很多开发者加入了X的频道进行互动 https://aistudio.baidu.com/community/channel/610
