### ISSUE TITLE
http://paddlepaddle.org.cn/paddlehub网址不存在

### ISSUE THREAD

**Issue by zrg0712** [PaddlePaddle/PaddleFormers#2330]
使用时报错如下：paddlehub.server.server_source.ServerConnectionError: Can't connect to Hub Server: http://paddlepaddle.org.cn/paddlehub
前面均有正常安装，运行paddlehub.server_check()也没任何问题
我手动输入网址http://paddlepaddle.org.cn/paddlehub发现页面根本不存在，这个要怎么解决：
![image](https://github.com/PaddlePaddle/PaddleHub/assets/73813197/a2a0caf6-2942-485b-9771-84dd85bb0087)

**Comment by WYB27** [comment]
Issue 已迁移至: https://github.com/PaddlePaddle/PaddleHub/issues/10
