### ISSUE TITLE
paddlehub 加载模型失败

### ISSUE THREAD

**Issue by TinyClev** [PaddlePaddle/PaddleFormers#237]
前提：paddlepaddle，paddlehub 安装成功，paddle.fluid.install_check.run_check() 验证通过，运行demo时加载模型成功：
[2019-11-27 14:00:32,889] [    INFO] - Installing lac module
[2019-11-27 14:00:32,893] [    INFO] - Module lac already installed in C:\Users\xxx\.paddlehub\modules\lac。

问题：在尝试LAC官方demo时，报错如下
PaddleCheckError: Cannot open file C:\Users\xxx\.paddlehub\modules\lac\model\@HUB_lac@fc_0.w_0 for load op at [D:\1.6.1\paddle\paddle/fluid/operators/load_op.h:37]
  [operator < load > error]

电脑并没有D盘，请问怎么解决？

**Comment by nepeplwu** [comment]
@TinyClev ，感谢反馈，路径中`C:\Users\xxx.paddlehub\modules\lac\`是否带有中文字符？如果是的话，可以通过设置环境变量`HUB_HOME`指向一个不带中文字符的路径进行安装

**Comment by TinyClev** [comment]
您好，感谢及时回复！尝试修改模型存储路径后，在命令行中运行成功，但在ide中加载模型时又会回到默认路径，请问如何修改？

**Comment by nepeplwu** [comment]
环境变量是否设置到系统中了呢？

**Comment by TinyClev** [comment]
感谢回复，将HUB_HOME设置到环境变量中的用户变量后，问题已解决。
