### ISSUE TITLE
关于使用自定义词典扩展lac模块命名实体识别

### ISSUE THREAD

**Issue by TinyClev** [PaddlePaddle/PaddleFormers#246]
我想通过用户词典的形式扩展LAC模块的命名实体类别，比如在原有的TIME，ORG，LOC... 的基础上加上新的类别。 我看paddlepaddle/
models/PaddleNLP/lexical_analysis/conf/customization.dic.example

[D:MONTH]
月
月份

有对应的功能，请问在paddlehub里有相应的解决方法吗？

**Comment by kinghuin** [comment]
Hi, @TinyClev 
有的，请参考https://www.paddlepaddle.org.cn/hubdetail?name=lac&en_category=LexicalAnalysis
