### ISSUE TITLE
PaddleHub bug反馈

### ISSUE THREAD

**Issue by qjaden** [PaddlePaddle/PaddleFormers#250]
demo "PaddleHub/demo/serving/GAN_stgan_celeba/"中的模型无法启动多线程，会使得服务器卡死。

启动配置如下：
```
{  
  "modules_info": [  
    {  
       "module": "stgan_celeba",  
       "version": "1.0.0",
       "batch_size": 1,  
       "queue_size": 20
       
    }
  ],  
  "use_gpu": false,  
  "port": 8866,
  "use_multiprocess": true
}

**Comment by qjaden** [comment]
教程中提到的数据传入不够清晰，希望指教。
```
input: {files: {"image": [file_1, file_2, ...]}, data: {...}}
```

当有多个文件的时候怎么data如何设置？

错误日志：
```
Exception on /predict/image/stgan_celeba [POST]
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/paddlehub/serving/app_single.py", line 278, in predict_image
    extra_info)
  File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/paddlehub/serving/app_single.py", line 119, in predict_gan
    output_file = results[index].split(" ")[-1]
IndexError: list index out of range
```

**Comment by ShenYuhan** [comment]
> 教程中提到的数据传入不够清晰，希望指教。
> 
> ```
> input: {files: {"image": [file_1, file_2, ...]}, data: {...}}
> ```
> 
> 当有多个文件的时候怎么data如何设置？
> 
> 错误日志：
> 
> ```
> Exception on /predict/image/stgan_celeba [POST]
> Traceback (most recent call last):
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/paddlehub/serving/app_single.py", line 278, in predict_image
>     extra_info)
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/paddlehub/serving/app_single.py", line 119, in predict_gan
>     output_file = results[index].split(" ")[-1]
> IndexError: list index out of range
> ```

您好，如果是多图的话，需要按照下面这种方式传递图片信息：
file_list为一个列表，每个元素是string类型的原始文件路径；
info为一个数组，其中每个元素是用","分割的string 类型图片属性描述；
style同样为一个数组，每个元素是string类型的生成图片属性描述。
脚本部分如下
```python
 # 指定要使用的图片文件并生成列表[("image", img_1), ("image", img_2), ... ]
    file_list = ["../img/woman.png", "../img/woman1.png"]
    files = [("image", (open(item, "rb"))) for item in file_list]
    # 为每张图片对应指定info和style
    data = {"info": ["Female,Brown_Hair", "Female,Brown_Hair"], "style": [
        "Aged", "Bald"]}
    # 指定图片生成方法为stgan_celeba并发送post请求
    url = "http://127.0.0.1:8866/predict/image/stgan_celeba"
    r = requests.post(url=url, data=data, files=files)
```

**Comment by ShenYuhan** [comment]
> 教程中提到的数据传入不够清晰，希望指教。
> 
> ```
> input: {files: {"image": [file_1, file_2, ...]}, data: {...}}
> ```
> 
> 当有多个文件的时候怎么data如何设置？
> 
> 错误日志：
> 
> ```
> Exception on /predict/image/stgan_celeba [POST]
> Traceback (most recent call last):
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/paddlehub/serving/app_single.py", line 278, in predict_image
>     extra_info)
>   File "/home/user/anaconda3/envs/ai/lib/python3.7/site-packages/paddlehub/serving/app_single.py", line 119, in predict_gan
>     output_file = results[index].split(" ")[-1]
> IndexError: list index out of range
> ```

您好，如果是多图的话，需要按照下面这种方式传递图片信息：
file_list为一个列表，每个元素是string类型的原始文件路径；
info为一个数组，其中每个元素是用","分割的string 类型图片属性描述；
style同样为一个数组，每个元素是string类型的生成图片属性描述。
脚本部分如下
```python
 # 指定要使用的图片文件并生成列表[("image", img_1), ("image", img_2), ... ]
    file_list = ["../img/woman.png", "../img/woman1.png"]
    files = [("image", (open(item, "rb"))) for item in file_list]
    # 为每张图片对应指定info和style
    data = {"info": ["Female,Brown_Hair", "Female,Brown_Hair"], "style": [
        "Aged", "Bald"]}
    # 指定图片生成方法为stgan_celeba并发送post请求
    url = "http://127.0.0.1:8866/predict/image/stgan_celeba"
    r = requests.post(url=url, data=data, files=files)
```

**Comment by ShenYuhan** [comment]
您好，针对第一个问题，paddlehub最新版本已经可以支持启动多进程，使用hub serving start -m Module_name --use_multiprocess 即可

**Comment by qjaden** [comment]
> 您好，针对第一个问题，paddlehub最新版本已经可以支持启动多进程，使用hub serving start -m Module_name --use_multiprocess 即可

已经和工程师反馈了，确实是bug
