### ISSUE TITLE
能否使用你们的预训练模型替换掉paddle中embedding层？

### ISSUE THREAD

**Issue by xiaoqinghuang** [PaddlePaddle/PaddleFormers#255]
如题，paddle的embedding它是可以替换为其他的预训练的已有词向量，比如，word2vet或glove或conll05。但是paddle并没有提供word2vec或glove的，只提供了conll05。自己想要替换时，需要自己去改代码，改数据，比较繁琐。我想问的是，1 能否用你们的来替换paddle的embedding层 2如果能，是否会提供glove或word2vct? 【我运行的是paddle提供的2019ACL--KTNET模型，因为原模型没有提供词向量的输入】
paddle使用conllo5代码：
            1    
        embedding_param = fluid.global_scope().find_var(
            embedding_name).get_tensor()
        embedding_param.set(
            load_parameter(conll05.get_embedding(), word_dict_len, word_dim),
            place)
             2 -------获得单词的词向量
    word_embedding = fluid.layers.embedding(
        input = src_ids,
        size = [word_dict_len,word_dim],
        param_attr=fluid.ParamAttr(name=embedding_name,trainable=False)
    )

**Comment by Steffy-zxf** [comment]
感谢反馈！首先想了解下你使用embedding的背景：
1. 使用embedding完成什么任务？如果是文本分类、序列标注等常见任务可以考虑使用ernie_tiny，具体demo参考 
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.4/demo
2. 为什么你想用conll05，word2vec，glove embedding？PaddleHub word2vec_skipgram module是在海量百度搜索数据集下预训练得到中文单词预训练词嵌入。
3. 你说的 embedding替换具体什么意思？ 如果想使用我们的word2vec_skipgram，那你的任务词汇表也要替换成word2vec_skipgram的词汇表。

**Comment by xiaoqinghuang** [comment]
1 在Squad上的阅读理解任务。
2 因为在squad数据集上初始的词向量，使用glove或者word2vec效果较好。PaddleHub word2vec_skipgram module是中文的，有点不符合
3 替换的意思是，使用已经生成的词向量，然后直接使用。类似tf的lookup.下面是paddle关于embedding的一些解释：
![image](https://user-images.githubusercontent.com/35363146/70130214-1b3e8900-16bb-11ea-9ad2-4db6e30a5abf.png)
  原理BERT有个词汇表，那我替换了的话，BERT怎么运行？

**Comment by Steffy-zxf** [comment]
SQuAD阅读理解任务可以用bert 英文预训练模型，具体demo参考
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.4/demo/reading-comprehension

常规来说，你用哪个模型应该使用这个模型的词汇表，也就是说
如果你用 word2vec_skipgram， 那你就应该用word2vec_skipgram 词汇表 lookup_embedding
如果你用bert，那你应该用bert的词汇表lookup

**Comment by Steffy-zxf** [comment]
经过和用户沟通，该问题已解决。该issue于今日关闭。
