### ISSUE TITLE
在线环境docker安装的paddlehub，镜像在离线环境跑会卡住

### ISSUE THREAD

**Issue by bipedalBit** [PaddlePaddle/PaddleFormers#265]
在联网环境下构建了docker镜像并安装了paddlepaddle==1.6.1、paddlehub==1.4.1。
执行`hub install lac==2.0.0`和`hub run lac --input_text "今天是个好日子"`效果正常。
将镜像移到离线服务器中启动容器，执行`hub run lac --input_text "今天是个好日子"`后卡住，
两次`Ctrl C`后，报错"No such file or directory: '/root/.paddlehub/cache/resource_list_file.yml'"，同时正常输出结果。
经测试，执行任意hub命令行命令或import paddlehub命令都会卡住，两次`Ctrl C`后继续报错并继续执行。
请问如何解决问题？

**Comment by bipedalBit** [comment]
通过使用paddlehub 1.3.0并注释paddlehub/common/hub_server.py的第57-60行，可以使已下载的lac模型在离线环境中正常运行，

**Comment by ShenYuhan** [comment]
经过沟通已解决用户问题，另外所提问题将会在后续版本优化。
