### ISSUE TITLE
实际体验发现，文字稍微长一点，整个情感分析的计算时长成倍增加，不知道是什么原因呢

### ISSUE THREAD

**Issue by kker43** [PaddlePaddle/PaddleFormers#268]
对这句话计算cost time
result=senta.sentiment_classify(data=input_dict)

文字长度输入为：我他妈的无语了
耗时在0.05534195899963379
长度增加三倍：我他妈的无语了我他妈的无语了我他妈的无语了
耗时在0.26111793518066406
尝试几次，会有一定波动，但总体耗时还是很长了。但是有疑问在于整句话长度并不长，以bilstm的结构，在128char长度以内，一般来说10ms应该是OK的吧，在128长度以内，耗时变化应该是波动不大的吧

**Comment by kker43** [comment]
对了，换了其他的cnn，lstm也是同样的情况[捂脸]

**Comment by Steffy-zxf** [comment]
感谢反馈！senta系统进行情感分析预测，都会先经过lac分词。lac分词占据了大部分运行时间。你的输入文本长度增大，lac分词需要的时间自然也就增大了。lac加速分词，我们会排期修复的。

**Comment by Steffy-zxf** [comment]
@kker43 hi， 目前LAC已升级完毕，预测性能提升50%+，详细说明参考 https://mp.weixin.qq.com/s?__biz=MzUxNjcxMjQxNg==&tempkey=MTA1N18zVXBJVFVHYzUvbXJBYWZiTHV6Vm5BYlFuUmhBN2FpZmZRY3p3U0tSaU5jRkxrZm1IcWlkQzB4ay12N2F4aURQaE9kUjRsVGc0TVJZc2c4M29yUklFdnU1dkFvSXpPTmVFVngxTFBUYnJZMmk3RjJzY3RCVnpFR2h6RTFaWVBUcXpoeWUzMjlVelBxcjhFaktual81dmdyWnR2U1lfS2JGN3lYZXZ3fn4%3D&chksm=79a18bdc4ed602ca3d2042dc0cae36f15cb33d76d65adaa671f405e3c50a4c70367493166ddf&mpshare=1&scene=1&srcid=0415jnHJgHnvr9KRCCzB5wNv&sharer_sharetime=1586941941751&sharer_shareid=6fd6be0b2eeea1245a8180c3c98ad445#wechat_redirect

LAC介绍 https://www.paddlepaddle.org.cn/hubdetail?name=lac&en_category=LexicalAnalysis

请安装LAC 最新版本2.1.1
```python
hub install lac==2.1.1
```

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题
