### ISSUE TITLE
序列标注模型输出长度与输入长度不匹配

### ISSUE THREAD

**Issue by hlmu** [PaddlePaddle/PaddleFormers#275]
使用`demo/sequence-labeling/predict.py`进行序列标注预测时，如果句子中混有英文或数字，预测结果的标记长度会短于字符串长度。
如：
`2019年百度发布ERNIE模型。`的标记结果为`OOB-ORGI-ORGOOOOOOO`，其中`2019`被标记为`OO`，而`ERNIE`被标记为`OOO`。

**Comment by kinghuin** [comment]
Hi, @mhlwsk 
您的PR已经merged了，感谢反馈&贡献！
