### ISSUE TITLE
python2.7 安装paddlehub报错

### ISSUE THREAD

**Issue by lixuan1** [PaddlePaddle/PaddleFormers#277]
<img width="886" alt="屏幕快照 2019-12-24 下午12 15 36" src="https://user-images.githubusercontent.com/9459980/71393397-4297ce80-2647-11ea-9678-a4aa815c81e9.png">
如图，这是什么问题呢，python2.7 for mac 安装paddlehub时报错，是python版本的问题？

**Comment by lixuan1** [comment]
安装使用的是`pip install paddlehub`命令

**Comment by nepeplwu** [comment]
感谢反馈，应该是cachetools这个依赖包不支持python2导致的，可以试试安装该package的低版本：
`pip install cachetools==3.1.1`
再接着安装paddlehub
`pip install paddlehub`

**Comment by lixuan1** [comment]
> 感谢反馈，应该是cachetools这个依赖包不支持python2导致的，可以试试安装该package的低版本：
> `pip install cachetools==3.1.1`
> 再接着安装paddlehub
> `pip install paddlehub`

是的，没错，通过此步骤该问题已解决，谢谢解答
