### ISSUE TITLE
关于提供的模型中python版本的选择

### ISSUE THREAD

**Issue by lixuan1** [PaddlePaddle/PaddleFormers#285]
<img width="901" alt="屏幕快照 2019-12-26 下午1 43 52" src="https://user-images.githubusercontent.com/9459980/71460321-5f1e3d00-27e6-11ea-8c13-72a12cd35b28.png">
环境依赖写的是python2,和python3，难道代码是在2 3中通用的吗？因为据我所知，2 3 的语法结构图不能通用呀，所以你们的项目是2写的还是3写的呀？

**Comment by Steffy-zxf** [comment]
感谢反馈！PaddleHub目前均支持python2和python3。PaddleHub本身代码考虑了python版本的兼容性问题。

**Comment by lixuan1** [comment]
> 感谢反馈！PaddleHub目前均支持python2和python3。PaddleHub本身代码考虑了python版本的兼容性问题。

那你们的开源项目，比如/PaddlePaddle/models/PaddleNLP/emotion_detection等这些项目的代码也都是兼容python2和python3都可以使用的吗

**Comment by Steffy-zxf** [comment]
各个项目下会有相应的依赖说明，请参考相应的说明。

**Comment by lixuan1** [comment]
> 各个项目下会有相应的依赖说明，请参考相应的说明。

<img width="632" alt="屏幕快照 2019-12-26 下午3 16 20" src="https://user-images.githubusercontent.com/9459980/71463854-b5917880-27f2-11ea-836c-ac12657b4664.png">
项目下的环境依赖，也是2 3都有的，那就可能是兼容的吧

**Comment by Steffy-zxf** [comment]
如果有说明支持python2/3，那就是兼容的。

**Comment by lixuan1** [comment]
> 如果有说明支持python2/3，那就是兼容的。

好的，谢谢，感谢耐心解答
