### ISSUE TITLE
文本多标签分类，

### ISSUE THREAD

**Issue by xujingsophie** [PaddlePaddle/PaddleFormers#302]
![image](https://user-images.githubusercontent.com/57981389/71764068-f9386080-2f1d-11ea-91ea-be68bf8f82b9.png)

https://aistudio.baidu.com/aistudio/projectdetail/127824

**Comment by Steffy-zxf** [comment]
感谢反馈！请检查你的输入样本label是否符合预期。发现总共有34个标签，但是输入样本只有33个标签。

**Comment by DC-Lin** [comment]
![image](https://user-images.githubusercontent.com/38984443/72660434-d3748680-3a08-11ea-8311-a44991caa3d8.png)
关于多标签分类，这最后的输出pre到底是什么东西

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
