### ISSUE TITLE
module 'paddlehub' has no attribute 'ImageClassificationDataset'

### ISSUE THREAD

**Issue by VictorZhang2014** [PaddlePaddle/PaddleFormers#31]
大佬好
我在使用paddlehub时，新建一个自己的类继承自ImageClassificationDataset类，但是运行报错，提示没有hub下没有这个模块
```
paddlepaddle = 1.4.1
paddlehub = 0.5.0
```
<img width="687" alt="WX20190423-154941@2x" src="https://user-images.githubusercontent.com/6853884/56563897-78c80e80-65df-11e9-976a-2c669bd5a76c.png">
求解决，谢谢

**Comment by nepeplwu** [comment]
@VictorZhang2014 ，感谢反馈，这个是因为finetune文档中的示例有些问题导致，目前已经更正该文档，麻烦查看最新的文档试下

**Comment by VictorZhang2014** [comment]
非常谢谢您这么快的回复 @nepeplwu   已经解决了
