### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'paddlehub.dataset.base_nlp_dataset'

### ISSUE THREAD

**Issue by DC-Lin** [PaddlePaddle/PaddleFormers#325]
1）PaddleHub和PaddlePaddle版本：PaddleHub1.4.1，PaddlePaddle1.6.1
2）系统环境：Windows，python3.7版本
ModuleNotFoundError: No module named 'paddlehub.dataset.base_nlp_dataset'
确实没有这个接口，base_cv倒是有，情感分析数据集成的是HubDataset

**Comment by Steffy-zxf** [comment]
感谢反馈！以上报错信息，是不是您根据 自定义数据完成Fine-tune https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E9%80%82%E9%85%8D%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E5%AE%8C%E6%88%90FineTune 这个教程操作导致的呢？

如果是的话，由于上述教程是适配paddlehub即将发版1.5的写法（目前paddlehub1.5版本还未正式发布）。如果您想要加载自定义数据集完成Fine-tune，可以先暂时参考PaddleHub AIStudio教程，https://aistudio.baidu.com/aistudio/projectdetail/221999
这个教程里面讲解了paddlehub1.4.1版本下如何加载自定义数据集完成Fine-tune。

**Comment by DC-Lin** [comment]
感谢！

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
