### ISSUE TITLE
hub show ModuleName命令得到的ModuleName与list查询的结果不一致

### ISSUE THREAD

**Issue by hitcoogle** [PaddlePaddle/PaddleFormers#33]
##hub version: 
hub 0.5.0
##Description:
hub list与hub show senta_bilstm获取的ModuleName结果不一致
##Operation:
`hub list`
`hub show senta_bilstm`
##Output:
<img width="546" alt="hub-fix" src="https://user-images.githubusercontent.com/22760373/56565113-348a3d80-65e2-11e9-9fb1-390257752562.png">

**Comment by Steffy-zxf** [comment]
@hitcoogle，感谢反馈，该问题已经修复哦～，麻烦重新在尝试下哈。
tip：在此之前，需要先卸载senta_bilstm，在重新安装senta_bilstm。之前用hub show senta_bilstm可以得到正确结果哦～

**Comment by hitcoogle** [comment]
赞神速修复~👍
