### ISSUE TITLE
Cannot use CUDAPlace in CPU only version

### ISSUE THREAD

**Issue by VictorZhang2014** [PaddlePaddle/PaddleFormers#34]
```
Cannot use CUDAPlace in CPU only version at [/paddle/paddle/fluid/pybind/pybind.cc:806]
```
根据这个教程：https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E5%9B%BE%E5%83%8F%E5%88%86%E7%B1%BB%E8%BF%81%E7%A7%BB%E6%95%99%E7%A8%8B
当运行到这行代码时，报错了，不能使用CUDAPlace
<img width="1080" alt="WX20190423-171319@2x" src="https://user-images.githubusercontent.com/6853884/56569211-1ffe7300-65eb-11e9-8700-8a1db1642b95.png">

看了代码后，发现了在配置那块，少了个参数，如下代码
```
config = hub.RunConfig()
```

**Comment by VictorZhang2014** [comment]
看下文档，参数应该是`use_cuda=False`，所以整个配置文件如下
```
config = hub.RunConfig(
    use_cuda=False,
    num_epoch=1,
    checkpoint_dir="cv_finetune_turtorial_demo",
    batch_size=32,
    log_interval=10,
    eval_interval=50,
    strategy=hub.finetune.strategy.DefaultFinetuneStrategy())
```
麻烦百度PaddlePaddle工程师在文档的适当处加上

**Comment by nepeplwu** [comment]
@VictorZhang2014 ，感谢反馈，为了提升finetune的速度，RunConfig默认开启了GPU进行训练，文档中已经更新了RunConfig的示例代码和说明。
