### ISSUE TITLE
图像分类finetune 网络输入图片尺寸修改

### ISSUE THREAD

**Issue by cchan19** [PaddlePaddle/PaddleFormers#350]
1. 请问在使用时图像分类finetune，网络输入尺寸可以修改吗？
2. 图像分类finetune时有没有数据增强的功能？

**Comment by Steffy-zxf** [comment]
感谢反馈！网络输入图片尺寸可以修改。但由于预训练模型在初始训练时，已经设定了相应的图片尺寸，如果Fine-tune修改了图片尺寸，可能会导致训练预测效果不佳。故建议不要修改。
