### ISSUE TITLE
[BUG]复现示例代码时报错

### ISSUE THREAD

**Issue by skywalkerhao** [PaddlePaddle/PaddleFormers#351]
PaddleHub 1.5.1
Windows系统
Python3.7
照搬示例代码，图片路径确认无误。前期安装加载顺利，最后出结果的时候一直报错：TypeError: 'NoneType' object is not subscriptable。具体见下图
![image](https://user-images.githubusercontent.com/42575388/74602643-cf11bb00-50e5-11ea-8125-78706d264bf0.png)

![image](https://user-images.githubusercontent.com/42575388/74602648-e3ee4e80-50e5-11ea-9b63-b30811bd7a69.png)
![image](https://user-images.githubusercontent.com/42575388/74602652-f072a700-50e5-11ea-8714-1c00580ab462.png)

**Comment by nepeplwu** [comment]
@skywalkerhao ，感谢反馈，你的input_dict写错了，需要将图片放入list中，如下
```python
input_dict = {"image": ["C://Users//ThinkPad//PythonProject//Mask Detection//test.jpg"]}
```

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
