### ISSUE TITLE
[BUG]无法使用GPU推理

### ISSUE THREAD

**Issue by lim-0** [PaddlePaddle/PaddleFormers#352]
- 版本、环境信息
1）paddlehub                 1.5.1                  
paddlepaddle-gpu          1.6.3
2）系统环境：Linux，python3.7
- 复现信息：
使用口罩检测：
使用flask搭建服务端
results = module.face_detection(data=input_dict，use_gpu=True)

设置use_gpu=True后，使用nvidia-smi查看，并无显存占用，推理时间与cpu无差别

**Comment by nepeplwu** [comment]
@lim-0 ，感谢反馈，是否有设置环境变量CUDA_VISIBLE_DEVICES？

**Comment by lim-0** [comment]
> 设

没有设置，因为为找到相关文档，如果调用，需要怎样进行设置？增加一行CUDA_VISIBLE_DEVICES=0？

**Comment by lim-0** [comment]
> @lim-0 ，感谢反馈，是否有设置环境变量CUDA_VISIBLE_DEVICES？
没有设置，因为为找到相关文档，如果调用，需要怎样进行设置？增加一行CUDA_VISIBLE_DEVICES=0？

**Comment by nepeplwu** [comment]
假设准备用机器上的第0号卡进行预测，则在命令行进行设置
```shell
export CUDA_VISIBLE_DEVICES=0
```

**Comment by lim-0** [comment]
> 假设准备用机器上的第0号卡进行预测，则在命令行进行设置
> 
> ```shell
> export CUDA_VISIBLE_DEVICES=0
> ```

机器上只有一张卡，服务是用flask写的，就是启动前先
export CUDA_VISIBLE_DEVICES=0
然后python server.py启动服务吗？

**Comment by nepeplwu** [comment]
是的

**Comment by lim-0** [comment]
> 是的

好的，感谢！！

**Comment by Steffy-zxf** [comment]
您好，此issue在近2周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
