### ISSUE TITLE
[BUG]PaddleHub口罩检测，疑似GPU，CUDA设置无效

### ISSUE THREAD

**Issue by Luna2199** [PaddlePaddle/PaddleFormers#353]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：
paddlehub                     1.5.0 
paddlepaddle-gpu              1.6.3.post97
2）系统环境：4.15.0-76-generic #86~16.04.1-Ubuntu，
python版本: Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
                    [GCC 5.4.0 20160609] on linux2
- 复现信息：如为报错，请给出复现环境、复现步骤
### 核心代码:
` cap = cv2.VideoCapture(0）`
` success ,frame = cap.read()`
` module = hub.Module(name="pyramidbox_lite_mobile_mask")`
` input_dict = {"data": [frame ]} `
`results = module.face_detection(data=input_dict, use_cuda=True, use_gpu=True, batch_size=1）`
### ~/.bashrc 添加:
`export CUDA_VISIBLE_DEVICES=0`
### 执行命令
`CUDA_VISIBLE_DEVICES='0' python paddle_mask.py `
### 进程信息
**nvidia-smi**
                 ` 0     27717      C   python                                      3549MiB `
**top**
` 7995   root     20   0  24.060g  396740  182028 S     83.1        4.9   0:08.06    python `
### 反馈
**GPU推理时间 与 CPU (取消相关GPU设置)推理，做过对比， 推理时间相差无多，均在87ms~170ms波动。**

**Comment by nepeplwu** [comment]
@lanzhou2012 感谢反馈，你在对比CPU和GPU耗时的时候，大概跑了多少组数据？

**Comment by Luna2199** [comment]
> @lanzhou2012 感谢反馈，你在对比CPU和GPU耗时的时候，大概跑了多少组数据？

**我是直接使用了 USB摄像头 数据，每秒帧数应该在30左右。分辨率 640x480 **
`start = time.time()`
`input_dict = {"data": [frame]}`
`results = self.module.face_detection(data=input_dict, use_cuda=True, use_gpu=True, batch_size=1)`
`elapsed_time = time.time() - start`
`print ("elapsed_time:{0}".format(elapsed_time) + "[sec]")`
**输出结果**
`elapsed_time:0.0982749462128[sec]`
`face_location = [256, 400, 330, 334]`
`elapsed_time:0.132550954819[sec]`
`face_location = [256, 400, 328, 334]`
`elapsed_time:0.156831026077[sec]`
`face_location = [256, 400, 330, 334]`
**软硬件信息**
    **CPU**   `Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz`
    **GPU**    `GeForce GTX 960M`
    **CUDA**  `CUDA Version 9.2.148 `

**Comment by nepeplwu** [comment]
@lanzhou2012 ，由于paddle在第一次执行计算图的时候，会做计算图的优化，这部分会带来不少的性能消耗，所以建议你在对比的时候，先跑一次预测，然后记录第二次的预测结果进行对比

**Comment by Luna2199** [comment]
> @lanzhou2012 ，由于paddle在第一次执行计算图的时候，会做计算图的优化，这部分会带来不少的性能消耗，所以建议你在对比的时候，先跑一次预测，然后记录第二次的预测结果进行对比

嗯，我能懂您的意思，之前也看过一些说明。最近几天一直在尝试使用GPU，所以这套代码是反复执行过数次的。

**Comment by Luna2199** [comment]
我整理里一组**1233张图像**的数据集(其中带口罩 500+， 未戴口罩 600+):
### 核心代码
```
test_img_datas = [cv2.imread(img) for img in test_img_path]
sum_time = 0
for i in range(6):
    start = time.time()
    results = module.face_detection(data={"data":test_img_datas}, use_gpu=False, batch_size=32)
    elapsed_time = time.time() - start
    sum_time += elapsed_time
    print ("epoch:{}, elapsed_time:{}".format(i+1, elapsed_time) + "[sec]")

print ("the mean elapsed_time:{}".format(sum_time/6.0) + "[sec]")

```
### `module.face_detection`关键字参数，设置如下：
         **USE_GPU = True  BATCH_SIZE = 1** 
![*USE_GPU = True  BATCH_SIZE = 1](https://user-images.githubusercontent.com/21285692/74739514-f27a6880-5293-11ea-8eb7-91d619088d27.JPG)
         **USE_GPU =False  BATCH_SIZE = 1** 
![USE_CPU-BATCHSIZE=1](https://user-images.githubusercontent.com/21285692/74739589-1fc71680-5294-11ea-8387-ece08f2555c9.JPG)
         **USE_GPU = True  BATCH_SIZE = 16**
![USE_GPU-BATCHSIZE=16](https://user-images.githubusercontent.com/21285692/74739682-5b61e080-5294-11ea-84f5-93e015bf1249.JPG)
          **USE_GPU = False  BATCH_SIZE = 16**
![USE_CPU-BATCHSIZE=16](https://user-images.githubusercontent.com/21285692/74739792-8f3d0600-5294-11ea-9bc4-abb2bace3144.JPG)
          **USE_GPU = True   BATCH_SIZE = 32**
![USE_GPU-BATCHSIZE=32](https://user-images.githubusercontent.com/21285692/74739870-bc89b400-5294-11ea-8f7a-3e0ab1f1758e.JPG)
          **USE_GPU = False   BATCH_SIZE = 32** 
![USE_CPU-BATCHSIZE=32](https://user-images.githubusercontent.com/21285692/74739981-f064d980-5294-11ea-9755-f4466e4a13df.JPG)
          **中间也重新计算了一次  USE_GPU = True  BATCH_SIZE = 1** 
![USE_GPU-BATCHSIZE=1-second](https://user-images.githubusercontent.com/21285692/74740114-36ba3880-5295-11ea-9936-8437cd785875.JPG)
### 反馈
       **USE_GPU 的设置，似乎并没有生效，推理时间并没有明显改观，请问这是正常的吗？**

**Comment by Luna2199** [comment]
@nepeplwu

**Comment by Luna2199** [comment]
@nepeplwu 您好，请问关于GPU的使用问题，现在是什么情况？如果是我 设备软硬件版本 或 系统环境配置 的问题，麻烦告诉我，非常感谢。

**Comment by nepeplwu** [comment]
@lanzhou2012 感谢反馈，可以试试把batch再加大些看看

**Comment by nepeplwu** [comment]
我们也正在优化Module的运行速度

**Comment by Luna2199** [comment]
> 我们也正在优化Module的运行速度

好的，非常感谢！

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题
