### ISSUE TITLE
[BUG]使用http post方式进行预测，返回的结果图片和result data信息不一致

### ISSUE THREAD

**Issue by zhouhaitao1023** [PaddlePaddle/PaddleFormers#354]
1）PaddleHub1.5.1，PaddlePaddle1.6.2
2）系统环境：win10，python版本3.7
- 使用hub serving start -m pyramidbox_lite_server_mask -p 8866启动服务。
-使用http post方式进行预测，同时使用wireshark进行抓包，一张图片上有四个戴口罩的人脸，服务器返回的图片上也能看到检测结果，有四个戴口罩人脸检测结果。
-问题是返回的json字符串中，result里面只有一个戴口罩人脸位置信息。

**Comment by ShenYuhan** [comment]
您好，这个问题在新版本的PaddleHub会解决，我们稍后会发布PaddleHub的1.5.2版本，到时候更新即可。

**Comment by Steffy-zxf** [comment]
您好，此issue在近2周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
