### ISSUE TITLE
口罩本地预测结果图片

### ISSUE THREAD

**Issue by MasonYangD** [PaddlePaddle/PaddleFormers#355]
你好：
我想问下我在电脑本地预测是否戴口罩，结果已经返回，但是结果图片在哪里？是否要自己打异常标记框在原始图片上？还是说本身有结果图片输出？
谢谢

**Comment by nepeplwu** [comment]
@MasonYangD 结果图片存放在执行脚本的./detection_result目录下

**Comment by MasonYangD** [comment]
我已经整盘扫描过了，挨个找的，并未找到，是我哪里未设置什么吗？

**Comment by nepeplwu** [comment]
你的预测代码是是否可以发下？

**Comment by MasonYangD** [comment]
import cv2
import paddle
import paddlehub as hub
import json
import math

module = hub.Module(name="pyramidbox_lite_server_mask")

test_img_path = "C:\\Users\\Administrator.USER-20190807PY\\Desktop\\masks\\6.jpg"
img = cv2.imread(test_img_path)
input_dict = {"data": [cv2.imread(test_img_path)]}
results = module.face_detection(data=input_dict)

for result in results:
    print(result)

**Comment by Steffy-zxf** [comment]
以上预测方式确实不会保存预测结果图片。但另外一种方式可以保存预测结果图片，保存在执行脚本的./detection_result目录下。参考教程 https://aistudio.baidu.com/aistudio/projectdetail/267322 三、预测
```python
input_dict = {"image": test_img_path}
# 口罩检测预测
results = module.face_detection(data=input_dict)
```

**Comment by Steffy-zxf** [comment]
您好，此issue在近2周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
