### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by liuwen-nj** [PaddlePaddle/PaddleFormers#359]
paddleHub 安装失败：
命令：
但是结果python import paddle 失败：
Installing collected packages: nltk, sentencepiece, protobuf, tb-paddle, gunicorn, cma, mccabe, pycodestyle, pyflakes, entrypoints, flake8, aspy.yaml, toml, nodeenv, cfgv, zipp, importlib-metadata, identify, distlib, appdirs, filelock, virtualenv, pre-commit, pyasn1, rsa, pyasn1-modules, cachetools, google-auth, oauthlib, requests-oauthlib, google-auth-oauthlib, grpcio, markdown, absl-py, tensorboard, colorlog, yapf, pytz, python-dateutil, pandas, paddlehub
  Found existing installation: gunicorn 19.9.0
    Uninstalling gunicorn-19.9.0:
      Successfully uninstalled gunicorn-19.9.0
Successfully installed absl-py-0.9.0 appdirs-1.4.3 aspy.yaml-1.3.0 cachetools-4.0.0 cfgv-3.0.0 cma-2.7.0 colorlog-4.1.0 distlib-0.3.0 entrypoints-0.3 filelock-3.0.12 flake8-3.7.9 google-auth-1.11.2 google-auth-oauthlib-0.4.1 grpcio-1.27.2 gunicorn-20.0.4 identify-1.4.11 importlib-metadata-1.5.0 markdown-3.2.1 mccabe-0.6.1 nltk-3.4.5 nodeenv-1.3.5 oauthlib-3.1.0 paddlehub-1.5.1 pandas-1.0.1 pre-commit-2.0.1 protobuf-3.11.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycodestyle-2.5.0 pyflakes-2.1.1 python-dateutil-2.8.1 pytz-2019.3 requests-oauthlib-1.3.0 rsa-4.0 sentencepiece-0.1.85 tb-paddle-0.4.0 tensorboard-2.1.0 toml-0.10.0 virtualenv-20.0.4 yapf-0.26.0 zipp-3.0.0
sh-4.2# 
sh-4.2# 
sh-4.2#       python 
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlehub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/paddlehub/__init__.py", line 25, in <module>
    from . import module
  File "/opt/conda/lib/python3.7/site-packages/paddlehub/module/__init__.py", line 16, in <module>
    from . import module
  File "/opt/conda/lib/python3.7/site-packages/paddlehub/module/module.py", line 30, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'

**Comment by nepeplwu** [comment]
@liuwen-nj 感谢反馈，paddlehub需要配合paddlepaddle一起使用，请参考[paddle安装教程](https://www.paddlepaddle.org.cn/install/quick)选择合适的版本进行安装

**Comment by Steffy-zxf** [comment]
您好，此issue在近2周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
