### ISSUE TITLE
task.load_parameters(args.model_path)中model_path有例子吗 该如何利用这个参数进行增量训练

### ISSUE THREAD

**Issue by Kaiser-love** [PaddlePaddle/PaddleFormers#360]
task.load_parameters(args.model_path)中model_path有例子吗 该如何利用这个参数进行增量训练

**Comment by Steffy-zxf** [comment]
感谢反馈！task.load_parameters传入的model_path是利用接口 [save_persistables](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_persistables_cn.html#save-persistables)保存的模型参数。
如何进行增量训练，你可以先训练一版模型并保存(用save_persistables保存），之后将此时保存的模型参数用task.load_parameters接口加载进来，在这基础上继续finetune。

**Comment by Kaiser-love** [comment]
感谢回复
