### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fengzifrank** [PaddlePaddle/PaddleFormers#361]
用win10  python3.6安装paddlehub时报错

**Comment by fengzifrank** [comment]
PS D:\python3.6\Scripts> pip3 install paddlehub  -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting paddlehub
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/86/1d/beca41f262f74cad316f5b7aa171fe2f694ba7a46d260f7de06119f4e40c/paddlehub-1.5.1-py3-none-any.whl (197 kB)
Collecting yapf==0.26.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f7/b6/266774a11dc81539dcf3b5117cd7a3c1c2b11a47853940b7f0803cf389b2/yapf-0.26.0-py2.py3-none-any.whl (176 kB)
     |████████████████████████████████| 176 kB 2.2 MB/s
Collecting cma==2.7.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b9/3b/87a4efbcfeaf3172d81ef843f0b0c34c3ba60ec884aa6777f34f68b57418/cma-2.7.0-py2.py3-none-any.whl (239 kB)
Requirement already satisfied: protobuf>=3.6.0 in d:\python3.5\lib\site-packages (from paddlehub) (3.6.1)
Requirement already satisfied: nltk in d:\python3.5\lib\site-packages (from paddlehub) (3.2.1)
Requirement already satisfied: chardet==3.0.4 in d:\python3.5\lib\site-packages (from paddlehub) (3.0.4)
Collecting tb-paddle
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a4/0d/76a4f45bcb8368886243fa3fb081fa0e3be719af0d8d02ea3ca9d35e7ec9/tb_paddle-0.4.0-py2.py3-none-any.whl (129 kB)
Collecting sentencepiece
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/1b/87/c3c2fa8cbec61fffe031ca9f0da512747520bec9be7f886f748457daac31/sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\python3.5\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HASEE\\AppData\\Local\\Temp\\pip-install-1kvnl3ao\\sentencepiece\\setup.py'"'"'; __file__='"'"'C:\\Users\\HASEE\\AppData\\Local\\Temp\\pip-install-1kvnl3ao\\sentencepiece\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HASEE\AppData\Local\Temp\pip-install-1kvnl3ao\sentencepiece\pip-egg-info'
         cwd: C:\Users\HASEE\AppData\Local\Temp\pip-install-1kvnl3ao\sentencepiece\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HASEE\AppData\Local\Temp\pip-install-1kvnl3ao\sentencepiece\setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "d:\python3.5\lib\codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Steffy-zxf** [comment]
感谢反馈！PaddleHub在windows上python版本需>=3.6，根据以上报错信息
`ERROR: Command errored out with exit status 1:
command: 'd:\python3.5\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = `
实际运行的python是3.5。 请换成python3.6以上安装PaddleHub
