### ISSUE TITLE
[BUG]安装时候import发生错误

### ISSUE THREAD

**Issue by BI4O** [PaddlePaddle/PaddleFormers#363]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.5.1，PaddlePaddle1.6.3
2）系统环境：win10, python=3.7.0

无论是import paddle.fluid还是import paddlehub或者直接hub run都会提示
缺少msys-lzma-1.dll，重新安装可能解决此问题，但是我重新安装了还是这样

**Comment by Steffy-zxf** [comment]
感谢反馈！请按照[paddle安装指南](https://www.paddlepaddle.org.cn/) 正确安装完PaddlePaddle之后，再安装PaddleHub。

**Comment by Steffy-zxf** [comment]
您好，此issue在近2周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
