### ISSUE TITLE
人面口罩检测模型，怎样可以只返回json不返回图片

### ISSUE THREAD

**Issue by yujingyang666** [PaddlePaddle/PaddleFormers#364]
可以设置吗？还是必须返回图片？

**Comment by Steffy-zxf** [comment]
感觉反馈！请参考[PaddleHub口罩检测教程](https://aistudio.baidu.com/aistudio/projectdetail/267322) 第三章节 预测的末尾部分示例进行预测
如：
```python
import cv2
# 读入图片
test_img_datas = [cv2.imread(img) for img in test_img_path]
# 预测
results = module.face_detection(data={"data":test_img_datas})
```

**Comment by yujingyang666** [comment]
PaddleHub Serving不支持设置吧？

**Comment by ShenYuhan** [comment]
1、目前的1.5.1版本可以用这样的方式请求即可只返回json
```python
    with open(file="./woman_mask.png", mode="rb") as fp:
        base64_data = base64.b64encode(fp.read())
    base64_data = str(base64_data, encoding="utf8")
    url = "http://127.0.0.1:8866/predict/image/pyramidbox_lite_mobile_mask"
    data = {"b64s": [base64_data]}
    r = requests.post(url=url, data={"data": json.dumps(data)})
```
2、我们即将升级的PaddleHub1.5.2版本可以通过http请求添加相应参数选择是否传回图片，敬请期待。

**Comment by yujingyang666** [comment]
> 感觉反馈！请参考[PaddleHub口罩检测教程](https://aistudio.baidu.com/aistudio/projectdetail/267322) 第三章节 预测的末尾部分示例进行预测
> 如：
> 
> ```python
> import cv2
> # 读入图片
> test_img_datas = [cv2.imread(img) for img in test_img_path]
> # 预测
> results = module.face_detection(data={"data":test_img_datas})
> ```

如果我是客户端传入base64，不是读图片路径，这一步我该如何转换

**Comment by nepeplwu** [comment]
这个需要看你的数据是什么格式的。举个例子，如果你传过来的数据是图片的二进制格式进行了base64编码，那么在预测前，你需要先进行base64解码，然后将二进制数据转为numpy数据（如cv2..imencode）
