### ISSUE TITLE
[Feature]paddlehub离线安装&&口罩检测

### ISSUE THREAD

**Issue by jetyingjia** [PaddlePaddle/PaddleFormers#365]
请问paddlehub可否离线安装？
口罩检测可否离线测试？
谢谢

**Comment by nepeplwu** [comment]
@jetyingjia paddlehub不支持离线安装，口罩模型一旦下载到本地后，就可以离线测试

**Comment by jetyingjia** [comment]
@nepeplwu 能否给出口罩模型放置的目录，我这边离线安装了hub, 离线下载好了模型，ubuntu系统，谢谢！

**Comment by Steffy-zxf** [comment]
通过PaddleHub下载的预训练模型，都是存放在${HUB_HOME}/.paddlehub/modules/ 下

PaddleHub支持修改预训练模型存放路径：

如已设置${HUB_HOME}环境变量，则预训练模型、配置等文件都存放在${HUB_HOME}指示的路径下
如未设置${HUB_HOME}环境变量，则存放在$HOME指示的路径下
