### ISSUE TITLE
paddlehub安装不成功

### ISSUE THREAD

**Issue by Melonzhou** [PaddlePaddle/PaddleFormers#37]
使用pip install paddlehub-0.4.6b0-py2-none-any.whl 进行安装，安装成功后执行hub命令，出现以下错误，paddle版本为1.3

![image](https://user-images.githubusercontent.com/5926307/56957939-556f0780-6b7b-11e9-8f0d-6fe81e96e6e0.png)

**Comment by ZeyuChen** [comment]
您好，我们PaddleHub最新版本是0.5.0，请看看是否可以更新下最新源，或试用一下最新版本安装
pip install -i https://pypi.org/simple/ paddlehub
另外出现这一错误是libmkldnn缺失，请检查下是否已正确安装了paddlepaddle 1.4.1版本
请尝试使用conda结合pip install paddlepaddle进行使用，推荐使用anaconda+python3的方式安装paddlepaddle。

**Comment by Melonzhou** [comment]
paddlehub的版本和paddlepaddle的版本没有必然关系，我使用paddlepaddle自带的python环境中的pip重新按pip install paddlehub 安装成功了，能正常运行，感谢 ~
