### ISSUE TITLE
想问一下PaddleCV下面有关train文件的问题

### ISSUE THREAD

**Issue by LilyCaiZL** [PaddlePaddle/PaddleFormers#370]
![image](https://user-images.githubusercontent.com/40067956/74935343-0ef8db00-5423-11ea-883d-40be035ebe4f.png)
您好，我想问一下train.py运行的时候，这些arg是在哪个文件定义的，我实在找不到了，希望解答，我用hub的时候需要用，谢谢老师

**Comment by Steffy-zxf** [comment]
感谢反馈！关于PaddleCV下的问题，请到 PaddlePaddle/models 下提issue。https://github.com/PaddlePaddle/models/issues

**Comment by ZeyuChen** [comment]
Issuse closed since it's a model issues instead of PaddleHub.
