### ISSUE TITLE
服务器部署设为守护进程，使其脱离终端后提供服务

### ISSUE THREAD

**Issue by omtbreak** [PaddlePaddle/PaddleFormers#371]
请问在服务器部署好模型后，关闭访问终端，模型就没有办法提供服务该如何解决，如何将其设置为守护进程呢

**Comment by ShenYuhan** [comment]
请问您的需求和使用环境是什么呢？一般来说直接关闭远程登陆后不会退出进程的。

**Comment by omtbreak** [comment]
需求是部署在服务器上后，使用hub serving start 开启pyramidbox_lite_server_mask模型，服务器系统是Ubuntu 18 。在关闭远程登录后，隔段时间，客户端程序就无法获取检测结果了。但是如果重新登陆，发现进程是开着的，并且处于端口listen状态，但不能进行调用。关闭进程重新开启模型才能检测。

**Comment by ShenYuhan** [comment]
您好，您可以试一下 nohup hub serving start -m pyramidbox_lite_server_mask &，将程序挂在后台运行。

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
