### ISSUE TITLE
默认依赖的imageio只兼容py3

### ISSUE THREAD

**Issue by guru4elephant** [PaddlePaddle/PaddleFormers#372]
python2环境
pip install paddlehub
![image](https://user-images.githubusercontent.com/35550832/75000124-7309b680-5498-11ea-9826-d152d16a9363.png)

**Comment by Steffy-zxf** [comment]
感谢反馈！PaddleHub的安装环境依赖：
https://github.com/PaddlePaddle/PaddleHub#%E7%8E%AF%E5%A2%83%E4%BE%9D%E8%B5%96
```text
环境依赖
* Python==2.7 or Python>=3.5 for Linux or Mac
* Python>=3.6 for Windows
* PaddlePaddle>=1.5
```

请确认你的环境是否满足。

**Comment by guru4elephant** [comment]
手动装了一个低版本的imageio后即可，如果对imageio没有版本要求，建议用低版本保证py2 py3都可以使用

**Comment by Steffy-zxf** [comment]
感谢建议！我们看下选用什么版本比较合适。

**Comment by Steffy-zxf** [comment]
您好！PaddleHub 1.7.0版本之后已经去除了imageio依赖。
