### ISSUE TITLE
新版口罩检测，迁移到android直接崩溃

### ISSUE THREAD

**Issue by northeastsquare** [PaddlePaddle/PaddleFormers#389]
ubuntu 16.04
PaddlePaddle '1.6.3'
PaddleHub release/v1.5

1. 下载这个目录：https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.5/demo/mask_detection/python
2. python export_model.py, 生成pyramidbox_lite_mobile_mask，然后cd进入
3. ~/work/model_optimize_tool --model_file=./mask_detector/__model__ --param_file=./mask_detector/__params__ --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=mask_detector_opt1 , 这样mask_detector_opt1下面生成 “__model__.nb  param.nb”

4.把两个文件拷贝到https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/demo/cxx/mask_detection/mask_detection.cc， 对应位置运行
加载就直接报错

**Comment by juncaipeng** [comment]
请问你具体错误log信息是什么？因为现在模型在不断优化，会出现不同的问题。

**Comment by juncaipeng** [comment]
请参考paddlelite 2.3或者2.6分支的demo文档，都是可以执行的。

https://github.com/PaddlePaddle/Paddle-Lite/tree/release/v2.6.0/lite/demo/cxx

**Comment by northeastsquare** [comment]
ok,当时实在跑不通，就切换框架了
