### ISSUE TITLE
Lac使用自定义词典返回500

### ISSUE THREAD

**Issue by Kidron-Hou** [PaddlePaddle/PaddleFormers#390]
环境信息：PaddleHubreleasev1.5在windows上python3.7
问题：LAC使用自定义词典时返回500。这里使用的字典为git上demo里的txt文档，未改动。LAC为本地部署的接口，不用自定义词典时可以正常使用。

**Comment by ShenYuhan** [comment]
您好，方便的话可以提供下：
1 客户端请求代码
2 服务端的报错日志

**Comment by Kidron-Hou** [comment]
已解决，问题在未安装pyahocorasick包，建议在[部署词法分析服务-以lac为例](https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.5/demo/serving/module_serving/lexical_analysis_lac#%E9%83%A8%E7%BD%B2%E8%AF%8D%E6%B3%95%E5%88%86%E6%9E%90%E6%9C%8D%E5%8A%A1-%E4%BB%A5lac%E4%B8%BA%E4%BE%8B)页上给出提示。

**Comment by Kidron-Hou** [comment]
请问对于“北京百度网讯科技有限公”这类识别为org，在实际使用时能否通过自定义词典进行筛除掉。

**Comment by Steffy-zxf** [comment]
你想把“北京百度网讯科技有限公” 这类词识别成 什么呢？

**Comment by Kidron-Hou** [comment]
当文本中为“北京百度网讯科技有限公司"时算法识别为org，对于“北京百度网讯科技有限公”直接过滤掉，这类词在实际业务中无法使用。

**Comment by Steffy-zxf** [comment]
这种情况，你可以通过拿到lac预测返回结果之后， 对于你不想要的分词结果，直接丢弃就行。

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题
