### ISSUE TITLE
模型是否可以运行在GPU下

### ISSUE THREAD

**Issue by KaggleAlbertaAI** [PaddlePaddle/PaddleFormers#391]
请问pyramidBox-lite-server-mask模型在paddle框架下是否可以使用GPU模式运行，目前用来处理视频觉得FPS有些慢了，实时性不够好。

**Comment by nepeplwu** [comment]
@KaggleAlbertaAI ，感谢反馈，模型是支持gpu预测的，可以参考以下api文档
https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_server_mask&en_category=ObjectDetection
![10713DF9-3639-4101-B024-F20639247D27](https://user-images.githubusercontent.com/45024560/75321787-7ba12900-58ac-11ea-8afe-c9e57189391d.JPG)

**Comment by KaggleAlbertaAI** [comment]
好的，谢谢。
解决了我的问题。

**Comment by KaggleAlbertaAI** [comment]
> @KaggleAlbertaAI ，感谢反馈，模型是支持gpu预测的，可以参考以下api文档
> https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_server_mask&en_category=ObjectDetection
> ![10713DF9-3639-4101-B024-F20639247D27](https://user-images.githubusercontent.com/45024560/75321787-7ba12900-58ac-11ea-8afe-c9e57189391d.JPG)

好的，谢谢。
解决了我的问题。

**Comment by Steffy-zxf** [comment]
您好，此issue在近2周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
