### ISSUE TITLE
BUG 1.模型下载下来是__param__,代码里是__params__,运行报错 2. 预测出来的faces[idx].class_id 不是0或者1

### ISSUE THREAD

**Issue by niceweipeng** [PaddlePaddle/PaddleFormers#392]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.5.3，PaddlePaddle-gpu1.6.3
2）系统环境：python版本

1.模型下载下来是__param__,代码里是__params__,运行报错 ,改下名称就行
 2. 预测出来的faces[idx].class_id 不是0或者1，报
   abel = LABELS[face.class_id]
IndexError: list index out of range
这个请教下是什么原因呢

**Comment by niceweipeng** [comment]
运行的是 高性能Python部署方案   运行命令：python infer.py --models_dir=/path/to/models --img_paths=/path/to/images --video_path=/path/to/video --video_size=size/of/video --use_camera=(False/True)
--use_gpu=(False/True)

**Comment by ZeyuChen** [comment]
@niceweipeng 请确认下是否是使用export_model.py这个导出的模型
新版本的Module导出后的的参数文件名应该为__params__
你也可以手动讲现有的模型文件名从__param__改为__params__

**Comment by Channingss** [comment]
@niceweipeng 请在调用hub模型的时候，使用version='1.1.0'版本的模型，hub.Module(name="pyramidbox_lite_server_mask", version='1.1.0')

**Comment by niceweipeng** [comment]
> @niceweipeng 请确认下是否是使用export_model.py这个导出的模型
> 新版本的Module导出后的的参数文件名应该为__params__
> 你也可以手动讲现有的模型文件名从__param__改为__params__

确定使用export_model.py这个导出的模型（不管直接运行export_model.py还是git克隆下来项目再运行都是不带s的）。手动改名可运行，但是预测的类不是0或者1（口罩识别预测值应该是0,1才对）

**Comment by niceweipeng** [comment]
> @niceweipeng 请在调用hub模型的时候，使用version='1.1.0'版本的模型，hub.Module(name="pyramidbox_lite_server_mask", version='1.1.0')

你说的这个没问题可运行，但是我测试的是高性能Python部署方案的那种

**Comment by Channingss** [comment]
@niceweipeng 我看模型还是老版本的，老版本的模型分类的输出output[1]，新版本的输出是output[0],你可以在高性能的python部署的代码里面https://github.com/PaddlePaddle/PaddleHub/blob/255b68143e750951195829ff21207e33b863092b/demo/mask_detection/python/infer.py#L191，
这一行最后获取输出的self.predictor.run([im_tensor])[0]改为self.predictor.run([im_tensor])[1]。

**Comment by ZeyuChen** [comment]
@niceweipeng 或者请删除HOME目录下~/.paddlehub/这个文件重新后，重新执行export_model.py
这样才会下载最新模型后顺利完成最新版本的代码匹配。

**Comment by niceweipeng** [comment]
> @niceweipeng 或者请删除HOME目录下~/.paddlehub/这个文件重新后，重新执行export_model.py
> 这样才会下载最新模型后顺利完成最新版本的代码匹配。
删除掉旧的版本果然解决问题了，赞

**Comment by niceweipeng** [comment]
> ]



> @niceweipeng 或者请删除HOME目录下~/.paddlehub/这个文件重新后，重新执行export_model.py
> 这样才会下载最新模型后顺利完成最新版本的代码匹配。

删除掉旧的版本果然解决问题了，赞

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
