### ISSUE TITLE
paddle.fluid.core_avx.EnforceNotMet问题求助

### ISSUE THREAD

**Issue by YasinZhao** [PaddlePaddle/PaddleFormers#394]
你好，运行项目时，报paddle.fluid.core_avx.EnforceNotMet问题，请问如何修改，谢谢~
1、paddlehub1.5.3  paddlepaddle1.7.0
2、系统环境：win10子系统，Ubuntu环境
具体错误如下图
![image](https://user-images.githubusercontent.com/16828608/75426347-71039400-597f-11ea-8ff7-d5f0ddb76592.png)

**Comment by Steffy-zxf** [comment]
感谢反馈！根据错误提示，`pyramidbox_lite_server_mask/pyramidbox_lite/pyramidbox_lite/__model__ `不存在，请检查下路径是否正确。

**Comment by YasinZhao** [comment]
> 感谢反馈！根据错误提示，`pyramidbox_lite_server_mask/pyramidbox_lite/pyramidbox_lite/__model__ `不存在，请检查下路径是否正确。

你好，已解决，谢谢~
