### ISSUE TITLE
mask_detection视频文件识别出错

### ISSUE THREAD

**Issue by Nasturtium-yyc** [PaddlePaddle/PaddleFormers#396]
输入video_path进行视频文件识别，出现报错：
C:\Windows\System32\PaddleHub\demo\mask_detection\python\pyramidbox_lite_server_mask
[ERROR:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap.cpp (116) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): C:\Windows\System32\PaddleHub\demo\mask_detection\python\videos in function 'cv::icvExtractPattern'

Traceback (most recent call last):
  File "infer.py", line 277, in <module>
    predict_video(args)
  File "infer.py", line 267, in predict_video
    print("include read time:", (end_time - start_time) / index)
ZeroDivisionError: float division by zero

不过发现result文件夹中出现了测试video的文件，但是打不开。

**Comment by Channingss** [comment]
@Nasturtium-yyc 请问视频的格式是？另外video_path指定到了文件吗？不是文件夹哦

**Comment by Nasturtium-yyc** [comment]
> @Nasturtium-yyc 请问视频的格式是？另外video_path指定到了文件吗？不是文件夹哦
格式是MP4，指定了文件也不行

**Comment by Nasturtium-yyc** [comment]
解决了

**Comment by Nasturtium-yyc** [comment]
感谢，问题已解决，另外请问，use_camera=True能否开启笔记本摄像头，还学要视频文件目录吗？








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"channings"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 中午1:23
收件人:&nbsp;"PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
抄送:&nbsp;"记忆沙城"<ycy0706@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleHub] mask_detection视频文件识别出错 (#396)




@Nasturtium-yyc 请问视频的格式是？另外video_path指定到了文件吗？不是文件夹哦

**Comment by Channingss** [comment]
@Nasturtium-yyc 可以的，请结合demo里面的代码进行开发

https://github.com/PaddlePaddle/PaddleHub/blob/255b68143e750951195829ff21207e33b863092b/demo/mask_detection/mask_detection.py#L98

**Comment by Channingss** [comment]
@Nasturtium-yyc 您好，我们更新了代码，优化了use_camera，以及实时显示视频检测结果的参数open_imshow。

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题
