### ISSUE TITLE
使用conda安装得paddlepaddle numpy是1.13.1，然后安装paddlehub：import得时候却显示

### ISSUE THREAD

**Issue by yhl2018** [PaddlePaddle/PaddleFormers#397]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by yhl2018** [comment]
this version of pandas is incompatible with numpy < 1.13.3

**Comment by yhl2018** [comment]
paddlepaddle-gpu          1.7.0           py36_gpu_cuda10.0_many_linux    paddle
paddlehub            1.5.3

**Comment by Steffy-zxf** [comment]
感谢反馈！根据提示 `this version of pandas is incompatible with numpy < 1.13.3` ，先卸载numpy 和pandas
```shell
$ pip uninstall numpy
$ pip uninstall pandas
```

之后尝试安装 numpy 1.16.2版本，pandas  0.24.2版本
```shell
$ pip install numpy==1.16.2
$ pip install pandas== 0.24.2
```

**Comment by yhl2018** [comment]
好的，多谢

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
