### ISSUE TITLE
infer文件的predict_video中use_camera为什么默认关闭？如何调用摄像头实时监测？

### ISSUE THREAD

**Issue by Nasturtium-yyc** [PaddlePaddle/PaddleFormers#398]
def predict_video(args, im_shape=(1920, 1080), use_camera=False):
    if args.use_camera:
        capture = cv2.VideoCapture(0)
    else:
        capture = cv2.VideoCapture(args.video_path)
 capture = cv2.VideoCapture(0)是调用笔记本摄像头，怎么能够实时显示检测？

**Comment by Channingss** [comment]
@Nasturtium-yyc 在main函数里面判断args.use_camera，允许进入predict_video，然后参看demo：https://github.com/PaddlePaddle/PaddleHub/blob/255b68143e750951195829ff21207e33b863092b/demo/mask_detection/mask_detection.py#L98
对单帧的结果进行可视化，即可实时显示摄像头检测

**Comment by Nasturtium-yyc** [comment]
你好，我在infer.py文件while循环里增加了以下代码：
&nbsp; &nbsp; cv2.imshow('Mask Detection', frame)
&nbsp; &nbsp; if cv2.waitKey(5) &amp; 0xFF == ord('q'):
&nbsp; &nbsp; &nbsp; &nbsp; break
运行时调用了摄像头，但是并没有进行识别，result文件夹中有了视频文件但是无法播放
另外实时检测时python infer.py --models_dir=/path/to/models&nbsp;--video_path=/path/to/video&nbsp;--use_camera=True这个指令的video_path是必须的吗？
while (1):
    ret, frame = capture.read()
    if not ret:
        break
    cv2.imshow('Mask Detection', frame)
    if cv2.waitKey(5) &amp; 0xFF == ord('q'):
        break
    print('detect frame:%d' % (index))




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"channings"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月29日(星期六) 晚上7:25
收件人:&nbsp;"PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
抄送:&nbsp;"记忆沙城"<ycy0706@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleHub] infer文件的predict_video中use_camera为什么默认关闭？如何调用摄像头实时监测？ (#398)




@Nasturtium-yyc 在main函数里面判断args.use_camera，允许进入predict_video，然后参看demo：https://github.com/PaddlePaddle/PaddleHub/blob/255b68143e750951195829ff21207e33b863092b/demo/mask_detection/mask_detection.py#L98
 对单帧的结果进行可视化，即可实时显示摄像头检测

**Comment by Nasturtium-yyc** [comment]
你好，我在infer.py文件while循环里增加了以下代码：
&nbsp; &nbsp; cv2.imshow('Mask Detection', frame)
&nbsp; &nbsp; if cv2.waitKey(5) &amp; 0xFF == ord('q'):
&nbsp; &nbsp; &nbsp; &nbsp; break
运行时调用了摄像头，但是并没有进行识别，result文件夹中有了视频文件但是无法播放
另外实时检测时python infer.py --models_dir=/path/to/models&nbsp;--video_path=/path/to/video&nbsp;--use_camera=True这个指令的video_path是必须的吗？








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"channings"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月29日(星期六) 晚上7:25
收件人:&nbsp;"PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
抄送:&nbsp;"记忆沙城"<ycy0706@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleHub] infer文件的predict_video中use_camera为什么默认关闭？如何调用摄像头实时监测？ (#398)




@Nasturtium-yyc 在main函数里面判断args.use_camera，允许进入predict_video，然后参看demo：https://github.com/PaddlePaddle/PaddleHub/blob/255b68143e750951195829ff21207e33b863092b/demo/mask_detection/mask_detection.py#L98
 对单帧的结果进行可视化，即可实时显示摄像头检测

**Comment by Channingss** [comment]
@Nasturtium-yyc 请使用分支release/v1.5最新的代码，我们提供了你需要的新功能。运行时指定--use_camera true。video_path是用来指定识别的视频文件所在路径，use_camera是用来指定是否开启摄像头识别，是两种场景，二选一。

**Comment by Nasturtium-yyc** [comment]
你好，刚运行新的版本，笔记本摄像头指示灯亮了，但是并未显示，终端显示正在检测帧，一直在计数，请问这是什么原因？并且result文件夹出现了视频文件但是依然打不开。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"channings"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月2日(星期一) 下午2:25
收件人:&nbsp;"PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
抄送:&nbsp;"记忆沙城"<ycy0706@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleHub] infer文件的predict_video中use_camera为什么默认关闭？如何调用摄像头实时监测？ (#398)




@Nasturtium-yyc 请使用分支release/v1.5最新的代码。运行时指定--use_camera true。

**Comment by Channingss** [comment]
@Nasturtium-yyc  麻烦更新到最新的代码，然后使用参数--open_imshow：是否对视频的检测结果实时绘图，默认为False
