### ISSUE TITLE
为什么检测时候，模型的精度不高？servie版只比mobile版高一点点

### ISSUE THREAD

**Issue by lzcchl** [PaddlePaddle/PaddleFormers#399]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

**Comment by lzcchl** [comment]
用两个模型来测试视频，结果差距不算很大，但是检测效果就是没有很好的区别带不带口罩的人

**Comment by adaxiadaxi** [comment]
@lzcchl hi，同学，你这边有测试的效果嘛？欢迎先加入飞桨官方技术交流群：703252161 可以更方便及时的交流信息哈~

**Comment by adaxiadaxi** [comment]
@lzcchl 同学，你这边的case反馈更多是想说明把没有戴口罩的人检测成带口罩了是嘛？这个bad cases我们已经在努力迭代升级了，预计这周会出一版新的模型
