### ISSUE TITLE
使用Demo的视频检测时，result文件夹下的输出视频只有两百多字节，且无法打开输出视频

### ISSUE THREAD

**Issue by Forestyuting** [PaddlePaddle/PaddleFormers#400]
视频指定到了文件：python infer.py --models_dir=E:/detection/PaddleHub/demo/mask_detection/python/pyramidbox_lite_server_mask --video_path=E:/detection/PaddleHub/demo/mask_detection/python/videos/2.mp4

**Comment by Channingss** [comment]
@Forestyuting  你好，应该是视频分辨率大小没有指定，刚刚提交了自动识别视频分辨率的代码，可尝试最新的代码。

**Comment by Forestyuting** [comment]
谢谢您的解答，更新版本后能正常使用了，但是运行到一半程序崩溃，错误代码如图。期待模型能继续优化！
`Traceback (most recent call last):
  File "infer.py", line 281, in <module>
    elif args.video_path != '' or args.use_camera:
  File "infer.py", line 261, in predict_video
    index += 1
  File "infer.py", line 192, in Predict
    output_data = output_data.as_ndarray()
  File "infer.py", line 173, in Postprocess
    class_id = int(out[0])
IndexError: index 1 is out of bounds for axis 0 with size 1`

**Comment by Channingss** [comment]
@Forestyuting 请问一下，跑不同的视频都遇到这个问题了吗？另外，能把出问题的视频发到我的邮箱吗？

**Comment by Forestyuting** [comment]
已发您163邮箱，其他视频都可以正常检测

**Comment by Channingss** [comment]
@Forestyuting 我这边使用您的视频，在Windows10和mac都没有复现出您描述的问题，预测的结果发回您的邮箱了，能详细描述一下您使用的过程和环境吗？

**Comment by Forestyuting** [comment]
> @Forestyuting 我这边使用您的视频，在Windows10和mac都没有复现出您描述的问题，预测的结果发回您的邮箱了，能详细描述一下您使用的过程和环境吗？

您好，电脑环境：win10，python版本3.7.3，paddlehub版本releasev1.5，
运行时直接命令`python infer.py --models_dir=E:/detection/PaddleHub1.5/demo/mask_detection/python/pyramidbox_lite_server_mask --video_path=E:/detection/PaddleHub1.5/demo/mask_detection/python/videos/1.mp4 --open_imshow=True`重复试了几次都是在22秒左右崩溃，其他视频没出现这个问题，另外我改了infer.py里的line262行的shrink=0.1！

**Comment by Channingss** [comment]
@Forestyuting 我这边环境：shrink=0.1，win10，python3.7.3，paddlehub版本releasev1.5。还是没有复现出来这个bug。

**Comment by ShanksYI** [comment]
> > @Forestyuting 我这边使用您的视频，在Windows10和mac都没有复现出您描述的问题，预测的结果发回您的邮箱了，能详细描述一下您使用的过程和环境吗？
> 
> 您好，电脑环境：win10，python版本3.7.3，paddlehub版本releasev1.5，
> 运行时直接命令`python infer.py --models_dir=E:/detection/PaddleHub1.5/demo/mask_detection/python/pyramidbox_lite_server_mask --video_path=E:/detection/PaddleHub1.5/demo/mask_detection/python/videos/1.mp4 --open_imshow=True`重复试了几次都是在22秒左右崩溃，其他视频没出现这个问题，另外我改了infer.py里的line262行的shrink=0.1！

当没有检测到人脸时，需要判断一下数组越界的问题，加入一行判断就可以了
……
for out in output_data:
            if len(out) < 5:
                continue
            class_id = int(out[0])
……
