### ISSUE TITLE
口罩检测有BUG，就是如果视频或者照片没有人脸的时候，直接崩溃了

### ISSUE THREAD

**Issue by lzcchl** [PaddlePaddle/PaddleFormers#401]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by lzcchl** [comment]
如题，不知道在哪儿改

**Comment by nepeplwu** [comment]
@lzcchl 能够提供下崩溃日志和测试图片吗？我们这边测试是没问题的
