### ISSUE TITLE
win10环境下 hub.Module(name="pyramidbox_lite_mobile_mask") 加载预训练模型错误

### ISSUE THREAD

**Issue by MrRGRG** [PaddlePaddle/PaddleFormers#407]
1）PaddleHub1.5.3，PaddlePaddle1.7.0
2）系统环境：win10 python3.6（3.7也不行）
- 复现信息：如为报错，请给出复现环境、复现步骤

win10环境下 hub.Module(name="pyramidbox_lite_mobile_mask") 加载预训练模型时出现 Error: Cannot open file C:\Users\xxxx\.paddlehub\modules\pyramidbox_lite_mobile_mask\model\@HUB_pyramidbox_lite_mobile_mask@age_block1_3.b_0 for load op at (D:\1.7.0\paddle\paddle/fluid/operators/load_op.h:38) [operator < load > error] 
D盘没有什么1.7.0，前面教程里面的两行确实有出现。。。新手求解答=。=（在AI studio里面就没有问题）

**Comment by MrRGRG** [comment]
就加载口罩检测的模型

**Comment by Steffy-zxf** [comment]
感谢反馈！你存放pyramidbox_lite_mobile_mask模型的路径`C:\Users\xxxx.paddlehub\modules\pyramidbox_lite_mobile_mask\`建议不要带有中文字符。
可以通过修改$HUB_HOME环境变量指定模型下载存放地址
参考[命令行使用教程](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/docs/tutorial/cmdintro.md#paddlehub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7)

**Comment by MrRGRG** [comment]
修改后载入成功，但是预测时显示W0302 21:49:59.747802 11992 operator.cc:181] conv2d raises an exception class std::runtime_error, mklml.dll not found.是否与tensorflow版本有关?我试过2.0也试过1.15都不行，感谢上一条的来信


 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Steffy-zxf"<notifications@github.com&gt;; 
发送时间: 2020年3月2日(星期一) 晚上6:00
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;; 
抄送: "煮鸡蛋"<1150671652@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleHub] win10环境下 hub.Module(name=&quot;pyramidbox_lite_mobile_mask&quot;) 加载预训练模型错误 (#407)




感谢反馈！你存放pyramidbox_lite_mobile_mask模型的路径C:\Users\xxxx.paddlehub\modules\pyramidbox_lite_mobile_mask\建议不要带有中文字符。
 可以通过修改$HUB_HOME环境变量指定模型下载存放地址
 参考命令行使用教程

**Comment by Steffy-zxf** [comment]
此问题参考 https://github.com/PaddlePaddle/PaddleHub/issues/412 解决方法。
