### ISSUE TITLE
window10 pycharm里运行mask_detection.py后rusults里的视频不能播放

### ISSUE THREAD

**Issue by xd905** [PaddlePaddle/PaddleFormers#410]
window10 pycharm里运行mask_detection.py通过摄像头检测有无戴口罩后results里的视频不能播放，但是通过检测视频格式为.mp4的视频保存下来的results视频就可以正常播放
，都是使用potplayer播放的。但是我视频检测几帧就无响应报错了。

**Comment by Channingss** [comment]
@xd905 麻烦使用命令行方式试一下看，也可以考虑换一个文件，看上去像抽帧失败了。如果视频识别还报错的话，麻烦把有问题的视频文件发到我的邮箱，视频无法播放的问题，你可以修改下视频的编码方式：
https://github.com/PaddlePaddle/PaddleHub/blob/042c80333e88e0df0b6437e15bb2b4f423e3cbf4/demo/mask_detection/mask_detection.py#L35
使用cv2.VideoWriter_fourcc(*'mp4v')试试

**Comment by xd905** [comment]
> @ xd905麻烦使用命令行方式试一下看，也可以考虑换一个文件，看起来像抽帧失败了。如果视频识别还报错的话，麻烦把有问题的视频文件发到我的邮箱，视频无法播放的问题，你可以修改下视频的编码方式：
> https://github.com/PaddlePaddle/PaddleHub/blob/042c80333e88e0df0b6437e15bb2b4f423e3cbf4/demo/mask_detection/mask_detection.py#L35
> 
> 
> 使用cv2.VideoWriter_fourcc（*'mp4v'）试试

改了还是无法播放结果视频

**Comment by Channingss** [comment]
@xd905 换一个视频呢？把出问题的视频发给我邮箱

**Comment by xd905** [comment]
> @ xd905换一个视频呢？把出问题的视频发给我邮箱

是通过打开电脑摄像头检测是否有戴口罩然后保存下来的结果视频无法打开播放，但是检测视频的就可以

**Comment by xd905** [comment]
> @ xd905换一个视频呢？把出问题的视频发给我邮箱

结果的视频以发

**Comment by Channingss** [comment]
@xd905 麻烦更新到最新的代码，应该是摄像头分辨率和默认的不一致，我们新增了自动识别视频分辨率。然后还新增了参数--open_imshow：是否对视频的检测结果实时绘图，默认为False

**Comment by xd905** [comment]
> @xd905 麻烦更新到最新的代码，应该是摄像头分辨率和默认的不一致，我们新增了自动识别视频分辨率。然后还新增了参数--open_imshow：是否对视频的检测结果实时绘图，默认为False

替换成了最新的代码，然后取消了里面的相关注释，无法运行成功
报错日志：
C:\Users\xiaomi\Anaconda3\python.exe C:/Users/xiaomi/PycharmProjects/untitled8/FaceMaskDetection-master/mask_detection.py
[2020-03-04 17:22:54,402] [    INFO] - Installing pyramidbox_lite_server_mask module-1.1.0
[2020-03-04 17:22:54,420] [    INFO] - Module pyramidbox_lite_server_mask-1.1.0 already installed in C:\Users\xiaomi\.paddlehub\modules\pyramidbox_lite_server_mask
[2020-03-04 17:22:54,537] [    INFO] - Installing pyramidbox_lite_server module-1.1.0
[2020-03-04 17:22:54,591] [    INFO] - Module pyramidbox_lite_server-1.1.0 already installed in C:\Users\xiaomi\.paddlehub\modules\pyramidbox_lite_server
[2020-03-04 17:22:59,999] [    INFO] - 133 pretrained paramaters loaded by PaddleHub
[2020-03-04 17:23:00,413] [    INFO] - 143 pretrained paramaters loaded by PaddleHub
Traceback (most recent call last):
  File "C:/Users/xiaomi/PycharmProjects/untitled8/FaceMaskDetection-master/mask_detection.py", line 96, in <module>
    color)
  File "C:/Users/xiaomi/PycharmProjects/untitled8/FaceMaskDetection-master/mask_detection.py", line 16, in paint_chinese
    'SourceHanSansSC-Medium.otf', fontsize, encoding="utf-8")
  File "C:\Users\xiaomi\Anaconda3\lib\site-packages\PIL\ImageFont.py", line 280, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\xiaomi\Anaconda3\lib\site-packages\PIL\ImageFont.py", line 145, in __init__
    layout_engine=layout_engine)
OSError: cannot open resource
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback

Process finished with exit code 1

代码：
# -*- coding:utf-8 -*-
import paddlehub as hub
import cv2
from PIL import Image, ImageDraw, ImageFont
import numpy as np
import json
import os

module = hub.Module(name="pyramidbox_lite_server_mask", version='1.1.0')

# opencv输出中文
def paint_chinese(im, chinese, position, fontsize, color_bgr):
    # 图像从OpenCV格式转换成PIL格式
    img_PIL = Image.fromarray(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))
    font = ImageFont.truetype(
        'SourceHanSansSC-Medium.otf', fontsize, encoding="utf-8")
    #color = (255,0,0) # 字体颜色
    #position = (100,100)# 文字输出位置
    color = color_bgr[::-1]
    draw = ImageDraw.Draw(img_PIL)
    # PIL图片上打印汉字 # 参数1：打印坐标，参数2：文本，参数3：字体颜色，参数4：字体
    draw.text(position, chinese, font=font, fill=color)
    img = cv2.cvtColor(np.asarray(img_PIL), cv2.COLOR_RGB2BGR)  # PIL图片转cv2 图片
    return img


result_path = './result'
if not os.path.exists(result_path):
    os.mkdir(result_path)

name = "./result/1-mask_detection.mp4"
width = 1280
height = 720
fps = 30
#fourcc = cv2.VideoWriter_fourcc(*'vp90')
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
writer = cv2.VideoWriter(name, fourcc, fps, (width, height))

maskIndex = 0
index = 0
data = []

capture = cv2.VideoCapture(0)  # 打开摄像头
#capture = cv2.VideoCapture('./test_video.mp4')  # 打开视频文件
while True:
    frameData = {}
    ret, frame = capture.read()  # frame即视频的一帧数据
    if ret == False:
        break

    frame_copy = frame.copy()
    input_dict = {"data": [frame]}
    results = module.face_detection(data=input_dict)

    maskFrameDatas = []
    for result in results:
        label = result['data']['label']
        confidence_origin = result['data']['confidence']
        confidence = round(confidence_origin, 2)
        confidence_desc = str(confidence)

        top, right, bottom, left = int(result['data']['top']), int(
            result['data']['right']), int(result['data']['bottom']), int(
                result['data']['left'])
        if label == 'NO MASK':

            #将当前帧保存为图片
            img_name = "avatar_%d.png" % (maskIndex)
            path = "./result/" + img_name
            image = frame[top - 10:bottom + 10, left - 10:right + 10]
            cv2.imwrite(path, image, [int(cv2.IMWRITE_PNG_COMPRESSION), 9])

            maskFrameData = {}
            maskFrameData['top'] = top
            maskFrameData['right'] = right
            maskFrameData['bottom'] = bottom
            maskFrameData['left'] = left
            maskFrameData['confidence'] = float(confidence_origin)
            maskFrameData['label'] = label
            maskFrameData['img'] = img_name

            maskFrameDatas.append(maskFrameData)

            maskIndex += 1

        color = (0, 255, 0)
        label_cn = "有口罩"
        if label == 'NO MASK':
            color = (0, 0, 255)
            label_cn = "无口罩"

        cv2.rectangle(frame_copy, (left, top), (right, bottom), color, 3)
        cv2.putText(frame_copy, label, (left, top-10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2)
        origin_point = (left, top - 36)
        frame_copy = paint_chinese(frame_copy, label_cn, origin_point, 24,
                                   color)

    writer.write(frame_copy)

    cv2.imshow('Mask Detection', frame_copy)

    frameData['frame'] = index
    frameData['seconds'] = int(index/fps)
    frameData['data'] = maskFrameDatas

    data.append(frameData)
    print(json.dumps(frameData))

    index += 1

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

with open("./result/2-mask_detection.json", "w") as f:
    json.dump(data, f)

writer.release()

cv2.destroyAllWindows()

**Comment by xd905** [comment]
> @xd905 麻烦更新到最新的代码，应该是摄像头分辨率和默认的不一致，我们新增了自动识别视频分辨率。然后还新增了参数--open_imshow：是否对视频的检测结果实时绘图，默认为False

已经解决啦非常感谢

**Comment by yingxingdechibang** [comment]
> > @xd905 麻烦更新到最新的代码，应该是摄像头分辨率和默认的不一致，我们新增了自动识别视频分辨率。然后还新增了参数--open_imshow：是否对视频的检测结果实时绘图，默认为False
> 
> 已经解决啦非常感谢

类似的问题，求解决方法！
window10 运行mask_detection.py，读取示例视频文件test_video.mp4，代码运行，74行会报错，错误信息cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:715: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'，注释74行后，代码正常运行，视频编码方式采用mp4v，但生成result下的mp4视频打不开显示已损坏，并且只有1KB。

**Comment by Channingss** [comment]
@yingxingdechibang 麻烦贴一下注释的是哪一行代码，我这边看74行感觉不是你描述的。https://github.com/PaddlePaddle/PaddleHub/blob/9c0152e8cbc98a59c0ca0355915322a3c7db83ab/demo/mask_detection/mask_detection.py#L74，
