### ISSUE TITLE
请问文本分类有multi class classificaiton吗？

### ISSUE THREAD

**Issue by Yufei-Z** [PaddlePaddle/PaddleFormers#414]
现在貌似只能分成正面、负面，但很多时候至少还需要一个中性吧？

**Comment by kinghuin** [comment]
@Yufei-Z Hi，您指的的是多分类吗? text_classification支持多分类的，例如您可以将https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/demo/text_classification/text_classifier.py#L46 中的ChnSentiCorp替换为TNews即可得到这些新闻类别分类：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/paddlehub/dataset/tnews.py#L55
如果您需要多极性情感分类，只需按照教程https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/docs/tutorial/how_to_load_data.md 即可构建自己的数据集

**Comment by Yufei-Z** [comment]
谢谢！我想多极性情感分类，那是不是只需要在dataset = hub.dataset.ChnSentiCorp()之后，再比如说在dataset下面加几千行，其中label为0.5，text为中性文本就可以了？谢谢！然后我还想问一下有没有什么专门为股票设计的dataset呢？因为我想做舆情与股价关系的研究

**Comment by kinghuin** [comment]
您可以参考hub.dataset.ChnSentiCorp的源码非常方便地改写出自定义带有中性文本的数据集。关于股票数据集我没有了解到相关高质量数据集，欢迎向我们提供建议

**Comment by Yufei-Z** [comment]
抱歉我没有找到源码，您的意思是我直接修改chnsenticorp数据集吗？我在想可不可以读取数据集之后再在python里面增加几千行新的数据？

**Comment by Yufei-Z** [comment]
from paddlehub.dataset.base_nlp_dataset import BaseNLPDataset

class DemoDataset(BaseNLPDataset):
    """DemoDataset"""
    def __init__(self):
        # 数据集存放位置
        self.dataset_dir = "path/to/dataset"
        super(DemoDataset, self).__init__(
            base_path=self.dataset_dir,
            train_file="train.tsv",
            dev_file="dev.tsv",
            test_file="test.tsv",
            # 如果还有预测数据（不需要文本类别label），可以放在predict.tsv
            predict_file="predict.tsv",
            train_file_with_header=True,
            dev_file_with_header=True,
            test_file_with_header=True,
            predict_file_with_header=True,
            # 数据集类别集合
            label_list=["0", "1"])
dataset = DemoDataset()
您好，请问dev_file是什么呀？然后那个test——file有什么用，是训练的时候返回训练精度吗？可是我现在自己整理的数据集不够大诶，可以省去吗

**Comment by Yufei-Z** [comment]
那我打算整理出一个几千条的股吧或者雪球数据集，然后上传给你们？金融数据应该应用很多的

**Comment by kinghuin** [comment]
> 抱歉我没有找到源码，您的意思是我直接修改chnsenticorp数据集吗？我在想可不可以读取数据集之后再在python里面增加几千行新的数据？

chnsenticorp源码请见：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/paddlehub/dataset/chnsenticorp.py

您可以同时参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/paddlehub/dataset/chnsenticorp.py 与 https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/docs/tutorial/how_to_load_data.md 进行改写



> 您好，请问dev_file是什么呀？然后那个test——file有什么用，是训练的时候返回训练精度吗？可是我现在自己整理的数据集不够大诶，可以省去吗

可以省去的，dev_file和test_file分别是验证集与测试集，验证集在finetune过程中验证模型当前性能，测试集在finetune结束后测试最优模型性能。如果您要省去dev_file的话请不要使用finetune_and_eval接口而是使用finetune接口

如果您的数据集是有标签的，则可以根据 训练/验证/测试 的用途构建 train_file/dev_file/test_file，如果是无标签的则只能构建 predict_file

可以通过这种方式追加数据：

```python
class YouDatasetName(BaseNLPDataset):
    def __init__(self):
        base_path = 数据集文件夹路径
        super(YouDatasetName, self).__init__(
            base_path=base_path,
            train_file= 训练集文件名,
            dev_file= 验证集文件名,
            test_file= 测试集文件名,
            label_file=None,
            label_list= 标签列表,
        )
        chn = hub.dataset.ChnSentiCorp()
        self.chn_train_examples = chn.get_train_examples()
        self.chn_dev_examples = chn.get_dev_examples()
        self.chn_test_examples = chn.get_test_examples()

    def _read_file(self, input_file, phase=None):
        """Reads a tab separated value file."""
        # 请参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/docs/tutorial/how_to_load_data.md 编写加载自定义数据代码
        return examples

    def get_train_examples(self):
        # 通过覆盖父类方法，实现数据追加
        return self.train_examples + self.chn_train_examples

    def get_dev_examples(self):
        return self.dev_examples + self.chn_dev_examples

    def get_test_examples(self):
        return self.test_examples + self.chn_test_examples
```





> 那我打算整理出一个几千条的股吧或者雪球数据集，然后上传给你们？金融数据应该应用很多的

非常感谢并期待您的贡献，您可以将数据集发送给我们，也可以参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/docs/contribution/contri_pr.md 直接向我们提供PR成为直接贡献者，如有疑问可以加Q 656612149

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
