### ISSUE TITLE
cls_tasks.predcit数据格式？

### ISSUE THREAD

**Issue by Yufei-Z** [PaddlePaddle/PaddleFormers#415]
请问我有几千行文本，储存在Excel里面，pd.read_csv读取之后，传到这个方程里面去报错The length of input_text is out of handling, which must be 1 or 2!
我后来看了一下demo，发现里面data是一个嵌套list。请问一定要转换成嵌套list吗？

**Comment by kinghuin** [comment]
Hi，@Yufei-Z 。是的，如果您在主程序里直接写data的话是需要转成嵌套list，如果您希望用其它数据结构构建自己的predict_data，可以参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/docs/tutorial/how_to_load_data.md 先构建数据集再用get_predict_examples获取预测数据

**Comment by Yufei-Z** [comment]
哦哦那个load data的方法既包括load数据集也包括load预测文本是吗

**Comment by kinghuin** [comment]
load方法是load数据集文件的，包括预测数据集

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
