### ISSUE TITLE
在finetune_and_eval结束后，如何获取验证集和测试集Top1等各项指标

### ISSUE THREAD

**Issue by mrhan36** [PaddlePaddle/PaddleFormers#419]
【期望特性】 应用paddehub，在finetune_and_eval结束后，期望能通过task.property的方式获取验证集和测试集Top1，top5准确率，和F1值等各项指标。

【场景】：场景1. 如写论文需要相关指标，场景2. 训练完后想知道在验证集上和测试集上的各项指标，用来比较各种方法和参数的优劣。目前的API缺点是只在屏幕输出训练集，验证集和测试集的acc，不显示其他指标。而且，如果本地计算机关机后重启，或者关闭浏览器后再次进入Aistudio，屏幕上的训练结果也不会再出现。完全搞不清训练进度。

【目前情况】 目前仅可通过task.best_score可获取验证集最好准确率。功能非常有限。应用task._calculate_metrics(run_states)可获得acc和F1（不清楚是哪个数据集的指标），但无法分别获得各验证集和测试集的指标。

【建议方案】增加task.val_output和task.test_outpu属性，通过这两个属性返回对应数据集合的TOP1,TOP5,F1等指标。

**Comment by kinghuin** [comment]
Hi @mrhan36 
感谢您的建议，目前您可以通过hook的方式重写_default_eval_end_event事件函数
hook教程：https://github.com/PaddlePaddle/PaddleHub/wiki/%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9Task%E5%86%85%E7%BD%AE%E6%96%B9%E6%B3%95%EF%BC%9F

针对您的需求，如果是分类任务可以参考以下伪代码：
```python
import numpy as np

# 自定义评估方法实现
def calculate_metrics(self, run_states):
    # run_states: list类型，每个元素是一个RunState对象，指明了该step的运行状态
    all_labels = np.array([])
    all_infers = np.array([])
    for run_state in run_states:
        np_labels = run_state.run_results[0]
        np_infers = run_state.run_results[1]
        all_labels = np.hstack((all_labels, np_labels.reshape([-1])))
        all_infers = np.hstack((all_infers, np_infers.reshape([-1])))

    # 可以从这里开始自定义评估方法
    scores = OrderedDict()
    # 验证阶段
    if self.phase in ['dev', 'val']:
        scores["自定义指标名"] = 自定义计算方法(all_infers, all_labels)
    # 测试阶段
    elif self.phase == 'test':
        ....
    return scores

# 为eval_end_event创建新的handler
def new_eval_end_event(self, run_states):
    # 参数列表务必包含2个，一个为self，另一个用于接收运行状态
    scores = calculate_metrics(self, run_states)
    ##################################################
    # 在这里就可以将socres写到文件里头，这样就可以记录下来啦 #
    ##################################################
    # 判断并保存最优模型
    main_metric, main_value = list(scores.items())[0]
    if self.phase in ["dev", "val"] and main_value > self.best_score:
            self.best_score = main_value
            model_saved_dir = os.path.join(self.config.checkpoint_dir,
                                           "best_model")
            logger.eval("best model saved to %s [best %s=%.5f]" %
                        (model_saved_dir, main_metric, main_value))
            self.save_inference_model(dirname=model_saved_dir)

# 1.删除PaddleHub内置eval_end_event实现，如果不删除将先执行hub默认事件函数再执行您的自定义事件函数
# hook_type：您想要改写的事件hook类型
# name：hook名字，“default”表示PaddleHub内置_log_interval_event实现
task.delete_hook(hook_type="eval_end_event", name="default")

# 2.增加自定义eval_end_event实现
# hook_type：你想要改写的事件hook类型
# name: hook名字
# func：自定义改写的方法
task.add_hook(hook_type="eval_end_event", name="my_great_eval_end_event", func=new_eval_end_event)

task.finetune_and_eval()
```

**Comment by mrhan36** [comment]
好的，这就太好了，感谢您的耐心回答！非常感谢！

**Comment by mrhan36** [comment]
**您好，根据您的建议，重写写了代码，但遇到一点问题。
以下第1段是改写评估方法log_interval_event相关代码，这段代码运行正常**
**第2段代码结尾有明确错误提示，麻烦您看一下这种情况怎么解决，谢谢！**


**第1段代码**
-----------------------------------------------------------------------------
`import numpy as np

def calculate_f1_np(preds, labels):
    # 计算F1分数
    # preds：预测label
    # labels： 真实labels
    # 返回F1分数
    preds = np.array(preds)
    labels = np.array(labels)
    tp = np.sum((labels == 1) & (preds == 1))
    tn = np.sum((labels == 0) & (preds == 0))
    fp = np.sum((labels == 0) & (preds == 1))
    fn = np.sum((labels == 1) & (preds == 0))
    p = tp / (tp + fp) if (tp + fp) else 0
    r = tp / (tp + fn) if (tp + fn) else 0
    f1 = (2 * p * r) / (p + r) if p + r else 0
    return f1

# 自定义评估方法实现
def calculate_metrics(self, run_states):
    # run_states: list类型，每个元素是一个RunState对象，指明了该step的运行状态
    # 返回评估得分，平均损失值和平局运行速度
    loss_sum = acc_sum = run_examples = 0
    run_step = run_time_used = 0
    all_labels = np.array([])
    all_infers = np.array([])

    for run_state in run_states:
        run_examples += run_state.run_examples
        run_step += run_state.run_step
        loss_sum += np.mean(
            run_state.run_results[-1]) * run_state.run_examples
        acc_sum += np.mean(
            run_state.run_results[2]) * run_state.run_examples
        np_labels = run_state.run_results[0]
        np_infers = run_state.run_results[1]
        all_labels = np.hstack((all_labels, np_labels.reshape([-1])))
        all_infers = np.hstack((all_infers, np_infers.reshape([-1])))

    run_time_used = time.time() - run_states[0].run_time_begin
    avg_loss = loss_sum / run_examples
    run_speed = run_step / run_time_used

    scores = OrderedDict()
    f1 = calculate_f1_np(all_infers, all_labels)
    scores["f1"] = f1

    return scores, avg_loss, run_speed


# 改写_log_interval_event实现
def new_log_interval_event(self, run_states):
    # 改写的事件方法，参数列表务必与PaddleHub内置的相应方法保持一致
    print("This is the new log_interval_event!")
    scores, avg_loss, run_speed = calculate_metrics(run_states)

# 利用Hook改写PaddleHub内置_log_interval_event实现，需要2步(假设task已经创建好)
# 1.删除PaddleHub内置_log_interval_event实现
# hook_type：你想要改写的事件hook类型
# name：hook名字，“default”表示PaddleHub内置_log_interval_event实现
task.delete_hook(hook_type="log_interval_event", name="default")

# 2.增加自定义_log_interval_event实现(new_log_interval_event)
# hook_type：你想要改写的事件hook类型
# name: hook名字
# func：自定义改写的方法
task.add_hook(hook_type="log_interval_event", name="new_log_interval_event", func=new_log_interval_event)

# 输出hook信息
task.hooks_info`

**第2段代码**
**改写评估方法log_interval_event后，运行Fintune_and_eval出现的错误提示：**
-------------------------------------------------------------------------------------------------------
{'L2': 0.001, 'L2SP': 0.0, 'weight_decay': 0.0} and clip: {'GlobalNorm': 0.0, 'Norm': 0.0}
[2020-03-08 20:01:35,458] [    INFO] - Try loading checkpoint from cv_finetune/ckpt.meta
[2020-03-08 20:01:35,459] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-03-08 20:01:35,527] [    INFO] - PaddleHub finetune start
This is the new log_interval_event!
---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<ipython-input-10-083e1cd87b3f> in <module>
      1 t1=time.time()
      2 
----> 3 run_states = task.finetune_and_eval()
      4 
      5 t2=time.time()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    761 
    762     def finetune_and_eval(self):
--> 763         return self.finetune(do_eval=True)
    764 
    765     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    773                 while self.current_epoch <= self.config.num_epoch:
    774                     self.config.strategy.step()
--> 775                     run_states = self._run(do_eval=do_eval)
    776                     self.env.current_epoch += 1
    777 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
    826         with fluid.program_guard(self.main_program, self.startup_program):
    827             if self.config.use_pyreader:
--> 828                 return self._run_with_py_reader(do_eval=do_eval)
    829             return self._run_with_data_feeder(do_eval=do_eval)
    830 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run_with_py_reader(self, do_eval)
    920                     if self.is_train_phase:
    921                         if self.current_step % self.config.log_interval == 0:
--> 922                             self._log_interval_event(period_run_states)
    923                             global_run_states += period_run_states
    924                             period_run_states = []
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    580                     func(*args)
    581                 else:
--> 582                     partial(func, self)(*args)
    583 
    584         return hook_function
<ipython-input-9-cab5d75057a1> in new_log_interval_event(self, run_states)
     73     # 改写的事件方法，参数列表务必与PaddleHub内置的相应方法保持一致
     74     print("This is the new log_interval_event!")
---> 75     scores, avg_loss, run_speed = calculate_metrics(run_states)
     76     # record_value(scores, avg_loss, run_speed)
     77 
TypeError: calculate_metrics() missing 1 required positional argument: 'run_states'

**Comment by mrhan36** [comment]
###  **您好，根据您的建议，重写写了代码，但遇到一点问题。
### 以下第1段是改写calculate_metrics相关代码，这段代码运行正常**
### 以下第2段代码结尾有明确错误提示，麻烦您看一下这种情况怎么解决，
### 谢谢！


### **第1段代码**
-----------------------------------------------------------------------------
import numpy as np
from collections import OrderedDict 

def calculate_f1_np(preds, labels):
    preds = np.array(preds)
    labels = np.array(labels)
    tp = np.sum((labels == 1) & (preds == 1))
    tn = np.sum((labels == 0) & (preds == 0))
    fp = np.sum((labels == 0) & (preds == 1))
    fn = np.sum((labels == 1) & (preds == 0))
    p = tp / (tp + fp) if (tp + fp) else 0
    r = tp / (tp + fn) if (tp + fn) else 0
    f1 = (2 * p * r) / (p + r) if p + r else 0
    return f1

def calculate_metrics(self,run_states):
    all_labels = np.array([])
    all_infers = np.array([])
    for run_state in run_states:
        np_labels = run_state.run_results[0]
        np_infers = run_state.run_results[1]
        all_labels = np.hstack((all_labels, np_labels.reshape([-1])))
        all_infers = np.hstack((all_infers, np_infers.reshape([-1])))

    scores = OrderedDict()   
    if self.phase in ['dev', 'val']:
        scores["f1"] = calculate_f1_np(all_infers, all_labels)
    elif self.phase == 'test':
        scores["f2"] = calculate_f1_np(all_infers, all_labels)
    return scores

def new_eval_end_event(self, run_states):
    scores = calculate_metrics(run_states)
    main_value = scores["f1"]
    if self.phase in ["dev", "val"] and main_value > self.best_score:
            self.best_score = main_value
            model_saved_dir = os.path.join(self.config.checkpoint_dir,
                                           "best_model")
            logger.info("best model saved to %s [best %s=%.5f]" %
                        (model_saved_dir, "F1", main_value))
            self.save_inference_model(dirname=model_saved_dir)
task.delete_hook(hook_type="eval_end_event", name="default")
task.add_hook(hook_type="eval_end_event", name="my_great_eval_end_event", func=new_eval_end_event)

### **第2段代码**
### 运行Fintune_and_eval出现的错误提示：
### 调试发现是形参self引起的错误，但没搞清怎么修改，谢谢！

-------------------------------------------------------------------------------------------------------
[2020-03-09 13:50:56,962] [   TRAIN] - step 20 / 18: loss=0.43417 acc=0.85417 f1=0.95652 matthews=0.91879 [step/sec: 3.63]
[2020-03-09 13:50:56,967] [    INFO] - Evaluation on dev dataset start
2020-03-09 13:50:57,475-WARNING: paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
share_vars_from is set, scope is ignored.
---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<ipython-input-14-083e1cd87b3f> in <module>
      1 t1=time.time()
      2 
----> 3 run_states = task.finetune_and_eval()
      4 
      5 t2=time.time()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    761 
    762     def finetune_and_eval(self):
--> 763         return self.finetune(do_eval=True)
    764 
    765     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    778                 # Final evaluation
    779                 if self._base_data_reader.get_dev_examples() != []:
--> 780                     self.eval(phase="dev")
    781                 if self._base_data_reader.get_test_examples() != []:
    782                     self.eval(phase="test", load_best_model=True)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in eval(self, phase, load_best_model)
    798             self._eval_start_event()
    799             run_states = self._run()
--> 800             self._eval_end_event(run_states)
    801             return run_states
    802 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    580                     func(*args)
    581                 else:
--> 582                     partial(func, self)(*args)
    583 
    584         return hook_function
<ipython-input-13-cf9dbd633c48> in new_eval_end_event(self, run_states)
     42 def new_eval_end_event(self, run_states):
     43     # 参数列表务必包含2个，一个为self，另一个用于接收运行状态
---> 44     scores = calculate_metrics(run_states)
     45     ##################################################
     46     # 在这里就可以将socres写到文件里头，这样就可以记录下来啦 #
TypeError: calculate_metrics() missing 1 required positional argument: 'run_states'

**Comment by mrhan36** [comment]
> Hi @mrhan36
> 感谢您的建议，目前您可以通过hook的方式重写_default_eval_end_event事件函数
> hook教程：https://github.com/PaddlePaddle/PaddleHub/wiki/%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9Task%E5%86%85%E7%BD%AE%E6%96%B9%E6%B3%95%EF%BC%9F
> 
> 针对您的需求，如果是分类任务可以参考以下伪代码：
> 
> ```python
> import numpy as np
> 
> # 自定义评估方法实现
> def calculate_metrics(self, run_states):
>     # run_states: list类型，每个元素是一个RunState对象，指明了该step的运行状态
>     all_labels = np.array([])
>     all_infers = np.array([])
>     for run_state in run_states:
>         np_labels = run_state.run_results[0]
>         np_infers = run_state.run_results[1]
>         all_labels = np.hstack((all_labels, np_labels.reshape([-1])))
>         all_infers = np.hstack((all_infers, np_infers.reshape([-1])))
> 
>     # 可以从这里开始自定义评估方法
>     scores = OrderedDict()
>     # 验证阶段
>     if self.phase in ['dev', 'val']:
>         scores["自定义指标名"] = 自定义计算方法(all_infers, all_labels)
>     # 测试阶段
>     elif self.phase == 'test':
>         ....
>     return scores
> 
> # 为eval_end_event创建新的handler
> def new_eval_end_event(self, run_states):
>     # 参数列表务必包含2个，一个为self，另一个用于接收运行状态
>     scores = calculate_metrics(run_states)
>     ##################################################
>     # 在这里就可以将socres写到文件里头，这样就可以记录下来啦 #
>     ##################################################
>     # 判断并保存最优模型
>     main_value = scores[0]
>     if self.phase in ["dev", "val"] and main_value > self.best_score:
>             self.best_score = main_value
>             model_saved_dir = os.path.join(self.config.checkpoint_dir,
>                                            "best_model")
>             logger.eval("best model saved to %s [best %s=%.5f]" %
>                         (model_saved_dir, main_metric, main_value))
>             self.save_inference_model(dirname=model_saved_dir)
> 
> # 1.删除PaddleHub内置eval_end_event实现，如果不删除将先执行hub默认事件函数再执行您的自定义事件函数
> # hook_type：您想要改写的事件hook类型
> # name：hook名字，“default”表示PaddleHub内置_log_interval_event实现
> task.delete_hook(hook_type="eval_end_event", name="default")
> 
> # 2.增加自定义eval_end_event实现
> # hook_type：你想要改写的事件hook类型
> # name: hook名字
> # func：自定义改写的方法
> task.add_hook(hook_type="eval_end_event", name="my_great_eval_end_event", func=new_eval_end_event)
> 
> task.finetune_and_eval()
> ```

**您好，根据您的建议，重写写了代码，但遇到一点问题。
以下第1段是改写calculate_metrics相关代码，这段代码运行正常**
以下第2段代码结尾有明确错误提示，麻烦您看一下这种情况怎么解决，
谢谢！
第1段代码
import numpy as np
from collections import OrderedDict

def calculate_f1_np(preds, labels):
preds = np.array(preds)
labels = np.array(labels)
tp = np.sum((labels == 1) & (preds == 1))
tn = np.sum((labels == 0) & (preds == 0))
fp = np.sum((labels == 0) & (preds == 1))
fn = np.sum((labels == 1) & (preds == 0))
p = tp / (tp + fp) if (tp + fp) else 0
r = tp / (tp + fn) if (tp + fn) else 0
f1 = (2 * p * r) / (p + r) if p + r else 0
return f1

def calculate_metrics(self,run_states):
all_labels = np.array([])
all_infers = np.array([])
for run_state in run_states:
np_labels = run_state.run_results[0]
np_infers = run_state.run_results[1]
all_labels = np.hstack((all_labels, np_labels.reshape([-1])))
all_infers = np.hstack((all_infers, np_infers.reshape([-1])))

scores = OrderedDict()   
if self.phase in ['dev', 'val']:
    scores["f1"] = calculate_f1_np(all_infers, all_labels)
elif self.phase == 'test':
    scores["f2"] = calculate_f1_np(all_infers, all_labels)
return scores
def new_eval_end_event(self, run_states):
scores = calculate_metrics(run_states)
main_value = scores["f1"]
if self.phase in ["dev", "val"] and main_value > self.best_score:
self.best_score = main_value
model_saved_dir = os.path.join(self.config.checkpoint_dir,
"best_model")
logger.info("best model saved to %s [best %s=%.5f]" %
(model_saved_dir, "F1", main_value))
self.save_inference_model(dirname=model_saved_dir)
task.delete_hook(hook_type="eval_end_event", name="default")
task.add_hook(hook_type="eval_end_event", name="my_great_eval_end_event", func=new_eval_end_event)

第2段代码
运行Fintune_and_eval出现的错误提示：
调试发现是形参self引起的错误，但没搞清怎么修改，谢谢！
[2020-03-09 13:50:56,962] [ TRAIN] - step 20 / 18: loss=0.43417 acc=0.85417 f1=0.95652 matthews=0.91879 [step/sec: 3.63]
[2020-03-09 13:50:56,967] [ INFO] - Evaluation on dev dataset start
2020-03-09 13:50:57,475-WARNING: paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
share_vars_from is set, scope is ignored.
---------------------------------------------------------------------------TypeError Traceback (most recent call last) in
1 t1=time.time()
2
----> 3 run_states = task.finetune_and_eval()
4
5 t2=time.time()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
761
762 def finetune_and_eval(self):
--> 763 return self.finetune(do_eval=True)
764
765 def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
778 # Final evaluation
779 if self._base_data_reader.get_dev_examples() != []:
--> 780 self.eval(phase="dev")
781 if self._base_data_reader.get_test_examples() != []:
782 self.eval(phase="test", load_best_model=True)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in eval(self, phase, load_best_model)
798 self._eval_start_event()
799 run_states = self._run()
--> 800 self._eval_end_event(run_states)
801 return run_states
802
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
580 func(*args)
581 else:
--> 582 partial(func, self)(*args)
583
584 return hook_function
in new_eval_end_event(self, run_states)
42 def new_eval_end_event(self, run_states):
43 # 参数列表务必包含2个，一个为self，另一个用于接收运行状态
---> 44 scores = calculate_metrics(run_states)
45 ##################################################
46 # 在这里就可以将socres写到文件里头，这样就可以记录下来啦 #
TypeError: calculate_metrics() missing 1 required positional argument: 'run_states'

**Comment by kinghuin** [comment]
@mrhan36 感谢反馈
请在报错行多传一个self参数，scores = calculate_metrics(run_states) --> scores = calculate_metrics(self, run_states)

**Comment by mrhan36** [comment]
这个我也试过，提示一下错误：

   798             self._eval_start_event()
    799             run_states = self._run()
--> 800             self._eval_end_event(run_states)
    801             return run_states
    802 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    580                     func(*args)
    581                 else:
--> 582                     partial(func, self)(*args)
    583 
    584         return hook_function
<ipython-input-9-fded388de7ba> in new_eval_end_event(self, run_states)
     42 def new_eval_end_event(self, run_states):
     43     # 参数列表务必包含2个，一个为self，另一个用于接收运行状态
---> 44     scores = calculate_metrics(self,run_states)
     45     ##################################################
     46     # 在这里就可以将socres写到文件里头，这样就可以记录下来啦 #
TypeError: calculate_metrics() takes 1 positional argument but 2 were given

**Comment by kinghuin** [comment]
可以发下完整程序给我看一下吗？我这边测试是正常的

**Comment by mrhan36** [comment]
已解决，谢谢
