### ISSUE TITLE
关于finetune后输出结果的困惑

### ISSUE THREAD

**Issue by mrhan36** [PaddlePaddle/PaddleFormers#420]
对以下代码存在疑问：
在fintune and eval后，通过以下代码获取训练集，验证集和测试集的指标，但发现以下三段代码输出结果一样，请帮忙解答一下，谢谢！

**第一段：**
with task.phase_guard("train"):  #train:训练   val, test:评估  
    print(task.best_score)
    task.metrics_choices=["acc","f1","matthews"]
    eval_avg_score, eval_avg_loss, eval_run_speed = task._calculate_metrics(run_states)

**第2段：**
with task.phase_guard("val"):  #train:训练   val, test:评估  
    print(task.best_score)
    task.metrics_choices=["acc","f1","matthews"]
    eval_avg_score, eval_avg_loss, eval_run_speed = task._calculate_metrics(run_states)

**第3段：**
with task.phase_guard("test"):  #train:训练   val, test:评估  
    print(task.best_score)
    task.metrics_choices=["acc","f1","matthews"]
    eval_avg_score, eval_avg_loss, eval_run_speed = task._calculate_metrics(run_states)

非常感谢！

**Comment by Steffy-zxf** [comment]
感谢反馈！上述代码打印的best_score， 因为都是在验证集(val)上计算的best_score。即使task切换phase，如task.phase_guard("train")，打印出来的都是在验证集(val)上计算的best_score，所以输出结果是一样的。

**Comment by mrhan36** [comment]
好的，这就太好了，感谢您的耐心回答！非常感谢！
