### ISSUE TITLE
加载上一次的训练模型时出错

### ISSUE THREAD

**Issue by MiniMinyi** [PaddlePaddle/PaddleFormers#423]
第一次训练时没有问题，第二次训练时用了一样的checkpoint_dir，希望继续上次的训练过程，但出现如下错误。希望告知如何处理。谢谢！

![image](https://user-images.githubusercontent.com/13238342/76072029-34184c80-5fd2-11ea-86b2-708d27489c3b.png)

以下是版本信息和config的代码。

Paddle 版本
paddlehub==1.5.3
paddlepaddle-gpu==1.7.0.post107
tb-paddle==0.4.0

系统 Ubuntu, Python 3.6
CUDA Version: 10.2

config = hub.RunConfig(
    use_cuda=True,
    use_data_parallel=False,
    use_pyreader=False,
    enable_memory_optim=False,
    checkpoint_dir='checkpoint', //与上次训练一样，想重新继续上次的训练过程
    num_epoch=10,
    batch_size=32,
    log_interval=10,
    eval_interval=100,
    strategy=strategy)

欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by Steffy-zxf** [comment]
感谢反馈！两次训练是使用的优化策略strategy相同吗？

**Comment by MiniMinyi** [comment]
感谢回答，我是用一样的优化策略的。

**Comment by MiniMinyi** [comment]
请问是否能够提供如何恢复上次checkpoint继续训练的demo代码呢？我在该API看到可以save_parameter和save_checkpoints, https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub-API:-BaseTask 不知道哪一种可以恢复上次的训练。

**Comment by Steffy-zxf** [comment]
恢复checkpoint文件中的参数是通过 load_checkpoint()方法，具体实现参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.5/paddlehub/finetune/task/base_task.py#L728
上述报错，我先复现问题，之后给你回复。两次训练是完全一样的情况，只是区别在于恢复checkpoint文件出现错误是吗？你是训练什么任务呢？

**Comment by MiniMinyi** [comment]
我是训练句子对是否相似任务，类似lcqmc数据集，自定义了dataset，下面是训练代码。
CovidDataset是继承BaseDataset的自定义数据集。
```
from paddle.fluid.framework import switch_main_program
import paddlehub as hub
import paddle.fluid as fluid
import covid
import os

os.environ['LD_LIBRARY_PATH'] = '/usr/local/cuda/lib64'
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
os.environ["FLAGS_selected_gpus"] = "1"

dataset = covid.CovidDataset('data','train_no_dup.csv', 'dev_no_dup.csv')
module = hub.Module(name="ernie")
inputs, outputs, program = module.context(trainable=True, max_seq_len=128)

reader = hub.reader.ClassifyReader(
    dataset=dataset,
    vocab_path=module.get_vocab_path(),
    max_seq_len=128)

strategy = hub.AdamWeightDecayStrategy(
    weight_decay=0.01,
    warmup_proportion=0.1,
    learning_rate=5e-5,
    lr_scheduler="linear_decay",
    optimizer_name="adam")

config = hub.RunConfig(
    use_cuda=True,
    use_data_parallel=False,
    use_pyreader=False,
    enable_memory_optim=False,
    checkpoint_dir=None,
    num_epoch=11,
    batch_size=32,
    log_interval=10,
    eval_interval=100,
    strategy=strategy)

# Use "pooled_output" for classification tasks on an entire sentence.
pooled_output = outputs["pooled_output"]

feed_list = [
    inputs["input_ids"].name,
    inputs["position_ids"].name,
    inputs["segment_ids"].name,
    inputs["input_mask"].name,
]

cls_task = hub.TextClassifierTask(
    data_reader=reader,
    feature=pooled_output,
    feed_list=feed_list,
    num_classes=dataset.num_labels,
    config=config)

cls_task.finetune_and_eval()
```

**Comment by Steffy-zxf** [comment]
感谢反馈！查出来这是个bug，已经在 #427 修复该问题，稍后会发布1.5.4版本。请使用最新版本重新训练一遍，之后就可以从ckpt文件中恢复继续训练了

**Comment by Steffy-zxf** [comment]
@MiniMinyi PaddleHub 1.5.4 已经发版了。可以升级PaddleHub最新版本 
```shell
pip install --upgrade paddlehub
```

**Comment by MillionaireChen** [comment]
您好！我前几天才入门，可否告知如何从旧的checkpoint继续训练新的数据集，我之前用10W标签数据训练好了checkpoint，现在重新装载数据集90w ，希望从10W的模型处再继续，虽然没报错，但是好像没进行训练
![image](https://user-images.githubusercontent.com/35960345/76306066-398ed300-6301-11ea-80e9-fd116fa3f12b.png)

**Comment by MillionaireChen** [comment]
![image](https://user-images.githubusercontent.com/35960345/76306546-0e58b380-6302-11ea-94f6-61ab730135a6.png)

**Comment by Steffy-zxf** [comment]
@chenjinhua1993 你好，把你的训练epoch设置比第一次时候的epoch更大，这样就可以继续训练。现在应该是因为你的第二次训练epoch和batch_size和第一次一样，task经过计算，发现加载的step已经是结束训练的step，自然就不会继续训练。

**Comment by MillionaireChen** [comment]
好的，感谢回答！！

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
