### ISSUE TITLE
PaddleHub 口罩检测编译与运行出错。 Ubuntu18.04 C++CPU server预模型

### ISSUE THREAD

**Issue by fanxinkeji** [PaddlePaddle/PaddleFormers#425]
- 版本、环境信息
1）PaddleHub1.5和develop都试过；PaddlePaddle最新安装的，不知道版本。基本都是最新安装的，按照说明的版本，如opencv3.4.6
2）系统环境：Ubuntu18.04
bug可复现。
(3)
linux_build.sh:
![09428QKQM9M@PE$0%6)Z36H](https://user-images.githubusercontent.com/52989381/76135657-0da2f180-6064-11ea-966f-8cc5574503e9.png)
(4)
Ubuntu18.04，编译错误：LoadModel 怎么不认SetModel，mask_detector.cc与paddle_inference_api.h没对上，修改两边使用后编译过。 
![Y2{A)OBNPE(OC{%0{4XK{%X](https://user-images.githubusercontent.com/52989381/76135671-28756600-6064-11ea-8444-5c3ddfe3feda.png)

改paddle_inference_api.h如下
  // Set model with a directory.
  void SetModel(const std::string& model_dir) { model_dir_ = model_dir; }
  // Set model with two specific pathes for program and parameters.--比上我修改此处
  void SetModel(const std::string& prog_file_path,
                const std::string& params_file_path){
                prog_file_ = prog_file_path ;
                params_file_ = params_file_path ;
        }
或者改mask_detector.cc
 /*config.SetModel(model_dir + "/__model__", model_dir + "/__params__");//用这个改头文件试过，/编译能过，但均运行有错*/
  config.SetModel(model_dir ); //改这样用过，也能过，但运行也有错
------------------------------------------------------------------------------------------------------
运行出错，（顺便一提，结果不是readme的main，是在build目录下mask_detector)
![6B_IHYLG`UX~V2HRHX8(M2W](https://user-images.githubusercontent.com/52989381/76135709-899d3980-6064-11ea-98d1-75a0020b9369.png)

连发现少几个库，只截了一个图，libiomp5.so，libmklml_intel.so，libmkldnn.so.0 拷进/usr/lib去掉了错误。
![_$7PIRX`VBJ6H LBEH_KAFK](https://user-images.githubusercontent.com/52989381/76135579-134c0780-6063-11ea-9e33-547e790f6951.png)

但是最后还是有错：
![6%DT2 572@S5Z~@LW0CX~}H](https://user-images.githubusercontent.com/52989381/76135580-13e49e00-6063-11ea-9322-1e90f7fe2837.png)

**Comment by Channingss** [comment]
@fanxinkeji 请问g++的版本是多少，请使用4.8-4.9之间的g++版本

**Comment by fanxinkeji** [comment]
修改过gcc版本为4.8.5 make clean 后重新编译运行所描述所有错误依然存在。
![M2N~O)ZQWB(EFUL)WGG26WN](https://user-images.githubusercontent.com/52989381/76137050-7d6ca880-6073-11ea-83e3-d787a0871ac9.png)

**Comment by Channingss** [comment]
@fanxinkeji 把build文件夹里的东西全部删除吧。还不行的话，麻烦按照readme克隆一个新的仓库，包括依赖库也重新下载一遍。因为我们这边没办法复现出您描述的问题。

**Comment by fanxinkeji** [comment]
又重新按说明操作了一遍，用的release/v1.5，还是一样。
我这边git速度太慢，而且很多时候就直接挂掉了，我是直接从git下载zip后解压的。
麻烦确认一下readme中提供的C++预测库的下载链接是否最新的吧。
CPU+MKL版 | [fluid_inference.tgz](https://paddle-inference-lib.bj.bcebos.com/1.6.3-cpu-avx-mkl/fluid_inference.tgz)
![PJLAXEBEK1$V49GNS@BLL)6](https://user-images.githubusercontent.com/52989381/76140537-92a6fe80-6096-11ea-9e48-e439ba198003.png)
编译就不过，mask_detector.cc 的LoadModelSet调用config.SetModel出错，通过头文件paddle_analysis_config.h的。

paddle_analysis_config.h中定义 结构体AnalysisConfig明显对SetModel单路径双路径处理上不一致，双参数的SetModel没有直接更新prog_file_和params_file_，虽然不能表面证明有问题，如可能库里面有处理函数去更新了，但是编译器都说找不到，就确实值得怀疑了。麻烦确认一下。
  /** Set model with a directory.
   */
  void SetModel(const std::string& model_dir) { model_dir_ = model_dir; }
  /** Set model with two specific pathes for program and parameters.
   */
  void SetModel(const std::string& prog_file_path,
                const std::string& params_file_path);

 protected:
  // Model pathes.
  std::string model_dir_;
  mutable std::string prog_file_;
  mutable std::string params_file_;

**Comment by Channingss** [comment]
@fanxinkeji 看上去是编译的问题，我们这边查一下，另外，Paddle预测库的最新的版本可以参考下面这个链接
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html

**Comment by sjtubinlong** [comment]
@fanxinkeji 你好，建议不要直接修改预测库头文件中的代码。

这里报错的原因是你这边的cmake使用的gcc编译器，其中cxx是7.4版本，c是4.8.5，可以使用类似下列命令设置：

```
export CXX=/path/to/gcc4.8.5/bin/g++
export CC=/path/to/gcc4.8.5/bin/gcc
```

如果还有问题，可以发出来我们再看下

**Comment by fanxinkeji** [comment]
谢谢，却是我g++ 版本的问题！非常抱歉耽误你们时间了。

**Comment by fanxinkeji** [comment]
谢谢，却是我g++ 版本的问题！非常抱歉耽误你们时间了。
