### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by Liaid** [PaddlePaddle/PaddleFormers#428]
能否在基础上训练模型？比如通过自己训练的模型改变词法分析的结果

**Comment by Steffy-zxf** [comment]
能否背景信息说明更详细些？比如你想用什么module，怎么训练，什么任务？自己训练的模型是什么？以及 为什么你有这个需求？

**Comment by Liaid** [comment]
lac模块。PaddleNLP/lexical_analysis训练的模型能用于lac模块吗

**Comment by Steffy-zxf** [comment]
PaddleHub [lac module](https://www.paddlepaddle.org.cn/hubdetail?name=lac&en_category=LexicalAnalysis) 本质上就是PaddleNLP/lexical_analysis预训练模型。

**Comment by Liaid** [comment]
PaddleNLP/lexical_analysis训练的模型怎么在PaddleHub lac加载呢

**Comment by Steffy-zxf** [comment]
由于PaddleHub lac module 本质上就是PaddleNLP/lexical_analysis预训练模型，加载 lac module 就是加载PaddleNLP/lexical_analysis 预训练模型
```python
import paddlehub as hub

lac = hub.Module(name='lac')
```
如果你想继续finetune lac module， 现PaddleHub还无法完成这个功能。近期PaddleHub 以及 NLP module（其中包含lac module）会升级，支持lac finetune功能。

**Comment by Liaid** [comment]
谢谢回答
