### ISSUE TITLE
口罩识别多线程运行报错

### ISSUE THREAD

**Issue by taingload** [PaddlePaddle/PaddleFormers#429]
版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如
paddlehub 1.5.2
paddlepaddle 1.6.3
2）系统环境：centos7请您描述系统类型，例如Linux/Windows/MacOS/，python版本
复现信息：
如为报错，请给出复现环境、复现步骤
复现环境，python调用摄像头不断读帧，将图像进行图像检测face_detection
input_dict={"data":[frame]}
错误追踪：
var @HUB_pyramidbox_lite_mobile@image not in this blockNone
Traceback (most recent call last):
File "/root/oeworkspace/kouzhao/kzvideo5.py", line 155, in startpushstream
results = module.face_detection(data=input_dict)
File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/module.py", line 537, in call
reader, feeder = _get_reader_and_feeder(data_format, data, place)
File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/module.py", line 510, in _get_reader_and_feeder
feeder = fluid.DataFeeder(feed_list=feed_name_list, place=place)
File "/usr/local/python3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 262, in init
each_var = program.block(0).var(each_var)
File "/usr/local/python3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2263, in var
raise ValueError("var %s not in this block" % name)
ValueError: var @HUB_pyramidbox_lite_mobile_mask@image not in this block

**Comment by nepeplwu** [comment]
@taingload  感谢反馈，请问大概跑了多久出现的？

**Comment by taingload** [comment]
> @taingload 感谢反馈，请问大概跑了多久出现的？

大概几分钟就会有错误提示

**Comment by nepeplwu** [comment]
@taingload 我们这边试了并未复现你所说的情况，是否方便提供下你的调用脚本？

**Comment by taingload** [comment]
这是kzvideo5.py
`# -*- coding:UTF-8 -*-
from PIL import Image, ImageFont, ImageDraw
import numpy as np
def draw_img(image, boxes, titles):
    '''
    left,top,width,height
    '''
    for i in range(0, len(boxes)):
        rects = boxes[i]
        # draw_image
        left = rects[0]
        top = rects[1]
        width = rects[2]
        height = rects[3]
        right = left + width
        bottom = top + height
        image = draw_image(image, titles[i], [left, top, right, bottom])
    return image


def draw_image(img_OpenCV, label, box):
    # 将opencv图像格式转换成PIL格式, 数据类型是PIL.Image.Image
    image = Image.fromarray(cv2.cvtColor(img_OpenCV, cv2.COLOR_BGR2RGB))
    #DejaVuSans.ttf
    # font = ImageFont.truetype(font='Fonts//msyhl.ttc',size=np.floor(3e-2 * image.size[1] + 0.5).astype('int32'))
    font = ImageFont.truetype(font='DejaVuSans.ttf', size=20)
    draw = ImageDraw.Draw(image)
    label_size = draw.textsize(label, font)

    left, top, right, bottom = box
    top = max(0, np.floor(top + 0.5).astype('int32'))
    left = max(0, np.floor(left + 0.5).astype('int32'))
    bottom = min(image.size[1], np.floor(bottom + 0.5).astype('int32'))
    right = min(image.size[0], np.floor(right + 0.5).astype('int32'))
    print(label, (left, top), (right, bottom))

    if top - label_size[1] >= 0:
        text_origin = np.array([left, top - label_size[1]])
    else:
        text_origin = np.array([left, top + 1])
    #text_origin = np.array([left + label_size[0] / 2, top - label_size[1] / 2])
    # My kingdom for a good redistributable image drawing library.
    # for i in range(thickness):
    #    draw.rectangle([left + i, top + i, right - i, bottom - i],outline=self.colors[c])
    draw.rectangle(box, outline='red')

    #draw.rectangle([tuple(text_origin), tuple(text_origin + label_size)], fill=(0, 255, 0))
    draw.text(text_origin, label, fill=(255, 0, 0), font=font)
    del draw
    # 转换回OpenCV格式
    img_OpenCV = cv2.cvtColor(np.asarray(image), cv2.COLOR_RGB2BGR)

    return img_OpenCV

#sys.path.append('/usr/local/lib/python3.7/site-packages')
import logging

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s',
                    datefmt='%a, %d %b %Y %H:%M:%S')

logger = logging.getLogger(__name__)
logger.setLevel(level = logging.INFO)
handler = logging.FileHandler("log_camera5.txt")
handler.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s')
handler.setFormatter(formatter)

console = logging.StreamHandler()
console.setLevel(logging.INFO)

logger.addHandler(handler)
logger.addHandler(console)

import os
import cv2
import subprocess as sp
import numpy as np
import queue
import threading
import time
import random

currentcamera=""


def startpushstream(module):
    #devicename="门口"
    rtmpUrl = "rtmp://127.0.0.1:8089/live/livestream2"
    cap = cv2.VideoCapture(0)
    
    # Get video information
    #fps = int(cap.get(cv2.CAP_PROP_FPS))
    #width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    #height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    
    fps = 40
    width = 800
    height = 600
    #currentcamera=""
    
    command = ['ffmpeg',
            '-y',
            '-f', 'rawvideo',
            '-vcodec', 'rawvideo',
            '-pix_fmt', 'bgr24',
            '-s', "{}x{}".format(width, height),
            '-r', str(fps),
            '-i', '-', 
            '-loglevel','info',
            '-progress','ffmpeg-python.log',
            '-c:v', 'libx264',
            '-pix_fmt', 'yuv420p',
            '-preset', 'ultrafast',
            '-f', 'flv',           
            rtmpUrl]
    ffmpegpipe = sp.Popen(command, stdin=sp.PIPE)
    
    print("start")
    boxes = []
    titles = []
    results=""
    i=1
    while(cap.isOpened()):
        try:
            #print(1)
            ret, frame = cap.read()
            if not ret:
                print("Opening camera is failed")
                cap = cv2.VideoCapture(rtspurl)
                continue
            try:
                start=time.time()
                frame = cv2.resize(frame,(int(800),int(600)))
                input_dict = {"data": [frame]}
                i=i+1
                if i%20==0:
                    i=1
                    # execute predict and print the result
                    results = module.face_detection(data=input_dict)
                    boxes=[]
                    titles = []
                    nomasknum=0
                    for result in results:
                        # 'left': 312.0999264717102, 'right': 395.90114295482635, 'top': 419.92909812927246, 'bottom': 527.7651309967041, 'confidence': 0.9701634}
                        width = result['data']['right'] - result['data']['left']
                        height = result['data']['bottom']-result['data']['top']
                        boxes.append([result['data']['left'], result['data']['top'], width, height])
                        
                        maskstr=result['data']["label"];
                        mask_conf=float('%.03f'%result['data']["confidence"])
                        if  maskstr=="NO MASK" and mask_conf>0.6:
                            nomasknum=nomasknum+1
                        titles.append("{0}:{1}".format(maskstr,mask_conf))
                    
                    if nomasknum>0:
                        frame = draw_img(frame, boxes, titles)
                        frame = cv2.resize(frame,(800,600))
                        photodir="NoKouZhaoPhoto"
                        if not os.path.exists(photodir):
                            os.mkdir(photodir)
                        date_str=time.strftime("%Y-%m-%d", time.localtime()) 
                        second_str=time.strftime("%Y-%m-%d_%H_%M_%S", time.localtime())
                        if not os.path.exists(photodir+"/"+date_str):
                            os.mkdir(photodir+"/"+date_str)
                        p_path=photodir+"/"+date_str+"/"+second_str+".jpg"
                        cv2.imwrite(p_path,frame)
                        global currentcamera
                        currentcamera=str(nomasknum)
                        print(currentcamera)
                        logger.info("{0} Person WithOut NoMask".format(str(nomasknum))) 
                frame = draw_img(frame, boxes, titles)
                frame = cv2.resize(frame,(800,600))
                # write to pipe
                ffmpegpipe.stdin.write(frame.tostring())
                
                if cv2.waitKey(1)&0xff == ord('q'):
                    isPlay=False
                    break;
                #logger.info("result_dict:%s", results)
                #logger.info("all time cost :%s", str(time.time() - start))
            except Exception as e:
                # 管道配置
                ri=int(random.random()*10000)
                if not os.path.exists("Error_Image"):
                    os.mkdir("Error_Image")
                if not os.path.exists("Error_Image/5"):
                    os.mkdir("Error_Image/5")
                cv2.imwrite("Error_Image/5/image-error-"+str(ri)+".jpg",frame)
                module = hub.Module(name="pyramidbox_lite_mobile_mask")
                logger.info("ffmpeg GetError By My Server:%s",str(e))
                time.sleep(1)
        except Exception as e:
            cap = cv2.VideoCapture(rtspurl)
            logger.info("Video Capture Error,%s",str(e))
def GetCurrentResult():
    #返回当前状况
    return currentcamera;
`
kzvideo.py和kzvideo一样，只是取视频流的地方不一样


这是用线程转发视频流的WebServer.py

`# coding:utf-8
# !/usr/bin/env python

from io import StringIO,BytesIO
import sys
import random
import logging
import kzvideo6 as kouzhao6
import kzvideo5 as kouzhao5

import json
import cv2
import paddlehub as hub
define("port", default=9012, type=int)
#module = hub.Module(name="pyramidbox_lite_mobile_mask")
module=hub.Module(name="pyramidbox_lite_server_mask")

#kouzhao6.startpushstream()
import threading 
def startstream6():
    kouzhao6.startpushstream(module)
def startstream5():
    kouzhao5.startpushstream(module)


if __name__ == '__main__':
    threading.Thread(target=startstream5,args=[]).start()
    threading.Thread(target=startstream6,args=[]).start()
    
    print("Service Start")
`


在运行之后会出现题中的错误

**Comment by taingload** [comment]
![百度口罩](https://user-images.githubusercontent.com/15126847/76323671-f859eb80-631f-11ea-80e0-c7125390de76.png)
这是错误截图。
Traceback (most recent call last):
  File "/root/oeworkspace/kouzhao/kzvideo5.py", line 155, in startpushstream
    results = module.face_detection(data=input_dict)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/module.py", line 535, in __call__
    sign_name=sign_name, data_dict=data)
  File "/root/.paddlehub/modules/pyramidbox_lite_server_mask/python/cf9ee187a84d0ce118fb4d633b34e28b.py", line 152, in preprocess
    for data_id, det_result in enumerate(self.face_detector.face_detection(data=data_dict, visualization=False, use_gpu=use_gpu, batch_size=batch_size)):
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/module.py", line 549, in __call__
    sub_data, **kwargs)
  File "/root/.paddlehub/modules/pyramidbox_lite_server/python/d45c09d5b70815d2f99c3c6d8a60f1d0.py", line 121, in postprocess
    lod = lod_tensor.lod()[0]
IndexError: list index out of range
ffmpeg GetError By My Server:list index out of rangeNone
Tue, 10 Mar 2020 22:32:53 kzvideo5.py[line:213] INFO ffmpeg GetError By My Server:list index out of rangeNone
Traceback (most recent call last):
  File "/root/oeworkspace/kouzhao/kzvideo6.py", line 152, in startpushstream
    results = module.face_detection(data=input_dict)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/module.py", line 549, in __call__
    sub_data, **kwargs)
  File "/root/.paddlehub/modules/pyramidbox_lite_server_mask/python/cf9ee187a84d0ce118fb4d633b34e28b.py", line 181, in postprocess
    if data_out[0][index].shape[0] == 2:
IndexError: list index out of range
ffmpeg GetError By My Server:list index out of range,None
Tue, 10 Mar 2020 22:32:53 kzvideo6.py[line:213] INFO ffmpeg GetError By My Server:list index out of range,None
我想请问一下这个错误是什么原因？

**Comment by nepeplwu** [comment]
@taingload 应该是多线程导致的，paddle并不支持多线程预测，建议换为启动多个进程的方式处理

**Comment by MimeZoe0628** [comment]
@nepeplwu paddle不支持多线程预测， 请问那支持多线程训练吗？

**Comment by nepeplwu** [comment]
@MimeZoe0628 ，不支持多线程训练。但是在GPU多卡或者CPU多核的情况下是可以并行训练的
