### ISSUE TITLE
关于图像分类里的预测presict.py

### ISSUE THREAD

**Issue by chaogehah** [PaddlePaddle/PaddleFormers#431]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

我在运行最后predict.py后，只对测试图片进行了分类，可是我想要得到每一个图片对应的那类的概率是多少，请问我需要在代码中进行怎样的修改呢，希望说的具体一些，谢谢

**Comment by Steffy-zxf** [comment]
感谢反馈！ ImageClassifierTask中的preidct接口返回的是 输入数据的预测结果，如果你想拿到预测结果类别概率，参考以下代码
```python
run_states = task.predict(data=data)
results = [run_state.run_results for run_state in run_states]
for batch_result in results:
    for result in batch_results:
        print(result)
```
其中result就是对应输入数据的类别概率
