### ISSUE TITLE
针对客流密集，环境复杂的场景，希望能参与finetune，才是解决问题的王道

### ISSUE THREAD

**Issue by DavidFangx** [PaddlePaddle/PaddleFormers#432]
应用场景：农贸市场，实时监测未佩戴口罩人群，实时预警。
问题现状：农贸市场客流密集，同时商品品种众多，我们需要全方位、多角落实时监测未佩戴口罩人群，监测半个月以来，目前效果没有达不到预警。经常把手，苹果，土豆等商品当作人脸监测出来，而且错误率还偏高，同时侧脸误报率也偏高，戴了口罩识别出未戴口罩，我们按官网建议对 （版本：1.1.0）
 face_detection(data=input_dict, shrink=1,use_multi_scale=True)  调参，其中对shrink，use_multi_scale 做了多次尝试调参，都有没有达到预期效果，目前很苦恼，很被动.,....
建议：希望 pyramidbox_lite_server_mask 和  pyramidbox_lite_mobile_mask 模型支持finetune,让我们也一起参与训练完善模型，如此，才能解决实际中面临的各种场景问题。

望采纳， 谢谢！

**Comment by adaxiadaxi** [comment]
@DavidFangx hi，同学你好哈~感谢你这边的建议。目前当下您可以做的事情：
1.先使用1.2.0的模型，这个我们已经上线了：https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_server_mask&en_category=ObjectDetection 可以查看下载最新的sever端模型，并且我们在口罩检测中还有两个接口可以调试效果pyramidbox_lite_mobile_mask.processor.set_face_confidence_threshold(0.9)
pyramidbox_lite_mobile_mask.processor.set_multi_scales([0.5, 0.8])
第一个方法用于设置人脸检测的置信度，置信值应该位于0 ~ 1之间，默认为0.5， 设置得更高，就可以避免误检人脸的情况（但是可能会导致漏检）
第二个方法用于设置多尺度检测时的尺度值，默认为[0.3, 0.6, 0.9]

**Comment by adaxiadaxi** [comment]
@DavidFangx hi，同学你好哈~感谢你这边的建议。目前当下您可以做的事情：
1.先使用1.2.0的模型，这个我们已经上线了：https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_server_mask&en_category=ObjectDetection 可以查看下载最新的sever端模型，并且我们在口罩检测中还有两个接口可以调试效果pyramidbox_lite_mobile_mask.processor.set_face_confidence_threshold(0.9)
pyramidbox_lite_mobile_mask.processor.set_multi_scales([0.5, 0.8])
第一个方法用于设置人脸检测的置信度，置信值应该位于0 ~ 1之间，默认为0.5， 设置得更高，就可以避免误检人脸的情况（但是可能会导致漏检）
第二个方法用于设置多尺度检测时的尺度值，默认为[0.3, 0.6, 0.9]

2.你这边如果还有很多bad cases可以统一收录给我们（原图和bad cases结果图片），我们推动后续的模型更新

3.对于finetune这块，目前我们的口罩检测分两阶段，人脸检测和口罩分类，优先要做的也是分类的finetune，这一块你可以关注下hub官网或者是社群，有信息会同步出来的
