### ISSUE TITLE
hub serving 离线部署

### ISSUE THREAD

**Issue by YasinZhao** [PaddlePaddle/PaddleFormers#438]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

版本、环境信息如下：
1、PaddleHub1.5.3 PaddlePaddle1.7.0
2、Linux系统，python3.6
你好，请问hub serving支持离线部署吗，口罩检测模型已经下载到本地/root/.paddlehub/modules/pyramidbox_lite_server_mask，但启动时报错
![image](https://user-images.githubusercontent.com/16828608/76375496-ef4d3680-6380-11ea-8824-74e8f54cd058.png)

**Comment by ShenYuhan** [comment]
您好 支持离线部署，但是这个口罩模型依赖于pyramidbox_lite_server模型，请问您一起下载了吗

**Comment by YasinZhao** [comment]
> 您好 支持离线部署，但是这个口罩模型依赖于pyramidbox_lite_server模型，请问您一起下载了吗

你好，谢谢提醒，我真没下载。。。

**Comment by YasinZhao** [comment]
你好下载pyramidbox_lite_server_mask正常，但下载pyramidbox_lite_server时报错，请问是什么原因

![image](https://user-images.githubusercontent.com/16828608/76377982-33dbd080-6387-11ea-8a9e-f2b82af1472d.png)

**Comment by ShenYuhan** [comment]
您可以尝试先将paddlehub升级到最新版，然后执行hub clear清理缓存，再重新进行下载，看看是否还有问题。

**Comment by YasinZhao** [comment]
> 您可以尝试先将paddlehub升级到最新版，然后执行hub clear清理缓存，再重新进行下载，看看是否还有问题。

你好，按照你说的方法已经解决，非常感谢~
