### ISSUE TITLE
关于用户自定义词典

### ISSUE THREAD

**Issue by Liaid** [PaddlePaddle/PaddleFormers#439]
用户自定义词典中，是否可以增加除现有词性以外的词性？如果有怎么添加新词性标签？

**Comment by Steffy-zxf** [comment]
感谢反馈！PaddleHub lac module已经是完成了预训练的模型，没有办法增加除lac现有词性以外的词性。如果你想增加词性，只能根据[lac训练说明](https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/lexical_analysis#%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83)重头再训一个新的模型。

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
