### ISSUE TITLE
关于自己训练（非官方的预训练模型）的模型部署问题

### ISSUE THREAD

**Issue by ClassmateXiaoyu** [PaddlePaddle/PaddleFormers#444]
数据集是自定义的，训练出来的模型是否可以通过paddlehub serving进行发布？

**Comment by Steffy-zxf** [comment]
感谢反馈！
1. 你的模型是怎么训练的呢，利用PaddleHub 提供的预训练模型结合自定义数据集进而通过PaddleHub Fine-tune API 训练得到的模型吗？

2. 你是想向PaddleHub贡献一个模型吗？通过PaddleHub Serving公开给其他用户使用吗？

**Comment by ClassmateXiaoyu** [comment]
你好，问题1答复：我的模型是自己用Python通过paddlepaddle训练的，没有采用PaddleHub Fine-tune API这个方式。 数据集是自己收集的，进行了预处理后构建了reader进一步划分了训练集和测试集；问题2答复：目前是已经训练了一个模型出来了，能否用PaddleHub Serving进行部署，我这个是为自己公司的项目使用，暂时不公开。

**Comment by Steffy-zxf** [comment]
根据以上情况，可以使用即将发版的PaddleHub 1.6.0版本， 代码实现 https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.6

利用PaddleHub release/v1.6分支代码，将训练好的模型转化为一个module，这样就可以使用PaddleHub Serving部署。具体如何创建module 参考https://github.com/nepeplwu/HubModule/tree/master/modules/demo  这个repo下 还有其他module创建的示例代码，比如lac，senta等模型

**Comment by ClassmateXiaoyu** [comment]
好的，感谢答疑。我昨天刚把hub更新到了1.5.4，paddlepaddle更新到了1.7.1，我马上用上述的方法试一下。

**Comment by Steffy-zxf** [comment]
PaddleHub 需要用 1.6.0 版本（也就是 https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.6 这个分支代码），1.5.4版本不行。

**Comment by ClassmateXiaoyu** [comment]
你好，请问在线方式如何更新到1.6.0？昨天用的pip install -upgrade paddlehub更新的，更新完后是1.5.4

**Comment by Steffy-zxf** [comment]
1.6.0版本还在测试中，还未正式发版。使用PaddleHub repo release/v1.6分支代码 https://github.com/PaddlePaddle/PaddleHub
 
```shell
$ git clone https://github.com/PaddlePaddle/PaddleHub.git
$ git checkout release/v1.6
$ python setup.py install
```

**Comment by ClassmateXiaoyu** [comment]
好的，多谢，明白了。

**Comment by DeIn221** [comment]
> 感谢反馈！
> 
> 1. 你的模型是怎么训练的呢，利用PaddleHub 提供的预训练模型结合自定义数据集进而通过PaddleHub Fine-tune API 训练得到的模型吗？
> 2. 你是想向PaddleHub贡献一个模型吗？通过PaddleHub Serving公开给其他用户使用吗？

我想请问下我利用PaddleHub提供的预训练模型结合自定义数据集通过PaddleHub Fine-tune API训练得到的模型如何部署呢

**Comment by Steffy-zxf** [comment]
@DeIn221 同样你需要将Fine-tune之后的模型转化成一个module，并且需要调用的预测接口加上serving修饰符，参考https://github.com/Steffy-zxf/HubModule/blob/master/modules/text/lexical_analysis/lac/module.py#L211
同样，你也需要使用PaddleHub 即将发版的 1.6.0（也就是 https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.6 这个分支代码）。
如何使用分支代码，参考上述回答。

**Comment by DeIn221** [comment]
> @DeIn221 同样你需要将Fine-tune之后的模型转化成一个module，并且需要调用的预测接口加上serving修饰符，参考https://github.com/Steffy-zxf/HubModule/blob/master/modules/text/lexical_analysis/lac/module.py#L211
> 同样，你也需要使用PaddleHub 即将发版的 1.6.0（也就是 https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.6 这个分支代码）。
> 如何使用分支代码，参考上述回答。

谢谢
