### ISSUE TITLE
Mac安装paddlehub之后，无法使用命令行工具

### ISSUE THREAD

**Issue by pepeshen** [PaddlePaddle/PaddleFormers#446]
-bash: hub: command not found

**Comment by Steffy-zxf** [comment]
你好！请检查运行PaddleHub的环境是否安装PaddleHub
```shell
$ pip show paddlehub
```

**Comment by MrNullPoint** [comment]
pip3 显示安装了 PaddleHub 但是 hub 命令确实没有

<img width="752" alt="截屏2020-04-01 下午5 38 41" src="https://user-images.githubusercontent.com/27116075/78122836-e27fa800-743f-11ea-97a2-abb286591fa0.png">

**Comment by Steffy-zxf** [comment]
你看下这里的相应解决方法。https://www.jianshu.com/p/bba968ca3957

**Comment by ZhaoUncle** [comment]
@MrNullPoint 能解决吗，我都找不到 hub 的 bin/路径，即便全局find，请问你如何解决的，在 mac 上

**Comment by livingbody** [comment]
能



---原始邮件---
发件人: "ZhaoUncle"<notifications@github.com&gt;
发送时间: 2020年8月25日(周二) 下午2:12
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleHub] Mac安装paddlehub之后，无法使用命令行工具 (#446)




 
@MrNullPoint 能解决吗，我都找不到 hub 的 bin/路径，即便全局find，请问你如何解决的，在 mac 上

**Comment by ZhaoUncle** [comment]
能说一下解决方案？
