### ISSUE TITLE
动态图如何实现?

### ISSUE THREAD

**Issue by Quan-zzx** [PaddlePaddle/PaddleFormers#449]
请问下如何在动态图里添加预训练模型参数

**Comment by Steffy-zxf** [comment]
你好！PaddleHub目前不支持动态图，关于动态图的问题，可以在 PaddlePaddle repo下提问https://github.com/PaddlePaddle/Paddle/issues

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
