### ISSUE TITLE
hub serving API接口支持直接base64编码的图片入参吗

### ISSUE THREAD

**Issue by YasinZhao** [PaddlePaddle/PaddleFormers#452]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

你好，目前我利用hub serving 能力部署了贵司开源的pyramidbox_lite_server模型，入参的是图片路径，我想请问hub serving API接口能否支持前端传输过来的以base64编码的图片直接入参，如果可以我需要修改hub serving 中哪些部分，还不太懂flask，希望能给予帮助，谢谢~

**Comment by ShenYuhan** [comment]
您好，Hub Serving是支持直接传base64编码的
参考这个demo方式，以此种post的信息格式请求即可https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/demo/serving/module_serving/object_detection_pyramidbox_lite_server_mask/pyramidbox_lite_server_mask_serving_demo.py

**Comment by YasinZhao** [comment]
> 您好，Hub Serving是支持直接传base64编码的
> 参考这个demo方式，以此种post的信息格式请求即可https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/demo/serving/module_serving/object_detection_pyramidbox_lite_server_mask/pyramidbox_lite_server_mask_serving_demo.py

老师你好，我按照你说的这个，pyramidbox_lite_server_mask模型确实可行，但是pyramidbox_lite_server还是不行，代码里我只修改了url为对应模型，其他没有变动，错误如下：
![image](https://user-images.githubusercontent.com/16828608/76842272-f2f72680-6874-11ea-822f-3ec8105d5d4b.png)

**Comment by ShenYuhan** [comment]
首先，您部署pyramidbox_lite_server模型了吗？您可以打印返回的json()出来看看是什么信息

**Comment by YasinZhao** [comment]
> 首先，您部署pyramidbox_lite_server模型了吗？您可以打印返回的json()出来看看是什么信息

老师你好，模型确定部署过了，下图是按图片路径得到的结果，是正常的
![image](https://user-images.githubusercontent.com/16828608/76914769-41003e80-68f6-11ea-823f-6dbd1c0d5803.png)

在按照pyramidbox_lite_server_mask_serving_demo.py方式时，就报如下错误：
<Response [500]>
Traceback (most recent call last):
  File "pyramidbox_lite_server_serving_demo.py", line 26, in <module>
    print(r.json()["results"])
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

服务器返回的是<Response [500]>，我也把开启服务端的结果记录了，如下：
2020-03-18 08:57:41,484-ERROR: Exception on /predict/image/pyramidbox_lite_server [POST]
Traceback (most recent call last):
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/serving/app_single.py", line 369, in predict_image
    extra_info)
  File "/home/zhaoyi-036/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlehub/serving/app_single.py", line 224, in predict_object_detection
    for index in range(len(input_img)):
TypeError: object of type 'NoneType' has no len()

**Comment by ShenYuhan** [comment]
麻烦您提供下测试的脚本，另外我确认一点，是否是 pyramidbox_lite_server_mask 可行，pyramidbox_lite_server不行？后者不是口罩检测模型，是人脸检测模型

**Comment by YasinZhao** [comment]
> 麻烦您提供下测试的脚本，另外我确认一点，是否是 pyramidbox_lite_server_mask 可行，pyramidbox_lite_server不行？后者不是口罩检测模型，是人脸检测模型

好的老师，辛苦你了，测试脚本如下：
# coding: utf8
import requests
import json
import base64

if __name__ == "__main__":
    # 获取第一张图片文件的base64编码
    with open(file="../../../../docs/imgs/man.png", mode="rb") as fp:
        base64_data1 = base64.b64encode(fp.read())
    base64_data1 = str(base64_data1, encoding="utf8")
    # 获取第二张图片文件的base64编码
    with open(file="../../../../docs/imgs/woman.png", mode="rb") as fp:
        base64_data2 = base64.b64encode(fp.read())
    base64_data2 = str(base64_data2, encoding="utf8")

    data = {"b64s": [base64_data1, base64_data2]}
    data = {"data": json.dumps(data)}
    # print(str(type(data)))
    # print(data)

    # 指定检测方法为pyramidbox_lite_server并发送post请求
    url = "http://127.0.0.1:8866/predict/image/pyramidbox_lite_server"
    r = requests.post(url=url, data=data)
    print(r)
    print(r.json()["results"])

    # 得到并打印检测结果
    results = eval(r.json()["results"])
    print(results)

    print(json.dumps(results, indent=4, ensure_ascii=False))

其实，就是只修改了pyramidbox_lite_server_mask_serving_demo.py中的url路径中模型，其他未变。

**Comment by YasinZhao** [comment]
> > 麻烦您提供下测试的脚本，另外我确认一点，是否是 pyramidbox_lite_server_mask 可行，pyramidbox_lite_server不行？后者不是口罩检测模型，是人脸检测模型
> 
> 好的老师，辛苦你了，测试脚本如下：
> 
> # coding: utf8
> import requests
> import json
> import base64
> 
> if **name** == "**main**":
> # 获取第一张图片文件的base64编码
> with open(file="../../../../docs/imgs/man.png", mode="rb") as fp:
> base64_data1 = base64.b64encode(fp.read())
> base64_data1 = str(base64_data1, encoding="utf8")
> # 获取第二张图片文件的base64编码
> with open(file="../../../../docs/imgs/woman.png", mode="rb") as fp:
> base64_data2 = base64.b64encode(fp.read())
> base64_data2 = str(base64_data2, encoding="utf8")
> 
> ```
> data = {"b64s": [base64_data1, base64_data2]}
> data = {"data": json.dumps(data)}
> # print(str(type(data)))
> # print(data)
> 
> # 指定检测方法为pyramidbox_lite_server并发送post请求
> url = "http://127.0.0.1:8866/predict/image/pyramidbox_lite_server"
> r = requests.post(url=url, data=data)
> print(r)
> print(r.json()["results"])
> 
> # 得到并打印检测结果
> results = eval(r.json()["results"])
> print(results)
> 
> print(json.dumps(results, indent=4, ensure_ascii=False))
> ```
> 
> 其实，就是只修改了pyramidbox_lite_server_mask_serving_demo.py中的url路径中模型，其他未变。

还有图片也修改了，不是戴口罩的图片。

**Comment by YasinZhao** [comment]
这是我开启hub serving start -m pyramidbox_lite_server_mask服务时，运行pyramidbox_lite_server_mask_serving_demo.py脚本的结果，结果是正常的，供老师参考：
![image](https://user-images.githubusercontent.com/16828608/76920776-4e71f480-6907-11ea-9550-a32c717ab77e.png)

**Comment by ShenYuhan** [comment]
您好，其他图像检测模型我们推荐通过file的形式传递图片，当然，仍然有一种方案能够完成base64编码的直接传输，脚本如下：
```python
# coding: utf8
import requests
import json
import base64
import os

if __name__ == "__main__":
    # 获取第一张图片文件的base64编码
    with open(file="../../../../docs/imgs/family_mask.jpg", mode="rb") as fp:
        base64_data1 = base64.b64encode(fp.read())
    base64_data1 = str(base64_data1, encoding="utf8")

    # data = {"b64s": [base64_data1, base64_data2]}
    # 由于前端生成的base64数据有固定的文件头，因此采用b64encode得到的结果需要加上此文件头
    base64_data1 = "data:image/png;base64," + base64_data1
    data = {"image": [base64_data1]}

    # 指定检测方法为pyramidbox_lite_server并发送post请求
    url = "http://127.0.0.1:8866/predict/image/pyramidbox_lite_server"
    r = requests.post(url=url, data=data)

    if not os.path.exists("output"):
        os.mkdir("output")

    results = eval(r.json()["results"])
    for item in results:
        with open(os.path.join("output", item["path"]), "wb") as fp:
            fp.write(base64.b64decode(item["base64"].split(',')[-1]))
            item.pop("base64")
    print(json.dumps(results, indent=4, ensure_ascii=False))

```
我们并不推荐采用这种方案，因为这是为了前端页面直接传输采用的方案，因此未来可能会被废弃。

**Comment by YasinZhao** [comment]
> 您好，其他图像检测模型我们推荐通过file的形式传递图片，当然，仍然有一种方案能够完成base64编码的直接传输，脚本如下：
> 
> ```python
> # coding: utf8
> import requests
> import json
> import base64
> import os
> 
> if __name__ == "__main__":
>     # 获取第一张图片文件的base64编码
>     with open(file="../../../../docs/imgs/family_mask.jpg", mode="rb") as fp:
>         base64_data1 = base64.b64encode(fp.read())
>     base64_data1 = str(base64_data1, encoding="utf8")
> 
>     # data = {"b64s": [base64_data1, base64_data2]}
>     # 由于前端生成的base64数据有固定的文件头，因此采用b64encode得到的结果需要加上此文件头
>     base64_data1 = "data:image/png;base64," + base64_data1
>     data = {"image": [base64_data1]}
> 
>     # 指定检测方法为pyramidbox_lite_server并发送post请求
>     url = "http://127.0.0.1:8866/predict/image/pyramidbox_lite_server"
>     r = requests.post(url=url, data=data)
> 
>     if not os.path.exists("output"):
>         os.mkdir("output")
> 
>     results = eval(r.json()["results"])
>     for item in results:
>         with open(os.path.join("output", item["path"]), "wb") as fp:
>             fp.write(base64.b64decode(item["base64"].split(',')[-1]))
>             item.pop("base64")
>     print(json.dumps(results, indent=4, ensure_ascii=False))
> ```
> 
> 我们并不推荐采用这种方案，因为这是为了前端页面直接传输采用的方案，因此未来可能会被废弃。

好的，非常感谢老师的反馈和建议，我会就此作出针对性改动，再次感谢~
