### ISSUE TITLE
你好，请问一下文件中有一个依赖项paddle为啥装不了

### ISSUE THREAD

**Issue by buaaRec** [PaddlePaddle/PaddleFormers#454]
报错信息：
ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7w/kjg08r3d0xl45_z9vk7_8gr40000gn/T/pip-install-sazg3s7j/paddle/setup.py'"'"'; __file__='"'"'/private/var/folders/7w/kjg08r3d0xl45_z9vk7_8gr40000gn/T/pip-install-sazg3s7j/paddle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7w/kjg08r3d0xl45_z9vk7_8gr40000gn/T/pip-install-sazg3s7j/paddle/pip-egg-info
         cwd: /private/var/folders/7w/kjg08r3d0xl45_z9vk7_8gr40000gn/T/pip-install-sazg3s7j/paddle/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7w/kjg08r3d0xl45_z9vk7_8gr40000gn/T/pip-install-sazg3s7j/paddle/setup.py", line 3, in <module>
        import paddle
      File "/private/var/folders/7w/kjg08r3d0xl45_z9vk7_8gr40000gn/T/pip-install-sazg3s7j/paddle/paddle/__init__.py", line 5, in <module>
        import common, dual, tight, data, prox
    ModuleNotFoundError: No module named 'common'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Steffy-zxf** [comment]
你好！关于paddlepaddle安装问题可以在 https://github.com/PaddlePaddle/Paddle/issues 下提issue

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。

**Comment by buaaRec** [comment]
好的谢谢啦，问题已解决


Steffy-zxf <notifications@github.com> 于2020年4月20日周一 下午8:11写道：
