### ISSUE TITLE
paddlepaddle和paddlehub都是最新版。在跑ace2p的人体解析时，处理大规模数据时内存会一直增加到爆炸，初步判断是在postprocess有问题。不知道你们遇到过没有。

### ISSUE THREAD

**Issue by leoxxxxxD** [PaddlePaddle/PaddleFormers#455]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by leoxxxxxD** [comment]
找到原因了，在postprocess中，每次循环从data_out[0]中取data，就会造成内存爆炸。我目前的解决方法是在取之前把data_out[0]转成numpy。这样为什么会造成内存爆炸，还不清楚，对paddlepaddle不是很了解。。

**Comment by leoxxxxxD** [comment]
观察了其他工程，在postprocess中都有先转numpy的操作，比较疑惑为什么不先转就有问题。

**Comment by linshuliang** [comment]
感谢反馈，我们会跟进解决。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
