### ISSUE TITLE
@moduleinfo()报错

### ISSUE THREAD

**Issue by ClassmateXiaoyu** [PaddlePaddle/PaddleFormers#456]
版本、环境信息如下：
1、paddlehub1.6.0，paddlepaddle1.7.1
2、Windows7 64位，Python3.7.4

paddlehub1.6.0是通过git clone、git checkout出分支release/v1.6安装的。在按照demo示例操作@moduleinfo()时报错SyntaxError: unexpected EOF while parsing

**Comment by Steffy-zxf** [comment]
你好！这个问题，一般是你写的python脚本语法有问题，比如说少了）之类的。和module_info没有关系。

**Comment by ClassmateXiaoyu** [comment]
> 你好！这个问题，一般是你写的python脚本语法有问题，比如说少了）之类的。和module_info没有关系。

有括号的（括号使用英文键盘输入的），脚本是用的英文键盘（没用中文输入法）。我将括号里的内容删除后，还是提示同样的的错误。但是当我把moduleinfo前面的@删除后，反而没有错误。

**Comment by Steffy-zxf** [comment]
> 比如说少了）之类的 

这个只是我举个可能出现错误例子。 你的出错代码贴下？报错堆栈信息也贴下。

**Comment by ClassmateXiaoyu** [comment]
import argparse,os
import paddlehub as hub
from paddlehub.module.module import runnable,moduleinfo

@moduleinfo(
    name = 'yc_test',
    version = '1.0.0',
    summary = 'for test',
    author = '',
    author_emai = ''
)

以下为终端显示：
C:\Users\Administrator>D:/Python37/python.exe "c:/Users/Administrator/Desktop/cs - 副本.py"
  File "c:/Users/Administrator/Desktop/cs - 副本.py", line 12

     ^
SyntaxError: unexpected EOF while parsing

**Comment by Steffy-zxf** [comment]
能麻烦把代码，报错信息也给贴全吗？

**Comment by ClassmateXiaoyu** [comment]
你好，我在16:18的回复里发的就是代码（回是目前为止的代码，没有其他内容）和终端（我用VSC写的Python）的报错呀，在moduleinfo这里就出现错误后我就没往后面继续写代码了。

**Comment by Steffy-zxf** [comment]
你接着
```python
@moduleinfo(
name = 'yc_test',
version = '1.0.0',
summary = 'for test',
author = '',
author_emai = ''
)
```
定义完了之后，继续定义一个你要定义的module class。上面出错的原因是因为`@`表示一个修饰器，修饰一个类。你没有写完整，所以会报错。

**Comment by ClassmateXiaoyu** [comment]
> 你接着
> @moduleinfo(
> name = 'yc_test',
> version = '1.0.0',
> summary = 'for test',
> author = '',
> author_emai = ''
> )
> 定义完了之后，继续定义一个你要定义的module class。上面出错的原因是因为@表示一个修饰器，修饰一个类。你没有写完整，所以会报错。

你好，按照建议后面加上class类后，昨天的moduleinfo报错没有了。但是出来了新的报错ImportError: cannot import name 'moduleinfo' from 'paddlehub.module.module'，我用pip list查看了，显示paddlehub是1.6.0

**Comment by Steffy-zxf** [comment]
请确认你运行PaddleHub的环境是否成功安装PaddleHub 1.6.0版本。目前 PaddleHub 1.6.0 已经正式发版了。

**Comment by ClassmateXiaoyu** [comment]
> 请确认你运行PaddleHub的环境是否成功安装PaddleHub 1.6.0版本。目前 PaddleHub 1.6.0 已经正式发版了。

我将paddlehub删除，重新下载正式版1.6.0后，报错消除了，问题已解决。
