### ISSUE TITLE
请问paddlehub的ERNIE是否支持finetune多个任务

### ISSUE THREAD

**Issue by MiniMinyi** [PaddlePaddle/PaddleFormers#458]
如题。
例如先将ERNIE用于finetune NER任务，再用于finetune句子分类任务。
如果可以，应该怎么做的，谢谢！

**Comment by Steffy-zxf** [comment]
你好！ERNIE 完成了NER Fine-tune后不能在用于其他任务的Fine-tune（句子分类任务）。因为两个任务的组网是不一样的，加载模型参数会出错。同时想了解下，你为什么需要这样做？背景是什么呢？

**Comment by MiniMinyi** [comment]
https://arxiv.org/pdf/1905.05583.pdf
我是阅读了上面这篇论文How to Fine-Tune BERT for Text Classification?，multi task finetuning看起来是可以提高模型在特定task的performance。如果ERNIE支持在一个任务上finetune，然后导出除了classification layer之后的参数，再在另一个任务上继续finetune就好了。

**Comment by Steffy-zxf** [comment]
PaddleHub 目前不支持multi-task learning，
> 如果ERNIE支持在一个任务上finetune，然后导出除了classification layer之后的参数，再在另一个任务上继续finetune就好了。

如果你需要这么做的话，你需要自己改动Task源码。然而这是我们不建议的，因为改动过程中可能带来其他问题。

**Comment by 131250208** [comment]
@Steffy-zxf 同样有这个需求，请问以后会支持multi-task learning吗？或者有没有办法先在无标签的语料上预训练，再在有标签的语料上进行下游任务？

**Comment by Steffy-zxf** [comment]
@131250208 @MiniMinyi 关于多任务学习，可以参考 https://github.com/PaddlePaddle/PALM

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
