### ISSUE TITLE
服务化部署了人像分割服务之后偶尔会出现500 Internal Server Error 请协助解决

### ISSUE THREAD

**Issue by lesterhnu** [PaddlePaddle/PaddleFormers#459]
paddlepaddle1.7.1  paddleHub 1.5.4
CentOS7 python3.7.3

通过 `hub serving start -m deeplabv3p_xception65_humanseg` 命令启动服务之后，有些图片不知道为什么会分割失败，提示500 Internal server error
![image](https://user-images.githubusercontent.com/42615458/77130426-e2bc9280-6a92-11ea-87dd-c1bb5f7c9048.png)
![image](https://user-images.githubusercontent.com/42615458/77130433-ea7c3700-6a92-11ea-8800-eb95bb925572.png)
![image](https://user-images.githubusercontent.com/42615458/77130436-f0721800-6a92-11ea-8d09-7690aa75373b.png)
![image](https://user-images.githubusercontent.com/42615458/77130440-f5cf6280-6a92-11ea-88ae-6a13064959bf.png)

**Comment by ShenYuhan** [comment]
请问是某些图片必现吗？如果是的话可以提供下图片吗，我这里试一下。
