### ISSUE TITLE
NLP任务自定义数据集内文本数据问题

### ISSUE THREAD

**Issue by ColinDowney** [PaddlePaddle/PaddleFormers#463]
[NLP类任务如何自定义数据](https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub适配自定义数据完成FineTune)
按照要求导入后发现始终报Index Error的错误，经过检查发现由于BaseNLPDataset._read_file中使用csv.reader读取lines，导致文本项中不能包含字符'\n'。
或许在Wiki里面明确指出来比较好？防止（像我这样的）新手踩坑。

**Comment by Steffy-zxf** [comment]
感谢反馈！[NLP类任务如何自定义数据](https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E9%80%82%E9%85%8D%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E5%AE%8C%E6%88%90FineTune) 教程中指出 数据集文件，一行表示 一个文本输入 和 相应的label。请问，你的数据集文件中加载出错的数据 是否能给个样例？同时，你的运行环境是什么样的？

**Comment by ColinDowney** [comment]
> 感谢反馈！NLP类任务如何自定义数据 教程中指出 数据集文件，一行表示 一个文本输入 和 相应的label。请问，你的数据集文件中加载出错的数据 是否能给个样例？

> 一个文本输入 和 相应的label

即，当列与列之间以'\t'隔开的时候，行与行之间应该以'\n'隔开。但是我的文本输入中包含了'\n'，因此会导致读取的时候有问题。把数据集文件中的文本部分里面包含的'\n'洗掉之后就没有问题了。

**Comment by Steffy-zxf** [comment]
你的运行环境是什么样的？

**Comment by ColinDowney** [comment]
> 你的运行环境是什么样的？
@Steffy-zxf 

在AI Studio跑的这个项目https://aistudio.baidu.com/aistudio/projectdetail/185121，只修改自定义数据集路径部分代码。

**Comment by Steffy-zxf** [comment]
你好！比如你的数据集文件像下面这样：
```text
text_a    lable
选择珠江花园的原因\n就是方便，有电动扶梯直接到达海边，\n周围餐馆、食廊、商场、超市、摊位一应俱全。酒店装修一般，\n但还算整洁。 泳池在大堂的屋顶，因此很小，不过女儿倒是喜欢。 包的早餐是西式的，还算丰富。 服务吗，一般    1
```

这样的文本数据就是多行了，但只有最后一行有label。这肯定是不符合PaddleHub自定义数据集格式要求的。

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。

**Comment by 60999** [comment]
这个情况和 这个问题相同：
https://github.com/PaddlePaddle/PaddleHub/issues/581

**Comment by cheeryoung79** [comment]
python 写文件不用\n怎么换行

**Comment by Steffy-zxf** [comment]
@cheeryoung79 你好！可以试试将换行符`\n`替换成别的特殊字符，比如空格。建议数据中不要带有换行符。
