### ISSUE TITLE
finetune 之后如何再次调用之前训练好的模型？同时finetune 之后想获取embedding应该怎么调用？有相关API文档吗？

### ISSUE THREAD

**Issue by Pacrky** [PaddlePaddle/PaddleFormers#477]
finetune 之后如何再次调用之前训练好的模型？同时finetune 之后想获取embedding应该怎么调用？有相关API文档吗？

**Comment by Steffy-zxf** [comment]
你好！Fine-tune好的模型参数会保存在Fine-tune时指定的checkpoint文件夹下best_model下面，加载模型参数可以使用[load_inference_model()接口](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/load_inference_model_cn.html#load-inference-model)
如果你想使用Fine-tune好的模型embedding，你需要将Fine-tune好的模型转化成一个module，参考 https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/finetuned_model_to_module.md
在定义你的finetune module class时，将其中继承的类hub.Module 改成[TransformerModule](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/module/nlp_module.py#L244)，创建完了module，就可以调用其中[get_embedding接口](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/module/nlp_module.py#L356)接口，取得 输入句子的embedding

get_embedding()接口调用示例，参考 https://www.paddlepaddle.org.cn/hubdetail?name=ERNIE&en_category=SemanticModel
其中的代码示例

**Comment by ChenMiya** [comment]
"在定义你的finetune module class时，将其中继承的类hub.Module 改成TransformerModule，创建完了module，就可以调用其中get_embedding接口接口，取得 输入句子的embedding"
请问这一步可以给示例demo吗？意思是把class ERNIETinyFinetuned(hub.Module): 改成 class ERNIETinyFinetuned(TransformerModule):吗
