### ISSUE TITLE
在MacOS下训练出错，但在AI STUDIO正常，日志详见下图

### ISSUE THREAD

**Issue by cvdnn** [PaddlePaddle/PaddleFormers#478]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.6.1，PaddlePaddle1.7.1
2）系统环境：系统类型：MacOS/，python版本：Python 3.7.2
- 复现信息：如为报错，请给出复现环境、复现步骤

[2020-03-25 21:08:52,561] [    INFO] - Installing mobilenet_v2_imagenet module
[2020-03-25 21:08:53,152] [    INFO] - Module mobilenet_v2_imagenet already installed in /Users/handy/.paddlehub/modules/mobilenet_v2_imagenet
[2020-03-25 21:08:53,660] [    INFO] - 267 pretrained paramaters loaded by PaddleHub
[2020-03-25 21:08:53,661] [    INFO] - Dataset label map = {'roses': 0, 'daisy': 1}
[2020-03-25 21:08:53,661] [    INFO] - Checkpoint dir: ckpt_model
[2020-03-25 21:09:00,721] [    INFO] - Strategy with slanted triangle learning rate, L2 regularization, 
/Users/handy/.virtualenvs/PaddleApp/lib/python3.7/site-packages/paddle/fluid/executor.py:804: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
[2020-03-25 21:09:00,763] [    INFO] - Try loading checkpoint from ckpt_model/ckpt.meta
[2020-03-25 21:09:00,763] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-03-25 21:09:00,810] [    INFO] - PaddleHub finetune start
I0325 21:09:01.170374 272072128 parallel_executor.cc:440] The Program will be executed on CPU using ParallelExecutor, 2 cards are used, so 2 programs are executed in parallel.
W0325 21:09:01.280500 272072128 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 161. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 161.
I0325 21:09:01.301883 272072128 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0325 21:09:01.572834 272072128 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0325 21:09:01.647723 272072128 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
[2020-03-25 21:09:05,624] [    INFO] - Evaluation on dev dataset start
Traceback (most recent call last):
  File "classify_task.py", line 27, in <module>
    run_states = paddle_wrap.task.finetune_and_eval()
  File "/Users/handy/.virtualenvs/PaddleApp/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 864, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "/Users/handy/.virtualenvs/PaddleApp/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 893, in finetune
    self.eval(phase="dev")
  File "/Users/handy/.virtualenvs/PaddleApp/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 923, in eval
    self._eval_end_event(run_states)
  File "/Users/handy/.virtualenvs/PaddleApp/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 631, in hook_function
    func(*args)
  File "/Users/handy/.virtualenvs/PaddleApp/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 719, in _default_eval_end_event
    eval_scores, eval_loss, run_speed = self._calculate_metrics(run_states)
  File "/Users/handy/.virtualenvs/PaddleApp/lib/python3.7/site-packages/paddlehub/finetune/task/classifier_task.py", line 115, in _calculate_metrics
    run_time_used = time.time() - run_states[0].run_time_begin
IndexError: list index out of range
libc++abi.dylib: terminating with uncaught exception of type paddle::platform::EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > paddle::platform::GetTraceBackString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int)
1   paddle::framework::RWLock::RDLock()
2   paddle::framework::Scope::HasKid(paddle::framework::Scope const*) const
3   paddle::framework::ParallelExecutorPrivate::~ParallelExecutorPrivate()
4   paddle::framework::ParallelExecutor::~ParallelExecutor()
5   pybind11::class_<paddle::framework::ParallelExecutor>::dealloc(pybind11::detail::value_and_holder&)
6   pybind11::detail::clear_instance(_object*)
7   pybind11_object_dealloc

----------------------
Error Message Summary:
----------------------
Error: acquire read lock failed
  [Hint: Expected pthread_rwlock_rdlock(&lock_) == 0, but received pthread_rwlock_rdlock(&lock_):22 != 0:0.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/framework/rw_lock.h:36)

W0325 21:09:06.206892 272072128 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0325 21:09:06.206903 272072128 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0325 21:09:06.206907 272072128 init.cc:214] The detail failure signal is:

W0325 21:09:06.206910 272072128 init.cc:217] *** Aborted at 1585141746 (unix time) try "date -d @1585141746" if you are using GNU date ***
W0325 21:09:06.207233 272072128 init.cc:217] PC: @                0x0 (unknown)
W0325 21:09:06.209056 272072128 init.cc:217] *** SIGABRT (@0x7fff682af7fa) received by PID 9529 (TID 0x110377dc0) stack trace: ***
W0325 21:09:06.209656 272072128 init.cc:217]     @     0x7fff6836142d _sigtramp

**Comment by Steffy-zxf** [comment]
你好！方便把运行脚本代码贴下吗？

**Comment by cvdnn** [comment]
![outofindex](https://user-images.githubusercontent.com/15883260/77842686-e2757300-71c7-11ea-917a-4340fbf068ed.jpg)

**Comment by cvdnn** [comment]
# -*- coding: utf8 -*-

import paddlehub as hub

from paddlehub import RunConfig, ImageClassifierTask, DefaultFinetuneStrategy
from paddlehub.dataset import BaseDataset
from paddlehub.reader import ImageClassificationReader


class PaddleWrap(object):

    def __init__(self, model_name, dataset: BaseDataset, use_cuda=False):
        self.use_cuda = use_cuda
        self.model_name = model_name
        self.dataset = dataset

        # learning_rate:        全局学习率。默认为1e-4；
        # optimizer_name:       优化器名称。默认adam；
        # regularization_coeff: 正则化的λ参数。默认为1e-3；
        self.strategy = DefaultFinetuneStrategy(
            learning_rate=1e-4,
            optimizer_name="adam",
            regularization_coeff=1e-3,
        )

        # log_interval:         打印训练日志的周期，默认为10。
        # eval_interval:        进行评估的周期，默认为100。
        # use_pyreader:         是否使用pyreader，默认False。
        # use_data_parallel:    是否使用并行计算，默认False。打开该功能依赖nccl库。
        # save_ckpt_interval:   保存checkpoint的周期，默认为None。
        # use_cuda:             是否使用GPU训练和评估，默认为False。
        # checkpoint_dir:       checkpoint的保存目录，默认为None，此时会在工作目录下根据时间戳生成一个临时目录。
        # num_epoch:            运行的epoch次数，默认为10。
        # batch_size：          每次训练的时候，给模型输入的每批数据大小为32，模型训练时能够并行处理批数据，
        #                       因此batch_size越大，训练的效率越高，但是同时带来了内存的负荷，过大的batch_size可能导致内存不足而无法训练，
        #                       因此选择一个合适的batch_size是很重要的一步；
        # enable_memory_optim:  是否进行内存优化，默认为False。
        # strategy:             finetune的策略。默认为None，此时会使用DefaultFinetuneStrategy策略。
        self.config = RunConfig(
            use_cuda=self.use_cuda,
            num_epoch=10,  # if self.use_cuda else 1,
            batch_size=32,  # if self.use_cuda else 16,
            checkpoint_dir='ckpt_model',
            strategy=self.strategy)

    def new_task(self):
        # Load Paddlehub  pretrained model
        module = hub.Module(name=self.model_name)
        input_dict, output_dict, program = module.context(trainable=True)

        # Use ImageClassificationReader to read dataset
        data_reader = ImageClassificationReader(
            image_width=module.get_expected_image_width(),
            image_height=module.get_expected_image_height(),
            images_mean=module.get_pretrained_images_mean(),
            images_std=module.get_pretrained_images_std(),
            dataset=self.dataset)

        # feed_list中的inputs参数指明了resnet/mobilenet等模型的输入tensor的顺序，与ImageClassifierTask返回的结果一致。
        feed_list = [input_dict["image"].name]

        # output_dict["feature_map"]返回了resnet/mobilenet等模型对应的feature_map，可以用于图片的特征表达。
        feature_map = output_dict["feature_map"]

        # hub.ImageClassifierTask通过输入特征，label与迁移的类别数，可以生成适用于图像分类的迁移任务ImageClassifierTask。
        task = ImageClassifierTask(
            data_reader=data_reader,
            feed_list=feed_list,
            feature=feature_map,
            num_classes=self.dataset.num_labels,
            config=self.config)

        return task

**Comment by cvdnn** [comment]
class PaddleDataset(BaseCVDataset):
    """
    默认dataset路径：hub.common.dir.DATA_HOME，即: ~/.paddlehub/dataset/
    """

    def __init__(self, name: str = 'test'):
        self.name = name
        base_path = self.get_base_path()

        super(PaddleDataset, self).__init__(
            base_path=base_path,
            label_list_file="label_list.dst",
            train_list_file="train_list.dst",
            validate_list_file="validate_list.dst",
            test_list_file="test_list.dst",
            label_list=None)

    def get_base_path(self):
        return path.join(DATA_HOME, self.name if self.name else 'test')

**Comment by handy001** [comment]
class PaddleDataset(BaseCVDataset):
    """
    默认dataset路径：hub.common.dir.DATA_HOME，即: ~/.paddlehub/dataset/
    """

    def __init__(self, name: str = 'test'):
        self.name = name
        base_path = self.get_base_path()

        super(PaddleDataset, self).__init__(
            base_path=base_path,
            label_list_file="label_list.dst",
            train_list_file="train_list.dst",
            validate_list_file="validate_list.dst",
            test_list_file="test_list.dst",
            label_list=None)

    def get_base_path(self):
        return path.join(DATA_HOME, self.name if self.name else 'test')

**Comment by cvdnn** [comment]
async def train(user_id: str, model_id: str, action: Optional[int] = 0):
    result = {"result": -1}

    dataset = classify.prepare(model_id)
    if dataset:
        run_states = classify.train(dataset)
        if run_states:
            result['result'] = 0

        else:
            result['result'] = -1
            result['msg'] = '模型训练失败，请重试'
    else:
        result['result'] = -100
        result['msg'] = '模型训练失败，请核对模型数据集是否选择正确'

    return result

**Comment by cvdnn** [comment]
![outofindex](https://user-images.githubusercontent.com/15883260/77842737-7ba48980-71c8-11ea-81bf-b3e6066b612b.jpg)

**Comment by Steffy-zxf** [comment]
@handy001 你好，尝试在Mac上运行时，将RunConfig中use_pyreader关闭试试。
```python
    self.config = RunConfig(
        use_cuda=self.use_cuda,
        use_pyreader=False,
        num_epoch=10, 
        batch_size=32,
        checkpoint_dir='ckpt_model',
        strategy=self.strategy)
```

同时，请检查下Mac上使用PaddlePaddle环境配置是否正确。参考[PaddlePaddle快速安装](https://www.paddlepaddle.org.cn/install/quick)，验证是否能成功使用Paddle。
