### ISSUE TITLE
ImportError: cannot import name 'HubDataset' from 'paddlehub.dataset'

### ISSUE THREAD

**Issue by MINORHDMI** [PaddlePaddle/PaddleFormers#484]
你好，我直接在Ai.studio上notebook环境使用，版本均未改动
当我from paddlehub.dataset import HubDataset
直接报错：ImportError: cannot import name 'HubDataset' from 'paddlehub.dataset' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/dataset/__init__.py)
请问这是什么原因导致的呢？

**Comment by Steffy-zxf** [comment]
你好！HubDataset是PaddleHub老版本的用法，建议你使用[新版本的PaddleHub加载自定义数据集](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/how_to_load_data.md)，PaddleHub最新版本是1.6.1.

**Comment by MINORHDMI** [comment]
好的，感谢您的回答。

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
