### ISSUE TITLE
bert service demo请求错误

### ISSUE THREAD

**Issue by luoluo001** [PaddlePaddle/PaddleFormers#485]
service 是用的notebooks cpu基础版本： 
service启动命令：hub serving start bert_service -m ernie_tiny --p 8866
而且虽然指定了port但是端口也没变过来。
然后用demo clinet请求 得到如下这个错误信息
status_code = int(response_list[0].split(':')[1])

**Comment by ShenYuhan** [comment]
可以把日志和报错信息粘贴一下吗

**Comment by luoluo001** [comment]
谢谢哈 已经解决了  在python端，怎么解决的我自己也没找到。。。。

**Comment by luoluo001** [comment]
> 可以把日志和报错信息粘贴一下吗
已经解决了 。  另外我想问下 如果是用bert_service 请求ernie_tiny 模型启动的服务 。用post数据格式是啥啊  案例上没有看到这些信息。

**Comment by luoluo001** [comment]
![image](https://user-images.githubusercontent.com/24263006/78131847-4d37e000-744e-11ea-9cab-11cfb1137b60.png)
如上是我用postwomen 仿造的请求 但是没通  8051是启动的时候设定的-p 端口

**Comment by ShenYuhan** [comment]
您好，bert-service不同于paddlehub-serving，需要借助paddlehub中的bert-service客户端进行请求，您可以看下这里的文档说明
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/bert_service.md#step3%E4%BD%BF%E7%94%A8bert-service%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%BF%9B%E8%A1%8C%E8%BF%9C%E7%A8%8B%E8%B0%83%E7%94%A8

**Comment by luoluo001** [comment]
> 您好，bert-service不同于paddlehub-serving，需要借助paddlehub中的bert-service客户端进行请求，您可以看下这里的文档说明
> https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/bert_service.md#step3%E4%BD%BF%E7%94%A8bert-service%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%BF%9B%E8%A1%8C%E8%BF%9C%E7%A8%8B%E8%B0%83%E7%94%A8

谢谢 您好 这个我看过的 但是我们独立部署通过 其他语言http调用，这个要怎么调呢？是否有案例说明呢 麻烦您了谢谢

**Comment by luoluo001** [comment]
我看到了是使用BRPC的调用方式计算向量，那么请问有java版本的调用jar包及案例吗

**Comment by MRXLT** [comment]
你好，使用其他语言HTTP调用的方式可以参考，bert service的python版client源码，https://github.com/PaddlePaddle/Serving/blob/develop/tools/cpp_examples/bert-gpu-serving/client/bert_service/bert_service.py
需要用到paddlehub做数据预处理，然后通过post请求发送给server

**Comment by luoluo001** [comment]
> 你好，使用其他语言HTTP调用的方式可以参考，bert service的python版client源码，https://github.com/PaddlePaddle/Serving/blob/develop/tools/cpp_examples/bert-gpu-serving/client/bert_service/bert_service.py
> 需要用到paddlehub做数据预处理，然后通过post请求发送给server

谢谢您哈，..主要是这个不大会python，回头我先研究研究  ，但如果有java sdk的话那更好了。

**Comment by ultimatedaotu** [comment]
我跟你一样的报错  请问是怎么解决的

**Comment by ChenMiya** [comment]
> service 是用的notebooks cpu基础版本：
> service启动命令：hub serving start bert_service -m ernie_tiny --p 8866
> 而且虽然指定了port但是端口也没变过来。
> 然后用demo clinet请求 得到如下这个错误信息
> status_code = int(response_list[0].split(':')[1])

我运行demo时也报这样的错误，请问是怎样解决的呀？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
