### ISSUE TITLE
Aistudio调用Paddlehub的deeplabv3p_xception65_humanseg报错

### ISSUE THREAD

**Issue by newdimitri** [PaddlePaddle/PaddleFormers#488]
请问我在aistudio上调用deeplabv3p_xception65_humanseg，为啥提示这个错误
![image](https://user-images.githubusercontent.com/11519247/77999450-45e8d780-7365-11ea-9eee-300cec944ef8.png)

**Comment by Steffy-zxf** [comment]
感谢反馈！请升级PaddleHub至最新版本
```
!pip install paddlehub==1.6.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
