### ISSUE TITLE
请问文本分类中的dropout做了预测处理吗？？

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/PaddleFormers#489]
就是那个再训练时用dropout，而预测时，不是跟训练一样直接舍弃一部分，候是所有的都用，只在过dropout的时候乘概率——这个处理，我想问一下文本分类的那个task里是否已经做了？我貌似没有看到……

**Comment by Steffy-zxf** [comment]
你好！文本分类Task，有经过dropout处理：
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/classifier_task.py#L182

**Comment by wxl1351641822** [comment]
额，不好意思，我知道他有dropout，我想要问的不是这个。训练的时候经过dropout层的时候会将部分神经元置零，**而在预测的时候则是保留所有神经元，仅将使用了dropout的层的神经元，乘以这个dropout概率**。<---我想问的是这个预测的这个处理，他处理了吗？

**Comment by Steffy-zxf** [comment]
如果是用PaddleHub 预测接口predict预测的话，在预测时，dropout会失效，所以保留了所有神经元。

**Comment by wxl1351641822** [comment]
那他乘那个dropout概率了吗？？

**Comment by Steffy-zxf** [comment]
> 那他乘那个dropout概率了吗？？

你能说的详细些吗？ 哪个乘以dropout概率？

**Comment by wxl1351641822** [comment]
就文本分类那个任务里，不是将输入的feature加了dropout层吗。在预测的时候保留所有的feature的话，是不是要乘上一个dropout概率？paddlehub里有做这个操作吗？就在feature这里。

**Comment by Steffy-zxf** [comment]
> 如果是用PaddleHub 预测接口predict预测的话，在预测时，dropout会失效，所以保留了所有神经元。

也就是说，预测是dropout没用了。

**Comment by wxl1351641822** [comment]
好的，谢谢
