### ISSUE TITLE
是否有anaconda的安装方式实现对paddlehub的安装

### ISSUE THREAD

**Issue by Hsoms** [PaddlePaddle/PaddleFormers#499]
是否有anaconda的安装方式实现对paddlehub的安装？

**Comment by Steffy-zxf** [comment]
感谢反馈！目前不支持conda安装paddlehub，你可以通过pip安装。参考[PaddleHub安装说明](https://github.com/PaddlePaddle/PaddleHub#%E5%AE%89%E8%A3%85%E5%91%BD%E4%BB%A4)
