### ISSUE TITLE
[Window]InvalidArgumentError: Tensor holds the wrong type, it holds int, but desires to be int64_t.

### ISSUE THREAD

**Issue by liuchang0523** [PaddlePaddle/PaddleFormers#500]
Paddle 1.7.1  PaddleHub 1.6.1 window操作系统
按照[PaddleHub进行图像分类](https://aistudio.baidu.com/aistudio/projectdetail/375473?pV=65216)例子在本地尝试时，运行到Step5、Fine-tune时报错：

> ----------------------
>Error Message Summary:
>----------------------
>InvalidArgumentError: Tensor holds the wrong type, it holds int, but desires to be int64_t.
>  [Hint: Expected valid == true, but received valid:0 != true:1.] at (D:\1.7.1\paddle\paddle/fluid/framework/tensor_impl.h:33)
  [operator < cross_entropy2 > error]

**Comment by Steffy-zxf** [comment]
感谢反馈！可以参考这个issue #473

**Comment by liuchang0523** [comment]
@Steffy-zxf 你好，降级到1.6.2没有解决此问题。

----------------------
Error Message Summary:
----------------------
Error: Tensor holds the wrong type, it holds float, but desires to be int64_t at (D:\1.6.2\paddle\paddle/fluid/framework/tensor_impl.h:30)
  [operator < cross_entropy2 > error]

**Comment by wk-mike** [comment]
同问，一样的错误。

**Comment by wk-mike** [comment]
@Steffy-zxf   
我在windows10 上面修复了这个问题。错误的原因是int和int64不匹配。

只需要更改  paddlehub\reader\cv_reader.py   第166行    
```
 labels.append([int(label)])
```
改为 
```
 labels.append([np.int64(label)])
```
希望及时修复，谢谢。

**Comment by wkxu** [comment]
> cv_reader.py

win10，paddlepaddle2.0.0rc gpu版本
找不到cv_reader.py了

**Comment by wk-mike** [comment]
> > cv_reader.py
> 
> win10，paddlepaddle2.0.0rc gpu版本
> 找不到cv_reader.py了

当时是在Paddle 1.7上面改的，现在版本更新之后就不知道了
