### ISSUE TITLE
Request Hub-Server unsuccessfully.

### ISSUE THREAD

**Issue by Thankyouforit** [PaddlePaddle/PaddleFormers#501]
错误提示
[2020-04-05 19:47:03,574] [   ERROR] - Request Hub-Server unsuccessfully, please check your network.
Traceback (most recent call last):
  File "D:/MyCode/BaiduAI/Cutout/cutout.py", line 25, in <module>
    module = hub.Module(name="deeplabv3p_xception65_humanseg")
  File "D:\MySoftwares\Miniconda3.4.5.12\envs\py37_ai\lib\site-packages\paddlehub\module\module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "D:\MySoftwares\Miniconda3.4.5.12\envs\py37_ai\lib\site-packages\paddlehub\module\module.py", line 173, in init_with_name
    raise RuntimeError(tips)
RuntimeError: Request Hub-Server unsuccessfully, please check your network.

我该怎么检查我的network，怎么设置我的network, 还是有什么配置文件配错了。
以下是我的 conf/config.json:
{
"server_url": [
"http://paddlepaddle.org.cn/paddlehub"
],
"resource_storage_server_url": "https://bj.bcebos.com/paddlehub-data/",
"debug": false,
"log_level": "DEBUG"
}

**Comment by ShenYuhan** [comment]
首先要确定您的环境可以正常联网吗？
如果能够正常联网，可以在命令行执行 hub config reset
然后脚本中可以这样测试
```python
import paddlehub
paddlehub.server_check()
```

**Comment by Thankyouforit** [comment]
(py37_ai) D:\test>hub config reset
Set success! The current configuration is shown below.
{
    "server_url": [
        "http://paddlepaddle.org.cn/paddlehub"
    ],
    "resource_storage_server_url": "https://bj.bcebos.com/paddlehub-data/",
    "debug": false,
    "log_level": "DEBUG",
    "hub_name": "f33ee0a425eec8750f851189303e5a13-1586117389"
}

(py37_ai) D:\test>ipython
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:22:21) [MSC v.1916 64 bit (AMD64)]

In [1]: import paddlehub

In [2]: paddlehub.server_check()
Request Hub-Server successfully.

但在pycharm中仍然抛出该问题，请问这是什么原因？

**Comment by ShenYuhan** [comment]
您是否使用了conda？确保pycharm使用的python环境和您测试通过的环境是一个，理论上说如果是同一个环境，应该表现是相同的。

**Comment by Thankyouforit** [comment]
更新pycharm 到2020.1版本时，使用conda环境时问题得到解决

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
