### ISSUE TITLE
finetune完成后，怎么导入训练好的参数？

### ISSUE THREAD

**Issue by sunw71** [PaddlePaddle/PaddleFormers#504]
finetune结束后，参数是保存到checkpoint文件夹了吗？下次用的时候怎么导入？

**Comment by kinghuin** [comment]
Hi @sunw71 ，是的，下次使用的时候设置checkpoint_dir为该checkpoint文件夹路径就会自动导入了

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
