### ISSUE TITLE
Senta-Bilstm fine-tune后predict报错LACClassifyReader does not support predictor, please close accelerate_mode

### ISSUE THREAD

**Issue by yocen** [PaddlePaddle/PaddleFormers#507]
版本、环境信息
1）PaddleHub：1.6.1  PaddlePaddle：1.7.1
2）系统环境：AI STUDIO高级版

问题描述：
Senta-Bilstm fine-tune后predict报错：
LACClassifyReader does not support predictor, please close accelerate_mode

项目地址：
https://aistudio.baidu.com/aistudio/projectdetail/311069

**Comment by Steffy-zxf** [comment]
你好！根据错误提示，如果你用的是LACClassifyReader，因为LACClassifyReader不支持加速模式，需要改为task.predict(accelerate_mode=False)
