### ISSUE TITLE
hub 预测每次都下载

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/PaddleFormers#508]
hub run yolov3_darknet53_coco2017 --input_path "/PATH/TO/IMAGE"
使用hub时每次执行都重复下载，有下载一次不再下载的参数吗？
Downloading yolov3_darknet53_coco2017
[==================================================] 100.00%
Uncompress /home/mcl/.paddlehub/tmp/tmpvb26tsku/yolov3_darknet53_coco2017
[==================================================] 100.00%
Successfully installed yolov3_darknet53_coco2017-1.0.0

**Comment by ShenYuhan** [comment]
您好，模型信息目前存在一些缺陷，我们会尽快升级此模型，将不再出现此问题。

**Comment by Steffy-zxf** [comment]
您好！该模型已经升级完毕，可以试试新版本。详细信息参考：https://www.paddlepaddle.org.cn/hubdetail?name=yolov3_darknet53_coco2017&en_category=ObjectDetection

```shell
hub install yolov3_darknet53_coco2017==1.1.1
```
