### ISSUE TITLE
please use 'application/json' as content-type to post to /predict/senta_lstm

### ISSUE THREAD

**Issue by mango941231** [PaddlePaddle/PaddleFormers#511]
text_list = ["我不爱吃甜食", "我喜欢躺在床上看电影"]
text = {"text": text_list}
url = "http://192.168.126.186:8866/predict/text/senta_lstm"
r = requests.post(url=url, data=text)

运行返回please use 'application/json' as content-type to post to /predict/senta_lstm，是什么原因 代码和Demo一样

**Comment by ShenYuhan** [comment]
您好，最新版本的模型使用方式有所变化，您可以参考这个文档，在返回的提示中应该也有相应指示。
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/serving.md#%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AF%B7%E6%B1%82%E6%96%B0%E7%89%88%E6%A8%A1%E5%9E%8B%E7%9A%84%E6%96%B9%E5%BC%8F

**Comment by mango941231** [comment]
> 您好，最新版本的模型使用方式有所变化，您可以参考这个文档，在返回的提示中应该也有相应指示。
> https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/serving.md#%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AF%B7%E6%B1%82%E6%96%B0%E7%89%88%E6%A8%A1%E5%9E%8B%E7%9A%84%E6%96%B9%E5%BC%8F

好的谢谢

**Comment by mango941231** [comment]
好的 谢谢

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
