### ISSUE TITLE
训练得到的结果可以可视化吗？

### ISSUE THREAD

**Issue by sunw71** [PaddlePaddle/PaddleFormers#513]
训练得到的参数文件夹里面有个visualization文件夹，里面的文件是用来可视化的吗？怎么用？谢谢

**Comment by nepeplwu** [comment]
@sunw71 使用以下命令启动，然后打开浏览器查看即可
```shell
tensorboard --logdir visualization 
```

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
