### ISSUE TITLE
hub命令行无法使用

### ISSUE THREAD

**Issue by Mryangkaitong** [PaddlePaddle/PaddleFormers#514]
使用hub 命令行时一直卡着不动，请问一下这个怎么解决呢
如使用hub help时：
versions/3.6.5/lib/python3.6/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py:28: UserWarning: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770..  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))

**Comment by nepeplwu** [comment]
@Mryangkaitong 感谢反馈，麻烦贴下完整的堆栈信息

**Comment by Mryangkaitong** [comment]
嗯嗯，上面就是完整的信息
![图片](https://user-images.githubusercontent.com/23132307/79034123-3a5ba300-7be6-11ea-9a6c-7781e25093bb.png)

**Comment by nepeplwu** [comment]
@Mryangkaitong 麻烦试试，在卡住后键入ctrl+C进行中断，看看输出堆栈是什么？

**Comment by Mryangkaitong** [comment]
> 
> 
> @Mryangkaitong 麻烦试试，在卡住后键入ctrl+C进行中断，看看输出堆栈是什么？

![图片](https://user-images.githubusercontent.com/23132307/79036067-f6bd6500-7bf6-11ea-810e-34d8c8c34fd9.png)

**Comment by nepeplwu** [comment]
从堆栈来看不像是被阻塞住了，你大概等了多久？

**Comment by Mryangkaitong** [comment]
> 
> 
> 从堆栈来看不像是被阻塞住了，你大概等了多久？

等了一会，最后还是会自动报上面的错
![图片](https://user-images.githubusercontent.com/23132307/79036477-2b332000-7bfb-11ea-9cc6-02da760724fa.png)

**Comment by Steffy-zxf** [comment]
@Mryangkaitong 你好，从堆栈信息上看起来是 运行环境中缺少werkzrug第三方库。按照以下命令安装
```shell
$ pip install Werkzeug
```

**Comment by haoyuying** [comment]
Since you haven't replied for more than a year, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过一年未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
