### ISSUE TITLE
您好，我想问一下，paddlehub的一键模型部署，可以支持自己进行迁移学习得到的结果吗？还是只能支持官方所提供的那些模型

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleFormers#515]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

**Comment by nepeplwu** [comment]
@gaooolianggg 是支持finetune后模型的部署的，需要先将finetune后的模型转换为paddlehub的module，教程见：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/finetuned_model_to_module.md

**Comment by 95289527** [comment]
hub serving start --modules ernie_tiny_finetuned --port 9090 --use_multiprocess  --workers 2
ernie_tiny_finetuned == 1.0.0
[2020-04-10 12:56:03 -0400] [3238] [INFO] Starting gunicorn 20.0.4
[2020-04-10 12:56:03 -0400] [3238] [INFO] Listening at: http://0.0.0.0:9090 (3238)
[2020-04-10 12:56:03 -0400] [3238] [INFO] Using worker: sync
[2020-04-10 12:56:03 -0400] [3251] [INFO] Booting worker with pid: 3251
[2020-04-10 12:56:03 -0400] [3252] [INFO] Booting worker with pid: 3252

好像不行.......  post过去 没有反应..........

**Comment by 95289527** [comment]
hub serving start bert_service -m ernie_tiny_finetuned --port 9090 
Working with paddlehub
Save model for serving ...
Traceback (most recent call last):
  File "/usr/local/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/usr/local/lib/python3.6/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/usr/local/lib/python3.6/site-packages/paddlehub/commands/serving.py", line 423, in execute
    ServingCommand.start_bert_serving(self.args)
  File "/usr/local/lib/python3.6/site-packages/paddlehub/commands/serving.py", line 181, in start_bert_serving
    bs.with_model(model_name=args.modules[0])
  File "/usr/local/lib/python3.6/site-packages/paddle_gpu_serving/run/__init__.py", line 197, in with_model
    self.get_model(model_name)
  File "/usr/local/lib/python3.6/site-packages/paddle_gpu_serving/run/__init__.py", line 239, in get_model
    inputs, outputs, program = module.context(
AttributeError: 'ERNIETinyFinetuned' object has no attribute 'context'

这样启动也不行

**Comment by 95289527** [comment]
![image](https://user-images.githubusercontent.com/12559853/79010355-5df5fd80-7b94-11ea-9692-7d44f8ba6ebe.png)
一直没反应....

**Comment by 95289527** [comment]
知道问题了..........



客户端数据格式 和 url都和文档https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/serving.md
说的不一样.....

url路径变成了 /predict/ernie_tiny_finetuned
ernie_tiny_finetuned 这个是自己训练的模型安装的名称

数据格式是一个json字符串 ....  key是作为参数直接传进预测函数的........
![image](https://user-images.githubusercontent.com/12559853/79015309-16c13a00-7b9f-11ea-9db5-2bd24101b112.png)

像这样把data传进去...........

启动命令是这个.....
hub serving start --modules ernie_tiny_finetuned --port 9090 --use_multiprocess --workers 2



![image](https://user-images.githubusercontent.com/12559853/79015108-b92ced80-7b9e-11ea-8a35-c44e9df215a0.png)

**Comment by nepeplwu** [comment]
@nqzhang  抱歉给你造成了困惑，自定义Module的serving请求方式参考[Hub-Serving 客户端请求新版模型的方式](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/serving.md#%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AF%B7%E6%B1%82%E6%96%B0%E7%89%88%E6%A8%A1%E5%9E%8B%E7%9A%84%E6%96%B9%E5%BC%8F)，文档描述得不够清晰，我们在文档中增加下相应说明

**Comment by ChaunceyBai98** [comment]
我也遇到了差不多的问题，
![image](https://user-images.githubusercontent.com/24198574/79194634-79485d80-7e5f-11ea-82d2-ac9c122a7c23.png)

finetuned_ernie是我自己迁移学习的44分类器，变成module安装并hub serving -m finetuned_ernie运行在AIstudio服务器上，请能给点建议么，我有点绝望。

**Comment by ChaunceyBai98** [comment]
我直接跑module.py文件是能正常返回分类的

**Comment by ChaunceyBai98** [comment]
![image](https://user-images.githubusercontent.com/24198574/79199549-bb759d00-7e67-11ea-93b3-25073d71a447.png)
这是服务器端报的信息

**Comment by nepeplwu** [comment]
@ChaunceyBai98 ，你module.py的代码是否可以贴下？感谢是接口参数有问题

**Comment by ChaunceyBai98** [comment]
[module.zip](https://github.com/PaddlePaddle/PaddleHub/files/4475718/module.zip)

又研究了一下，好像就是predict写的不对，有啥教程么，不太会写。

这是serving部分的代码，直接粘在这了，module全部代码在压缩包里。
    @serving
    def predict(self, data, return_result=False, accelerate_mode=True):
        """
        Get prediction results
        """
        run_states = self.cls_task.predict(
            data=data,
            return_result=return_result,
            accelerate_mode=accelerate_mode)
        return run_states

**Comment by Steffy-zxf** [comment]
@ChaunceyBai98 @nqzhang hi, 由于hub serving使用的是flask框架，由于flask返回的response内容要遵循http协议，所以要保证predict接口返回的结果是能够被json编码的对象。而此时返回的是一个run_states对象，你需要在这个对象上做一些后处理，返回真正的预测结果，如
```python
@serving 
def predict(self, data, return_result=False, accelerate_mode=True):
    """
    Get prediction results
    """
    run_states = self.cls_task.predict(
        data=data,
        return_result=return_result,
        accelerate_mode=accelerate_mode)
    results = [run_state.run_results for run_state in run_states]
    prediction = []
    for batch_result in results:
        # get predict index
        batch_result = np.argmax(batch_result, axis=2)[0]
        prediction.append(batch_result)
     return prediction
```

参考调用方法中代码
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/finetuned_model_to_module.md#%E8%B0%83%E7%94%A8%E6%96%B9%E6%B3%951

感谢反馈！后续我们完善该文档。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
