### ISSUE TITLE
CPU_NUM设置

### ISSUE THREAD

**Issue by sunyanrec** [PaddlePaddle/PaddleFormers#516]
CPU跑程序，出现需要优化的警告，需要在程序哪里设置一下吗？
```
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=8 # for example, set CPU_NUM as number of physical CPU core which is 8.

!!! The default number of CPU_NUM=1.
```

**Comment by kinghuin** [comment]
Hi，@sunyanhust 您可以在命令行中执行 export CPU_NUM=2设置环境变量指定您希望用于模型训练使用的CPU数量

**Comment by athulvingt** [comment]
`export CPU_NUM=2` this didn't work for me, even after doing that the code uses only one thread. Can someone help me ?
Does paddle uses only one CPU thread during inference?

**Comment by liandanjia** [comment]
我也遇到这个问题，请看：https://github.com/PaddlePaddle/PaddleSeg/issues/930
推理的时候设置CPU_NUM好像不起作用。有人吗？

**Comment by liandanjia** [comment]
@kinghuin 你好，请问export CPU_NUM=2能用于推理吗？

**Comment by sportzhang** [comment]
我再使用LAC进行模型增量训练的时候也遇到了这个问题：
----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: The number(4) of samples[words] of current batch is less than the count(10) of devices(CPU), currently, it is not allowed. You should set the environment variable CPU_NUM in the system to determine the number of devices you need. at (/paddle/paddle/fluid/framework/parallel_executor.cc:923)

请问该如何解决？
