### ISSUE TITLE
PaddleHub >= 1.6.0版本会出现重复下载【yolov3_darknet53_coco2017】模型

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleFormers#517]
PaddleHub >= 1.6.0版本会出现重复下载【yolov3_darknet53_coco2017】模型，即无法获悉【yolov3_darknet53_coco2017】模型是否已安装，其他模型则正常。

**Comment by Steffy-zxf** [comment]
感谢反馈！该问题会在yolov3_darknet53_coco2017后续版本修复。同时想了解下，您使用yolov3_darknet53_coco2017的任务背景是什么？

**Comment by 670133189** [comment]
任务背景：学习paddleHub。
此外我想申请一下：paddleHub能否新增OCR的功能？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Steffy-zxf"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 上午9:13
收件人:&nbsp;"PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
抄送:&nbsp;"桢少"<670133189@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleHub] PaddleHub &gt;= 1.6.0版本会出现重复下载【yolov3_darknet53_coco2017】模型 (#517)





 
感谢反馈！该问题会在yolov3_darknet53_coco2017后续版本修复。同时想了解下，您使用yolov3_darknet53_coco2017的任务背景是什么？

**Comment by ZeyuChen** [comment]
@670133189 PaddleHub新增OCR模型已经在排期计划中，会在未来版本提供中文OCR模型，敬请期待。

**Comment by 670133189** [comment]
你好，关于paddleHub新增文字识别的日期，方便告诉我们么？
我们需要提前安排学习。
感谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zeyu Chen <notifications@github.com&gt;
发送时间: 2020年4月14日 16:10
收件人: PaddlePaddle/PaddleHub <PaddleHub@noreply.github.com&gt;
抄送: 670133189 <670133189@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/PaddleHub] PaddleHub &gt;= 1.6.0版本会出现重复下载【yolov3_darknet53_coco2017】模型 (#517)





 
@670133189 PaddleHub新增OCR模型已经在排期计划中，会在未来版本提供中文OCR模型，敬请期待。

**Comment by Steffy-zxf** [comment]
@670133189 感谢您的关注！OCR模型预计在5月份发布。

**Comment by Steffy-zxf** [comment]
@670133189 你好！目前ocr模型 PaddleHub已经上线，模型详情请参见 https://www.paddlepaddle.org.cn/hublist?filter=en_category&value=TextRecognition
