### ISSUE TITLE
自定义 多分类数据集

### ISSUE THREAD

**Issue by guowhite** [PaddlePaddle/PaddleFormers#518]
为什么样例数据的label是 list
但是根据要求自定义构建的数据集，label类型是str，导致程序报错

**Comment by Steffy-zxf** [comment]
@guowhite 你好！麻烦把背景说清楚些。同时贴上相应的报错堆栈信息。

**Comment by guowhite** [comment]
![个人数据集](https://user-images.githubusercontent.com/36331553/79180370-5789af00-7e3c-11ea-8e48-fbd2887dd06b.png)
这是我个人数据集，根据要求构建后，生成的label类型为str
但是我看dataset = hub.dataset.Toxic() 中的内容，label的类型为list
![样例数据集](https://user-images.githubusercontent.com/36331553/79180467-a0416800-7e3c-11ea-8667-704abf2b4bd7.png)

**Comment by Steffy-zxf** [comment]
你的写法是什么样的，可以参考下PaddleHub 定义Toxic数据集的写法https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/dataset/toxic.py#L39

**Comment by guowhite** [comment]
已解决。开始用的是文档里面的自定义数据加载
![1586916176](https://user-images.githubusercontent.com/36331553/79291220-a4cf5480-7f00-11ea-89c1-920fa8e1346f.jpg)

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
