### ISSUE TITLE
迁移学习 自定义数据集

### ISSUE THREAD

**Issue by thirteen-ypj** [PaddlePaddle/PaddleFormers#520]
用 Ernie进行中文情感分析时，自定义数据集，总是报错

IndexError: list index out of range

想问一下处理中文最大长度是多少？
我自己试了一下把text_b列的数据长度筛选为110才可以不报错

**Comment by kinghuin** [comment]
Hi,@thirteen-ypi   请贴一下完整的报错信息

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
