### ISSUE TITLE
hub serving 多进程使用

### ISSUE THREAD

**Issue by zhnglicho** [PaddlePaddle/PaddleFormers#521]
PaddleHub1.6.1，PaddlePaddle1.7.1
Linux，python 3.6.8

hub serving start --use_multiprocess **--workers 4** -m senta_cnn 
hub serving start --use_multiprocess **--workers 1** -m senta_cnn 

我用这2种方式启动服务， 并发处理能力没有任何变化， 请问是我用法的问题？

**Comment by ShenYuhan** [comment]
用法没有错误，您可以看下启动的进程数也是不同的，并发处理能力受硬件条件影响，您机器的cpu是几核的呢？

**Comment by zhnglicho** [comment]
cpu 是16核的， workers = 4， 会启动4个进程， workers=1 , 启动1个进程。 我做压测， 
workers=4, 和 workers =1 , qps 都是 300左右， 唯一区别就是 workers =1 , 单核cpu 使用率>90%, workers =4 时， 每个 进程的cpu 使用率在 20% 与 30 % 之间

**Comment by zhnglicho** [comment]
另外， 我看 hub serving start 命令不能传 gunicorn 支持的其它参数， 比如我想设置 access-logfile, 如何设置 ？

**Comment by ShenYuhan** [comment]
第一个是符合预期的，这也是多核的好处，再提高模型性能的话建议您可以调大batch_size，通过提升每次预测的数据个数来间接提高qps。
第二个问题，目前确实不支持，但这个需求我们会尽快完成，在未来的版本中增加更灵活的gunicorn参数配置。
