### ISSUE TITLE
使用vs2017无法通过编译，请问这是什么原因？

### ISSUE THREAD

**Issue by tyjsnz** [PaddlePaddle/PaddleFormers#522]
export_model.py已经下载好了模型，fluid_inference_install_dir 也下载了，在vs2017中加载demo文件mask_detector进行编译时lib库加载不了。opencv使用的是4.2，没有使用CUDA版本，编译产生 如下错误： 请问这是哪里没有设置对吗？

![image](https://user-images.githubusercontent.com/6022847/79304760-a27ef180-7f24-11ea-9876-24a8a1f6e3a7.png)

1>mask_detector.obj : error LNK2001: 无法解析的外部符号 "class std::unique_ptr<class paddle::PaddlePredictor,struct std::default_delete<class paddle::PaddlePredictor> > __cdecl paddle::CreatePaddlePredictor<struct paddle::AnalysisConfig>(struct paddle::AnalysisConfig const &)" (??$CreatePaddlePredictor@UAnalysisConfig@paddle@@@paddle@@YA?AV?$unique_ptr@VPaddlePredictor@paddle@@U?$default_delete@VPaddlePredictor@paddle@@@std@@@std@@AEBUAnalysisConfig@0@@Z)
1>mask_detector.obj : error LNK2001: 无法解析的外部符号 "public: class std::vector<int,class std::allocator<int> > __cdecl paddle::ZeroCopyTensor::shape(void)const " (?shape@ZeroCopyTensor@paddle@@QEBA?AV?$vector@HV?$allocator@H@std@@@std@@XZ)
1>mask_detector.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl paddle::ZeroCopyTensor::copy_to_cpu<float>(float *)" (??$copy_to_cpu@M@ZeroCopyTensor@paddle@@QEAAXPEAM@Z)
1>mask_detector.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl paddle::ZeroCopyTensor::copy_from_cpu<float>(float const *)" (??$copy_from_cpu@M@ZeroCopyTensor@paddle@@QEAAXPEBM@Z)
1>mask_detector.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl paddle::ZeroCopyTensor::Reshape(class std::vector<int,class std::allocator<int> > const &)" (?Reshape@ZeroCopyTensor@paddle@@QEAAXAEBV?$vector@HV?$allocator@H@std@@@std@@@Z)
1>mask_detector.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::EnableMemoryOptim(void)" (?EnableMemoryOptim@AnalysisConfig@paddle@@QEAAXXZ)
1>mask_detector.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::DisableGpu(void)" (?DisableGpu@AnalysisConfig@paddle@@QEAAXXZ)
1>mask_detector.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::EnableUseGpu(unsigned __int64,int)" (?EnableUseGpu@AnalysisConfig@paddle@@QEAAX_KH@Z)
1>mask_detector.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::SetModel(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SetModel@AnalysisConfig@paddle@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)
1>D:\project\MaskDetector\x64\Release\MaskDetector.exe : fatal error LNK1120: 9 个无法解析的外部命令

**Comment by sjtubinlong** [comment]
@tyjsnz 能否提供下你下载的 fluid_inference_install_dir 版本，以及编译的 CMAKE 参数设置。另外，2017 未充分测试，推荐使用 vs 2019开发。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
