### ISSUE TITLE
hub调用crmc保存时报错

### ISSUE THREAD

**Issue by binwang672012** [PaddlePaddle/PaddleFormers#523]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.6.1，PaddlePaddle1.7.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
ubuntu18.04, python 3.7.4 (conda)
- 复现信息：如为报错，请给出复现环境、复现步骤

在 paddle1.7.2中调用 crmc报错,在paddle1.6.2正常. 详细信息已在QQ上沟通,还望帮忙解决,感谢.
![Selection_081](https://user-images.githubusercontent.com/53250648/79450144-17325880-8017-11ea-9970-a37cdef3c1f7.jpg)

**Comment by kinghuin** [comment]
Hi, @binwang672012  paddle的下一个版本会解决这一问题 目前请暂时使用paddle1.6.2运行该任务
