### ISSUE TITLE
humanseg.segmentation(data={"image": files13},output_dir="./out/")  输出是否可以直接为图像数据

### ISSUE THREAD

**Issue by anthonyyuan** [PaddlePaddle/PaddleFormers#524]
路径输出 是否可以灵活，可以输出，
可以直接和CV2 利用
，比如直接输出一个IMG，
CV2 ，直接可以读取，不需要保存在文件里，保存用户自己处理

**Comment by Steffy-zxf** [comment]
感谢反馈！后续PaddleHub 会对deeplabv3p_xception65_humanseg module进行升级，到时就会支持您说的需求了，直接返回预测结果，是否保存成文件，用户可选。
