### ISSUE TITLE
如何手动下载模型？

### ISSUE THREAD

**Issue by peixin-lin** [PaddlePaddle/PaddleFormers#525]
你好，我想要在无法连接外网的机器上进行训练，请问如何预先下载好需要使用的模型，然后进行调用呢, 是否使用pub.Module(directory=..)即可？

**Comment by kinghuin** [comment]
Hi @peixin-lin 是的，可以用directory自定义路径 也可以将模型文件放入~/.paddlehub/module下再通过name的方式调用

**Comment by Steffy-zxf** [comment]
你好！你可以在可以访问外网环境的机器上下载paddlehub 以及 paddlepaddle 第三方库。安装完paddlehub 和 paddlepaddle之后，下载想要的预训练模型/数据集等，预训练模型/数据集存放在$HUB_HOME目录下。HUB_HOME是个环境变量，支持修改，参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/cmdintro.md#paddlehub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7
同时建议HUB_HOME路径不要带有中文名。

之后把你上面所有下载的东西，拷贝到无网的机器上。同时注意HUB_HOME的设置。

**Comment by applepieiris** [comment]
> 你好！你可以在可以访问外网环境的机器上下载paddlehub 以及 paddlepaddle 第三方库。安装完paddlehub 和 paddlepaddle之后，下载想要的预训练模型/数据集等，预训练模型/数据集存放在$HUB_HOME目录下。HUB_HOME是个环境变量，支持修改，参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/cmdintro.md#paddlehub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7 同时建议HUB_HOME路径不要带有中文名。
> 
> 之后把你上面所有下载的东西，拷贝到无网的机器上。同时注意HUB_HOME的设置。

请问windows上HUB_HOME设置在哪里？
