### ISSUE TITLE
TextClassifierTask能否加载指定checkpoint呢？

### ISSUE THREAD

**Issue by astronstar** [PaddlePaddle/PaddleFormers#526]
cls_task = hub.TextClassifierTask(
        data_reader=reader,
        feature=pooled_output,
        feed_list=feed_list,
        num_classes=dataset.num_labels,
        config=config,
        metrics_choices=["f1"])
hub.TextClassifierTask看了下日志，加载的是best文件夹的那个chkt，怎样加载指定的？看了源码，几个参数都不是支持这个的

**Comment by Steffy-zxf** [comment]
你好，你是想加载指定的ckpt整个文件夹吗？还是指定的ckpt文件夹下保存的具体参数文件？

**Comment by astronstar** [comment]
> 你好，你是想加载指定的ckpt整个文件夹吗？还是指定的ckpt文件夹下保存的具体参数文件？

是某一轮的checkpoint，它默认加载的是best里面的。

**Comment by Steffy-zxf** [comment]
你是预测是吧， 预测predict接口有一个参数load_best_model指定为False，就会加载Fine-tune时保存的最后一个step的参数。[predict接口](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/base_task.py#L985)

同时Task提供了[load_parameters接口](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/base_task.py#L837) 可以加载指定的参数， 用法如下
```python
with task.phase_guard('predict'):
    task.load_parameters('path/to/parameters')
```

**Comment by Steffy-zxf** [comment]
你好，此issue在近两月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
