### ISSUE TITLE
请问文本二分类的那个模型固定seed了吗？

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/PaddleFormers#529]
我看他代码里写的seed=0？这是固定了吗？？请问paddle有全局固定seed的那种工具吗？

**Comment by Steffy-zxf** [comment]
你好！你指的"文本二分类的那个模型"是哪个模型，方便给下链接吗？可以设置program的seed，方法如下：
```python

# program是paddle的Program类对象
# SEED是你想要设置的随机种子数
program.random_seed = SEED
```

**Comment by wxl1351641822** [comment]
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/classifier_task.py#L29

**Comment by Steffy-zxf** [comment]
你可以参考我上述回复的方式，固定program的随机种子。

**Comment by wxl1351641822** [comment]
好的，谢谢
