### ISSUE TITLE
hub serving服务，某些照片报500错误

### ISSUE THREAD

**Issue by YasinZhao** [PaddlePaddle/PaddleFormers#533]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

版本、环境信息：
1）paddlepaddle_gpu=1.7.0  paddlehub=1.5.4
2）系统环境：Linux，服务器部署模型服务python3.6，win10调用服务的脚本python3.7
老师你好，我使用贵司开源的paddlehub serving功能部署了pyramidbox_lite_server服务，然后在调用服务时，遇到有4张图片，无论是curl命令，还是python脚本都出现500错误，具体见下图：

C:\Users\zhaoyi-036\Desktop\cv\多人脸检测\imgs>curl -X POST -F "image=@FL_DB_FL202003310858058150aLdh4.jpg" http://10.182.107.219:8866/predict/image/pyramidbox_lite_server
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

想请问老师，为什么会报500错误，按理应该是200，但无返回结果这样子的吗？此外，这4张图片，在win10系统上进行另存操作后，再调用服务又可以通过了，也没搞清楚是为什么，还请老师能帮忙看下，给予解答。

**Comment by nepeplwu** [comment]
@YasinZhao 感谢反馈，我们跟进了下，这个问题是因为图片没有检测到人脸，而serving处理无人脸图片时的逻辑存在问题，导致出现异常，后续我们将会修复这个问题

**Comment by YasinZhao** [comment]
> @YasinZhao 感谢反馈，我们跟进了下，这个问题是因为图片没有检测到人脸，而serving处理无人脸图片时的逻辑存在问题，导致出现异常，后续我们将会修复这个问题

好的，明白了，谢谢老师的解答~
