### ISSUE TITLE
请问是否有layer transfer的方法？

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/PaddleFormers#536]
![image](https://user-images.githubusercontent.com/42665925/79965800-11c58a00-84bf-11ea-9f82-7decdf1f328c.png)
就是只加载部分预训练参数，而其他预训练参数随机初始化？
请问有实现这个的方法吗？在网络搭建完成，预训练参数加载前或者能否重新初始化bert部分的预训练参数？

**Comment by wxl1351641822** [comment]
或者不引入预训练参数仅引入bert模型的方法？

**Comment by kinghuin** [comment]
Hi，@wxl1351641822 。 实现这个功能需要修改paddlehub源码，您可以使用pip show paddlehub找到paddlehub安装路径，再修改https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/module/nlp_module.py#L261，参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/load_vars_cn.html#load-vars 为它指定vars参数

**Comment by wxl1351641822** [comment]
```
 def init_pretraining_params(self, exe, pretraining_params_path,
                                main_program):
        assert os.path.exists(
            pretraining_params_path
        ), "[%s] cann't be found." % pretraining_params_path

        def existed_params(var):
            if not isinstance(var, fluid.framework.Parameter):
                return False
            return os.path.exists(
                os.path.join(pretraining_params_path, var.name))

        fluid.io.save_vars(executor=exe, dirname='./pureparam', main_program=main_program, vars=None, predicate=existed_params)

        fluid.io.load_vars(
            exe,
            pretraining_params_path,
            main_program=main_program,
            predicate=existed_params)
        logger.info("Load pretraining parameters from {}.".format(
            pretraining_params_path))
```
在这个里面我加了这个
```
fluid.io.save_vars(executor=exe, dirname='./pureparam', main_program=main_program, vars=None, predicate=existed_params)`
```
[你说的这个链接的这个位置](https://github.com/PaddlePaddle/PaddleHub/blob/15d102eb1de4405f9fc40766504a1002a97b19cf/paddlehub/module/nlp_module.py#L261)加的
我想保存一个初始化版本的参数，然后到时候替换一下之类的。
但是报错了：

> ----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Tensor in the save Op's Input Variable X(@HUB_bert_chinese_L-12_H-768_A-12@word_embedding) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] at (D:\1.7.0\paddle\paddle\fluid\framework\operator.cc:1264)
  [operator < save > error]

**Comment by wxl1351641822** [comment]
请问这个是什么情况，我看他代码里初始化了？但这里却还没有初始化？
`self._param_initializer = fluid.initializer.TruncatedNormal(
            scale=config['initializer_range'])`

**Comment by wxl1351641822** [comment]
fluid.io.save_vars(executor=exe, dirname='./pureparam', main_program=main_program, vars=None, predicate=existed_params)`
这个我改了
我加了个
exe.run(startup_program)
和
```
        def find(var):
            match = re.match(r'.*layer_(\d+).*', var.name)
            if match:
                return True
            else:
                return False

        fluid.io.save_vars(executor=exe, dirname='./pureparam', main_program=main_program,predicate=find)
```
但他还是一样的错误
他是何时初始化的呢？他的initializer不能以save保存吗？

**Comment by kinghuin** [comment]
初始化的位置不正确，请在这行https://github.com/PaddlePaddle/PaddleHub/blob/15d102eb1de4405f9fc40766504a1002a97b19cf/paddlehub/module/nlp_module.py#L339
后面进行初始化，

```python
        vars = filter(lambda var: "tmp" not in var,
                      list(module_program.global_block().vars.keys())[4:])
        此处初始化
        paddle_helper.add_vars_prefix(
            program=module_program, prefix=self.param_prefix(), vars=vars)
```
修改后：
```python
        vars = filter(lambda var: "tmp" not in var,
                      list(module_program.global_block().vars.keys())[4:])
        paddle_helper.add_vars_prefix(
            program=startup_program, prefix=self.param_prefix())
        exe.run(startup_program)
        paddle_helper.add_vars_prefix(
            program=module_program, prefix=self.param_prefix(), vars=vars)
```

**Comment by wxl1351641822** [comment]
大概是好了，谢谢。
