### ISSUE TITLE
在预测时获取并保存隐藏层的特征

### ISSUE THREAD

**Issue by CSU-NXY** [PaddlePaddle/PaddleFormers#537]
我参考[这篇教程](https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E6%96%87%E6%9C%AC%E5%88%86%E7%B1%BB%E8%BF%81%E7%A7%BB%E6%95%99%E7%A8%8B)成功finetune了一个任务，请问如何在predict的时候读取并保存隐藏层的输出（比如文中的句子粒度特征pooled_output）呢？

**Comment by Steffy-zxf** [comment]
你好！你可以在相应的Task的fetch_list添加你想要获取的隐藏层参数，如文本分类任务[fetch_list](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/classifier_task.py#L317), 之后运行[Executor.run](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/base_task.py#L1079)即可将参数拿到。另外，如果你只是想要拿到ERNIE/BERT等预训练保存的句子粒度特征pooled_output，可以参考[get_embedding](https://www.paddlepaddle.org.cn/hubdetail?name=ERNIE&en_category=SemanticModel)接口。
![image](https://user-images.githubusercontent.com/48793257/80050401-12563300-8548-11ea-9f1d-ce98c4ce9279.png)

**Comment by CSU-NXY** [comment]
谢谢你的回答！

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
