### ISSUE TITLE
将paddledetection训练得到的best_model转换成paddlehub需要的module

### ISSUE THREAD

**Issue by GodMmmm** [PaddlePaddle/PaddleFormers#538]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

**Comment by GodMmmm** [comment]
> 欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
> 在留下您的建议时，辛苦您同步提供如下信息：
> 
> * 您想要增加什么新特性？
> * 什么样的场景下需要该特性？
> * 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
> * 增加该特性，PaddleHub可能需要变化的部分。
> * 如果可以的话，简要描述下您的解决方案

请问有相关文档可供学习吗  我只看到关于finetune后的模型转换的文档

**Comment by Steffy-zxf** [comment]
你好！将paddledetection训练得到的best_model转换成paddlehub需要的module， 你可以参考 这篇文档 https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/contribution/contri_pretrained_model.md

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
