### ISSUE TITLE
hub yolov3_darknet53_coco2017 模型，能解析opencv 视频帧 ?

### ISSUE THREAD

**Issue by DavidFangx** [PaddlePaddle/PaddleFormers#539]
hub yolov3_darknet53_coco2017 模型 分析图片是可以的：
           file_list = [config.handleImagePath + imageName]
            input_dict = {"image": file_list}
            results = AI_Module.object_detection(data=input_dict)

**目前有个需求，需要实时解析视频码流，测试多了当frame为 opencv视频帧，传入作为参数，报错了。**

  input_dict = {"image": [frame]}  # frame 为视频帧 
  results = AI_Module.object_detection(data=input_dict)

报这个错误： 
assert os.path.isfile(path), "The {} isn't a valid file path.".format(path) 

谢谢

**Comment by Steffy-zxf** [comment]
你好！感谢反馈！目前yolov3_darknet53_coco2017还不支持传入图片帧数据，只支持传入图片路径。后续paddlehub会对CV类module进行升级，支持传入图片帧数据。

**Comment by DavidFangx** [comment]
好的，期待....

**Comment by linshuliang** [comment]
你好，我们已经升级了 object detection 的模型，现处于测试阶段，计划在5月中旬发布更新版本。

**Comment by DavidFangx** [comment]
你好，
hub yolov3_darknet53_coco2017 模型，这个模型解析速度 2秒/张图片，能优化吗？
还有就是每次运行这个模型，都从百度重新下载，不知道是什么问题？

**Comment by DavidFangx** [comment]
人脸口罩模型，速度和精度都不错，同时支持图片和视频流分析！！！ 希望  yolov3_darknet53_coco2017 以及其他模型 都能有这个好的效果
感谢！！！
