### ISSUE TITLE
微调roberta模型问题

### ISSUE THREAD

**Issue by Antlerkeke** [PaddlePaddle/PaddleFormers#540]
在paddlepaddle1.6.2下
module = hub.Module(name="roberta_wwm_ext_chinese_L-24_H-1024_A-16")
微调时总是自动重启页面环境，无法微调。

**Comment by Steffy-zxf** [comment]
你好，页面重启是在什么样的背景下发生的呢？是AIStudio吗？麻烦把背景和问题说的详细些，方便排查问题。

**Comment by Antlerkeke** [comment]
您好，重启是在每次进行任务进行finetune_and_eval()时输出PaddleHub finetune start后页面右上角就会提示自动重启中，AI studio项目地址https://aistudio.baidu.com/aistudio/projectdetail/389985，感谢！

**Comment by Steffy-zxf** [comment]
@Antlerkeke 你好，你的项目还需要公开，现在是私密状态，无法查看。

**Comment by Antlerkeke** [comment]
已公开。麻烦您再次查看

**Comment by Steffy-zxf** [comment]
@Antlerkeke 建议你的batch_size设置小一些。batch_size和max_seq_len会影响占用的运行内存。另外由于roberta-large/ERNIE等模型参数量级较大，建议使用GPU环境运行。

**Comment by Antlerkeke** [comment]
谢谢，确实是因为batchsize太大了，已经解决了
