### ISSUE TITLE
如何获取迁移学习后的模型？

### ISSUE THREAD

**Issue by guchuanhang** [PaddlePaddle/PaddleFormers#547]
1.基于resnet_v2_50_imagenet，进行猫狗分类后，如何保存这个模型？

**Comment by daniao2017** [comment]
可以报名参加[百度的Python小白逆袭大神](https://aistudio.baidu.com/aistudio/education/group/info/1224)课程，看一下day4的作业
```
config = hub.RunConfig(
    use_cuda=False,                              #是否使用GPU训练，默认为False；
    num_epoch=3,                                #Fine-tune的轮数；
    checkpoint_dir="cv_finetune_turtorial_demo",#模型checkpoint保存路径, 若用户没有指定，程序会自动生成；
    batch_size=3,                              #训练的批大小，如果使用GPU，请根据实际情况调整batch_size；
    eval_interval=10,                           #模型评估的间隔，默认每100个step评估一次验证集；
    strategy=hub.finetune.strategy.DefaultFinetuneStrategy())  #Fine-tune优化策略；
```
记得点下star，让我们多点得奖机会~

**Comment by Steffy-zxf** [comment]
@guchuanhang 你好! 用PaddleHub 迁移学习功能会自动保存训练时最好的模型，模型保存在RunConfig中指定的checkpoint_dir路径中。

**Comment by guchuanhang** [comment]
多谢，周末试一下。

**Comment by guchuanhang** [comment]
首先，AI Studio PaddleHub进行图像分类，有像上面的保存的代码。并且在那一份文档上测试的时候也有打印：
`[2020-05-01 08:43:20,098] [    INFO] - Load the best model from ./cv_finetune_turtorial_demo/best_model`
可是在当前目录下就是搜索不到这个文件夹。在unbuntu下切换到root帐号，从根目录执行
`find  / -name cv_finetune_turtorial_demo -type d `也搜素不到任何结果。

深度学习7日入门-CV疫情特辑 -> 课节5 PaddleHub体验 -> PaddleHub进行图像分类
