### ISSUE TITLE
`CUDA_VISIBLE_DEVICES` 没有设置 | 没有属性 `gpu_predictor`

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/PaddleFormers#548]
在`AIstudio`运行demo“PaddleHub人脸检测示例”：
[https://aistudio.baidu.com/aistudio/projectdetail/215962](https://aistudio.baidu.com/aistudio/projectdetail/215962)

将`module.face_detection`中的`use_gpu`设置为`True`
报错，说环境变量没有正确设置:
```
RuntimeError: Attempt to use GPU for prediction, but environment variable CUDA_VISIBLE_DEVICES was not set correctly.
```

我尝试设置环境变量：
```
%set_env CUDA_VISIBLE_DEVICES=0
```
再次执行：`module.face_detection`

再次报错：
```
AttributeError: 'FaceDetector640' object has no attribute 'gpu_predictor'
```
这是环境的问题还是paddlehub的问题？

麻烦帮忙看一下

**Comment by nepeplwu** [comment]
@DrRyanHuang ，项目启动的时候，有选择GPU环境吗？

**Comment by DrRyanHuang** [comment]
> @DrRyanHuang ，项目启动的时候，有选择GPU环境吗？

@nepeplwu 
选择了GPU环境

**Comment by nepeplwu** [comment]
@DrRyanHuang ，重启下项目，把环境变量的设置放在最前面执行，试试看这样是否ok

**Comment by DrRyanHuang** [comment]
@nepeplwu 嗯嗯，这次可以使用
