### ISSUE TITLE
paddlehub不能通过__version__来查看版本吗？

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/PaddleFormers#552]
为了做版本兼容，需要查看paddlehub的版本号，paddlehub不能通过__version__来查看版本吗？
手动`pip list`有点儿麻烦...

**Comment by nepeplwu** [comment]
@DrRyanHuang 使用如下方式获取
```python
import paddlehub as hub
print(hub.version.hub_version)
```

**Comment by DrRyanHuang** [comment]
@nepeplwu 十分感谢，太粗心了，我在paddlehub的帮助文档上没有找到，我搜了一下也没找到，写篇博客吧嘿嘿
