### ISSUE TITLE
目标检测迁移任务

### ISSUE THREAD

**Issue by MimeZoe0628** [PaddlePaddle/PaddleFormers#557]
想用SSD_Mobilenet在自定义的数据上做迁移学习，请问目前有可用的目标检测的迁移任务接口吗？
如果自己添加的话，需要在源码内部添加/修改哪些部分的内容？需要自己添加的内容在paddle其他项目有没有可参考的代码？

**Comment by nepeplwu** [comment]
@MimeZoe0628 感谢反馈，目前PaddleHub还不支持目标检测的迁移任务，可以参考[PaddleX 示例demo](https://paddlex.readthedocs.io/zh_CN/latest/tutorials/train/detection.html)，建议使用yolo而不是ssd

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
