### ISSUE TITLE
NLP类任务自定义数据

### ISSUE THREAD

**Issue by bazhe666** [PaddlePaddle/PaddleFormers#560]
from paddlehub.dataset.base_nlp_dataset import BaseNLPDataset

ModuleNotFoundError: No module named 'paddlehub.dataset.base_nlp_dataset'

**Comment by Steffy-zxf** [comment]
你好！运行环境中的paddlehub版本是多少？请升级paddlehub至最新版本1.6.2
```shell
pip install -U paddlehub
```

**Comment by wannabe-X** [comment]
你好，按照PaddleHub适配NLP类自定义数据完成finetune。数据读不进去。报错Exception: the train file: ./dataset/train.tsv only has one column but it is not a predict file 。我的数据格式为：15.4寸笔记本的键盘确实爽，基本跟台式机差不多了，蛮喜欢数字小键盘，输数字特方便，样子也很美观，做工也相当不错    1

**Comment by Steffy-zxf** [comment]
@wannabe-X ，你好！ 关于自定义数据参考[文档说明](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/how_to_load_data.md)
或者[自定义数据文本分类任务教程](https://aistudio.baidu.com/aistudio/projectdetail/221999)，其中第一部分——PART I. 加载自定义数据集，有相应的代码示例。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
