### ISSUE TITLE
为何本机实验口罩检测，系统提示找不到Module

### ISSUE THREAD

**Issue by lee83214** [PaddlePaddle/PaddleFormers#563]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：
paddlehub                          1.6.0
paddlepaddle                       1.7.2
2）系统环境：请您描述系统类型，例如Windows10，python版本 Python 3.7.4
3）遇到的问题: 在本机实验(Jupyter note界面)口罩检测功能时，提示找不到Module
代码:
import paddlehub as hub
import cv2

#hub.Module?

module = hub.Module(name="pyramidbox_lite_mobile_mask")

test_img_path = "test.jpeg"

# set input dict
input_dict = {"data": [cv2.imread(test_img_path)]}
results = module.face_detection(data=input_dict)
print(results)

报错提示:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-bb865ad5b851> in <module>
      4 #hub.Module?
      5 
----> 6 module = hub.Module(name="pyramidbox_lite_mobile_mask")
      7 
      8 test_img_path = "test.jpeg"

AttributeError: module 'paddlehub' has no attribute 'Module'

**Comment by Steffy-zxf** [comment]
你好！请确认运行环境中paddlehub是否为我们的PaddleHub第三方库，在cmd下运行以下命令检查
```
C:\> where paddlehub
```

**Comment by lee83214** [comment]
输入这条命令的结果是“信息: 用提供的模式无法找到文件。”
(base) C:\Users\86135>where paddlehub
信息: 用提供的模式无法找到文件。

我之前安装的时候是用下面这条指令安装的，为何没有能引用上，奇怪了。
pip install paddlehub==1.6.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by Steffy-zxf** [comment]
出现上述问题，一般是运行环境设置不正确，请检查环境变量设置等。

**Comment by lee83214** [comment]
由于这个配置有什么建议么？没有找到什么帮助文档。我装其他的库就这么安装的，基本都能直接使用:(

**Comment by Steffy-zxf** [comment]
建议可以直接在你的运行机器上安装一个anaconda，之后利用conda创建一个纯净的python3环境。

**Comment by lee83214** [comment]
我一直是安装的anaconda，然后pip和conda的安装方式反复试了几次都不行:(

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
