### ISSUE TITLE
如何获取预测结果的置信度

### ISSUE THREAD

**Issue by heyimabu** [PaddlePaddle/PaddleFormers#564]
现在使用task.predict(data=data, return_result=True)方法智能回去一个值，如果不准确就100%不准了，
想要获取置信度前三的结果，如何处理?

**Comment by Steffy-zxf** [comment]
你好！你是想做什么任务呢？Task.predict接口参数return_result=True会直接返回相应的预测结果，如果return_result=False，会返回模型的预测结果，如分类概率等。比如你想完成文本分类任务，可以参考PaddleHub release/v1.4分支后处理写法，https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.4/demo/text_classification/predict.py#L94

```python
    run_states = cls_task.predict(data=data, return_result=False)
    results = [run_state.run_results for run_state in run_states]
    # batch_result是一个batch输入的预测对应每个类别的概率值
    for batch_result in results:
        # 取分类概率最大值作为相应的预测类别
        batch_result = np.argmax(batch_result, axis=2)[0]
        for result in batch_result:
            print("%s\tpredict=%s" % (data[index][0], result))
            index += 1
```

如果你想完成其他的任务，可以参考其他demo的后处理写法。

**Comment by heyimabu** [comment]
多谢，通过源码已经找到了解决方法
