### ISSUE TITLE
PaddleHub 阅读理解

### ISSUE THREAD

**Issue by childe-wuhen** [PaddlePaddle/PaddleFormers#566]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.7.2post97，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
 执行PaddleHub 阅读理解demo代码时，在Step2，max_seq_len=384，出现报错：TypeError: __init__() got an unexpected keyword argument 'max_seq_length'。在去掉这个参数后，执行又出现：Dataset is None or it has not any labels, label map = {}

**Comment by Steffy-zxf** [comment]
你好！方便贴出你写的代码以及完成的报错堆栈信息吗？一般出现上述错误，是代码写的不对，建议可以参考PaddleHub的[阅读理解demo](https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.6/demo/reading_comprehension)

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
