### ISSUE TITLE
autofinetune可以断点重启吗

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/PaddleFormers#567]
它跑了4个round之后挂了……orz，可以断点重启吗

**Comment by Steffy-zxf** [comment]
你好！由于PaddleHub超参优化AutoDL超参的产生带有一定随机因素，恢复训练的话没有办法捕捉之前训练产生的超参信息。故超参优化AutoDL无法恢复断点。你可以看看是什么原因导致4个round挂了的？可以在每个round文件下面有log-***.info文件里面查看错误信息。
