### ISSUE TITLE
TextClassifierTask

### ISSUE THREAD

**Issue by 09094080-Tao-Jiao** [PaddlePaddle/PaddleFormers#57]
error: module 'paddlehub' has no attribute 'TextClassifierTask'

**Comment by Steffy-zxf** [comment]
由于PaddleHub中的task做了些变动。如果安装的paddlehub版本是0.5.1，则会出现相应的错误。如果想用0.5.1版本的paddlehub运行demo，可以切换到paddlehub仓库的release/v0.5.0分支下，就可以正常运行了。
