### ISSUE TITLE
paddlehub无法启动bert service的服务端

### ISSUE THREAD

**Issue by remarkableJ** [PaddlePaddle/PaddleFormers#572]
1）paddlehub1.6.2，paddlepaddle1.7.2，paddle-gpu-serving0.8.2
2）Linux系统，python3.6.6
- 复现信息：paddlehub无法启动bert service的服务端
- 命令行：hub serving start bert_service -m ernie -p 8866
- 报错信息：未报错，但是不显示Server[baidu::paddle_serving::predictor::bert_service::BertServiceImpl] is serving on port=8866.
- 报错信息：
32           0x16f29e7p baidu::paddle_serving::predictor::ReloadableInferEngine::proc_initialize_impl(baidu::paddle_serving::configure::EngineDesc const&, bool) + 311
33           0x16f88a0p baidu::paddle_serving::predictor::ReloadableInferEngine::proc_initialize(baidu::paddle_serving::configure::EngineDesc const&, bool) + 32
34           0x1707b8ep baidu::paddle_serving::predictor::CloneDBReloadableInferEngine<baidu::paddle_serving::fluid_cpu::FluidCpuAnalysisDirCore>::proc_initialize(baidu::paddle_serving::configure::EngineDesc const&, bool) + 110
35           0x3c6bea2p baidu::paddle_serving::predictor::VersionedInferEngine::proc_initialize(baidu::paddle_serving::configure::EngineDesc const&, bool) + 338
36           0x3c6cf49p baidu::paddle_serving::predictor::InferManager::proc_initialize(char const*, char const*) + 521
37           0x3c69ca0p baidu::paddle_serving::predictor::Resource::initialize(std::string const&, std::string const&) + 256
38           0x1649392p main + 482
39      0x7fbfc4fe2505p __libc_start_main + 245
40           0x1670c01p

**Comment by MRXLT** [comment]
你好，请问未报错是指的什么情况，可以发一下启动服务出错后的截图吗

**Comment by remarkableJ** [comment]
> 
> 
> 你好，请问未报错是指的什么情况，可以发一下启动服务出错后的截图吗
![捕获](https://user-images.githubusercontent.com/45261220/81460423-ceb22900-91d7-11ea-92be-53b58a2b4797.JPG)

**Comment by MRXLT** [comment]
有没有更多的信息，看图中应该只是一部分

**Comment by remarkableJ** [comment]
> 
> 
> 有没有更多的信息，看图中应该只是一部分
![1](https://user-images.githubusercontent.com/45261220/81470044-1dcd7d80-921b-11ea-9a35-efdf25be9fa5.JPG)
![2](https://user-images.githubusercontent.com/45261220/81470055-2de55d00-921b-11ea-903b-6c693fe23a49.JPG)
![3](https://user-images.githubusercontent.com/45261220/81470058-2e7df380-921b-11ea-98e7-db9852438f3a.JPG)

**Comment by remarkableJ** [comment]
我的机器没有卡，请问会不会是这种情况造成的

**Comment by MRXLT** [comment]
有可能是CUDA环境问题，CUDA版本、GPU型号、系统版本是什么样的。
也可以先试一下新版的bert service，不过目前只支持中文模型
https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/bert
https://github.com/PaddlePaddle/Serving

**Comment by MRXLT** [comment]
> 我的机器没有卡，请问会不会是这种情况造成的

看报错是因为跑gpu模式没有找到gpu导致的，但是不指定--use_gpu和--gpu的时候应该是跑cpu模式的。

如果是中文模型的话可以先使用新版本的bert service
https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/bert
安装方式
https://github.com/PaddlePaddle/Serving#installation

**Comment by remarkableJ** [comment]
> 
> 
> > 我的机器没有卡，请问会不会是这种情况造成的
> 
> 看报错是因为跑gpu模式没有找到gpu导致的，但是不指定--use_gpu和--gpu的时候应该是跑cpu模式的。
> 
> 如果是中文模型的话可以先使用新版本的bert service
> https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/bert
> 安装方式
> https://github.com/PaddlePaddle/Serving#installation

谢谢，可以了
