### ISSUE TITLE
hub serving start --modules pose_resnet50_mpii

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/PaddleFormers#573]
hub serving start --modules pose_resnet50_mpii 
启动关键点检测后，预测时报错误
![7D8_RS8U7B0} 46X(R3(2}I](https://user-images.githubusercontent.com/62418900/81274904-84b82e80-9083-11ea-92a4-5a99b056e55d.png)

**Comment by mcl-stone** [comment]
> hub serving start --modules pose_resnet50_mpii
> 启动关键点检测后，预测时报错误
> ![7D8_RS8U7B0} 46X(R3(2}I](https://user-images.githubusercontent.com/62418900/81274904-84b82e80-9083-11ea-92a4-5a99b056e55d.png)
显示模型名字不对，用浏览器访问也是同样错误。

**Comment by ShenYuhan** [comment]
您好，您用的哪个版本，建议升级最新版paddlehub然后再使用hub-serving测试。

**Comment by mcl-stone** [comment]
> 您好，您用的哪个版本，建议升级最新版paddlehub然后再使用hub-serving测试。

我是使用的最新的版本，您那能试下吗？刚才在群里大家也试过了

**Comment by mcl-stone** [comment]
> 您好，您用的哪个版本，建议升级最新版paddlehub然后再使用hub-serving测试。

跑起来没有问题的，进行预测的时候出现问题

**Comment by ShenYuhan** [comment]
您好，目前建议您手动在paddlehub/serving/app_single.py中加入这段代码
```python
def predict_human_pose_estimation(module_info, input_img, id, extra={}):
    output_folder = "output_pose"
    method_name = module_info["method_name"]
    module = module_info["module"]
    predict_method = getattr(module, method_name)

    predict_args = module_info["predict_args"].copy()
    predict_args.update({"data": {"image": input_img}})

    if isinstance(predict_method, functools.partial):
        predict_method = predict_method.func
        predict_args.update({"sign_name": method_name})
    for item in predict_method.__code__.co_varnames:
        if item in module_info.keys():
            predict_args.update({item: module_info[item]})
    try:
        results = predict_method(**predict_args)
    except Exception as err:
        curr = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time()))
        print(curr, " - ", err)
        return gen_result("-1", "Please check data format!", "")
    finally:
        base64_list = []
        results_pack = []
        for index in range(len(input_img)):
            item = input_img[index]
            result_item = "rendered_" + item
            with open(os.path.join(output_folder, result_item), "rb") as fp:
                b_head = "data:image/" + item.split(".")[-1] + ";base64"
                b_body = base64.b64encode(fp.read())
                b_body = str(b_body).replace("b'", "").replace("'", "")
                b_img = b_head + "," + b_body
                base64_list.append(b_img)
                results[index]["path"] = results[index]["path"].replace(
                    id + "_", "")
                results[index].update({"base64": b_img})
                results_pack.append(results[index])
            os.remove(item)
            os.remove(os.path.join(output_folder, result_item))
    return gen_result("0", "", str(results_pack))
```
代码在这里https://github.com/ShenYuhan/PaddleHub/blob/c1a773c03ea4d7c194f85209dd653a07ba39edb9/paddlehub/serving/app_single.py#L238

另外，您说的群是哪个群，我在里面回复下大家。

**Comment by ShenYuhan** [comment]
另外现在`pose_resnet50_mpii`模型的`1.1.0`版本已经上线，您可以通过指定版本下载新版的模型，但模型名改为了 `human_pose_estimation_resnet50_mpii `,新版模型使用paddlehub-serving的方式也给了详细的示例说明，您可以参考[human_pose_estimation_resnet50_mpii](https://paddlepaddle.org.cn/hubdetail?name=human_pose_estimation_resnet50_mpii&en_category=KeyPointDetection)

**Comment by mcl-stone** [comment]
> 您好，目前建议您手动在paddlehub/serving/app_single.py中加入这段代码
> 
> ```python
> def predict_human_pose_estimation(module_info, input_img, id, extra={}):
>     output_folder = "output_pose"
>     method_name = module_info["method_name"]
>     module = module_info["module"]
>     predict_method = getattr(module, method_name)
> 
>     predict_args = module_info["predict_args"].copy()
>     predict_args.update({"data": {"image": input_img}})
> 
>     if isinstance(predict_method, functools.partial):
>         predict_method = predict_method.func
>         predict_args.update({"sign_name": method_name})
>     for item in predict_method.__code__.co_varnames:
>         if item in module_info.keys():
>             predict_args.update({item: module_info[item]})
>     try:
>         results = predict_method(**predict_args)
>     except Exception as err:
>         curr = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time()))
>         print(curr, " - ", err)
>         return gen_result("-1", "Please check data format!", "")
>     finally:
>         base64_list = []
>         results_pack = []
>         for index in range(len(input_img)):
>             item = input_img[index]
>             result_item = "rendered_" + item
>             with open(os.path.join(output_folder, result_item), "rb") as fp:
>                 b_head = "data:image/" + item.split(".")[-1] + ";base64"
>                 b_body = base64.b64encode(fp.read())
>                 b_body = str(b_body).replace("b'", "").replace("'", "")
>                 b_img = b_head + "," + b_body
>                 base64_list.append(b_img)
>                 results[index]["path"] = results[index]["path"].replace(
>                     id + "_", "")
>                 results[index].update({"base64": b_img})
>                 results_pack.append(results[index])
>             os.remove(item)
>             os.remove(os.path.join(output_folder, result_item))
>     return gen_result("0", "", str(results_pack))
> ```
> 
> 代码在这里https://github.com/ShenYuhan/PaddleHub/blob/c1a773c03ea4d7c194f85209dd653a07ba39edb9/paddlehub/serving/app_single.py#L238
> 
> 另外，您说的群是哪个群，我在里面回复下大家。

我是在qq的飞桨交流3群的

**Comment by mcl-stone** [comment]
> 另外现在`pose_resnet50_mpii`模型的`1.1.0`版本已经上线，您可以通过指定版本下载新版的模型，但模型名改为了 `human_pose_estimation_resnet50_mpii `,新版模型使用paddlehub-serving的方式也给了详细的示例说明，您可以参考[human_pose_estimation_resnet50_mpii](https://paddlepaddle.org.cn/hubdetail?name=human_pose_estimation_resnet50_mpii&en_category=KeyPointDetection)

添加了您的代码，关键点检测可以了!hub serving start -m yolov3_darknet53_coco2017这个还是有点问题，一样的问题，新版本有问题，老版本没有问题的

**Comment by ShenYuhan** [comment]
您可以查看下这个模型的使用说明，对serving的部署有详细的说明[yolov3_darknet53_coco2017](https://paddlepaddle.org.cn/hubdetail?name=yolov3_darknet53_coco2017&en_category=ObjectDetection)
新版本的调用方式和旧版本稍有不同，建议使用新版本，使用新的paddlehub-serving部署和调用方法。

**Comment by mcl-stone** [comment]
> 您可以查看下这个模型的使用说明，对serving的部署有详细的说明[yolov3_darknet53_coco2017](https://paddlepaddle.org.cn/hubdetail?name=yolov3_darknet53_coco2017&en_category=ObjectDetection)
> 新版本的调用方式和旧版本稍有不同，建议使用新版本，使用新的paddlehub-serving部署和调用方法。

好的！感谢！
