### ISSUE TITLE
服务器部署后，可代码调用但端口访问有界面无法运行

### ISSUE THREAD

**Issue by shinichiye17** [PaddlePaddle/PaddleFormers#574]
在AI Studio上跟着教程实现PaddleHub口罩检测项目 [项目地址](https://aistudio.baidu.com/aistudio/projectdetail/456915)
执行到服务器部署步骤，在本地运行那行命令后，有warning“WARNING: This is a development server. Do not use it in a production deployment.”之后在客户端代码调用成功，尝试打开0.0.0.0:8866接口，接口有界面，但是运行报错“Connection error:undefined”，具体截图在项目地址也可查看。

**Comment by ShenYuhan** [comment]
您好，hub-serving没有web页面，您提到的那个页面是供我们开发测试使用的，实际上并不对外展示。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
