### ISSUE TITLE
RunConfig里设置的batch_size的大小，怎么计算需要多少内存

### ISSUE THREAD

**Issue by baolicai** [PaddlePaddle/PaddleFormers#575]
RunConfig里设置的batch_size这个参数有什么作用，batch_size的大小，怎么计算需要多少内存

**Comment by MrChengmo** [comment]
请问具体是哪个模型？

**Comment by Steffy-zxf** [comment]
@baolicai 你好！RunConfig中的batch_size的作用是程序运行program（搭建的神经网络）的时候，program每运行一次需要处理的样本数量。RunConifg API文档说明：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/reference/config.md

内存的占用不仅和batch_size有关，还和模型参数大小有关系。

**Comment by baolicai** [comment]
> 请问具体是哪个模型？

ernie模型，我同样的训练数据，我本地用windows训练 batch_size 设置的 32，跑10次step 需要6分钟，放到Linux机器上 batch_size 设置的 128 ，跑10次step 需要1小时......

**Comment by baolicai** [comment]
> @baolicai 你好！RunConfig中的batch_size的作用是程序运行program（搭建的神经网络）的时候，program每运行一次需要处理的样本数量。RunConifg API文档说明：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/reference/config.md
> 
> 内存的占用不仅和batch_size有关，还和模型参数大小有关系。

用的ernie模型，我同样的训练数据，我本地用windows训练 batch_size 设置的 32，跑10次step 需要6分钟，放到Linux机器上 batch_size 设置的 128 ，跑10次step 需要1小时......

**Comment by Steffy-zxf** [comment]
@baolicai batch_size设置大，一个step（处理一个batch）运行的时间自然也就增大了。同时处理速度还和你的运行硬件有关。

**Comment by baolicai** [comment]
> @baolicai batch_size设置大，一个step（处理一个batch）运行的时间自然也就增大了。同时处理速度还和你的运行硬件有关。

请问怎么使用多核训练，我现在一直都是单核在跑

**Comment by Steffy-zxf** [comment]
Runconfig接口参数use_data_parallel=True，在运行脚本之前，如果使用GPU训练，则设置CUDA_VISIBLE_DEVICES为多卡。

**Comment by baolicai** [comment]
> Runconfig接口参数use_data_parallel=True，在运行脚本之前，如果使用GPU训练，则设置CUDA_VISIBLE_DEVICES为多卡。

我使用的是CPU，将 Runconfig接口参数use_data_parallel=True ，cpu_num环境变量设置成2，运行的时候会报以下这个错：
PermissionDeniedError: Your machine has multiple cards, but the WITH_NCCL option is not turned on during compilation, and you cannot use multi-card training or prediction. Please recompile and turn on the WITH_NCCL option.
  [Hint: Expected places.size() == 1, but received places.size():2 != 1:1.] at (D:\1.7.2\paddle\paddle\fluid\framework\parallel_executor.cc:437)

**Comment by Steffy-zxf** [comment]
@baolicai 根据错误提示，运行环境中nccl没有配置正确，按照[paddle安装教程](https://www.paddlepaddle.org.cn/install/quick)检查环境是否能够正常使用paddle。
![image](https://user-images.githubusercontent.com/48793257/81465734-ac7fd180-91fe-11ea-97d5-f1e80d7f4010.png)

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
