### ISSUE TITLE
本地用windows训练好的模型放到Linux机器上，预测结果不一致

### ISSUE THREAD

**Issue by baolicai** [PaddlePaddle/PaddleFormers#578]
我在本地训练好的模型放到 Linux机器上，预测的结果和我在本地的不一样，一模一样的代码，感觉放到 Linux机器上预测的结果不管什么输入 就只有一种结果

**Comment by Steffy-zxf** [comment]
@baolicai 训练保存好的ckpt文件有完整的拷贝到另外一台机器上吗？ckpt的加载是否正确？

**Comment by baolicai** [comment]
> @baolicai 训练保存好的ckpt文件有完整的拷贝到另外一台机器上吗？ckpt的加载是否正确？

@Steffy-zxf 训练好的模型在指定的hub_ernie_text_cls目录下，生成了 best_model文件夹，step_1500文件夹，visualization文件夹 以及 ckpt.meta 文件，我在另一台机器只保存了best_model文件夹

**Comment by Steffy-zxf** [comment]
如果你想用best_model中的模型参数去预测，则另外一台机器上best_model的层级目录，应该和其在hub_ernie_text_cls层级保持一致。同时[task.predict接口](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/base_task.py#L983)参数load_best_model=True表示使用ckpt下的best_model预测，load_best_model=False则表示使用ckpt下保存的做后一个step模型参数预测。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
