### ISSUE TITLE
(D:\1.7.2\paddle\paddle\fluid\inference\api\analysis_predictor.cc:664)

### ISSUE THREAD

**Issue by zxzxde** [PaddlePaddle/PaddleFormers#579]
PaddlePaddle1.6.2
Windows10/MacOS/，
python3.7

使用pip安装好paddlehub后， 运行检测代码成功。但是运行人脸关键点识别的时候报如下错误，
我觉得不应该是用户名是中文的原因吧。
    self.cpu_predictor = create_paddle_predictor(cpu_config)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
Error: Cannot open file C:\Users\我的电脑\.paddlehub\modules\ultra_light_fast_generic_face_detector_1mb_320\ultra_light_fast_generic_face_detector_1mb_320/__model__ at (D:\1.7.2\paddle\paddle\fluid\inference\api\analysis_predictor.cc:664)

**Comment by Steffy-zxf** [comment]
@zxzxde 你好！建议安装PaddleHub module的路径不要带有中文名，可以通过修改HUB_HOME环境变量解决该问题，参考文档：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/cmdintro.md#paddlehub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7

**Comment by Tears1997** [comment]
@Steffy-zxf 你好，我遇到了相同问题，我已经在环境变量的用户变量设置了HUB_HOME变量，但之后然后安装模型的位置却依然是之前的位置，而不是HUB_HOME指定的位置

**Comment by Steffy-zxf** [comment]
@Tears1997 你好，是否有重启机器试试？使得设置的环境变量生效。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
