### ISSUE TITLE
Is there a pretrained lexical_analysis model?

### ISSUE THREAD

**Issue by FrontMage** [PaddlePaddle/PaddleFormers#58]
I ran 
` hub run lexical_analysis --input_text "在搜索引擎输入.尚赫”就可以发现多篇.尚赫涉嫌传销”.虚假宣传”.跨区经营”等各类媒体公开报道天津尚赫保健品有限公司违规经营的报道"`
and it says
```bash
Install Module lexical_analysis
Can't find module lexical_analysis
```

---

I understand that `lexical_analysis` is a model, not a module, is there a way to call a trained model?

**Comment by nepeplwu** [comment]
@FrontMage , thanks for your feedback, we have provided a lexical analysis module "lac"， you can use it like this 
`hub run lac --input_text "在搜索引擎输入.尚赫”就可以发现多篇.尚赫涉嫌传销”.虚假宣传”.跨区经营”等各类媒体公开报道天津尚赫保健品有限公司违规经营的报道"`

If you want to use the python interface, please refer to [demo](https://github.com/PaddlePaddle/PaddleHub/blob/release/v0.5.0/demo/lac/lac_demo.py)

**Comment by FrontMage** [comment]
@nepeplwu so the models are not callable through paddlehub?

**Comment by nepeplwu** [comment]
@FrontMage, yes, only module  can be run via paddlehub. For the difference between model and module, please have a look at [Doc](https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7#%E5%85%B3%E4%BA%8Emodel%E5%92%8Cmodule)

**Comment by FrontMage** [comment]
Thanks for the help, closing it.
