### ISSUE TITLE
预训练模型在自己数据上继续进行预训练任务

### ISSUE THREAD

**Issue by cbqin** [PaddlePaddle/PaddleFormers#583]
hi，paddlehub 支持预训练模型在自己数据上继续进行预训练任务么？是否有相关demo可参考？

**Comment by Steffy-zxf** [comment]
你好！PaddleHub目前不支持将预训练模型module继续预训练。

**Comment by cbqin** [comment]
好的，谢谢！

**Comment by ghost** [comment]
> 你好！PaddleHub目前不支持将预训练模型module继续预训练。

后续会支持吗？毕竟“预训练”太重要了

**Comment by Steffy-zxf** [comment]
@cbqin @illcat 你好！请问你们需要做什么样的预训练呢？是什么任务，什么背景呢？

**Comment by ghost** [comment]
> @cbqin @illcat 你好！请问你们需要做什么样的预训练呢？是什么任务，什么背景呢？

MLM & NSP

**Comment by Steffy-zxf** [comment]
> MLM & NSP

 这是BERT的预训练任务。为啥需要重新预训练bert呢？任务背景方便说说吗？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
