### ISSUE TITLE
我的训练集图片是灰色的，训练时如何设置通道

### ISSUE THREAD

**Issue by gekie** [PaddlePaddle/PaddleFormers#586]
input_shape = (1,100,100)
类似这种参数在hub里如何设置？

**Comment by Steffy-zxf** [comment]
你好！你的任务背景是什么，是想利用PaddleHub做图像分类迁移学习？还是使用PaddleHub提供的CV module直接预测呢？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
