### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/PaddleFormers#589]
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.6/demo/senta_module_sample

完整代码
module.py

processor.py

其中：processor.py
链接错误。

**Comment by Steffy-zxf** [comment]
@60999 感谢反馈！文档已修正，processor.py文件：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/demo/senta_module_sample/senta_test/processor.py
