### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/PaddleFormers#590]
https://github.com/PaddlePaddle/PaddleHub/blob/7224a9cefd6e7c25d98e18e4d77084191dcc8ae0/demo/README.md
"
检索式问答任务 
该样例展示了PaddleHub如何将ERNIE和BERT作为预训练模型在NLPCC-DBQA等数据集上完成检索式问答任务的FineTune和预测。
"
检索式问答任务  链接失效。其他链接 也有失效情况，显示404页面。

**Comment by Steffy-zxf** [comment]
你好！请查看release/v1.6分支中的文档 https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/demo/README.md

检索式问答demo：https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.6/demo/qa_classification
