### ISSUE TITLE
对paddlehub中strategy.py中的几个问题

### ISSUE THREAD

**Issue by mrhan36** [PaddlePaddle/PaddleFormers#591]
注：以下问题均为在paddlehub中实施迁移学习，进行图像分类时遇到的问题，主要是针对strategy.py的理解上的困惑，谢谢！

**#问题1：以下scheduler部分，代码的功能是设置对末3层（块）进行finetune，这样理解对吗？
#问题2：如果设置scheduler[gradual_unfreeze][blocks]=0，则不会实施多层finetune，discriminative也会无效，这样理解对吗？
#问题3：如果设置scheduler[gradual_unfreeze][blocks]=3,但scheduler[disciminative][blocks]=0，则会对末3层进行finetune，但discriminative无效（各层学习率相同），这样理解对吗？**
scheduler = {
  "discriminative": {
    "blocks": 3,
    "factor": 2.6
  },

 "gradual_unfreeze": {
                "blocks":3,
                "params_layer": None,
            } 
}

**#问题4：以下两行代码希望设置L2正则化，请问应该设置regularization[L2]=1e-3，还是应该设置regularization[weight_decay]=1e-3 ?**
regularization = {"L2": 1e-3}  
regularization = {"weight_decay": 1e-3}  

**#问题5：如果不设置clip参数，默认各层均不会有batchnorm，这样理解对吗？
#问题6：设置clip后，会对每层normalize还是只对unfreezing层进行normalize？
#问题7：是不是globalnorm更适合用于迁移学习，norm适合非迁移学习？**
clip = {"GlobalNorm": 1.0}
strategy = hub.CombinedStrategy(
    optimizer_name="adam", # "sgd","Adagrad","adamax","decayedadagrad","ftrl","larsmomentum","momentum","decayedadagrad","rmsprop"
    learning_rate=1e-4,
    scheduler = scheduler,
    regularization = regularization,
    clip = clip
)

config = hub.RunConfig(
    log_interval=10,
    use_cuda=True,
    num_epoch=30,
    checkpoint_dir=ckpt_dirckpt_dir,  
    batch_size=32,
    eval_interval=50,
    strategy=strategy 
    )

问题比较多，麻烦您了，谢谢！

参考资料：
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub-API:-Strategy
https://github.com/PaddlePaddle/PaddleHub/blob/a2cda1381ace47a8053280bc8f9dda043e25bd27/paddlehub/finetune/strategy.py

**Comment by kinghuin** [comment]
Hi @mrhan36  欢迎反馈问题
问题1：这里同时设置了discriminative和gradual_unfreeze blocks=3，参数被划分成3层，学习率逐层递减，一开始只有最顶层参与finetune，此后每个epoch解冻1层，epoch=3时全部参数都参与finetune。
问题2：不是，设置scheduler[gradual_unfreeze][blocks]=0只会关闭gradual_unfreeze，还要设置scheduler[discriminative][blocks]=0才会关闭discriminative
问题3：此时只有逐层解冻策略生效，每个epoch解冻1层
问题4：设置L2
问题5：clip是用于梯度裁剪，防止梯度爆炸的，和batchnorm不同
问题6：clip是梯度裁剪，只有unfreezing层会梯度更新
问题7：经验上我们没有这种结论，二者都是梯度裁剪，目前hub内置策略中使用的是globalnorm，可参考
 https://github.com/PaddlePaddle/PaddleHub/blob/develop/paddlehub/finetune/strategy.py#L584

**Comment by mrhan36** [comment]
谢谢您耐心解答！！

根据您的回复，再请教几个问题：
问题8：问题1的回复中，您提到“参数被划分成3层”，假定以VGG16迁移学习模型为例，请问是模型的所有层被划分为3层（块）？还是从迁移模型中取出最后3层进行finetune？
问题9：问题1的回复中，您提到“每个epoch解冻1层，epoch=3时全部参数都参与finetune“。请问您所知的“全部参数”指预训练模型中的所有层的全部参数吗？从epoch=4，epoch=5.....开始，.各个epoch优化的是哪几层参数，也是全部吗？
问题10：请问，以VGG16模型为例，gradual_unfreeze的blocks取值范围是多少？是0-16吗？

谢谢您！

**Comment by kinghuin** [comment]
客气啦

问题8： 是所有层被划分为3块
问题9：是的 “全部参数”指预训练模型中的所有层的全部参数。从epoch=4，epoch=5.....开始，.各个epoch优化的也是全部参数
问题10：gradual_unfreeze的blocks是按照底层算子的衔接顺序进行划分的，假设总op数是10，网络一共有2层，第1层有8个op，第2层只有2个op，如果设置blocks=5，那末，第一层会被划分为4block，第2层会被划分为1block。要想严格按照网络层进行划分，需要指定params_layer。目前只有nlp中的transformer系列模型（BERT、ERNIE等）可以已经内置了params_layer。您可以参考以下链接：
1. https://www.paddlepaddle.org.cn/hubdetail?name=ERNIE&en_category=SemanticModel 中的代码示例
2. https://github.com/PaddlePaddle/PaddleHub/blob/develop/paddlehub/module/nlp_module.py#L472 定义了get_params_layer接口
3. https://github.com/PaddlePaddle/PaddleHub/blob/develop/paddlehub/module/nlp_module.py#L392  您可以print(param.name)，观察param.name中是否包含layer信息，如果有的话可以通过正则表达式取出layer数，如果没有可能需要通过其它方式进行判断

如果您实现了VGG16的get_params_layer接口，欢迎向我们的module提PR：https://github.com/PaddlePaddle/PaddleHub/blob/develop/hub_module/modules/image/classification/vgg16_imagenet/module.py
module教程：https://github.com/PaddlePaddle/PaddleHub/tree/develop/hub_module/modules/demo

**Comment by mrhan36** [comment]
感谢回复！今天设置gradual_unfreeze时遇到一个调试错误，我对照strategy.py逐行检查，错误提示很明确，就是没搞清怎么改，请您指导一下。

源代码如下：
scheduler = {
  "gradual_unfreeze": {
    "blocks": 3
    }
}

strategy = hub.CombinedStrategy(
    optimizer_name="adam", 
    learning_rate=1e-4,    # 正交试验参数1
    scheduler = scheduler
)
config = hub.RunConfig(
    log_interval=10,
    use_cuda=True,
    num_epoch=30,
    checkpoint_dir=ckpt_dirckpt_dir,  
    batch_size=32,
    eval_interval=50,
    strategy=strategy
    )


错误提示如下：
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-63-a422b322feba> in <module>
     43     optimizer_name="adam",
     44     learning_rate=1e-4,    # 正交试验参数1
---> 45     scheduler = scheduler
     46 )
     47 config = hub.RunConfig(
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/strategy.py in __init__(self, optimizer_name, learning_rate, scheduler, regularization, clip)
    229         # check legality and assign
    230         for name in scheduler:
--> 231             self.check_assign(self.scheduler, name, scheduler[name])
    232         for name in regularization:
    233             self.check_assign(self.regularization, name, regularization[name])
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/strategy.py in check_assign(self, dictionary, key, value)
    256             else:
    257                 raise ValueError("The type of parameter %s should be %s" %
--> 258                                  (key, type(dictionary[key])))
    259 
    260     def add_scheduler(self, name="warmup", value=0, **values):
ValueError: The type of parameter gradual_unfreeze should be <class 'int'>


# 谢谢！

**Comment by kinghuin** [comment]
Hi，我已在https://github.com/PaddlePaddle/PaddleHub/issues/598 进行回复

**Comment by mrhan36** [comment]
> Hi，我已在#598 进行回复

好的，谢谢您！我下到本地stepin调试模式试一下啊，先自信解决，不行后再来打扰您。
