### ISSUE TITLE
paddlehub使用human_pose_estimation_resnet50_mpii模型，为什么最多只能检测出1个人体的骨骼点

### ISSUE THREAD

**Issue by ShanksYI** [PaddlePaddle/PaddleFormers#592]
- 版本、环境信息
1）PaddleHub1.6.2，paddlepaddle-gpu       1.7.2.post107
2）系统环境：Windows，python3.7
- 问题
paddlehub使用human_pose_estimation_resnet50_mpii模型，1张图片中最多只能检测出1套骨骼点，这是什么原因呢？

**Comment by Steffy-zxf** [comment]
你好！目前human_pose_estimation_resnet50_mpii只支持识别图中一个人的骨骼点。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
