### ISSUE TITLE
对于视频类自定义数据集的格式问题

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/PaddleFormers#593]
您好，我在看PADDLEHUB自定义数据的时候，发现教程里只写了图片类如何自定义数据，没写视频类数据如何自定义数据：

├─data: 数据目录
  ├─train_list.txt：训练集数据列表
  ├─test_list.txt：测试集数据列表
  ├─validate_list.txt：验证集数据列表
  ├─label_list.txt：标签列表
  └─……

训练/验证/测试集的数据列表文件的格式如下
图片1路径 图片1标签
图片2路径 图片2标签
...

请问我在做视频分类FINETUNE任务的时候，只需要将图片路径换成视频路径就可以了吗？
就是把”图片1路径 图片1标签 “换成 ”视频1路径 视频1标签“  就可以了吗？

另外，视频类的dataloader应该选什么呢？是选CVREADER吗？

**Comment by Steffy-zxf** [comment]
你好！目前PaddleHub还不支持视频类的迁移学习任务，所以没有相应的视频类自定义数据集格式说明。

**Comment by Derek-Kun** [comment]
感谢回答~ 我还有几个问题，希望大神能解答一下，感激不尽！

请问PADDLEHUB提供的几个视频分类的模型（TSN,TSM,VIDEOTAG_TSN_LSTM等）哪个更适合用来做“”短视频打标签分类任务"的迁移学习呢？

PaddlePaddlee初学者用对上述网络实现迁移学习代码难度大吗？

是否可以通过修改PaddleHub部分代码实现对上述视频分类的迁移学习？（例如：修改并建立一个专属于视频分类的data_reader，建立一个专属于视频分类的Dataset等。因为我发现hub.Module(name="tsn_kinetics400").context已经能够读取TSN网络的input_dict,output_dict和prgoram，所以在想是不是其他部分只要符合格式需求就能进行task.finetune_and_eval()的任务了~）

**Comment by Steffy-zxf** [comment]
PaddleHub提供的视频分类module有module 
 tsn_kinetics400/tsm_kinetics400/stnet_kinetics400/nonlocal_kinetics400

文档参考：https://www.paddlepaddle.org.cn/hublist?filter=en_category&value=ImageSegmentation

这些模型都可以用于视频分类任务。
如果想利用以上module配合PaddleHub 迁移学习Fine-tune API，需要定义相应的Dataset(读入数据集），Reader（读取数据，并返回给视频分类Task相应program需要feed的数据），Task（完成视频分类任务组网，训练评估测试等）。之前就可以task.finetune_and_eval()完成迁移学习。可以参考我们文本分类任务代码实现[TextClassifierTask](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/classifier_task.py#L158)

**Comment by Derek-Kun** [comment]
好的非常感谢~ 看来我还得去学习一下PaddlePaddle的基本命令了

**Comment by Steffy-zxf** [comment]
你好，此issue在近两月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
