### ISSUE TITLE
进入eval模式报错，train可以

### ISSUE THREAD

**Issue by zhengzihe** [PaddlePaddle/PaddleFormers#595]
https://aistudio.baidu.com/aistudio/projectdetail/305654?_=1589344524774&qq-pf-to=pcqq.temporaryc2c
项目地址
![image](https://user-images.githubusercontent.com/58216756/81883473-e61e5700-95c7-11ea-8096-cb484837f5dc.png)
![image](https://user-images.githubusercontent.com/58216756/81883535-09e19d00-95c8-11ea-8bc6-9e93e8d7babd.png)
![image](https://user-images.githubusercontent.com/58216756/81883561-1d8d0380-95c8-11ea-9c29-1f11fddb1de3.png)
事件抽取的paddlehub的baseline，项目不改可以跑，输出层做了一点改动，跑不了了
这个项目，把eval_step 弄小一点，一下就跑错了
![ET4$I2{CL1FXGR27J{0T%GX](https://user-images.githubusercontent.com/58216756/81883688-7197e800-95c8-11ea-8e53-42f17be988d4.png)

**Comment by Steffy-zxf** [comment]
你好！报错信息是什么？麻烦把报错信息贴全。

**Comment by zhengzihe** [comment]
![QQ图片20200514113550](https://user-images.githubusercontent.com/58216756/81890778-5e414880-95d9-11ea-80e8-fd59d8238ee0.jpg)

**Comment by Steffy-zxf** [comment]
你的paddle版本、paddlehub版本是多少呢？

**Comment by zhengzihe** [comment]
1.7 1.6

**Comment by Steffy-zxf** [comment]
试试将paddle换成1.6.2版本。

**Comment by zhengzihe** [comment]
![(G6F9JHLXV6@J8Q) 4~OXA0](https://user-images.githubusercontent.com/58216756/81918540-2a7e1700-9609-11ea-8cd4-ae38ec4d5ca4.JPG)

**Comment by zhengzihe** [comment]
![QQ图片20200514202634](https://user-images.githubusercontent.com/58216756/81935864-e0eef580-9623-11ea-881e-bce5a8538e41.png)

应该是rnn方法产生了_generated_var_0这种变量，得不到desc这个属性，不知道是什么原理，paddle的开源太假了，所有的底层函数都是一个字符串，下面就是c++了

**Comment by Steffy-zxf** [comment]
这个问题我们正在修复，试试用[dynamic_gru op](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/dynamic_gru_cn.html#dynamic-gru)。使用这个op，需要对输入去padding化。去padding化实现参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/sequence_task.py#L76

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
