### ISSUE TITLE
自定义Finetune模型完成训练后无法使用一键部署 

### ISSUE THREAD

**Issue by Suphx** [PaddlePaddle/PaddleFormers#599]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2

paddlepaddle == 1.7.2
paddlehub == 1.6.2

2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

Windows 10 专业版 版本号1909 操作系统版本18363.836
-复现信息
使用命令
hub install trash_module 安装自己训练的finetune模型
已显示Module trash_finetuned-1.0.0 already installed in C:\Users\TF\.paddlehub\modules\trash_finetuned

现在希望使用命令hub serving start -m trash_finetuned 启动预测服务
报错RuntimeError: Can't find module trash_finetuned, please check your spelling.

**Comment by Steffy-zxf** [comment]
你好！创建trash_finetuned module按照[教程](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/finetuned_model_to_module.md#%E6%B5%8B%E8%AF%95%E6%AD%A5%E9%AA%A4)本地预测接口调用是否成功呢？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
