### ISSUE TITLE
关于使用PaddlePaddle使用的咨询

### ISSUE THREAD

**Issue by ARDUJS** [PaddlePaddle/PaddleFormers#602]
### 问题1 预训练模型的使用
> https://www.paddlepaddle.org.cn/hubdetail?name=chinese-roberta-wwm-ext-large&en_category=SemanticModel

> 我现在有一个可以生成token_id, segment_id, mask_id, label的generator对象, 我该怎么样喂数据给下面这个预训练模型？
```
import paddlehub as hub

# Load $ hub install chinese-roberta-wwm-ext-large pretrained model
module = hub.Module(name="chinese-roberta-wwm-ext-large")
inputs, outputs, program = module.context(trainable=True, max_seq_len=128)
```
### 问题2 
```
    model_name = "chinese-roberta-wwm-ext-large"
    module = hub.Module(name=model_name)
    inputs, outputs, program = module.context(
        trainable=True, max_seq_len=args.max_seq_len)

    # 加载数据并通过SequenceLabelReader读取数据
    dataset = EEDataset(args.data_dir, schema_labels, model=args.do_model)
    reader = hub.reader.SequenceLabelReader(
        dataset=dataset,
        vocab_path=module.get_vocab_path(),
        max_seq_len=args.max_seq_len,
        sp_model_path=module.get_spm_path(),
        word_dict_path=module.get_word_dict_path())
```
> 如何重写hub.reader.SequenceLabelReader？代码中处理text为token_id, segment_id, mask_id的方式，不是我所希望的。

> 一直找不到相关api。

> 感谢大佬！

**Comment by Steffy-zxf** [comment]
你好！问题1和问题2 应该是类似的问题，如果你想喂数据给module chinese-roberta-wwm-ext-large，那么你需要写一个reader，这个reader会返回这个module需要feed 变量的数据，这个module必须feed以下4个变量，
```python
feed_list = [
        inputs["input_ids"].name, inputs["position_ids"].name,
        inputs["segment_ids"].name, inputs["input_mask"].name
    ]
```

hub.reader.SequenceLabelReader代码参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/reader/nlp_reader.py#L322

如果你想重写hub.reader.SequenceLabelReader中的token_id, segment_id, mask_id处理，可以其中[_convert_example_to_record方法](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/reader/nlp_reader.py#L445) 替换成你想要的方法。不过我们不建议这么做，因为这个模型预训练的时候是按照这套方法处理token_id, segment_id, mask_id，如果将其改变，可能会带来新的问题。

**Comment by ARDUJS** [comment]
> 你好！问题1和问题2 应该是类似的问题，如果你想喂数据给module chinese-roberta-wwm-ext-large，那么你需要写一个reader，这个reader会返回这个module需要feed 变量的数据，这个module必须feed以下4个变量，
> 
> ```python
> feed_list = [
>         inputs["input_ids"].name, inputs["position_ids"].name,
>         inputs["segment_ids"].name, inputs["input_mask"].name
>     ]
> ```
> 
> hub.reader.SequenceLabelReader代码参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/reader/nlp_reader.py#L322
> 
> 如果你想重写hub.reader.SequenceLabelReader中的token_id, segment_id, mask_id处理，可以其中[_convert_example_to_record方法](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/reader/nlp_reader.py#L445) 替换成你想要的方法。不过我们不建议这么做，因为这个模型预训练的时候是按照这套方法处理token_id, segment_id, mask_id，如果将其改变，可能会带来新的问题。

- 大佬！我还是不清楚该怎么喂数据给模型。

```
    pyreader = fluid.layers.py_reader(capacity=50,
                                      shapes=[[-1, args.max_seq_len, 1],
                                              [-1, args.max_seq_len, 1],
                                              [-1, args.max_seq_len, 1],
                                              [-1, args.max_seq_len, 1],
                                              [-1, args.max_seq_len, 1],
                                              [-1, args.max_seq_len, 1], [-1]],
                                      dtypes=[
                                          'int64', 'int64', 'int64', 'int64',
                                          'float32', 'int64', 'int64'
                                      ],
                                      lod_levels=[0, 0, 0, 0, 0, 0, 0],
                                      name=pyreader_name,
                                      use_double_buffer=True)

    (src_ids, sent_ids, pos_ids, task_ids, input_mask, labels,
     seq_lens) = fluid.layers.read_file(pyreader)

    ernie = ErnieModel(src_ids=src_ids,
                       position_ids=pos_ids,
                       sentence_ids=sent_ids,
                       task_ids=task_ids,
                       input_mask=input_mask,
                       config=ernie_config,
                       use_fp16=args.use_fp16)

    enc_out = ernie.get_sequence_output()
```
> 可以怎么封装下 类似这样喂数据吗？

> 感谢大佬！

**Comment by ARDUJS** [comment]
Help!

**Comment by Steffy-zxf** [comment]
关于如何feed 数据给program，可以参考PaddleHub DataLoader的实现：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/paddlehub/finetune/task/base_task.py#L1055

DataLoader API介绍：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
