### ISSUE TITLE
tokenize[SEP] 有问题

### ISSUE THREAD

**Issue by ARDUJS** [PaddlePaddle/PaddleFormers#604]
- 输入
`print(reader.tokenizer.tokenize("[SEP]"))`
- 输出
`[u'\u2581[', u'\u2581sep', u'\u2581]']`
这个是有问题把！！

**Comment by Steffy-zxf** [comment]
你好！`tokenizer.tokenize`是将输入的文本text进去切分，如果text是中文则切字，如果text是英文则token化。`tokenizer.tokenize("[SEP]")`这里待切分的是[SEP]，自然会把"["（u'\u2581['），“]”（u'\u2581]'）切分出来。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
