### ISSUE TITLE
请问如何将ernie保存成到inference_model并在AIstudio部署

### ISSUE THREAD

**Issue by ChaunceyBai98** [PaddlePaddle/PaddleFormers#608]
finetune是按照github上教程走的，只是修改了自己的数据集，没有改网络结构啥的。save_inference_model的文档我也看了，主要是不知道feeded_var_names, target_vars这两个参数ernie下应该写啥。PS：做的文本分类

**Comment by Steffy-zxf** [comment]
你好！feeded_var_names 是指program里面需要feed数据的变量名称，target_vars是想从program中fetch得到的变量。

使用PaddleHub Finetune-API，训练结束之后会生成ckpt文件，这个文件夹下有一个best_model文件夹。这个best_model里面的模型和参数就可以用于预测部署。

**Comment by ChaunceyBai98** [comment]
请问有用best_model部署的教程/文档么？

**Comment by Steffy-zxf** [comment]
可以使用PaddleHub Serving部署预测。第一步：把finetune得到的模型参数转化为module。 第二步：用PaddleHub Serving部署预测。

参考文档：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/docs/tutorial/finetuned_model_to_module.md#paddlehub-serving%E8%B0%83%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by ChaunceyBai98** [comment]
哦哦，这个我已经弄明白了，我现在是想用AIstudio的部署功能，那个必须要用inference_model才行

**Comment by Steffy-zxf** [comment]
best_model就是使用save_ inference_model接口保存的。用best_model就可以部署。

**Comment by ChaunceyBai98** [comment]
好的，我再研究研究，十分感谢！

**Comment by wuzixin** [comment]
> 好的，我再研究研究，十分感谢！

在沙盒部署，自定义参数转换这一块你是如何编写的呢，有没有例子看一下，呵呵

**Comment by ChaunceyBai98** [comment]
我放弃了，自己租了服务器部署的。

**Comment by Steffy-zxf** [comment]
@wuzixin 该问题参考issue 回复https://github.com/PaddlePaddle/PaddleHub/issues/651#issuecomment-636265350 

@ChaunceyBai98 @wuzixin 同时想了解下，你们说的沙盒环境是什么样的环境？是指在AIStudio上部署预测服务吗？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
