### ISSUE TITLE
batchsize 必须设置成卡数倍数

### ISSUE THREAD

**Issue by Austendeng** [PaddlePaddle/PaddleFormers#61]
![image](https://user-images.githubusercontent.com/16330293/59987225-84ca5e00-966c-11e9-81a5-ec4a800f45be.png)
如图，当ba't'cbatchsize不是卡数倍数时会报错，是否考虑修改代码求余或者添加设置说明？

**Comment by Austendeng** [comment]
上述例子中卡数是8，batchsize是20

**Comment by Steffy-zxf** [comment]
感谢反馈，这个问题我们正在查找原因并修复。
