### ISSUE TITLE
hub serving start pyramidbox_lite_server_mask

### ISSUE THREAD

**Issue by linux-devil** [PaddlePaddle/PaddleFormers#610]
hub version 1.6.2
Ubuntu

Followed steps in serving section of : https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_server_mask&en_category=ObjectDetection

```
    data = {'images':[cv2_to_base64(cv2.imread(file_name))]}
    headers = {"Content-type": "application/json"}
    url = "http://127.0.0.1:8866/predict/pyramidbox_lite_server_mask"
    r = requests.post(url=url, headers=headers, data=json.dumps(data))
    print(r.json())
```
gives output : 
```
{'msg': 'Please check data format!', 'results': '', 'status': '-1'}
```

**Comment by linux-devil** [comment]
```
2020-05-18 10:40:40  -  __call__() missing 1 required positional argument: 'data'
2020-05-18 10:40:40,794-INFO: 127.0.0.1 - - [18/May/2020 10:40:40] "POST /predict/pyramidbox_lite_server_mask HTTP/1.1" 200 -

```

**Comment by ShenYuhan** [comment]
Hi， maybe you can check this issue， the problem is same as yours.

https://github.com/PaddlePaddle/PaddleHub/issues/609

Upgrade your module and try again.

**Comment by linux-devil** [comment]
I am already using latest version of pyramidbox_lite_server_mask 1.3.0

**Comment by ShenYuhan** [comment]
Module "pyramidbox_lite_server_mask" depends on module "pyramidbox_lite_server"
Make sure the module "pyramidbox_lite_server" has latest version "1.2.0".
Execute:
```shell
hub install pyramidbox_lite_server ==1.2.0
```
