### ISSUE TITLE
请问那个模型可以解决序列预测的问题

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleFormers#615]
遇到的需求是这样的  
需要根据设备前面7天的报警信息去预测后面一天的报警情况？
有没有相关案例推荐？

**Comment by Steffy-zxf** [comment]
你好！PaddleHub目前不支持这类任务，可以移步 https://github.com/PaddlePaddle/models 提问。

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
