### ISSUE TITLE
Can't find module ernie

### ISSUE THREAD

**Issue by githubsora** [PaddlePaddle/PaddleFormers#616]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub 1.1.1和PaddlePaddle 1.3.1
2）系统环境：请您描述系统类型，例如Linux，python版本2.7.14
Can't find module ernie with version 1.2.0
无法正常安装

**Comment by Steffy-zxf** [comment]
你好！根据上述你提供的环境信息：
> PaddleHub 1.1.1和PaddlePaddle 1.3.1 
> python版本2.7.14

paddlehub 和 paddlepaddle版本太旧了。目前paddlehub最新版本1.7.0，paddle最新版本1.8.0，请升级至最新版本

```
pip install --upgrade paddlehub
```
同时 paddlehub 1.7.0版本之后不再支持python2.7，请切换至python3.6以上环境使用paddlehub。详情参考[安装文档](https://github.com/PaddlePaddle/PaddleHub#%E5%AE%89%E8%A3%85)

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
