### ISSUE TITLE
AssertionError: Not compiled with CUDA

### ISSUE THREAD

**Issue by yuzehui1996** [PaddlePaddle/PaddleFormers#617]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：
PaddleHub1.5.4，PaddlePaddle1.7.1
2）系统环境：
Linux(centos-7)，python-3.7

报错信息如下：
▽
  1 [2020-05-21 20:35:47,983] [    INFO] - Installing resnext50_32x4d_imagenet module
  2 [2020-05-21 20:35:48,001] [    INFO] - Module resnext50_32x4d_imagenet already installed in /home/luban/.paddlehub/modules/resnext50_32x4d_imagenet
  3 [2020-05-21 20:35:48,332] [    INFO] - 267 pretrained paramaters loaded by PaddleHub
  4 [2020-05-21 20:35:48,518] [    INFO] - Dataset label map = {'1': 0, '2': 1, '3': 2, '4': 3, '5': 4, '6': 5, '7': 6, '8': 7, '9': 8}
  5 [2020-05-21 20:35:48,519] [    INFO] - Checkpoint dir: ckpt_20200521203548
  6 Traceback (most recent call last):
  7   File "img_cls.py", line 147, in <module>
  8     finetune(args)
  9   File "img_cls.py", line 113, in finetune
 10     config=config)
 11   File "/home/luban/anaconda3/lib/python3.7/site-packages/paddlehub/finetune/task/classifier_task.py", line 49, in __init__
 12     metrics_choices=metrics_choices)
 13   File "/home/luban/anaconda3/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 242, in __init__
 14     self.place = self.places[0]
 15   File "/home/luban/anaconda3/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 416, in places
 16     _places = fluid.framework.cuda_places()
 17   File "/home/luban/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 314, in cuda_places
 18     "Not compiled with CUDA"
 19 AssertionError: Not compiled with CUDA

**Comment by Steffy-zxf** [comment]
你好！报错信息显示你的运行环境上没有相应GPU运行的环境条件。请根据[paddle安装指南](https://www.paddlepaddle.org.cn/install/quick)检查paddle是否正确安装。另外，如果你的运行环境没有GPU显卡，可以选择cpu运行，只需安装cpu版本的paddle，之后在[RunConfig](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/docs/reference/config.md#class-hubfinetuneconfigrunconfig)中设置use_cuda=False即可。

**Comment by yuzehui1996** [comment]
机器上有GPU，也是按照安装指南一步一步做的，检查后结果如下：
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Paddle Program ...
Your Paddle works well on SINGLE GPU or CPU.
I0521 21:10:39.315587 30098 parallel_executor.cc:440] The Program will be executed on CPU using ParallelExecutor, 2 cards are used, so 2 programs are executed in parallel.
W0521 21:10:39.316433 30098 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
I0521 21:10:39.316529 30098 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0521 21:10:39.317095 30098 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0521 21:10:39.317523 30098 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
Your Paddle works well on MUTIPLE GPU or CPU.
Your Paddle is installed successfully! Let's start deep Learning with Paddle now

**Comment by Steffy-zxf** [comment]
另外看你的paddlehub版本是1.5.4，paddle为1.7.1，paddlehub版本比较旧，请升级paddlehub至最新版本1.7.0，paddle最新版本1.8.0

**Comment by Steffy-zxf** [comment]
您好，此issue在近两周内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
