### ISSUE TITLE
pyramidbox_lite_server、pyramidbox_face_detect，两个modules的服务预测时间为什么相差这么大

### ISSUE THREAD

**Issue by YasinZhao** [PaddlePaddle/PaddleFormers#618]
老师你好，我在研究贵司提供的人脸检测模型服务时，对比了下pyramidbox_lite_server、pyramidbox_face_detect，两个modules的服务预测时间：
pyramidbox_lite_server：CPU预测，时间10ms左右
pyramidbox_face_detect：P100 GPU预测，时间8s左右
请问，为什么预测时间相差这么多，有什么可优化的措施建议吗，谢谢~

**Comment by Steffy-zxf** [comment]
你好！pyramidbox_lite_server是一个轻量级的人脸检测模型，所以它相对于pyramidbox_face_detect预测速度更快。如果想要更快的处理速度，更推荐使用pyramidbox_lite_server。

**Comment by YasinZhao** [comment]
> 你好！pyramidbox_lite_server是一个轻量级的人脸检测模型，所以它相对于pyramidbox_face_detect预测速度更快。如果想要更快的处理速度，更推荐使用pyramidbox_lite_server。

好的，谢谢~
