### ISSUE TITLE
模型基准测试结果

### ISSUE THREAD

**Issue by jacobssy** [PaddlePaddle/PaddleFormers#62]
您好，请问哪里可以看到模型基准测试结果呢？比如图像分类任务，我想知道通过paddle官方训练的某个模型的基准测试结果。在哪里可以看呢？

**Comment by nepeplwu** [comment]
@jacobssy ，可以查看Paddle的[模型库](https://github.com/PaddlePaddle/models)了解模型的代码和细节， 其中图像分类的基准测试结果见：
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification#supported-models-and-performances

**Comment by jacobssy** [comment]
@nepeplwu 谢谢，这个hub可以多卡数据并行跑吗？不好意思，我没在config里面找到这个

**Comment by nepeplwu** [comment]
@jacobssy ，多卡并行的功能旧版本并不支持，新版本中已经开发完成，正在测试中，预计近期会发布，可以通过Watch来关注我们的发布

**Comment by jacobssy** [comment]
@nepeplwu 好的 谢谢 支持一波 感觉paddle对用户很友好
