### ISSUE TITLE
strategy应用momentum优化时报错

### ISSUE THREAD

**Issue by mrhan36** [PaddlePaddle/PaddleFormers#620]
## 环境设置
环境：aistudio
python版本：3.7
paddlehub版本：1.7.0

## 项目位置：
https://aistudio.baidu.com/aistudio/projectdetail/492913

## 问题：运行到以下代码处报错：
strategy = hub.CombinedStrategy(
    optimizer_name="momentum", 
    learning_rate=0.0001
)
config = hub.RunConfig(
    log_interval=10,
    use_cuda=True,
    num_epoch=5,
    checkpoint_dir=ckpt_dirckpt_dir,  
    batch_size=32,
    eval_interval=50,
    strategy=strategy,
    )

报错内容如下：
---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<ipython-input-7-222108b5f3b3> in <module>
      7 strategy = hub.CombinedStrategy(
      8     optimizer_name="momentum",
----> 9     learning_rate=0.0001
     10 )
     11 config = hub.RunConfig(
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/strategy.py in __init__(self, optimizer_name, learning_rate, scheduler, regularization, clip)
    189                  clip=None):
    190         super(CombinedStrategy, self).__init__(
--> 191             optimizer_name=optimizer_name, learning_rate=learning_rate)
    192 
    193         # init set
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/strategy.py in __init__(self, learning_rate, optimizer_name)
    157         elif self._optimizer_name.lower() == "momentum":
    158             self.optimizer = fluid.optimizer.Momentum(
--> 159                 learning_rate=self.learning_rate)
    160         elif self._optimizer_name.lower() == "decayedadagrad":
    161             self.optimizer = fluid.optimizer.DecayedAdagrad(
TypeError: __init__() missing 1 required positional argument: 'momentum'

## 谢谢！

**Comment by Steffy-zxf** [comment]
感谢反馈！该问题是由于调用Momentum优化器api时，缺少了momentum参数值导致报错。请先用使用Adam优化器，如下：
```python
strategy = hub.CombinedStrategy(optimizer_name="adam", learning_rate=0.0001)
```

该问题将在paddlehub 1.7.1版本修复。

**Comment by mrhan36** [comment]
收到，感谢回复！

**Comment by mrhan36** [comment]
补充：
在调用“larsmomentum”优化时，遇到同样的问题。

**Comment by Steffy-zxf** [comment]
感谢反馈！
> 在调用“larsmomentum”优化时，遇到同样的问题。

这个问题同样会在1.7.1版本修复。

**Comment by mrhan36** [comment]
收到，感谢回复！
