### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/home/xxx/.paddlehub/modules/pyramidbox_lite_mobile_mask'

### ISSUE THREAD

**Issue by wgwang314** [PaddlePaddle/PaddleFormers#623]
1）PaddleHub1.5.0，PaddlePaddle1.8
2）Ubuntu16.04，Python2.7

问题：学习PaddleHub口罩检测项目过程中，pyramidbox mask模型安装出错，其它如lac，YOLOv3可以正常安装
tar@NUC7i3BNK:~$hub run pyramidbox_lite_mobile_mask --input_path test_mask_detection.jpg
Install Module pyramidbox_lite_mobile_mask
Downloading pyramidbox_lite_mobile_mask
[==================================================] 100.00%
Uncompress /home/xxx/.paddlehub/tmp/tmpqGvucz/pyramidbox_lite_mobile_mask
[==================================================] 100.00%
Traceback (most recent call last):
  File "/home/mustar/.local/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/home/mustar/.local/lib/python2.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/home/xxx/.local/lib/python2.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/home/xxx/.local/lib/python2.7/site-packages/paddlehub/commands/run.py", line 232, in execute
    self.module = self.find_module(module_name)
  File "/home/xxx/.local/lib/python2.7/site-packages/paddlehub/commands/run.py", line 66, in find_module
    module_name, extra=extra)
  File "/home/xxx/.local/lib/python2.7/site-packages/paddlehub/module/manager.py", line 201, in install_module
    shutil.move(module_dir, save_path)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/xxx/.paddlehub/modules/pyramidbox_lite_mobile_mask'

**Comment by Steffy-zxf** [comment]
你好！根据上述环境信息，paddlehub为1.5.0版本，版本较为老旧，请更新至paddlehub最新版本1.7.0。另外paddlehub 1.7.0版本之后不在支持python2.7，请切换至python3.6以上版本使用。

**Comment by wgwang314** [comment]
谢谢！解决了，是版本问题。没办法，必须用python2.7。pyramidbox_lite_server_mask v1.1.0可以安装上。
The version of PaddlePaddle or PaddleHub can not match module, please upgrade your PaddlePaddle or PaddleHub according to the form below.
+--------------------------------+----------+------------------+------------------+
|          ResourceName          | Version  |   PaddlePaddle   |    PaddleHub     |
+--------------------------------+----------+------------------+------------------+
|  pyramidbox_lite_server_mask   |  1.3.0   |      >1.6.2      |      >1.6.0      |
+--------------------------------+----------+------------------+------------------+
|  pyramidbox_lite_server_mask   |  1.2.0   |      >1.6.1      |      >1.5.0      |
+--------------------------------+----------+------------------+------------------+
|  pyramidbox_lite_server_mask   |  1.2.0   |      >1.6.1      |  >1.0.0, <1.4.9  |
+--------------------------------+----------+------------------+------------------+
|  pyramidbox_lite_server_mask   |  1.1.0   |      >1.6.1      |      >1.0.0      |
+--------------------------------+----------+------------------+------------------+
|  pyramidbox_lite_server_mask   |  1.0.1   |      >1.6.1      |      >1.0.0      |
+--------------------------------+----------+------------------+------------------+
|  pyramidbox_lite_server_mask   |  1.0.0   |      >1.6.1      |      >1.0.0      |
+--------------------------------+----------+------------------+------------------+
