### ISSUE TITLE
ernie 命名实体如何保存模型，如何部署

### ISSUE THREAD

**Issue by wuzixin** [PaddlePaddle/PaddleFormers#624]
![image](https://user-images.githubusercontent.com/22019016/82797224-5fac2400-9ea9-11ea-9317-83806ed6d59d.png)

**Comment by Steffy-zxf** [comment]
你好！`seq_lable_task.finetune_and_eval()`会自动在指定的ckpt文件夹下保存微调之后的模型，其中ckpt文件夹下best_model就可以用于部署预测。关于部署预测参考回复 https://github.com/PaddlePaddle/PaddleHub/issues/608#issuecomment-630021347

**Comment by wuzixin** [comment]
命名实体沙盒部署的时候，数据转换的逻辑

> 你好！`seq_lable_task.finetune_and_eval()`会自动在指定的ckpt文件夹下保存微调之后的模型，其中ckpt文件夹下best_model就可以用于部署预测。关于部署预测参考回复 [#608 (comment)](https://github.com/PaddlePaddle/PaddleHub/issues/608#issuecomment-630021347)

命名实体沙盒部署的数据转换代码这一块是如何写的呢，您这个有写过么，我写的一直都有问题，能否给一个参考一下：
![image](https://user-images.githubusercontent.com/22019016/82983867-87bf9280-a023-11ea-80c5-27c310859875.png)

**Comment by wuzixin** [comment]
> 命名实体沙盒部署的时候，数据转换的逻辑
> 
> > 你好！`seq_lable_task.finetune_and_eval()`会自动在指定的ckpt文件夹下保存微调之后的模型，其中ckpt文件夹下best_model就可以用于部署预测。关于部署预测参考回复 [#608 (comment)](https://github.com/PaddlePaddle/PaddleHub/issues/608#issuecomment-630021347)
> 
> 命名实体沙盒部署的数据转换代码这一块是如何写的呢，您这个有写过么，我写的一直都有问题，能否给一个参考一下：
> ![image](https://user-images.githubusercontent.com/22019016/82983867-87bf9280-a023-11ea-80c5-27c310859875.png)

![1590559792(1)](https://user-images.githubusercontent.com/22019016/82984011-d2d9a580-a023-11ea-9a95-e2c6d3402e95.jpg)

**Comment by Steffy-zxf** [comment]
你好！该问题参考回复：https://github.com/PaddlePaddle/PaddleHub/issues/651#issuecomment-636265350

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
