### ISSUE TITLE
关于组合优化策略的一个问题

### ISSUE THREAD

**Issue by mrhan36** [PaddlePaddle/PaddleFormers#631]
## 【训练环境】
环境：aistudio
python版本：3.7
paddlehub版本：1.7.0
模型：se_resnext101_32x4d_imagenet
任务：通过迁移学习，训练最佳预测模型

## 【我的问题】
问题1：
为进行模型调优，得到最优预测模型，计划对以下8个参数在不同取值组合下做正交实验，观察各组合准确率。**我的困惑是，以下各优化器（SGD,ADAM等）和其他7个参数之间，以及1-7各参数之间是否可以任意组合，是否存在在理论上不适合组合的地方。**

问题2：
以下各参数取值是在小样本数据上实施单因素预实验（将其他参数设置为None或paddlehub默认值）后筛选确定的acc较高的代表性的参数值。**请问依您的经验，以下参数取值是否有明显不合理的地方**。该实验数据要写在英文论文中，是核心实验部分，文中会提到paddlepaddle和Aistudio平台，所以希望能严谨呈现，为避免犯低级错误，所以来此处寻求帮助，谢谢！

由于数据量较大，各组合确定后，下一步实验会耗费大量计算资源和时间（单卡训练需要20天完成实验），所以请专家给把把关，谢谢！

1. 【Batch_size】：16，32，64
2. 【学习率（learning_rate）】：0.001，0.0001，0.00005
3. 【权重衰减（weight_decay）】：0.0001，0.0005，0.001
4. 【gradual_unfreeze】：3，5，7
5. 【slanted_triangle-cut_fraction】：0.05，0.1，0.2
6. 【Discrimitive-blocks】：2，3，5
7. 【Clip】：1，2，3
8. 【优化器（optimizer）】：sgd，adam，adagrad，adamax，decayedadagrad，rmsprop

**Comment by kinghuin** [comment]
Hi @mrhan36 欢迎提问
1. 可以任意组合的
2. 未见明显不合理的地方

另外，
1. 请问您的实验目的是什么呢
2. 组合策略的超参搜索还可以尝试paddlehub 自动超参搜索：https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.7/demo/autofinetune_text_classification
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.7/demo/autofinetune_image_classification

**Comment by mrhan36** [comment]
> Hi @mrhan36 欢迎提问
> 
> 1. 可以任意组合的
> 2. 未见明显不合理的地方
> 
> 另外，
> 
> 1. 请问您的实验目的是什么呢
> 2. 组合策略的超参搜索还可以尝试paddlehub 自动超参搜索：

感谢您回复！
1. 实验的目的基于160类中药材数据训练中药材识别模型，以测试集准确率做评价指标。从深度学习在行业中应用的角度撰写论文。
2. 谢谢建议，我尽快研究下自动超参搜索。因为写论文，需要体现出一些设计的思路在里边，所以之前没有用自动化程度很高的方法。

从写论文角度，您是否可以再提供一些宝贵建议？谢谢！

**Comment by kinghuin** [comment]
是企业需求呢还是毕设或者学术论文呢？

模型方面可以尝试一下我们新出的模型 resnet50_vd_imagenet_ssld和resnet50_vd_10w
https://www.paddlepaddle.org.cn/hubdetail?name=resnet50_vd_imagenet_ssld&en_category=ImageClassification
https://www.paddlepaddle.org.cn/hubdetail?name=resnet50_vd_10w&en_category=ImageClassification

**Comment by mrhan36** [comment]
> 学术论文

太好了，谢谢！
是普通的学术论文，计划投稿到SCI期刊。

您的意思是基于以上模型，实施现在的多参数组合训练计划是吧？

**Comment by kinghuin** [comment]
是的 这些新模型对提升成绩会有帮助 建议基于以上模型实施多参数组合训练计划

**Comment by mrhan36** [comment]
好的，非常感谢！
