### ISSUE TITLE
 Module face_landmark_localization，实现川剧变脸时换成别的图片识别不出来

### ISSUE THREAD

**Issue by lzb-James** [PaddlePaddle/PaddleFormers#632]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by lzb-James** [comment]
是cv读文件的格式不对吗？

**Comment by Steffy-zxf** [comment]
你好！是什么样的图片？你是怎么读取图片的？方便把样例图片和代码贴上吗？另外你的环境信息（paddlehub版本 paddle版本 python版本）是什么样的？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
