### ISSUE TITLE
如何导出及导入模型？

### ISSUE THREAD

**Issue by T-baby** [PaddlePaddle/PaddleFormers#635]
没有看到如何将训练好的模型导出的办法，也没看到该如何直接导入自己训练好的模型。

**Comment by Steffy-zxf** [comment]
你好！

1. 你是指什么模型要导出？是使用PaddleHub迁移学习Fine-tune API训练得到的模型，还是指PaddleHub提供的可直接预测module呢？

2. > 也没看到该如何直接导入自己训练好的模型。

这个模型是 从哪里来的？

**Comment by T-baby** [comment]
使用PaddleHub迁移学习Fine-tune API训练得到的模型

**Comment by Steffy-zxf** [comment]
使用PaddleHub Fine-tune API，在迁移学习训练过程中会自动导出最佳模型，导出路径为在训练时`RunConfig`中指定的ckpt文件夹下的best_model文件夹中。

如果想要加载best_model文件夹下的模型，可以直接使用[load_inference_model API](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/load_inference_model_cn.html#load-inference-model)

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Comment by JzHuangJian** [comment]
PaddleHub提供的可直接预测module怎么使用model.load，加载

**Comment by rainyfly** [comment]
如果你是想替换模型的参数文件的话，你可以看一下module的代码，里面直接替换成你自己的模型参数的路径。module的代码路径在~/.paddlehub/modules/模型名称， 然后一般module.py文件里载入的参数，因为module提供的是一键预测的功能，所以paddlehub发布的module用到的模型参数是提前准备好给用户使用的，你需要替换的话按上述方法替换一下路径试试
