### ISSUE TITLE
paddlehub目标检测迁移学习有相关的教程和demo吗？

### ISSUE THREAD

**Issue by whjdark** [PaddlePaddle/PaddleFormers#638]
我翻了很久都没找到hub上目标检测进行迁移学习的，请问一下是否有相关的教程和样例。

**Comment by Steffy-zxf** [comment]
你好！目前PaddleHub还未支持目标检测迁移学习功能，在未来PaddleHub会增加目标检测和图像分割等任务迁移学习，敬请期待。目标检测任务迁移学习可以暂时先参考PaddleX完成目标检测任务demo：https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/train
