### ISSUE TITLE
利用videotag_tsn_lstm模型进行train的几点疑惑

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/PaddleFormers#640]
你好，我注意到视频分类videotag_tsn_lstm模型里有train_utils.py文件，里面有一个方法叫：
def  train_with_dataloader(exe, train_prog, compiled_train_prog, train_dataloader, \
                        train_fetch_list, train_metrics, epochs = 10, \
                        log_interval = 0, valid_interval = 0, save_dir = './', \
                        save_model_name = 'model', fix_random_seed = False, \
                        compiled_test_prog = None, test_dataloader = None, \
                        test_fetch_list = None, test_metrics = None, \
                        is_profiler = None, profiler_path = None):
这是否意味着该模型可以像paddlepaddle提供的其他视频分类模型那样在自建数据集上进行训练？如果可以的话，应该怎样自建数据集？ train_with_dataloader里的各个参数分别代表什么意思，我是否可以直接用准备好格式的数据集和train_with_dataloader方法，然后再修改一下分类的配置文件，直接开始训练？

**Comment by huangjun12** [comment]
PaddlePaddle models/PaddleCV/video下也release了代码，可以基于release的预训练权重fine-tune，具体请参考：
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/video/application/video_tag

**Comment by Derek-Kun** [comment]
好的谢谢！！
