### ISSUE TITLE
chinese_ocr_db_crnn 模型 shapely 加载报错

### ISSUE THREAD

**Issue by D-DanielYang** [PaddlePaddle/PaddleFormers#642]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
PaddleHub1.7.0，PaddlePaddle1.8.1
2）系统环境：windows
- 复现信息：如为报错，请给出复现环境、复现步骤
import paddlehub as hub
ocr = hub.Module(name="chinese_ocr_db_crnn") #加载预训练模型

results = ocr.recognize_text(paths=[r'D:\myfile\PythonTest\OCR_test.jpg'], visualization=True)
print(result)

里面会用到依赖shapely
通过pip install shapely 之后，安装shapely 1.7成功

但是调试报错
![log](https://user-images.githubusercontent.com/23690325/83118045-6c768500-a100-11ea-912c-62b293d67cba.JPG)

**Comment by D-DanielYang** [comment]
网上找到答案了，应该是windows环境下的，pip install shapely的一个bug

解决方案如下：

先将位于Anaconda3\Lib\site-packages的shapely文件删除
然后去https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely
下载自己系统对应的.whl
如我的python是3.7，64位，则下载
Shapely‑1.7.0‑cp37‑cp37m‑win_amd64.whl
一定要下载对，不然会出现... is not a supported wheel on this platform的错误提示。

用如下命令安装即可

pip install Shapely‑1.7.0‑cp37‑cp37m‑win_amd64.whl

原文链接：https://blog.csdn.net/qq_43630348/java/article/details/105864047

**Comment by YuNaruto** [comment]
使用 conda install 可以直接安装这两个库，没有报错
