### ISSUE TITLE
文字识别【chinese_ocr_db_crnn】报错：'str' object has no attribute 'shape'

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleFormers#644]
_报错内容：_【**'str' object has no attribute 'shape'**】

_版本、环境信息：_
chinese_ocr_db_crnn-1.0.0
paddlehub-1.7.1
paddlepaddle-1.8.1
MacOS-10.14.6
python-3.7.4

_官方代码：_
【1】启动PaddleHub Serving：
`hub serving start -m chinese_ocr_db_crnn`

【2】发送预测请求：
```
import requests
import json
import cv2
import base64

def cv2_to_base64(image):
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')

# 发送HTTP请求
data = {'images':[cv2_to_base64(cv2.imread("/PATH/TO/IMAGE"))]}
headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:8866/predict/chinese_ocr_db_crnn"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(r.json()["results"])
```

**Comment by Steffy-zxf** [comment]
你好！

```python
# 发送HTTP请求
data = {'images':[cv2_to_base64(cv2.imread("/PATH/TO/IMAGE"))]}
```
 这里 "/PATH/TO/IMAGE" 表示 待预测图片所在路径。确定把待预测的图片路径输入对了吗？

**Comment by 670133189** [comment]
> 你好！
> 
> ```python
> ＃发送HTTP请求
> 数据 = { '图像'：[ cv2_to_base64（CV2。imread（“/ PATH / TO / IMAGE” ））]}
> ```
> 
> 这里“ / PATH / TO / IMAGE”表示待预测图片所在路径。确定把待预测的图片路径输入对了吗？

是的，路径没错。
通过以下方式调用则成功，反之通过http会失败：
```
import paddlehub as hub
import cv2

ocr = hub.Module(name="chinese_ocr_db_crnn")
result = ocr.recognize_text(images=[cv2.imread('/PATH/TO/IMAGE')])
```

**Comment by Steffy-zxf** [comment]
你好！目前文字识别模型已经升级新版本，详细信息参考PaddleHub官网文档：https://www.paddlepaddle.org.cn/hublist?filter=en_category&value=TextRecognition

chinese_text_detection_db已经更改名字为 chinese_text_detection_db_mobile
chinese_ocr_db_crnn已经更改名字为chinese_ocr_db_crnn_mobile

试试将文字识别模型升级到最新版本1.0.1
```shell
$ hub install chinese_text_detection_db_mobile==1.0.1
$ hub install chinese_ocr_db_crnn_mobile==1.0.1
```

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
