### ISSUE TITLE
你好在运用百度口罩检测模型的时候，报错

### ISSUE THREAD

**Issue by yousong1992** [PaddlePaddle/PaddleFormers#648]
RuntimeError: pyramidbox_lite_server_mask does not support dynamic graph mode yet.
报错是这个错误，但是我两个python文件处理方式是一样的，都是通过rtsp流读取视频流，获得一张图片格式为numpy数组放入列表中，然后送入模型检测，一个demo没问题，另外一个会报上面的错误

            img_rd = stack.pop()        # Get camera video stream
            print('图片属性',type(img_rd))
            kk = cv2.waitKey(1)
            img_list.append(img_rd)
            print(img_list,'列表图片长度',len(img_list))
            faces = []
            result = mask_detector(img_list)# Use paddle face detector

图片属性 <class 'numpy.ndarray'> 我不明白为什么 麻烦了

**Comment by yousong1992** [comment]
在同一个环境下，同一种处理方式，一种没有问题可以正常使用，一种报错如上面所说.

**Comment by nepeplwu** [comment]
@yousong1992 报错的堆栈麻烦贴下

**Comment by yousong1992** [comment]
@nepeplwu 没事大哥解决了，自己的问题 少打了一个函数。。不好意思打扰了.
