### ISSUE TITLE
【必重现】CPU_NUM > 1 时训练发生异常

### ISSUE THREAD

**Issue by cvdnn** [PaddlePaddle/PaddleFormers#649]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.7.0，PaddlePaddle1.8.1
2）系统环境：CentOS Linux release 7.8.2003 (Core)，python版本：Python 3.6.8
- 复现信息：
![异常堆栈信息](http://comn.cvdnn.com/paddle/paddle_error.png)

**Comment by kinghuin** [comment]
hi，请问您的数据量，batch_size，CPU_NUM分别是多少呢？

**Comment by kinghuin** [comment]
初步判断是   数据量无法被(batch_size*CPU_NUM)整除 导致有CPU设备没能接受到足够数据

**Comment by cvdnn** [comment]
"ai": {
    "cpu_num": 24,
    "train_ratio": 0.8,
    "task": {
      "use_cuda": false,
      "use_pyreader": false,
      "num_epoch": 16,
      "batch_size": 96
    },

**Comment by kinghuin** [comment]
数据量是多少呢

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
