### ISSUE TITLE
运行predict时报错

### ISSUE THREAD

**Issue by TianTian-O1** [PaddlePaddle/PaddleFormers#65]
Traceback (most recent call last):
  File "predict.py", line 76, in <module>
    fluid.io.load_persistables(exe, args.checkpoint_dir)
  File "/home/tianzhen/.local/lib/python3.7/site-packages/paddle/fluid/io.py", line 704, in load_persistables
    filename=filename)
  File "/home/tianzhen/.local/lib/python3.7/site-packages/paddle/fluid/io.py", line 575, in load_vars
    filename=filename)
  File "/home/tianzhen/.local/lib/python3.7/site-packages/paddle/fluid/io.py", line 610, in load_vars
    executor.run(load_prog)
  File "/home/tianzhen/.local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/home/tianzhen/.local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator load error.
Python Callstacks: 
  File "/home/tianzhen/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/tianzhen/.local/lib/python3.7/site-packages/paddle/fluid/io.py", line 596, in load_vars
    attrs={'file_path': os.path.join(dirname, new_var.name)})
  File "/home/tianzhen/.local/lib/python3.7/site-packages/paddle/fluid/io.py", line 575, in load_vars
    filename=filename)
  File "/home/tianzhen/.local/lib/python3.7/site-packages/paddle/fluid/io.py", line 704, in load_persistables
    filename=filename)
  File "predict.py", line 76, in <module>
    fluid.io.load_persistables(exe, args.checkpoint_dir)
C++ Callstacks: 
Cannot open file CKPT_DIR/@HUB_ernie-stable@encoder_layer_6_multi_head_att_key_fc.w_0 for load op at [/paddle/paddle/fluid/operators/load_op.h:37]
PaddlePaddle Call Stacks: 
0       0x7fe8da2e6830p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fe8da2e6ba9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fe8da8b65a6p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 774
3       0x7fe8da8b6813p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
4       0x7fe8db492da6p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 662
5       0x7fe8db4938a4p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
6       0x7fe8db491a7bp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 267
7       0x7fe8da44c23ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 158
8       0x7fe8da44f21fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
9       0x7fe8da2d74bep
10      0x7fe8da31620ep
11            0x5d8014p _PyMethodDef_RawFastCallKeywords + 548
12            0x5d9970p _PyObject_FastCallKeywords + 1744
13            0x54b0f1p
14            0x552197p _PyEval_EvalFrameDefault + 17495
15            0x54b9f2p _PyEval_EvalCodeWithName + 594
16            0x5d8c62p _PyFunction_FastCallKeywords + 1154
17            0x54af20p
18            0x54f0eep _PyEval_EvalFrameDefault + 5038
19            0x54b9f2p _PyEval_EvalCodeWithName + 594
20            0x5d8c62p _PyFunction_FastCallKeywords + 1154
21            0x54e3dcp _PyEval_EvalFrameDefault + 1692
22            0x54b9f2p _PyEval_EvalCodeWithName + 594
23            0x5d8c62p _PyFunction_FastCallKeywords + 1154
24            0x54af20p
25            0x54f0eep _PyEval_EvalFrameDefault + 5038
26            0x54b9f2p _PyEval_EvalCodeWithName + 594
27            0x5d8c62p _PyFunction_FastCallKeywords + 1154
28            0x54af20p
29            0x54f0eep _PyEval_EvalFrameDefault + 5038
30            0x54b9f2p _PyEval_EvalCodeWithName + 594
31            0x5d8c62p _PyFunction_FastCallKeywords + 1154
32            0x54af20p
33            0x552197p _PyEval_EvalFrameDefault + 17495
34            0x54b9f2p _PyEval_EvalCodeWithName + 594
35            0x54dd33p PyEval_EvalCode + 35
36            0x630f22p
37            0x630fd7p PyRun_FileExFlags + 151
38            0x631c3fp PyRun_SimpleFileExFlags + 383
39            0x65414ep
40            0x6544aep _Py_UnixMain + 46
41      0x7fe8f89eab6bp __libc_start_main + 235
42            0x5e04eap _start + 42

**Comment by nepeplwu** [comment]
@TianZhenGG ，请问运行的是哪个分支的哪个demo？args.checkpoint_dir存在吗？

**Comment by TianTian-O1** [comment]
@nepeplwu   ，这是paddlehub下的demo下的text-classification, 没有args.checkpoint_dir

**Comment by nepeplwu** [comment]
@TianZhenGG ，需要先运行下sh run_classifcation.sh，等有checkpoint后再执行predict。
从截图看，运行的是0.5.0分支的demo，我们在新的分支上升级了接口，以及增加了更多的demo，建议使用新的demo体验下：https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.0.0/demo/text-classification
