### ISSUE TITLE
hub文字识别返回空结果

### ISSUE THREAD

**Issue by liweigu** [PaddlePaddle/PaddleFormers#650]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.7.1，PaddlePaddle1.8.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
Ubuntu 18.04，Python3
- 复现信息：如为报错，请给出复现环境、复现步骤
根据 https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.7/hub_module/modules/image/text_recognition/chinese_ocr_db_crnn#第二步发送预测请求
修改服务地址和图片路径，调用服务不能得到分析结果，返回{"msg":"Please check data format!","results":"","status":"-1"}。
经沟通发现：这个模型还不支持处理base64，也还使用不了serving。
需要更新模型解决。

**Comment by Steffy-zxf** [comment]
你好！目前文字识别模型已经升级新版本，详细信息参考PaddleHub官网文档：https://www.paddlepaddle.org.cn/hublist?filter=en_category&value=TextRecognition

chinese_text_detection_db已经更改名字为 chinese_text_detection_db_mobile
chinese_ocr_db_crnn已经更改名字为chinese_ocr_db_crnn_mobile
```shell
$ hub install chinese_text_detection_db_mobile==1.0.1
$ hub install chinese_ocr_db_crnn_mobile==1.0.1
```

**Comment by liweigu** [comment]
升级后的模型可以发布服务，并且客户端访问它正常。

**Comment by liweigu** [comment]
请问，
1）从测试结果看，好像只能识别文本，不能识别数字，请问mobile版本支持手写数字识别吗？
2）chinese_text_detection_db_server 和 chinese_ocr_db_crnn_server 还没有1.0.1版本，近期会发布吗？

**Comment by Steffy-zxf** [comment]
1. 从测试结果看，好像只能识别文本，不能识别数字，请问mobile版本支持手写数字识别吗？
 是否可以将未能识别成功的图片附上，我们看看问题。

2. chinese_text_detection_db_server 和 chinese_ocr_db_crnn_server 还没有1.0.1版本，近期会发布吗？
chinese_text_detection_db_server 和 chinese_ocr_db_crnn_server  1.0.0 版本 已经支持 服务部署的用法。也就是说 它们两和 mobile模型1.0.1版本支持的功能一样。
另外，server模型效果上比mobile更佳。但mobile模型参数量级更小，属于轻量级ocr模型。

**Comment by liweigu** [comment]
使用mobile版本模型，这张图片识别结果只有字母
![3](https://user-images.githubusercontent.com/31612697/83390248-179a7d80-a424-11ea-82d7-c9a7048740bb.png)
这张图片里的数字都没识别到
<img width="576" alt="4" src="https://user-images.githubusercontent.com/31612697/83390303-2da83e00-a424-11ea-83f0-acdd1689f936.png">

**Comment by liweigu** [comment]
换 chinese_ocr_db_crnn_server==1.0.0 模型，第一张图能识别到 'text': '103', 'text': '123', 'text': '3', 'text': '口'，第2张图还是没有任何结果。

**Comment by dyning** [comment]
上面测试数据是手写体数字，开源的模型中训练数据没有手写体数据。可以利用手写体数字的数据，重新训练模型使用。

**Comment by liweigu** [comment]
哦，目前hub还没提供支持手写数字的模型吧。
另外想问问，hub run chinese_ocr_db_crnn_server --input_path xxx 怎么设置 text_thresh，以及 hub serving start -m chinese_ocr_db_crnn_server 怎么设置 text_thresh ？

**Comment by Steffy-zxf** [comment]
命令行hub run不支持设置text_thresh。可以直接在预测接口中设置，如

```python
import paddlehub as hub
import cv2

ocr = hub.Module(name="chinese_ocr_db_crnn_server")
# 预测接口中设置text_thresh
result = ocr.recognize_text(images=[cv2.imread('/PATH/TO/IMAGE')], text_thresh=0.5)
```

在HubServing中请求服务参数设置如：
```python
import requests
import json
import cv2
import base64

def cv2_to_base64(image):
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')

# 发送HTTP请求, 在data中设置text_thresh
data = {'images':[cv2_to_base64(cv2.imread("/PATH/TO/IMAGE"))], "text_thresh":0.5}
headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:8866/predict/chinese_ocr_db_crnn_server"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(r.json()["results"])
```

**Comment by liweigu** [comment]
好的，谢谢。

**Comment by WJinhai** [comment]
这个方法预测一张图片需要时间很久，有什么办法解决吗？result=ocr.recognize_text(images=[cv2.imread('/PATH/TO/IMAGE')], text_thresh=0.5) 这行代码的执行时间很久

**Comment by liweigu** [comment]
文字多的时候预测更慢，建议先拿文字少的实验。
