### ISSUE TITLE
序列标注默认教程沙盒部署自定义数据转换

### ISSUE THREAD

**Issue by wuzixin** [PaddlePaddle/PaddleFormers#651]
用序列标注默认教程跑了一个模型，沙盒部署的时候自定义转换数据总是不对，这一块有没有一个例子可以参考呢

**Comment by Steffy-zxf** [comment]
你好！

> 沙盒部署的时候自定义转换数据总是不对

报错信息是什么呢？同时相应的代码方便贴上吗？同时请安装paddlehub 1.7.1 最新版本，paddle 1.8.0版本。另外想了解下你说的沙盒环境是什么环境？是指AIStudio上部署预测服务吗？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
