### ISSUE TITLE
paddlehub调用GPU报错

### ISSUE THREAD

**Issue by yousong1992** [PaddlePaddle/PaddleFormers#652]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
paddlehub1.7.1 paddlepaddle-gpu 1.8.1post107，
win10 python3.6
报错信息为：
  File "C:/project/Dlib_face_recognition_from_camera-master/re_get_face.py", line 103, in process
    result = mask_detector.face_detection(img_list,use_gpu=True)
  File "C:\Users\dltbj\.paddlehub\modules\pyramidbox_lite_server_mask\module.py", line 127, in face_detection
    images, paths, use_gpu, use_multi_scale):
  File "C:\Users\dltbj\.paddlehub\modules\pyramidbox_lite_server_mask\data_feed.py", line 202, in reader
    confs_threshold=confs_threshold)
  File "C:\Users\dltbj\.paddlehub\modules\pyramidbox_lite_server\module.py", line 106, in face_detection
    ]) if use_gpu else self.cpu_predictor.run([image_tensor])
  File "C:\Users\dltbj\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\dygraph\layers.py", line 533, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'PyramidBoxLiteServer' object has no attribute 'gpu_predictor'
不明白为什么，我另一个代码用了同样的调用方式，是可以使用GPU的说明环境应该没有问题。
报错代码为:
        cam_url = 'rtsp://admin:12345@192.168.1.64:554/h264/ch1/main/av_stream'
        cap = cv2.VideoCapture(cam_url)
        while True:
            img_list = []
            flag, img_rd = cap.read()# Get camera video stream
            img_list.append(img_rd)
            kk = cv2.waitKey(1)
            result = mask_detector.face_detection(img_list,use_gpu=True)
            faces = []

**Comment by Steffy-zxf** [comment]
你好！想要使用GPU环境预测需要在运行之前设置CUDA_VISIBLE_DEVICES环境变量。

**Comment by yousong1992** [comment]
我已经设置了这个环境变量让他等于0，我相同的环境跑另一个程序同样调用咱们这个paddlegpu是可以跑通的，就很奇怪…发自我的华为手机-------- 原始邮件 --------发件人： Steffy-zxf <notifications@github.com>日期： 2020年5月30日周六 上午10:49收件人： PaddlePaddle/PaddleHub <PaddleHub@noreply.github.com>抄送： yousong1992 <dltbjys1992@163.com>, Author <author@noreply.github.com>主    题： Re: [PaddlePaddle/PaddleHub] paddlehub调用GPU报错 (#652)

你好！想要使用GPU环境预测需要在运行之前设置CUDA_VISIBLE_DEVICES环境变量。

**Comment by Steffy-zxf** [comment]
我复现使用GPU正常，没能复现你的错误。试试将pyramidbox_lite_server_mask，pyramidbox_lite_server卸载重新安装试试。

```shell
$ hub uninstall pyramidbox_lite_server_mask
$ hub uninstall pyramidbox_lite_server
$
$ hub install pyramidbox_lite_server_mask
$ hub install pyramidbox_lite_server
```

**Comment by yousong1992** [comment]
好的，是这样，我也觉得奇怪，就是我写了两个代码，基本上都是一样的，就是都是通过rtsp读取海康威视的摄像头，一个用gpu一点问题没有，另一个就会出现这个问题，我查了半天代码实在找不到有什么区别。我周一在查查吧，电脑在单位。发自我的华为手机-------- 原始邮件 --------发件人： Steffy-zxf <notifications@github.com>日期： 2020年5月30日周六 傍晚6:45收件人： PaddlePaddle/PaddleHub <PaddleHub@noreply.github.com>抄送： yousong1992 <dltbjys1992@163.com>, Author <author@noreply.github.com>主    题： Re: [PaddlePaddle/PaddleHub] paddlehub调用GPU报错 (#652)

我复现使用GPU正常，没能复现你的错误。试试将pyramidbox_lite_server_mask，pyramidbox_lite_server卸载重新安装试试。

$ hub uninstall pyramidbox_lite_server_mask

$ hub uninstall pyramidbox_lite_server

$

$ hub install pyramidbox_lite_server_mask

$ hub install pyramidbox_lite_server

**Comment by yousong1992** [comment]
@Steffy-zxf  您好 我按照您的方法试了一下，还是同样的报错，重新安装也不好用，os.environ['CUDA_VISIBLE_DEVICES'] = '0'我已经添加了这个代码，并且在我另一段程序中，调用gpu是没有任何问题的。或者这么说，result = mask_detector.face_detection(img_list)我在这个代码段，如果不加use_gpu=True，程序是可以跑的，但是加了 result = mask_detector.face_detection(img_list,use_gpu=True)，就会报错。报错信息如下：
  File "C:/project/Dlib_face_recognition_from_camera-master/re_get_face.py", line 103, in process
    result = mask_detector.face_detection(img_list, use_gpu=True)
  File "C:\Users\dltbj\.paddlehub\modules\pyramidbox_lite_server_mask\module.py", line 127, in face_detection
    images, paths, use_gpu, use_multi_scale):
  File "C:\Users\dltbj\.paddlehub\modules\pyramidbox_lite_server_mask\data_feed.py", line 202, in reader
    confs_threshold=confs_threshold)
  File "C:\Users\dltbj\.paddlehub\modules\pyramidbox_lite_server\module.py", line 106, in face_detection
    ]) if use_gpu else self.cpu_predictor.run([image_tensor])
  File "C:\Users\dltbj\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\dygraph\layers.py", line 533, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'PyramidBoxLiteServer' object has no attribute 'gpu_predictor'

**Comment by yousong1992** [comment]
@Steffy-zxf 最后我的解决办法是用多进程，一个进程读取RTSP流，另一个进程从共享内存中获取图片，这样就不会报错，我也不知道为什么。。
            if len(stack) > 1 and flag.value:
                img_rd = stack.pop()
                flag.value = False
                img_list.append(img_rd)
                kk = cv2.waitKey(1)
                result = mask_detector.face_detection(img_list, use_gpu=True)
                faces = []
                for i in result[0]['data']:
                    left = i['left']
                    top = i['top']
                    right = i['right']
                    bottom = i['bottom']
这样就不会报错

**Comment by Steffy-zxf** [comment]
@yousong1992 方便提供下**最小**复现错误代码吗？

**Comment by yousong1992** [comment]
@Steffy-zxf 您有邮箱吗 我单发你邮箱可以吗？ 其实我报错代码就是这段，我只是不太明白为什么会这样，没道理会报错，因为我多进程这么玩就可以用GPU，单进程就会报错。
import paddlehub as hub
mask_detector = hub.Module(name="pyramidbox_lite_server_mask")
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
        # 1. 读取存放所有人脸特征的 csv
        if self.get_face_database():
            cam = 'rtsp://admin:hhgk4321@192.168.1.64:554/h264/ch1/main/av_stream'
            cap = cv2.VideoCapture(cam)
            while True:
                img_list = []
                flag, img_rd = cap.read()
                img_list.append(img_rd)
                result = mask_detector.face_detection(img_list,use_gpu = True)
                faces = []
                for i in result[0]['data']:
                    left = i['left']
                    top = i['top']
                    right = i['right']
                    bottom = i['bottom']
                    face = dlib.rectangle(int(left), int(top), int(right), int(bottom))
                    faces.append(face)

**Comment by Steffy-zxf** [comment]
你好！根据上述代码，

> import paddlehub as hub
mask_detector = hub.Module(name="pyramidbox_lite_server_mask")
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

因为在加载pyramidbox_lite_server_mask module时，会同时进行运行设置初始化。请将环境变量设置置于加载module之前，代码如下：

> import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
import paddlehub as hub
mask_detector = hub.Module(name="pyramidbox_lite_server_mask")

**Comment by yousong1992** [comment]
OKOK 原来是这样 我搞明白了 ！！感谢！！

**Comment by jeffzhengye** [comment]
> 你好！想要使用GPU环境预测需要在运行之前设置CUDA_VISIBLE_DEVICES环境变量。

有，这个会直接对应的错误，跟tf一样。
