### ISSUE TITLE
pyramidbox_lite_mobile_mask 1.3.0文档有误

### ISSUE THREAD

**Issue by FruitTea2015** [PaddlePaddle/PaddleFormers#657]
PaddleHub 1.7.0
pyramidbox_lite_mobile_mask 1.3.0

用的是AI Studio在线环境

文档中face_detection函数并没有data这个参数，只有images参数，要求传入[BGR]格式的图片。但在实际使用中，我对照着别的教程做，用了data这个参数，也可以执行，而且函数的返回值格式也与文档中描述的不同。可能是文档写错了，或者是module只升级了版本号而并没有更新具体代码。

具体示例见以下链接：
https://aistudio.baidu.com/aistudio/projectdetail/521073
（在第三步，[In13]）

**Comment by Steffy-zxf** [comment]
感谢反馈！pyramidbox_lite_mobile_mask 1.3.0版本之后对预测接口face_detection进行了升级，支持images参数 和 paths参数。data参数为pyramidbox_lite_mobile_mask 1.0.0版本的用法，新版本的模型预测接口data参数已被废弃。推荐使用images参数 或 paths参数。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
