### ISSUE TITLE
对于NLPCC-DBQA预测的predict.py文件配置

### ISSUE THREAD

**Issue by TianTian-O1** [PaddlePaddle/PaddleFormers#66]
范例中predict采用的是chnsentcorp,如果想预测dbqa问答系统，具体该如何设置，能不能在text_b输出预测文本呢。

**Comment by nepeplwu** [comment]
@TianZhenGG ，用ernie做问答系统的话，预测时同时输入问题和答案，根据预测结果的接近程度来选择问题的答案。
例如有问题a和候选答案[a1, a2, a3]，预测时依次预测[a, a1]、[a, a2]、[a, a3]的结果，选择预测结果最接近1的作为答案

**Comment by TianTian-O1** [comment]
大概是懂了，可以有参考的文件吗


 
---原始邮件---
发件人: "wuzewu"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 晚上7:47
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"TianZhenGG"<410771376@qq.com>;
主题: Re: [PaddlePaddle/PaddleHub] 对于NLPCC-DBQA预测的predict.py文件配置 (#66)



@TianZhenGG ，用ernie做问答系统的话，预测时同时输入问题和答案，根据预测结果的接近程度来选择问题的答案。
 例如有问题a和候选答案[a1, a2, a3]，预测时依次预测[a, a1]、[a, a2]、[a, a3]的结果，选择预测结果最接近1的作为答案

**Comment by Steffy-zxf** [comment]
可以参考release/v1.0.0分支下demo/qa_classification。

**Comment by Steffy-zxf** [comment]
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.0.0/demo/qa_classification
