### ISSUE TITLE
肺炎 CT 模型可否finetune

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleFormers#660]
想请问针对分割类型的模型paddlehub是否有finetune的支持，查找了文档只发现了分类和nlp方面finetune的文档，并没有发现分割方向的。

**Comment by Steffy-zxf** [comment]
你好！目前PaddleHub 肺炎 CT module只支持预测。分割任务迁移学习可以移步 https://github.com/PaddlePaddle/PaddleSeg

**Comment by linhandev** [comment]
收到，请问未来有添加分割模型的finetune的计划吗

**Comment by Steffy-zxf** [comment]
分割任务迁移学习，PaddleHub会在未来版本支持。

**Comment by linhandev** [comment]
收到，谢谢
