### ISSUE TITLE
图片base64编码支持明码格式

### ISSUE THREAD

**Issue by liweigu** [PaddlePaddle/PaddleFormers#665]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
需要图片base64编码支持明码格式。

- 什么样的场景下需要该特性？
python客户端访问paddle服务进行图片文字识别，示例代码对图片进行base64编码的方法是
def cv2_to_base64(image):
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')
其中data是一维数字数组，data.tostring()应该是python array的tostring方法，或numpy的PyArray_ToString方法，它的实现比较复杂，难以用Java复写。

- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
由于不能用Java复写该tostring方法，就无法实现java客户端调用paddlehub服务实现图片文字识别。

- 增加该特性，PaddleHub可能需要变化的部分。
需要修改图片文字识别服务，支持明码的图片编码格式。

- 如果可以的话，简要描述下您的解决方案
方案1，定义一种开放的明码的图片编码格式，便于用其他语言实现。
方案2，提供python的data.tostring()的实现说明。

**Comment by ShenYuhan** [comment]
base64是图片在网络传输的一种基础格式，java、c++、python都有图片转base64的实现，最终只要保证传过去的是base64格式就可以了，您不需要实现一摸一样的cv2_to_base64

**Comment by liweigu** [comment]
base64.b64encode(data.tostring()).decode('utf8')
这句代码在base64编码之前会先调用 data.tostring()，一维数字数组的tostring在Java里没有跟python一样的实现。

**Comment by ShenYuhan** [comment]
您原始数据是本地图片文件还是nd.array表示的图片？

**Comment by liweigu** [comment]
原始数据是本地图片文件，Java读取出的数值能跟 cv2.imencode('.jpg', image)[1] 一样是个一维数组，类型是整型数字。

**Comment by ShenYuhan** [comment]
这样的话其实直接从本地文件处理成base64就行了

**Comment by liweigu** [comment]
好的，我试过用这段代码直接对文件base64编码就行了。
		Path path = FileSystems.getDefault().getPath("D:/temp/", "me.png"); // 1.jpg
		byte[] fileData = Files.readAllBytes(path);
		String imageData = Base64.getEncoder().encodeToString(fileData);

**Comment by xu-feiran** [comment]
亲测有用
