### ISSUE TITLE
Hub serving一键部署后应用lac预测接口使用自定义字典报错

### ISSUE THREAD

**Issue by wangxingMachine** [PaddlePaddle/PaddleFormers#667]
1）PaddleHub 1.7.1， PaddlePaddle 1.8.1
2）Linux 16.04，  Python3.6.0

1、使用示例代码执行报错（1.6、1.7分支代码一致）
示例地址：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/demo/serving/module_serving/lexical_analysis_lac/lac_with_dict_serving_demo.py
![image](https://user-images.githubusercontent.com/16412208/83712703-ec4ca400-a658-11ea-8751-1b40d28b91f0.png)

2、根据提示修改请求为post json
代码：
`#coding: utf8
import requests
import json

if __name__ == "__main__":
    # 指定用于预测的文本并生成字典{"text": [text_1, text_2, ... ]}
    text_list = ["今天是个好日子", "天气预报说今天要下雨"]
    text = {"texts": text_list}
    # 指定自定义词典{"user_dict": dict.txt}
    file = {"user_dict": open("dict.txt", "rb")}
    # 指定预测方法为lac并发送post请求
    url = "http://127.0.0.1:8866/predict/text/lac"
    headers = {"Content-Type": "application/json"}
    r = requests.post(url=url, headers=headers, files=file, data=json.dumps(text))

    # 打印预测结果
    print(json.dumps(r.json(), indent=4, ensure_ascii=False))
`
报错如下：
![image](https://user-images.githubusercontent.com/16412208/83712852-451c3c80-a659-11ea-8508-ef8839643221.png)

**请问：
1、lac预测接口是否支持同时传json和自定义字典文件？该如何解决？
2、hub serving一键部署指定自定义字典后启动，支持动态刷新字典么，如果放在接口里面传递字典文件，对大小是否有限制及对预测效率有无影响**

谢谢！

note:hub serving通过配置文件指定字典启动，可以正常使用

**Comment by Steffy-zxf** [comment]
你好！根据以上错误提示，你当前使用的Hub Serving请求方法已过时，最新用法可以参考：
https://www.paddlepaddle.org.cn/hubdetail?name=lac&en_category=LexicalAnalysis
![image](https://user-images.githubusercontent.com/48793257/83739879-bb846300-a688-11ea-96fa-56c436200bd8.png)

> hub serving一键部署指定自定义字典后启动，支持动态刷新字典么，如果放在接口里面传递字典文件，对大小是否有限制及对预测效率有无影响?

请求hub serving服务时，已经无法再更改自定义词典。自定义词典，已经是在你启动服务的时候已经确定了。关于自定义词典用法还是参考上述链接

![image](https://user-images.githubusercontent.com/48793257/83740413-6137d200-a689-11ea-9d48-765b1d6d1016.png)

**Comment by wangxingMachine** [comment]
谢谢回复！
最新的用法https://www.paddlepaddle.org.cn/hubdetail?name=lac&en_category=LexicalAnalysis已经尝试过了，通过hub命令or Python脚本使用模块来应用自定义字典没有问题。
现在是通过Hub Serving一键部署后，不能通过接口传递自定义字典文件，是现在不支持这种用法了么？

**Comment by Steffy-zxf** [comment]
lac自定义词典，hub serving用法参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/demo/serving/module_serving/lexical_analysis_lac/lac_with_dict_serving_demo.py

**Comment by wangxingMachine** [comment]
就是按照这个试过报错的

**Comment by ShenYuhan** [comment]
您好，新的hub-serving已经不支持部署后传递自定义字典了

**Comment by wangxingMachine** [comment]
好的，那推荐使用老版本的部署么？
现在lac预测实现动态字典只有两种方式了吧
1、hub-serving配置文件指定字典位置，修改字典后重启服务
2、python代码直接应用字典

**Comment by ShenYuhan** [comment]
推荐使用新的，但如果您一定要每次预测都可以传入新的自定义字典，那就只能用旧版本了。从服务的角度来看，字典的配置也应该由服务端配置。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
