### ISSUE TITLE
hub的模型可以离线安装吗？

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/PaddleFormers#668]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

使用object_detector = hub.Module(name="yolov3_darknet53_coco2017")进行预测
网络不好，下载模型时间太长太慢， 有什么地址可以 
（1）离线下载
（2）然后进行安装吗？

**Comment by Steffy-zxf** [comment]
你好！下载模型，PaddleHub必须在访问外网的情况下才能下载。你可以现在网络条件好的环境下，先下载安装对应的module，之后将安装好module 完整的拷贝到你需要的机器上，放在`HUB_HOME`下。关于`HUB_HOME`的解释参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/docs/tutorial/cmdintro.md#paddlehub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7

**Comment by applepieiris** [comment]
> 你好！下载模型，PaddleHub必须在访问外网的情况下才能下载。你可以现在网络条件好的环境下，先下载安装对应的module，之后将安装好module 完整的拷贝到你需要的机器上，放在`HUB_HOME`下。关于`HUB_HOME`的解释参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/docs/tutorial/cmdintro.md#paddlehub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7

请问如果在虚拟环境中安装的paddlehub，如何更改HUB_HOME设置呢？我没有管理员权限，所以无法设置环境变量。
