### ISSUE TITLE
可以基于飞桨的人脸口罩模型训练自己的模型？

### ISSUE THREAD

**Issue by DavidFangx** [PaddlePaddle/PaddleFormers#670]
需求：飞桨的人脸口罩模型应用效果很好。但偏重于识别我们日常佩戴的口罩，有的些口罩是透明类型的，如我们去熟食店或卤菜店或食堂，要求工作人员佩戴透明口罩，若没有佩戴需要预警。我们希望能基于飞桨的人脸口罩模型训练自己的模型，请提供帮助，谢谢！
[https://detail.tmall.com/item.htm?spm=a220m.1000858.1000725.144.23a3603dY1ihCn&id=562234066040&skuId=4240902433288&user_id=2049340132&cat_id=2&is_b=1&rn=f4b0c5545a57a909585bb58925b9c7ac](url)

如何制作数据集？  先标注人脸，再标注透明口罩？

**Comment by nepeplwu** [comment]
@DavidFangx 感谢反馈，PaddleHub目前还不支持检测类任务的训练，可以看看[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection)

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
