### ISSUE TITLE
运行口罩识别时候出现bug

### ISSUE THREAD

**Issue by hanqikai** [PaddlePaddle/PaddleFormers#678]
在运行官方给的口罩识别demo时，运行到最后一步，出现文件未找到错误：
FileNotFoundError: [Errno 2] No such file or directory: 'detection_result/test_mask_detection.jpg'
对官网给的demo一点都没有修改，在notebook中出现这个错误，请问如何解决？

**Comment by Steffy-zxf** [comment]
你好！选择官方口罩项目最新版本重新运行试试，上一版本没有把detection_result/test_mask_detection.jpg文件公开。
参考其中口罩模型文档API说明：https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_mobile_mask&en_category=FaceDetection
另外，预测接口face_detection参数
* visualization (bool): 表示是否将识别结果保存为图片文件；

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
