### ISSUE TITLE
paddlehub 目标检测，输入数组报错

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/PaddleFormers#681]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
paddlehub              1.6.2
paddlepaddle-gpu       1.8.1.post107
使用results = object_detector.object_detection(images=[cv2.imread('./dog')],use_gpu=True)
进行预测
dog文件夹下只有4张图片，提示报错如下
Traceback (most recent call last):
  File "main_mutil.py", line 19, in <module>
    results = object_detector.object_detection(images=[cv2.imread('./dog')],use_gpu=True)
  File "/root/.paddlehub/modules/yolov3_darknet53_coco2017/module.py", line 199, in object_detection
    for iter_id, feed_data in enumerate(batch_reader()):
  File "/root/anaconda3/envs/dog/lib/python3.7/site-packages/paddle/batch.py", line 58, in batch_reader
    for instance in r:
  File "/root/.paddlehub/modules/yolov3_darknet53_coco2017/data_feed.py", line 39, in reader
    im_shape = im.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Steffy-zxf** [comment]
你好！根据上述显示代码，

> results = object_detector.object_detection(images=[cv2.imread('./dog')],use_gpu=True)
进行预测
dog文件夹下只有4张图片

`cv2.imread(path)` 这个接口用于读取图片，`path`为图片所在路径。你的代码没有指定完全。所以图片图片为空，报错。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
