### ISSUE TITLE
paddlehub进行检测，为什么每次第一帧检测时间都很长

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/PaddleFormers#683]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
paddlehub              1.6.2
paddlepaddle-gpu       1.8.1.post10

启动hub对图像预测的时候，发现每次第一次的预测都会时间很长，后面就很快，
我做了一个测试，对同一张图进行10次的预测， 结果如下
dec is 11.1651451587677
dec is 0.9181404113769531
dec is 0.15127277374267578
dec is 0.1371166706085205
dec is 0.1367952823638916
dec is 0.1357100009918213
dec is 0.12549448013305664
dec is 0.29573535919189453
dec is 0.29613327980041504
dec is 0.28490161895751953
dec is 0.15406084060668945
dec is 0.1517481803894043
-----------------------------
dec is 10.995591163635254
dec is 0.9476826190948486
dec is 0.15262794494628906
dec is 0.14814209938049316
dec is 0.1429147720336914
dec is 0.13404297828674316
dec is 0.13592171669006348
dec is 0.13328957557678223
dec is 0.12551116943359375
dec is 0.12455463409423828
这个是什么原因？

**Comment by Steffy-zxf** [comment]
你好！由于module预测时，第一次预测需要创建预测program以及相应预测设置，所以第一次调用预测接口时间会相对较长。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
