### ISSUE TITLE
installed paddlehub via pip: now cannot import paddle.fluid

### ISSUE THREAD

**Issue by andreazanetti** [PaddlePaddle/PaddleFormers#685]
Hi, I am not sure I am posting this issue in the right place, however, the problem I am having is the following:
I have installed PaddlePaddle from source, and then cloned the paddle model repo.
Happily tested VGG, did some stuff with VisualDL to test it, happily run sentiment_classification using run.sh script under PaddleNL/sentiment_calssification
Once I tried to run ernie for sentiment classification however, using ./run_ernie.sh train it complained that "import paddlehub" could not be done as module was absent.
So I have installed it, `pip install paddlehub --user`, and after that I cannot import paddle.fluid anymore. Anytime I try I get the following error message:
`  File "/nfs/pdx/home/azanetti/.local/lib/python2.7/site-packages/nltk/probability.py", line 333
    print("%*s" % (width, samples[i]), end=" ")
                                          ^
SyntaxError: invalid syntax`
I thought it was something connected to missing `from __future_ import print_function` or alike but these imports are already in the code. Could you please let me know? thanks!

**Comment by Steffy-zxf** [comment]
Hi！ As referred：

> File "/nfs/pdx/home/azanetti/.local/lib/python2.7/site-packages/nltk/probability.py", line 333 print("%*s" % (width, samples[i]), end=" ") ^ SyntaxError: invalid syntax

the python version is 2.7. PaddleHub (1.7+) only works on python 3.6+. Please check the used environment, and update paddlepaddle and paddlehub to the latest version.

**Comment by andreazanetti** [comment]
Hi thanks for your reply. What I reported was obtained using develop branch of  Paddle, built from source, python 2.7. 
After that, I cloned the release 1.8 of model repo. Everything worked fine, ran VGG and other simple tests.
As I said, when I tried`./run_ernie.sh train` it requested to install paddlehub.
So I am not clear here, apologies. If I paddlehub  only works with python 3.6+, then the version of ernie for sentiment_calssification is not supposed to be run with paddle built on 2.7? 
Can you please clarify? thanks!

**Comment by Steffy-zxf** [comment]
> PaddleHub (1.7+) only works on python 3.6+. 

PaddleHub only works on python3.6+ over version 1.7.0. If you install the latest version paddle, I would prefer you to use the latest paddlehub (v1.7.1).

**Comment by andreazanetti** [comment]
rebuilt Paddle on the last develop branch and this issue does not appear anymore, so I close the issue for the moment. Thanks
