### ISSUE TITLE
在做Fine-tune保存的模型转化为一个PaddleHub Module时报了错

### ISSUE THREAD

**Issue by zhuyingjun-zyj** [PaddlePaddle/PaddleFormers#687]
使用fine-tune后的RENIE模型做文本分类后，将其转化为Paddle Hub Module时报错了
具体错误信息：
```bash
[2020-06-11 16:48:50,307] [    INFO] - Load the best model from D:\project\test\textPaddle\finetuned_model_to_module\modle.ckpt\best_model
C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
[2020-06-11 16:49:00,985] [    INFO] - PaddleHub predict finished.
Traceback (most recent call last):
  File "D:/project/test/textPaddle/finetuned_model_to_module/module.py", line 91, in <module>
    predictions = ernie_tiny.predict(data=data)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddlehub\module\module.py", line 72, in _wrapper
    return func(*args, **kwargs)
  File "D:\project\test\textPaddle\finetuned_model_to_module\module.py", line 82, in predict
    accelerate_mode=accelerate_mode)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddlehub\finetune\task\base_task.py", line 1024, in predict
    return self._postprocessing(run_states)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddlehub\finetune\task\classifier_task.py", line 156, in _postprocessing
    results += [id2label[sample_infer] for sample_infer in batch_infer]
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddlehub\finetune\task\classifier_task.py", line 156, in <listcomp>
    results += [id2label[sample_infer] for sample_infer in batch_infer]
KeyError: 1
```

**Comment by kinghuin** [comment]
Hi， 麻烦贴一下代码部分

**Comment by zhuyingjun-zyj** [comment]
```python
#-*-coding:utf-8-*-
"""
@author:zhuhyingjun
@time:2020/6/11 9:49
"""
"""Finetuning on classification task """

import os
from paddlehub.module.module import moduleinfo, serving
import paddlehub as hub

@moduleinfo(
    name="my_ernie_finetuned",
    version="1.0.0",
    summary="ERNIE which was fine-tuned on the myset dataset.",
    author="zhuyingjun",
    author_email="zhuyingjunzyj@163.com",
    type="nlp/semantic_model")
class ERNIEFinetuned(hub.Module):
    def _initialize(self,
                    ckpt_dir="/modle.ckpt",
                    num_class=5,
                    max_seq_len=128,
                    use_gpu=False,
                    batch_size=32):
        self.ckpt_dir = os.path.join(self.directory, ckpt_dir)
        self.num_class = num_class
        self.MAX_SEQ_LEN = max_seq_len

        # Load Paddlehub ERNIE Tiny pretrained model
        self.module = hub.Module(name="ernie")
        inputs, outputs, program = self.module.context(
            trainable=True, max_seq_len=max_seq_len)

        self.vocab_path = self.module.get_vocab_path()

        metrics_choices = ["acc"]

        # For ernie_tiny, it use sub-word to tokenize chinese sentence
        # If not ernie tiny, sp_model_path and word_dict_path should be set None
        reader = hub.reader.ClassifyReader(
            vocab_path=self.module.get_vocab_path(),
            max_seq_len=max_seq_len,
            sp_model_path=self.module.get_spm_path(),
            word_dict_path=self.module.get_word_dict_path())

        pooled_output = outputs["pooled_output"]

        # Setup feed list for data feeder
        # Must feed all the tensor of module need
        feed_list = [
            inputs["input_ids"].name,
            inputs["position_ids"].name,
            inputs["segment_ids"].name,
            inputs["input_mask"].name,
        ]

        # Setup runing config for PaddleHub Finetune API
        config = hub.RunConfig(
            use_data_parallel=False,
            use_cuda=use_gpu,
            batch_size=batch_size,
            checkpoint_dir=self.ckpt_dir,
            strategy=hub.AdamWeightDecayStrategy())

        # Define a classfication finetune task by PaddleHub's API
        self.cls_task = hub.TextClassifierTask(
            data_reader=reader,
            feature=pooled_output,
            feed_list=feed_list,
            num_classes=self.num_class,
            config=config,
            metrics_choices=metrics_choices)
    @serving
    def predict(self, data, return_result=True, accelerate_mode=False):
        """
        Get prediction results
        """
        run_states = self.cls_task.predict(
            data=data,
            return_result=return_result,  
            accelerate_mode=accelerate_mode)
        return run_states

if __name__ == "__main__":
    ernie_tiny = ERNIEFinetuned(
        ckpt_dir="modle.ckpt", num_class=5)
    # Data to be prdicted
    data = [["这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般"], ["交通方便；环境很好；服务态度很好 房间较小"],
            ["19天硬盘就罢工了~~~算上运来的一周都没用上15天~~~可就是不能换了~~~唉~~~~你说这算什么事呀~~~"]]
    predictions = ernie_tiny.predict(data=data)
    # for index, text in enumerate(data):
    print("predict= %s" % (predictions))
```

**Comment by kinghuin** [comment]
请将
```python
        run_states = self.cls_task.predict(
            data=data,
            return_result=return_result,  
            accelerate_mode=accelerate_mode)
```
中的return_result置为False
按照https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/docs/tutorial/finetuned_model_to_module.md#step-3_4-%E5%AE%8C%E5%96%84%E9%A2%84%E6%B5%8B%E9%80%BB%E8%BE%91
完成后处理和serving

**Comment by zhuyingjun-zyj** [comment]
为题一：
按照你说的建议进行了更改：但是又报错了：
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'list' object has no attribute 'argmax'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/project/test/textPaddle/finetuned_model_to_module/module.py", line 98, in <module>
    batch_result = np.argmax(batch_result, axis=2)[0]
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 1004, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 62, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 42, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (3,5) into shape (3)
你说的这种方式，在不进行模型转换的时候也会包同样的错误，不进行模型转换时，只有将

    run_states = self.cls_task.predict(
            data=data,
            return_result=return_result,  
            accelerate_mode=accelerate_mode)
中的 return_result 设置为Ture才会正常运行。所以在模型转换时也报了同样的错误，


问题2：
将return_result设置为False时,得到的预测返回值代表什么意思呢？
我知道设置为Ture时，返回的是预测标签的list。

**Comment by Steffy-zxf** [comment]
你好！
1. 调用`cls_task.predict`接口之后，你的后处理是怎么写的呢？

2. return_result=False，predict接口返回预测对应各类别的概率值。return_result=True会将后处理帮你搞定，也就是取预测概率值最大对应label作为最终类别。目前当你不定义dataset时，在预测接口predict设置return_result=True，会有错误。所以当你不定义dataset时，需要将return_result置为Fasle。之后需要用户自己写后处理代码。另外如果你想要使用hub serving预测部署的话，在转换module的代码

```python
@serving 
def predict(...)
    ...
```
**这个接口返回的结果应该是python的标准类型对象。**

**Comment by zhuyingjun-zyj** [comment]
我是按照上周你给的这个文档改的https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/docs/tutorial/finetuned_model_to_module.md#step-3_4-%E5%AE%8C%E5%96%84%E9%A2%84%E6%B5%8B%E9%80%BB%E8%BE%91
就报了一下错误：
[2020-06-15 13:57:21,428] [    INFO] - PaddleHub predict finished.
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'list' object has no attribute 'argmax'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/project/test/textPaddle/finetuned_model_to_module/module.py", line 101, in <module>
    predictions = ernie_tiny.predict(data=data)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddlehub\module\module.py", line 72, in _wrapper
    return func(*args, **kwargs)
  File "D:\project\test\textPaddle\finetuned_model_to_module\module.py", line 89, in predict
    batch_result = np.argmax(batch_result, axis=2)[0]
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 1004, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 62, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 42, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (3,5) into shape (3)


**二：  调用cls_task.predict接口的代码和之后的后处理如下：**
import os
from paddlehub.module.module import moduleinfo, serving
import paddlehub as hub
import numpy as np

@moduleinfo(
    name="my_ernie_finetuned",
    version="1.0.0",
    summary="ERNIE which was fine-tuned on the myset dataset.",
    author="zhuyingjun",
    author_email="zhuyingjunzyj@163.com",
    type="nlp/semantic_model")
class ERNIEFinetuned(hub.Module):
    def _initialize(self,
                    ckpt_dir="/modle.ckpt2",
                    num_class=5,
                    max_seq_len=128,
                    use_gpu=False,
                    batch_size=32):
        self.ckpt_dir = os.path.join(self.directory, ckpt_dir)
        self.num_class = num_class
        self.MAX_SEQ_LEN = max_seq_len

        # Load Paddlehub ERNIE Tiny pretrained model
        self.module = hub.Module(name="ernie")
        inputs, outputs, program = self.module.context(
            trainable=True, max_seq_len=max_seq_len)

        self.vocab_path = self.module.get_vocab_path()

        metrics_choices = ["acc"]

        # For ernie_tiny, it use sub-word to tokenize chinese sentence
        # If not ernie tiny, sp_model_path and word_dict_path should be set None
        reader = hub.reader.ClassifyReader(
            vocab_path=self.module.get_vocab_path(),
            max_seq_len=max_seq_len,
            sp_model_path=self.module.get_spm_path(),
            word_dict_path=self.module.get_word_dict_path())

        pooled_output = outputs["pooled_output"]

        # Setup feed list for data feeder
        # Must feed all the tensor of module need
        feed_list = [
            inputs["input_ids"].name,
            inputs["position_ids"].name,
            inputs["segment_ids"].name,
            inputs["input_mask"].name,
        ]

        # Setup runing config for PaddleHub Finetune API
        config = hub.RunConfig(
            use_data_parallel=False,
            use_cuda=use_gpu,
            batch_size=batch_size,
            checkpoint_dir=self.ckpt_dir,
            strategy=hub.AdamWeightDecayStrategy())

        # Define a classfication finetune task by PaddleHub's API
        self.cls_task = hub.TextClassifierTask(
            data_reader=reader,
            feature=pooled_output,
            feed_list=feed_list,
            num_classes=self.num_class,
            config=config,
            metrics_choices=metrics_choices)
    @serving
    def predict(self, data, return_result=False, accelerate_mode=False):
        """
        Get prediction results
        """
        run_states = self.cls_task.predict(
            data=data,
            return_result=return_result,  #我认为这个参数可以改一下，具体的值测试的时候再试
            accelerate_mode=accelerate_mode)
        results = [run_state.run_results for run_state in run_states]
        prediction = []
        for batch_result in results:
            # get predict index
            batch_result = np.argmax(batch_result, axis=2)[0]
            batch_result = batch_result.tolist()
            prediction += batch_result
        return prediction

if __name__ == "__main__":
    ernie_tiny = ERNIEFinetuned(
        ckpt_dir="modle.ckpt2", num_class=5)
    # Data to be prdicted
    data = [["这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般"], ["交通方便；环境很好；服务态度很好 房间较小"],
            ["19天硬盘就罢工了~~~算上运来的一周都没用上15天~~~可就是不能换了~~~唉~~~~你说这算什么事呀~~~"]]
    predictions = ernie_tiny.predict(data=data)
    for index, text in enumerate(data):
        print("%s\tpredict=%s" % (data[index][0], predictions[index]))

**Comment by Steffy-zxf** [comment]
predict接口代码改成下面试试：

```python

@serving
def predict(self, data, return_result=False, accelerate_mode=True):
    """
    Get prediction results
    """
    run_states = self.cls_task.predict(
        data=data,
        return_result=return_result,
        accelerate_mode=accelerate_mode)
    results = [run_state.run_results for run_state in run_states]
    prediction = []
    for batch_result in results:
        # get predict index
        batch_result = np.argmax(batch_result[0], axis=1)
        batch_result = batch_result.tolist()
        prediction += batch_result
    return prediction
```

**Comment by zhuyingjun-zyj** [comment]
已经改好，多谢

**Comment by D-DanielYang** [comment]
> 已经改好，多谢

请问下这个是仅个人学习，还是有一些具体的企业应用，是否可以沟通下，看能否更好的为您服务？
是否方便加个微信沟通下：282214037

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
