### ISSUE TITLE
可以将hub上面的OCR模型和口罩识别模型同时部署在摄像头上面吗？请问有demo吗

### ISSUE THREAD

**Issue by lzb-James** [PaddlePaddle/PaddleFormers#688]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

**Comment by Steffy-zxf** [comment]
你好！
> 可以将OCR模型和口罩识别模型同时部署在摄像头上面吗？

可以的。只需要将摄像头捕捉的视频，使用cv2转成视频帧，之后将这个视频帧分别传给ocr模型 和 口罩模型预测接口（以参数images传入），即可同时使用ocr模型 和 口罩模型预测。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
