### ISSUE TITLE
paddlehub没有办法离线运行

### ISSUE THREAD

**Issue by yangtianyu92** [PaddlePaddle/PaddleFormers#69]
训练机子不让上外网，我一个劲的docker save docker load 日的我不要不要的。已经折腾两周了，结果载入paddlehub还要求连外网。不连外网就用不了了吗？

**Comment by yangtianyu92** [comment]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='bj.bcebos.com', port=443): Max retries exceeded with url: /paddlehub-data/resource_list_file.yml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f720e7dbe10>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by yangtianyu92** [comment]
hello-word直接给劝退，一点意思没有。。。

**Comment by yangtianyu92** [comment]
PaddleHub/paddlehub/common/hub_server.py 
我把该文件__init__里面的self.requests()去掉。OK了。

**Comment by nepeplwu** [comment]
@yangtianyu92 ，抱歉造成不好的体验，这是因为PaddleHub中的预训练模型和预置数据集都需要通过服务端进行下载，因此我们默认用户得有外网权限

**Comment by yangtianyu92** [comment]
> @yangtianyu92 ，抱歉造成不好的体验，这是因为PaddleHub中的预训练模型和预置数据集都需要通过服务端进行下载，因此我们默认用户得有外网权限

然后我又跑去 docker pull hub.baidubce.com/paddlepaddle/paddle:1.5.0-gpu-cuda9.0-cudnn7 结果直接不能用多个GPU训练，说 Can not find library: libnccl.so. The process maybe hang. Please try to add the lib path to LD_LIBRARY_PATH.无奈

**Comment by nepeplwu** [comment]
@yangtianyu92 ，这个是因为Paddle的多卡并行依赖于libnccl.so，如果机器上有安装相应的库，可以按照指示添加到环境变量LD_LIBRARY_PATH中。如果未安装，请参考下面的链接进行安装：
http://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/beginners_guide/install/install_Ubuntu.html

**Comment by yangtianyu92** [comment]
在按照你说的操作安装过libnccl.so之后，多GPU运行还需要以下步骤。
首先翻墙下载
https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v7.3.0/prod/9.0_2018920/cudnn-9.0-linux-x64-v7.3.0.29
其次按照该网址指导添加个CUDNN7.3的库
https://blog.csdn.net/zhangpengzp/article/details/85008507
这个时候镜像就可以正常使用了。
真费劲，贵司还招实习的不？专业打包docker镜像出体力活那种。

**Comment by ZeyuChen** [comment]
@yangtianyu92 您好，镜像内应该有nccl的连接，您尝试下
 ln -s /usr/lib/x86_64-linux-gnu/libnccl.so.2 /usr/lib/x86_64-linux-gnu/libnccl.so 就可以修复这一问题。
新的镜像我们会重新打包，解决这个软连问题
cudnn镜像内应该都安装好的，感谢您的使用反馈
