### ISSUE TITLE
Fine-tune保存的模型如何转化为一个PaddleHub Module

### ISSUE THREAD

**Issue by Payne-Zhu** [PaddlePaddle/PaddleFormers#692]
有没有基于图片分类的例子
转化后的Module使用hub serving部署后参数如何转化？
怎么实现自带网页的调用，需要实现什么接口么？

**Comment by Steffy-zxf** [comment]
你好！
1. 图像分类任务Fine-tune保存的模型如何转化为一个PaddleHub Module 可以参考教程：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/docs/tutorial/finetuned_model_to_module.md
将教程中的创建文本分类TextClassifierTask换成创建图像分类ImageClassifierTask。如何创建ImageClassifierTask：参考图像分类demo： https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/demo/image_classification/img_classifier.py

2. 转化后的module 如何配合Hub Serving使用同样地参考上述教程，Hub serving使用部分。其中注意：
```python
@serving 
def predict(...)
    ...
```
这个接口返回的结果应该是python的标准类型对象。

3. 服务前端网页调用，需要用户自己实现。PaddleHub只支持后端服务部署。
