### ISSUE TITLE
我在百度大脑AI studio 运行了PaddleHub的实例三，目标检测，发现只有ssd可以正常运行，faster-rcnn和yolov3都提示没有发现模型。

### ISSUE THREAD

**Issue by yearddxx01** [PaddlePaddle/PaddleFormers#70]
示例三

使用目标检测模型 SSD/YOLO v3/Faster RCNN 对图片进行目标检测

$ wget --no-check-certificate https://paddlehub.bj.bcebos.com/resources/test_object_detection.jpg
$ hub run ssd_mobilenet_v1_pascal --input_path test_object_detection.jpg
$ hub run yolov3_coco2017 --input_path test_object_detection.jpg
$ hub run faster_rcnn_coco2017 --input_path test_object_detection.jpg

  
运行输出
运行耗时: 7秒751毫秒
Can't find module faster_rcnn_coco2017
Can't find module yolov3_coco2017
Module ssd_mobilenet_v1_pascal already installed in /home/aistudio/.paddlehub/modules/ssd_mobilenet_v1_pascal

**Comment by Steffy-zxf** [comment]
感谢反馈！百度大脑AI studio运行PaddleHub建议选择GPU环境。
