### ISSUE TITLE
使用口罩检测模型弹出提示警告

### ISSUE THREAD

**Issue by yousong1992** [PaddlePaddle/PaddleFormers#703]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

你好 ，我用的paddle-gpu1.8.2 paddlehub 1.7.1 win10 python3.6
再运行咱们口罩检测模型时，提示警告信息为:
2020-06-18 13:49:04,414-INFO: Instantiated empty configuration.
HDFS initialization failed, please check if .hdfscli，cfg exists.
但是 模型可以正常使用，我想问这个提示信息是因为我缺少了什么东西吗？

**Comment by ShenYuhan** [comment]
Maybe this issue could give you some help.
https://github.com/PaddlePaddle/VisualDL/issues/668

**Comment by yousong1992** [comment]
额 可能我没表述清楚我的问题，我笔记本的环境跟台式机的环境是一样的，都是上述的环境，但是笔记本就没有这条信息，台式机就有，我台式机是4快GPU，除了这点区别别的真没有什么区别。所以我很奇怪为什么笔记本不会报这个信息，而台式机就会。

**Comment by ShenYuhan** [comment]
因为VisualDL版本不同，您可以看下，报这个问题的VisualDL版本应该是b6

**Comment by ShenYuhan** [comment]
我们已经在新版本优化了此问题，需要升级visualdl：
```shell
pip install visualdl==2.0.0b7 -U
```
可参考这个issue
PaddlePaddle/VisualDL#668

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
