### ISSUE TITLE
deeplabv3p_xception65_humanseg的segmentation方法返回值不正确

### ISSUE THREAD

**Issue by bobyanglin** [PaddlePaddle/PaddleFormers#704]
1）PaddleHub和PaddlePaddle版本：PaddleHub1.7.1，PaddlePaddle1.8.1，deeplabv3p_xception65_humanseg1.1.0

2）系统环境：Windows10 64位，python3.6.5
- 复现信息：
按照文档，segmentation（）方法的返回值包含分割结果，其中data应该是Alpha通道数据，取值为0-255 (0为全透明，255为不透明)，但是实际返回的数据里面有负数，类型是float32

**Comment by bobyanglin** [comment]
把PaddlePaddle升级到1.8.2也是同样的错误
img = cv2.imread('xxxxx.jpg')
results = humanseg.segmentation(images = [img])
print(results)

**Comment by bobyanglin** [comment]
![aaa](https://user-images.githubusercontent.com/67145610/85118704-42256c80-b253-11ea-92c9-92ba9f20ec9a.png)

**Comment by Steffy-zxf** [comment]
@bobyanglin 你好！感谢反馈！以上问题已解决，可以通过安装deeplabv3p_xception65_humanseg 最新版本1.1.1，
```shell
$ hub install deeplabv3p_xception65_humanseg==1.1.1
```
