### ISSUE TITLE
hub.Module(name=“ernie”) 时报错

### ISSUE THREAD

**Issue by bill0507** [PaddlePaddle/PaddleFormers#705]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.7.0，PaddlePaddle1.8.2.post97
2）系统环境：Aistudio
import paddlehub as hub
module = hub.Module(name=“ernie”)

2020-06-19 17:46:24,960-INFO: Instantiated empty configuration.
HDFS initialization failed, please check if .hdfscli，cfg exists.（第一处错误）
Downloading ernie
[==================================================] 100.00%
Uncompress /home/aistudio/.paddlehub/tmp/tmpigvf1p5d/ernie
[==================================================] 100.00%
Successfully installed ernie-1.2.0
[2020-06-19 17:46:50,215] [ INFO] - Installing ernie module
[2020-06-19 17:46:50,217] [ INFO] - Module ernie already installed in /home/aistudio/.paddlehub/modules/ernie
---------------------------------------------------------------------------TypeError Traceback (most recent call last) in 
2 import paddlehub as hub
3 get_ipython().system(‘hub install ernie’)
----> 4 module = hub.Module(name=“ernie”)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in new(cls, name, directory, module_dir, version, **kwargs)
100 if name:
101 module = cls.init_with_name(
–> 102 name=name, version=version, **kwargs)
103 elif directory:
104 module = cls.init_with_directory(directory=directory, **kwargs)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in init_with_name(cls, name, version, **kwargs)
137
–> 138 super(Module, self).init()
139 _run_func_name = self._get_func_name(self.class,
140 _module_runnable_func)
TypeError: init() missing 1 required positional argument: ‘name_scope’（第二处错误）

我完整运行了作者的代码 为什么会出现这种错误啊

**Comment by Steffy-zxf** [comment]
你好！运行环境中的paddle 版本是多少呢? 请按照如下代码，查看paddle版本
```python
import paddle
paddle.__version
```

出现上述错误，应该是你运行环境paddle不是1.8.0以上版本导致的。请将paddle升级至最新版本。

**Comment by bill0507** [comment]
你好，原贴中的代码fork之后直接运行后的代码，进入的环境是1.7.1的版本 需要自己创建版本1.8.0的环境重新输入代码 问题可以解决，谢谢

**Comment by bill0507** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/294224 原贴

**Comment by ShenYuhan** [comment]
第一处错误需要升级visualdl：可参考这个issue
https://github.com/PaddlePaddle/VisualDL/issues/668
