### ISSUE TITLE
有关于paddlehub的autodl方面的问题

### ISSUE THREAD

**Issue by LilyCaiZL** [PaddlePaddle/PaddleFormers#708]
你好，有关超参数自动调节的问题，因为我正在研究这个，开库看了之后，发现hazero用的明明是cmaes，但是在官网的配图是高斯分布贝叶斯优化算法，然后在pshe2里面的配图是cmaes的图，请问这个文档是否有误，还是我的理解有问题，图并没有问题，我非常着急，望解答谢谢！
![image](https://user-images.githubusercontent.com/40067956/85215266-adcd1e00-b3a8-11ea-9ffe-9a9e089c3459.png)
![image](https://user-images.githubusercontent.com/40067956/85215267-b160a500-b3a8-11ea-9a8e-1d4866c5c2ec.png)

**Comment by Steffy-zxf** [comment]
你好！如线下沟通，cma是第三方库，本质上是贝叶斯优化算法。pshe2的配图没有问题。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
