### ISSUE TITLE
使用paddle出现Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by linzhk** [PaddlePaddle/PaddleFormers#709]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

paddle ：1.8.2
系统版本：linux，python3.7

代码尝试：
results = lac.lexical_analysis(texts=_batch, use_gpu=True, batch_size=32, return_tag=True)
其中：
_batch = 一个列表的迭代器，使用for循环不断产生_batch
有没有可能是文本太长的关系？
一个_batch的长度是32，每个项的字符串长度长达21w
报错信息：
2020-06-21 14:11:39,398-INFO: Instantiated empty configuration.
HDFS initialization failed, please check if .hdfscli，cfg exists.
[2020-06-21 14:11:39,766] [    INFO] - Installing lac module
[2020-06-21 14:11:39,926] [    INFO] - Module lac already installed in /home/lzk/.paddlehub/modules/lac
Segmentation fault (core dumped)

**Comment by Steffy-zxf** [comment]
你好！
> 一个_batch的长度是32，每个项的字符串长度长达21w

是的，你的输入文本数据过长。请试试将每项字符串，按句输入。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
