### ISSUE TITLE
PaddleHub的使用指南

### ISSUE THREAD

**Issue by InstantWindy** [PaddlePaddle/PaddleFormers#71]
请问下有没有关于paddlehub的使用指南呢？比如module里都有哪些预训练模型和预训练模型的名字，不知道名字无法加载预训练模型。怎么加载自己的数据集？

**Comment by Steffy-zxf** [comment]
感谢反馈！PaddleHub支持命令行工具和迁移学习。PaddleHub的功能介绍可以参考我们的wiki https://github.com/PaddlePaddle/PaddleHub/wiki，
命令行工具
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7，
迁移学习demo
文本分类 
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E6%96%87%E6%9C%AC%E5%88%86%E7%B1%BB%E8%BF%81%E7%A7%BB%E6%95%99%E7%A8%8B
图像分类 
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E5%9B%BE%E5%83%8F%E5%88%86%E7%B1%BB%E8%BF%81%E7%A7%BB%E6%95%99%E7%A8%8B。

tips：
1.安装完PaddleHub后，可以通过 hub search，搜索到PaddleHub支持的所有预训练模型，这些预训练模型在我们的PaddleHub官网上有相应的介绍
https://www.paddlepaddle.org.cn/hub。
2.PaddleHub迁移学习demo不仅限于文本分类、图像分类，还支持序列标注、多标签分类等，具体demo详情可以参考有关demo的介绍
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.0.0/demo

PaddleHub加载自定义数据集，可以参考我们的wiki 
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E9%80%82%E9%85%8D%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E5%AE%8C%E6%88%90FineTune

利用PaddleHub完成自定义任务迁移，可以参考我们的wiki 
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub:-%E8%87%AA%E5%AE%9A%E4%B9%89Task

**Comment by gateslee1984** [comment]
加载自定义数据集只列出了文本分类的，有‘图像’类别的自定数据集加载的wiki吗？
