### ISSUE TITLE
希望提供一下利用PaddleHub Serving进行个性化开发demo的代码

### ISSUE THREAD

**Issue by zhuyingjun-zyj** [PaddlePaddle/PaddleFormers#710]
**Step3：利用PaddleHub Serving进行个性化开发**
使用PaddleHub Serving进行模型服务部署后，可以利用得到的接口进行开发，如对外提供web服务，或接入到应用程序中，以降低客户端预测压力，提高性能，下面展示了一个web页面demo:
具体见链接：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/docs/tutorial/serving.md，中的Step-3
需求：
（1）希望提供一下这个demo的代码，我想知道模型是如何处理web端传来的参数如：如何处理选择分类的参数、如何处理选择模型的参数，如何接受上传的图片（或nlp任务的样本）等等。

（2）还希望增加一个nlp方向的类似这样的demo

**Comment by ShenYuhan** [comment]
您好，您可以参考下最新的文档https://github.com/PaddlePaddle/PaddleHub/blob/develop/docs/tutorial/serving.md
（1）step-3展示的是一个web demo，前端代码在这里[serving 前端demo](https://github.com/PaddlePaddle/PaddleHub/blob/develop/paddlehub/serving/templates/main.html)，这个demo并不是一个对外展示的demo，仅仅供开发人员测试，所以不能保证可用
（2）nlp的demo[以lac为例]同样在上述文档链接中。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Comment by pinkman199810** [comment]
@ShenYuhan dear, could y4ou upload the Front-End code again, i cant find it,thanks in advance
