### ISSUE TITLE
需要提供一下在线部署PaddleHub服务时，通过WSGI方式部署的demo或者文档

### ISSUE THREAD

**Issue by bobyanglin** [PaddlePaddle/PaddleFormers#712]
在部署在线PaddleHub服务时，直接执行 hub serving start -m  XXXXXX，系统提示Flask app用于开发环境，生产系统请用WSGI替代，需要提供一下通过WSGI方式部署PaddleHub服务的demo或者文档。

谢谢

![20200622171920](https://user-images.githubusercontent.com/67145610/85271055-d50d1380-b4ac-11ea-8f61-ddb08ef69565.png)

**Comment by D-DanielYang** [comment]
微信群已回复，同步给更多同学了解
这个问题 启动的时候 加上 --use_multiprocess 就可以使用gunicorn作为wsgi框架包裹flask 不会有此提示，事实上 这个提示一般也没有什么关系的～仅仅是来自flask官方的一个小提示哈

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
