### ISSUE TITLE
使用Paddle hub fine-tune Ernie时如何获取训练时的log信息

### ISSUE THREAD

**Issue by zhuyingjun-zyj** [PaddlePaddle/PaddleFormers#717]
问题：在fine-tune时如何获取log信息如：

[2020-06-23 18:33:20,547] [   TRAIN] - step 21 / 1752: loss=1.57232 acc=0.28125 [step/sec: 0.02]
[2020-06-23 18:35:38,595] [   TRAIN] - step 24 / 1752: loss=1.61973 acc=0.19792 [step/sec: 0.02]
以上这些参数（step，loss，acc等）信息由ernie内部封装好的，但在fine-tune时如何获取？

**Comment by Steffy-zxf** [comment]
你好！以上日志是你使用PaddleHub 迁移学习Finetune API时打印出来的。你可以将log 输出重定向输出到文件当中。具体如何操作可以百度一下，重定向输出。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
