### ISSUE TITLE
 hub serving 服务异常出错退出

### ISSUE THREAD

**Issue by bobyanglin** [PaddlePaddle/PaddleFormers#718]
1）PaddleHub和PaddlePaddle版本：PaddleHub1.7.1，PaddlePaddle1.8.2，deeplabv3p_xception65_humanseg模型版本：1.1.1
2）系统环境：Centos7，python3.6.8
- 复现信息：部署在线服务后，反复调用，hub服务异常退出，具体操作如下：

启动服务：hub serving start --config cpuconfig.json
能够看到系统进程：
![ps_info](https://user-images.githubusercontent.com/67145610/85498568-8ed1c480-b612-11ea-9780-a9c77fc127f9.png)

反复调用接口，向 http://127.0.0.1:8866/predict/deeplabv3p_xception65_humanseg 提交图片，有时候成功，有时候出错，出错返回信息：
{"msg": "Please check data format!", "results": "", "status": "-1"}

出错后使用相同的图片又正常返回了，在多次失败后hub服务异常退出，错误信息：
[nohup.txt](https://github.com/PaddlePaddle/PaddleHub/files/4823138/nohup.txt)

启动服务时的配置文件：
[cpuconfig.json.txt](https://github.com/PaddlePaddle/PaddleHub/files/4823144/cpuconfig.json.txt)

**Comment by ShenYuhan** [comment]
您试一下如果不使用 --use_multiprocess 是否依然报错

**Comment by bobyanglin** [comment]
> 您试一下如果不使用 --use_multiprocess 是否依然报错

不使用 --use_multiprocess参数，hub serving 服务倒是不出错了，不过客户端如果同时请求，就会出错了，我用多线程模拟客户端的同时请求就出错了。

那么在生产环境下，应该如何部署呢？

**Comment by ShenYuhan** [comment]
您使用--use_multiprocess进行预测的时候，实时查看下内存，是否是内存不够了造成的
不使用--use_multiprocess确实不能支持过多的同时请求

**Comment by bobyanglin** [comment]
> 您使用--use_multiprocess进行预测的时候，实时查看下内存，是否是内存不够了造成的
> 不使用--use_multiprocess确实不能支持过多的同时请求

用  free -m  命令看了，在预测的时候32G内存的确基本上用完了，在使用--use_multiprocess的时候，用ps命令查看，hub serving一共有18个进程，应该是和服务器的CPU内核数有关吧，大概需要多大内存才能支撑呢？在部署服务的时候能设置使用的最大内存吗？

**Comment by ShenYuhan** [comment]
目前可以通过设置worker数来管理启动的线程，可以通过测试来确定比较适合的worker数，需要的内存和具体的模型有关，不是固定的。
具体设置方法是在config文件中设置
```json
workers: 3
```

**Comment by bobyanglin** [comment]
> 目前可以通过设置worker数来管理启动的线程，可以通过测试来确定比较适合的worker数，需要的内存和具体的模型有关，不是固定的。
> 具体设置方法是在config文件中设置
> 
> ```json
> workers: 3
> ```

我的config文件中加载了两个模型，我试了分别设置workers: 3或者设置总的workers: 6都有问题，应该放在哪里合适呢？

`{
  "modules_info": {
    "face_landmark_localization": {
      "init_args": {
        "version": "1.0.2"
      },
      "predict_args": {
        "batch_size": 1,
        "use_gpu": false
      }
    },
    "deeplabv3p_xception65_humanseg": {
      "init_args": {
        "version": "1.1.1"
      },
      "predict_args": {
        "batch_size": 1,
        "use_gpu": false
      }
    }
  },
  "port": 8866,
  "use_multiprocess": true
}
`

**Comment by ShenYuhan** [comment]
可以参考这个文件
https://github.com/PaddlePaddle/PaddleHub/blob/develop/paddlehub/serving/templates/serving_config.json

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
