### ISSUE TITLE
使用PaddleHub提供的ERNIE进行序列标注如何在AIstudio正确进行在线部署

### ISSUE THREAD

**Issue by TWwWT1** [PaddlePaddle/PaddleFormers#721]
![image](https://user-images.githubusercontent.com/52694143/85938988-80eaaf00-b944-11ea-865a-f8ca1fb1037c.png)
这块应该如何书写，看很多Issue都没有解决

**Comment by songdi3** [comment]
https://ai.baidu.com/ai-doc/AISTUDIO/bk3e382cq
您可以参考下以上链接进行相关部署，如在设置参数时出现不能理解的报错，可以将您的问题阐述以及截图发送邮件至AI Studio（aistudio@baidu.com）进行询问。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
