### ISSUE TITLE
paddlehub human_pose_estimation_resnet50_mpii模型关键点识别不准确

### ISSUE THREAD

**Issue by iotctech** [PaddlePaddle/PaddleFormers#723]
- 版本信息
PaddlePaddle 1.8.2 
PaddleHub 1.7.1

- 系统环境
ubuntu 18.04

- 问题描述

```
    frame = cv2.imread("/home/beta/datasets/coco/coco/images/train2017/000000001146.jpg")
    results = module.keypoint_detection(images=[frame])
    data = results[0]['data']
    print(data)

    for k in data.keys() :
        cv2.circle(frame, tuple(data[k]), 1, (0,0,255), 4)
        print(k, data[k])

    # show video
    cv2.imshow("cheating_detection", frame)
``` 
使用coco的数据集和其他图片测试多次，描点位置不正确，这是什么原因呢？

**Comment by nepeplwu** [comment]
@iotctech 该module对于这种非全身人像的预测效果会不太准确。如果你想试验效果的话，建议找一个包含全身的人像图片

**Comment by iotctech** [comment]
> @iotctech 该module对于这种非全身人像的预测效果会不太准确。如果你想试验效果的话，建议找一个包含全身的人像图片

全身的照片稍微准确一点，但还是无法达到应用场景，并且这个模型不支持多人的识别，有优化计划吗？

**Comment by nepeplwu** [comment]
@iotctech 你们目前的应用场景是什么呢？

**Comment by iotctech** [comment]
@nepeplwu 教室或办公室环境内，学生的人体关键点，人员密度相对比较大，并且会有遮挡，我测试百度以API方式提供的人体关键点检测，效果还是挺不错的，不过开源的版本基本没效果。

**Comment by nepeplwu** [comment]
@iotctech 预计会在Q3进行优化
