### ISSUE TITLE
想问问时间序列进行设备损坏的提前预警怎么处理

### ISSUE THREAD

**Issue by mmmahhhhe** [PaddlePaddle/PaddleFormers#724]
你好，请问一下我想问个时间序列的问题，有多台设备的m个连续属性值，每台设备在开始使用的时刻是正常的，然后渐渐的会损坏，也就是m个属性值变化，然后突然就没有接下来的数据了，或者说接下来的数据已经没有意义了，同时会给一个标签，说明损坏的原因（可以是损坏与否的二分类或者具体属于哪种的多分类），如果想对于未来一台设备，每天会有新产生的数据，来提前s天预测s天后会不会损坏或者损坏的原因，这个怎么做呀，不同设备损坏时间不一样，但是一定会在比如说一年内损坏

**Comment by Steffy-zxf** [comment]
你好！PaddleHub不支持时间序列任务，可以参考models repo是否有相关任务：https://github.com/PaddlePaddle/models

**Comment by mmmahhhhe** [comment]
那在哪问比较好呢
