### ISSUE TITLE
deeplabv3p_xception65_humanseg预测时丢失图片语义细节

### ISSUE THREAD

**Issue by andy-zhangtao** [PaddlePaddle/PaddleFormers#726]
感谢PaddleHub提供deeplabv3p_xception65_humanseg模型, 我再使用时发现deeplabv3p_xception65_humanseg模型对一些人物手持物品类图片进行预测时会丢失手持物品。

- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub 1.7.1 PaddlePaddle 1.8.2
2）系统环境：Linux Ubuntu ，python 3.7
原图:
![175314](https://user-images.githubusercontent.com/8232737/86190194-57b16500-bb76-11ea-8178-e7f7afa0c5a4.png)

预测结果:
![175314](https://user-images.githubusercontent.com/8232737/86190317-9fd08780-bb76-11ea-81e0-12de8fb089d3.png)

我想确认:

1. 是否是我使用错误导致，如果是，请告之可能的原因。 
2. 是否是原数据集没有包括手持物品类图片导致。 如果是的话，我是否可以使用自有数据集进行训练

**Comment by Steffy-zxf** [comment]
你好！
1. 由于PaddleHub 提供的deeplabv3p_xception65_humanseg module是分割人像，而手持物体不属于人体，所以预测结果中没有预测出手持物品。
2. 你可以在相关自有数据集上进行重新Fine-tune，从而满足需求。关于图像分割Finetune 可以参考：
PaddleX 分割demo：https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/human_segmentation
教程：https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/segmentation/deeplabv3p.py

**Comment by andy-zhangtao** [comment]
好的。 明白了。 多谢

**Comment by juzuo** [comment]
> 
> 
> 你好！
> 
>     1. 由于PaddleHub 提供的deeplabv3p_xception65_humanseg module是分割人像，而手持物体不属于人体，所以预测结果中没有预测出手持物品。
> 
>     2. 你可以在相关自有数据集上进行重新Fine-tune，从而满足需求。关于图像分割Finetune 可以参考：
>        PaddleX 分割demo：https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/human_segmentation
>        教程：https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/segmentation/deeplabv3p.py

@Steffy-zxf 你好，请问能否基于安装在~/.paddlehub/modules/的deeplabv3p_xception65_humanseg模型来做fine-tune而不是通过checkpoint文件？我是通过hub install deeplabv3p_xception65_humanseg==1.1.1安装的模型。因为我发现通过这个命令安装的模型对我的数据效果比较好，但我仍然想fine-tune它。
我尝试了这个[https://aistudio.baidu.com/aistudio/projectdetail/475345](https://aistudio.baidu.com/aistudio/projectdetail/475345)，这里的humanseg_server_ckpt对应的推理模型对我的数据效果不太好，所以我想直接基于效果好的安装模型deeplabv3p_xception65_humanseg做fine-tune。可以搞吗？
paddle新手，轻拍啊。多谢了。
