### ISSUE TITLE
请问有能部署在Windows 32位系统上的解决办法吗

### ISSUE THREAD

**Issue by JserWF** [PaddlePaddle/PaddleFormers#729]
希望能把训练好的模型部署在较低版本的windows环境上

**Comment by ShenYuhan** [comment]
请问您的具体需求是什么呢？我们有在windows上部署hub模型的方案

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
