### ISSUE TITLE
squad数据集的模型怎么构造？

### ISSUE THREAD

**Issue by miaohaa** [PaddlePaddle/PaddleFormers#73]
squad数据集的模型怎么构造？ernie的sequence_out输出后，我接了两层全连接，最后输出shape为[-1,2], 和label[23,28]计算cross_entropy，然后使用finetue_and_evl函数（“sequence_labeling”）训练，怎么报错？ Invoke operator mul error.

**Comment by miaohaa** [comment]
可以出一个阅读理解的demo吗？

**Comment by miaohaa** [comment]
ernie输入的max_seq_len必须是512吗？

**Comment by miaohaa** [comment]
出错是这个原因吗？

**Comment by Steffy-zxf** [comment]
感谢反馈！目前PaddleHub还未支持阅读理解任务迁移学习，需要用户自定义阅读理解的Task、SQuAD数据集的加载和Reader。另外，由于PaddleHub开放的Module ERNIE预训练数据集为中文数据集，故利用ERNIE Module不能完成SQuAD数据集的阅读理解任务。不过您可以尝试PaddleHub  Module bert_uncased_L-12_H-768_A-12，支持该任务。ERNIE的max_seq_len不是必须512，可以根据您的显存大小选择合适的max_seq_len。另外PaddleHub会尽快release SQuAD数据集的阅读理解任务demo。

**Comment by miaohaa** [comment]
那中文数据集的阅读理解任务的迁移学习，是否会出吗？

**Comment by Steffy-zxf** [comment]
基于SQuAD数据集的阅读理解任务demo在测试分支add-reading-comprehension-task，
欢迎试用。
https://github.com/PaddlePaddle/PaddleHub/tree/add-reading-comprehension-task/demo

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
