### ISSUE TITLE
export CUDA_VISIBLE_DEVICES="0" && hub serving start pyramidbox_face_detection --use_gpu 调用gpu失败

### ISSUE THREAD

**Issue by NextGuido** [PaddlePaddle/PaddleFormers#730]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

如题，ubuntu系统下使用命令`export CUDA_VISIBLE_DEVICES="0" && hub serving start pyramidbox_face_detection --use_gpu`启动服务，请求的时候gpu完全没有使用。但是如果启用ocr服务的话`export CUDA_VISIBLE_DEVICES="0" && hub serving start chinese_ocr_db_crnn_server --use_gpu`，gpu可以正常使用。
另外，我尝试了在代码中使用gpu，既`face_detector.face_detection(images=[cv2.imread('/PATH/TO/IMAGE')], use_gpu=True)`，这样也是可以正常调用gpu的

我的环境：
ubuntu16.04
python 3.7.3
paddlehub 1.7.1
paddlepaddle-gpu 1.8.1.post107

**Comment by ShenYuhan** [comment]
您好，现在是否使用gpu是作为请求参数在http请求中携带的，所以如果要使用gpu，需要请求时指定。

**Comment by NextGuido** [comment]
@ShenYuhan 是这样吗？`data = {'images': [cv2_to_base64(img)], 'use_gpu': True}`

**Comment by NextGuido** [comment]
@ShenYuhan 可以了，感谢。
