### ISSUE TITLE
paddlehub口罩检测模型使用报错 

### ISSUE THREAD

**Issue by yousong1992** [PaddlePaddle/PaddleFormers#737]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
paddlehub1.7.1 paddlepaddle-gpu 1.8.2
linux18.04  2080显卡4块，然后cuda cudnn nccl已经正确安装，在跑paddlepaddle-gpu的测试代码时，提示信息如下：
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0706 20:39:04.760099  5235 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W0706 20:39:04.841992  5235 device_context.cc:260] device: 0, cuDNN Version: 7.6.
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0706 20:39:15.426373  5235 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
可是在运行口罩检测模型时，设置环境变量如下：
os.environ['CUDA_VISIBLE_DEVICES'] = '0'或者os.environ['CUDA_VISIBLE_DEVICES'] = '0，1，2，3'
运行均会报错：

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:183)
求帮助！

**Comment by Steffy-zxf** [comment]
你好！你的代码是怎么写的呢？试试在运行预测脚本之前设置CUDA_VISIBLE_DEVICES环境变量，如果是Linux平台，可以用`export CUDA_VISIBLE_DEVICES=0`命令设置。

**Comment by yousong1992** [comment]
@Steffy-zxf  您好 我已经查明原因了，是因为我用了多进程，需要使用set_start_method('spawn',True)方式开启进程即可。
