### ISSUE TITLE
安装完hub后使用hub命令提示不是内部命令。

### ISSUE THREAD

**Issue by upenggod** [PaddlePaddle/PaddleFormers#739]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
1。PaddleHub1.7.1，PaddlePaddle1.8
2.系统环境：Windows，anaconda，python版本3.6.9

问题1：安装完hub后使用hub命令提示不是内部命令。
问题2：PaddleHub抠图比赛教程中，results = module.segmentation(images=test_img)，没有看到抠图的结果在哪？

**Comment by Steffy-zxf** [comment]
你好！
1. 确认下paddlehub 是否安装在当前运行环境当中。
2. 保存预测结果图片，可以将预测接口 `module.segmentation(images=test_img, visualization=True)`，此时即可将图片保存在当前运行目录下。
