### ISSUE TITLE
请问我在ernie的框架下面使用roberta的权重，应该要怎么操作？

### ISSUE THREAD

**Issue by Maybewuss** [PaddlePaddle/PaddleFormers#747]
因为要复现一个模型，需要用到roberta_large的权重

**Comment by Steffy-zxf** [comment]
你好！你指的 ERNIE框架什么意思？ 是ernie 模型代码吗？还是 ERNIE repo， https://github.com/PaddlePaddle/ERNIE ？

**Comment by Maybewuss** [comment]
> 你好！你指的 ERNIE框架什么意思？ 是ernie 模型代码吗？还是 ERNIE repo， https://github.com/PaddlePaddle/ERNIE ？

是框架，应该已经如流上请教过同学了hh～

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
