### ISSUE TITLE
valueerror: the length of ret_tokens can't match with labels

### ISSUE THREAD

**Issue by miaohaa** [PaddlePaddle/PaddleFormers#75]
训练序列标注任务，自己构建的数据集合，和msra_ner一样格式，怎么会出现这句错误valueerror: the length of ret_tokens can't match with labels。ret_tokens是什么意思？可我确定 label的长度和text_a的长度相同了啊。

**Comment by Steffy-zxf** [comment]
ret_tokens 是指文本经过tokenize处理后的文本。ernie应用于中文序列标注任务时，是针对每一个字进行处理，所以label应该也是对应于每个字的，label的长度需要和文本的字数保持一致。

**Comment by ZeyuChen** [comment]
已和用户确定问题已解决。
