### ISSUE TITLE
控制台cmd.exe无法识别padddlehub的hub命令，怎么才能部署啊

### ISSUE THREAD

**Issue by zm960204** [PaddlePaddle/PaddleFormers#752]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

**Comment by Steffy-zxf** [comment]
你好！`控制台cmd.exe无法识别padddlehub的hub命令`一般是环境设置问题，请检查paddlehub安装是否在当前运行环境中。

部署相关问题可以参考PaddleHub Serving使用说明：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/docs/tutorial/serving.md

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
