### ISSUE TITLE
can't load module with: hub.Module(name="XXX")

### ISSUE THREAD

**Issue by lexmen318** [PaddlePaddle/PaddleFormers#76]
in manager.py: name = search_result.get('name', None)

but the search_result does not return the "name" at all, 'cos in the hub_server.py:

                return {
                    'url': self.resource_list_file['url'][index],
                    'md5': self.resource_list_file['md5'][index],
                    'version': version
                }

**Comment by Steffy-zxf** [comment]
Thanks for feedback! Which module do you wanna load and which version is PaddleHub used?

**Comment by lexmen318** [comment]
ERNIE
1.0.1

**Comment by Steffy-zxf** [comment]
BTW， I wanna find out that

1. How do you load ERNIE Module?
The exact way is as following:

import paddlehub as hub

module = hub.Module(name="ernie")

2. Can the computer that you run the ernie module connet the extranet，e.g. www.baidu.com ?

**Comment by lexmen318** [comment]
Yes, I just loaded the module exactly like the way you provide.

My server can connect the extranet.

Actually, I've solved the problem by just modifying the file of manager.py as following:

**name = module_name
#name = search_result.get('name', None)**

So I inferred that the code may have something wrong.

**Comment by Steffy-zxf** [comment]
1. Please try this, I wonder whether that computer works out?
```python
import requests

res = requests.get('http://paddlepaddle.org.cn/paddlehub/search', {'word': 'ernie', 'type': 'Module'})
print(res)

# the common result is like this:
# <Response [200]>
```
2. Yes, We found the the code has some bug and we are fixing it.

**Comment by lexmen318** [comment]
明白了，确实因为我们公司对外网的限制导致以上的requests.get不成功，进而走到了代码中的下面的“异常流程”，然后异常流程里面也确实漏返回了'name'字段，因此导致了最后的错误信息。

不过还好在稍作修改让程序往下走之后，后面对模块文件的下载成功了。
