### ISSUE TITLE
服务器部署成功无法POST

### ISSUE THREAD

**Issue by TWwWT1** [PaddlePaddle/PaddleFormers#760]
服务器端 ：
Ubuntu 16.04.1 
paddlepaddle == 1.8.3
paddlehub == 1.7.1 
python == 3.6

客户端 ：
windows10
python == 3.6
我用paddlehub 在服务器上的成功部署了 senta_gru 模型（port 设为服务器登陆端口）

![image](https://user-images.githubusercontent.com/52694143/87846753-ce838780-c904-11ea-9daf-f1341eab7653.png)

但本地端设为无法在POST的时候

![image](https://user-images.githubusercontent.com/52694143/87846774-f4a92780-c904-11ea-9df0-e4f22b7b5170.png)

更换默认端口 8866

![image](https://user-images.githubusercontent.com/52694143/87847156-57e88900-c908-11ea-8935-20f9a0b200cf.png)

客户端代码

import requests
import json

text = ["这家餐厅很好吃", "这部电影真的很差劲"]

# 设置运行配置
# 对应本地预测senta_gru.sentiment_classify(texts=text, batch_size=1, use_gpu=True)
data = {"texts": text, "batch_size": 1, "use_gpu":False}

# 指定预测方法为senta_gru并发送post请求，content-type类型应指定json方式
# HOST_IP为服务器IP
url = "http://bob.geeekvr.com:8866/predict/senta_gru"
headers = {"Content-Type": "application/json"} 
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(json.dumps(r.json(), indent=4, ensure_ascii=False))

**Comment by TWwWT1** [comment]
再次更换 prot 为 8860 后
ConnectionError: HTTPConnectionPool(host='bob.geeekvr.com', port=8860): Max retries exceeded with url: /predict/senta_gru (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D715BBD978>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

**Comment by ShenYuhan** [comment]
您确认下您填写 bob.geekvr.com的这个url是否能够正常访问，以及端口是否对外开放，您可以试下在同一台机器上部署和请求，如果可行，大概率是网络问题

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
