### ISSUE TITLE
无法从服务端正确获取返回json

### ISSUE THREAD

**Issue by Darkside-king** [PaddlePaddle/PaddleFormers#761]
服务器端：
CentOS 8.1.1911
python ==3.6.8
paddleHub ==1.7.1
paddlepaddle ==1.8.3

客户端：
Windows10
python==3.7.6

我用paddlehub 在服务器上的成功部署了pyramidbox_lite_server_mask 口罩识别模型
![1](https://user-images.githubusercontent.com/32789489/87899134-d0735500-ca82-11ea-8391-f65877dcb786.png)
在客户端尝试获取json的时候
![2](https://user-images.githubusercontent.com/32789489/87899216-129c9680-ca83-11ea-9abd-08989d2c23f7.png)
更改访问方式后（增加了headers）
![3](https://user-images.githubusercontent.com/32789489/87899260-3bbd2700-ca83-11ea-805f-555a8f2a858a.png)
仍然无法正常获取返回数据。
这是上级目录，代码目录为MaskDetect
![4](https://user-images.githubusercontent.com/32789489/87899369-8ccd1b00-ca83-11ea-9b39-a7e8d04b9fdc.png)
![5](https://user-images.githubusercontent.com/32789489/87899376-9191cf00-ca83-11ea-90fe-66b15c248c1b.png)
尝试访问后服务器的显示
![6](https://user-images.githubusercontent.com/32789489/87899415-b25a2480-ca83-11ea-83eb-fac67548be05.png)

**Comment by ShenYuhan** [comment]
把url中的image去掉试试
参考下面的demo
```python
import requests
import json
import cv2
import base64

def cv2_to_base64(image):
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')

# 发送HTTP请求
data = {'images':[cv2_to_base64(cv2.imread("/PATH/TO/IMAGE"))]}
headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:8866/predict/pyramidbox_lite_server_mask"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

# 打印预测结果
print(r.json()["results"])
```
参考https://paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_server_mask&en_category=FaceDetection

**Comment by Darkside-king** [comment]
ok,按照这个能够正常显示了。
