### ISSUE TITLE
paddlehub serving 如何部署后台服务

### ISSUE THREAD

**Issue by zhuyingjun-zyj** [PaddlePaddle/PaddleFormers#765]
使用paddlehub serving 部署后，关闭连接，服务就停止了，如何部署后台服务？

**Comment by ShenYuhan** [comment]
您可以使用`nohup`方式挂载后台运行，这样关闭服务连接仍可以保持运行。

**Comment by BobDu** [comment]
@ShenYuhan  那请问提供的 hub server stop 命令是什么时候才能用到的呢？

**Comment by ShenYuhan** [comment]
在您想优雅的关闭hub-serving，而不是用kill的方式关闭的时候。

**Comment by BobDu** [comment]
@ShenYuhan  不好意思  还是没弄明白这个逻辑  
hub start 本身就不支持后台运行服务  关闭的时候不就是 `control+C` 的吗？  为什么需要stop命令
能提供个案例吗？

**Comment by ShenYuhan** [comment]
就像上面的回答，使用`nohup`方式启动的hub serving，这个时候用stop命令比查找进程、杀死进程要简单。
主要是这种场景，其他场景下使用ctrl+c和stop命令，目前没有太大差别。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
