### ISSUE TITLE
图像分类的预训练模型不支持传入top参数

### ISSUE THREAD

**Issue by zhangmianhongni** [PaddlePaddle/PaddleFormers#766]
![QQ图片20200721105446](https://user-images.githubusercontent.com/8606965/88007493-ada77600-cb40-11ea-98b9-c8b7c2b3917b.png)

直接使用预训练模型的话，这个classification方法不支持传入top参数，例如需要返回top5的预测结果和置信度

同时如果使用hub serving来部署这个预训练模型的话，http接口也是不支持top参数的，最好classification方法和serving的接口都增加一个top参数

**Comment by nepeplwu** [comment]
@zhangmianhongni 感谢反馈，xception后续会升级支持top_k参数。目前你可以使用下面这个module作为替代，该module已经支持top_k参数
https://www.paddlepaddle.org.cn/hubdetail?name=resnet50_vd_imagenet_ssld&en_category=ImageClassification

**Comment by zhangmianhongni** [comment]
> @zhangmianhongni 感谢反馈，xception后续会升级支持top_k参数。目前你可以使用下面这个module作为替代，该module已经支持top_k参数
> https://www.paddlepaddle.org.cn/hubdetail?name=resnet50_vd_imagenet_ssld&en_category=ImageClassification

好的

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
