### ISSUE TITLE
LAC是否支持多线程？

### ISSUE THREAD

**Issue by PHizing** [PaddlePaddle/PaddleFormers#77]
用hub使用lac有几个问题，望解答：
1. lac是否支持多线程？没看到接口有描述，在业务实现多线程，报string index out of range错误，只能改为多进程，才开始正常
2. lac的代码实现在哪里？比如lexical_analysis这个api接口。
3. lac的句法分析是用哪套API呢？
4. 原程序使用了logger做日志输出，指定到了文件里面。引入hub，加载lac模块后，日志既输出到文件，还输出到了控制台，不知道怎么关掉。

**Comment by Steffy-zxf** [comment]
感谢反馈！
1. PaddleHub Module Lac 目前暂不支持多线程。
2. Lac的代码实现可以参考$HOME/.paddlehub/module/lac/ 下.py文件的实现。由于PaddleHub并没有对外开放个Module的代码实现，所以还没有相应的文档说明Module具体实现。
3. 您的意思是想了解LAC模型实现吗？如果是这样的话，可以参考 https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/lexical_analysis
4. 关闭PaddleHub控制台的日志输出，方法有二
    1）需要运行的python文件下，加入 以下两行
          from paddlehub.common.logger import logger
          logger.setLevel("NOLOG")
    2）以运行PaddleHub/demo/lac/lac_demo.py为例：
          python lac_demo.py 2> test.log
          如此，相应的日志输出会保存在test.log文件中。

**Comment by PHizing** [comment]
谢谢这么及时的反馈。

问题3是指，有没有lac（或者是hub？）对句法进行分析的api。比如对于一个句子：“中国人民共和国成立了”，进行主谓宾的依赖分析？
问题4，我的目的还是用自己的debug、info来写日志文件，同时也不想要两个日志文件的输出。所以我选择1）将hub导入的logger设置为NOLOG，同时将我自己的logger变量重命名了。等程序下次跑的时候再看看效果。

**Comment by PHizing** [comment]
还有一个问题忘了，GPU版本的paddle安装后，仍然报“Compiled with WITH_GPU, but no GPU found in runtime”，查看了有关于paddle的issues，就是一个CUDA和Driver版本不匹配的情况，我对比了，发现是相匹配的。不知道哪里出了问题。该GPU机器的环境下，之前已经可以跑另外的GPU程序了。

**Comment by Steffy-zxf** [comment]
问题3: 有没有lac（或者是hub？）对句法进行分析的api?比如对于一个句子：“中国人民共和国成立了”，进行主谓宾的依赖分析？
 回复： Lac不支持句法分析。

关于Paddle-GPU的安装问题，“Compiled with WITH_GPU, but no GPU found in runtime”，可以参考https://github.com/PaddlePaddle/Paddle/issues/18602

**Comment by PHizing** [comment]
1. 日志的问题仍未解决。我是这么做的：
```
import paddlehub as hub
from paddlehub.common.logger import logger
logger.setLevel("NOLOG")

...

import mylog as ml
\# 我自己的日志输出
lac_logger = ml.log_print(__name__)

lac_logger.info("all cut finish.")
```

仍然是控制台和日志文件各输出一份，不过格式不一样。
控制台输出：
[2019-07-15 18:31:57,102] [    INFO] - start cut 
日志文件输出
[22470][139773570205440]2019-07-15 18:30:43,520 - lac_cut_word - [INFO] - start cut

应该是paddle的日志还是没有关掉

2. GPU的问题，我看的就是那个issue，可以看到我在那个issue也回了信息

**Comment by Steffy-zxf** [comment]
具体代码方便贴出来吗？

**Comment by Steffy-zxf** [comment]
想了解下，import mylog as ml， 这个mylog是colorlog吗？

**Comment by PHizing** [comment]
我用的是ConcurrentLogHandler。
mylog的代码大致如下：
```
import logging
import logging.handlers
from cloghandler import ConcurrentRotatingFileHandler as RFHandler

LOG_FILE = "../log/server.log"

def log_print(name):
    concurrent_loghandle = RFHandler(LOG_FILE, maxBytes=500 * 1024 * 1024,
                                     backupCount=5)
    format_str = '[%(process)d][%(thread)d]%(asctime)s - %(name)s - [%(levelname)s] - %(message)s '
    formatter = logging.Formatter(format_str)
    concurrent_loghandle.setFormatter(formatter)

    logger = logging.getLogger(name)
    logger.setLevel(logging.DEBUG)
    logger.addHandler(concurrent_loghandle)

    return logger
```

**Comment by Steffy-zxf** [comment]
@PHizing 感谢反馈，目前该问题我们已经复现，原因正在排查中，初步分析和logging的handler机制有关，正在考虑解决方案，有合适方案我们第一时间回复。

**Comment by nepeplwu** [comment]
@PHizing ，这个问题是因为我们的logger设置了logging的basicConfig，导致logging增加了一个handler导致。我们会在后续版本中修复该问题，抱歉给你造成了不便

目前可以通过在你的mylog文件中，调用以下代码删除掉该handler
```python
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)
```

**Comment by PHizing** [comment]
文件中不行，得是log_print函数中。现在终于取消了hub的打印。Thanks
GPU的问题，还有没有可能进一步追踪？

**Comment by nepeplwu** [comment]
@PHizing 关于GPU的问题，建议check以下几个点：
1. CUDA版本和驱动是否对应得上
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#abstract
![77038796-B80F-461C-BA4B-A13C47925FB5](https://user-images.githubusercontent.com/45024560/61842678-969d5c00-aecb-11e9-93c8-c9149947f0fe.JPG)
2. LD_LIBRARY_PATH中CUDA相关路径是否设置正确
3. CUDA_HOME、CUDA_VISIBLE_DEVICES环境变量是否设置正确

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
