### ISSUE TITLE
图像分类

### ISSUE THREAD

**Issue by j2538318409** [PaddlePaddle/PaddleFormers#772]
您好 尊敬的技术员：
      目前我还没有能获取到图像的特征向量的接口用于计算余玄相似读

**Comment by Steffy-zxf** [comment]
你好！图像分类的module（https://www.paddlepaddle.org.cn/hublist?filter=en_category&value=ImageClassification
） 没有直接提供预测计算余弦相似度的接口。你可以基于图像分类module的输出特征，继续搭建你想要的网络，计算余弦相似度。可以参考下文本余弦相似度计算demo：
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/docs/tutorial/sentence_sim.md

**Comment by j2538318409** [comment]
好的 那咱们有可以提供特性的接口吗

**Comment by j2538318409** [comment]
我看返回的都是label和对应label的概率

**Comment by Steffy-zxf** [comment]
@j2538318409 由于上述提到的 

> 图像的特征向量的接口用于计算余玄相似度

需求较少，所以不会提供这样的接口。如有需要，可以试试使用paddle op搭建网络计算相似度。

图像分类 module 都支持用于finetune，可以拿到module的特征输出，以resnet50_vd_imagenet_ssld为例


![image](https://user-images.githubusercontent.com/48793257/88179282-3d8f1200-cc5e-11ea-851e-5c88bcaaf012.png)

`feature_map`变量即可用于finetune。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
