### ISSUE TITLE
建议TextClassifierTask的network增加bilstm+attention的net选项

### ISSUE THREAD

**Issue by onewaymyway** [PaddlePaddle/PaddleFormers#780]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
建议TextClassifierTask的network增加bilstm+attention的net选项
- 什么样的场景下需要该特性？
bilstm+attention效果应该比单纯的bilstm好
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
对于新手来说用paddle实现attention有难度，目前网上也几乎搜不到可用的现成代码
- 增加该特性，PaddleHub可能需要变化的部分。
增加bilstm+attention的net选项
- 如果可以的话，简要描述下您的解决方案

**Comment by Steffy-zxf** [comment]
你好！感谢反馈！关于Attention的实现可以参考：https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleNLP/seq2seq/seq2seq/attention_model.py#L38

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
