### ISSUE TITLE
使用use_gpu=True比use_gpu=False慢

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleFormers#781]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：paddlehub 1.7.1，paddlepaddle-gpu 1.8.1.post107
2）系统环境：CentOS7, python 3.7.6, GPU: RTX 2080

测试pyramidbox_lite_server_mask模型的face_detection API时发现使用use_gpu=True比use_gpu=False慢：以下为单张图片使用face_detection时time.perf_count()的耗时：

`use_gpu=True`

> time cost: 4.844235592056066
> time cost: 1.454470616299659
> time cost: 1.3260896857827902
> time cost: 1.425043759867549
> time cost: 1.4381717252545059
> time cost: 1.3000757340341806
> time cost: 1.3987517324276268
> time cost: 1.4077853970229626
> time cost: 1.2869801730848849
> done, time cost: 15.88195555889979

`use_gpu=False`

> time cost: 2.0452515189535916
> time cost: 1.7653371165506542
> time cost: 1.388544927816838
> time cost: 1.5212951567955315
> time cost: 1.4754767650738358
> time cost: 1.4352801940403879
> time cost: 1.3712380463257432
> time cost: 1.4844537246972322
> time cost: 1.3216509399935603
> done, time cost: 13.819137034006417

使用的模型及版本号：

> !hub install pyramidbox_lite_server_mask==1.0.0
> !hub install pyramidbox_lite_server==1.1.0

请问这是为什么呢，如何能够更加快速地推理？

**Comment by Steffy-zxf** [comment]
你好！使用GPU预测，建议batch化预测。单条数据预测建议使用CPU。

**Comment by T-baby** [comment]
我在使用 simnet 这个模型的时候也遇到了同样的问题，已经 batch 化预测了。但是 GPU 上就是很慢，而且随着数据量提升会与 CPU 速度拉开更大的差距。

**Comment by nihuizhidao** [comment]
对的，已经使用CPU预测了。。。对于流式数据，没有办法用batch的。。。。

**Comment by Steffy-zxf** [comment]
@nihuizhidao @T-baby 你好！GPU预测的话，建议在batch_size较大时预测速度会明显提升！如果是流式数据，建议使用CPU预测。

**Comment by T-baby** [comment]
batch_size 从 32 到 512 都调过，然后一次输入一万条数据，但还是慢过 CPU，GPU 使用率平均在 70% - 80%。

**Comment by Karenlyw** [comment]
您好 为什么我用use_gpu起来了serving，gpu使用率却为0呢
