### ISSUE TITLE
服务出现假死现象

### ISSUE THREAD

**Issue by bikerr** [PaddlePaddle/PaddleFormers#787]
Paddlehub 1.7 Linux  官方docker 环境 python 3.5.2 
部署的chinese_ocr_db_crnn_mobile 模型，偶尔出现假死现象
kill port 也无法杀掉进程 不对外提供服务，最近发现的一次是在其他服务进行重新部署 有可能打断了正在执行的操作类似于客户端断开连接

**Comment by Steffy-zxf** [comment]
你好！PaddleHub 要求python3.6以上环境。请更换python环境再试试。

**Comment by ShenYuhan** [comment]
请问具体的情况是什么样的，进程是否还存活呢？

**Comment by bikerr** [comment]
![image](https://user-images.githubusercontent.com/14155359/89626701-5a694d80-d8cc-11ea-9adf-315e4fae4870.png)
![image](https://user-images.githubusercontent.com/14155359/89626732-681ed300-d8cc-11ea-9de9-dda03ed16470.png)

进程存活，今天又发生了 仔细拍查了下 发现是出现了死锁，目前该服务是单进程部署，有一个定时进程进行监控，当监控不到进程的时候会进行重新拉起进行，目前还不知道是什么情况 出现了三个进程 
```
/root/.paddlehub/conf/config.json
socket:[44564127]
```
三个进程发生了死锁

@ShenYuhan @Steffy-zxf

**Comment by ShenYuhan** [comment]
您好，您可以试一下下面的步骤
1 删除旧进程
2 删除config.json文件
重新运行，这个文件会被hub进程加锁，如果检测不到进程存在的时候一定要把这个文件删掉，才能重新唤起新进程

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Comment by 736048546** [comment]
请问解决了吗？
