### ISSUE TITLE
口罩预测模型如何在树莓派上运行（python）

### ISSUE THREAD

**Issue by shenyt-sanshui** [PaddlePaddle/PaddleFormers#793]
请问通过paddle lite，将口罩检测模型部署到树莓派4b有python的demo吗，网上找到了c++的但是没有Python的呢，请问可不可以提供一下呀

**Comment by Steffy-zxf** [comment]
你好！口罩模型python预测方法参考 API介绍以及使用样例：https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_mobile_mask&en_category=FaceDetection

![image](https://user-images.githubusercontent.com/48793257/89139288-c8caaa80-d570-11ea-8c52-98f07f6fcb92.png)

**Comment by ZeyuChen** [comment]
目前Paddle框架暂时还不支持arm上直接运行，因此Hub也无法再arm上直接运行，需要通过Paddle Lite完成树莓派部署。
更多可以参考 https://paddle-lite.readthedocs.io/zh/latest/demo_guides/linux_arm_demo.html

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
