### ISSUE TITLE
请求添加albert模型？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleFormers#794]
.

**Comment by Steffy-zxf** [comment]
你好！感谢反馈！目前小模型可以参考ernie_tiny: https://www.paddlepaddle.org.cn/hubdetail?name=ernie_tiny&en_category=SemanticModel

同时，想了解下您的任务背景是什么呢？

**Comment by ghost** [comment]
希望对比ernie_tiny，ALBERT等小模型的速度和性能。
