### ISSUE TITLE
请问一下ERNIE的文本分类采用什么优化器？

### ISSUE THREAD

**Issue by lexmen318** [PaddlePaddle/PaddleFormers#80]
我使用30万的数据，进行100多类的分类训练，发现训练过程震荡比较明显。

**Comment by Steffy-zxf** [comment]
ERNIE的文本分类采用Adam优化器，默认优化策略选择AdamWeightDecayStrategy，详情参考 

 https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub-API:-Strategy#class-hubfinetunestrategyadamweightdecaystrategy。

建议开启Warmup，比例warmup_proportion设置为0.1

**Comment by lexmen318** [comment]
好的，感谢

**Comment by lexmen318** [comment]
刚看了一下，目前我使用的版本里面，warmup_proportion缺省已经是0.1了。

另外learning_rate缺省为1e-4，我使用的是5e-5，序列长度我用的是256。

不知道还有什么好建议？

**Comment by Steffy-zxf** [comment]
learning_rate可以尝试稍调大一点。想了解下，数据集文本平均长度大概是多少？如果较小，可以尝试将max_seq_length调小，将batch_size增大。

**Comment by lexmen318** [comment]
好的，非常感谢你的建议！

数据集文本平均长度预计在100多左右，因此我会试试采纳你的建议。

目前256的结果已经出来了，虽然震荡比较严重，不过最终还是收敛到合理的期望结果。

另外补充问一句，请问step数量与epoch的关系是怎样的？我设定了epoch为3，但在训练过程中，没有看到有关epoch的任何提示，只知道每100step会做一次 validation，最后竟然执行了1万多个 step，我估计这个step总数和epoch、GPU卡数以及数据集大小都有关吧？能否提供一下换算的关系？

**Comment by Steffy-zxf** [comment]
是的，这个step总数是根据epoch、GPU卡数、数据集大小和batch_size有关。step = epoch * ( num_data / batch_size )  / dev_count , 其中num_data是数据集文本的数量，dev_count是GPU卡数。

**Comment by lexmen318** [comment]
好的，感谢你的回复！
