### ISSUE TITLE
服务端部署成功，客户端请求出错（树莓派）

### ISSUE THREAD

**Issue by shenyt-sanshui** [PaddlePaddle/PaddleFormers#800]
服务器端 ：
windows10

客户端 ：
树莓派4b
32bit
armv7

我在windows10上成功部署了
![image](https://user-images.githubusercontent.com/59388845/89178800-06efba80-d5c1-11ea-8632-4b6c95674321.png)
然后我在windows10上，在.py文件中通过客户端请求的方式，得到预测结果（一切正常，客户端请求也正常，返回结果也正常）
# datas = {'images':[cv2_to_base64(frame)],"visualization":True,"output_dir":"result"} 
# headers = {"Content-type": "application/json"}
# url = "http://127.0.0.1:8866/predict/pyramidbox_lite_server_mask"
# r = requests.post(url=url, headers=headers, data=json.dumps(datas))
但是，当我把同样的.py文件在树莓派上跑的时候，却返回这样的错误
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8866): Max retries exceeded with url: /predict/pyramidbox_lite_server_mask (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa038a4f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
树莓派连上网了，和windows连的是同一个wifi。

请问这是什么原因呢

**Comment by ShenYuhan** [comment]
确认下使用的ip地址是否正确，你是指在pc端部署，移动端请求吧，那么ip地址应该为pc端的ip地址而不是127.0.0.1

**Comment by shenyt-sanshui** [comment]
哦哦谢谢，但是为啥我在pc端请求的时候使用127.0.0.1却成功请求到了。  还有这里ip地址指的是啥呀，是服务器端的ip地址吗。windows dos中ipconfgi/all  中里面的ipv4地址么。

**Comment by shenyt-sanshui** [comment]
解决啦，改了ip就行了，谢谢！

**Comment by Steffy-zxf** [comment]
该问题已解决，就此关闭。如后续还有问题，可以重新开启问题。
