### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleFormers#801]
![image](https://user-images.githubusercontent.com/57654726/89264221-28a27d80-d665-11ea-9bdf-912771f45d7d.png)
部分图片遇到这问题，导致消耗大量内存和时间，

**Comment by Steffy-zxf** [comment]
你好！请问任务背景是什么呢？module是什么？运行的代码是什么样的呢？

**Comment by xialei2821212670** [comment]
> 你好！请问任务背景是什么呢？module是什么？运行的代码是某种的呢？
进行ocr预测的时候，图片计算时出现nan,模型是ocr = hub.Module(name="chinese_ocr_db_crnn_server")

**Comment by Steffy-zxf** [comment]
@xialei2821212670 感谢反馈！目前该问题已修复，可以尝试安装chinese_ocr_db_crnn_server 1.0.2版本 或者 chinese_ocr_db_crnn_mobile 1.0.3版本。
```shell
$ hub install chinese_ocr_db_crnn_server==1.0.2
$ hub install chinese_ocr_db_crnn_mobile==1.0.3
```

**Comment by xialei2821212670** [comment]
> @ xialei2821212670感谢反馈！现有该问题已修复，可以尝试安装chinese_ocr_db_crnn_server 1.0.2版本或chinese_ocr_db_crnn_mobile 1.0.3版本。
> 
> ```shell
> $ hub install chinese_ocr_db_crnn_server == 1.0.2
> $ hub intsall chinese_ocr_db_crnn_mobile == 1.0.3
> ```

命令修改为 $ hub install chinese_ocr_db_crnn_mobile == 1.0.3

**Comment by Steffy-zxf** [comment]
你好！该问题已修复。请根据上述回复解决。该issue就此关闭。
