### ISSUE TITLE
GPU训练模型，在GPU服务器上预测的结果与在本地不带GPU预测的结果相差较大

### ISSUE THREAD

**Issue by Sherry666666** [PaddlePaddle/PaddleFormers#809]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
paddlepaddle:1.7.0
paddlehub:1.6.2
ernie:训练时未指定版本，但服务器是本地考上去的，所以确定两边用的是同一版本

代码是一致的

**Comment by Steffy-zxf** [comment]
你好！你使用的是什么任务呢？代码是什么样的呢？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
