### ISSUE TITLE
用Paddlepaddle训练的模型，用paddlehub加载做推理时缺少module_desc.pb文件

### ISSUE THREAD

**Issue by lambert-lan** [PaddlePaddle/PaddleFormers#81]
用Paddlepaddle训练的模型，用paddlehub加载做推理时缺少module_desc.pb文件，请问有没有解决方法
还是用paddlehub加载的模型必须用paddlehub训练?

**Comment by ZeyuChen** [comment]
可否更详细的描述下您的使用场景？
不是特别理解paddle训练的模型用paddlehub来推理是什么场景。

**Comment by lambert-lan** [comment]
> 可否更详细的描述下您的使用场景？
> 不是特别理解paddle训练的模型用paddlehub来推理是什么场景。

比如之前用paddleNLP里面的emotion_detection训练脚本跑完生成的模型(参数use_paddle_hub=true)，里面并没有module_desc.pb文件，然后我想用paddlehub.Module(module_dir=[])加载就报错了

请问这个怎么解决？非常感谢

**Comment by Steffy-zxf** [comment]
1.  PaddleHub中Module是PaddleHub在已保存预训练模型参数基础上封装的可执行模块，所以直接利用想用paddlehub.Module(module_dir=“模型参数文件”)加载，是无法运行的。
2. 了解下，您想用PaddleHub的背景是什么呢？比如想利用PaddleHub进行对自定义模型Finetune？
3.  如果您是想利用PaddleNLP中的emotion_detection模型，PaddleHub现已支持该模型加载，您可以通过如下方式加载：
```python
import paddlehub as hub

module = hub.module(name="emotion_detection_textcnn")
```
关于该module的详情可以参考    https://www.paddlepaddle.org.cn/hubdetail?name=emotion_detection_textcnn&en_category=SentimentAnalysis

另外，您可以通过命令端 hub search 查找PaddleHub支持的所有Module。
