### ISSUE TITLE
口罩预测模型如何判断是否检测到人脸

### ISSUE THREAD

**Issue by shenyt-sanshui** [PaddlePaddle/PaddleFormers#812]
请问口罩预测模型，如果是将模型部署到服务器上，通过客户端请求的方式获取检测结果，
那么如何能获得人脸的检测结果呢（即是否检测到人脸），好像官网的教程只提供了是否佩戴口罩的检测，不知道人脸检测在客户端是如何调用的呢。（口罩检测模型里面应该有包含人脸检测模型吧，请问接口是啥呀）

**Comment by shenyt-sanshui** [comment]
已解决

**Comment by Steffy-zxf** [comment]
你好！口罩模型检测口罩，第一步检测人脸，第二步检测是否佩戴口罩。人脸检测模型：使用的模型为pyramidbox_lite_server、pyramidbox_lite_mobile

https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_server&en_category=FaceDetection

https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_mobile&en_category=FaceDetection

![image](https://user-images.githubusercontent.com/48793257/89747665-66ceef80-daf2-11ea-8c88-69c363125f6e.png)

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
