### ISSUE TITLE
关于模型一键部署服务

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleFormers#816]
我想知道PaddleHub Serving 一键部署服务现在支持部署 **开发者使用PaddleHub Fine-tune API得到的模型**了吗？

**Comment by iceriver97** [comment]
我利用PaddleHub Fine-tune过的模型该如何部署呢？

**Comment by iceriver97** [comment]
一键部署支持的模型列表是该页面所有的模型吗？
https://paddlepaddle.org.cn/hublist
为什么我在部署时会出现错误提示：该模型不能用来预测

**Comment by Steffy-zxf** [comment]
你好！
1. PaddleHub Finetune得到的模型可以用PaddleHub Serving，但需要先将保存的模型参数转换成一个module，
可以参考文档：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/finetuned_model_to_module.md

>2.  一键部署支持的模型列表是该页面所有的模型吗？
https://paddlepaddle.org.cn/hublist
为什么我在部署时会出现错误提示：该模型不能用来预测

PaddleHub所有的module可以在 https://paddlepaddle.org.cn/hublist 找到，但不是所有的module都支持一键部署。只有支持直接预测的module才支持部署预测。如ERNIE这类模型（支持Fine-tune，不能一键预测）就不能一键部署，可以先fine-tune后保存模型，转成module之后部署。

**Comment by iceriver97** [comment]
@Steffy-zxf  感谢您的回复，很有帮助，我参照您给的文档进行了转化，但是我不太清楚 modelinfo 里 type 字段该如何填写：
```
@moduleinfo(
    name="ernie_tiny_finetuned",
    version="1.0.0",
    summary="ERNIE tiny which was fine-tuned on the chnsenticorp dataset.",
    author="anonymous",
    author_email="",
    type="nlp/semantic_model")
```
如果我的模型是做 触发词识别 的，我该如何填写？
如果我的模型是做 论元角色识别 的，我该如何填写？
谢谢您！

**Comment by iceriver97** [comment]
@Steffy-zxf  我在写完Module.py之后，尝试运行，但给出了下面的错误：
[2020-08-12 23:32:47,367] [    INFO] - Installing chinese-roberta-wwm-ext-large module
[2020-08-12 23:32:47,369] [    INFO] - Module chinese-roberta-wwm-ext-large already installed in /home/aistudio/.paddlehub/modules/chinese_roberta_wwm_ext_large
[2020-08-12 23:33:00,294] [    INFO] - Load pretraining parameters from /home/aistudio/.paddlehub/modules/chinese_roberta_wwm_ext_large/assets/params.
Traceback (most recent call last):
  File "./module.py", line 174, in <module>
    ckpt_dir="./role")
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/module/module.py", line 122, in __new__
    directory=directory, **kwargs)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/module/module.py", line 199, in init_with_directory
    user_module = _item(directory=directory, **kwargs)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddlehub/module/module.py", line 145, in __init__
    self._initialize(**kwargs)
  File "/home/aistudio/work/finetuned_model_to_module/module.py", line 93, in _initialize
    word_dict_path=self.module.get_word_dict_path())
TypeError: __init__() takes at least 2 arguments (5 given)

这是否与type字段有关呢？修改后的 Module.py 代码如下：
```
@moduleinfo(
    name="chinese-roberta-wwm-ext-large_finetuned",
    version="1.0.0",
    summary="ERNIE tiny which was fine-tuned on the chnsenticorp dataset.",
    author="anonymous",
    author_email="",
    type="nlp/sentiment_analysis")
class ERNIETinyFinetuned(hub.Module):
    def _initialize(self,
                    # 修改为包含 best_model 的文件夹
                    ckpt_dir="role",
                    max_seq_len=128,
                    use_gpu=False,
                    batch_size=1):
        self.ckpt_dir = os.path.join(self.directory, ckpt_dir)
        self.MAX_SEQ_LEN = max_seq_len

        # Load Paddlehub ERNIE Tiny pretrained model
        # 修改为自己加载的预训练模型
        model_name = "chinese-roberta-wwm-ext-large"
        self.module = hub.Module(model_name)
        inputs, outputs, program = self.module.context(
            trainable=True, max_seq_len=max_seq_len)

        self.vocab_path = self.module.get_vocab_path()

        # Download dataset and use accuracy as metrics
        # Choose dataset: GLUE/XNLI/ChinesesGLUE/NLPCC-DBQA/LCQMC
        # metric should be acc, f1 or matthews
        schema_labels = schema_process('/home/aistudio/work/event_schema/event_schema.json', 'trigger')
        dataset = EEDataset('/home/aistudio/work/', schema_labels, model='trigger')
        metrics_choices = ["acc"]

        # For ernie_tiny, it use sub-word to tokenize chinese sentence
        # If not ernie tiny, sp_model_path and word_dict_path should be set None
        reader = hub.reader.SequenceLabelReader(
            dataset=dataset,
            max_seq_len=256,
            sp_model_path=self.module.get_spm_path(),
            word_dict_path=self.module.get_word_dict_path())

        # Construct transfer learning network
        # Use "sequence_output" for token-level output.
        # 使用ERNIE模型字级别的输出sequence_output作为迁移网络的输入
        sequence_output = outputs["sequence_output"]

        # Setup feed list for data feeder
        # Must feed all the tensor of module need
        feed_list = [
            inputs["input_ids"].name,
            inputs["position_ids"].name,
            inputs["segment_ids"].name,
            inputs["input_mask"].name,
        ]
        # 选择优化策略
        strategy = hub.AdamWeightDecayStrategy(
            warmup_proportion=0.1,
            weight_decay=0.01,
            learning_rate=3e-5)
        # 配置运行设置
        config = hub.RunConfig(
            eval_interval=100,
            save_ckpt_interval=1000,
            use_data_parallel=False,
            use_cuda=True,
            num_epoch=3,
            batch_size=8,
            checkpoint_dir=self.ckpt_dir,
            strategy=strategy)

         # Define a classfication finetune task by PaddleHub's API
        # 构建序列标注迁移任务
        seq_label_task = hub.SequenceLabelTask(
            data_reader=reader,
            feature=sequence_output,
            feed_list=feed_list,
            max_seq_len=256,
            num_classes=dataset.num_labels,
            config=config,
            add_crf=True)

    @serving
    def predict(self, data, return_result=False, accelerate_mode=True):
        """
        Get prediction results
        """
        run_states = self.cls_task.predict(
            data=data,
            return_result=return_result,
            accelerate_mode=accelerate_mode)
        results = [run_state.run_results for run_state in run_states]
        prediction = []
        for batch_result in results:
            # get predict index
            batch_result = np.argmax(batch_result, axis=2)[0]
            batch_result = batch_result.tolist()
            prediction += batch_result
        return prediction


if __name__ == "__main__":
    ernie_tiny = ERNIETinyFinetuned(
        ckpt_dir="./role")

    # Data to be prdicted
    data = [["这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般"], ["交通方便；环境很好；服务态度很好 房间较小"],
            ["19天硬盘就罢工了~~~算上运来的一周都没用上15天~~~可就是不能换了~~~唉~~~~你说这算什么事呀~~~"]]

    predictions = ernie_tiny.predict(data=data)
    for index, text in enumerate(data):
        print("%s\tpredict=%s" % (data[index][0], predictions[index]))
```

**Comment by iceriver97** [comment]
@Steffy-zxf 您好，转换后，测试模型，功能正常。但是当我直接用命令
`hub serving start –m my_module_name`
启动服务时报错找不到指定的模型，因为什么呢？我需要把转换好的Module放在某个地方,以便hub可以找到他吗？
安装成功之后，为什么通过hub list 查看不到自己的模型呢？
已经提示：Successfully installed chinese-roberta-wwm-ext-large_finetuned
但就是找不到该模型

**Comment by iceriver97** [comment]
@Steffy-zxf  HubServing 可以将多个Module发布成一个服务吗？

**Comment by Steffy-zxf** [comment]
> 1. hub serving start –m my_module_name
启动服务时报错找不到指定的模型，因为什么呢？我需要把转换好的Module放在某个地方,以便hub可以找到他吗？
安装成功之后，为什么通过hub list 查看不到自己的模型呢？
已经提示：Successfully installed chinese-roberta-wwm-ext-large_finetuned
但就是找不到该模型

`hub install Path/to/Module/`会将module安装到${HUB_HOME}下。如果你没有改过${HUB_HOME}环境变量，默认为`~/.paddlehub/modules/`下。安装module之后，使用`hub show chinese-roberta-wwm-ext-large_finetuned`查看module信息，会显示module的位置。

> 2. HubServing 可以将多个Module发布成一个服务吗？

你是想怎么用这多个Module呢？ 比如说，senta module的预处理切词是使用lac进行切词的，但是serving服务接口完成的是情感分类功能，lac module切词属于在senta module情感分类之前的预处理步骤。但senta module提供预测部署接口只有一个，就是切词功能。

**Comment by iceriver97** [comment]
@Steffy-zxf 感谢，我在`~/.paddlehub/modules/`可以看到自己的Module，但是当我使用 `hub show chinese-roberta-wwm-ext-large_finetuned` 时会提示我  `chinese-roberta-wwm-ext-large_finetuned is not existed!`这是什么原因呢？
2. 将事件抽取分为了两个子任务：触发词识别、论元抽取；
对应两个子任务分别训练了两个模型；
我只能将两个模型分别发布服务，最后再做整合吗？
非常感谢！

**Comment by Steffy-zxf** [comment]
> 我在~/.paddlehub/modules/可以看到自己的Module，但是当我使用 hub show chinese-roberta-wwm-ext-large_finetuned 时会提示我 chinese-roberta-wwm-ext-large_finetuned is not existed!

方便贴下 module.py的代码吗？

> 2. 将事件抽取分为了两个子任务：触发词识别、论元抽取；
对应两个子任务分别训练了两个模型；
我只能将两个模型分别发布服务，最后再做整合吗？

其中一个任务的输入是另一个任务的输出吗？如果是的话，serving接口可以是最终下游任务的预测接口。

**Comment by iceriver97** [comment]
@Steffy-zxf  万分感谢！我分别将两个模型转化为了两个Module，两个模型即为[这个项目](https://aistudio.baidu.com/aistudio/projectdetail/381711)中的两个模型；
修改后的module.py的代码如下：（两个文件的差异仅在将role的地方替换成了trigger）
`
```
"""Finetuning on classification task """
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import json
import numpy as np
from paddlehub.common.logger import logger
from paddlehub.module.module import moduleinfo, serving
import paddlehub as hub
from paddlehub.dataset.base_nlp_dataset import BaseNLPDataset
# from sequence_label import EEDataset
from data_process import schema_process,data_process,write_by_lines

class EEDataset(BaseNLPDataset):
    """EEDataset"""
    def __init__(self, data_dir, labels, model="role"):
        # 数据集存放位置
        super(EEDataset, self).__init__(
            base_path=data_dir,
            train_file="{}_train.tsv".format(model),
            dev_file="{}_dev.tsv".format(model),
            test_file="{}_test.tsv".format(model),
            # 如果还有预测数据（不需要文本类别label），可以放在predict.tsv
            predict_file="{}_predict.tsv".format(model),
            train_file_with_header=True,
            dev_file_with_header=True,
            test_file_with_header=True,
            predict_file_with_header=True,
            # 数据集类别集合
            label_list=labels)
@moduleinfo(
    name="chinese-roberta-wwm-ext-large_finetuned",
    version="1.0.0",
    summary="ERNIE tiny which was fine-tuned on the chnsenticorp dataset.",
    author="anonymous",
    author_email="",
    type="nlp/sequence_label")
class ERNIETinyFinetuned(hub.Module):
    def _initialize(self,
                    # 修改为包含 best_model 的文件夹
                    ckpt_dir="role",
                    # num_class=2,
                    max_seq_len=256,
                    use_gpu=True,
                    batch_size=3):
        self.ckpt_dir = os.path.join(self.directory, ckpt_dir)
        # self.num_class = num_class
        self.MAX_SEQ_LEN = max_seq_len
```

        # Load Paddlehub ERNIE Tiny pretrained model
        # 修改为自己加载的预训练模型
        model_name = "chinese-roberta-wwm-ext-large"
        self.module = hub.Module(model_name)
        inputs, outputs, program = self.module.context(
            trainable=True, max_seq_len=max_seq_len)

        self.vocab_path = self.module.get_vocab_path()

        # Download dataset and use accuracy as metrics
        # metric should be acc, f1 or matthews
        schema_labels = schema_process('/home/aistudio/work/event_schema/event_schema.json', 'role')
        dataset = EEDataset('/home/aistudio/work/', schema_labels, model='role')
        metrics_choices = ["acc"]

        # For ernie_tiny, it use sub-word to tokenize chinese sentence
        # If not ernie tiny, sp_model_path and word_dict_path should be set None
        reader = hub.reader.SequenceLabelReader(
            dataset=dataset,
            max_seq_len=256,
            vocab_path=self.module.get_vocab_path(),
            sp_model_path=self.module.get_spm_path(),
            word_dict_path=self.module.get_word_dict_path())

        # 使用ERNIE模型字级别的输出sequence_output作为迁移网络的输入
        sequence_output = outputs["sequence_output"]

        # Setup feed list for data feeder
        # Must feed all the tensor of module need
        feed_list = [
            inputs["input_ids"].name,
            inputs["position_ids"].name,
            inputs["segment_ids"].name,
            inputs["input_mask"].name,
        ]

        # 选择优化策略
        strategy = hub.AdamWeightDecayStrategy(
            warmup_proportion=0.1,
            weight_decay=0.01,
            learning_rate=3e-5)
        # 配置运行设置
        config = hub.RunConfig(
            eval_interval=100,
            save_ckpt_interval=1000,
            use_data_parallel=False,
            use_cuda=True,
            num_epoch=3,
            batch_size=8,
            checkpoint_dir=self.ckpt_dir,
            strategy=strategy)
            
        # # Define a classfication finetune task by PaddleHub's API
        # 构建序列标注迁移任务
        self.seq_label_task = hub.SequenceLabelTask(
            data_reader=reader,
            feature=sequence_output,
            feed_list=feed_list,
            max_seq_len=256,
            num_classes=dataset.num_labels,
            config=config,
            add_crf=True)

    @serving
    def predict(self, data, return_result=False, accelerate_mode=True):
        """
        Get prediction results
        """
        print("start predict process")
        schema_labels = schema_process('/home/aistudio/work/event_schema/event_schema.json', 'role')
        dataset = EEDataset('/home/aistudio/work/', schema_labels, model='role')
        reader = hub.reader.SequenceLabelReader(
            dataset=dataset,
            max_seq_len=256,
            vocab_path=self.module.get_vocab_path(),
            sp_model_path=self.module.get_spm_path(),
            word_dict_path=self.module.get_word_dict_path())
        ret = []
        predict_sents, predict_data = data_process('/home/aistudio/work/test1_data/test1.json', 'role', is_predict=True)
        id2label = {val: key for key, val in reader.label_map.items()}
        input_data = [[d] for d in predict_data]
        run_states = self.seq_label_task.predict(data=input_data[1:])
        results = []
        for batch_states in run_states:
            batch_results = batch_states.run_results
            batch_infers = batch_results[0].reshape([-1]).astype(np.int32).tolist()
            seq_lens = batch_results[1].reshape([-1]).astype(np.int32).tolist()
            current_id = 0
            for length in seq_lens:
                seq_infers = batch_infers[current_id:current_id + length]
                seq_result = list(map(id2label.get, seq_infers[1: -1]))
                current_id += length if True else 256
                results.append(seq_result)

        ret = []
        for sent, r_label in zip(predict_sents, results):
            sent["labels"] = r_label
            ret.append(json.dumps(sent, ensure_ascii=False))
        write_by_lines("{}.{}.predict".format('/home/aistudio/work/test1_data/test1.json', 'role'), ret)
        



```
if __name__ == "__main__":
    ernie_tiny = ERNIETinyFinetuned(
        ckpt_dir="role")
    # # Data to be prdicted
    data = [["这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般"], ["交通方便；环境很好；服务态度很好 房间较小"],
             ["19天硬盘就罢工了~~~算上运来的一周都没用上15天~~~可就是不能换了~~~唉~~~~你说这算什么事呀~~~"]]
    ernie_tiny.predict(data=data)
    # predictions = ernie_tiny.predict(data=data)
    # for index, text in enumerate(data):
    #     print("%s\tpredict=%s" % (data[index][0], predictions[index]))`
```

**Comment by Steffy-zxf** [comment]
看了下上面module.py代码，整体写法没问题。具体出现module not found的问题，还需要调试下。方便公开下项目吗？
1. 同时，也可以使用`hub.Module(directory=Path/to/Module/)`加载module。
2. 预测时，其实可以不用加载数据集`EEDataset`。`SequenceLabelReader`中`dataset`参数置为`None`即可。

**Comment by iceriver97** [comment]
@Steffy-zxf 感谢你，我可以正常加载模型了，也能启动服务，not found 是因为下划线与横杠的混淆；但是我在客户端请求的时候会报错，请问是我传送数据格式的问题吗？我应该改成什么样呢？
`curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"text": ["7岁男孩地震遇难，父亲等来噩耗失声痛哭，网友：希望不再有伤亡"],"id":["6eab49e6643d5a5f50037be79937d7cb"]}],"fetch":["ret"]}' http://127.0.0.1:8866/predict/chinese-roberta-wwm-ext-large_finetuned
`
报错：
{
    "msg": "Please check data format!", 
    "status": "-1", 
    "results": ""
}

**Comment by ShenYuhan** [comment]
您可以安装最新版的paddlehub，1.8.1，然后进行预测，在服务端会把具体的错误信息打印出来。
