### ISSUE TITLE
PaddleHub 能启动但不能下载模型是什么意思？

### ISSUE THREAD

**Issue by nn3126** [PaddlePaddle/PaddleFormers#822]
没法下载安装模型
D:\Programs\PaddleOCR>hub install chinese_ocr_db_crnn_mobile
Can't find module chinese_ocr_db_crnn_mobile, please check your spelling.

但下面这个识图可以装成功~
hub install deploy\hubserving\ocr_system\

是哪里的问题？

**Comment by Steffy-zxf** [comment]
你好！paddlehub、paddle版本是多少呢？我没能复现你的错误。请尝试升级paddlehub、paddle为最新版本，paddlehub(1.8.1)/paddle(1.8.3)

**Comment by nn3126** [comment]
本来其它都正常，突然就崩了。全部删除重装就可以了，现在也没找到原因
