### ISSUE TITLE
能否在日志输出上显示epoch的轮次？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleFormers#823]
现有日志输出：
[2020-08-16 12:50:06,106] [   TRAIN] - step 10 / 231: loss=0.82945 f1=0.37425 [step/sec: 4.88]
[2020-08-16 12:50:08,067] [   TRAIN] - step 20 / 231: loss=0.51294 f1=0.04651 [step/sec: 5.10]
能否在日志输出上显示epoch的轮次？步数有时不太直观。
另外怎么控制显示一次日志输出的步数，现在好像是每10步？

**Comment by Steffy-zxf** [comment]
你好！epoch可以通过计算得到，每次训练的最大step= num_sample / batch_size * epoch ，可以通过这个公式反推得倒epoch。
控制答应一次日志输出的步数，可以通过RunConfig中的log_interval参数设置。参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/reference/config.md#class-hubfinetuneconfigrunconfig

**Comment by ghost** [comment]
好的，感谢。
那use_data_parallel为什么默认值是True，而use_cuda为False? 感觉两个都为False比较合理

**Comment by Steffy-zxf** [comment]
use_data_parallel表示是否需要数据并行。如果use_cuda=False， use_data_parallel=True，则表示使用多个cpu进行计算。如果use_cuda=True， use_data_parallel=True，则表示使用多个gpu进行计算。
