### ISSUE TITLE
 PaddleCheckError

### ISSUE THREAD

**Issue by yinyiyu** [PaddlePaddle/PaddleFormers#825]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

在Aistudio上面，paddlehub版本为1.6 然后安装的1.6.2   paddle版本为1.6
使用paadlehub的resnet_v2_50_imagenet模型进行finetune 做二分类任务，图片类型是bmp格式的。
前面步骤都没有问题，最后在执行run_states = task.finetune_and_eval()的时候报PaddleCheckError
报错如下：

PaddleCheckError: Tensor holds the wrong type, it holds float, but desires to be int64_t at [/paddle/paddle/fluid/framework/tensor_impl.h:30] [operator < cross_entropy2 > error]

但是并不知道在哪里更改类型

**Comment by Steffy-zxf** [comment]
你好！运行的代码是什么？完整的报错信息可以贴上吗？另外目前PaddleHub、Paddle最新版本为1.8.1， 1.8.3。 建议升级至最新版本。

**Comment by yinyiyu** [comment]
谢谢 我更换了最新的paddlehub版本就可以了  可能是paddlehub1.6.2有问题

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
