### ISSUE TITLE
下载hub模型失败

### ISSUE THREAD

**Issue by ares5221** [PaddlePaddle/PaddleFormers#826]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，
paddlepaddle=1.8.1
paddlehub=1.8.1
例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
linux ubuntu18
 python=3.6

import paddlehub as hub
module = hub.Module(name="ernie")
安装的时候无法下载模型
 module = hub.Module(name="ernie")
  File "/home/liujiefei/tensorflow20/tf20/local/lib/python3.6/site-packages/paddlehub/module/module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "/home/liujiefei/tensorflow20/tf20/local/lib/python3.6/site-packages/paddlehub/module/module.py", line 174, in init_with_name
    raise RuntimeError(tips)
RuntimeError: Request Hub-Server unsuccessfully, please check your network.
 
![1597733239(1)](https://user-images.githubusercontent.com/13331671/90479787-cddb4c80-e161-11ea-8948-cc907f6aba19.jpg)

**Comment by Steffy-zxf** [comment]
你好！当前运行环境可以访问外网吗？

**Comment by ares5221** [comment]
![image](https://user-images.githubusercontent.com/13331671/90492283-9bd2e600-e173-11ea-95f8-9d768bc79bb8.png)
可以的，试了下ping baidu可以的

**Comment by ShenYuhan** [comment]
先执行下 `hub config` 看下输出是什么，
然后试下能不能访问 `http://paddlepaddle.org.cn/paddlehub`

**Comment by ares5221** [comment]
![image](https://user-images.githubusercontent.com/13331671/90494392-0be26b80-e176-11ea-8518-d1769fc90eda.png)
hub.config 如何执行呢
print(paddlehub.config)?

**Comment by ShenYuhan** [comment]
在命令行执行`hub config`看下是什么

**Comment by ares5221** [comment]
![image](https://user-images.githubusercontent.com/13331671/90495806-a0999900-e177-11ea-9000-675147daf935.png)
没有执行

**Comment by ares5221** [comment]
![image](https://user-images.githubusercontent.com/13331671/90495897-bc9d3a80-e177-11ea-919c-a4c6e1ed09be.png)

**Comment by ShenYuhan** [comment]
执行一下 `hub clear`
然后打开python脚本，试一下这个脚本
```python
import paddlehub
paddlehub.server_check()
```

**Comment by ares5221** [comment]
![image](https://user-images.githubusercontent.com/13331671/90498113-7f867780-e17a-11ea-82d0-34f0e37ce705.png)

嗯显示request 失败

**Comment by ShenYuhan** [comment]
您有没有开代理之类的呢？
您试下在命令行能否连接http://paddlepaddle.org.cn/paddlehub

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
