### ISSUE TITLE
模型预测并行的list上限多少

### ISSUE THREAD

**Issue by Malestudents** [PaddlePaddle/PaddleFormers#830]
是根据cpu的线程数来的，还是什么呢

**Comment by Steffy-zxf** [comment]
你好！请问你是怎么开启模型预测并行呢？

**Comment by Malestudents** [comment]
data = [
    ["\002".join(list(u"喻晓刚云南省楚雄彝族自治州南华县东街古城路37号18513386163"))],
    ["\002".join(list(u"河北省唐山市玉田县无终大街159号18614253058尚汉生"))],
    ["\002".join(list(u"台湾嘉义县番路乡番路乡公田村龙头17之19号宣树毅13720072123"))],
]

run_states = seq_label_task.predict(data=data)

**Comment by Steffy-zxf** [comment]
> 模型预测并行的list上限多少

并行list是指什么意思呢？是指开启数据并行预测，数据并行的数量？还是指预测data数据量？

如果是指开启数据并行预测
请问你定义的RunConfig对象，use_data_parallel开启了吗？关于use_data_parallel参数含义可以参考回复：https://github.com/PaddlePaddle/PaddleHub/issues/823#issuecomment-674838589。
那么并行上限是指cpu核数或者gpu卡数。

如果是指预测data数据量，一个batch数据预测量上限需要根据你的显存或者内存而决定。

**Comment by Malestudents** [comment]
是paddlehub中的数据并行预测的条数

**Comment by Malestudents** [comment]
use_data_parallel这个参数默认是开启的

**Comment by Steffy-zxf** [comment]
> 是paddlehub中的数据并行预测的条数

并行预测数据量需要根据运行机器内存（或者显存）、模型参数大小、模型处理数据的max_seq_len等因素决定。

**Comment by Malestudents** [comment]
好的明白了多谢解答

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
