### ISSUE TITLE
关于图像数据增广

### ISSUE THREAD

**Issue by zhangmianhongni** [PaddlePaddle/PaddleFormers#834]
我看PaddleClas有图像数据增广相关的API，但是使用PaddleHub的迁移学习的时候，发现并没有图像数据增广相关的功能，请问如何在hub的finetune api下面引入图像数据增广呢？

**Comment by haoyuying** [comment]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
目前PaddleHub已实现您提出的需求，请安装PaddleHub>=1.7.0, PaddlePaddle>=1.8.0快速体验。请您在定义ImageClassificationReader任务时增加data_augmentation=True选项，即可实现数据增广功能，示例如下：

    data_reader = hub.reader.ImageClassificationReader(
        image_width=module.get_expected_image_width(),
        image_height=module.get_expected_image_height(),
        images_mean=module.get_pretrained_images_mean(),
        images_std=module.get_pretrained_images_std(),
        data_augmentation=True, #将data_augmentation选项设置为True
        dataset=dataset)
对于数据增广处理代码细则，请参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/paddlehub/io/augmentation.py

**Comment by haoyuying** [comment]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
目前PaddleHub已实现您提出的需求，请安装PaddleHub>=1.7.0, PaddlePaddle>=1.8.0快速体验。请您在定义ImageClassificationReader任务时增加data_augmentation=True选项，即可实现数据增广功能，示例如下：

data_reader = hub.reader.ImageClassificationReader(
    image_width=module.get_expected_image_width(),
    image_height=module.get_expected_image_height(),
    images_mean=module.get_pretrained_images_mean(),
    images_std=module.get_pretrained_images_std(),
    data_augmentation=True, #将data_augmentation选项设置为True
    dataset=dataset)
对于数据增广处理代码细则，请参考https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/paddlehub/io/augmentation.py
后续我们会将数据增强的方式开放出来，让用户自行设置，敬请期待。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
