### ISSUE TITLE
能否提供一个将PaddleHub FineTune保存起来的模型在AIStudio上部署的示例

### ISSUE THREAD

**Issue by onewaymyway** [PaddlePaddle/PaddleFormers#835]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：

- 您想要增加什么新特性？
AIStudio上有个可以将训练得到的模型，在线部署的功能，详情可以参见https://ai.baidu.com/ai-doc/AISTUDIO/bk3e382cq
但是由于Erinie类模型的特殊性，不能像那些简单输入的模型那样简单的部署，希望PaddleHub能和AIStudio交流一下，看看怎么能让PaddleHubFineTune出来的模型也能方便的在AIStudio上在线部署与预测。

- 什么样的场景下需要该特性？
用户在AIStudio上用PaddleHub训练模型之后无需自己有服务器就可以在AIStudio上部署，然后 就能通过http请求使用模型了，这样可以大大提升PaddleHub的应用范围

- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
现在找不到现成的资料可以让用户自己折腾出来，而且其中涉及到的一些问题可能需要AIStudio那边提供新的支持，如果PaddleHub和AIStudio协调会更容易解决这个问题

- 增加该特性，PaddleHub可能需要变化的部分。
PaddleHub本身可能不需要变化，是需要AIStudio那边改

- 如果可以的话，简要描述下您的解决方案
PaddleHub的产品经理和AIStudio的产品经理一起协商一下

**Comment by Steffy-zxf** [comment]
感谢反馈！我们考虑下！

**Comment by onewaymyway** [comment]
> 感谢反馈！我们考虑下！

等你的好消息了 ：）

**Comment by Difers** [comment]
> > 感谢反馈！我们考虑下！
> 
> 等你的好消息了 ：）

您好,现在有这方面的示例了吗?

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
