### ISSUE TITLE
UnavailableError: Load operator fail to open file

### ISSUE THREAD

**Issue by zbp-xxxp** [PaddlePaddle/PaddleFormers#840]
您好，版本信息如下：
paddlehub          1.7.1
paddlepaddle       1.8.2

报错信息如下：
----------------------
Error Message Summary:
----------------------
UnavailableError: Load operator fail to open file C:\Users\郑博培\.paddlehub\modules\xception71_imagenet\model\@HUB_xception71_imagenet@entry_flow_0_branch1_weights, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (D:\1.8.2\paddle\paddle/fluid/operators/load_op.h:41)
  [operator < load > error]

问题描述：
使用PaddleHub的图像 - 图像分类：xception71_imagenet时，安装完这个模型，在调用的时候报了以上错

**Comment by haoyuying** [comment]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
您出现的问题是由于存放hub module中存在中文字符导致的，C:\Users\郑博培.paddlehub\modules\xception71_imagenet\model，因此，推荐您修改${HUB_HOME}环境变量。请根据不同的操作系统修改环境变量后，重新安装您需要的hub模型，hub命令行操作指南为https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/cmdintro.md

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
