### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by thailand88** [PaddlePaddle/PaddleFormers#841]
我用的是resnet_v2_50_imagenet预训练模型，
默认配置
task = hub.ImageClassifierTask(
    data_reader=data_reader,
    feed_list=feed_list,
    feature=feature_map,
    num_classes=dataset.num_labels,
    config=config)
作分类任务。
请问，对于RESNET50模型固定的是那些层，fine-tune的是那个层？
对于paddlehub相关的fine-tune老师有没有推荐的文章或者参考资料，麻烦推荐一下，谢谢。
还有，我怎么没有找到paddlehub API的手册在哪里？能不能发个链接，多谢了。

欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

**Comment by haoyuying** [comment]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
目前PaddleHub中提供分类模型finetune，固定的是全连阶层之前的卷积层，finetune的是resnet全连接层部分。PaddleHub API及学习的参考资料可以参考https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.8/docs/tutorial。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
