### ISSUE TITLE
用PaddleHub和ernie模型训练了一个文本四分类模型，然后根据https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.0.0/demo/text-classification/predict.py进行预测，为何每次预测结果都不一样，也没有显示accuarcy

### ISSUE THREAD

**Issue by lllyyyqqq** [PaddlePaddle/PaddleFormers#85]

**Comment by Steffy-zxf** [comment]
感谢反馈！想确认下，
1. 运行预测脚本predict.py时是否指定了Fintune时保存的checkpoint。
2. 预测脚本只显示了预测样本的相应结果。若是想知道预测的accauray，可以仿照我们提供的数据集的相应格式整理自定义数据集，按照如下说明，可以将自定义数据集加载到PaddleHub中。   
https://github.com/PaddlePaddle/PaddleHub/wiki/PaddleHub%E9%80%82%E9%85%8D%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E5%AE%8C%E6%88%90FineTune
之后，在FineTune时，通过task.finetune()接口可以得倒dev、test set的accuarcy。

**Comment by lllyyyqqq** [comment]
1.已指定finetune后的checkpoint目录，如下
parser.add_argument("--checkpoint_dir", type=str, default="ckpt_20190719144307/best_model", help="Directory to model checkpoint")
2. finetune时的确输出了accuracy，表现正常。

**Comment by Steffy-zxf** [comment]
1. finetune时保存的checkpoint文件，不仅保存了fintune时的模型参数文件，并且保存了相应的meta数据（记录训练的轮次等信息）。所以预测时指定的checkpoint目录应保持与finetune时一致，如上例中应该为：
parser.add_argument("--checkpoint_dir", type=str, default="ckpt_20190719144307", help="Directory to model checkpoint")
2. 预测脚本只显示了预测样本的相应结果。若是想得到分类acc，
方法1: 如我上次回复中第2点。
方法2: 在predict.py脚本中写一个计算分类acc的方法

**Comment by lllyyyqqq** [comment]
谢谢，解决了
