### ISSUE TITLE
faster_rcnn_resnet50_fpn_venus用不了了

### ISSUE THREAD

**Issue by phigzen** [PaddlePaddle/PaddleFormers#851]
1）版本PaddleHub1.8.4，PaddlePaddle1.7.1
2）centos7下运行  hub run faster_rcnn_resnet50_fpn_venus --input_path "test.jpg"
报错
ERROR! Module faster_rcnn_resnet50_fpn_venus is not executable

**Comment by haoyuying** [comment]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
目前faster_rcnn_resnet50_fpn_venus模型只支持finetune，不支持一键预测。对比于其他通用检测模型，使用该Module进行finetune，可以更快收敛，达到较优效果。欢迎您使用该模型finetune接口获取自己训练的模型。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
