### ISSUE TITLE
目标检测的图片保存结果有误

### ISSUE THREAD

**Issue by phigzen** [PaddlePaddle/PaddleFormers#852]
版本PaddleHub1.8.4，PaddlePaddle1.7.1
使用yolov3_darknet53_vehicles来做目标检测，调用object_detection，images值为一个list，list内有多个img数组，output_dir 内生成的图片， 有很多目标框画的位置明显不正确，查看该方法返回值，res 内值是正常的

**Comment by haoyuying** [comment]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
您好，请问您使用的yolov3_darknet53_vehicles模型版本是什么呢，是否方便把测试图片发给我们，谢谢。

**Comment by phigzen** [comment]
版本是1.0.1，图片很多不便发送，我是一次读取成千上万图片调用object_detection方法

**Comment by haoyuying** [comment]
您好，您可以发过来错误的一张典型的图，我们可以用于复现模型问题，谢谢。

**Comment by phigzen** [comment]
![image_numpy_48](https://user-images.githubusercontent.com/31277407/92191552-a6d98600-ee96-11ea-899c-ac26d3367967.jpg)

**Comment by phigzen** [comment]
找几张图组成一个列表，看保存的检测结果就知道了

**Comment by haoyuying** [comment]
好的，我们会尽快测试回答您的问题，感谢您对PaddleHub的贡献！

**Comment by haoyuying** [comment]
您好，请使用最新版yolov3_darknet53_vehicles体验车辆检测，安装代码为hub install yolov3_darknet53_vehicles==1.0.1，我尝试利用您发的图片去检测新版本效果，结果如下
![image](https://user-images.githubusercontent.com/35907364/92205509-6ab71d00-eeb8-11ea-9a5f-611dbdd15af6.png)，

**Comment by haoyuying** [comment]
您好，请使用最新版yolov3_darknet53_vehicles体验车辆检测，安装代码为hub install yolov3_darknet53_vehicles==1.0.1，我尝试利用您发的图片去检测新版本效果，结果如下，请忽略您原图中的原始框，新增的框才是检测结果。
![image](https://user-images.githubusercontent.com/35907364/92205688-c8e40000-eeb8-11ea-8693-c7eac6b0ff5c.png)

**Comment by phigzen** [comment]
你没弄懂我的意思，希望你能认真看我的描述

**Comment by haoyuying** [comment]
同学您好，您方便加一下微信吗，我们来讨论下这个问题，我在本地测试的图片用list结果也是没问题的，建议您看下您img读入是不是cv2读入的。
![image](https://user-images.githubusercontent.com/35907364/92209910-64c53a00-eec0-11ea-92c8-98975d9cb0c1.png)

**Comment by phigzen** [comment]
代码大概这样子
`    ii = 0
    while ii < len(jsdata):
            filepath = os.path.join(datadir, jsdata[ii][0])
            img = cv2.imread(filepath)
            list_input.append(img)
            tmp = vehicles_detector.object_detection(images=list_input,visualization=True)
            ii += 1`
检测结果，框的位置好像没问题（没有一个一个对比），但保存图片里面，框的位置和对应的图是不匹配的，可能保存图片时，所使用的图片array并不是对应的array

**Comment by haoyuying** [comment]
![image](https://user-images.githubusercontent.com/35907364/92215404-4b73bc00-eec7-11ea-8c5f-01b48a9a0e28.png)
欢迎加飞桨小哥哥微信。备注hub即可，快到碗里来吧！

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
