### ISSUE TITLE
SKEP模型可指定GPU，批量预测

### ISSUE THREAD

**Issue by izhx** [PaddlePaddle/PaddleFormers#854]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
  - SKEP模型可以在指定GPU运行。现在只能在`CUDA_VISIBLE_DEVICES`的第0个，且方式很简陋。
  - SKEP模型批量预测。现在的`predict_sentiment`方法输入是句子list，方法内部竟然又遍历list单个预测？没懂这操作，如果有什么特殊限制麻烦告知，有点好奇
- 什么样的场景下需要该特性？
  - 大量文本的情感分析加速，一个项目有百万级句子，要多张卡一起跑。
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
  - 能，太慢了，显存利用太少。
- 增加该特性，PaddleHub可能需要变化的部分。
  - 文件`PaddleHub/hub_module/modules/text/sentiment_analysis/ernie_skep_sentiment_analysis/module.py`，`ErnieSkepSentimentAnalysis`类。
- 如果可以的话，简要描述下您的解决方案
  - 指定GPU的，貌似在`_set_config`方法增加个参数即可，就别`int(os.environ["CUDA_VISIBLE_DEVICES"][0])`了。。。然后，把GPU ID绑定在实例上，`predict_sentiment`的额外检查也相应更改。
  - batch预测的不知道，需要学学paddle。

**Comment by izhx** [comment]
batch也找到原因了。。。。

`_convert_text_to_feature`，明明可以pad成batch，就生要处理单句，可能有自己的考虑把。。。

**Comment by Steffy-zxf** [comment]
@izhx 你好！

使用GPU的话，在运行程序之前通过设置`CUDA_VISIBLE_DEVICES`环境变量可以直接指定GPU卡号，如linux系统可以通过`export CUDA_VISIBLE_DEVICES=2`可以指定使用2号卡。

没有batch预测是因为Paddle高阶预测API [PaddlePredictor](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/python_infer_cn.html)支持单条数据预测。

**Comment by izhx** [comment]
@Steffy-zxf 感谢你的回复！但全是废话。
1. 我知道可以用环境变量指定GPU，我也是这么用的。
但是代码中`int(os.environ["CUDA_VISIBLE_DEVICES"][0])`就很烂，不自由。所以想提建议，加载时像pytorch一样自由指定设备。
2. “没有batch预测。。”这句话。。。我竟无言以对
我改成batch之后，确实发现提速并不多，原始API跑16句约`0.7~0.8s`，跑16的batch用10G显存约`0.6~0.7s`。
既然是单句预测，那接口就别输入`list`欺骗感情了嘤嘤嘤

我简单修改代码之后也达到了想要的目的，经过实践后发现并不是质的提升，这两项提议貌似也无关紧要，但还是希望能为paddlehub提出使用建议，改善用户体验。

SKEP是一篇很好的工作，如果配合paddlehub方便好用的API，相信一定影响深远，大家也会越来越喜欢paddle生态。
好像senta烂尾了，这里至少还能用，很感谢你们的努力！

**Comment by Steffy-zxf** [comment]
> 我简单修改代码之后也达到了想要的目的，经过实践后发现并不是质的提升，这两项提议貌似也无关紧要，但还是希望能为paddlehub提出使用建议，改善用户体验。

是否可以给PaddleHub 提pr贡献，改善体验呢？

**Comment by izhx** [comment]
@Steffy-zxf 感谢你的回复！好的，学习设计理念和现有代码后来献丑。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
