### ISSUE TITLE
missing 1 required positional argument: 'data'

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleFormers#855]
CentOS 7
CUDA 10.0
paddlepaddle 1.8.1.post107
paddlehub 1.7.1
face_landmark_localization==1.0.2
pyramidbox_lite_server==1.1.0

在运行下面代码时：
```
shaper = hub.Module(name="face_landmark_localization")
shaper.set_face_detector_module(hub.Module(name="pyramidbox_lite_server"))
......
detected_keypoints = shaper.keypoint_detection(images=[frame], use_gpu=True)  # frame is cv2.imread() object
```

出现以下错误：

> W0827 03:06:23.397197 50265 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.0, Runtime API Version: 10.0
> W0827 03:06:23.401690 50265 device_context.cc:260] device: 0, cuDNN Version: 7.6.
> [2020-08-27 03:06:25,641] [    INFO] - Installing face_landmark_localization module
> [2020-08-27 03:06:25,739] [    INFO] - Module face_landmark_localization already installed in /home/scc/.paddlehub/modules/face_landmark_localization
> [2020-08-27 03:06:25,740] [    INFO] - Installing ultra_light_fast_generic_face_detector_1mb_640 module
> [2020-08-27 03:06:25,753] [    INFO] - Module ultra_light_fast_generic_face_detector_1mb_640 already installed in /home/scc/.paddlehub/modules/ultra_light_fast_generic_face_detector_1mb_640
> [2020-08-27 03:06:26,325] [    INFO] - Installing pyramidbox_lite_server module
> [2020-08-27 03:06:26,355] [    INFO] - Module pyramidbox_lite_server already installed in /home/scc/.paddlehub/modules/pyramidbox_lite_server
> Process Process-3:
> Traceback (most recent call last):
>   File "/home/scc/anaconda3/envs/paddle/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/home/scc/anaconda3/envs/paddle/lib/python3.7/multiprocessing/process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "get_infer_results_pp.py", line 205, in infer_process
>     detected_keypoints = shaper.keypoint_detection(images=[frame], use_gpu=True)  # BGR mode, need by paddlehub
>   File "/home/scc/.paddlehub/modules/face_landmark_localization/module.py", line 141, in keypoint_detection
>     for yield_data in reader(self.face_detector, images, paths, use_gpu):
>   File "/home/scc/.paddlehub/modules/face_landmark_localization/data_feed.py", line 48, in reader
>     visualization=False)):
> TypeError: __call__() missing 1 required positional argument: 'data'

请问这个是什么原因呢？

P.S.，代码里使用了多线程，这些代码都在子线程里

**Comment by Steffy-zxf** [comment]
你好！根据上述module版本信息
> face_landmark_localization==1.0.2
pyramidbox_lite_server==1.1.0

请升级pyramidbox_lite_server至1.2.0版本，
```shell
$ hub install pyramidbox_lite_server==1.2.0
```

**Comment by nihuizhidao** [comment]
感谢~的确是模型版本问题
