### ISSUE TITLE
运行sequence_label的demo报错

### ISSUE THREAD

**Issue by zj890724** [PaddlePaddle/PaddleFormers#86]
EnforceNotMet: Input ShapeTensor cannot be found in Op reshape2 at [D:\1.5.1\release_cuda97\paddle\paddle\fluid\framework\op_desc.cc:306]

不清楚是为什么？尝试了很多办法都行不通。。。求助！！！

**Comment by Steffy-zxf** [comment]
感谢反馈！PaddlePaddle版本是1.5？PaddleHub版本是多少呢？ernie module的版本是多少呢？

**Comment by nlp4whp** [comment]
同报错 = = mark下等修复

**Comment by Steffy-zxf** [comment]
@nlp4whp paddle版本是多少？Ernie module版本是多少？

**Comment by nlp4whp** [comment]
> @nlp4whp paddle版本是多少？Ernie module版本是多少？

paddlehub                1.0.2
paddlepaddle-gpu         1.5.1.post97

用bert会报错，ernire没问题的

**Comment by Steffy-zxf** [comment]
这是因为bert module 创建时paddle和当前运行时paddle版本不一致导致的，试试看将paddle降级至1.4.1。这个bug我们已经在修复了。

**Comment by nlp4whp** [comment]
> 这是因为bert module 创建时paddle和当前运行时paddle版本不一致导致的，试试看将paddle降级至1.4.1。这个bug我们已经在修复了。

好的蟹蟹

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddleHub的支持!
