### ISSUE TITLE
只要是后导入hub的模型就会报segmentation fault (core dumped)

### ISSUE THREAD

**Issue by liuchenbaidu** [PaddlePaddle/PaddleFormers#861]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

my_model = mytensorflow_model()
 model = hub.Module(name="emotion_detection_textcnn")

**Comment by Steffy-zxf** [comment]
你好！请检查paddle是否安装正确，paddle安装指南：https://www.paddlepaddle.org.cn/install/quick

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
