### ISSUE TITLE
口罩检测中的口罩分类模型的数据预处理是什么？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleFormers#863]
```python
import paddlehub as hub

module = hub.Module(name="pyramidbox_lite_mobile_mask")
# 将模型保存在test_program文件夹之中
module.processor.save_inference_model(dirname="test_program")
```

我使用了其他的模型完成了人脸检测，

我想使用其导出的口罩分类模型做口罩检测，请问这个模型的预处理是什么？例如要对检测的人脸做什么裁剪，均值、方差是什么？

**Comment by haoyuying** [comment]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
口罩检测项目的预处理包括图像的剪裁，归一化等处理，具体操作可参见下方链接中reader（）函数部分的处理。
https://github.com/PaddlePaddle/PaddleHub/blob/91d03798b2199a9521f264cf9e11039d02ee8843/hub_module/modules/image/face_detection/pyramidbox_lite_mobile_mask/data_feed.py
