### ISSUE TITLE
ernie_pointwise_matching.py文本匹配demo出错

### ISSUE THREAD

**Issue by dickobe** [PaddlePaddle/PaddleFormers#864]
paddlehub: 1.8.2  PaddlePaddle: 1.8.3.post97  
系统：linux  python3.6
执行demo时报错  cmd: 
![image](https://user-images.githubusercontent.com/9254170/91708884-88347000-ebb4-11ea-9670-092ed28ea424.png)

![image](https://user-images.githubusercontent.com/9254170/91709297-21638680-ebb5-11ea-881c-ff7c1c09e5ce.png)

![image](https://user-images.githubusercontent.com/9254170/91702513-6da9c900-ebab-11ea-9240-0c6c0029bb3e.png)

**Comment by Steffy-zxf** [comment]
你好！我运行demo正常，没能复现你的错误。请问有对demo修改吗？ 另外可以参考匹配任务教程：https://aistudio.baidu.com/aistudio/projectdetail/705526

**Comment by dickobe** [comment]
> 你好！我运行demo正常，没能复现你的错误。请问有对demo修改吗？ 另外可以参考匹配任务教程：https://aistudio.baidu.com/aistudio/projectdetail/705526

问下预测的时候很慢是什么原因呢，有使用gpu，但和不使用区别不大

> 你好！我运行demo正常，没能复现你的错误。请问有对demo修改吗？ 另外可以参考匹配任务教程：https://aistudio.baidu.com/aistudio/projectdetail/705526



> 你好！我运行demo正常，没能复现你的错误。请问有对demo修改吗？ 另外可以参考匹配任务教程：https://aistudio.baidu.com/aistudio/projectdetail/705526

**Comment by dickobe** [comment]
> 你好！我运行demo正常，没能复现你的错误。请问有对demo修改吗？ 另外可以参考匹配任务教程：https://aistudio.baidu.com/aistudio/projectdetail/705526
问下预测的时候速度很慢是什么原因呢，有使用gpu，但貌似和不使用的区别不大

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
