### ISSUE TITLE
文本分类采用bert模型，在finetune_and_eval()报错。

### ISSUE THREAD

**Issue by glsoon** [PaddlePaddle/PaddleFormers#87]
数据集为chnsenticorp   
 module = hub.Module(name="bert_chinese_L-12_H-768_A-12")
.....
cls_task.finetune_and_eval()
运行报错：

  File "/home/*****/.local/lib/python3.6/site-packages/paddle/fluid/backward.py", line 310, in _append_backward_ops_
    op.desc, cpt.to_text(no_grad_dict[block.idx]), grad_sub_block_list)

EnforceNotMet: Input ShapeTensor cannot be found in Op reshape2 at [/paddle/paddle/fluid/framework/op_desc.cc:306]
PaddlePaddle Call Stacks: 
0       0x7f63a310b650p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352

**Comment by Steffy-zxf** [comment]
感谢反馈！PaddlePaddle版本是多少呢？

**Comment by glsoon** [comment]
您好，panddle 和paddlehub version 如下：
paddlehub (1.0.1)
paddlepaddle (1.5.1)






------------------ 原始邮件 ------------------
发件人: "Steffy-zxf"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 下午4:03
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com>;
抄送: "巩乐"<glsoon@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/PaddleHub] 文本分类采用bert模型，在finetune_and_eval()报错。 (#87)




感谢反馈！PaddlePaddle版本是多少呢？

**Comment by Steffy-zxf** [comment]
btw， 您把参数use_pyreader设置为False了吗？可以尝试use_pyreader=True。另外该问题，我们正在修复。

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddleHub的支持!
