### ISSUE TITLE
执行完ocr.recognize_text()之后，内存没有释放，导致后面会内存溢出，请问怎么解决？

### ISSUE THREAD

**Issue by luomix** [PaddlePaddle/PaddleFormers#871]
1)PaddleHub和PaddlePaddle版本：PaddleHub1.8.2，PaddlePaddle1.8.4
2)系统环境：window7，python3.6，PyCharm2018.3.3

问题：执行完ocr.recognize_text()之后，内存没有释放，导致后面会内存溢出，请问怎么解决？
![image](https://user-images.githubusercontent.com/23301913/91962798-9fec2f80-ed3f-11ea-9190-f7d02e5e07d6.png)
![image](https://user-images.githubusercontent.com/23301913/91962825-a5497a00-ed3f-11ea-98c9-2deeb232e86d.png)

**Comment by Steffy-zxf** [comment]
你好！请参考issue https://github.com/PaddlePaddle/PaddleHub/issues/682

**Comment by luomix** [comment]
谢谢，有计划大概什么时候更新吗？

**Comment by Steffy-zxf** [comment]
预计需要等Paddle 2.0版本正式发出

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Comment by startfromzero0** [comment]
> 你好！请参考issue #682

您好，我用的suse系统，paddlepaddle用的2.1，安装的是CPU版本的，使用的server模型，在连续识别多张图片后，内存使用占到10个G左右，比使用以前的版本多了很多，请问是怎么回事呢？
