### ISSUE TITLE
调用Senta_lstm生成新module后报I/O错误

### ISSUE THREAD

**Issue by KW213** [PaddlePaddle/PaddleFormers#873]
环境：windows10, paddlepaddle1.7.0，paddlehub1.6.2
![报错1](https://user-images.githubusercontent.com/31813915/92089195-67f8f100-ee00-11ea-9d0e-6e286a27940a.png)

在报错的497行处加print输出参数完全无法输出
![错误3](https://user-images.githubusercontent.com/31813915/92089472-c6be6a80-ee00-11ea-862c-247587b38db5.png)
![错误4](https://user-images.githubusercontent.com/31813915/92089481-c8882e00-ee00-11ea-8e5a-6508544c433f.png)

之后审核代码
发现如下语句，删除后没问题
![报错2](https://user-images.githubusercontent.com/31813915/92089351-a098ca80-ee00-11ea-97dd-3168baf363d9.png)
此语句在别的module也使用过，能正常使用，但在本module中报错。
且会牵连hub install服务

**Comment by ShenYuhan** [comment]
您好，请问这段代码的目的是什么。
可以提供下您的模型吗

**Comment by chunzhang-hub** [comment]
@KW213 Hi，同学你好哈~我是hub这边的产品同学，想了解下咱们基于senta_lstm组建的新module是什么场景呢，可以和我们这边聊聊嘛~我的微信号：zxy8811666 😁😁
