### ISSUE TITLE
关于自定义数据集的predict.tsv

### ISSUE THREAD

**Issue by Briskyu** [PaddlePaddle/PaddleFormers#876]
您好，我按照官方的教程，在一项NLP任务的自定义数据集中添加了predict.tsv，并且正常训练了ERNIE模型。请问预测结果在哪里可以看到？谢谢！

**Comment by Steffy-zxf** [comment]
你好！预测结果需要调用task.predict接口返回预测结果。参考代码：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/demo/text_classification/predict.py#L90

**Comment by Briskyu** [comment]
> 你好！预测结果需要调用task.predict接口返回预测结果。参考代码：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.7/demo/text_classification/predict.py#L90

谢谢您！这么似乎自定义数据集中的predict.tsv文件似乎没有起到什么作用啊，我以为模型会自动地读取predict.tsv中的数据并进行预测~

**Comment by goPikachu88** [comment]
我也有类似的疑问！从参考代码来看我需要单独写一个读取predict.tsv的函数，predict的结果也需要自定义函数保存？

虽然自己写也不是很麻烦，但是既然在Dataset类里指定了predict_file参数，reader里应该已经读入了predict.tsv examples，为什么task里又要求手动将data传入predict()呢？

https://github.com/PaddlePaddle/PaddleHub/blob/d9293a3f8ae0dce9ccd26c71ffbddfff20769e82/paddlehub/finetune/task/base_task.py#L326
https://github.com/PaddlePaddle/PaddleHub/blob/d9293a3f8ae0dce9ccd26c71ffbddfff20769e82/paddlehub/finetune/task/base_task.py#L1125


Traceback (most recent call last):
  File "predict.py", line 111, in <module>
    run_states = cls_task.predict()
TypeError: predict() missing 1 required positional argument: 'data'

**Comment by Steffy-zxf** [comment]
@ardellelee @Briskyu 你好！感谢反馈！请先将预测数据传入`task.predict`接口data参数进行预测。dataset中预测数据将会在PaddleHub未来版本优化！

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
