### ISSUE TITLE
ExternalError:  Cudnn error, CUDNN_STATUS_INTERNAL_ERROR  at (/paddle/paddle/fluid/platform/device_context.h:165)

### ISSUE THREAD

**Issue by xiaotaiyangsun** [PaddlePaddle/PaddleFormers#878]
例如PaddleHub1.8.2，PaddlePaddle1.8.2
**linux报错**请问如何解决
W0904 19:14:44.950731  1153 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.0
W0904 19:14:44.954766  1153 device_context.cc:260] device: 0, cuDNN Version: 7.6.

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_INTERNAL_ERROR  at (/paddle/paddle/fluid/platform/device_context.h:165)

**Comment by xiaotaiyangsun** [comment]
> W0904 19:14:44.950731 1153 device_context.cc:252] Please NOTE: dev

运行pointwise_text_matching

**Comment by Steffy-zxf** [comment]
你好！根据错误提示，应该是cudnn没有安装正确，参考[paddle安装指南](https://www.paddlepaddle.org.cn/install/quick)

**Comment by xiaotaiyangsun** [comment]
> 你好！根据错误提示，应该是cudnn没有安装正确，参考[paddle安装指南](https://www.paddlepaddle.org.cn/install/quick)



> 你好！根据错误提示，应该是cudnn没有安装正确，参考[paddle安装指南](https://www.paddlepaddle.org.cn/install/quick)

paddle安装指南要求：GPU 版本的 PaddlePaddle 需要使用 cuDNN 7.6+ 版本；
我安装的版本：cuDNN Version: 7.6.**报错**
aistudio平台版本，cuDNN Version: 7.64.，正常

**Comment by xiaotaiyangsun** [comment]
> > 你好！根据错误提示，应该是cudnn没有安装正确，参考[paddle安装指南](https://www.paddlepaddle.org.cn/install/quick)
> 
> > 你好！根据错误提示，应该是cudnn没有安装正确，参考[paddle安装指南](https://www.paddlepaddle.org.cn/install/quick)
> 
> paddle安装指南要求：GPU 版本的 PaddlePaddle 需要使用 cuDNN 7.6+ 版本；
> 我安装的版本：cuDNN Version: 7.6.**报错**
> aistudio平台版本，cuDNN Version: 7.64.，正常

奇怪，上周报错，这周我的环境都没有改，正常出结果了。请问什么原因？

**Comment by Steffy-zxf** [comment]
> 奇怪，上周报错，这周我的环境都没有改，正常出结果了。请问什么原因？

当时运行时，指定使用的GPU是否有别的进程占满显存了呢？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
