### ISSUE TITLE
PaddleHub 进行图像分类迁移报错

### ISSUE THREAD

**Issue by cisco08** [PaddlePaddle/PaddleFormers#88]
运行图像分类的示例notebiok报错
58     # Step 4: load pretrained parameters
     59     place = fluid.CUDAPlace(0)
AttributeError: 'ClassifierTask' object has no attribute 'inference_program

**Comment by nepeplwu** [comment]
@cisco08 ，请问参照的是哪份示例？paddlehub版本是多少？

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddleHub的支持!
