### ISSUE TITLE
regularization_handler中一处地方存疑

### ISSUE THREAD

**Issue by TyrionZK** [PaddlePaddle/PaddleFormers#882]
参数更新不应该是 update_param=param-grad  *lr * weight_decay吗？为什么下面链接中grad为param_list[param.name]呢？
https://github.com/PaddlePaddle/PaddleHub/blob/d9293a3f8ae0dce9ccd26c71ffbddfff20769e82/paddlehub/finetune/strategy.py#L454

**Comment by kinghuin** [comment]
Hi, 欢迎提问。 
https://github.com/PaddlePaddle/PaddleHub/blob/d9293a3f8ae0dce9ccd26c71ffbddfff20769e82/paddlehub/finetune/strategy.py#L441

参考[Paddle API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/optimizer_cn/AdamOptimizer_cn.html#minimize-loss-startup-program-none-parameter-list-none-no-grad-set-none)

这里已经执行了梯度更新

后面是weight decay操作
