### ISSUE TITLE
能否增加一个在NLP FineTune任务里增加对抗训练的DEMO

### ISSUE THREAD

**Issue by onewaymyway** [PaddlePaddle/PaddleFormers#883]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
增加一个在NLP FineTune任务里增加对抗训练的DEMO
- 什么样的场景下需要该特性？
对抗训练在很多任务上能提升最终效果，希望能把对抗训练也加到PaddleHub的训练框架里，对抗训练相关的资料可以参考https://spaces.ac.cn/archives/7234
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
如果不内置这个功能，普通用户很难自己通过改Task简单的改出来
- 增加该特性，PaddleHub可能需要变化的部分。
将对抗训练功能内置，对外暴露一个简单的参数接口
- 如果可以的话，简要描述下您的解决方案
将对抗训练功能内置，对外暴露一个简单的参数接口

**Comment by Steffy-zxf** [comment]
你好！该需求，我们会考虑支持！感谢反馈！

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
