### ISSUE TITLE
ExternalError:  Cublas error, CUBLAS_STATUS_NOT_INITIALIZED 

### ISSUE THREAD

**Issue by xiaotaiyangsun** [PaddlePaddle/PaddleFormers#885]
paddlehub paddlepaddke 均为1.8.2
在自己的linux运行ernie_pointwise_matching.py。修改了
module = hub.Module(name="ernie")
为
 module = hub.Module(directory="../ernie")
其他没有变
报如下错误，请问如何解决
ExternalError:  Cublas error, CUBLAS_STATUS_NOT_INITIALIZED  at (/paddle/paddle/fluid/platform/cuda_helper.h:32)

**Comment by Steffy-zxf** [comment]
你好！根据错误提示，是运行环境中cuda配置有问题，请根据paddle安装教程检查paddle是否安装正确：https://www.paddlepaddle.org.cn/install/quick

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
