### ISSUE TITLE
PaddleHub 在启动添加模型时发生错误

### ISSUE THREAD

**Issue by lagelanhai** [PaddlePaddle/PaddleFormers#886]
目前在学习PaddleORC ， 在使用PaddleHub 过程中 ， 当启动 PaddleHub时 
![1](https://user-images.githubusercontent.com/52648575/92677390-53fc4480-f356-11ea-84ea-ccdb40ff9179.jpg)
会出现当前这个问题，但我并没有在 -m 参数后加入 ocr_system 这个model  ,并且我把 ocr_system  删除后 可以正常启动，或者 注释掉 ocr_system/module.py  中的 21行 22行  后，也可以启动成功， 这是不是互相兼容的问题 ，还是我没正确使用
附 
![2](https://user-images.githubusercontent.com/52648575/92677694-fa484a00-f356-11ea-91bd-f030e4b94e22.jpg)

**Comment by Steffy-zxf** [comment]
你好！`ocr_system` module 是根据 [PaddleOCR 服务部署文档](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_ch/serving.md#1-%E5%87%86%E5%A4%87%E7%8E%AF%E5%A2%83)创建的module吗 ？ 如果是的话，需要先将ocr repo路径加入python的模块搜索路径。如
```shell
$ export PYTHONPATH=Path/to/PaddleOCR/Repo
```

**Comment by Steffy-zxf** [comment]
你好好，此issue在近两月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
