### ISSUE TITLE
预测输出nan可能是什么原因呢

### ISSUE THREAD

**Issue by TyrionZK** [PaddlePaddle/PaddleFormers#887]
在进行文本分类任务时，加载模型正常，数据输入经检查也正常，但是预测输出nan（下面一句输出），可能是什么原因呢？怎么查找呢？苦闷啊
https://github.com/PaddlePaddle/PaddleHub/blob/d9293a3f8ae0dce9ccd26c71ffbddfff20769e82/paddlehub/finetune/task/base_task.py#L1078

**Comment by TyrionZK** [comment]
我做了对照试验：同样的程序，同样的conda环境，换了台机器预测就变成nan了，很苦闷

**Comment by kinghuin** [comment]
请问分别是什么机器呢，有没有尝试过指定predict的accelerate_mode参数为False呢？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
