### ISSUE TITLE
PaddleHub图像分类迁移教程错误

### ISSUE THREAD

**Issue by foreversolar** [PaddlePaddle/PaddleFormers#89]
首先感谢这份教程，十分的完善清楚
但是在最后一步预测的时候是不是漏了一句
    run_states = task.predict(data=data)
    results = [run_state.run_results for run_state in run_states]

**Comment by Steffy-zxf** [comment]
感谢反馈！由于更新Task类，wiki文档没有及时更新，现已更新。
