### ISSUE TITLE
使用Paddlehub推理时RuntimeError: Request Hub-Server unsuccessfully, please check your network.

### ISSUE THREAD

**Issue by wangjc7** [PaddlePaddle/PaddleFormers#891]
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.8.2，PaddlePaddle1.8.4.post107
2）系统环境：请您描述系统类型:CentOS7.7，python版本:3.6.9
- 复现信息：
使用Paddlehub训练好的模型放到无外网机器上进行推理时，报如下错误：
Request Hub-Server unsuccessfully.
[2020-09-12 06:59:57,212] [    INFO] - Installing bert_chinese_L_12_H_768_A_12 module
[2020-09-12 06:59:57,223] [   ERROR] - Request Hub-Server unsuccessfully, please check your network.
Traceback (most recent call last):
  File "predict.py", line 44, in <module>
    module = hub.Module(name="bert_chinese_L_12_H_768_A_12")
  File "/usr/local/python3/lib/python3.6/site-packages/paddlehub/module/module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/paddlehub/module/module.py", line 174, in init_with_name
    raise RuntimeError(tips)
RuntimeError: Request Hub-Server unsuccessfully, please check your network.
预训练模型已经放到.paddlehub下了 但还是提示这个
![image](https://user-images.githubusercontent.com/30836214/92993676-0a625400-f526-11ea-96c0-a8c72d348bc9.png)
尝试设置${HUB_HOME}环境变量 export HUB_HOME=/home/chapterix后，再次尝试也无效
![image](https://user-images.githubusercontent.com/30836214/92993699-4bf2ff00-f526-11ea-8887-2c69fd57a2d2.png)

请帮忙解决~

**Comment by Steffy-zxf** [comment]
你好！刚问题已线下沟通解决，现就此关闭该问题。如有需要，可以重新开启。

**Comment by Devindan** [comment]
解决方法是什么啊？同样的情况，同样的问题，为啥不能提一下解决方法呢？头疼

**Comment by 1253970836** [comment]
> 解决方法是什么啊？同样的情况，同样的问题，为啥不能提一下解决方法呢？头疼

你好，问题解决了吗，我也遇到这样的问题了

**Comment by 1253970836** [comment]
> 你好！刚问题已线下沟通解决，现就此关闭该问题。如有需要，可以重新开启。

你好，能告诉下解决方法吗，谢谢

**Comment by Devindan** [comment]
> > 解决方法是什么啊？同样的情况，同样的问题，为啥不能提一下解决方法呢？头疼
> 
> 你好，问题解决了吗，我也遇到这样的问题了

你好，我最后是发现我调用的模型其实是基于另一个模型的，但是说明文档上没有明确说明这一点，我只安装了一个模型，所以paddleHub会一直尝试联网下载前置模型。
你可以仔细看看你的模型是不是没有安装，或者缺少前置模型，目前paddleHub不会提示缺少模型，而是直接联网下载，不能联网就提示Request Hub-Server unsuccessfully, please check your network.

**Comment by 1253970836** [comment]
好的，多谢，可能也是确少前置模型，我再去看看，谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Devin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月17日(星期四) 下午4:48
收件人:&nbsp;&quot;PaddlePaddle/PaddleHub&quot;<PaddleHub@noreply.github.com&gt;;
抄送:&nbsp;&quot;1253970836&quot;<1253970836@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleHub] 使用Paddlehub推理时RuntimeError: Request Hub-Server unsuccessfully, please check your network. (#891)
