### ISSUE TITLE
paddlehub使用paddlepaddle的gpu版本，可以在无gpu的机器上运行吗

### ISSUE THREAD

**Issue by dickobe** [PaddlePaddle/PaddleFormers#894]
paddlehub使用paddlepaddle的gpu版本，可以在无gpu的机器上运行吗？

**Comment by Steffy-zxf** [comment]
你好！无GPU的机器上可以安装paddle cpu版本。paddle安装指南：https://www.paddlepaddle.org.cn/install/quick

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
