### ISSUE TITLE
使用paddlehub自定义任务，具体是自定义文本分类任务中的评价指标时按照官方文档的方法做了之后报错了，请问应该如何解决？

### ISSUE THREAD

**Issue by Masterkmp** [PaddlePaddle/PaddleFormers#895]
**### 我的版本、环境信息**
1）PaddleHub 1.8.2和PaddlePaddle版本1.8.4
2）系统环境：在Windows的AiStudio网页端跑的，python版本为3.7
- 复现信息：
### **执行的操作：**
参考这里[https://github.com/PaddlePaddle/PaddleHub/wiki/%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9Task%E5%86%85%E7%BD%AE%E6%96%B9%E6%B3%95%EF%BC%9F](url)意图修改paddlehub中的hub.TextClassifierTask的默认的评价指标**_（目前是计划先按照文档把默认指标”acc"改成“f1",进而学会怎么改成macro_f1、microf1、召回率）_**，这部分代码如下：
`import numpy as np

def calculate_f1_np(preds, labels):
    # 计算F1分数
    # preds：预测label
    # labels： 真实labels
    # 返回F1分数
    preds = np.array(preds)
    labels = np.array(labels)
    tp = np.sum((labels == 1) & (preds == 1))
    tn = np.sum((labels == 0) & (preds == 0))
    fp = np.sum((labels == 0) & (preds == 1))
    fn = np.sum((labels == 1) & (preds == 0))
    p = tp / (tp + fp) if (tp + fp) else 0
    r = tp / (tp + fn) if (tp + fn) else 0
    f1 = (2 * p * r) / (p + r) if p + r else 0
    return f1

def calculate_metrics(self, run_states):
    loss_sum = acc_sum = run_examples = 0
    run_step = run_time_used = 0
    all_labels = np.array([])
    all_infers = np.array([])
    for run_state in run_states:
        run_examples += run_state.run_examples
        run_step += run_state.run_step
        loss_sum += np.mean(
            run_state.run_results[-1]) * run_state.run_examples
        acc_sum += np.mean(
            run_state.run_results[2]) * run_state.run_examples
        np_labels = run_state.run_results[0]
        np_infers = run_state.run_results[1]
        all_labels = np.hstack((all_labels, np_labels.reshape([-1])))
        all_infers = np.hstack((all_infers, np_infers.reshape([-1])))

    run_time_used = time.time() - run_states[0].run_time_begin
    avg_loss = loss_sum / run_examples
    run_speed = run_step / run_time_used

    scores = OrderedDict()
    f1 = calculate_f1_np(all_infers, all_labels)
    scores["f1"] = f1

    return scores, avg_loss, run_speed

from tb_paddle import SummaryWriter
tb_writer = SummaryWriter("PATH/TO/LOG")
def record_value(evaluation_scores, loss, s):
    tb_writer.add_scalar(
        tag="Loss_{}".format(self.phase),
        scalar_value=loss,
        global_step=self._envs['train'].current_step)
    log_scores = ""
    for metric in evaluation_scores:
        self.tb_writer.add_scalar(
            tag="{}_{}".format(metric, self.phase),
            scalar_value=scores[metric],
            global_step=self._envs['train'].current_step)
        log_scores += "%s=%.5f " % (metric, scores[metric])
    print("step %d / %d: loss=%.5f %s[step/sec: %.2f]" %
            (self.current_step, self.max_train_steps, avg_loss,
                log_scores, run_speed))

def new_log_interval_event(self, run_states)：
    print("This is the new log_interval_event!")
    scores, avg_loss, run_speed = calculate_metrics(run_states)
    record_value(scores, avg_loss, run_speed)

cls_task.delete_hook(hook_type="log_interval_event", name="default")
cls_task.add_hook(hook_type="log_interval_event", name="new_log_interval_event", func=new_log_interval_event)
cls_task.hook_info()`
**### 报错信息如下**
This is the new log_interval_event!

---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<ipython-input-10-de34726f263a> in <module>
      1 #run_states = cls_task.finetune_and_eval()
----> 2 cls_task.finetune_and_eval()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    943 
    944     def finetune_and_eval(self):
--> 945         return self.finetune(do_eval=True)
    946 
    947     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    964                 while self.current_epoch <= self.config.num_epoch:
    965                     self.config.strategy.step()
--> 966                     run_states = self._run(do_eval=do_eval)
    967                     self.env.current_epoch += 1
    968 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
   1222                 if self.is_train_phase:
   1223                     if self.current_step % self.config.log_interval == 0:
-> 1224                         self._log_interval_event(period_run_states)
   1225                         global_run_states += period_run_states
   1226                         period_run_states = []
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    708                     func(*args)
    709                 else:
--> 710                     partial(func, self)(*args)
    711 
    712         return hook_function
<ipython-input-8-8777b1d08ede> in new_log_interval_event(self, run_states)
     73     # 改写的事件方法，参数列表务必与PaddleHub内置的相应方法保持一致
     74     print("This is the new log_interval_event!")
---> 75     scores, avg_loss, run_speed = calculate_metrics(run_states)
     76     record_value(scores, avg_loss, run_speed)
     77 
TypeError: calculate_metrics() missing 1 required positional argument: 'run_states'

**Comment by Steffy-zxf** [comment]
你好！文本分类支持precision、recall、f1、acc、matthews等评价指标。用法参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/reference/task/text_classify_task.md

如果你想要修改评价指标，参考文档：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/Secondary_development/hook.md

**Comment by Masterkmp** [comment]
你好，感谢回复！还有几个问题
### 问题1：
请问[https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/reference/task/text_classify_task.md]里面的metrics_choices("default" or list ⊂ ["acc", "precision", "recall", "f1", "matthews"])是只用于二分类的吗，不能用于多分类，那么我需要改写评价指标了？
### 问题2：
metrics_choices("default" or list ⊂ ["acc", "precision", "recall", "f1", "matthews"]): 其中指定的第一个指标将被作为**主指标**用于判断当前得分是否为最佳分值。**如果我需要的指标同等重要，应该如何修改呢？**

**Comment by Masterkmp** [comment]
> 
> 
> 你好！文本分类支持precision、recall、f1、acc、matthews等评价指标。用法参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/reference/task/text_classify_task.md
> 
> 如果你想要修改评价指标，参考文档：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/Secondary_development/hook.md
你好，感谢回复！还有几个问题
问题1：

请问[https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/reference/task/text_classify_task.md]里面的metrics_choices("default" or list ⊂ ["acc", "precision", "recall", "f1", "matthews"])是只用于二分类的吗，不能用于多分类，那么我需要改写评价指标了？
问题2：

metrics_choices("default" or list ⊂ ["acc", "precision", "recall", "f1", "matthews"]): 其中指定的第一个指标将被作为主指标用于判断当前得分是否为最佳分值。如果我需要的指标同等重要，应该如何修改呢？

**Comment by Masterkmp** [comment]
> 
> 
> 你好！文本分类支持precision、recall、f1、acc、matthews等评价指标。用法参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/reference/task/text_classify_task.md
> 
> 如果你想要修改评价指标，参考文档：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/Secondary_development/hook.md
 @**你好，按照文档修改指标报错了**
### **指标修改的代码如下：**
`import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, fbeta_score
def calculate_f1_macro(preds, labels):
    # 计算f1_macro分数
    # preds：预测label
    # labels： 真实labels
    # 返回F1分数
    f1_macro=precision_score(labels, preds, average='macro')
    return f1_macro

# 自定义评估方法实现
def calculate_metrics(self, run_states):
    # run_states: list类型，每个元素是一个RunState对象，指明了该step的运行状态
    # 返回评估得分，平均损失值和平局运行速度
    loss_sum = acc_sum = run_examples = 0
    run_step = run_time_used = 0
    all_labels = np.array([])
    all_infers = np.array([])

    for run_state in run_states:
        run_examples += run_state.run_examples
        run_step += run_state.run_step
        loss_sum += np.mean(
            run_state.run_results[-1]) * run_state.run_examples
        acc_sum += np.mean(
            run_state.run_results[2]) * run_state.run_examples
        np_labels = run_state.run_results[0]
        np_infers = run_state.run_results[1]
        all_labels = np.hstack((all_labels, np_labels.reshape([-1])))
        all_infers = np.hstack((all_infers, np_infers.reshape([-1])))

    run_time_used = time.time() - run_states[0].run_time_begin
    avg_loss = loss_sum / run_examples
    run_speed = run_step / run_time_used

    scores = OrderedDict()
    f1 = calculate_f1_macro(all_infers, all_labels)
    scores["calculate_f1_macro"] = f1

    return scores, avg_loss, run_speed

# 利用自定义可视化工具tb-paddle记录训练过程中的损失值，评估指标等
from tb_paddle import SummaryWriter

tb_writer = SummaryWriter("PATH/TO/LOG")

def record_value(evaluation_scores, loss, s):
    tb_writer.add_scalar(
        tag="Loss_{}".format(self.phase),
        scalar_value=loss,
        global_step=self._envs['train'].current_step)
    log_scores = ""
    for metric in evaluation_scores:
        self.tb_writer.add_scalar(
            tag="{}_{}".format(metric, self.phase),
            scalar_value=scores[metric],
            global_step=self._envs['train'].current_step)
        log_scores += "%s=%.5f " % (metric, scores[metric])
    print("step %d / %d: loss=%.5f %s[step/sec: %.2f]" %
            (self.current_step, self.max_train_steps, avg_loss,
                log_scores, run_speed))

# 改写_log_interval_event实现
def new_log_interval_event(self, run_states):
    # 改写的事件方法，参数列表务必与PaddleHub内置的相应方法保持一致
    print("This is the new log_interval_event!")
    scores, avg_loss, run_speed = calculate_metrics(run_states)
    record_value(scores, avg_loss, run_speed)

# 利用Hook改写PaddleHub内置_log_interval_event实现，需要2步(假设task已经创建好)
# 1.删除PaddleHub内置_log_interval_event实现
# hook_type：你想要改写的事件hook类型
# name：hook名字，“default”表示PaddleHub内置_log_interval_event实现
cls_task.delete_hook(hook_type="log_interval_event", name="default")

# 2.增加自定义_log_interval_event实现(new_log_interval_event)
# hook_type：你想要改写的事件hook类型
# name: hook名字
# func：自定义改写的方法
cls_task.add_hook(hook_type="log_interval_event", name="new_log_interval_event", func=new_log_interval_event)

# 输出hook信息
cls_task.hook_info()`


**### 报错信息如下：**
`---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-10-38bfa3486979> in <module>
     73 # hook_type：你想要改写的事件hook类型
     74 # name：hook名字，“default”表示PaddleHub内置_log_interval_event实现
---> 75 cls_task.delete_hook(hook_type="log_interval_event", name="default")
     76 
     77 # 2.增加自定义_log_interval_event实现(new_log_interval_event)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in delete_hook(self, hook_type, name)
    750             name (str): the handler function name
    751         """
--> 752         self._hooks.delete(hook_type, name)
    753         logger.info("Delete hook %s:%s successfully" % (hook_type, name))
    754 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in delete(self, hook_type, name)
    180             raise ValueError(
    181                 "No hook_type: %s exists or name: %s does not exist in hook_type: %s"
--> 182                 % (hook_type, name, hook_type))
    183 
    184     def modify(self, hook_type, name, func):
ValueError: No hook_type: log_interval_event exists or name: default does not exist in hook_type: log_interval_event`
