### ISSUE TITLE
希望能增加paddhub文本多分类任务的评价指标

### ISSUE THREAD

**Issue by Masterkmp** [PaddlePaddle/PaddleFormers#896]
### **希望能增加paddhub文本多分类任务的评价指标，比如macro_f1 micro_f1 micro_recall micro_recall macro_precision micro_precision,目前paddlehub文本分类模块不支持这些指标**

- 1、这些指标用于文本多分类任务，目的是对不平衡数据集进行合理的评价
- 2、可能的解决方案
[`[`也许可以修改接口实现，参考](https://github.com/PaddlePaddle/PaddleHub/wiki/%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9Task%E5%86%85%E7%BD%AE%E6%96%B9%E6%B3%95%EF%BC%9F)。但是我根据官方文档修改后报错了，不知道怎么回事。

**Comment by Steffy-zxf** [comment]
你好！以上问题可以参考 issue 回复：https://github.com/PaddlePaddle/PaddleHub/issues/895

**Comment by Masterkmp** [comment]
> 
> 
> 你好！以上问题可以参考 issue 回复：#895

你好，您给的参考没有解决我的问题，我按照参考文档做了报错了，能否给出完整方案？

**Comment by Steffy-zxf** [comment]
你好！以上问题请参考 #901 的回复。后续问题可以在 #901 下进行讨论，此issue就此关闭。
