### ISSUE TITLE
自定义paddle_hub指标时，按照参考文档报错了，请问怎么解决？能否提供具体demo？

### ISSUE THREAD

**Issue by Masterkmp** [PaddlePaddle/PaddleFormers#901]
报错信息如下
[2020-09-16 15:10:25,693] [    INFO] - Strategy with warmup, linear decay, slanted triangle learning rate, weight decay regularization, 
/opt/conda/envs/python35-paddle120-envb/python3.7/site-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
[2020-09-16 15:10:25,756] [    INFO] - Try loading checkpoint from hub_ernie_text_cls_demo/ckpt.meta
[2020-09-16 15:10:25,756] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-09-16 15:10:25,825] [    INFO] - PaddleHub finetune start

This is the new log_interval_event!

---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<ipython-input-23-de34726f263a> in <module>
      1 #run_states = cls_task.finetune_and_eval()
----> 2 cls_task.finetune_and_eval()
/opt/conda/envs/python35-paddle120-envb/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    943 
    944     def finetune_and_eval(self):
--> 945         return self.finetune(do_eval=True)
    946 
    947     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-envb/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    964                 while self.current_epoch <= self.config.num_epoch:
    965                     self.config.strategy.step()
--> 966                     run_states = self._run(do_eval=do_eval)
    967                     self.env.current_epoch += 1
    968 
/opt/conda/envs/python35-paddle120-envb/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
   1222                 if self.is_train_phase:
   1223                     if self.current_step % self.config.log_interval == 0:
-> 1224                         self._log_interval_event(period_run_states)
   1225                         global_run_states += period_run_states
   1226                         period_run_states = []
/opt/conda/envs/python35-paddle120-envb/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    708                     func(*args)
    709                 else:
--> 710                     partial(func, self)(*args)
    711 
    712         return hook_function
<ipython-input-22-0c27e1cae3e0> in new_log_interval_event(self, run_states)
     66     # 改写的事件方法，参数列表务必与PaddleHub内置的相应方法保持一致
     67     print("This is the new log_interval_event!")
---> 68     scores, avg_loss, run_speed = calculate_metrics(run_states)
     69     record_value(scores, avg_loss, run_speed)
     70 
TypeError: calculate_metrics() missing 1 required positional argument: 'run_states'

**Comment by Masterkmp** [comment]
在paddlehub的讨论区找到类似的问题[https://ai.baidu.com/forum/topic/show/958689](url)
但是没有解答

**Comment by kinghuin** [comment]
Hi
hook的使用方式请参考https://paddlehub.readthedocs.io/zh_CN/develop/tutorial/hook.html
如您参考该文档使用仍然有误，请贴下相关代码

另外，您也可以直接继承所需Task，然后覆盖calculate_metrics方法

**Comment by Masterkmp** [comment]
> 
> 
> Hi
> hook的使用方式请参考https://github.com/PaddlePaddle/PaddleHub/wiki/%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9Task%E5%86%85%E7%BD%AE%E6%96%B9%E6%B3%95%EF%BC%9F
> 如您参考该文档使用仍然有误，请贴下相关代码
> 
> 另外，您也可以直接继承所需Task，然后覆盖calculate_metrics方法

**### 参考文档依然报错，代码如下：**
```python
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, fbeta_score
def calculate_f1_macro(preds, labels):
    f1_macro=precision_score(labels, preds, average='macro')
    return f1_macro

def calculate_metrics(self, run_states):
    loss_sum = acc_sum = run_examples = 0
    run_step = run_time_used = 0
    all_labels = np.array([])
    all_infers = np.array([])

    for run_state in run_states:
        run_examples += run_state.run_examples
        run_step += run_state.run_step
        loss_sum += np.mean(
            run_state.run_results[-1]) * run_state.run_examples
        acc_sum += np.mean(
            run_state.run_results[2]) * run_state.run_examples
        np_labels = run_state.run_results[0]
        np_infers = run_state.run_results[1]
        all_labels = np.hstack((all_labels, np_labels.reshape([-1])))
        all_infers = np.hstack((all_infers, np_infers.reshape([-1])))

    run_time_used = time.time() - run_states[0].run_time_begin
    avg_loss = loss_sum / run_examples
    run_speed = run_step / run_time_used

    scores = OrderedDict()
    f1 = calculate_f1_macro(all_infers, all_labels)
    scores["f1_macro"] = f1

    return scores, avg_loss, run_speed

from tb_paddle import SummaryWriter

tb_writer = SummaryWriter("PATH/TO/LOG")

def record_value(evaluation_scores, loss, s):
    tb_writer.add_scalar(
        tag="Loss_{}".format(self.phase),
        scalar_value=loss,
        global_step=self._envs['train'].current_step)
    log_scores = ""
    for metric in evaluation_scores:
        self.tb_writer.add_scalar(
            tag="{}_{}".format(metric, self.phase),
            scalar_value=scores[metric],
            global_step=self._envs['train'].current_step)
        log_scores += "%s=%.5f " % (metric, scores[metric])
    print("step %d / %d: loss=%.5f %s[step/sec: %.2f]" %
            (self.current_step, self.max_train_steps, avg_loss,
                log_scores, run_speed))


def new_log_interval_event(self, run_states):
    print("This is the new log_interval_event!")
    scores, avg_loss, run_speed = calculate_metrics(run_states)
    record_value(scores, avg_loss, run_speed)

cls_task.delete_hook(hook_type="log_interval_event", name="default")

cls_task.add_hook(hook_type="log_interval_event", name="new_log_interval_event", func=new_log_interval_event)

```
```
**### 上一段代码输出为：**
[2020-09-17 10:10:24,694] [    INFO] - Delete hook log_interval_event:default successfully
[2020-09-17 10:10:24,695] [    INFO] - Add hook log_interval_event:new_log_interval_event successfully
**### 在执行run_states = cls_task.finetune_and_eval()后报错，具体如下：**
```
```bash
[2020-09-17 10:10:34,224] [    INFO] - Strategy with warmup, linear decay, slanted triangle learning rate, weight decay regularization, 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
[2020-09-17 10:10:34,277] [    INFO] - Try loading checkpoint from hub_ernie_text_cls_demo/ckpt.meta
[2020-09-17 10:10:34,277] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-09-17 10:10:34,359] [    INFO] - PaddleHub finetune start

This is the new log_interval_event!

---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<ipython-input-10-33eafd68b5ee> in <module>
----> 1 run_states = cls_task.finetune_and_eval()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    943 
    944     def finetune_and_eval(self):
--> 945         return self.finetune(do_eval=True)
    946 
    947     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    964                 while self.current_epoch <= self.config.num_epoch:
    965                     self.config.strategy.step()
--> 966                     run_states = self._run(do_eval=do_eval)
    967                     self.env.current_epoch += 1
    968 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
   1222                 if self.is_train_phase:
   1223                     if self.current_step % self.config.log_interval == 0:
-> 1224                         self._log_interval_event(period_run_states)
   1225                         global_run_states += period_run_states
   1226                         period_run_states = []
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    708                     func(*args)
    709                 else:
--> 710                     partial(func, self)(*args)
    711 
    712         return hook_function
<ipython-input-9-55d0b779f714> in new_log_interval_event(self, run_states)
     66     # 改写的事件方法，参数列表务必与PaddleHub内置的相应方法保持一致
     67     print("This is the new log_interval_event!")
---> 68     scores, avg_loss, run_speed = calculate_metrics(run_states)
     69     record_value(scores, avg_loss, run_speed)
     70 
**TypeError: calculate_metrics() missing 1 required positional argument: 'run_states'**
```

**Comment by kinghuin** [comment]
请将
scores, avg_loss, run_speed = calculate_metrics(run_states)
修改为
scores, avg_loss, run_speed = calculate_metrics(self, run_states)

**Comment by Masterkmp** [comment]
> 
> 
> 请将
> scores, avg_loss, run_speed = calculate_metrics(run_states)
> 修改为
> scores, avg_loss, run_speed = calculate_metrics(self, run_states)

你好，按照你说的修改为 scores, avg_loss, run_speed = calculate_metrics(self, run_states)后，**我重启环境运行依然报错**。
报错信息如下：
`
[2020-09-17 10:39:02,377] [    INFO] - PaddleHub finetune start

This is the new log_interval_event!

---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<ipython-input-10-33eafd68b5ee> in <module>
----> 1 run_states = cls_task.finetune_and_eval()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    943 
    944     def finetune_and_eval(self):
--> 945         return self.finetune(do_eval=True)
    946 
    947     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    964                 while self.current_epoch <= self.config.num_epoch:
    965                     self.config.strategy.step()
--> 966                     run_states = self._run(do_eval=do_eval)
    967                     self.env.current_epoch += 1
    968 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
   1222                 if self.is_train_phase:
   1223                     if self.current_step % self.config.log_interval == 0:
-> 1224                         self._log_interval_event(period_run_states)
   1225                         global_run_states += period_run_states
   1226                         period_run_states = []
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    708                     func(*args)
    709                 else:
--> 710                     partial(func, self)(*args)
    711 
    712         return hook_function
<ipython-input-8-15c5678eb762> in new_log_interval_event(self, run_states)
     66     # 改写的事件方法，参数列表务必与PaddleHub内置的相应方法保持一致
     67     print("This is the new log_interval_event!")
---> 68     scores, avg_loss, run_speed = calculate_metrics(self,run_states)
     69     record_value(scores, avg_loss, run_speed)
     70 
<ipython-input-8-15c5678eb762> in calculate_metrics(self, run_states)
     31         all_infers = np.hstack((all_infers, np_infers.reshape([-1])))
     32 
---> 33     run_time_used = time.time() - run_states[0].run_time_begin
     34     avg_loss = loss_sum / run_examples
     35     run_speed = run_step / run_time_used
NameError: name 'time' is not defined`

**Comment by kinghuin** [comment]
这个错误应该是没有 import time

**Comment by Masterkmp** [comment]
> 
> 
> 这个错误应该是没有 import time

你好，添加后重启依然报错，信息如下：
`[2020-09-17 10:52:29,925] [    INFO] - Strategy with warmup, linear decay, slanted triangle learning rate, weight decay regularization, 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
[2020-09-17 10:52:29,982] [    INFO] - Try loading checkpoint from hub_ernie_text_cls_demo/ckpt.meta
[2020-09-17 10:52:29,983] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-09-17 10:52:30,061] [    INFO] - PaddleHub finetune start

This is the new log_interval_event!

---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<ipython-input-11-33eafd68b5ee> in <module>
----> 1 run_states = cls_task.finetune_and_eval()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    943 
    944     def finetune_and_eval(self):
--> 945         return self.finetune(do_eval=True)
    946 
    947     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    964                 while self.current_epoch <= self.config.num_epoch:
    965                     self.config.strategy.step()
--> 966                     run_states = self._run(do_eval=do_eval)
    967                     self.env.current_epoch += 1
    968 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
   1222                 if self.is_train_phase:
   1223                     if self.current_step % self.config.log_interval == 0:
-> 1224                         self._log_interval_event(period_run_states)
   1225                         global_run_states += period_run_states
   1226                         period_run_states = []
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    708                     func(*args)
    709                 else:
--> 710                     partial(func, self)(*args)
    711 
    712         return hook_function
<ipython-input-10-fc50b6cb4255> in new_log_interval_event(self, run_states)
     67     # 改写的事件方法，参数列表务必与PaddleHub内置的相应方法保持一致
     68     print("This is the new log_interval_event!")
---> 69     scores, avg_loss, run_speed = calculate_metrics(self,run_states)
     70     record_value(scores, avg_loss, run_speed)
     71 
<ipython-input-10-fc50b6cb4255> in calculate_metrics(self, run_states)
     36     run_speed = run_step / run_time_used
     37 
---> 38     scores = OrderedDict()
     39     f1 = calculate_f1_macro(all_infers, all_labels)
     40     scores["f1_macro"] = f1
NameError: name 'OrderedDict' is not defined`

**Comment by kinghuin** [comment]
请将scores = OrderedDict() 修改为 scores = {}
或添加 from collections import OrderedDict

**Comment by Masterkmp** [comment]
> 
> 
> 请将scores = OrderedDict() 修改为 scores = {}
> 或添加 from collections import OrderedDict
你好，修改后重启运行依然报错，信息如下：
`[2020-09-17 11:03:06,494] [    INFO] - Strategy with warmup, linear decay, slanted triangle learning rate, weight decay regularization, 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
[2020-09-17 11:03:06,549] [    INFO] - Try loading checkpoint from hub_ernie_text_cls_demo/ckpt.meta
[2020-09-17 11:03:06,549] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-09-17 11:03:06,628] [    INFO] - PaddleHub finetune start

This is the new log_interval_event!

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<ipython-input-9-33eafd68b5ee> in <module>
----> 1 run_states = cls_task.finetune_and_eval()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    943 
    944     def finetune_and_eval(self):
--> 945         return self.finetune(do_eval=True)
    946 
    947     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    964                 while self.current_epoch <= self.config.num_epoch:
    965                     self.config.strategy.step()
--> 966                     run_states = self._run(do_eval=do_eval)
    967                     self.env.current_epoch += 1
    968 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
   1222                 if self.is_train_phase:
   1223                     if self.current_step % self.config.log_interval == 0:
-> 1224                         self._log_interval_event(period_run_states)
   1225                         global_run_states += period_run_states
   1226                         period_run_states = []
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    708                     func(*args)
    709                 else:
--> 710                     partial(func, self)(*args)
    711 
    712         return hook_function
<ipython-input-8-3b7ae1e3e8c4> in new_log_interval_event(self, run_states)
     69     print("This is the new log_interval_event!")
     70     scores, avg_loss, run_speed = calculate_metrics(self,run_states)
---> 71     record_value(scores, avg_loss, run_speed)
     72 
     73 # 利用Hook改写PaddleHub内置_log_interval_event实现，需要2步(假设task已经创建好)
<ipython-input-8-3b7ae1e3e8c4> in record_value(evaluation_scores, loss, s)
     50 def record_value(evaluation_scores, loss, s):
     51     tb_writer.add_scalar(
---> 52         tag="Loss_{}".format(self.phase),
     53         scalar_value=loss,
     54         global_step=self._envs['train'].current_step)
NameError: name 'self' is not defined`

**Comment by kinghuin** [comment]
Hi, 非常感谢您的反馈。我们重新维护了hook的文档，请您参考[新的hook文档](https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/Secondary_development/hook.md) 去掉record_value函数

**Comment by Masterkmp** [comment]
> 
> 
> Hi, 非常感谢您的反馈。我们重新维护了hook的文档，请您参考[新的hook文档](https://github.com/PaddlePaddle/PaddleHub/wiki/%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9Task%E5%86%85%E7%BD%AE%E6%96%B9%E6%B3%95%EF%BC%9F) 去掉record_value函数

### 谢谢回复，我跑了新的hook文档，例子是没问题的，可以正常跑完，但是在我的自定义数据集上跑了报错了，我的数据集不是二分类的而是多分类的，是不是重写了没有覆盖呢？
**以下是我的代码部分：**
```python
import time
from collections import OrderedDict
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, fbeta_score
import numpy as np
import paddlehub as hub

def calculate_f1_np(preds, labels):
    preds = np.array(preds)
    labels = np.array(labels)
    f1_macro=precision_score(labels, preds, average='macro')
    return f1_macro

def calculate_metrics(self, run_states):
    loss_sum = acc_sum = run_examples = 0
    run_step = run_time_used = 0
    all_labels = np.array([])
    all_infers = np.array([])

    for run_state in run_states:
        run_examples += run_state.run_examples
        run_step += run_state.run_step
        loss_sum += np.mean(
            run_state.run_results[-1]) * run_state.run_examples
        acc_sum += np.mean(
            run_state.run_results[2]) * run_state.run_examples
        np_labels = run_state.run_results[0]
        np_infers = run_state.run_results[1]
        all_labels = np.hstack((all_labels, np_labels.reshape([-1])))
        all_infers = np.hstack((all_infers, np_infers.reshape([-1])))

    run_time_used = time.time() - run_states[0].run_time_begin
    avg_loss = loss_sum / run_examples
    run_speed = run_step / run_time_used
    scores = OrderedDict()
    f1_macro= calculate_f1_np(all_infers, all_labels)
    scores["f1_macro"] = f1_macro
    return scores, avg_loss, run_speed

def new_log_interval_event(self, run_states):
    # 改写的事件方法，参数列表务必与PaddleHub内置的相应方法保持一致
    scores, avg_loss, run_speed = calculate_metrics(self, run_states)
    formatted_scores = ", ".join(["%s: %.5f"%(key, value) for key, value in scores.items()])
    print("[new_log_interval_event] step %d / %d: loss=%.5f %s[step/sec: %.2f]" %
            (self.current_step, self.max_train_steps, avg_loss,
                formatted_scores, run_speed))
cls_task.delete_hook(hook_type="log_interval_event", name="default")
cls_task.add_hook(hook_type="log_interval_event", name="new_log_interval_event", func=new_log_interval_event)
print(cls_task.hooks_info())
```

**这部分运行结果如下：**
```bash
`[2020-09-17 15:53:20,621] [    INFO] - Delete hook log_interval_event:default successfully
[2020-09-17 15:53:20,623] [    INFO] - Add hook log_interval_event:new_log_interval_event successfully

hook_type: log_interval_event{
 name: new_log_interval_event{
  def new_log_interval_event(self, run_states):
      scores, avg_loss, run_speed = calculate_metrics(self, run_states)
      formatted_scores = ", ".join(["%s: %.5f"%(key, value) for key, value in scores.items()])
      print("[new_log_interval_event] step %d / %d: loss=%.5f %s[step/sec: %.2f]" %
              (self.current_step, self.max_train_steps, avg_loss,
                  formatted_scores, run_speed))
  
 }
}
```
`
**但是在run的时候报错了，现在执行**
`run_states = cls_task.finetune_and_eval()`
**报错信息如下：**
``` bash
`[2020-09-17 15:53:28,511] [    INFO] - Strategy with warmup, linear decay, slanted triangle learning rate, weight decay regularization, 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
[2020-09-17 15:53:28,564] [    INFO] - Try loading checkpoint from hub_ernie_text_cls_demo/ckpt.meta
[2020-09-17 15:53:28,565] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-09-17 15:53:28,614] [    INFO] - PaddleHub finetune start
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

[new_log_interval_event] step 10 / 2029: loss=2.03818 f1_macro: 0.09080[step/sec: 3.20]
[new_log_interval_event] step 20 / 2029: loss=1.99851 f1_macro: 0.09585[step/sec: 4.04]
[new_log_interval_event] step 30 / 2029: loss=1.93053 f1_macro: 0.09630[step/sec: 4.04]
[new_log_interval_event] step 40 / 2029: loss=1.85964 f1_macro: 0.07410[step/sec: 4.04]

[2020-09-17 15:53:41,701] [    INFO] - Evaluation on dev dataset start

[new_log_interval_event] step 50 / 2029: loss=1.85176 f1_macro: 0.05865[step/sec: 4.03]

share_vars_from is set, scope is ignored.

---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-11-de25dff1885d> in <module>
      1 #开始Finetune
----> 2 run_states = cls_task.finetune_and_eval()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    943 
    944     def finetune_and_eval(self):
--> 945         return self.finetune(do_eval=True)
    946 
    947     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    964                 while self.current_epoch <= self.config.num_epoch:
    965                     self.config.strategy.step()
--> 966                     run_states = self._run(do_eval=do_eval)
    967                     self.env.current_epoch += 1
    968 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
   1230 
   1231                     if do_eval and self.current_step % self.config.eval_interval == 0:
-> 1232                         self._eval_interval_event()
   1233 
   1234                 self._run_step_event(step_run_state)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    706             for name, func in self._hooks[hook_type].items():
    707                 if inspect.ismethod(func):
--> 708                     func(*args)
    709                 else:
    710                     partial(func, self)(*args)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _default_eval_interval_event(self)
    859 
    860     def _default_eval_interval_event(self):
--> 861         self.eval(phase="dev")
    862 
    863     def _default_run_step_event(self, run_state):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in eval(self, phase, load_best_model)
   1009             self._eval_start_event()
   1010             run_states = self._run()
-> 1011             self._eval_end_event(run_states)
   1012             return run_states
   1013 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    706             for name, func in self._hooks[hook_type].items():
    707                 if inspect.ismethod(func):
--> 708                     func(*args)
    709                 else:
    710                     partial(func, self)(*args)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _default_eval_end_event(self, run_states)
    794             run_states (object): the results in eval phase
    795         """
--> 796         eval_scores, eval_loss, run_speed = self._calculate_metrics(run_states)
    797         if 'train' in self._envs:
    798             self.vdl_writer.add_scalar(
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/classifier_task.py in _calculate_metrics(self, run_states)
    137                 raise ValueError(
    138                     "Unknown metric: %s! The chosen metrics must be acc, f1, presicion or recall."
--> 139                     % metric)
    140 
    141         return scores, avg_loss, run_speed
**ValueError: Unknown metric: default! The chosen metrics must be acc, f1, presicion or recall.**`
```
**从结果来看，好像自定义指标失败了，没有覆盖原本的代码。**

**Comment by kinghuin** [comment]
您已经成功改写了log_interval_event，但还没有改写eval_end_event，错误发生在 self._eval_end_event(run_states)
请您继续改写其它事件hook

**Comment by Masterkmp** [comment]
> 
> 
> 您已经成功改写了log_interval_event，但还没有改写eval_end_event，错误发生在 self._eval_end_event(run_states)
> 请您继续改写其它事件hook
感谢解答！问题已解决！

**Comment by Masterkmp** [comment]
> 
> 
> 您已经成功改写了log_interval_event，但还没有改写eval_end_event，错误发生在 self._eval_end_event(run_states)
> 请您继续改写其它事件hook

### 感谢解答，问题已解决！
### 另外，如果想记录best model，我的是多个指标可以自定义吗，paddlehub默认记录第一个指标为best model的记录标准。
`[2020-09-17 18:13:02,939] [    EVAL] - [dev dataset evaluation result] loss=0.82451 f1_macro=0.59680 f1_micro=0.69982 re_macro=0.58674 re_micro=0.69982 pre_macro=0.67826 pre_micro=0.69982 [step/sec: 13.22]
[2020-09-17 18:13:02,941] [    EVAL] - best model saved to hub_ernie_text_cls_demo/best_model **[best f1_macro=0.59680]`**

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
