### ISSUE TITLE
请问paddlehub如何使用Early stop?

### ISSUE THREAD

**Issue by Masterkmp** [PaddlePaddle/PaddleFormers#912]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

**Comment by Steffy-zxf** [comment]
你好！目前PaddleHub 还未支持early stop， 需要自行实现。early stop在hub 未来版本会支持。自行实现需要了解下，paddlehub 训练的过程，代码：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/paddlehub/finetune/task/base_task.py#L1163

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
