### ISSUE TITLE
模块，每次能不能只下载一次，我每次运行都要下载一次

### ISSUE THREAD

**Issue by sunjunling666** [PaddlePaddle/PaddleFormers#915]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？
- 什么样的场景下需要该特性？
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案
你好，就是我运行个hub.模块。每次运行，都要下载，能不能每次只下载一次呀
？？请求哥哥姐姐们帮助一下

**Comment by Masterkmp** [comment]
如果是在AIStudio上，你新建一个项目，有代码提示你需不需要安装到你的环境，下次直接import就可以。

**Comment by sunjunling666** [comment]
还有疑问，实在搞不懂了
，但是那个模块安装过了，再次运行，还是显示安装呀

**Comment by sunjunling666** [comment]
谢谢你呀，真的有点不明白

**Comment by sunjunling666** [comment]
我是在一个程序中，里面有个加载向，每次都要加载，不知道怎么把它去掉

**Comment by sunjunling666** [comment]
只有在AIstudio中吗？能不能指点一下

**Comment by GT-ZhangAcer** [comment]
截图、代码什么都没有，仅凭几句话别人很难猜出你的问题。
不管是QQ群还是GitHub，在提问时也要为别人考虑，这样才能会有人原因为你答疑，谢谢。

**Comment by wxd11011** [comment]
确实存在这个现象，每次运行，模型都要重新下载一遍，不管是在python程序中通过paddlehub调用还是在shell中直接调用hub命令，皆如此。
程序版本：
windows 10
python 3.8.3
paddlehub              1.8.2
paddlepaddle-gpu       1.8.5.post107

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
