### ISSUE TITLE
模块运行问题

### ISSUE THREAD

**Issue by sunjunling666** [PaddlePaddle/PaddleFormers#916]
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 您想要增加什么新特性？模块加载问题，同一个程序，每次运行，都要下载吗？
- 什么样的场景下需要该特性？做训练的时候，节省时间
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？不能提高速度
- 增加该特性，PaddleHub可能需要变化的部分。就是用第一次下载的模块，以后每次运行，就不要在下载
- 如果可以的话，简要描述下您的解决方案：运行第一次，下载一次，运行第二次的时候，就可以在前一次的下载好的模块，直接使用，有助于提高速度。帮个忙，解决一下，由于可能没有读模块的作用，删除了，希望贵公司体谅。

**Comment by Steffy-zxf** [comment]
你好！能详细描述下你的需求背景、运行环境 吗？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
