### ISSUE TITLE
Paddle Hub 如何在后台运行？

### ISSUE THREAD

**Issue by xiaomochen520** [PaddlePaddle/PaddleFormers#923]
Paddle Hub （以下简称PHub）目前好像不允许后台运行，我查了文档，里没有说明。经过试验，好像只有使用nohup、setsid 之类的命令才可以让其后台运行。
众所周知，在生产环境中部署，如果不支持后台运行的话，则会很麻烦，虽然可以使用nohop、setsid 命令去完成这件事，但是总感觉不是很优雅

**Comment by Steffy-zxf** [comment]
你好！感谢反馈！目前PaddleHub 没有直接的命令可以后台运行。可以通过nohop等命令后台运行。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
