### ISSUE TITLE
Ernie 相关

### ISSUE THREAD

**Issue by dickobe** [PaddlePaddle/PaddleFormers#929]
问下Ernie和ernie-tiny embedding 的维度是多少呢？我看通过get_embedding 取ernie的embedding的维度是768，ernie-tiny的是1024？ 是这样吗？如果是为什么ernie-tiny的维度比ernie还要更大呢？

**Comment by Steffy-zxf** [comment]
你好！从ERNIE module取出的 embedding 信息，参考：https://www.paddlepaddle.org.cn/hubdetail?name=ERNIE&en_category=SemanticModel
![image](https://user-images.githubusercontent.com/48793257/94383404-8689a800-0172-11eb-9d7e-565694465e66.png)

从ernie tiny module取出的 embedding 信息，参考：https://www.paddlepaddle.org.cn/hubdetail?name=ernie_tiny&en_category=SemanticModel
![image](https://user-images.githubusercontent.com/48793257/94385460-d5860c00-0177-11eb-98eb-06f56abe9a20.png)

ernie tiny只有3层Transformer结构，而ernie 有12层Transformer结构。所以ernie tiny hidden_size 更大些。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
