### ISSUE TITLE
运行流程问题请教

### ISSUE THREAD

**Issue by foreversolar** [PaddlePaddle/PaddleFormers#93]
看官方给出的demo
在finetune_and_eval()之后，在预测的时候又把前面的所有流程走了一遍，最后这个finetune_and_val()改成了predict(), 那这时候predict使用的难道不是预训练的模型么。
看到代码中注释了一句finetune之后会自动保存，请问这个是保存到哪了呢？在使用新模型的时候还是写module = hub.Module(name="ernie")吗

**Comment by Steffy-zxf** [comment]
感谢反馈！
1. 在finetune_and_eval()之后，在预测的时候又把前面的所有流程走了一遍，最后这个finetune_and_val()改成了predict(), 那这时候predict使用的难道不是预训练的模型么？

   回复：预测脚本predict.py用到的模型参数是finetune时加载的预训练模型在目标数据集（比如 文本分类demo中的chnsenticorp数据集）再训练更新的参数

2. 看到代码中注释了一句finetune之后会自动保存，请问这个是保存到哪了呢？

   回复：加载的预训练模型在目标数据集上更新的参数保存在fintune时指定checkpoint文件中。

3. 在使用新模型的时候还是写module = hub.Module(name="ernie")吗？

   回复：新模型是指finetune之后保存的模型参数吗？如果是的话，预测时想要加载对应脚本需要module = hub.Module(name="ernie") （finetune时使用的预训练模型也是ernie），并且需要指定hub.RunConfig方法中的checkpoint_dir参数为finetune时指定的checkpoint_dir。
