### ISSUE TITLE
从昨天开始模型下载速度贼慢

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/PaddleFormers#932]
大概一分钟进展0.01？……也可能没有进展，可以看一下吗？
![image](https://user-images.githubusercontent.com/42665925/94400313-7803b680-019b-11eb-936f-46236891d9b5.png)

**Comment by wxl1351641822** [comment]
急，在线等

**Comment by Steffy-zxf** [comment]
你好！一般网速慢的话，是网络问题。试试重新下载？另外你是在什么平台上下载呢，是 aistudio上运行吗？

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
