### ISSUE TITLE
文本匹配 PointwiseTextMatchingTask 中，预测时显示Variable's shape does not match

### ISSUE THREAD

**Issue by Echo0117** [PaddlePaddle/PaddleFormers#935]
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.8.4，PaddlePaddle1.8.0
2）系统环境：aistudio，python3.7版本

训练PointwiseTextMatchingTask后，预测时显示如下错误：

**RuntimeError: Variable's shape does not match, the Program requires a parameter with the shape of ((32768, 2)), while the loaded parameter (namely [ matching_out_w ]) has a shape of  ((256, 2)).**

![图片](https://user-images.githubusercontent.com/54064209/94503819-ef882300-0239-11eb-89ad-86352d8137ef.png)

已经将checkpoint_dir设置成和训练时一样。
    
config = hub.RunConfig(use_cuda=True, 
                        num_epoch=50, 
                        batch_size=32, 
                        strategy=strategy, 
                        checkpoint_dir=checkpoint_dir
                        )

**Comment by Steffy-zxf** [comment]
你好！预测和fine-tune 参数设置一致吗？比如`context`接口`max_seq_len` 和 数据集设置的`max_seq_len`参数。finetune 和 predict的区别仅在于task.finetune_and_eval()换成task.predict()以及预测时需要定义相应的数据。

**Comment by Echo0117** [comment]
之前的问题已经解决了，谢谢～
我想再请问一下，paddle 1.8 会更新能支持 cuda 10.2 的版本吗，有的话大概是什么时候呢？

Steffy-zxf <notifications@github.com> 于2020年10月3日周六 上午8:44写道：

**Comment by Steffy-zxf** [comment]
你好！paddle 1.8已经支持 cuda 10.2，参考 https://www.paddlepaddle.org.cn/install/quick

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
