### ISSUE TITLE
paddleOCR的迁移finetune问题

### ISSUE THREAD

**Issue by Zaoyee** [PaddlePaddle/PaddleFormers#936]
您好，

请问基于`ocr = hub.Module(name="chinese_ocr_db_crnn_server")`如何进行简单的迁移训练。
我尝试了`ocr.context(.....)`似乎没有定义这个函数。
在源码中，需要提取的是`self.cls(rec)_predictor, self.cls(rec)_input_tensor, self.cls(rec)_out_tensor`吗？
如果可以，能简要描述下这个类型module的方法吗？

**Comment by Steffy-zxf** [comment]
你好！PaddleHub OCR module 不支持finetune。如有需要，请参考 https://github.com/PaddlePaddle/PaddleOCR

`self.cls(rec)_predictor, self.cls(rec)_input_tensor, self.cls(rec)_out_tensor` 是用于ocr预测，具体说明参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/python_infer_cn.html#paddlepredictor

**Comment by Steffy-zxf** [comment]
你好好，此issue在近两月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题。
