### ISSUE TITLE
关于ace2p处理

### ISSUE THREAD

**Issue by zandls-lovelulu** [PaddlePaddle/PaddleFormers#938]
能不能输出下面的这些数据呢，以下是json文件，，或者有什么办法能够可以输出这个json文件呢，请指教
![无标题](https://user-images.githubusercontent.com/71753992/94988375-44f86300-059f-11eb-8eb2-bb14bf7bd0ce.png)

**Comment by zandls-lovelulu** [comment]
![无标题](https://user-images.githubusercontent.com/71753992/94988385-5c375080-059f-11eb-9031-2e50b065f71e.png)

**Comment by Steffy-zxf** [comment]
你好！你可以将上述结果在程序中以`json.dumps`保存，以`json.loads`读取。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
