### ISSUE TITLE
在proxy情况下下载paddlehub模型

### ISSUE THREAD

**Issue by Jiannan28** [PaddlePaddle/PaddleFormers#939]
请问在网络有proxy的情况下如何使用hub.Module（）或hub install来下载senta的模型呢，https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.0.0/demo/senta/senta_demo.py

版本paddlehub 1.8.2
paddlepaddle 1.8.5
windows10

**Comment by Steffy-zxf** [comment]
你好！只要能够访问https://www.paddlepaddle.org.cn/hub 网站，即可下载PaddleHub预训练模型Module。

**Comment by Jiannan28** [comment]
请问这里边的paddlehub的模型https://www.paddlepaddle.org.cn/hublist?filter=en_category&value=SentimentAnalysis 在有代理的情况下怎么下载并且在本地配置呢？ 如果用hub.install会被block掉。感谢！

**Comment by ShenYuhan** [comment]
先把代理关了，再下载就可以了

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
