### ISSUE TITLE
目前是否支持PDF格式文件的识别功能？

### ISSUE THREAD

**Issue by JerryXue0609** [PaddlePaddle/PaddleFormers#943]
- 您想要增加什么新特性？
  PDF格式文件的识别
- 什么样的场景下需要该特性？
  扫描仪扫描的成品PDF需要识别
- 没有该特性的条件下，PaddleHub目前是否能间接满足该需求？
  否
- 增加该特性，PaddleHub可能需要变化的部分。
- 如果可以的话，简要描述下您的解决方案

**Comment by Steffy-zxf** [comment]
你好！目前PaddleHub 有支持图片文件识别的module，参考：https://www.paddlepaddle.org.cn/hublist?filter=en_category&value=TextRecognition

可以试试将pdf文件转为图像，之后用ocr module识别文字。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
