### ISSUE TITLE
语义相似度匹配任务

### ISSUE THREAD

**Issue by TianTian-O1** [PaddlePaddle/PaddleFormers#95]
在做语义相似度匹配任务时，如果数据很多的话，predict.py 里面data的添加是怎么一种策略呢，如何能够快速匹配相似语义。

**Comment by Steffy-zxf** [comment]
感谢反馈！数据很多很多的情况下，预测时可以先将待预测的数据放在文件，利用程序读入数据，之后调用task.predict()接口，即可以进行预测。可以参考PaddleHub提供的检索式问答任务的预测文件写法。https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.0.0/demo/qa_classification/predict.py

**Comment by TianTian-O1** [comment]
好的，谢谢


 
---原始邮件---
发件人: "Steffy-zxf"<notifications@github.com>
发送时间: 2019年7月30日(星期二) 上午9:51
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"TianZhenGG"<410771376@qq.com>;
主题: Re: [PaddlePaddle/PaddleHub] 语义相似度匹配任务 (#95)



感谢反馈！数据很多很多的情况下，预测时可以先将待预测的数据放在文件，利用程序读入数据，之后调用task.predict()接口，即可以进行预测。可以参考PaddleHub提供的检索式问答任务的预测文件写法。
