### ISSUE TITLE
paddlehub每次运行，模型都要重新下载一遍

### ISSUE THREAD

**Issue by wxd11011** [PaddlePaddle/PaddleFormers#952]
paddlehub每次运行，模型都要重新下载一遍，不管是在python程序中通过paddlehub调用还是在shell中直接调用hub命令，皆如此。

程序版本：
windows 10
python 3.8.3
paddlehub 1.8.2
paddlepaddle-gpu 1.8.5.post107

**Comment by Steffy-zxf** [comment]
你好！是什么module？代码是什么样的？

**Comment by wxd11011** [comment]
@Steffy-zxf 
你好！在Windows Terminal(版本: 1.3.2651.0)中直接调用如下命令使用yolov3_coco2017模型对图片进行目标检测时，都会重新下载安装一次该模型：
`hub run yolov3_coco2017 --input_path ".\a.jpg"`
在python3.8.3中运行以下代码段时亦然：
`
import paddlehub as hub
mYolov3=hub.Module(name="yolov3_coco2017")
tImg="c:/users/paddleuser/desktop/a.jpg"
input_dict={"image":[tImg,]}

rlt=mYolov3.object_detection(data=input_dict)
for i in rlt:
    print(i['path'])
    print(i['data'])
`

在次运行之前已经调用
`hub install yolov3_coco2017`
命令正确安装该模型。

第二次（以及后续）运行以上shell命令以及python程序之前，在Windows Terminal(版本: 1.3.2651.0)中执行以下命令：
hub list
会有以下输出：
+------------------------+-------------------------------------------------------+
|`      ModuleName        |                   Path                                                        `|
+------------------------+-------------------------------------------------------+
|yolov3_darknet_coco2  |C:\Users\paddleuser\paddlehub\modules\yolov3  |
|`017                               |_coco2017                                                                 `|
+------------------------+-------------------------------------------------------+

另测试过在poweshell以及windows系统的CMD命令提示符窗口中调用上述hub指令（分别以标准用户模式及管理员模式），程序行为相同。

另测试过在PaddleHub管网上列出的其它模型，情况相同。

**Comment by haoyuying** [comment]
yolov3_coco2017是一个较早的hub module版本，存在的问题已经在升级版本yolov3_resnet50_vd_coco2017解决，建议使用这个模型或者其他paddlehub1.8版本的检测模型。

**Comment by wxd11011** [comment]
@haoyuying 
谢谢！确实换用新版本的hub模型后，症状消失了。但还是不太明白这个问题与模型版本之间存在怎样的关系？

**Comment by haoyuying** [comment]
yolov3_coco2017和yolov3_resnet50_vd_coco2017在构建方法上不相同，yolov3_coco2017使用的是较旧的版本的paddlehub，而yolov3_resnet50_vd_coco2017是可以适配paddlehub 1.8.2版本的paddlehub的，你可以进入本地.paddlehub/module/yolov3_coco2017 和.paddlehub/module/yolov3_resnet50_vd_coco2017 目录下查看两个代码在构建网络时的差异。yolov3_coco2017 仅提供了数据前处理和后处理的部分，组网代码内嵌在较老版本的paddlehub中，而yolov3_resnet50_vd_coco2017中module.py是组网代码，所以paddlehub 1.8.2适用的是yolov3_resnet50_vd_coco2017这种方式的组网方式。

**Comment by wxd11011** [comment]
@haoyuying 
非常感谢您提供的帮助！谢谢！
