### ISSUE TITLE
提问-关于paddlehub的人物分割如何提升检测速度

### ISSUE THREAD

**Issue by fuchunming11** [PaddlePaddle/PaddleFormers#953]
想法:想通过paddlehub的deeplabv3p_xception65_humanseg实现**实时**的人物抠图换背景
问题：本地使用2080ti ，单纯预测每张图片耗时大约0.16s，实际效果卡卡的，想问下有没有什么加速方法？谢谢大家

**Comment by haoyuying** [comment]
网络比较大时实行实时人像抠图确实会比较卡，如果非必要必须使用deeplabv3p_xception65_humanseg，可以尝试使用humanseg_lite等小模型来体验实时人物抠图效果。

**Comment by fuchunming11** [comment]
谢谢，换了humanseg_mobile ，速度上来了，可以达到实时的效果
