### ISSUE TITLE
请问服务化部署是如何加载模型的？

### ISSUE THREAD

**Issue by tyy2tyy** [PaddlePaddle/PaddleFormers#954]
我发现paddlehub的功能非常强大，开发人员都很厉害。在研究代码时，我发现我不是很理解服务器是怎样加载模型并使用模型进行预测，请问能给我一些提示吗？

**Comment by Steffy-zxf** [comment]
你好！你指的加载模型是，是指`hub.Module(name=***)`加载module ，还是指module加载预训练模型参数呢？

**Comment by tyy2tyy** [comment]
加载训练好的模型，比如说我想进行文字识别，那么服务化部署时是怎么样加载它的，才能在test时添加图片位置即可得到检测结果

**Comment by Steffy-zxf** [comment]
关于PaddleHub ocr 服务部署，可以参考文档：https://www.paddlepaddle.org.cn/hubdetail?name=chinese_ocr_db_crnn_mobile&en_category=TextRecognition

服务化部署：
![image](https://user-images.githubusercontent.com/48793257/95933930-411bda80-0e02-11eb-8657-601c66f74f11.png)

关于PaddleHub Serving 参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/serving.md

**Comment by tyy2tyy** [comment]
好的，谢谢

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
