### ISSUE TITLE
LAC自定义词典干预分词问题请教

### ISSUE THREAD

**Issue by aofch** [PaddlePaddle/PaddleFormers#96]
自定义词典 user.dict 中的格式如下：
单词\t单词词性\t单词词频

这个单词词频设置多少合适呢，有参考的大小吗？

例如句子：吉利新帝豪标配搪塑中控实际是注塑
默认情况下分成了
['吉利新帝豪标配搪塑中控', '实际', '是', '注塑']

在 user.dict 中添加
吉利新帝豪      n       30000
后，变成👇：
['吉利新帝豪', '标配搪塑中控', '实际', '是', '注塑']

然后再次添加
标配      vn       30000
就不起作用了

**Comment by Halfish** [comment]
hi @aofch 这个问题是这样，因为用户词典直接替换的话规则太强，所以代码内部会算一个语言模型打分。直观来说，如果用户词典替换后太不通顺，就忽略这个词。

比如你这里的“标配”，会导致新切分出“吉利新帝豪” 和 “搪塑中控”，那这两个新词默认词频是 0，这样这句话就不“通顺了”。

可以这样添加：
```text
吉利新帝豪	nt	3000
标配	vn	3000
搪塑中控	nt	3000
```
