### ISSUE TITLE
安装paddlehub后import卡住

### ISSUE THREAD

**Issue by AOZMH** [PaddlePaddle/PaddleFormers#97]
您好！
我在linux系统上安装了paddlepaddle 1.5.1 和 paddlehub 1.0.2。但是我import paddlehub时会卡住，手动中断后显示卡在了connect某个socket一步。
请问这是否和 https://github.com/PaddlePaddle/PaddleHub/issues/69 是同样的错误？应如何解决？
![4c07edf9cba683f0fbd0132aabdf756](https://user-images.githubusercontent.com/49521559/62226965-aa762000-b3ed-11e9-8eaf-d4c65dc089b9.png)

**Comment by Steffy-zxf** [comment]
感谢反馈！您的机器可以访问外网吗？尝试以下代码：
```python
import requests

res = requests.get('http://paddlepaddle.org.cn/paddlehub/search', {'word': 'ernie', 'type': 'Module'})
print(res)

# the common result is like this:
# <Response [200]>
```
因为PaddleHub中的预训练模型和预置数据集都需要通过服务端进行下载，因此我们默认用户得有外网权限。

**Comment by AOZMH** [comment]
谢谢回复！我这边访问外网确实有些问题，我修复一下之后如果还有问题反馈给您。

**Comment by Steffy-zxf** [comment]
PaddleHub 最新版本1.1.1现已支持离线运行。可以先卸载之前的PaddleHub，安装最新版1.1.1 PaddleHub。
