### ISSUE TITLE
关于paddlehub里的模型部署为服务后并发的疑问

### ISSUE THREAD

**Issue by fish-hello** [PaddlePaddle/PaddleFormers#976]
1）PaddleHub和PaddlePaddle版本：PaddleHub1.8.2，PaddlePaddle1.8.4
2）系统环境：Windows 7，python 3.7
- 复现信息：
本人发现模型（目标检测）：yolov3_resnet50_vd_coco2017，版本为1.0.1，在部署为服务后，可能有并发的问题，望答疑。

问题在processor.py

![image](https://user-images.githubusercontent.com/72905070/96833875-abbcbe00-1473-11eb-943b-0098b5c48c92.png)

调用时的控制台打印，每次请求都是0开始计数

![image](https://user-images.githubusercontent.com/72905070/96833957-c727c900-1473-11eb-94c2-4b40a4e20efe.png)

后面的draw_bounding_box_on_image方法使用这个org_img_path路径：

![image](https://user-images.githubusercontent.com/72905070/96833983-d27af480-1473-11eb-8a1f-16dcaefea986.png)

**请问是否会出现文件被覆盖的问题，当并访问的时候？**

本人临时加了全局计数id，拼在文件名上，用于防止文件被覆盖

![image](https://user-images.githubusercontent.com/72905070/96834065-f2121d00-1473-11eb-9a9b-3cf943491e5a.png)

本人是一个Java web开发者，刚接触Python两三周，望指点。

**Comment by ShenYuhan** [comment]
实际上用部署后的模型，是不需要保存本地的，因此这个逻辑是可以跳过的

**Comment by haoyuying** [comment]
Since you haven't replied for more than a year, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过一年未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Comment by haoyuying** [comment]
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。
