### ISSUE TITLE
服务器部署成功POST结果异常？

### ISSUE THREAD

**Issue by 1290726334** [PaddlePaddle/PaddleFormers#979]
返回结果是
{"msg":"Module chinese_ocr_db_crnn_server is not available.","results":"","status":"-1"}
![image](https://user-images.githubusercontent.com/16836773/97065988-fc532900-15e3-11eb-84d3-3c3adea0ae42.png)

**Comment by suntao2015005848** [comment]
你的怎么解决掉

**Comment by diandian11** [comment]
有解决办法吗
