### ISSUE TITLE
windows运行ernie分类程序，出现报错Windows not support stack backtrace yet.

### ISSUE THREAD

**Issue by natureLanguageQing** [PaddlePaddle/PaddleFormers#98]
windows运行paddlehub的ernie的任务出现对cls_task.finetune_and_eval()不支持

**Comment by Steffy-zxf** [comment]
感谢反馈！方便贴下错误提示吗？PaddleHub版本是多少呢？

**Comment by Steffy-zxf** [comment]
您好，此issue在近一个星期内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，
我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddleHub的支持!
